### ISSUE TITLE
invalid CSV regional data

### ISSUE THREAD

**Issue by FabrizioML73** [pcm-dpc/COVID-19#1]
It looks like the regional data (csv) are not reporting the correct region. Emilia-Romagna region (code 08) is reported to have 79 active  cases on march 6th, while Bolzano seems to have 870 active cases.

**Comment by FabrizioML73** [comment]
This seems to be true for March 6  files only, on both region and province

**Comment by umbros** [comment]
Thank you! We replace with the correct one!
