### ISSUE TITLE
Dati non aggiornati

### ISSUE THREAD

**Issue by r00t91** [pcm-dpc/COVID-19#10]
A 2 ore dalla raccolta dati (che avviene alle ore 17:00) e trascorsa 1 ora dall'inizio della conferenza stampa, i dati risultano non aggiornati. Sia per l'assenza delle schede PDF, sia per i dati sulla mappa (nonostante sia presente la data di aggiornamento ad oggi ore 18:00).
![Cattura](https://user-images.githubusercontent.com/61915537/76149975-b32a8500-60a5-11ea-9638-c5cfe2f8972f.PNG)

**Comment by umbros** [comment]
@r00t91 i dati sono in fase di aggiornamento. Stiamo migliorando i processi per essere tempestivi.

**Comment by r00t91** [comment]
Grazie, intanto potreste caricare la scheda riepilogativa manualmente.
