### ISSUE TITLE
Disaccordo con i Tamponi e testati tra il 17 e il 18 Dicembre 

### ISSUE THREAD

**Issue by guixmax** [pcm-dpc/COVID-19#1000]
Sia i tamponi che i casi testati del Piemonte mostrano un incongruenza al passare dal 17 a 18 Dicembre. 
Decrescono entrambe mentre viene dichiarato un incremento quotidiano  di 9493 unità.

Non mi sembra di avere visto una nota al riguardo del Piemonte

**Tipo di richiesta**:  richiesta di informazione | richiesta di dati | suggerimento di miglioramento (documentazione, label, _ecc_) | relativo alla pagina grafica

**Comment by umbros** [comment]
#998
