### ISSUE TITLE
Errore sui casi testati del 18/12/20

### ISSUE THREAD

**Issue by ornolio** [pcm-dpc/COVID-19#1001]
Tipo di issue:

- [ ] Dati mancanti o errati 
- [ ] Errore nella documentazione 
- [ ] Errore or mancanza nella dashboard 
- [ ] Problemi di visualizzazione nella dashboard 

- Regione:
- Provincia: 

## Riassunto

Il totale dei casi testati del 18/12 sono inferiore a quelli del 17/12:

           | T. casi testati | diff
18-dic | 14.150.088 | -96.651
17-dic | 14.246.739 | 80.778
16-dic | 14.165.961 | 80.502
15-dic | 14.085.459 | 62.707
14-dic | 14.022.752 | 

idem per i tamponi

           | T. tamponi | diff
18-dic | 24.815.520 | -53.030
17-dic | 24.868.550 | 185.320
16-dic | 24.683.230 | 201.040
15-dic | 24.482.190 | 162.880
14-dic | 24.319.310 | xxxxxxxxxxx

**Attuale:**

**Comment by umbros** [comment]
#998
