### ISSUE TITLE
Nota Piemonte

### ISSUE THREAD

**Issue by Paulsword** [pcm-dpc/COVID-19#1003]
Mi devo essere perso la circolare del ministero con la nuova definizione di casi sulla base della quale il Piemonte oggi (unica regione) depenna 2590 casi.
Qualcuno mi sa aiutare?

**Comment by Paulsword** [comment]
Già che ci siamo, avete una stima delle persone testate oggi in Piemonte, visto il ricalcolo di oltre 100mila sul totale?

**Comment by Paulsword** [comment]
Per non dire delle -57mila persone testate in Basilicata. Help please

**Comment by MicheleAlfinito** [comment]
-106675 in Piemonte e -57470 in Basilicata.
E c'è anche la ciliegina sulla torta: Friuli VG 0 (zero)

**Comment by umbros** [comment]
Ciao a tutti, la cosa è riportata sulla nota #998 (per il Piemonte) la stessa linea il Ministero la sta seguendo anche per gli altri dati. Lato DPC stiamo comunicando comunque ogni problema riscontrato sui dati in base alle analisi pre-caricamento.

**Comment by LucaZeta** [comment]
> Ciao a tutti, la cosa è riportata sulla nota #998 (per il Piemonte)

Ce ne fosse una di comunicazione che funziona. Si è superato sia il ridicolo che il pietoso.
