### ISSUE TITLE
Why the recent, simultaneous increase in cases, tests, deaths?

### ISSUE THREAD

**Issue by Jmuccigr** [pcm-dpc/COVID-19#1005]
I notice that there is a recent simultaneous spike in the weekly avg of deaths and cases and testing, which one would normally not expect.

I could understand a spike in cases resulting from a spike in testing, but that shouldn't happen with deaths, which should lag cases.

Any idea what's behind this?

The attached image aligns the three sets of data and the shared spike is evident, though the correction in testing causes those data to fall rapidly out of view. The bars show that the spike is real and would be there were it not for the correction.
<img width="257" alt="spike" src="https://user-images.githubusercontent.com/615115/102696135-1121f680-41fa-11eb-905e-787e9868789a.png">

**Comment by Rabelaiss** [comment]
Sometime Regions add "old" deaths to the count resulting in a number bigger than the expected

**Comment by Jmuccigr** [comment]
Ok, but that doesn’t explain all 3 increasing at once.

**Comment by albar70** [comment]
Hi, there is rather a dip in the data of the week including the 8th December, which is a holiday. So, instead of the usual 2-day reduction of testing and reporting at weekends, on that week there was a 4-day reduction, that explains a below-expectation weekly average of cases, tests and deaths.

**Comment by Jmuccigr** [comment]
> Hi, there is rather a dip in the data of the week including the 8th December, which is a holiday. So, instead of the usual 2-day reduction of testing and reporting at weekends, on that week there was a 4-day reduction, that explains a below-expectation weekly average of cases, tests and deaths.

Not so sure that's the reason.

The 8th was over a week before this blip, which is a long delay. You also don't see much of a change in the rate of decreases during the week of the 8th - in fact deaths **slow** their decline, so that's the opposite direction you'd expect from a reporting issue. If you look at new cases for that period, the 9th is a bit low, which could be the holiday, but the rest of the week looks fine and there's no blip in the 7-day. Besides Wednesdays are sometimes lower than Tuesdays, as Nov 10-11.

Also a one-day dip isn't enough to count for the uptick a week later.

I also don't think the holidays show up in the death totals in other cases, though it's hard to tell. June 2, for example, doesn't seem to show a change in deaths, and you can't see a dip in new cases either.

I'd believe some kind of reporting problem in the system, since the phenomenon is national, but I don't think the holiday explains it.

<img width="1440" alt="Screen Shot 2020-12-21 at 14 09 00" src="https://user-images.githubusercontent.com/615115/102813356-a954e280-4396-11eb-9a43-aa373fc2f6c2.png">

**Comment by albar70** [comment]
But one sees exactly in your graph above that on the week of December 8th you have 3 days with much lower new cases (and tests, and deaths, which one could see in your other graphs), instead of just the Sunday as in all other weeks before and after. The delay of the 7-days average is always there, because of how the average is defined, and the dip in the 7-day average starts exactly when the daily curve shows the anomaly (i.e. Tuesday and Wednesday with anomalously low cases) with respect to the week before, and it disappears exactly one week later, when Tuesday and Wednesday were normal weekdays again.

**Comment by Jmuccigr** [comment]
Yeah, it's possible that it was the holiday, but basically I don't understand why it took over a week to get back on track. If there was a day or two delay, we'd see the 7-day get quickly back on track as those delayed cases were handled. This should be especially true for deaths which will just have a reporting delay. If you look, (1) they show a spike as well in that second week, and (2) they don't normally show much of a holiday effect at all, I don't think.

And, yes, there are three lower days, whereas normally there's one. If you look, I think you'll see that there's the one expected low (Sunday Dec 7), a rise, then a fall on the 9th, then back up again. It's that fall on the 9th that maybe you could say was related to the holiday and represents only one unusually low day. But again why don't those cases appear within a day or two?

Unfortunately the testing data has that correction that means it can't help here.

Anyway, this is probably just idle speculation on my part. :-)
