### ISSUE TITLE
Errore relativo al numero di tamponi 2020-12-17

### ISSUE THREAD

**Issue by leeppolis** [pcm-dpc/COVID-19#1009]
Tipo di issue:

- [x] Dati mancanti o errati `dpc-covid19-ita-andamento-nazionale.csv` `dpc-covid19-ita-andamento-nazionale-latest.csv` `dpc-covid19-ita-andamento-nazionale-20201220.csv` `dpc-covid19-ita-andamento-nazionale-20201219.csv` `dpc-covid19-ita-andamento-nazionale-20201218.csv` `dpc-covid19-ita-andamento-nazionale-20201217.csv`
- [ ] Errore nella documentazione 
- [ ] Errore or mancanza nella dashboard 
- [ ] Problemi di visualizzazione nella dashboard 

- Regione: Italia
- Provincia: n.a.

## Riassunto

Il dato relativo ai tamponi eseguiti il 17/12 (24.635.720) è inferiore rispetto al dato del giorno precedente (24.683.230).

**Attesa:**

Ogni giorno il dato relativo al numero di tamponi effettuati deve essere maggiore o uguale rispetto al giorno precedente.

**Attuale:**

16/12/2020: 24.683.230 tamponi effettuati
17/12/2020: 24.635.720 tamponi effettuati

Tamponi effettuati tra il 16 e il 17 dicembre:

24.635.720 - 24.683.230 = -47.510

**Comment by Primopiano1** [comment]
Il dato corretto da inserire nel csv relativo ai tamponi del 17/12 è 24.868.550

**Comment by xhantos** [comment]
Lo stesso vale per lo stesso per quanto riguarda il numero di tamponi in piemonte e in valle d'aosta: entrambi inferiori al giorno precedente

**Comment by ilTrev** [comment]
> Il dato corretto da inserire nel csv relativo ai tamponi del 17/12 è 24.868.550

@Primopiano1 in questo caso però il problema si sposta sul giorno successivo, visto che il dato per il 18 dicembre è 24815520

**Comment by thecellarguardian** [comment]
Il problema persiste (verificato sul json).

Qualora non fosse disponibile il valore corretto (...) per il 17 dicembre, suggerirei quantomeno di mantenere la consistenza del dataset inserendo un valore interpolato *E* annotando opportunamente la entry per far capire che il valore non è esatto ma solo indicativo.

Avere il valore corretto, chiaramente, sarebbe meglio.

**Comment by AndreaBassi58** [comment]
si il dato è errato ... è possibile aggiornarlo ???

**Comment by AndreaBassi58** [comment]
> Tipo di issue:
> 
> * [x]  Dati mancanti o errati `dpc-covid19-ita-andamento-nazionale.csv` `dpc-covid19-ita-andamento-nazionale-latest.csv` `dpc-covid19-ita-andamento-nazionale-20201220.csv` `dpc-covid19-ita-andamento-nazionale-20201219.csv` `dpc-covid19-ita-andamento-nazionale-20201218.csv` `dpc-covid19-ita-andamento-nazionale-20201217.csv`
> * [ ]  Errore nella documentazione
> * [ ]  Errore or mancanza nella dashboard
> * [ ]  Problemi di visualizzazione nella dashboard
> * Regione: Italia
> * Provincia: n.a.
> 
> ## Riassunto
> Il dato relativo ai tamponi eseguiti il 17/12 (24.635.720) è inferiore rispetto al dato del giorno precedente (24.683.230).
> 
> **Attesa:**
> 
> Ogni giorno il dato relativo al numero di tamponi effettuati deve essere maggiore o uguale rispetto al giorno precedente.
> 
> **Attuale:**
> 
> 16/12/2020: 24.683.230 tamponi effettuati
> 17/12/2020: 24.635.720 tamponi effettuati
> 
> Tamponi effettuati tra il 16 e il 17 dicembre:
> 
> 24.635.720 - 24.683.230 = -47.510

👌

**Comment by leeppolis** [comment]
https://github.com/pcm-dpc/COVID-19/issues/998

**Comment by alex27riva** [comment]
> Il dato corretto da inserire nel csv relativo ai tamponi del 17/12 è 24.868.550

Come è stato calcolato? Facendo una media dei giorni precedenti?
Comunque penso che del dato debba essere corretto, non ha senso che il conteggio cumulativo dei tamponi sia inferiore rispetto al giorno precedente...
