### ISSUE TITLE
Dato errato per la Sardegna 

### ISSUE THREAD

**Issue by marcs7** [pcm-dpc/COVID-19#101]
Tipo di issue:

- [x] Dati mancanti o errati 
- [ ] Errore nella documentazione 
- [ ] Errore or mancanza nella dashboard 
- [ ] Problemi di visualizzazione nella dashboard 

## Riassunto

Nei dati per la Sardegna i casi risultano essere oltre i 30 dopo le 18 ma erano di sicuro oltre i 20 prima delle 18

**Attuale:**
Vengono contate 20 persone

**Comment by orion434** [comment]
@marcs7 puoi gentilmente aggiungere le fonti per i dati citati?

Le statistiche ufficiali del 10/03/2020 parlano di 20 casi totali in Sardegna alle ore 18:00 

(fonte: https://github.com/pcm-dpc/COVID-19/blob/master/dati-regioni/dpc-covid19-ita-regioni-20200310.csv#L16)

E' possibile che altre fonti riportino aggiornamenti ad un orario differente o risultati diversi (per esempio persone nate in Sardegna ma residenti o in cura in altre zone in Italia o all'esterno). In ogni caso i casi oltre le ore 18 vanno conteggiati tra i nuovi dati del 11/03/2020.

**Comment by marcs7** [comment]
ecco a te @orion434 https://www.lanuovasardegna.it/oristano/cronaca/2020/03/10/news/coronavirus-una-donna-contagiata-a-oristano-35-i-casi-in-sardegna-1.38576040

**Comment by orion434** [comment]
@marcs7 Grazie mille. L'articolo citato riporta correttamente l'aumento di una unità a seguito di 22 tamponi da parte dell'Unità di crisi della regione.
Il dato finale di 35 casi totali sembra però basato su un valore iniziale di 34 casi positivi non corretto (e apparentemente non proveniente direttamente dall'Unità di crisi della regione). Da segnalare che l'articolo non presenta collegamenti a siti ufficiali di protezione civile, ministero della sanità o altre istituzioni ufficiali. Pertanto i numeri citati non possono essere direttamente verificati. 
Personalmente ritengo che si tratti quindi di un errore dell'articolo (in buona fede). Ti invito però a segnalare altre fonti ufficiali da cui risultino un numero diverso di casi.

**Comment by marcs7** [comment]
posso aggiungere altre tre testate giornalistiche locali, cercando coronavirus sardegna si hanno molti altri risultati che riportano tra i 34 e 35 casi

**Comment by orion434** [comment]
Per quanto importanti e diffuse le testate giornalistiche, un articolo che non riporti chiaramente la provenienza dei loro dati non ha alcuna valenza scientifica, in quanto non è possibile verificare tali numeri.
Di conseguenza, puoi aggiungere tali articoli se esplicitano in modo chiaro la provenienza dei loro dati (non basta che riportino che qualcuno o un ente ha detto qualcosa, servono **link a dati certi e verificabili**). Se da una parte abbiamo dei dati ufficiali prodotti dalla protezione civile, dall'altra ci sono dei numeri non verificabili in alcun modo (chiunque può pubblicare dei numeri dicendo che sono la realtà, ma dal punto di visto scientifico non hanno valore se non ci sono prove a sostegno delle proprie affermazioni). Personalmente mi atterrei ai dati ufficiali per non cadere in errori (anche semplicemente di conteggio, riallocazioni, verifiche di falsi positivi/negativi, etc.). 
 
Ho verificato poco fa il sito della regione Sardegna e rimanda direttamente ai siti della protezione civile e all'istituto della sanità.

**Comment by umbros** [comment]
Ciao a tutti,
corretto quanto riporta @orion434, questo è il repository ufficiale dei dati, altre informazioni potrebbero essere anche non aggiornate ma non hanno seguito il processo di ufficializzazione e pertanto non sono presenti.
