### ISSUE TITLE
Aggiungere colori delle regioni

### ISSUE THREAD

**Issue by rinaldo-lisario** [pcm-dpc/COVID-19#1012]
Sarebbe utile avere nel json delle regioni il colore di appartenenza.
Oppure in un file json dedicato.
Grazie,
Rinaldo

**Tipo di richiesta**:  richiesta di informazione | richiesta di dati | suggerimento di miglioramento (documentazione, label, _ecc_) | relativo alla pagina grafica

**Comment by umbros** [comment]
Ciao Rinaldo, cosa intendi? Regione gialla, arancione rossa?

**Comment by rinaldo-lisario** [comment]
Si, in questo modo chi realizza portali/app che usano questi dati può far vedere il colore di appartenenza delle varie regioni.

**Comment by LucaZeta** [comment]
Sarebbe senz'altro utile, anzi: ottima idea.

**Comment by umbros** [comment]
Ciao,
le aree con i colori sono rilasciate qui https://github.com/pcm-dpc/COVID-19/tree/master/aree in formato shape (shp) e geojson.

**Comment by rinaldo-lisario** [comment]
> Ciao,
> le aree con i colori sono rilasciate qui https://github.com/pcm-dpc/COVID-19/tree/master/aree in formato shape (shp) e geojson.

Grazie, ma io intendevo solo un semplice elenco tipo questo:
[
  {
    "data":"2020-02-24T18:00:00",
    "denominazione_regione":"Abruzzo",
    "colore":"arancio",
  },
  {
    "data":"2020-02-24T18:00:00",
    "denominazione_regione":"Basilicata",
    "colore":"giallo",
  },
etc........

**Comment by LucaZeta** [comment]
Le aree comunali contenute nei file indicati da umbros:
![immagine](https://user-images.githubusercontent.com/45511384/103103597-44152180-4622-11eb-8487-3584131a7b86.png)

Non ci sono le indicazioni richieste da rinaldo.

**Comment by umbros** [comment]
@pierluigicara

**Comment by pierluigicara** [comment]
Stiamo adottando il data model della direttiva "INSPIRE" per il tema Area Management and Restriction, che non ammette un campo con il colore. Considerate che riuscire a mantenere l'adozione di questo modello con tutte le variazioni giuridiche adottate in questi mesi dal Governo, dal MinSalute e dalle Regioni è una impresa davvero difficile che però sta funzionando. Le soluzioni potrebbero essere un nuovo file dedicato, ma andrebbe replicato per ogni tipologia di area, oppure mantenere il data model e utilizzare il campo appropriato che - nel caso delle aree nuove-  se ricordo bene si chiama legspecrif (art.1=giallo, art.2=arancione e art.3=rosso). Personalmente preferirei come dicevo questa soluzione per la conformità al data model.

**Comment by LucaZeta** [comment]
> Stiamo adottando il data model della direttiva "INSPIRE" per il tema Area Management and Restriction, che non ammette un campo con il colore.

@pierluigicara Benvenga una soluzione che aderisca a standard Europei, ma l'impressione che mi sono fatto analizzando i file indicati da umbros è che la granularità è comunale e siamo ben lungi dall'aver implementato tutti i comuni, province, aree-metropolitane e regioni.

Il campo **legSpecRif** riporta varie informazioni ("Allegato 1" oppure "unpopolated"). Sinceramente non ritengo che i file indicati possano essere utili per risolvere quanto richiesto da Rinaldo.
Felice di essere smentito in maniera puntuale.

**Comment by pierluigicara** [comment]
C'è un equivoco di fondo: io mi riferivo al caso del dataset "aree nuove" della fase attuale, che ha granularita' regionale/nazionale, mentre @LucaZeta parla di granularita' comunale e nella cartella "aree" l'unico dataset con quella granularita' è quello delle "aree comunali" che è un dataset ormai superato e che si riferisce alle zone rosse comunali della fase 1, dove peraltro non c'è alcuna distinzione di colore e nel file c'erano solo le istanze dei comuni in zona rossa.

**Comment by LucaZeta** [comment]
Non riesco neanche a visualizzarlo "aree nuove": oltre 70 MB di file json, il plug-in per la visualizzazione di firefox probabilmente non ce la fa. Rinuncio.

**Comment by LucaZeta** [comment]
@pierluigicara Riesci a pubblicare i riferimenti per accedere ai valori del "livello di attenzione" per le Regioni e se definito e se ha senso anche delle Province ?
La dimensione del file è tale da rendere difficoltoso il reverse engeneering, almeno con gli strumenti di cui dispongo, come già accennato.

servirebbero: I nomi delle variabili e relative strutture gerarchiche per accedervi.

**Comment by pierluigicara** [comment]
**Dimensioni del file**: il modelo dati adottato prevede al suo interno il versionamento (campo versionID), pertanto non esistono tanti file separati relativi ciascuno ad una specifica versione, ma un unico file che le contiene tutte. L'inconveniente - come giustamente fatto notare da @LucaZeta - è che il file tende a diventare molto grande. Oggi metterò anche una versione "generalizzata" del medesimo file (al nome verrà aggiunto -g) e i prossimi aggiornamenti verranno effettuati solo sulla versione semplificata.
**Rappresentazione dei "livelli di attenzione" (o colori)**: anzitutto non esiste un livello provinciale, il monitoraggio previsto dal Ministero della Salute/ISS con la circolare del 30.4.2020 in attuazione dell'all.10 del DPCM 26.4.2020 e ribadito nel documento "Prevenzione e risposta a Covid-19: evoluzione della strategia e pianificazione nella fase di transizione per il periodo autunno-invernale" del 12.10.2020 è su base regionale/nazionale. Per i valori, ripeto, bisogna riferirsi al campo legSpecRif. I dettagli della struttura del data model sono riportati nel file README e ulteriori indicazioni sono contenute nei METADATI. L'uso del file, richiede l'adozione di tecniche e strumenti GIS.
**scopo del dataset**: mi sembra necessario sottolineare che lo scopo del dataset è quello di dare una rappresentazione geografica di disposizioni giuridiche in materia di restrizioni associate a determinate aree geografiche. Non si può dunque prescindere dalle disposizioni giuridiche di riferimento (circolari, DPCM, DL ...) con tutta la loro complessità. In ogni caso in [questa ](http://www.salute.gov.it/portale/nuovocoronavirus/dettaglioContenutiNuovoCoronavirus.jsp?area=nuovoCoronavirus&id=5351&lingua=italiano&menu=vuoto) pagina si trovano tutti i dettagli.

**Comment by LucaZeta** [comment]
...
