### ISSUE TITLE
Inserimento indice RT

### ISSUE THREAD

**Issue by chuck2098** [pcm-dpc/COVID-19#1013]
**Tipo di richiesta**:  richiesta di dati

Salve, 
so che magari potrebbe essere complicato ma sarebbe molto utile se inseriste l'indice RT per ogni regione.

Grazie
## Interesse pubblico

Ultimamente i cittadini si basano su questo indice anche perché ne sentono parlare spesso in tv.

**Comment by vi-enne** [comment]
Se può essere utile, l'indice Rt per regione è diffuso settimanalmente nei monitoraggi pubblicati dal Ministero della Salute [qui](http://www.salute.gov.it/portale/nuovocoronavirus/dettaglioContenutiNuovoCoronavirus.jsp?area=nuovoCoronavirus&id=5351&lingua=italiano&menu=vuoto).

Il più recente è disponibile qui: [Report 32](http://www.salute.gov.it/portale/news/p3_2_1_1_1.jsp?lingua=italiano&menu=notizie&p=dalministero&id=5241)

**Comment by chuck2098** [comment]
Sorry,
ho dimenticato di specificare che poi lo andrei ad integrare nel mio sw mobile che ho sviluppato ad inizio pandemia.
Pertanto, fare web scraping, penso che:
1) sia scomodo
2) non sia legale

**Comment by umbros** [comment]
l'RT è rilasciato da ISS e non viene a noi fornito dal Ministero della Salute.

**Comment by CloudItaly** [comment]
Alla fine, prendendo spunto dall'ottimo lavoro fatto qui con i file JSON, mi son creato un mio progetto con l'RT puntuale. mio JSON con i dati. Certo li vado a popolare manualmente però almeno porto traccia settimana-per-settimana dei dati.
