### ISSUE TITLE
Scheda errata 25 dicembre

### ISSUE THREAD

**Issue by snooper0831** [pcm-dpc/COVID-19#1014]
Tipo di issue:

- [ ] Dati mancanti o errati 
- [ ] Errore nella documentazione  scheda errata
- [ ] Errore or mancanza nella dashboard 
- [ ] Problemi di visualizzazione nella dashboard 

- Regione:
- Provincia: 

## Riassunto

Per il 25 dicembre è stata caricata la scheda del 24
**Attesa:**

 25 dicembre 2020

**Attuale:**  24 dicembre 2020

**Comment by umbros** [comment]
corretto
