### ISSUE TITLE
Il file della scheda 25 dicembre contiene la scheda del 24 dicembre

### ISSUE THREAD

**Issue by ornolio** [pcm-dpc/COVID-19#1015]
Tipo di issue:

- [x] Dati mancanti o errati 
- [ ] Errore nella documentazione 
- [ ] Errore or mancanza nella dashboard 
- [ ] Problemi di visualizzazione nella dashboard 

- Regione:
- Provincia: 

## Riassunto

**Attesa:**

**Attuale:**

**Comment by ornolio** [comment]
scheda riassuntiva 25/12 errata = scheda del 24/12

**Comment by umbros** [comment]
#1014

**Comment by snooper0831** [comment]
Si, hi riportato lo stesso problema anche io un'oretta fa ma ancora niente...
