### ISSUE TITLE
26/12 - Dati Provincia Autonoma di Bolzano non aggiornati

### ISSUE THREAD

**Issue by umbros** [pcm-dpc/COVID-19#1017]
26/12 - Dati Provincia Autonoma di Bolzano non aggiornati
I dati saranno aggiornati domani (27/12).

**Comment by Rabelaiss** [comment]
@umbros Nel file delle province i casi totali di Bolzano sono 0 invece di quelli di ieri che erano 28722.
Ossia alla riga 43113 colonna `totale_casi` del file [dpc-covid19-ita-province.csv](https://github.com/pcm-dpc/COVID-19/blob/master/dati-province/dpc-covid19-ita-province.csv) dovrebbe esserci 28722 invece c'è 0, potete correggere? Grazie e buone feste!

**Comment by umbros** [comment]
Attendiamo domani per correggere tutte le informazioni. I dati sono conferiti in maniera ufficiale e noi ci limitiamo a segnalare, come già fatto :-)

Grazie a te e buone feste.

**Comment by umbros** [comment]
Aggiornati i dati di Bolzano del 26/12

**Comment by Rabelaiss** [comment]
@umbros ottimo! però il file dpc-covid19-ita-province-20201226.csv non è stato corretto
