### ISSUE TITLE
MOLISE 26/12: DIMESSI/GUARITI E TOTALE POSITIVI NON CONGRUENTI

### ISSUE THREAD

**Issue by MicheleAlfinito** [pcm-dpc/COVID-19#1018]
Tipo di issue:

- [x] Dati mancanti o errati 
- [ ] Errore nella documentazione 
- [ ] Errore or mancanza nella dashboard 
- [ ] Problemi di visualizzazione nella dashboard 

- Regione: Molise
- Provincia: 

## Riassunto

Nel file https://github.com/pcm-dpc/COVID-19/blob/master/dati-regioni/dpc-covid19-ita-regioni-20201226.csv per il Molise figurano 3877 dimessi_guariti mentre in https://github.com/pcm-dpc/COVID-19/blob/master/dati-regioni/dpc-covid19-ita-regioni-20201225.csv ne figura uno in più: 3878.
Inoltre la fonte ANSA qui http://www.moliseweb.it/info.php?id=24900 (25 Dicembre ore 19:00) riporta 2482 attualmente positivi, mentre il file github di oggi riporta 2323 come "totale_positivi".
Collimano invece i dati di tamponi, casi, ospedalizzati e deceduti.

**Attesa:**

revisione e/o correzione dei campi "dimessi_guariti" e "totale_positivi" per la Regione Molise;
e/o nota esplicativa al riguardo.

**Attuale:**

figura "-1" dimessi_guariti dalla differenza oggi-ieri

**Comment by umbros** [comment]
Ciao Michele, la nota ANSA non è per noi una fonte ufficiale (ovvero che viene analizzata per i dati di questo repository). I dati provengono da Ministero della Salute tramite le regioni. Il 26 non è stata emessa alcuna nota (si tratta effettivamente di un ricalcolo).
