### ISSUE TITLE
Suddivisione per fasce di eta'

### ISSUE THREAD

**Issue by luigiselmi** [pcm-dpc/COVID-19#102]
**Tipo di richiesta**:  richiesta di dati 

## Riassunto

Suddivisione dei dati per fasce di eta, per esempio 30-39, 40-49, etc.
## Interesse pubblico

La suddivisione per fasce di eta' aiuta a capire quali sono i soggetti piu a rischio.

**Comment by marcodadamo** [comment]
Avevo proposto l'issues n. #55 avente la stessa argomentazione. All'interno sono presenti risposte a riguardo.

**Comment by umbros** [comment]
#55
