### ISSUE TITLE
Ho aggiunto i vostri dati a https://covid-19-analytics.herokuapp.com/

### ISSUE THREAD

**Issue by danielerosa** [pcm-dpc/COVID-19#103]
https://covid-19-analytics.herokuapp.com/

<img width="1842" alt="image" src="https://user-images.githubusercontent.com/37300442/76385909-5941ed80-6339-11ea-96d3-bdb500ddc2bb.png">

<img width="1870" alt="image" src="https://user-images.githubusercontent.com/37300442/76385945-6f4fae00-6339-11ea-8f4e-85cfb5b979d1.png">

**Tipo di richiesta**:  richiesta di informazione | richiesta di dati | suggerimento di miglioramento (documentazione, label, _ecc_) | relativo alla pagina grafica

**Comment by umbros** [comment]
Grazie  @danielerosa
