### ISSUE TITLE
Dato errato per i "casi testati" della Basilicata

### ISSUE THREAD

**Issue by andreazinno** [pcm-dpc/COVID-19#1032]
Ciao, ho notato che i dati di oggi (8 gennaio) riportano, per la Basilicata, un totale di tamponi pari a 1.485, mentre per i casi testati il valore è di  57.184, evidentemente errato, cosa che peraltro porta a un conteggio errato a livello nazionale e a una percentuale di nuovi positivi su casi testati di 15,46% (magari fosse...) .

Grazie e buona lavoro a tutti.

**Comment by Rho2021** [comment]
Ciao, secondo il bollettino della regione Basilicata il totale dei casi testati all'8 gennaio è 121.207 e non 177.722. Dovrebbero essere 669 nuovi casi testati anziché 57.184.
https://www.regione.basilicata.it/giunta/site/giunta/detail.jsp?otype=1012&id=3071703&value=regione

**Comment by umbros** [comment]
Basilicata: ricalcolo modifica tamponi - https://github.com/pcm-dpc/COVID-19/commit/6ac60c636d618aca06fc53fcba7da68b3aadbef0
