### ISSUE TITLE
Errore casi testati Basilicata

### ISSUE THREAD

**Issue by emazep** [pcm-dpc/COVID-19#1033]
Oggi 08/01/2021 la Basilicata riporta un valore nel campo [casi testati] (cumulati) pari a 177.722, che vuol dire 57.184 casi testati nella sola giornata odierna, ovvero all'incirca 100 (cento) volte quelli riportati mediamente negli ultimi 10 giorni, mentre peraltro riporta soltanto 1.485 tamponi effettuati sempre nella giornata odierna.

C'è la possibilità di correggere quello che è con ogni evidenza un errore (marchiano)?

**Comment by Rho2021** [comment]
Ciao, secondo il bollettino della regione Basilicata il totale dei casi testati all'8 gennaio è 121.207 e non 177.722. Dovrebbero essere 669 nuovi casi testati anziché 57.184.
https://www.regione.basilicata.it/giunta/site/giunta/detail.jsp?otype=1012&id=3071703&value=regione

**Comment by emazep** [comment]
> 
 > Ciao, secondo il bollettino della regione Basilicata il totale dei casi testati all'8 gennaio è 121.207 e non 177.722. Dovrebbero essere 669 nuovi casi testati anziché 57.184.
> https://www.regione.basilicata.it/giunta/site/giunta/detail.jsp?otype=1012&id=3071703&value=regione

Grazie per l'informazione @Rho2021: speriamo che la correzione possa essere apportata anche ai dati di questo repository, altrimenti ci ritroveremo alterato anche il delta di domani.

**Comment by MicheleAlfinito** [comment]
> Ciao, secondo il bollettino della regione Basilicata il totale dei casi testati all'8 gennaio è 121.207 e non 177.722. Dovrebbero essere 669 nuovi casi testati anziché 57.184.
> https://www.regione.basilicata.it/giunta/site/giunta/detail.jsp?otype=1012&id=3071703&value=regione

Grazie mille. Colgo l'occasione per segnalare anche il delta anomalo (sempre Basilicata) del 18/12 sul 17/12: dal mio storico risulta un delta simile, come ordine di grandezza, a quello odierno tranne che per il segno: -57470.
Ho verificato di nuovo i latest del 17/12 e 18/12 per la Basilicata, ma l'incongruenza non è stata ancora corretta.
Se il dato dei testati di oggi andasse a parziale correzione di quella situazione, meglio sarebbe intervenire sul file relativo alla data in questione ed apportare un update su quello. Certo...poi andrebbe a catena sui cumulati successivi, me ne rendo ben conto.
Speriamo che vengano svolte le opportune verifiche.
Grazie

**Comment by MicheleAlfinito** [comment]
La discrepanza sul delta del 18/12 col segno meno era frutto di un ricalcolo, come da nota.

**Comment by Rho2021** [comment]
Sì, il 18/12 la Basilicata (e anche il Piemonte) ha ricalcolato i casi testati (prima della correzione il numero di casi testati era praticamente simile a quello dei tamponi), ma non ho trovato dati per correggere la serie.

**Comment by Rabelaiss** [comment]
Mi sembra di ricordare che le correzioni sui tamponi di basilicata e piemonte del 18/12 erano state fatte per togliere dal conteggio i test antigenici. In questi giorni è uscita una circolare del ministero riguardo la nuova definizione di caso covid (vedere #1031) che comprende anche le diagnosi avvenute tramite test rapido (sotto certe condizioni). Probabile quindi che il ricalcolo di ieri per la basilicata sia un riallineamento dei tamponi aggiungendo quelli che erano stati tolti il 18/12.

**Comment by Rabelaiss** [comment]
Come non detto sono appena stati corretti 🤣

**Comment by umbros** [comment]
Basilicata: ricalcolo modifica tamponi - https://github.com/pcm-dpc/COVID-19/commit/6ac60c636d618aca06fc53fcba7da68b3aadbef0
