### ISSUE TITLE
Basilicata il 9/1/21 numero di casi testati errato

### ISSUE THREAD

**Issue by ornolio** [pcm-dpc/COVID-19#1034]
Tipo di issue:

- [ x] Dati mancanti o errati 
- [ ] Errore nella documentazione 
- [ ] Errore or mancanza nella dashboard 
- [ ] Problemi di visualizzazione nella dashboard 

- Regione:Basilicata
- Provincia: 

## Riassunto

**Attesa:**

**Attuale:**

**Comment by umbros** [comment]
I dati sono stati corretti nella commit di ieri relativa al 09/01
