### ISSUE TITLE
Chiarimento: persone positive includono risultati test antigenico?

### ISSUE THREAD

**Issue by Rho2021** [pcm-dpc/COVID-19#1035]
**Tipo di richiesta**: richiesta di informazione

## Riassunto
Salve, visto l’aggiornamento della definizione di caso COVID-19 mi chiedevo se i casi totali conteggiati in questo repository compressero anche i soggetti risultati positivi al test antigenico (anche senza conferma con test molecolare) e se sì da che data.
Grazie

## Interesse pubblico
Sarebbe utile per valutare correttamente l’evoluzione della curva dei contagi

**Comment by magaspari** [comment]
Guardano i bollettini della provincia di Bolzano che specificano questo dato ad ora, ovvero fino alla settimana scorsa, sembrava di no, gli ultimo giorni non ho controllato. Da li si vede subito.

**Comment by Rho2021** [comment]
Grazie mille @magaspari. Ho controllato e Bolzano effettivamente rileva solo i casi positivi da PCR così come il Friuli. 
I nuovi casi positivi del Piemonte (al netto di quelli testati con test antigenico) non corrispondono invece a quelli del repo.

@umbros ci sono indicazioni ufficiali? Sarebbe utile capire se la serie storica ha subito break. Grazie

**Comment by magaspari** [comment]
La serie storica del Piemonte ha avuto un break per i tamponi ll 17 Dicembre (circa -20000), sembra siano stati tolti gli antigenici fatti fino a quel giorno in Piemonte, il tutto e' documentato qui #998. E' seguita una crescita del tasso di positività dei tamponi a partire dal 20/12 e non risulta chiaro se questa dipenda solo dall'errore sui dati (all'inizio e' sicuramente cosi) o se effettivamente sta tornando a crescere bisognerebbe ripristinare la serie aggiungendo le informazioni sui tamponi antigenici per il Piemonte da quel giorno in poi.  Se prima del 17 gli antigenici ci sono e sono mescolati agli altri l'errore rimane minimo, se si tolgono completamente il dato diventa inutilizzabile.
Se lo fa la potrebbe condividere per cortesia?
Io ho ricostruito Toscana, Bolzano e Parzialmente il Veneto.
Dopo di che va capita l'interpretazione dei positivi, fino ad un certo punto le circolari prevedevano il doppio controllo, quindi a meno di notizie contrarie Bolzano dovrebbe essere OK, ultimamente dal 4 Gennaio, potrebbero essere presenti più numerosi casi diagnosticati solo con antigenici per ulteriore modifica delle disposizioni causa anche il miglioramento dei test rapidi a disposizione.

**Comment by Rho2021** [comment]
Sulla pagine fb dell’Ass. [Marnati ](https://www.facebook.com/matteomarnatilegaassessore/)ci sono dati che possono aiutare a ripulire la serie del Piemonte prima del break, ma si hanno informazioni solo per i tamponi (viene indicato il totale e la % di test rapidi). Gli altri indicatori riportano soltanto il totale complessivo (senza precisare la quota relativa ai test rapidi).

I bollettini della regione [Piemonte ](https://www.regione.piemonte.it/web/pinforma/notizie/coronavirus-gli-aggiornamenti-dalla-regione-piemonte)riportano, dal 18 dicembre (quindi dopo il ricalcolo), anche il numero di casi positivi indicando la quota da test antigenico. Se dal totale complessivo si escludono i casi da test antigenico si ottiene un numero di nuovi casi positivi coincidente con quello fornito dalla protezione civile, ma solo dal 18 al 22 dicembre. Dopo tale data non c’è più corrispondenza (a meno che non abbia fatto errori di calcolo). 

Rimane comunque il problema di capire cosa viene conteggiato dopo la circolare del Ministero. Non tutte le regioni pubblicano un bollettino e quindi non è sempre possibile fare controlli. Insomma, se ci fosse una definizione ufficiale degli indicatori (e, se ci sono stati cambiamenti, avere elementi per ricostruire una serie storica omogenea) sarebbe utile per le analisi.

**Comment by Jmuccigr** [comment]
Con il grande numero di positive di oggi sembra che i test antigenici sono stati aggiunti, no?

**Comment by magaspari** [comment]
Effettivamente, noto che per la Provincia di Bolzano questa volta, diversamente da ieri, rispetto al bollettino nel sito della provincia precedente sono stati aggiunti anche tutti i positivi da antigenici.  Non e' chiaro se c'è stato un cambio dei metodi diagnostici dovuto alle nuove recenti indicazioni ministeriali oppure se i precedenti bollettini andrebbero interpretati in questo modo.

**Comment by Rho2021** [comment]
Pare di sì. La tabella pdf riporta il dettaglio dei test rapidi sia per i tamponi sia per i casi risultati positivi.

**Comment by magaspari** [comment]
> Sulla pagine fb dell’Ass. [Marnati ](https://www.facebook.com/matteomarnatilegaassessore/)ci sono dati che possono aiutare a ripulire la serie del Piemonte prima del break, ma si hanno informazioni solo per i tamponi (viene indicato il totale e la % di test rapidi). Gli altri indicatori riportano soltanto il totale complessivo (senza precisare la quota relativa ai test rapidi).
> 
> I bollettini della regione [Piemonte ](https://www.regione.piemonte.it/web/pinforma/notizie/coronavirus-gli-aggiornamenti-dalla-regione-piemonte)riportano, dal 18 dicembre (quindi dopo il ricalcolo), anche il numero di casi positivi indicando la quota da test antigenico. Se dal totale complessivo si escludono i casi da test antigenico si ottiene un numero di nuovi casi positivi coincidente con quello fornito dalla protezione civile, ma solo dal 18 al 22 dicembre. Dopo tale data non c’è più corrispondenza (a meno che non abbia fatto errori di calcolo).
> 
> Rimane comunque il problema di capire cosa viene conteggiato dopo la circolare del Ministero. Non tutte le regioni pubblicano un bollettino e quindi non è sempre possibile fare controlli. Insomma, se ci fosse una definizione ufficiale degli indicatori (e, se ci sono stati cambiamenti, avere elementi per ricostruire una serie storica omogenea) sarebbe utile per le analisi.

Rimetterei a posto la serie togliendo gli antigenici dai molecolari e considerando gli antigenici in una colonna a parte. Se ci riesco posso analizzare anche il Piemonte.  Relativamente alle discrepanze nei totali potrebbero essere, dovute alla necessita' di aspettare i controlli degli antigenici positivi.

**Comment by Rho2021** [comment]
Può darsi.
Spero rendano disponibile il dato anche per i soggetti testati perché il pdf non lo riporta.

**Comment by Jmuccigr** [comment]
Adesso vedo anche #1037.

**Comment by Rho2021** [comment]
Perfetto. Grazie mille

**Comment by magaspari** [comment]
> Sulla pagine fb dell’Ass. [Marnati ](https://www.facebook.com/matteomarnatilegaassessore/)ci sono dati che possono aiutare a ripulire la serie del Piemonte prima del break, ma si hanno informazioni solo per i tamponi (viene indicato il totale e la % di test rapidi). Gli altri indicatori riportano soltanto il totale complessivo (senza precisare la quota relativa ai test rapidi).

Grazie mille per questo suggerimento @Rho2021,  ho controllato ed effettivamente come dici c'è la serie completa tranne 6 e 5 Dicembre, se non sbaglio, sai se e' possibile recuperare i bollettini per queste due date?

**Comment by magaspari** [comment]
> Se dal totale complessivo si escludono i casi da test antigenico si ottiene un numero di nuovi casi positivi coincidente con quello fornito dalla protezione civile, ma solo dal 18 al 22 dicembre. Dopo tale data non c’è più corrispondenza (a meno che non abbia fatto errori di calcolo).

Questo credo che sia quello che ci si dovrebbe aspettare da questa nuova modalità di trasmettere i dati. La logica e' che in alcuni casi la diagnosi con gli antigenici va confermata con molecolare in altri no.  Quanto riporta il Piemonte permette tra l'altro di individuare i tamponi ripetuti ed escluderli. Levando dal totale dei positivi quelli dovuti a molecolare, si trovano le diagnosi fatte con solo antigenico, che sottratte al numero totale degli antigenici danno i test che necessitano conferma. E presumibilmente saranno duplicati lo stesso giorno o nei giorni a venire.

**Comment by Rho2021** [comment]
> > Se dal totale complessivo si escludono i casi da test antigenico si ottiene un numero di nuovi casi positivi coincidente con quello fornito dalla protezione civile, ma solo dal 18 al 22 dicembre. Dopo tale data non c’è più corrispondenza (a meno che non abbia fatto errori di calcolo).
> 
> Questo credo che sia quello che ci si dovrebbe aspettare da questa nuova modalità di trasmettere i dati. La logica e' che in alcuni casi la diagnosi con gli antigenici va confermata con molecolare in altri no. Quanto riporta il Piemonte permette tra l'altro di individuare i tamponi ripetuti ed escluderli. Levando dal totale dei positivi quelli dovuti a molecolare, si trovano le diagnosi fatte con solo antigenico, che sottratte al numero totale degli antigenici danno i test che necessitano conferma. E presumibilmente saranno duplicati lo stesso giorno o nei giorni a venire.

Vediamo che succederà nei prossimi giorni.
Grazie comunque per il contributo.
