### ISSUE TITLE
Colori regioni

### ISSUE THREAD

**Issue by steq28** [pcm-dpc/COVID-19#1038]
Salve, sto costruendo un sito web riguardante il coronavirus in Italia. E' possibile avere un file contenete il livello di rischio (colore) di ogni regione come lo è quello per gli infetti, guariti, ecc. Ho letto che lo avete già aggiunto in "aree_nuove" ma mi risulta troppo dispendioso utilizzarlo. Non sarebbe più semplice usare un formato json del tipo:
[{
"denominazione_regione": "Lombardia",
"rischio": "arancione"
}] ???

**Comment by Rabelaiss** [comment]
Ti conviene fare scraping dal [sito governativo](http://www.salute.gov.it/portale/nuovocoronavirus/dettaglioContenutiNuovoCoronavirus.jsp?area=nuovoCoronavirus&id=5351&lingua=italiano&menu=vuoto)

**Comment by alesasse** [comment]
Da quel che ho potuto vedere, il "colore" della regione è mappato nei files relativi alle aree (p.es. nel json in aree/geojson/dpc-covid-19-aree-nuove-g-json.zip) nel campo "legSpecRif":
art.1 -> giallo
art.2 -> arancione
art.3 -> rosso

**Comment by dbaroncelli** [comment]
dover unzippare quel file per estrarre i colori delle regioni è folle
servirebbe un semplice JSON or CSV con semplicemente il nome della regione ed il colore

**Comment by imcatta** [comment]
Ho realizzato un dataset che espone il "colore" delle regioni. Se vi può essere utile lo trovate qui [https://github.com/imcatta/restrizioni_regionali_covid](https://github.com/imcatta/restrizioni_regionali_covid)

**Comment by LucaZeta** [comment]
In formato json: https://covid19.zappi.me/coloreRegioni.php

**Comment by pollopollo6** [comment]
> Ho realizzato un dataset che espone il "colore" delle regioni. Se vi può essere utile lo trovate qui https://github.com/imcatta/restrizioni_regionali_covid

grazie infinite, ci hai salvato il simulatore ad agenti

**Comment by jumpjack** [comment]
> Salve, sto costruendo un sito web riguardante il coronavirus in Italia. E' possibile avere un file contenete il livello di rischio (colore) di ogni regione come lo è quello per gli infetti, guariti, ecc. Ho letto che lo avete già aggiunto in "aree_nuove" ma mi risulta troppo dispendioso utilizzarlo. Non sarebbe più semplice usare un formato json del tipo:
> [{
> "denominazione_regione": "Lombardia",
> "rischio": "arancione"
> }] ???

per caso hai fatto anche una rappresentazione grafica dello storico dei colori?

**Comment by steq28** [comment]
> > Salve, sto costruendo un sito web riguardante il coronavirus in Italia. E' possibile avere un file contenete il livello di rischio (colore) di ogni regione come lo è quello per gli infetti, guariti, ecc. Ho letto che lo avete già aggiunto in "aree_nuove" ma mi risulta troppo dispendioso utilizzarlo. Non sarebbe più semplice usare un formato json del tipo:
> > [{
> > "denominazione_regione": "Lombardia",
> > "rischio": "arancione"
> > }] ???
> 
> per caso hai fatto anche una rappresentazione grafica dello storico dei colori?
> 
> Intanto ho trovato altri repository con i dati dei colori messi in altra forma:
> https://github.com/imcatta/restrizioni_regionali_covid/blob/main/dataset.csv
> https://github.com/ondata/covid19italia/tree/master/webservices/COVID-19Aree/processing
> https://github.com/CloudItaly/Indice-RT/blob/main/colori.json

Purtroppo sono stato molto impegnato e quindi il progetto non è più proseguito. Ho aggiunto l'indicazione del colore solo per il giorno stesso.
Se vuoi dargli un'occhiata questo è il sito:
https://coronavirusitaliamap.altervista.org/

**Comment by jumpjack** [comment]
Scusate, ma perchè questo issue è stato chiuso? Il problema permane, bisogna ancora ricorrere a repository esterni per aggirarlo.
