### ISSUE TITLE
Total number of tests

### ISSUE THREAD

**Issue by raftgs** [pcm-dpc/COVID-19#104]
**Type of issue**: total number of tests explication

## Summary

Please confirm if the total number of tests represent the number of people tested or it includes the double verification.

## Public interest

Explaining this number can be helpful to have a better overview.
We're trying to collect this kind of data from all countries in this issue [https://github.com/CSSEGISandData/COVID-19/issues/277](https://github.com/CSSEGISandData/COVID-19/issues/277)
Thank you

**Comment by umbros** [comment]
Hi, the number of tests is an indicated number of tests made, 1 test does not represent 1 person but 1 person may have made n tests.

**Comment by raftgs** [comment]
Thank you
