### ISSUE TITLE
I dati sui tamponi delle Marche non corrispondono al vero

### ISSUE THREAD

**Issue by Abalieno** [pcm-dpc/COVID-19#1042]
Tipo di issue:

- [x] Dati mancanti o errati 

- Regione: Marche

## Riassunto

Questo e' un errore che va avanti da mesi, adesso e' ancora piu' sfacciato per il modo in cui sono pubblicati i dati.

In sintesi, le Marche nelle ultime settimane hanno comunicato un numero di test gonfiato dall'aggiunta di antigenici (ulteriormente manipolato in quanto si contano molecolari + antigenici nel numero di test eseguiti, ma si contano solo i casi positivi usciti da test molecolari, quindi il tasso di positivita' risultante e' falso).

Oggi nel bollettino finalmente si possono vedere il numero di test molecolari e antigenici, separatamente. Ma il dato delle Marche continua ad essere falso. La colonna dei test molecolari include TUTTI i test (molecolari + antigenici), poi c'e' la colonna di antigenici che include solo antigenici fatti. 

E poi abbiamo il colpo di genio: la somma di test totali del giorno, che sono prima colonna (molecolari + antigenici) + seconda colonna (antigenici).

Quindi nel totale tamponi delle Marche gli antigenici sono contati due volte. Gli antigenici gia' sommati ai molecolari, e gli antigenici da soli. Tamponi totali: ((molecolari + antigenici) + antigenici)

Questi sono i dati precisi riportati oggi dalla regione, nello stesso formato in cui sono sempre stati riportati:
https://www.regione.marche.it/News-ed-Eventi/Post/70687/Coronavirus-Marche-aggiornamento-dati-dal-Servizio-Sanit%C3%A0-situazione-al-15-01-2021-ore-9-00

> "Il Servizio Sanità della Regione Marche ha comunicato che nelle ultime 24 ore sono stati testati 6239 tamponi: 3919 nel percorso nuove diagnosi (di cui **1926** nello **screening con percorso Antigenico**) e 2320 nel percorso guariti (con un rapporto positivi/testati pari al 14,6%).
> 
> I positivi nel percorso nuove diagnosi sono 571
> 
> Nel **Percorso Screening Antigenico** sono stati effettuati **1926** test e sono stati riscontrati 58 casi positivi (da sottoporre al tampone molecolare). Il rapporto positivi/testati è pari al 3%."

Quindi:
571 + 58 = 629 positivi, da oggi questi sono riportati correttamente (anche se i 58 saranno da riconfermare, stando a quanto scritto).

Rimane il grosso problema dei tamponi. Come si puo' leggere il numero totale di tamponi eseguiti, che comprende la somma di molecolari e antigenici, e' 6239 secondo la regione.
Divisi tra 1993 molecolari, 1926 antigenici, e altri 2320 per verifica guariti.

Nei dati della protezione civile invece questi numeri arrivano in questo modo (bollettino di oggi):
8165 tamponi totali.
Numero ottenuto in questo modo: 1993 molecolari + 1926 antigenici + 1926 (sommati due volte) + 2320 verifica guariti = 8165
Ovvero i 6239 della regione (molecolari + antigenici), piu' 1926, di nuovo il numero di antigenici.

Quindi due campi sono errati. E' sbagliato il numero di molecolari, che invece include gli antigenici, ed e' sbagliata la somma totale, dove gli antigenici sono contati due volte.

Ribadisco anche che questo errore grossolano non e' un caso di oggi, ma sono settimane che questi numeri sono registrati in maniera errata.

Mi rendo conto che qui la responsabilita' e' della regione che non riporta correttamente i dati, ma in qualche modo il problema deve essere risolto.

**Comment by Paulsword** [comment]
@Abalieno  cosa mi dici dei casi? #1041

**Comment by Abalieno** [comment]
Non ho capito a cosa si riferiscono i 2206 "che ballano", o dove si trovino.

**Comment by Paulsword** [comment]
Se fai check incrociato tra il totale dei casi nel report regioni e quello del report province (sommando le province di ogni regione) dovresti ottenere valori identici. Così è per tutte le regioni, salvo errori, avendo cura di aggiungere al dato di ogni provincia anche i codici ottocentoXY e novecentoXY che definiscono i casi extra cioè per le Marche:

889 | Fuori   Regione / Provincia Autonoma
989 | In fase di definizione/aggiornamento

che ieri hanno avuto una differenza notevole rispetto al giorni prima, NON incluso nel totale della regione.

**Comment by tummarellox** [comment]
Il problema attuale è che dai dati forniti dalla regione nei bollettini giornalieri non è chiaro se i test positivi del percorso nuove diagnosi INCLUDANO i positivi nel percorso screening antigenico rapido oppure no. Io propendo per la seconda opzione e in tal caso i dati forniti nel bollettino nazionale risulterebbero falsati.

Questa la dichiarazione di oggi ad esempio:
_Il Servizio Sanità della Regione Marche ha comunicato che nelle ultime 24 ore sono stati testati 5682 tamponi: 3668 nel percorso nuove diagnosi (di cui 2057 nello screening con percorso Antigenico) e 2014 nel percorso guariti (con un rapporto positivi/testati pari al 12,7%).

I positivi nel percorso nuove diagnosi sono 467 (87 in provincia di Macerata, 137 in provincia di Ancona, 132 in provincia di Pesaro-Urbino, 58 in provincia di Fermo, 37 in provincia di Ascoli Piceno e 16 fuori regione).

Questi casi comprendono soggetti sintomatici (52 casi rilevati), contatti in setting domestico (84 casi rilevati), contatti stretti di casi positivi (132 casi rilevati), contatti in setting lavorativo (26 casi rilevati), contatti in ambienti di vita/socialità (14 casi rilevati), contatti in setting assistenziale (9 casi rilevati), contatti con coinvolgimento di studenti di ogni grado di formazione (13 casi rilevati), screening percorso sanitario (3 casi rilevati) e 1 rientro dall'estero. Per altri 133 casi si stanno ancora effettuando le indagini epidemiologiche. Nel Percorso Screening Antigenico sono stati effettuati 2057 test e sono stati riscontrati 80 casi positivi (da sottoporre al tampone molecolare). Il rapporto positivi/testati è pari al 4%._

Letta così sembra che gli 80 siano da aggiungere ai 467... Ma non è chiaro.

**Comment by tummarellox** [comment]
Mi rispondo da solo: fino a ieri, la regione Marche ha inserito i soli positivi ai PCR nel conteggio dei casi positivi, mettendo tuttavia la somma di test PCR e antigenici rapidi eseguiti al denominatore e non includendo quindi i casi positivi ai test antigenici rapidi.
Seguendo questo iter, viene spontaneo presupporre che anche oggi i test positivi al rapido antigenico non vengono inclusi nella conta dei casi positivi, quindi sì, i dati forniti dal bollettino nazionale relativi ai contagi della regione Marche sono fuorvianti e sottostimati in quanto i casi positivi agli antigenici rapidi non vengono inclusi nella colonna "Incremento casi totali" del bollettino nazionale, a differenza delle altre regioni che li includono.

**Comment by Abalieno** [comment]
Oggi in bollettino alcuni aggiustamenti.

La regione riporta 467 positivi da PCR, il bollettino ne riporta 409. La differenza di 58 significa che i positivi agli antigenici di ieri sono stati rimossi dal conteggio di positivi. Questo potrebbe essere corretto se la procedura e', nel mondo reale piuttosto che in quello dell'intenzione, di verificare tutti i positivi antigenici con PCR.

Oggi, gli 80 positivi da antigenici non sono inseriti nel totale positivi. Quindi nell'intenzione di verificarli con PCR, presumibilmente per evitare doppioni una volta verificati. 

**Il conteggio dei tamponi invece continua a non aver senso.**

https://www.regione.marche.it/News-ed-Eventi/Post/70731/Coronavirus-Marche-aggiornamento-dati-dal-Servizio-Sanit%C3%A0-situazione-al-16-01-2021-ore-9-00

"Tamponi processati con test molecolare"
Oggi il bollettino riporta: 609.804, la differenza rispetto a ieri e' di 5.682.

**Questo campo continua ad essere la SOMMA di molecolari ed antigenici, invece che solo antigenici.**

La regione scrive:
_" nelle ultime 24 ore sono stati testati 5682 tamponi: 3668 nel percorso nuove diagnosi (di cui 2057 nello screening con percorso Antigenico) e 2014 nel percorso guariti"_

Il numero di test molecolari corretto e' quindi 3625. Ovvero il totale (5682) MENO il numero di antigenici (2057).

Il campo "Tamponi processati con test antigenico rapido" oggi segna 2057, che e' il numero corretto degli antigenici di oggi, ma solo di oggi (mentre questi campi dovrebbero essere cumulativi).
So fosse deciso di resettare i dati per correggerli, ok. Ma come visto i molecolari sono ancora sommati agli antigenici.

Il campo "Incremento tamponi totali (rispetto al giorno precedente)" segna 5813.
Non ho ben capito come esce fuori questo numero. Il numero di tamponi totali (molecolari + antigenici) corretto di oggi, come visto sopra, e' 5682. Quindi c'e' uno scarto di 131.
Almeno non sono stati sommati gli antigenici due volte, come successo ieri. Quindi il totale tamponi sarebbe solo sbagliato di quei misteriosi 131, invece che qualche migliaia come ieri.

Rimane il problema dei molecolari, che continuano ad essere la somma di molecolari e antigenici, gonfiando artificialmente il numero.

**Comment by Abalieno** [comment]
Oggi in bollettino stessi errori del giorno precedente.

I positivi da test antigenico (71) non vengono piu' registrati, ne nei totali, ne come dato singolo. Oggi molte altre regioni hanno uno zero nel campo di positivi ad antigenico, pur avendo fatto test antigenici nelle 24 ore.

**"Tamponi processati con test molecolare" continua ad essere la SOMMA di molecolari e antigenici.**

https://www.regione.marche.it/News-ed-Eventi/Post/70735/Coronavirus-Marche-aggiornamento-dati-dal-Servizio-Sanit%C3%A0-situazione-al-17-01-2021-ore-9-00
_nelle ultime 24 ore sono stati testati 6346 tamponi: 4147 nel percorso nuove diagnosi (di cui 2268 nello screening con percorso Antigenico) e 2199 nel percorso guariti_

In bollettino invece:
Totale molecolari: 616150 (oggi) - 609804 (ieri) = 6346, ovvero NON il numero di test molecolari reale, ma la somma di molecolari ed antigenici.

Il numero reale, non riportato in bollettino, di test molecolari di oggi e' invece: 6346 - 2268 = 4078.

Il numero riportato in bollettino di test antigenici e' 2268. Che e' il numero delle 24h come riportato dalla regione, ma che in bollettino secondo il criterio dovrebbe essere il totale di piu' giorni.

L'incremento tamponi rispetto al giorno precedente in bollettino e' 6557, numero di origine ignota e misteriosa.

**Comment by tummarellox** [comment]
Con i dati di oggi siamo al delirio assoluto: 
Nel bollettino nazionale non solo non vengono calcolati i positivi al test rapido antigenico, ma il numero complessivo di tamponi effettuati include DUE VOLTE la quota degli antigenici rapidi:
https://www.regione.marche.it/News-ed-Eventi/Post/70741/Coronavirus-Marche-aggiornamento-dati-dal-Servizio-Sanit%C3%A0-situazione-al-18-01-2021-ore-9-00


Il Servizio Sanità della Regione Marche ha comunicato che nelle ultime 24 ore sono stati testati 2340 tamponi: 1454 nel percorso nuove diagnosi (di cui 984 nello screening con percorso Antigenico) e 886 nel percorso guariti (con un rapporto positivi/testati pari al 10,8%).

Al bollettino nazionale risultano, incredibilmente, 3324 tamponi (2340+984). Totalmente errato visto che i 2340 tamponi includono già i 984 antigenici rapidi.

**Comment by Abalieno** [comment]
Si, aggiornamento di oggi.

Oggi in bollettino si sono cancellati i minimi progressi fatti, e si e' tornati agli errori piu' grossolani di Venerdi'.

- **Il Campo "Tamponi processati con test molecolare" continua ad essere la SOMMA di molecolari e antigenici.**
- Si e' ritornati a sommare **due volte** il numero di antigenici sul totale.

https://www.regione.marche.it/News-ed-Eventi/Post/70741/Coronavirus-Marche-aggiornamento-dati-dal-Servizio-Sanit%C3%A0-situazione-al-18-01-2021-ore-9-00
_nelle ultime 24 ore sono stati testati 2340 tamponi: 1454 nel percorso nuove diagnosi (di cui 984 nello screening con percorso Antigenico) e 886 nel percorso guariti_

Il bollettino riporta:
Totale molecolari: 618490 (oggi) - 616150 (ieri) = 2340 ovvero NON il numero di test molecolari reale, ma la somma di molecolari ed antigenici.

Il numero reale, non riportato in bollettino, di test molecolari di oggi e' invece: 2340 - 984 = 1356.

Il numero riportato in bollettino di test antigenici e' 3252. Questo numero oggi viene fuori dalla somma di antigenici di ieri e di oggi. Presumibilmente corretto se si fosse ora deciso di sommarli, sempre da non cambiare di nuovo idea tra qualche giorno.

L'incremento tamponi rispetto al giorno precedente in bollettino e' 3324. Tornando appunto alla DOPPIA SOMMA di antigenici. Problema introdotto Venerdi', risolto Sabato e Domenica, e tornato di moda il Lunedi'.

Secondo la formula: ((molecolari + antigenici) + antigenici)

**Comment by magicblack7** [comment]
Oltre che concordare e condividere ogni appunto fatto aggiungo che, dati regionali alla mano e opportunamente salvati giorno per giorno, questa storia va avanti precisamente dal giorno 04/12.

Dal 04/12 (incluso) al 18/01 (incluso) sono stati aggiunti, nel conto dei molecolari, precisamente 58.552 antigenici (circa il 29-30% del totale di tamponi inseriti a bollettino in questo queriodo).

**Comment by Abalieno** [comment]
Dovrebbe essere la data in cui la regione ha cominciato a specificarli.

Sommario di oggi 19/01, stesso di ieri:
- **Il Campo "Tamponi processati con test molecolare" continua ad essere la SOMMA di molecolari e antigenici.**
- Si e' ritornati a sommare **due volte** il numero di antigenici sul totale.

https://www.regione.marche.it/News-ed-Eventi/Post/70760/Coronavirus-Marche-aggiornamento-dati-dal-Servizio-Sanit%C3%A0-situazione-al-19-01-2021-ore-9-00
_nelle ultime 24 ore sono stati testati 4502 tamponi: 2481 nel percorso nuove diagnosi (di cui 1002 nello screening con percorso Antigenico) e 2021 nel percorso guariti_

In bollettino, totale molecolari: 622992 (oggi) - 618490 (ieri) = 4502, ovvero NON il numero di test molecolari reale, ma la somma di molecolari ed antigenici.

Il numero reale, non riportato in bollettino, di test molecolari di oggi e' invece: 3500 (4502 - 1002)

Il numero riportato in bollettino di test antigenici e' il dato corretto cumulativo, ora su tre giorni.

L'incremento tamponi rispetto al giorno precedente riportato in bollettino e' 5504. Riproponendo la DOPPIA SOMMA di antigenici.

Secondo la formula: ((molecolari + antigenici) + antigenici)

**Comment by Abalieno** [comment]
Bollettino del 20/01, questa volta i dati coincidono con quelli della regione.

Segnalo un'ulteriore stranezza, anche se qui non ci sono elementi per capirne la dinamica (e la discrepanza risulta nello stesso documento, quindi non e' un problema di comunicazione dati). La regione ha sempre riportato un numero di persone in isolamento domiciliare leggermente diverso da quello che risulta in bollettino. Negli ultimi giorni questa discrepanza e' cresciuta significativamente.

Oggi, il numero di isolati che risulta nella tabella regionale e' di 16.007, mentre in bollettino sono 7.958

https://www.regione.marche.it/News-ed-Eventi/Post/70782/Coronavirus-Marche-aggiornamento-dati-dal-Servizio-Sanit%C3%A0-20-01-2021-ore-12-00

**Comment by magicblack7** [comment]
Bollettino del 21/01, questa volta i dati NON coincidono (nuovamente) con quelli della regione.

Risultano 7.639 tamponi molecolari in più rispetto alla giornata di ieri, quando in realtà sarebbero 4.684.

Pur aggiungendo gli antigenici, com'è stato fatto fino al 19/01, si arriverebbe a 6.998 tamponi "molecolari" in più.

C'è un disavazano di 641 tamponi, non si sa presi da dove.

**Comment by Abalieno** [comment]
Aggiornamento 21/01, sommario:
- **Il Campo "Tamponi processati con test molecolare" continua ad essere la SOMMA di molecolari e antigenici. Piu' altri 641 di origine ignota.**
- Si e' ritornati a sommare **due volte** il numero di antigenici sul totale (piu' i 641).

Invece che confermare le correzioni fatte, si sono aggiunti errori a quelli gia' presenti precedentemente. 

https://www.regione.marche.it/News-ed-Eventi/Post/70789/Coronavirus-Marche-aggiornamento-dati-dal-Servizio-Sanit%C3%A0-situazione-al-21-01-2021-ore-9-00
_nelle ultime 24 ore sono stati testati 6998 tamponi: 4508 nel percorso nuove diagnosi (di cui 2314 nello screening con percorso Antigenico) e 2490 nel percorso guariti_

In bollettino, totale molecolari: 634798 (ieri) - 627159 (oggi) = 7639. Non solo la somma di molecolari e antigenici, che sarebbe 6998, ma altri 641 di origine ignota.

Il numero reale, non riportato in bollettino, di test molecolari di oggi e' invece: 4684 (6998 - 2314)

Il numero riportato in bollettino di test antigenici e' il dato corretto cumulativo riportato dalla regione degli ultimi 5 giorni.

L'incremento tamponi rispetto al giorno precedente riportato in bollettino e' 9953. Secondo la formula:
(molecolari + antigenici) + antigenici + bonus 641

**Comment by magicblack7** [comment]
@Abalieno svelato l'arcano sui +641. In realtà, guardando meglio l'incremento di ieri, puoi notare che, per i tamponi molecolari l'incremento del 21/01 è stato di +7.639.

È la somma dei molecolari comunicati il 21/01 (4.684) e degli antigenici comunicati il 20/01 (2.955).

La stessa cosa è successa oggi: per i tamponi molecolari l'incremento del 22/01 è stato di +6.349.

È la somma dei molecolari comunicati il 22/01 (4.035) e degli antigenici comunicati il 21/01 (2.314).

**Comment by Abalieno** [comment]
Ok, cambia poco.

Sommario 22/01:
- **Il Campo "Tamponi processati con test molecolare" e' la SOMMA di molecolari e antigenici.** 
- Si sommano **due volte** il numero di antigenici sul totale.

https://www.regione.marche.it/News-ed-Eventi/Post/70811/Coronavirus-Marche-aggiornamento-dati-dal-Servizio-Sanit%C3%A0-situazione-al-22-01-2021-ore-9-00
_nelle ultime 24 ore sono stati testati 6698 tamponi: 4415 nel percorso nuove diagnosi (di cui 2663 nello screening con percorso Antigenico) e 2283 nel percorso guariti_

In bollettino, totale molecolari: 541147 (ieri) - 634798 (oggi) = 6349. Come osservato gia' sopra, questi sono la somma di molecolari e antigenici, ma invece di usare il numero di antigenici di oggi (2663), si e' usato quello di ieri (2314).
2283 tamponi verifica guariti + 1752 tamponi diagnostici + 2314 test antigenici di ieri = 6349

Svelato il mistero, perpetuato l'errore.

Faccio presente quanto lontani dalla realta' siano i numeri che si ottengono in questo modo. Sappiamo che l'incidenza di positivi 437 si calcola sui soli tamponi diagnostici (1752): ne deriva un tasso di positivita' del 25% circa. Molto piu' alto dei valori riportati.

L'incremento tamponi rispetto al giorno precedente riportato in bollettino e' 9953. 
**Numero che si ottiene prendendo i tamponi molecolari di oggi (4035) sommati agli antigenici di oggi (2663) sommati agli antigenici di ieri (2314)** = 9012

Provo anche a tentare una spiegazione sul motivo il 20/01 abbiamo avuto dati corretti: qualcuno ha provato a fare le correzioni, il giorno dopo si e' ritrovato con tutti i campi sfasati rispetto a quelli riportati, e piuttosto che correggere ogni giorno manualmente tutto si e' deciso di perpetuare l'errore.

**Comment by Abalieno** [comment]
Oggi riproposizione errori di ieri.

Sommario 23/01:
- **Il Campo "Tamponi processati con test molecolare" e' la SOMMA di molecolari e antigenici.**
- Si sommano **due volte** il numero di antigenici sul totale.

https://www.regione.marche.it/News-ed-Eventi/Post/70824/Coronavirus-Marche-aggiornamento-dati-dal-Servizio-Sanit%C3%A0-situazione-al-23-01-2021-ore-9-00
_nelle ultime 24 ore sono stati testati 6559 tamponi: 4398 nel percorso nuove diagnosi (di cui 2833 nello screening con percorso Antigenico) e 2161 nel percorso guariti_

In bollettino, totale molecolari: 647536 (oggi) - 641147 (oggi) = 6389. 
Dato sbagliato dato che somma i test molecolari di oggi (3726) ai test antigenici di ieri (2663).

L'incremento tamponi rispetto al giorno precedente riportato in bollettino e' 9222.
Dato sbagliato dato che somma i test molecolari di oggi (3726), agli antigenici di oggi (2833), piu' ancora gli antigenici di ieri (2663) = 9222

**Comment by Abalieno** [comment]
Continuero' a riportare gli stessi errori fino a Sabato, poi basta.

Sommario 24/01:
- **Il Campo "Tamponi processati con test molecolare" e' la SOMMA di molecolari e antigenici.**
- Si sommano **due volte** il numero di antigenici sul totale.

https://www.regione.marche.it/News-ed-Eventi/Post/70830/Coronavirus-Marche-aggiornamento-dati-dal-Servizio-Sanit%C3%A0-situazione-al-24-01-2021-ore-9-00
_nelle ultime 24 ore sono stati testati 5736 tamponi: 3069 nel percorso nuove diagnosi (di cui 1166 nello screening con percorso Antigenico) e 2667 nel percorso guariti_

In bollettino, totale molecolari: 654939 (oggi) - 647536 (ieri) = 7403
Dato sbagliato e volontariamente gonfiato in quanto somma dei test molecolari di oggi (4570) ai test antigenici di ieri (2833).

L'incremento tamponi rispetto al giorno precedente riportato in bollettino e' 8569.
Dato sbagliato e volontariamente gonfiato in quanto somma i test molecolari di oggi (4570), agli antigenici di oggi (1166), sommati ancora agli antigenici di ieri (2833).

**Comment by Abalieno** [comment]
Sommario 25/01:

- **Il Campo "Tamponi processati con test molecolare" e' la SOMMA di molecolari e antigenici.**
- Si sommano **due volte** il numero di antigenici sul totale.

https://www.regione.marche.it/News-ed-Eventi/Post/70834/Coronavirus-Marche-aggiornamento-dati-dal-Servizio-Sanit%C3%A0-situazione-al-25-01-2021-ore-9-00
_nelle ultime 24 ore sono stati testati 2976 tamponi: 1862 nel percorso nuove diagnosi (di cui 1115 nello screening con percorso Antigenico) e 1114 nel percorso guariti_

In bollettino, totale molecolari: 657966 (oggi) - 654939 (ieri) = 3027
Dato sbagliato e volontariamente gonfiato in quanto somma i test molecolari di oggi (1861), agli antigenici di ieri (1166).

L'incremento tamponi rispetto al giorno precedente riportato in bollettino e' 4142.
Dato sbagliato e volontariamente gonfiato in quanto somma i test molecolari di oggi (1861), agli antigenici di oggi (1115), sommati ancora agli antigenici di ieri (1166).

**Comment by Abalieno** [comment]
Sospendo momentaneamente l'aggiornamento, dato: https://github.com/pcm-dpc/COVID-19/issues/1060

In bollettino risultano -13337 test molecolari meno di ieri. Nella speranza che vengano risolti i problemi, per il meglio, attendero' un qualche riallineamento nei prossimi giorni.

In ogni caso vengono segnalati +5365 tamponi fatti rispetto a ieri, dato comunque errato. Il numero corretto e' 4618.

Il numero errato in bollettino vien fuori sommando il totale tamponi totale reale (4618) al numero antigenici segnati in bollettino (1770), quindi sommando due volte gli antigenici, dato che sono inclusi nella prima somma. Ma oltre a questo non si capisce da dove arrivi quel 1770, dato che gli antigenici di oggi sono stati 1023, e quelli di ieri 1115.

https://www.regione.marche.it/News-ed-Eventi/Post/70848/Coronavirus-Marche-aggiornamento-dati-dal-Servizio-Sanit%C3%A0-situazione-al-26-01-2021-ore-9-00
_nelle ultime 24 ore sono stati testati 4618 tamponi: 2540 nel percorso nuove diagnosi (di cui 1023 nello screening con percorso Antigenico) e 2078 nel percorso guariti_

**Comment by Abalieno** [comment]
Veloce aggiornamento 27/01:

Sembra che (quasi) tutto sia a posto.

https://www.regione.marche.it/News-ed-Eventi/Post/70861/Coronavirus-Marche-aggiornamento-dati-dal-Servizio-Sanit%C3%A0-situazione-al-27-01-2021-ore-9-00
_nelle ultime 24 ore sono stati testati 5452 tamponi: 3301 nel percorso nuove diagnosi (di cui 1287 nello screening con percorso Antigenico) e 2151 nel percorso guariti_

Incremento tamponi totali di oggi in bollettino e' corretto: 5452

Il numero di antigenici in bollettino e' corretto: 20357 (oggi) - 19070 (ieri) = 1287 

Il numero di tamponi molecolari e' QUASI corretto: 648749 (oggi) - 644629 (ieri) = 4120
Il numero corretto dovrebbe essere 5452 (tamponi totali) - 1287 (antigenici) = 4165

Quindi un eccesso di appena 40 tamponi, che non si capisce come si ottiene dato che il numero di tamponi totali e antigenici ritorna.

**Comment by Abalieno** [comment]
28/01

Mi risulta tutto corretto. Se anche domani non ci sono problemi penso si possa anche chiudere.

L'unico aspetto riguarderebbe gli antigenici inseriti come molecolari per il mese di Dicembre. Un totale in eccesso di 50k circa. Ma almeno intanto abbiamo i dati progressivi giorno per giorno piu' vicini al vero.

**Comment by Abalieno** [comment]
29/01 chiudo, dato che anche i oggi i dati corrispondono.

Come detto, sul totale esiste ancora un eccesso di circa 50k, ma ora i dati giornalieri in bollettino sono coordinati con quelli riportati dalla regione.
