### ISSUE TITLE
Nuovi casi Campania 891 o 1021?

### ISSUE THREAD

**Issue by Rabelaiss** [pcm-dpc/COVID-19#1044]
La regione riporta 1021, facendo la differenza tra casi totali di oggi e ieri esce 1021 ma il dato `nuovi_positivi` in [dpc-covid19-ita-regioni-20210117.csv](https://github.com/pcm-dpc/COVID-19/blob/601bce47b1473b61f4a1bc884d95c0edaed5ad3b/dati-regioni/dpc-covid19-ita-regioni-20210117.csv) riporta 891.
Non ci sono avvisi a riguardo in [avvisi.md](https://github.com/pcm-dpc/COVID-19/blob/master/avvisi.md)
![image](https://user-images.githubusercontent.com/20670578/104849840-3767ae80-58ec-11eb-8576-80e90ceea261.png)

**Comment by Paulsword** [comment]
1021 è anche nel csv regionale https://github.com/pcm-dpc/COVID-19/blob/master/dati-regioni/dpc-covid19-ita-regioni-20210117.csv

**Comment by Rabelaiss** [comment]
@Paulsword ha fatto nuovo commit dopo che ho aperto la issue

**Comment by Paulsword** [comment]
@Rabelaiss sbaglio o la discrepanza rimane?

**Comment by Rabelaiss** [comment]
@Paulsword non mi sembra cosa intendi? nel file che hai inviato il dato `nuovi_positivi` è coretto ossia 1021, e hanno corretto anche quello nazionale passando da 12415 a 12545

**Comment by Paulsword** [comment]
Lo do per buono, ma qui resta 891 https://github.com/pcm-dpc/COVID-19/blob/601bce47b1473b61f4a1bc884d95c0edaed5ad3b/dati-regioni/dpc-covid19-ita-regioni-20210117.csv

**Comment by Paulsword** [comment]
A posto scusa
