### ISSUE TITLE
Errore di formattazione nel file dpc-covid19-ita-province.csv

### ISSUE THREAD

**Issue by Rabelaiss** [pcm-dpc/COVID-19#1046]
@umbros nel file [dpc-covid19-ita-province](https://raw.githubusercontent.com/pcm-dpc/COVID-19/master/dati-province/dpc-covid19-ita-province.csv) le prime righe contengono una virgola in meno, ossia una colonna in meno (13 colonne invece di 14), ecco a confronto la prima riga con l'ultima, dopo le coordinate lat long la prima contiene `0,,,` ossia 4 colonne, mentre l'ultima dopo lat long contiene `11757,,ITF,ITF1,ITF11` ossia 5 colonne.

`2020-02-24T18:00:00,ITA,13,Abruzzo,066,L'Aquila,AQ,42.35122196,13.39843823,0,,,`
`2021-01-18T17:00:00,ITA,13,Abruzzo,066,L'Aquila,AQ,42.35122196,13.39843823,11757,,ITF,ITF1,ITF11`

questo causa una lettura errata del file da parte di matlab, potresti correggere grazie.

**Comment by umbros** [comment]
Corretto, grazie

**Comment by Rabelaiss** [comment]
@umbros grazie, nel nuovo file c'è un errore alla riga 1589

`2020-03-07T18:00:00,ITA,03,Lombardia,017,Brescia,BS,45.53993052,10.21910323,413,pd-IT-0001,,`

**Comment by umbros** [comment]
ora ok.
Grazie
Umberto

**Comment by Rabelaiss** [comment]
@umbros grazie, scusa il disturbo ma ce ne sono altri alle righe 2846 2967 6214 15670 16117 16266 16818 16967 17116 e ne sto trovando altri

**Comment by Rabelaiss** [comment]
@umbros queste righe hanno 12 delimitatori invece di 13
Row 20997 has    12 delimiters
Row 21891 has    12 delimiters
Row 22040 has    12 delimiters
Row 22189 has    12 delimiters
Row 22636 has    12 delimiters
Row 22785 has    12 delimiters
Row 23322 has    12 delimiters
Row 23670 has    12 delimiters
Row 23977 has    12 delimiters
Row 24424 has    12 delimiters
Row 24573 has    12 delimiters
Row 25467 has    12 delimiters
Row 25757 has    12 delimiters
Row 25765 has    12 delimiters
Row 25914 has    12 delimiters
Row 26063 has    12 delimiters
Row 26212 has    12 delimiters
Row 26354 has    12 delimiters
Row 26361 has    12 delimiters
Row 27404 has    12 delimiters
Row 27687 has    12 delimiters
Row 27992 has    12 delimiters
Row 28000 has    12 delimiters
Row 28149 has    12 delimiters
Row 28298 has    12 delimiters
Row 28447 has    12 delimiters
Row 28894 has    12 delimiters
Row 29192 has    12 delimiters
Row 30086 has    12 delimiters
Row 30370 has    12 delimiters
Row 30373 has    12 delimiters
Row 30533 has    12 delimiters
Row 30831 has    12 delimiters
Row 31874 has    12 delimiters
Row 32023 has    12 delimiters
Row 33653 has    12 delimiters
Row 38719 has    12 delimiters
Row 38720 has    12 delimiters
Row 39473 has    12 delimiters
Row 42840 has    12 delimiters
Row 42873 has    12 delimiters
Row 42874 has    12 delimiters
Row 42875 has    12 delimiters
Row 42991 has    12 delimiters
Row 43345 has    12 delimiters
Row 46013 has    12 delimiters

**Comment by umbros** [comment]
Fatto lo stesso check e ora è ok.

**Comment by floatingpurr** [comment]
Vedere anche #945
