### ISSUE TITLE
Campi note con "virgole" nei dataset regioni

### ISSUE THREAD

**Issue by Artico77** [pcm-dpc/COVID-19#1049]
Vorrei segnalare che i campi "note", "note_test" e "note_casi" nei file dataset Regioni (file CSV), spesso riportano stringhe di testo che comprendono "virgole" al loro interno.

ad esempio nel file "dpc-covid19-ita-regioni-20210118.csv", il campo "note_casi" riporta: 
Si segnala il decesso dei pz.: - 1 uomo, 70 aa, Residente nella Provincia del Sud Sardegna - 1 uomo, 62 aa, Residente nella Città Metropolitana di Cagliari - 1 uomo, 89 aa, Residente nella Città Metropolitana di Cagliari - 1 uomo, 65 aa, Residente nella Provincia di Oristano

Le virgole che compaiono in queste stringhe di testo creano problemi in fase di importazione dei CSV poichè si confondono con le virgole che devono essere utilizzate come separatore di campi. 

E' possibile far ripulire i suddetti campi note dalle virgole per i dataset regioni pubblicati in futuro?
grazie

**Comment by aborruso** [comment]
Nei CSV è possibile avere la `,` come carattere in una cella, anche se il separatore è la stessa `,`.

Occorre però che il testo della cella sia tra `"`. E in questo file è così.

Si ha ad esempio `"Questo, è un testo di esempio"`. Se impostato così, il CSV non dà alcun problema.

**Comment by umbros** [comment]
Grazie @aborruso
