### ISSUE TITLE
totale_casi errato per la Valle d'Aosta (7698 invece di 7679)

### ISSUE THREAD

**Issue by Rabelaiss** [pcm-dpc/COVID-19#1051]
Il `totale_casi` al 19/1 in V.Aosta è 7684, oggi sono state comunicate 14 nuove diagnosi e la rimozione di 19 diagnosi riferite al 19/1 in quanto non confermate da successivo test molecolare, quindi i casi totali ad oggi sono 7684+14-19=7679, numero che compare anche nel [bollettino della regione](https://www.regione.vda.it/immagine.aspx?pk=75023).

Nel file [dpc-covid19-ita-regioni-20210120.csv](https://github.com/pcm-dpc/COVID-19/blob/master/dati-regioni/dpc-covid19-ita-regioni-20210120.csv) si legge invece che il `totale_casi` è pari a 7698, ossia 7684 più i 14 nuovi casi, quindi non risultano rimosse le 19 diagnosi non confermato.

@umbros errore vostro oppure vi sono arrivati già così i dati?

**Comment by umbros** [comment]
Non tocchiamo mai i dati ma provengono dalla Regione, abbiamo evidenziato il problema
