### ISSUE TITLE
Codici Nuts non corretti nel report delle regioni

### ISSUE THREAD

**Issue by Ugetto** [pcm-dpc/COVID-19#1052]
Buongiorno,
ho l'impressione che i codici nuts1 e nuts2 inseriti nelle tabelle relative alle Regioni siano sbagliati. Ad esempio Nuts2 della Lombardia viene dato ITI3 quando invece è ITC4.
Credo invece che i codici inseriti nelle tabelle delle Provincie siano esatti.
Saluti

**Comment by aborruso** [comment]
Buongiorno, è come dice @Ugetto , la Lombardia è `ITC4`.

@umbros [questi i codici](https://gist.github.com/aborruso/33e2f8fa64a9e99dc4712561926089d2) e le variazioni negli anni (la 2021 è la corrente).

Questa la fonte 

```
https://gisco-services.ec.europa.eu/distribution/v2/nuts/geojson/NUTS_LB_2021_4326_LEVL_2.geojson
```

| regulationYear | NUTS_NAME | NUTS_ID | LEVL_CODE | CNTR_CODE | NAME_LATN | FID |
| --- | --- | --- | --- | --- | --- | --- |
| 2003 | Abruzzo | ITF1 | 2 | IT |  | ITF1 |
| 2003 | Basilicata | ITF5 | 2 | IT |  | ITF5 |
| 2003 | Calabria | ITF6 | 2 | IT |  | ITF6 |
| 2003 | Campania | ITF3 | 2 | IT |  | ITF3 |
| 2003 | Emilia-Romagna | ITD5 | 2 | IT |  | ITD5 |
| 2003 | Friuli-Venezia Giulia | ITD4 | 2 | IT |  | ITD4 |
| 2003 | Lazio | ITE4 | 2 | IT |  | ITE4 |
| 2003 | Liguria | ITC3 | 2 | IT |  | ITC3 |
| 2003 | Lombardia | ITC4 | 2 | IT |  | ITC4 |
| 2003 | Marche | ITE3 | 2 | IT |  | ITE3 |
| 2003 | Molise | ITF2 | 2 | IT |  | ITF2 |
| 2003 | Piemonte | ITC1 | 2 | IT |  | ITC1 |
| 2003 | Provincia Autonoma Bolzano/Bozen | ITD1 | 2 | IT |  | ITD1 |
| 2003 | Provincia Autonoma Trento | ITD2 | 2 | IT |  | ITD2 |
| 2003 | Puglia | ITF4 | 2 | IT |  | ITF4 |
| 2003 | Sardegna | ITG2 | 2 | IT |  | ITG2 |
| 2003 | Sicilia | ITG1 | 2 | IT |  | ITG1 |
| 2003 | Toscana | ITE1 | 2 | IT |  | ITE1 |
| 2003 | Umbria | ITE2 | 2 | IT |  | ITE2 |
| 2003 | Valle d'Aosta/Vallée d'Aoste | ITC2 | 2 | IT |  | ITC2 |
| 2003 | Veneto | ITD3 | 2 | IT |  | ITD3 |
| 2006 | Abruzzo | ITF1 | 2 | IT | Abruzzo | ITF1 |
| 2006 | Basilicata | ITF5 | 2 | IT | Basilicata | ITF5 |
| 2006 | Calabria | ITF6 | 2 | IT | Calabria | ITF6 |
| 2006 | Campania | ITF3 | 2 | IT | Campania | ITF3 |
| 2006 | Emilia-Romagna | ITD5 | 2 | IT | Emilia-Romagna | ITD5 |
| 2006 | Friuli-Venezia Giulia | ITD4 | 2 | IT | Friuli-Venezia Giulia | ITD4 |
| 2006 | Lazio | ITE4 | 2 | IT | Lazio | ITE4 |
| 2006 | Liguria | ITC3 | 2 | IT | Liguria | ITC3 |
| 2006 | Lombardia | ITC4 | 2 | IT | Lombardia | ITC4 |
| 2006 | Marche | ITE3 | 2 | IT | Marche | ITE3 |
| 2006 | Molise | ITF2 | 2 | IT | Molise | ITF2 |
| 2006 | Piemonte | ITC1 | 2 | IT | Piemonte | ITC1 |
| 2006 | Provincia Autonoma Bolzano/Bozen | ITD1 | 2 | IT | Provincia Autonoma Bolzano/Bozen | ITD1 |
| 2006 | Provincia Autonoma Trento | ITD2 | 2 | IT | Provincia Autonoma Trento | ITD2 |
| 2006 | Puglia | ITF4 | 2 | IT | Puglia | ITF4 |
| 2006 | Sardegna | ITG2 | 2 | IT | Sardegna | ITG2 |
| 2006 | Sicilia | ITG1 | 2 | IT | Sicilia | ITG1 |
| 2006 | Toscana | ITE1 | 2 | IT | Toscana | ITE1 |
| 2006 | Umbria | ITE2 | 2 | IT | Umbria | ITE2 |
| 2006 | Valle d'Aosta/Vallée d'Aoste | ITC2 | 2 | IT | Valle d'Aosta/Vallée d'Aoste | ITC2 |
| 2006 | Veneto | ITD3 | 2 | IT | Veneto | ITD3 |
| 2010 | Abruzzo | ITF1 | 2 | IT | Abruzzo | ITF1 |
| 2010 | Basilicata | ITF5 | 2 | IT | Basilicata | ITF5 |
| 2010 | Calabria | ITF6 | 2 | IT | Calabria | ITF6 |
| 2010 | Campania | ITF3 | 2 | IT | Campania | ITF3 |
| 2010 | Emilia-Romagna | ITH5 | 2 | IT | Emilia-Romagna | ITH5 |
| 2010 | Friuli-Venezia Giulia | ITH4 | 2 | IT | Friuli-Venezia Giulia | ITH4 |
| 2010 | Lazio | ITI4 | 2 | IT | Lazio | ITI4 |
| 2010 | Liguria | ITC3 | 2 | IT | Liguria | ITC3 |
| 2010 | Lombardia | ITC4 | 2 | IT | Lombardia | ITC4 |
| 2010 | Marche | ITI3 | 2 | IT | Marche | ITI3 |
| 2010 | Molise | ITF2 | 2 | IT | Molise | ITF2 |
| 2010 | Piemonte | ITC1 | 2 | IT | Piemonte | ITC1 |
| 2010 | Provincia Autonoma di Bolzano/Bozen | ITH1 | 2 | IT | Provincia Autonoma di Bolzano/Bozen | ITH1 |
| 2010 | Provincia Autonoma di Trento | ITH2 | 2 | IT | Provincia Autonoma di Trento | ITH2 |
| 2010 | Puglia | ITF4 | 2 | IT | Puglia | ITF4 |
| 2010 | Sardegna | ITG2 | 2 | IT | Sardegna | ITG2 |
| 2010 | Sicilia | ITG1 | 2 | IT | Sicilia | ITG1 |
| 2010 | Toscana | ITI1 | 2 | IT | Toscana | ITI1 |
| 2010 | Umbria | ITI2 | 2 | IT | Umbria | ITI2 |
| 2010 | Valle d'Aosta/Vallée d'Aoste | ITC2 | 2 | IT | Valle d'Aosta/Vallée d'Aoste | ITC2 |
| 2010 | Veneto | ITH3 | 2 | IT | Veneto | ITH3 |
| 2013 | Abruzzo | ITF1 | 2 | IT | Abruzzo | ITF1 |
| 2013 | Basilicata | ITF5 | 2 | IT | Basilicata | ITF5 |
| 2013 | Calabria | ITF6 | 2 | IT | Calabria | ITF6 |
| 2013 | Campania | ITF3 | 2 | IT | Campania | ITF3 |
| 2013 | Emilia-Romagna | ITH5 | 2 | IT | Emilia-Romagna | ITH5 |
| 2013 | Friuli-Venezia Giulia | ITH4 | 2 | IT | Friuli-Venezia Giulia | ITH4 |
| 2013 | Lazio | ITI4 | 2 | IT | Lazio | ITI4 |
| 2013 | Liguria | ITC3 | 2 | IT | Liguria | ITC3 |
| 2013 | Lombardia | ITC4 | 2 | IT | Lombardia | ITC4 |
| 2013 | Marche | ITI3 | 2 | IT | Marche | ITI3 |
| 2013 | Molise | ITF2 | 2 | IT | Molise | ITF2 |
| 2013 | Piemonte | ITC1 | 2 | IT | Piemonte | ITC1 |
| 2013 | Provincia Autonoma di Bolzano/Bozen | ITH1 | 2 | IT | Provincia Autonoma di Bolzano/Bozen | ITH1 |
| 2013 | Provincia Autonoma di Trento | ITH2 | 2 | IT | Provincia Autonoma di Trento | ITH2 |
| 2013 | Puglia | ITF4 | 2 | IT | Puglia | ITF4 |
| 2013 | Sardegna | ITG2 | 2 | IT | Sardegna | ITG2 |
| 2013 | Sicilia | ITG1 | 2 | IT | Sicilia | ITG1 |
| 2013 | Toscana | ITI1 | 2 | IT | Toscana | ITI1 |
| 2013 | Umbria | ITI2 | 2 | IT | Umbria | ITI2 |
| 2013 | Valle d'Aosta/Vallée d'Aoste | ITC2 | 2 | IT | Valle d'Aosta/Vallée d'Aoste | ITC2 |
| 2013 | Veneto | ITH3 | 2 | IT | Veneto | ITH3 |
| 2016 | Abruzzo | ITF1 | 2 | IT | Abruzzo | ITF1 |
| 2016 | Basilicata | ITF5 | 2 | IT | Basilicata | ITF5 |
| 2016 | Calabria | ITF6 | 2 | IT | Calabria | ITF6 |
| 2016 | Campania | ITF3 | 2 | IT | Campania | ITF3 |
| 2016 | Emilia-Romagna | ITH5 | 2 | IT | Emilia-Romagna | ITH5 |
| 2016 | Friuli-Venezia Giulia | ITH4 | 2 | IT | Friuli-Venezia Giulia | ITH4 |
| 2016 | Lazio | ITI4 | 2 | IT | Lazio | ITI4 |
| 2016 | Liguria | ITC3 | 2 | IT | Liguria | ITC3 |
| 2016 | Lombardia | ITC4 | 2 | IT | Lombardia | ITC4 |
| 2016 | Marche | ITI3 | 2 | IT | Marche | ITI3 |
| 2016 | Molise | ITF2 | 2 | IT | Molise | ITF2 |
| 2016 | Piemonte | ITC1 | 2 | IT | Piemonte | ITC1 |
| 2016 | Provincia Autonoma di Bolzano/Bozen | ITH1 | 2 | IT | Provincia Autonoma di Bolzano/Bozen | ITH1 |
| 2016 | Provincia Autonoma di Trento | ITH2 | 2 | IT | Provincia Autonoma di Trento | ITH2 |
| 2016 | Puglia | ITF4 | 2 | IT | Puglia | ITF4 |
| 2016 | Sardegna | ITG2 | 2 | IT | Sardegna | ITG2 |
| 2016 | Sicilia | ITG1 | 2 | IT | Sicilia | ITG1 |
| 2016 | Toscana | ITI1 | 2 | IT | Toscana | ITI1 |
| 2016 | Umbria | ITI2 | 2 | IT | Umbria | ITI2 |
| 2016 | Valle d'Aosta/Vallée d'Aoste | ITC2 | 2 | IT | Valle d'Aosta/Vallée d'Aoste | ITC2 |
| 2016 | Veneto | ITH3 | 2 | IT | Veneto | ITH3 |
| 2021 | Abruzzo | ITF1 | 2 | IT | Abruzzo | ITF1 |
| 2021 | Basilicata | ITF5 | 2 | IT | Basilicata | ITF5 |
| 2021 | Calabria | ITF6 | 2 | IT | Calabria | ITF6 |
| 2021 | Campania | ITF3 | 2 | IT | Campania | ITF3 |
| 2021 | Emilia-Romagna | ITH5 | 2 | IT | Emilia-Romagna | ITH5 |
| 2021 | Friuli-Venezia Giulia | ITH4 | 2 | IT | Friuli-Venezia Giulia | ITH4 |
| 2021 | Lazio | ITI4 | 2 | IT | Lazio | ITI4 |
| 2021 | Liguria | ITC3 | 2 | IT | Liguria | ITC3 |
| 2021 | Lombardia | ITC4 | 2 | IT | Lombardia | ITC4 |
| 2021 | Marche | ITI3 | 2 | IT | Marche | ITI3 |
| 2021 | Molise | ITF2 | 2 | IT | Molise | ITF2 |
| 2021 | Piemonte | ITC1 | 2 | IT | Piemonte | ITC1 |
| 2021 | Provincia Autonoma di Bolzano/Bozen | ITH1 | 2 | IT | Provincia Autonoma di Bolzano/Bozen | ITH1 |
| 2021 | Provincia Autonoma di Trento | ITH2 | 2 | IT | Provincia Autonoma di Trento | ITH2 |
| 2021 | Puglia | ITF4 | 2 | IT | Puglia | ITF4 |
| 2021 | Sardegna | ITG2 | 2 | IT | Sardegna | ITG2 |
| 2021 | Sicilia | ITG1 | 2 | IT | Sicilia | ITG1 |
| 2021 | Toscana | ITI1 | 2 | IT | Toscana | ITI1 |
| 2021 | Umbria | ITI2 | 2 | IT | Umbria | ITI2 |
| 2021 | Valle d’Aosta/Vallée d’Aoste | ITC2 | 2 | IT | Valle d’Aosta/Vallée d’Aoste | ITC2 |
| 2021 | Veneto | ITH3 | 2 | IT | Veneto | ITH3 |

**Comment by aborruso** [comment]
@umbros occhio a questa faccenda dei codici.

Grazie

**Comment by umbros** [comment]
Grazie della segnalazione, corretti ed allineati alla 2021
https://github.com/pcm-dpc/COVID-19/commit/27370c643da2aa8b7c805ff80daa3a784596448c

**Comment by aborruso** [comment]
Grazie @umbros
