### ISSUE TITLE
Info indici RT e colori regioni

### ISSUE THREAD

**Issue by chuck2098** [pcm-dpc/COVID-19#1056]
**Tipo di richiesta**: richiesta di informazione

Salve, 
come da titolo, chiedo a voi se siete riusciti a trovare una repository o qualche api per il retrieve degli indici RT delle regioni e dei rispettivi colori.

Grazie, Saluti

**Comment by Kisswolf72** [comment]
seguo

**Comment by LucaZeta** [comment]
Volendo potete utilizzare un servizio php appena reso disponibile:
https://covid19.zappi.me/coloreRegioni.php

Viene restituita una stringa codificata json con una intuitiva struttura a due livelli:
![immagine](https://user-images.githubusercontent.com/45511384/105631192-857d3480-5e4d-11eb-8442-1766aa423782.png)

Accedendo all'URL con FireFox dovreste essere in grado di ottenere il corrispondente dell'immagine.
accedendo all'ulr tramite comando curl si ottiene una stringa di questo tipo:

"{"gialla":["Campania","Basilicata","Molise","Provincia autonoma di Trento","Toscana"],"arancione":["Abruzzo","Calabria","Emilia Romagna","Friuli Venezia Giulia","Lazio","Liguria","Lombardia","Marche","Veneto","Piemonte","Puglia","Sardegna","Umbria","Valle d\u2019Aosta"],"rossa":["Provincia Autonoma di Bolzano","Sicilia"]}"

Massima disponibilità, ma nessuna responsabilità se usando il servizio si sveglia il gatto.

**Comment by Ale4224** [comment]
Ciao, per l'indice dlel'Rt ho implementato il calcolo trovato su [wikipedia ](https://it.wikipedia.org/wiki/Numero_di_riproduzione_di_base#Numero_di_riproduzione_netto_al_tempo_t) nel mio [sito web](https://ale4224.github.io/coviditalia/) contenente grafici vari

Il sito è [open source](https://github.com/Ale4224/coviditalia), potete rubare l'algoritmo se volete :D

**Comment by chuck2098** [comment]
Buonasera,
vi ringrazio per le risposte.
In ogni caso, ho poi risolto con queste due repositories:
https://github.com/italia/covid19-opendata-vaccini
https://github.com/CloudItaly/Indice-RT

In caso di problemi, non esiterò a provare anche le vostre soluzioni.
Saluti a tutti.
