### ISSUE TITLE
Numero di Malati Asintomatici (senza sintomi)

### ISSUE THREAD

**Issue by tailot** [pcm-dpc/COVID-19#106]
**Tipo di richiesta**: richiesta di dati

## Riassunto

Se è disponibile potrebbe essere interessante avere il numero dei pazienti malati e asintomatici.

## Interesse pubblico

Aiutare la ricerca ed avere un dato statistico in più sulla malattia.

**Comment by umbros** [comment]
@tailot per quanto riguarda i pazienti malati sono definiti dai campi ricoverati_con_sintomi e terapia_intensiva e totalizzati nel campo totale_ospedalizzati, gli asintomatici, ovviamente, non c'è modo di monitorarli.
