### ISSUE TITLE
Dati tamponi non rispondenti a quanto riportato sul pdf elaborato

### ISSUE THREAD

**Issue by umbros** [pcm-dpc/COVID-19#1060]
Il dato dei tamponi non corrisponde a quanto riportato, il dato sarà corretto nella giornata di domani anche su giorni precedenti.

**Comment by umbros** [comment]
I dati del CSV sono corretti ma non corretti quelli del pdf inviato da Ministero della Salute.

**Comment by gmoscelli** [comment]
Gentile Umberto, 
è possibile in qualche modo ottenere i dati sul numero effettuato di tamponi a livello giornaliero per provincia, da inizio pandemia? 

Cordiali saluti,
Giuseppe
