### ISSUE TITLE
Possibile errore sui casi positivi della PA Bolzano il gg 26/1/2021

### ISSUE THREAD

**Issue by ornolio** [pcm-dpc/COVID-19#1061]
Tipo di issue:

- [x ] Dati mancanti o errati 
- [ ] Errore nella documentazione 
- [ ] Errore or mancanza nella dashboard 
- [ ] Problemi di visualizzazione nella dashboard 

- Regione: PA Bolzano
- Provincia: 

## Riassunto

I Nuovi positivi superano i casi testati: i casi testati il giorno 26/1 sono 355 (175974 tot al 26/1  - 175619 tot al 25/1), con 559 positivi.
**Attesa:**

Nuovi positivi non superiori ai casi testati.
**Attuale:**

**Comment by mxmt68** [comment]
Notato anche io.
Purtroppo (almeno per la provincia di Bolzano) vedo che i dati sono incomparabili. Dal sito provinciale http://www.provincia.bz.it/sicurezza-protezione-civile/protezione-civile/dati-attuali-sul-coronavirus.asp risulta:

- 355 persone sottoposte al test molecolare (PCR). Non vi è il dato corrispondente per il solo antigenico
- 86 positivi al test molecolare (PCR) + 473 positivi all' antigenico = 559

Di conseguenza il dato casi testati sembra contenere solo i PCR. Ma questo per la provincia di Bolzano.

**Comment by MicheleAlfinito** [comment]
Possibile comunque che i positivi vengano anche solo dai tamponi, in caso di screening ripetuti.
Rimando a #864
