### ISSUE TITLE
Dati duplicati 25 e 26 gennaio 2021

### ISSUE THREAD

**Issue by eguidotti** [pcm-dpc/COVID-19#1062]
Tipo di issue:

- [x] Dati mancanti o errati 
- [ ] Errore nella documentazione 
- [ ] Errore or mancanza nella dashboard 
- [ ] Problemi di visualizzazione nella dashboard 

- Regione: Dati nazionali
- Provincia: Dati nazionali

## Riassunto

Il file https://github.com/pcm-dpc/COVID-19/blob/master/dati-andamento-nazionale/dpc-covid19-ita-andamento-nazionale.csv contiene righe duplicate per il 25 e 26 gennaio 2021

**Attesa:**

Rimuovere le righe duplicate

**Comment by aborruso** [comment]
Sono duplicate, ad eccezione dei campi `tamponi_test_molecolare` e `tamponi_test_antigenico_rapido`

**Comment by umbros** [comment]
Corretto grazie
