### ISSUE TITLE
Delta negativo tamponi Marche 25 Gennaio

### ISSUE THREAD

**Issue by magaspari** [pcm-dpc/COVID-19#1065]
Tipo di issue:

- [ ] Dati mancanti o errati 
- [ ] Errore nella documentazione 
- [ ] Errore or mancanza nella dashboard 
- [ ] Problemi di visualizzazione nella dashboard 

- Regione:
- Provincia: 

## Riassunto

**Attesa:**

**Attuale:** 

Il 25 Gennaio sono stati tolti -13905 Tamponi molecolari dalla regione Marche, 
si tratta di un errore o di una correzione come alcune precedenti?

**Comment by Abalieno** [comment]
Fino al 25 venivano sommati gli antigenici ai molecolari, nel campo dei molecolari: #1042

Quindi, alcuni di questi, sono stati tolti. Penso siano stati tolti quelli di Gennaio, da quando gli antigenici sono stati inseriti in bollettino.

**Comment by magaspari** [comment]
Grazie!

**Comment by magaspari** [comment]
.
