### ISSUE TITLE
File codice condotta collaboratori in lingua italiana

### ISSUE THREAD

**Issue by marcodadamo** [pcm-dpc/COVID-19#107]
---
name: Creazione file CODICE DI CONDOTTA.MD (LINGUA ITALIANA)
about: Richiesta di creazione del file codice di condotta in lingua italiana
---

**Tipo di richiesta**: suggerimento di miglioramento (creazione file .md) 

## Riassunto
Creare un file codice condotta in lingua italiana.

**CODICE DI CONDOTTA PER I COLLABORATORI** 
Inserire i sueguenti punti:
1. **Impegno nella collaborazione**
2. **Modelli standard**
3. **Le responsabilità**
4. **Ambito**
5. **Istanze di rinforzo**
6. **Attribuzioni** 

## Interesse pubblico
File disponibile in versione lingua italiana.

**Comment by umbros** [comment]
Done!
