### ISSUE TITLE
Cambio nome file aree

### ISSUE THREAD

**Issue by aborruso** [pcm-dpc/COVID-19#1072]
Buongiorno @pierluigicara ,
ho visto che hai aggiornato il file, grazie.

C'è stato però credo un cambio di nome, da `dpc-covid-19-aree-nuove-g-json.zip` a `dpc-covid-19-ita-aree-nuove-g-json.zip`, che mi sembra non sia stato comunicato con preavviso.
Potreste per favore avvisare con qualche giorno di anticipo?

Buona serata

![image](https://user-images.githubusercontent.com/30607/107234248-c23b5500-6a23-11eb-83e6-16eeae26db09.png)

**Comment by pierluigicara** [comment]
Grazie della segnalazione, si tratta di un refuso, il file verrà corretto.

**Comment by aborruso** [comment]
Grazie a te
