### ISSUE TITLE
Numero tamponi delle Marche in data 12/02 errato (errore di immissione)

### ISSUE THREAD

**Issue by Abalieno** [pcm-dpc/COVID-19#1078]
Tipo di issue:

- [ X ] Dati mancanti o errati 
- [ ] Errore nella documentazione 
- [ ] Errore or mancanza nella dashboard 
- [ ] Problemi di visualizzazione nella dashboard 

- Regione: Marche

In bollettino vengono segnati oggi (12/02) 18.000 tamponi inesistenti. 

Il numero di tamponi totale in bollettino e' 764.607, quello riportato dalla regione e' 746.607.

E' evidente una inversione del 46 a 64, quindi un errore di immissione.

Lo si puo' verificare sia dal numero di tamponi totali in questo pdf:
https://www.regione.marche.it/News-ed-Eventi/Post/71046/Coronavirus-Marche-aggiornamento-dati-dal-Servizio-Sanit%C3%A0-situazione-al-12-02-2021-ore-12-00

Sia dai dati giornalieri:
https://www.regione.marche.it/News-ed-Eventi/Post/71033/Coronavirus-Marche-aggiornamento-dati-dal-Servizio-Sanit%C3%A0-situazione-al-12-02-2021-ore-9-00
_Il Servizio Sanità della Regione Marche ha comunicato che nelle ultime 24 ore sono stati testati 5229 tamponi: 3414 nel percorso nuove diagnosi (di cui 1225 nello screening con percorso Antigenico) e 1815 nel percorso guariti_

Essendo i tamponi giornalieri 5229, mentre il numero riportato in bollettino nazionale e' 23.229:
23.229 - 5.229 = 18.000
Appunto.

Questi 18.000 in piu' sono tutti stati inseriti come tamponi molecolari.

Differenza da ieri molecolari in bollettino: 723.732 - 701.728 = 22.004
Tamponi molecolari di oggi corretti: 5229 - 1225 = 4004
18.000 + 4.004 = 22.004

**Comment by tummarellox** [comment]
Stavo per aprire io l'issue e segnalare lo stesso. Sempre preciso e attento @Abalieno  :D

**Comment by Abalieno** [comment]
Mi sembra sia stato corretto oggi, quindi chiudo.

**Comment by tummarellox** [comment]
Segnalo che nel bollettino nazionale odierno, 22 maggio (https://github.com/pcm-dpc/COVID-19/blob/master/schede-riepilogative/regioni/dpc-covid19-ita-scheda-regioni-20210522.pdf) l'incremento dei tamponi complessivi effettuati dalla regione Marche risulta essere **4348**, quando il numero reale, come riportato dal bollettino quotidiano della Regione Marche disponibile qui: https://www.regione.marche.it/News-ed-Eventi/Post/75600/Coronavirus-Marche-aggiornamento-dati-dal-Servizio-Sanit%C3%A0-situazione-al-22-05-2021-ore-9-00 risulta essere invece di **3422** tamponi.
