### ISSUE TITLE
Number of tests for Lombardia generates negative values on day-by-day difference

### ISSUE THREAD

**Issue by ianny82** [pcm-dpc/COVID-19#108]
Type of issue:

-  Incorrect or missing data : 
- [ ] Incorrect or missing documentation 
- [ ] Incorrect or missing data in the dashboard 
- [ ] Layout problem in the dashboard 

## Summary

I assume the column "tamponi"  indicates the cumulative number of tests performed over days. If we take the day-by-day difference of this column for Lombardia, then we get a negative number between February 25th and 26th, 2020. On February 25th, the column indicates 3700 whereas on Feb 26th it indicates 3208 (on Feb 27th it is 3320).

**Expected:**

I would expect only numbers >=0 by taking the day-by-day difference of the column tamponi.

**Actual:** 

We get a negative value for Lombardia on column "tamponi" when considering the difference between February 26th and February 25th 3208-3700 = -492

**Comment by federico-vitale** [comment]
I'm interested in this as well - #71 - and I've seen that it happens also in other "total" values (for example in "total cases" for Liguria on 1/3/2020)

**Comment by LBreda** [comment]
Is it actually a problem? The new cases seems to be the difference between the actual new cases and the healed+dead. It can be a negative number.

**Comment by ianny82** [comment]
> Is it actually a problem? The new cases seems to be the difference between the actual new cases and the healed+dead. It can be a negative number.

I'm talking about the number of tests (tamponi) not new cases. @federico-vitale is instead mentioning "totale_casi", which also shouldn't be negative (unless cleaned by potential false positives...if any).

**Comment by federico-vitale** [comment]
@ianny82 right said, I opened #71 just because I've seen decreasing the total number of both swabs and cases (generally data that are cumulative, to my understanding)

**Comment by umbros** [comment]
Hi, the number of tests is an indicated number of tests made, any negatives may depend on incorrect communication of information, to underline that 1 test does not represent 1 person but 1 person may have made n tests.
