### ISSUE TITLE
Righe duplicate 1 marzo 2021 (nazionale e regioni)

### ISSUE THREAD

**Issue by Doc73** [pcm-dpc/COVID-19#1086]
Tipo di issue:

- [x] Dati mancanti o errati dpc-covid19-ita-andamento-nazionale.csv
- [ ] Errore nella documentazione 
- [ ] Errore or mancanza nella dashboard 
- [ ] Problemi di visualizzazione nella dashboard 

- Regione:
- Provincia: 

## Riassunto

Duplicata la riga del primo marzo 2021

Si prega di correggere, grazie!

**Attesa:**

**Attuale:**

**Comment by Rabelaiss** [comment]
ancora con questi errori dopo 1 anno ormai, possibile che non si riesca ad implementare un controllo automatico?

**Comment by Doc73** [comment]
@Rabelaiss 
Stesso errore anche nel file delle regioni

**Comment by floatingpurr** [comment]
Ho provato a riassumere la questione nella #1081 spero ci possa essere un feedback

**Comment by floatingpurr** [comment]
Idem sui JSON. Devono avere una sorta di procedura che parte da dei dati tabellari e serializza CSV e JSON (just guessing, in attesa di chiarimenti).

**Comment by alexodus** [comment]
@umbros pippone di merda, risolvi please!!!!

**Comment by alexodus** [comment]
Ragazzi, scusatemi, ma questo imbecille va trattato così. E' maleducato con chi gli propone soluzioni ed è totalmente incapace.

**Comment by CapMar00** [comment]
Bisognerebbe per favore sistemare anche questo file .json che ha 3 volte la data del 1 marzo:
https://raw.githubusercontent.com/pcm-dpc/COVID-19/master/dati-json/dpc-covid19-ita-andamento-nazionale.json
Grazie

**Comment by alexodus** [comment]
> Bisognerebbe per favore sistemare anche questo file .json che ha 3 volte la data del 1 marzo:
> https://raw.githubusercontent.com/pcm-dpc/COVID-19/master/dati-json/dpc-covid19-ita-andamento-nazionale.json
> Grazie

Verrebbe da ridere se non ci fosse da piangere. Sono almeno 10 mesi che gli si propone (compreso il sottoscritto) di fare script di validazione dei dati. Penso che qui, chiunque abbia un minimo di destrezza saprebbe creane uno sensato in poche ore. Sono almeno 10 mesi che il tizio si rifiuta sia di implementarli che di farsi aiutare dalla "community".

**Comment by Doc73** [comment]
Il file nazionale è stato corretto, ma non ancora quello regionale

**Comment by Rabelaiss** [comment]
comunque non mi sembra il caso di insultare

**Comment by DataEnthusiast84** [comment]
Mi sono preso un colpo!  😮 
<img width="1005" alt="Schermata 2021-03-01 alle 18 23 21" src="https://user-images.githubusercontent.com/61232774/109534158-5052aa80-7abb-11eb-96fb-8180d023b834.png">

**Comment by alexodus** [comment]
> comunque non mi sembra il caso di insultare

Se una persona in 10 mesi ha fatto qualcosa come un centinaio di errori (spesso gli stessi e dei più assurdi, tipo json con doppie parentesi graffe di chiusura) tu che diresti? Cosa pensi di uno che a decine di offerte di aiuto a creare script di validazione si è sempre opposto fermamente (non rispondendo)? Cosa pensi di uno che fa malissimo un lavoro per cui viene pagato con i soldi di noi contribuenti?
Quindi insultarlo è l'estrema ratio, visto che il tizio in questione si è rifiutato (in issue che fiurbescamente ha cancellato) di indicarmi un suo superiore verso cui fare escalation al fine di rimuoverlo dal progetto.

Qui sotto posto stesso errore fatto mese scorso.
![image](https://user-images.githubusercontent.com/2721510/109536705-5ac27380-7abe-11eb-9b14-c3f7fe9b2a4a.png)

**Comment by FragIt66** [comment]
@floatingpurr  può darsi che partano da dati tabellari. Però , se così fosse,  perchè non si creano almeno gli  indici "unique"?  Sul json dei dati nazionali di oggi il primo marzo compare tre volte ....... basterebbe creare un indice unuque sulla data e saresti a posto  non c'è da implementare chissà cosa ....  :-(

**Comment by emazep** [comment]
> 
> 
> Ragazzi, scusatemi, ma questo imbecille va trattato così. E' maleducato con chi gli propone soluzioni ed è totalmente incapace.

@alexodus: cancella i tuoi commenti intemperanti e augurati che la persona a cui li hai rivolti non ti quereli. Che tu segua o meno il mio consiglio, questo commento serve a prendere le distanze da soggetti come te. Personalmente sono stato più che critico riguardo l'assenza di controlli automatizzati di consistenza e integrità dei dati (chiaramente evidenziata dalla frequenza con cui ricorrono questi errori), ma non mi permetterei mai di usare questo linguaggio, per giunta senza conoscere la situazione nella quale la persona a cui ti stai rivolgendo si trova ad operare.

**Comment by alexodus** [comment]
> @alexodus: cancella i tuoi commenti smodati e augurati che la persona a cui li hai rivolti non ti quereli. Che tu segua o meno il mio consiglio, questo commento serve a prendere le distanze dalle tue intemperanze. Personalmente sono stato più che critico riguardo l'assenza di controlli automatizzati di consistenza e integrità dei dati (chiaramente evidenziata dalla frequenza con cui ricorrono questi errori), ma non mi permetterei mai di usare questo linguaggio, per giunta senza conoscere la situazione nella quale la persona a cui ti stai rivolgendo si trova ad operare.

ho seguito il tuo consiglio, ma per il solo motivo che ho deciso di abbandonare lo sviluppo della mia app/webapp. Ho fatto l'ennesima figura di merda con i miei utenti per colpa di una gestione davvero pessima e vergognosa (oltre che pagata da noi tutti, te compreso). Errare è umanissimo, ma non rispondere nemmeno alle numerose issue che chiedono spiegazioni o offrono aiuto per la validazione dei dati è assai grave. Io non mi sognerei mai di non spiegare il perché non si possono validare i dati. Anche se ci fosse un problema di budget avrei l'educazione di dirlo. Qui niente. E ripeto: è gravissimo.
D'ora in avanti divertitevi voi.

**Comment by emazep** [comment]
> ho seguito il tuo consiglio [...]

Hai fatto benissimo. Allora cancellerò anche il mio commento, che non ha più ragione di rimanere (e poi cancellerò anche questo). Grazie.

**Comment by pcatta1966** [comment]
> Mi sono preso un colpo! 😮
> 
> Per fortuna esiste la community...
> meno male si... anch'io.....

![image](https://user-images.githubusercontent.com/61948662/109559825-78520600-7adb-11eb-8e1f-d02b1612d80d.png)

**Comment by floatingpurr** [comment]
> @floatingpurr può darsi che partano da dati tabellari. Però , se così fosse, perchè non si creano almeno gli indici "unique"? Sul json dei dati nazionali di oggi il primo marzo compare tre volte ....... basterebbe creare un indice unuque sulla data e saresti a posto non c'è da implementare chissà cosa .... :-(

Ci sono diverse soluzioni relativamente lineari per ovviare a questo tipo di problemi. Credo che finché non verrà implementata una procedura di verifica, ci dovremmo aspettare errori del genere di tanto in tanto.

Spiace un po' che non ci sia stato neppure un riscontro sul tema "validazione dati" dato che è stato sollevato da diverse persone e a più riprese (#1081, #945, #982 ecc...). Comprendo però che per @umbros e i collaboratori del Dipartimento non sia facile stare dietro a tutto.

**Comment by DataEnthusiast84** [comment]
> > Mi sono preso un colpo! 😮
> > Per fortuna esiste la community...
> > meno male si... anch'io.....
> 
> ![image](https://user-images.githubusercontent.com/61948662/109559825-78520600-7adb-11eb-8e1f-d02b1612d80d.png)

anche tu Qliksense addicted? 😄

**Comment by DataEnthusiast84** [comment]
> > Bisognerebbe per favore sistemare anche questo file .json che ha 3 volte la data del 1 marzo:
> > https://raw.githubusercontent.com/pcm-dpc/COVID-19/master/dati-json/dpc-covid19-ita-andamento-nazionale.json
> > Grazie
> 
> Verrebbe da ridere se non ci fosse da piangere. Sono almeno 10 mesi che gli si propone (compreso il sottoscritto) di fare script di validazione dei dati. Penso che qui, chiunque abbia un minimo di destrezza saprebbe creane uno sensato in poche ore. Sono almeno 10 mesi che il tizio si rifiuta sia di implementarli che di farsi aiutare dalla "community".

Vado un po' OT: 
mi piacerebbe approfondire la tematica di validazione dati. Puoi indicarmi qualche fonte/strumento?

**Comment by pcatta1966** [comment]
Anche per lavoro..
👍

Il lun 1 mar 2021, 23:42 DataEnthusiast84 <notifications@github.com> ha
scritto:

**Comment by alexodus** [comment]
> > > Bisognerebbe per favore sistemare anche questo file .json che ha 3 volte la data del 1 marzo:
> > > https://raw.githubusercontent.com/pcm-dpc/COVID-19/master/dati-json/dpc-covid19-ita-andamento-nazionale.json
> > > Grazie
> > 
> > 
> > Verrebbe da ridere se non ci fosse da piangere. Sono almeno 10 mesi che gli si propone (compreso il sottoscritto) di fare script di validazione dei dati. Penso che qui, chiunque abbia un minimo di destrezza saprebbe creane uno sensato in poche ore. Sono almeno 10 mesi che il tizio si rifiuta sia di implementarli che di farsi aiutare dalla "community".
> 
> Vado un po' OT:
> mi piacerebbe approfondire la tematica di validazione dati. Puoi indicarmi qualche fonte/strumento?

#1081

**Comment by CloudItaly** [comment]
> @floatingpurr può darsi che partano da dati tabellari. Però , se così fosse, perchè non si creano almeno gli indici "unique"? Sul json dei dati nazionali di oggi il primo marzo compare tre volte ....... basterebbe creare un indice unuque sulla data e saresti a posto non c'è da implementare chissà cosa .... :-(

Anche io son corso a questa soluzione, per non incorrere più in questi problemi.

**Comment by FragIt66** [comment]
Ferma restando l'utilità dell'indice dovrebbe comunque esistere un controllo a monte. 
Non è bello fare affidamento solo su un indice per  "proteggere" una chiave ( primaria o unique che sia )  
E, al di là dei toni, trovo assurdo che un repository istituzionale come questo - dopo un anno - sia ancora spesso in uno stato indecente.

**Comment by umbros** [comment]
Corretto, grazie

**Comment by floatingpurr** [comment]
Ciao, segnalo che i JSON sono ancora sbagliati

**Comment by umbros** [comment]
Viene corretto con la prossima commit.
