### ISSUE TITLE
dati duplicati

### ISSUE THREAD

**Issue by setteZ** [pcm-dpc/COVID-19#1087]
Tipo di issue:

- [x] Dati duplicati in dpc-covid19-ita-andamento-nazionale.json
- [ ] Dati mancanti o errati 
- [ ] Errore nella documentazione 
- [ ] Errore or mancanza nella dashboard 
- [ ] Problemi di visualizzazione nella dashboard 

- Regione:
- Provincia: 

## Riassunto

nel file dpc-covid19-ita-andamento-nazionale.json i dati del 01-03-2021 sono riportati 3 volte

**Attesa:**

eliminare i dati doppi

**Comment by umbros** [comment]
risolto con l'ultima commit: https://github.com/pcm-dpc/COVID-19/commit/bb9987a44a80e4927ead3048e75237f861977c87
