### ISSUE TITLE
Dati province

### ISSUE THREAD

**Issue by riccste** [pcm-dpc/COVID-19#1088]
Al fine di valutare in maniera più accurata la casistica ed il rischio locale delle singole province, sarebbe utile avere anche i dati dei positivi, tamponi effettuati, guariti, deceduti ecc...
Questi dati li ho però solo trovati nei dati globali delle regioni, mentre nei dati province c'è solo la colonna Totale casi.
È possibile reperire gli stessi dati delle regioni anche per le province?

Grazie

**Comment by joefoxcmcc** [comment]
Hai poi trovato una soluzione?

**Comment by pierluigicara** [comment]
Il flusso dei dati che alimenta questo repository e che è stato recentemente meglio illustrato nel Readme non prevede a livello provinciale l'analogo dettaglio che è presente a livello regionale. Le ragioni di questa situazione di fatto sono state più volte illustrate in sedi pubbliche (vedi ad es [qui](https://www.youtube.com/watch?v=QOd1SKzxRqA&t=17385s oppure [qui](http://eventipa.formez.it/node/311755). In sintesi, la mancanza di un quadro omogeneo nazionale quotidiano sulla disponibilità di queste informazioni e il conseguente mancato conferimento quotidiano da parte del Ministero della Salute si possono considerare le ragioni principali. Le medesime informazioni sono invece trattate dall'Istituto Superiore di Sanità con cadenza settimanale nei propri bollettini pubblicati [qui](https://www.epicentro.iss.it/coronavirus/sars-cov-2-sorveglianza-dati), nell'ambito del Sistema di sorveglianza integrata COVID-19 in Italia descritto [qui](https://www.epicentro.iss.it/coronavirus/sars-cov-2-sorveglianza).
