### ISSUE TITLE
Wrong geoJson file

### ISSUE THREAD

**Issue by AlessandroAnnini** [pcm-dpc/COVID-19#109]
Type of issue:

- [x] Incorrect or missing data : 
- [ ] Incorrect or missing documentation 
- [ ] Incorrect or missing data in the dashboard 
- [ ] Layout problem in the dashboard 

## Summary

The map produced by the geoJson file has a lot of provinces missing

**Expected:**

I expect a map like the one that you can get from [this geoJson](https://github.com/deldersveld/topojson/blob/master/countries/italy/italy-provinces.json)
that is **124kb**

**Actual:** 
At the moment I can get this one: 
![image](https://user-images.githubusercontent.com/3852307/76411125-6be81100-6391-11ea-874c-8cfa9e8dfa84.png)

for **7.2 Mb**!

My advice is to get the file used in deldersveld repo and fix some province name so that they match with `sigla_provincia` from the json with the data

I have already done this, crossing the map with the data and giving color interpolation and I get this:

![image](https://user-images.githubusercontent.com/3852307/76411299-d1d49880-6391-11ea-900c-a113f879e628.png)

Sardegna is the only region with something wrong in the provinces for now.

**Comment by pierluigicara** [comment]
Hi @AlessandroAnnini the dataset is concerned ONLY the related administrative units citated by the DPCMs dealing with measurements to contain COVID19 in Italy and NOT all the provinces in Italy. For this please see the cartogrphic section on istat.it.
This means that every feature in the dataset is related with a juridic act that apply speciphic restrictions on that area, for example for the DPCM 1.3.2020 all.1 are 11 municipalities and for all.3 in the same DPCM are 4 provinces. This according with INSPIRE Data Model for Area Management and Restriction Theme.

**Comment by AlessandroAnnini** [comment]
While I completely understand your point, and please correct me if I'm wrong, I still would like to say that:

- every province of Italy is under COVID19 measurements
- even if the same measurement covers more provinces, drawing the map this way is absolutely not interesting for the general audience
- divide data for province and areas for DPCMs is a big consistency flaw

I think that DPCMs ara important so you can add to every province data 2 fields: `dpcm_number` and `dpcm_date` to have the exact dpcm reference and date of enforcement.

> _As a side note I would thank you all for your work, I thought having a github repo like this was not possible in Italy instead this is nothing short that **AMAZING**

**Comment by pierluigicara** [comment]
Thank you for your endorsement.
I understand what you mean, but at the moment this is out of scope for us and furthermore it would made us non conform to the Inspire AM [data model](https://inspire.ec.europa.eu/id/document/tg/am) that is, on the contrary, our goal.

**Comment by AlessandroAnnini** [comment]
Ok, if that is your goal I now fully understand. Thanks!
