### ISSUE TITLE
impossibile clonare il Repositry

### ISSUE THREAD

**Issue by simonebartolacci** [pcm-dpc/COVID-19#1090]
Credo che sia stato usato qualche nome file non compatibile nella cartella METRCHE

**Comment by AleZanz** [comment]
Sembra esserci un file strano con nome . ..

**Comment by mydozer** [comment]
Ciao,
facendo pull si presenta il seguente errore

git.exe pull --progress -v --no-rebase "origin"
From https://github.com/pcm-dpc/COVID-19
= [up to date]      master     -> origin/master
Updating 4c26f53..ecf2a28
warning: could not open directory 'metriche/. .../': No such file or directory
error: The following untracked working tree files would be overwritten by merge:
dati-andamento-nazionale/dpc-covid19-ita-andamento-nazionale-20210307.csv
dati-province/dpc-covid19-ita-province-20210307.csv
dati-regioni/dpc-covid19-ita-regioni-20210307.csv
Please move or remove them before you merge.
Aborting


Grazie!!

**Comment by albertodolara** [comment]
Ho riscontrato lo stesso problema. Chiedo gentilmente se vi è modo di "aggirare" il problema, e di fissare il bug nel database originale.
Grazie!

**Comment by mdallapozza** [comment]
stesso problema. Grazie

**Comment by mdallapozza** [comment]
![image](https://user-images.githubusercontent.com/77343571/110314693-7bcc1c80-8008-11eb-9488-edeb791d6b2f.png)

**Comment by umbros** [comment]
Ho fatto un controllo e riscontrato che è stato caricato un file "...". Il problema è risolto.
