### ISSUE TITLE
Open Source Helps!

### ISSUE THREAD

**Issue by WeileiZeng** [pcm-dpc/COVID-19#11]
Thanks for your work to help the people in need! Your site has been added! I currently maintain the OpenSourceWuhan page, which collects all open source projects related to COVID-19, including maps, data, news, api, analysis, medical and supply information, etc. Please share to anyone who might need the information in the list, or will possibly contribute to some of those projects. You are also welcome to recommend more projects.

https://weileizeng.github.io/OpenSourceWuhan/world

Cheers!

**Comment by alranel** [comment]
@WeileiZeng you might want to mention in your directory that this site is the official source of truth maintained by the Italian government. :)

**Comment by WeileiZeng** [comment]
> @WeileiZeng you might want to mention in your directory that this site is the official source of truth maintained by the Italian government. :)

Sounds very true! Added!
I don't know Italian. Thanks for the explanation.

**Comment by miccoli** [comment]
Issue pages are for project related issues. I understand @WeileiZeng good will, but please do not add noise to this repo, which is vital for the proper dissemination of official figures about COVID-19 in Italy.

**Comment by mydozer** [comment]
@miccoli Think open please and omit to put thumb down on open contributions. It is not polite and collaborative! This place should be trustable and open to share the knowledge on the topic. Thank you!

**Comment by umbros** [comment]
Thank you @WeileiZeng  and thank you @WeileiZeng.
@miccoli, you said the right thing but on this occasion similar initiatives are elegible to opens an issue :-)

**Comment by miccoli** [comment]
@mydozer thumb down removed.

My point is there are hundreds of repos and teams doing an excellent job on COVID-19, so it is simply impracticable to (ab)use issues for spreading awareness.

Each repo should remain focused on its objective, and this one is on official data from Italy.

But again sorry @WeileiZeng if I was impolite.

**Comment by WeileiZeng** [comment]
@miccoli You do make a point that the way I open an issue here and other places has a purpose of promotion. 
I agree with you that each repo has its own objective, and should focus on that. For that, my project is aiming to gather the sources and trigger more collaboration among open source projects, make the community stronger and more powerful. Thus, my goal requires outreaches to as many related projects as possible.
Each time I add a repo, I open an issue in their repo as a feedback. So far, it serves as an encouragement for the contributors. They can also leave further explanations or correction on the information. They can also complain or decline it at their will, instead of being unnoticed (so far, no declination yet).
But I cannot deny that these issues serve a purpose of promotion, for my own list and projects in the list. Although it is all for a good purpose, I am not 100% comfortable with it. If you have further advices, please let me know. So far, it works okay. Some people pinned it. Also, they can close it anytime.

Meanwhile, there are indeed hundreds of projects out there, simply by searching COVID or nCoV on github. I search it as well, and add some of them to my list this way. I am trying to avoid any bias in my list, that's why I don't use any ranking method. The github searching method has its own ranking or promotion method(so called star, forks, best-related), and there are also projects that is not hosted on github. For this reason, I think my person-checked list provide a different perspective. Overall, rank or collection is a very subtle and difficult task. I am just trying to make this list useful, don't miss important informations, and hopefully help some of the repos.

Finally, thanks for pointing it out and trigger me to think about this issue
