### ISSUE TITLE
Dati per Comune

### ISSUE THREAD

**Issue by DataEnthusiast84** [pcm-dpc/COVID-19#110]
**Tipo di richiesta**: Richiesta di dati a livello comunale

## Riassunto

Fornire una distribuzione dei dati dettagliata per singolo comune per studiare la diffusione del contagio riportando ad esempio campi come

| Data | Sesso | Età | Comune di residenza | Regione di residenza | Comune di provenienza |Regione di provenienza | Tipo di contagio | Stato |

Tipo di contagio=da ritorno in zone rosse, locale, ecc 
Stato = isolamento domiciliare, isolamento fiduciario, terapia intensiva, ricovero con sintomi, guariti, morti ecc...

## Interesse pubblico

 Studio sulla popolazione a livello locale e regionale. Utile per valutare, ad esempio, le zone meno soggette a contagio per effettuare la chiamata dei donatori per la donazione di sangue (che anche in questo frangente deve continuare per garantire le emergenze)

**Comment by brucellino** [comment]
Hello @DataEnthusiast84 - sembra un duplicato di #61 e #89  - potresti confermare?

**Comment by DataEnthusiast84** [comment]
Confermo totalmente...scusate per la duplicazione della richiesta...

**Comment by umbros** [comment]
@61  @89

Grazie
