### ISSUE TITLE
Migliorare la gestione dei dati

### ISSUE THREAD

**Issue by tiziodcaio** [pcm-dpc/COVID-19#1103]
**Tipo di richiesta**: suggerimento/informazione per il miglioramento relativo alla gestione dei dati

## Riassunto

Ho notato che alcuni campi sono indicati come totale (esempio dei tamponi molecolari). Non converrebbe a livello pratico segnare i tamponi giornalmente (del tipo oggi ci sono stati 3800 tamponi in Lazio) e nel caso in cui sia necessaria, fare la somma manualmente?

## Interesse pubblico

Gestione dei dati migliore, molto più facile trovare incongruenze

**Comment by umbros** [comment]
Ciao @tiziodcaio sono dati facilmente elaborabili e controllabili. Grazie comunque del suggerimento
