### ISSUE TITLE
Errore nella colonna totale_casi Italia

### ISSUE THREAD

**Issue by gliv60** [pcm-dpc/COVID-19#1105]
Tipo di issue:

- [X] Dati mancanti o errati https://github.com/pcm-dpc/COVID-19

- Regione: Italia

Errore nella colonna totale_casi

Con 13846 nuovi positivi, il totale_casi odierno dovrebbe essere 3390222 e non 3400877

**Comment by Rabelaiss** [comment]
leggi gli [avvisi](https://github.com/pcm-dpc/COVID-19/blob/master/avvisi.md) bolzano ha aggiunto migliaia di casi arretrati
