### ISSUE TITLE
Delta [casi_testati] odierno maggiore del Delta dei [tamponi]

### ISSUE THREAD

**Issue by emazep** [pcm-dpc/COVID-19#1108]
Nell'andamento nazionale, il campo `casi_testati` presenta un incremento giornaliero maggiore dell'incremento giornaliero `tamponi`, in altre parole nella giornata di oggi (22/03/2021) abbiamo più casi testati che tamponi, cosa chiaramente impossibile (segnatamente 197.947 casi testati contro 169.196 tamponi).

**Comment by Rabelaiss** [comment]
Prima di aprire una issue leggere gli [avvisi ](https://github.com/pcm-dpc/COVID-19/blob/master/avvisi.md) e guardare se c'è già una issue a riguardo, leggi la mia risposta qua #1107

**Comment by emazep** [comment]
Duplicate of #1107

**Comment by emazep** [comment]
Approfitto della duplicazione per lanciare l'ennesimo disperato appello a non imputare recuperi contabili ad un unica data in una serie temporale, altrimenti tanto vale prelevare i dati sulla pandemia da `/dev/random`.

**Comment by RossoDeM** [comment]
> Approfitto della duplicazione per lanciare l'ennesimo disperato appello a non imputare recuperi contabili ad un unica data in una serie temporale, altrimenti tanto vale prelevare i dati sulla pandemia da `/dev/random`.

Tempo e fiato sprecato.
È un anno che vanno avanti così (dust under the carpet missing the point) con tanti cari saluti a statistiche, serie temporali e grafici.
Di disperati appelli si son straripate le fosse. Personalmente ci ho rinunciato da mesi e ormai non mi loggo nemmeno più
