### ISSUE TITLE
P.A. Bolzano: casi totali non coerenti

### ISSUE THREAD

**Issue by Ugetto** [pcm-dpc/COVID-19#1109]
Segnalo che i casi totati di Bolzano in data 22/03 sono dichiarati essere 67859 quando al 21/03 erano 57163, con un incremento di 10696 nuovi casi (i nuovi casi dichiarati da Bolzano sono solo 35). 
Le note inserite parlano dei tamponi e non dei casi totali. In ogni caso non giustificano una tale macroscopica discrepanza. 
Segnalo anche che almeno dal 18/03 i dati di Bolzano non quadrano, anche se non in modo così macroscopico come il 22/03. Basta confrontare i casi totali con quelli del giorno prima. Gli incrementi non tornano con quelli dichiarati dalla regione.
C'è una giustificazione per queste incoerenze?
Grazie

**Comment by Rabelaiss** [comment]
Gli [avvisi](https://github.com/pcm-dpc/COVID-19/blob/master/avvisi.md) parlano anche dei casi
> La PA Bolzano comunica che a seguito di un ricalcolo dei dati è emerso che i test antigenici positivi confermati dall'esito del test molecolare eseguiti prima del 15.01.2021 non sono stati conteggiati fino ad oggi. Pertanto oggi vengono aggiunti 10692 unità ai casi confermati da test molecolare, di cui 27 risultati positivi in data 21.03.2021 e 10665 risultati positivi prima del 15.01.2021.

**Comment by CT-igiul** [comment]
@Rabelaiss, @umbros 
Buongiorno a tutti. 
Prendo atto dell'aggiunta da P.A.Bolzano di 10.692 unità (**per me sono solo 10.661**) ma i media comunicano ancora stamattina dati errati con quello che chiamano, erroneamente, indice di contagiosità pari a **8,18%**.

![Schermata 2021-03-23 alle 13 15 49](https://user-images.githubusercontent.com/71124532/112144987-15cfbf80-8bda-11eb-8030-cc77da5e522c.png)


Guardate i numeri nelle celle nere.
![WiX-VARIAZIONI 22 03 2021](https://user-images.githubusercontent.com/71124532/112145116-431c6d80-8bda-11eb-95c6-6ae53ae20568.png)
La differenza che valuto  totale fra **Totale Casi (24.501)** e **nuovi contagi** comunicati dal TG1 (**13.846**) è pari a **10.655** ( vedi Abruzzo con 1 caso e Emilia Romagna con 5 casi). 

Il vero problema è che l'indice di contagiosità (rapporto fra nuovi casi e tamponi effettuati) è pari a **14,48%** e non quello comunicato dal TG1.
**Qualcuno dovrebbe fare correggere l'informazione ufficiale.**

![WiX-TERMOMETRI PANDEMICI 22 03 2021](https://user-images.githubusercontent.com/71124532/112147439-03a35080-8bdd-11eb-8589-eb153ce07629.png)



![WiX- Grafico Relazionale del 22 03 2021](https://user-images.githubusercontent.com/71124532/112147762-5bda5280-8bdd-11eb-9ab2-a2845bc72096.png)


Saluti
Luigi
