### ISSUE TITLE
Details about Bergamo on the first wave

### ISSUE THREAD

**Issue by iambernics** [pcm-dpc/COVID-19#1110]
Cio,

Our entire repository is extremely useful and set example for the other countries.

Have you details about Bergamo?
I find cumulative data for Lombardi.  

I would like to compare the peak of the first wave with the current data from Hungary.

Thanks a lot!

Regards,
Gabor

**Comment by Sojuz-27** [comment]
You have to check the "province" xls, there you find data for subregional italian territories.

**Comment by iambernics** [comment]
Thanks a lot!

Regards,
Gabor
