### ISSUE TITLE
nuovi Positivi Toscana 26-03-2021

### ISSUE THREAD

**Issue by gliv60** [pcm-dpc/COVID-19#1112]
- [X ] Dati mancanti o errati 
- [ ] Errore nella documentazione 
- [ ] Errore o mancanza nella dashboard 
- [ ] Problemi di visualizzazione nella dashboard 

- Regione: Toscana
- Provincia: 

Nuovi positivi Toscana riportati come 1425 mentre il sito della regione ne riporta 1527

**Comment by Rabelaiss** [comment]
è scritto nel dpc-covid19-ita-regioni.csv 

> Facendo seguito alle intese intercorse,  si fa presente che  in data 26/03/2021 sono stati aggiunti 102 casi positivi relativi al giorno 25/03/2021
