### ISSUE TITLE
Note del 30 marzo 2021.

### ISSUE THREAD

**Issue by AntonioB1976** [pcm-dpc/COVID-19#1116]
Le note relative al 30 marzo 2021 recitano:

30/3/2021

I casi reali rilevati nelle ultime 24 ore sono 76. La Regione Sicilia integrerà nella giornata di domani i dati non comunicati oggi per motivi organizzativi. La Regione Abruzzo comunica che dai casi già comunicati sono stati eliminati 3 casi, 1 caso già segnalato da altra regione e 2 casi duplicati. La Regione Emilia Romagna comunica che dai casi già comunicati in precedenza sono stati eliminati 13 casi, positivi a test antigenico ma non confermati da tampone molecolare. La PA di Bolzano comunica che dai casi già comunicati in precedenza sono stati eliminati 4 casi, positivi al test antigenico ma negativi al test molecolare. La Regione Valle d'Aosta comunica che in seguito a ricalcolo dei casi del 2020 sono emersi 58 casi non ancora comunicati (55 casi guariti e 3 decessi), che vengono comunicati in data odierna, portando così il numero totale dei casi a 9236.

Ma non c'è un errore nel posizionamento della prima frase ?
La frase:
"I casi reali rilevati nelle ultime 24 ore sono 76."
Non andrebbe in coda alle note di quel giorno ?

Le note giuste non andavano scritte per quel giorno:

La Regione Sicilia integrerà nella giornata di domani i dati non comunicati oggi per motivi organizzativi. La Regione Abruzzo comunica che dai casi già comunicati sono stati eliminati 3 casi, 1 caso già segnalato da altra regione e 2 casi duplicati. La Regione Emilia Romagna comunica che dai casi già comunicati in precedenza sono stati eliminati 13 casi, positivi a test antigenico ma non confermati da tampone molecolare. La PA di Bolzano comunica che dai casi già comunicati in precedenza sono stati eliminati 4 casi, positivi al test antigenico ma negativi al test molecolare. La Regione Valle d'Aosta comunica che in seguito a ricalcolo dei casi del 2020 sono emersi 58 casi non ancora comunicati (55 casi guariti e 3 decessi), che vengono comunicati in data odierna, portando così il numero totale dei casi a 9236.I casi reali rilevati nelle ultime 24 ore sono 76.

**Comment by umbros** [comment]
Buongiorno Antonio, oggi la Regione Sicilia ha rimandato una correzione relativa al giorno 31/03 ma stiamo vedendo di poter risolvere il problema del 30/03.

Grazie
