### ISSUE TITLE
Dati 31 Marzo e 1 April

### ISSUE THREAD

**Issue by lorenzo-gabrielli** [pcm-dpc/COVID-19#1118]
Sembra che non siano più disponibili i dati del 31 e del 1 aprile

**Comment by AlfaCent** [comment]
I dati vengono pubblicati regolarmente verso le 18: può essere legato all'ora legale che non viene tenuta in considerazione nelle schedulazioni? Saluti

**Comment by ilTrev** [comment]
> I dati vengono pubblicati regolarmente verso le 18: può essere legato all'ora legale che non viene tenuta in considerazione nelle schedulazioni? Saluti

Il problema qui non è tanto che non ci sono (ancora) i dati del 1/4, quanto che c'è stata una commit (c58255875e78b35077371d0768d9ae34f09dbe1c, di @umbros , non commentata) che ha modificato una serie di dati storici e ha cancellato i dati del 31/3 dal csv dell'andamento nazionale

**Comment by AlfaCent** [comment]
Normalmente venivano pubblicati alle 17.00 (orario riportato nei dati).

**Comment by ilTrev** [comment]
> Normalmente venivano pubblicati alle 17.00 (orario riportato nei dati).

E di nuovo, ribadisco: c'è stata una commit, oggi, verso le 17:25, che non solo non ha aggiunto i dati di oggi (il che, ribadisco, non sarebbe un problema perché dall'entrata dell'ora legale le commit quotidiane sono slittate in là), ma **ha cancellato quelli di ieri**.

**Comment by alexodus** [comment]
![image](https://user-images.githubusercontent.com/2721510/113324394-52589500-9317-11eb-8d3f-71764e49b85e.png)

**Comment by alexodus** [comment]
confermo e confermo che in questo modo il delta dei deceduti è quasi di 1000!

**Comment by alexodus** [comment]
penso sia un pesce d'aprile far sparire il 31 marzo! :)

**Comment by Achab94** [comment]
<img width="1014" alt="Schermata 2021-04-01 alle 18 25 15" src="https://user-images.githubusercontent.com/9095461/113324614-9c417b00-9317-11eb-9b01-c8241b74634d.png">

**Comment by ricir** [comment]
Dal numero temponi e deceduti sembra quasi siano stati sommati  i due giorni 31 e 1.

**Comment by ilTrev** [comment]
> Dal numero temponi e deceduti sembra quasi siano stati sommati i due giorni 31 e 1.

È esattamente quello che è successo.

**Comment by marcomarmo** [comment]
però non si può continuare così, umbros sta facendo un po' di casini ...
il 31/3 è sparito, forse sommato in 1/4. Ma ci si può fidare? Su questi dati sono basati un'infinità di ragionamenti delicatissimi ...

**Comment by ilTrev** [comment]
> però non si può continuare così, umbros sta facendo un po' di casini ...
> il 31/3 è sparito, forse sommato in 1/4. Ma ci si può fidare? Su questi dati sono basati un'infinità di ragionamenti delicatissimi ...

Il dato del 31 è scomparso solo dai due file cumulativi (dati-andamento-nazionale e dati-regioni) ma continua a esistere come file del giorno singolo. È possibile ricostruirlo manualmente riportando le righe mancanti da quelle del giorno singolo, in attesa che qualcuno si accorga dell'errore e ripristini i file corretti.

**Comment by umbros** [comment]
@marcomarmo i dati non sono processati a mano quindi non è umbros che ha fatto casini. Comunque corretto.

**Comment by marcomarmo** [comment]
> > però non si può continuare così, umbros sta facendo un po' di casini ...
> > il 31/3 è sparito, forse sommato in 1/4. Ma ci si può fidare? Su questi dati sono basati un'infinità di ragionamenti delicatissimi ...
> 
> Il dato del 31 è scomparso solo dai due file cumulativi (dati-andamento-nazionale e dati-regioni) ma continua a esistere come file del giorno singolo. È possibile ricostruirlo manualmente riportando le righe mancanti da quelle del giorno singolo, in attesa che qualcuno si accorga dell'errore e ripristini i file corretti.

Sì, certo. Adesso umbros ha fatto altra commit, ma non ha risolto nulla. In che mani siamo?

**Comment by Vincent1060** [comment]
I dati ci sono.
Grazie Umbros
