### ISSUE TITLE
Aggiornamento dati: orario di pubblicazione

### ISSUE THREAD

**Issue by AlfaCent** [pcm-dpc/COVID-19#1119]
**Tipo di richiesta**:  richiesta di informazione 

## Riassunto

Dall'introduzione dell'ora legale i dati paiono pubblicati con 1 ora di ritardo.

## Interesse pubblico

 maggiore tempestività

**Comment by umbros** [comment]
Buongiorno @AlfaCent ci sono dei ritardi ultimamente, grazie per la segnalazione.
