### ISSUE TITLE
Liguria oggi 184.131 positivi a test antigenico rapido, ieri erano 0

### ISSUE THREAD

**Issue by Rabelaiss** [pcm-dpc/COVID-19#1120]
Nel file di ieri [dpc-covid19-ita-regioni-20210331.csv](https://github.com/pcm-dpc/COVID-19/blob/656199fd06ccd606d20a9249ba26b203b9638b82/dati-regioni/dpc-covid19-ita-regioni-20210331.csv) la liguria ha
`totale_positivi_test_antigenico_rapido = 0`
mentre nel file di oggi [dpc-covid19-ita-regioni-20210401.csv](https://github.com/pcm-dpc/COVID-19/blob/656199fd06ccd606d20a9249ba26b203b9638b82/dati-regioni/dpc-covid19-ita-regioni-20210401.csv)
`totale_positivi_test_antigenico_rapido = 184131`
quest'ultimo è anche il numero di test antigenici rapidi, @umbros correggi grazie

**Comment by CapMar00** [comment]
Buonasera,
segnalo che il problema relativo al totale_positivi_test_antigenico_rapido è anche in questo file:
https://raw.githubusercontent.com/pcm-dpc/COVID-19/master/dati-andamento-nazionale/dpc-covid19-ita-andamento-nazionale.csv

dato di oggi: 298516
dato di ieri: 112772
298516−112772 = 185744

grazie

**Comment by umbros** [comment]
Il sistema di elaborazione dei dati ha evidenziato questi dati e altre incongruenze che sono state segnalate, vi ringrazio comunque della segnalazione.

Umberto
