### ISSUE TITLE
Casi testati Veneto il 1/4/2021

### ISSUE THREAD

**Issue by ornolio** [pcm-dpc/COVID-19#1121]
Tipo di issue:

- [x ] Dati mancanti o errati 
- [ ] Errore nella documentazione 
- [ ] Errore o mancanza nella dashboard 
- [ ] Problemi di visualizzazione nella dashboard 

- Regione:Veneto
- Provincia: 

## Riassunto

**Attesa:**

**Attuale:**

**Comment by Rabelaiss** [comment]
ieri erano 1.558.375 oggi 1.558.380 quindi incremento = 5, un po pochi ultimamente ne fanno 4-6 mila

**Comment by Leisure17-68** [comment]
Penso che ne convieni che non si può andare avanti così...

**Comment by umbros** [comment]
Ciao @Rabelaiss quanto da te evidenziato e ti ringrazio è già stato analizzato prima dell'invio dei dati, ma purtroppo non è sempre subito tutto risolvibile. Stiamo quindi attendendo risposte.
