### ISSUE TITLE
Dati regionali errati in Valle d'Aosta il 4/4/2021

### ISSUE THREAD

**Issue by AndreaPlanetGroup** [pcm-dpc/COVID-19#1125]
Buongiorno, vi segnalo dati errati nel file della Regione Valle d'Aosta il giorno 4/4/2021.
Il numero di test molecolari effettuati risulta uguale al giorno precedente, quindi con un saldo a 0, a fronte di 75 positivi.

Grazie e Buona Pasqua.

**Comment by umbros** [comment]
Buongiorno,
richiesto controllo ed è corretto secondo quanto comunicato.
