### ISSUE TITLE
Nuovi file zip aree divisi non possono essere scompattati

### ISSUE THREAD

**Issue by edoguido** [pcm-dpc/COVID-19#1128]
Tipo di issue:

- [X] Dati mancanti o errati 
- [ ] Errore nella documentazione 
- [ ] Errore o mancanza nella dashboard 
- [ ] Problemi di visualizzazione nella dashboard 

## Riassunto

I nuovi file zip `dpc-covid-19-aree-nuove-g-json-parte1.zip` e `dpc-covid-19-aree-nuove-g-json-parte2.z01` non possono essere scompattati perché restituiscono errore.

<img src="https://user-images.githubusercontent.com/22613065/113889882-f0d77100-97c3-11eb-8f54-5afdd5349879.png" width="480" />

Ho provato anche tramite Python (che è ciò che mi serve per automatizzare il processo) ma mi restituisce lo stesso errore.

**Comment by umbros** [comment]
Corretto, grazie
