### ISSUE TITLE
Lazio numero tamponi inesatto

### ISSUE THREAD

**Issue by ChiaraCCC** [pcm-dpc/COVID-19#113]
Tipo di issue:

x Dati mancanti o errati
Errore nella documentazione
Errore or mancanza nella dashboard

    Problemi di visualizzazione nella dashboard

Riassunto
Anche oggi il numero di tamponi effettuati nel Lazio sono uguali a quelli di ieri, eppure aumentano i casi confermati. Capisco che questi siano i dati ufficiali, ma chiaramente non sono affidabili.

**Comment by Crusan** [comment]
Credo che il dato di oggi non sia stato caricato ancora. Potrei sbagliarmi

**Comment by riccardopinto** [comment]
il dato odierno ancora non è stato caricato

**Comment by umbros** [comment]
@ChiaraCCC il dato non è stato aggiornato quel dato specifico o semplicemente non sono stati fatti tamponi. Oltretutto il dato dei tamponi non rappresenta la singola persona che ha fatto il tampone ma un soggetto potrebbe fare più tamponi.
