### ISSUE TITLE
Riga in eccesso nel file dpc-covid19-ita-note.csv

### ISSUE THREAD

**Issue by Doc73** [pcm-dpc/COVID-19#1132]
Tipo di issue: errore nel file `dpc-covid19-ita-note.csv`

- [x] Dati mancanti o errati `dpc-covid19-ita-note.csv`
- [ ] Errore nella documentazione 
- [ ] Errore o mancanza nella dashboard 
- [ ] Problemi di visualizzazione nella dashboard

## Riassunto

Nel file `dpc-covid19-ita-note.csv`, il rigo 246 è di troppo e va cancellato.
Grazie mille per l'attenzione

**Attuale:**

**Comment by umbros** [comment]
Corretto, grazie
