### ISSUE TITLE
ERRORE CODICE REGIONE

### ISSUE THREAD

**Issue by VeRsUuU** [pcm-dpc/COVID-19#1133]
Tipo di issue:

- [ -] Dati mancanti o errati 
- [ ] Errore nella documentazione 
- [ ] Errore o mancanza nella dashboard 
- [ ] Problemi di visualizzazione nella dashboard 

- Regione:
- Provincia: 

## Riassunto

Manca il codice 04 per le regioni in tutti i file

**Attesa:**

**Attuale:**

**Comment by aborruso** [comment]
@VeRsUuU la sanità in Trentino-Alto Adige/Südtirol non è gestita a livello regionale, ma dalle due province autonome.
