### ISSUE TITLE
Url non validi nei file Aree

### ISSUE THREAD

**Issue by stefanofaferrari** [pcm-dpc/COVID-19#1134]
Tipo di issue:

- [ X] Dati mancanti o errati : 
- https://github.com/pcm-dpc/COVID-19/blob/master/aree/geojson/dpc-covid-19-aree-nuove-g-json.zip 
- https://github.com/pcm-dpc/COVID-19/blob/master/aree/shp/dpc-covid-19-ita-aree-nuove.dbf

- Regione:

## Riassunto

Alcuni link nei documenti di cui sopra non sono più raggiungibili.
In particolare, quelli nel campo legLink di tipo: https://bit.ly/3kVMXNB

--

**Attesa:**

**Attuale:**

**Comment by pierluigicara** [comment]
Grazie dell'osservazione, sarà l'occasione per effettuare una revisione generale dei collegamenti rendendoli possibilmente il più omogenei possibili (ad es. sostituendo i riferimenti ai pdf, oppure alla citazione che punta ad uno specifico articolo piuttosto che alla norma in sè, oppure le url contratte). Sorvolo sui singoli motivi che hanno reso necessario utilizzare queste diverse forme di url nelle diverse "versioni". Negli ultimi periodi la pubblicazione da parte del Ministero della Salute delle Ordinanze è molto più stabile e tempestiva e ha reso più facile l'inserimento omogeneo dei dati.
Nel frattempo i permalink del sito della Gazzetta Ufficiale possono sostituire i riferimenti che non rispondono.
Nella prossima pubblicazione verrà reso disponibile anche l'esito di tale revisione.
