### ISSUE TITLE
Contagi in Piemonte 1464 o 1646 / Tamponi in Campania 26990 o 61831?

### ISSUE THREAD

**Issue by Rabelaiss** [pcm-dpc/COVID-19#1135]
Il delta è 337953-336489=1464 mentre il campo `nuovi_positivi` in [regioni-latest](https://github.com/pcm-dpc/COVID-19/blob/master/dati-regioni/dpc-covid19-ita-regioni-latest.csv) riporta 1646, forse le cifre sono state invertite?

Nelle comunicazioni non compare nulla a riguardo anche perché per errore in [avvisi](https://github.com/pcm-dpc/COVID-19/blob/master/avvisi.md) e [note](https://github.com/pcm-dpc/COVID-19/blob/master/note/dpc-covid19-ita-note.csv) l'ultima comunicazione è uguale a quella di ieri

**Comment by Paulsword** [comment]
L’Unità di Crisi della Regione Piemonte ha comunicato  1.464  nuovi casi di persone risultate positive al Covid-19

**Comment by Rabelaiss** [comment]
@Paulsword grazie, anomalia anche sui tamponi della Campania, il delta è 61831 ma la regione ne riporta 27 mila

**Comment by RossoDeM** [comment]
In effetti il delta tra il totale nazionale di oggi e quello di ieri sarebbe 16,046. Se aggiungiamo gli 8 delle note (ABR e EMR) arriviamo a 16,054. Ma per arrivare ai 16,232 comunicati servono 178. E quindi il Δ piemontese tra 1,646 e 1,464 (182) non è sufficiente. Ne ballano 4 se non sbaglio.

**Comment by Rabelaiss** [comment]
@RossoDeM come ho scritto prima la nota di oggi è sbagliata, infatti se vedi è uguale a quella di ieri, in realtà l'Abruzzo oggi non ha comunicato ricalcoli e l'emilia-romagna ha comunicato di aver eliminato 4 casi (vedasi le note [regioni-latest)](https://github.com/pcm-dpc/COVID-19/blob/master/dati-regioni/dpc-covid19-ita-regioni-latest.csv)

**Comment by RossoDeM** [comment]
> @RossoDeM come ho scritto prima la nota di oggi è sbagliata, infatti se vedi è uguale a quella di ieri, in realtà l'Abruzzo oggi non ha comunicato ricalcoli e l'emilia-romagna ha comunicato di aver eliminato 4 casi (vedasi le note [regioni-latest)](https://github.com/pcm-dpc/COVID-19/blob/master/dati-regioni/dpc-covid19-ita-regioni-latest.csv)) quindi ai 16046 casi ne vanno aggiunti 4 e si arriva a 16050.

Hai ragione, ho appena controllato le note regionali. Quindi nel file note il 22 è clone di ieri. Allora il calcolo è corretto 1,464 e non 1,646.

**Comment by Rabelaiss** [comment]
@RossoDeM esatto, resta da risolvere l'anomalia sui tamponi della campania

@umbros

**Comment by RossoDeM** [comment]
Quindi? Novità??

**Comment by umbros** [comment]
Campania si conferma, Piemonte segnalato ieri e corretto oggi.
