### ISSUE TITLE
Dati colori regioni in file separato

### ISSUE THREAD

**Issue by jumpjack** [pcm-dpc/COVID-19#1139]
I dati relativi ai colori delle regioni contenuti in https://github.com/pcm-dpc/COVID-19/tree/master/aree  sono molto interessanti, ma anche molto pesanti da elaborare: uno zip di 33MB ( https://github.com/pcm-dpc/COVID-19/blob/master/aree/geojson/dpc-covid-19-aree-nuove-g-json.zip ) che si scompatta in un file JSON di 130MB, del quale però sono utili solo pochi kb! Questo perchè nel file sono inclusi anche i dati vettoriali dei confini regionali.

Sarebbe possibile mettere invece i dati dei colori in un file separato, che sarebbe molto più snello da leggere?
In pratica si tratterebbe di mettere in un file separato l'oggetto "properties" degli elementi dell'array "features", anche perchè l'oggetto "geometries" è ovviamente costante, mentre "properties" si aggiorna all'uscita di ogni nuova ordinanza. Infatti credo che l'oggetto costante "geometries" sia già contenuto nel file separato https://github.com/pcm-dpc/COVID-19/blob/master/aree/geojson/dpc-covid-19-ita-aree.json , mentre non trovo un file per l'oggetto "properties".

**Comment by aborruso** [comment]
Ciao @jumpjack. Noi estraiamo ogni giorno (tra le varie cose) un file senza le geometrie

<https://github.com/ondata/covid19italia/blob/master/webservices/COVID-19Aree/processing/areeStorico.csv>

**Comment by jumpjack** [comment]
Ottimo grazie, 70 KB sono decisamente meglio di 30 MB!

**Comment by jumpjack** [comment]
se poteste fare anche un json con la struttura originaria dell'oggetto "properties" sarebbe anche meglio...

**Comment by aborruso** [comment]
> se poteste fare anche un json con la struttura originaria dell'oggetto "properties" sarebbe anche meglio...

Eccolo qui https://github.com/ondata/covid19italia/blob/master/webservices/COVID-19Aree/processing/areeStorico.json

**Comment by jumpjack** [comment]
non l'avevo visto o l'avete aggiunto dopo che ci ho guardato?!?
cmq grazie.

**Comment by aborruso** [comment]
L'abbiamo aggiunto dopo che l'hai proposto 😎

______
Scusami per la brevità, ti sto scrivendo dal cellulare.

website: https://medium.com/tantotanto
38° 7' 48" N, 13° 21' 9" E EPSG:4326

Il sab 8 mag 2021, 20:33 jumpjack ***@***.***> ha scritto:

**Comment by jumpjack** [comment]
però è vuoto :-(

**Comment by aborruso** [comment]
Ok, domani verifico e aggiorno

**Comment by aborruso** [comment]
> però è vuoto :-(

Eccolo https://github.com/ondata/covid19italia/blob/master/webservices/COVID-19Aree/processing/areeStorico.json
