### ISSUE TITLE
proposal: Add region labels

### ISSUE THREAD

**Issue by brucellino** [pcm-dpc/COVID-19#114]
I have seen several issues related to data specific to a region (or provinces within a region). I propose that a set of issue labels be created to be able to better categorise issues, one for each region (ie, `Sardegna`, `Sicilia`, `Abruzzo`, _etc_. This will help in the following way:

- people submitting or checking data may be responsible for collating data at a regional level (it seems that the provincia or comune level would be too fine-grained). By allowing the maintainers to tag issues by region, it would be easier to highlight which data has issues.
- People opening issues highlighting errors or discrepancies in data are typically referring to them by region. Including the region name in the relevant issue template might help the maintainers keep context.

**Comment by umbros** [comment]
Add Region and Province label to issue
Thank you @brucellino
