### ISSUE TITLE
Dati errati nel db regioni, le righe di ieri contengono i dati del 2021-04-07

### ISSUE THREAD

**Issue by Rabelaiss** [pcm-dpc/COVID-19#1142]
@umbros  Le penultime 21 righe del file [dpc-covid19-ita-regioni.csv](https://raw.githubusercontent.com/pcm-dpc/COVID-19/master/dati-regioni/dpc-covid19-ita-regioni.csv) non contengono i dati di ieri ma quelli del 2021-04-07

**Comment by Paulsword** [comment]
@umbros fix urgente

**Comment by umbros** [comment]
corretto, grazie
