### ISSUE TITLE
50 mila guariti non conteggiati in Campania

### ISSUE THREAD

**Issue by Rabelaiss** [pcm-dpc/COVID-19#1145]
Alcuni [siti](https://www.fanpage.it/napoli/covid-campania-positivi-dati-sbagliati/) e [giornali](https://d3wo5wojvuv7l.cloudfront.net/t_square_limited_720/images.spreaker.com/original/796d82df5eb39aad306808f9c46c272a.jpg) riportano la notizia che alle Asl della Campania risultano meno di 23 mila attuali positivi (dove si trova questo dato?), contro gli oltre 70 mila presenti in questo database.
Il problema sembra essere il ritardo da parte degli operatori nel rilasciare i certificati di guarigione / negativizzazione a circa 50 mila persone.

Andando a guardare il rapporto `totale_positivi` su popolazione si nota in effetti la % molta alta della Campania, quindi il problema sembra essere reale
@umbros 

![image](https://user-images.githubusercontent.com/20670578/119022168-99bae380-b9a0-11eb-969f-376e05193fcd.png)

**Comment by umbros** [comment]
Ciao @Rabelaiss la Campania ha segnalato casi al Ministero della Salute, riguardo quanto detto dai giornali non so darti maggiori info
