### ISSUE TITLE
Errore dati Molise, 22 maggio 2021

### ISSUE THREAD

**Issue by Sojuz-27** [pcm-dpc/COVID-19#1147]
Tipo di issue:

- [x] Dati mancanti o errati 
- [ ] Errore nella documentazione 
- [ ] Errore o mancanza nella dashboard 
- [ ] Problemi di visualizzazione nella dashboard 

- Regione: Molise
- Provincia: Ciascuna

## Riassunto

Sembra che per ciascuna riga di dati del Molise di oggi, 22 maggio 2021, ci sia stata un'attribuzione erronea che riguarda un'altra riga della stessa regione.

**Attesa:**

**Attuale:**

**Comment by Rabelaiss** [comment]
casi totali ieri
campobasso 9767
isernia 3709
in verifica 68

casi totali oggi
campobasso 0
iserna 9767
in verifica 3780
