### ISSUE TITLE
24/05/2021 Dati mancanti per tutte le provincie della Puglia

### ISSUE THREAD

**Issue by gilegiov** [pcm-dpc/COVID-19#1148]
Tipo di issue:

- [ x] Dati mancanti o errati 
- [ ] Errore nella documentazione 
- [ ] Errore o mancanza nella dashboard 
- [ ] Problemi di visualizzazione nella dashboard 

- Regione: Puglia
- Provincia:  Tutte

## Riassunto

Per la regione Puglia manca il dettaglio per provincia del 24/05/2021 nel file
/dati-province/dpc-covid19-ita-province.csv

**Attesa:**

**Attuale:**

**Comment by Rabelaiss** [comment]
questi sono i dati corretti per chi vuole correggere a mano
![image](https://user-images.githubusercontent.com/20670578/119372497-aba9c880-bcb7-11eb-91e1-1cc1fb267941.png)

**Comment by umbros** [comment]
Ciao @Rabelaiss già segnalato in sede di elaborazione. Grazie

**Comment by Rabelaiss** [comment]
@umbros bene, avete notizie per quanto riguarda #1145 ?

**Comment by umbros** [comment]
La Puglia correggerà i dati del 24-05 nei prossimi giorni

**Comment by umbros** [comment]
Dati delle province della Puglia del giorno 24-05 corretti https://github.com/pcm-dpc/COVID-19/commit/d1a95116f5a45da6bcff1302f15372b6c8564bff
