### ISSUE TITLE
Errore file province

### ISSUE THREAD

**Issue by sausyn** [pcm-dpc/COVID-19#1149]
Tipo di issue:

- [x] Dati mancanti o errati dati-province/dpc-covid19-ita-province.csv
- [ ] Errore nella documentazione 
- [ ] Errore o mancanza nella dashboard 
- [ ] Problemi di visualizzazione nella dashboard 

- Regione:
- Provincia: 

## Riassunto

una riga vuota alla riga 65682 del file csv delle province causa errori di import e validazione del file

**Attesa:**

nessuna riga vuota nel file dati-province/dpc-covid19-ita-province.csv

**Attuale:**

riga vuota alla riga 65682 del file csv dati-province/dpc-covid19-ita-province.csv

**Comment by umbros** [comment]
Corretto, grazie
