### ISSUE TITLE
Suggerimenti

### ISSUE THREAD

**Issue by frankoball** [pcm-dpc/COVID-19#115]
Grazie per tutto il lavoro che stai facendo!
La dizione 'nuovi_attualmente_positivi' non è di immediata comprensione. Sarebbe meglio 'incremento_attualmente_positivi'.
Il dato di ieri 10-mar era un po' volatile (un numero troppo basso) e da quello che ho capito potrebbe dipendere dall'esito differito dei tamponi. Questo potrebbe significare che il numero elevato di oggi 11-mar potrebbe incorporare alcuni di ieri.
Per ovviare a ciò potrebbe essere utile calcolare una media mobile centrata a 3 giorni del totale dei casi. La variazione sarebbe in questo caso: 7 marzo 24,5%; 8 marzo 25,3%; 9 marzo 19%; 10 marzo 19,1%. Per l'11 marzo si deve attendere il dato di domani.
Mi sembra utile calcolare i rapporti tra numero casi positivi e tamponi (intorno al 17%) e di terapia intensiva su ospedalizzati (15%).

**Comment by umbros** [comment]
ciao @frankoball il lavoro è fatto da una squadra di persone tra cui @pierluigicara  e ti ringraziamo per l'apprezzamento :)
Nella giornata di domani cambierà il formato del dataset inserendo un campo note dove verranno riportati eventuali informazioni non aggiornate. Non possiamo fare calcoli e ipotesi in quanto c'è un processo di conferimento formale dei dati. Allo stato attuale le Regioni sono in affanno quindi possono accadere dei rallentamenti o invio dati in ritardo. 
Grazie per i suggerimenti
