### ISSUE TITLE
Tamponi in Liguria il 31 maggio 2021.

### ISSUE THREAD

**Issue by AntonioB1976** [pcm-dpc/COVID-19#1151]
Il sito della Protezione Civile per la Liguria oggi 31 maggio 2021 indica 2676 tamponi.
Oggi sono in totale 1615207 e ieri 1612531.
E 1615207-1612531=2676
La Pagina FaceBook della Regione ed il relativo sito ne indica 
invece per oggi 1804 molecolari e 1172 antigenici per un totale di 2976.
https://www.regione.liguria.it/area-stampa/archivio-comunicati-stampa-della-giunta/item/30125-bollettino-31-5-2021.html?fbclid=IwAR1pf2ldoKcYbQRInOTTWpZgZoFJ5bCGPd7qpS1vuuaEhZCwl4gBi08XC-A

Quale è il numero esatto ?

**Comment by AntonioB1976** [comment]
La differenza mi pare sia sui tamponi rapidi.
Per la regione ad oggi sarebbero 323.789,invece per la Protezione Civile
323.489.
Coincidono con 1.291.718 invece i tamponi totali molecolari sia di regione sia di protezione civile.

**Comment by Rabelaiss** [comment]
probabilmente errore di digitazione

**Comment by AntonioB1976** [comment]
Ed anche oggi 300 tamponi di differenza. 
Sono 5202 per la Protezione Civile e 4902 per la regione.(2927 molecolari e 1975 rapidi)

**Comment by Paulsword** [comment]
Off topic, ma magari @Rabelaiss e @AntonioB1976 che siete osservatori attenti avete qualche idea.. #1152

**Comment by pierluigicara** [comment]
L'unica cosa che possiamo dire al riguardo è che i dati che pubblichiamo sono quelli che ci trasmette il Ministero della Salute (vedi Flusso nel README) e fino a quando non ci perviene una rettifica "ufficiale" relativa al conferimento di quei dati per il giorno in questione (in pratica le osservazioni che vengono riportate nelle note) per noi restano validi.
