### ISSUE TITLE
Dati duplicati 8 giugno

### ISSUE THREAD

**Issue by floatingpurr** [pcm-dpc/COVID-19#1154]
I dati di oggi sono nuovamente duplicati.

E.g.,

https://github.com/pcm-dpc/COVID-19/blob/b2b32477bb4b3992171cbb8cd8a7369d469abe79/dati-json/dpc-covid19-ita-andamento-nazionale.json#L12223

https://github.com/pcm-dpc/COVID-19/blob/b2b32477bb4b3992171cbb8cd8a7369d469abe79/dati-json/dpc-covid19-ita-andamento-nazionale.json#L12249

**Comment by giordanomattei** [comment]
Si segnala che i dati sono stati corretti con ultimo update giorno 8/6/2021
