### ISSUE TITLE
Nome file dati aree errato

### ISSUE THREAD

**Issue by edoguido** [pcm-dpc/COVID-19#1155]
Tipo di issue:

- [X] Dati mancanti o errati 
- [ ] Errore nella documentazione 
- [ ] Errore o mancanza nella dashboard 
- [ ] Problemi di visualizzazione nella dashboard 

- Regione:
- Provincia: 

## Riassunto

`dpc-covid-19-aree-nuove-g-jsion.zip` contiene un typo: `jsion` dovrebbe essere `json`.

Nome file corretto: `dpc-covid-19-aree-nuove-g-json.zip`

**Comment by pierluigicara** [comment]
Grazie, il nome ora è corretto.
