### ISSUE TITLE
Variazione numero positivi del 15/6/2021 probabilmente errato

### ISSUE THREAD

**Issue by ornolio** [pcm-dpc/COVID-19#1156]
Tipo di issue:

- [x ] Dati mancanti o errati 
- [ ] Errore nella documentazione 
- [ ] Errore o mancanza nella dashboard 
- [ ] Problemi di visualizzazione nella dashboard 

- Regione:Campania
- Provincia: 

## Riassunto

**Attesa:**

**Attuale:**

**Comment by emazep** [comment]
Dipende dal fatto che la Campania ha comunicato oggi 48.213 guariti (delta giornaliero), contro una media negli ultimi giorni di circa 500 (e circa 5.000 a livello nazionale). Da mesi aveva accumulato un deficit nel comunicare tale dato, e ha pensato male di rimediare con un conguaglio da imputare alla sola giornata di oggi, come non verrebbe mai in mente di fare nemmeno a chi si occupa di gestione dei dati anche solo a livello hobbistico, ma come sembra sia la norma al Ministero della Salute.

**Comment by pierluigicara** [comment]
Grazie della segnalazione, che di fatto commenta la comunicazione riportata tra le note di oggi a cura della Regione Campania e trasmessa dal Ministero della Salute.

**Comment by Rabelaiss** [comment]
> Ne approfitto per chiedere: dove sono le note? Una volta erano rinvenibili a questo link (denominato AVVISI...) nel README, che però attualmente risulta interrotto:
> https://github.com/pcm-dpc/COVID-19/blob/master/note/dpc-covid19-ita-note.md

modifica il link sostituendo 'md' con 'csv'

**Comment by emazep** [comment]
> 
> 
> > Ne approfitto per chiedere: dove sono le note? Una volta erano rinvenibili a questo link (denominato AVVISI...) nel README, che però attualmente risulta interrotto:
> > https://github.com/pcm-dpc/COVID-19/blob/master/note/dpc-covid19-ita-note.md
> 
> modifica il link sostituendo md con csv

Grazie. Mi permetto comunque di insistere nel mio suggerimento di correggere il link nel README.

**Comment by pierluigicara** [comment]
Link nei README corretto: grazie!

**Comment by ornolio** [comment]
pensavo ci fosse la mano di S. Gennaro...
pier giacomo ornolio
***@***.***
***@***.***
pec: ***@***.***
+39 335 78 31 433
In data 15 giugno 2021 20:06:23 Pierluigi Cara - DPC 
***@***.***> ha scritto:
