### ISSUE TITLE
Calo di più di 400 casi per province di Trieste e Udine

### ISSUE THREAD

**Issue by Sojuz-27** [pcm-dpc/COVID-19#1158]
Buonasera,

segnalo quanto in oggetto: è corretto? C'è stato un ricalcolo dei casi Covid-19 in Friuli-Venezia Giulia?

PS: http://www.regione.fvg.it/rafvg/comunicati/comunicato.act?dir=/rafvg/cms/RAFVG/notiziedallagiunta/&nm=20210624184538008

**Comment by RossoDeM** [comment]
Ci sono un po' di problemi tra ieri e oggi. È stato corretto il totale dei decessi di ieri, ma non è stato aggiornato di conseguenza il totale dei positivi, e a ruota i positivi su molecolari e antigenici.
Quindi le variazioni giornaliere non tornano.

**Comment by RossoDeM** [comment]
![Screenshot_20210624-194818](https://user-images.githubusercontent.com/65342251/123309421-2ec37600-d525-11eb-8d0e-48c8e8eab151.jpg)
