### ISSUE TITLE
Errore caricamento dati 11/3 regioni?

### ISSUE THREAD

**Issue by DataEnthusiast84** [pcm-dpc/COVID-19#116]
Tipo di issue:

- [X] Dati mancanti o errati
- [ ] Errore nella documentazione 
- [ ] Errore or mancanza nella dashboard 
- [ ] Problemi di visualizzazione nella dashboard 

## Riassunto

I dati regionali dell'11/3 sembrerebbero essere uguali al 10/3 per l'Abruzzo

**Attesa:**

**Attuale:** Ho visto dopo che avete aggiunto che non è arrivata la comunicazione dei dati di oggi proprio per la regione Abruzzo.

**Comment by umbros** [comment]
Come spiegato nel README 
11/03/2020: dati Regione Abruzzo non pervenuti.

Nei prossimi giorni, forse anche da oggi, metteremo un campo note sui dati in modo da gestire eventuali dati non aggiornati o pervenuti.

Prossimi aggiornamenti // Next updates

    Aggiunta "Note" in "dati-regioni", "dati-province" e "dati-andamento-nazionale" (Add "Notes" in "dati-regioni", "dati-province" e "dati-andamento-nazionale")
