### ISSUE TITLE
anno 2121 invece di 2021 nel file dpc-covid-19-ita-aree.shp

### ISSUE THREAD

**Issue by Rabelaiss** [pcm-dpc/COVID-19#1160]
Le date riportate nei campi `designIniz`, `legDataApp` e `datasetIni` nelle righe delle ultime 2 settimane riportano come anno 2121 invece di 2021, es. `'21210628'`.

**Comment by pierluigicara** [comment]
Grazie per la segnalazione, il refuso è stato corretto.
