### ISSUE TITLE
Dati province liguri del 5-7-2021

### ISSUE THREAD

**Issue by unbombarolo** [pcm-dpc/COVID-19#1161]
**Tipo di richiesta**:  richiesta di dati 

## Riassunto

I dati odierni per le province liguri sono "anomali": il totale dei casi in provincia di Imperia è diminuito di 7 unità, quello per Savona è aumentato di 7 unità, mentre nei giorni scorsi la media era intorno a 1 al giorno e il numero di casi "fuori regione" è diminuito di 12 unità. Sono correzioni di errori precedenti o ci sono problemi sui dati di oggi?

## Interesse pubblico

Fino a ieri l'andamento dei dati era abbastanza regolare, tra 0.04 e 0.06 nuovi casi per 10.000 abitanti nelle varie province liguri (media settimanale mobile), oggi i numeri sono tutti cambiati di molto, circa raddoppiati ovunque tranne che a Imperia dove si è andati in negativo (cosa che non può essere corretta). Capire se ci sono stati errori nei giorni scorsi oppure nei dati di oggi credo sia utile.

**Comment by pierluigicara** [comment]
Si riporta l'informazione riportata nelle note del giorno 5/7/2021 trasmessa dalla Regione Liguria: "La Regione Liguria comunica che a causa di problemi informatici verificatisi in data 4/7/2021, l'informazione relativa al numero di soggetti guariti è stata erroneamente calcolata. Il dato viene aggiornato e contestualmente rettificato in data odierna."
