### ISSUE TITLE
Problemi visualizzazione su firefox

### ISSUE THREAD

**Issue by jump65** [pcm-dpc/COVID-19#1163]
Buongiorno, oggi riscontro un problema nella visualizzazione della tabella coi dati quotidiani: il relativo frame ha la dimensione giusta ma è vuota, non si vede la tabella PDF. 
Succede cercando di visualizzare le tabelle riassuntive di qualsiasi data e solo con firefox; con chrome o edge funziona.
Il download mi pare invece funzionare regolarmente.

Saluti
 Giampietro Viola

Tipo di issue:

- [ ] Dati mancanti o errati 
- [ ] Errore nella documentazione 
- [ ] Errore o mancanza nella dashboard 
- [X] Problemi di visualizzazione nella dashboard 

- Regione: Veneto
- Provincia:  Padova

## Riassunto

**Attesa:**

**Attuale:**

**Comment by Doc73** [comment]
Anche da me (Firefox 88 su Debian 11 Bullseye) i PDF non risultavano incorporati, ma, disabilitato l'adblock, tutto si è risolto.

**Comment by pierluigicara** [comment]
Anch'io ho superato il problema modificando in Firefox 90.0.2 (64 bit) Impostazioni-->Applicazioni-->Adobe Content Server Message le modalità di gestione.
