### ISSUE TITLE
Nuovi casi: numero vaccinati (%) e non vaccinati (%)

### ISSUE THREAD

**Issue by CloudItaly** [pcm-dpc/COVID-19#1164]
Salve, in questa repo (o altre repo) c'è la possibilità di ottenere il dato richiesto?

**Comment by pierluigicara** [comment]
Questo repository pubblica giornalmente solo il bollettino sanitario a cura del Ministero della Salute.
Per i dati sui vaccini bisogna consultare [questo ](https://github.com/italia/covid19-opendata-vaccini) repository.
