### ISSUE TITLE
Numeri contagiati, ospedalizzati, terapia intensiva e morti divise per vaccinati e non vaccinati

### ISSUE THREAD

**Issue by elenap1980** [pcm-dpc/COVID-19#1168]
buongiorno,
mi chiedevo se esiste una banca dati disponibile da cui estrapolare questi dati
Numeri contagiati, ospedalizzati, terapia intensiva e morti divise per vaccinati e non vaccinati,

al momento sto usando i dati contenuti qui https://raw.githubusercontent.com/pcm-dpc/COVID-19/master/dati-andamento-nazionale/dpc-covid19-ita-andamento-nazionale.csv
ma vorrei avere un csv simile per avere gli stessi dati che riportino però la divisione tra vaccinati e non...
qualcuno mi può aiutare?
grazie!

**Comment by Fuffo00339958** [comment]
ISS pubblica un report settimanale in https://www.epicentro.iss.it/coronavirus/aggiornamenti , nella tab. 3 a metà documento sono riportati i valori delle categorie: vaccinazioni,diagnosi, ricoveri, intensive, decessi; divisi per vaccinati, ciclo incompleto e completo, e per fascia d'età. Però la divisione statistica in tabella è incongrua, va ricalcolata come casi/popolazione omogenea e non come singole quote di sintomo. Ho elaborato un foglio excel che fa questi calcoli, con valori da importare manualmente. Evidenziano che: dato "1" il "rischio" di un vaccinato con ciclo completo dopo i 14 giorni, il rischio di "Comparsa sintomi" è circa 3-4
[ISS agosto 2021 EFFETTO Vaccinazioni.xlsx](https://github.com/pcm-dpc/COVID-19/files/7093896/ISS.agosto.2021.EFFETTO.Vaccinazioni.xlsx)
 per i non vaccinati, ma sale di parecchio per i ricoveri, e ancora di più per le intensive e i decessi, ma i casi sono pochi e la stima statistica è poco affidabile (elaborazione sui dati della settimana precedente).
[Bollettino-sorveglianza-integrata-COVID-19_25-agosto-2021.pdf](https://github.com/pcm-dpc/COVID-19/files/7093878/Bollettino-sorveglianza-integrata-COVID-19_25-agosto-2021.pdf)

**Comment by pierluigicara** [comment]
Le richieste relative a informazioni aggiuntive da introdurre nel flusso giornaliero, vengono trasmesse al Ministero della Salute in quanto titolare e fornitore dei dati. Nello specifico, per la distinzione indicata, al momento non abbiamo avuto un riscontro.
