### ISSUE TITLE
Richiesta dati: Casi covid su persone vaccinate

### ISSUE THREAD

**Issue by ambr89** [pcm-dpc/COVID-19#1169]
**Tipo di richiesta**:  richiesta di dati | relativo alla pagina grafica https://www.epicentro.iss.it/coronavirus/bollettino/Bollettino-sorveglianza-integrata-COVID-19_8-settembre-2021.pdf

## Riassunto

Richiesta di dati per l'elaborazione dell'efficacia vaccinale.
Si chiede di poter accedere ai dati grezzi raccolti per l'elaborazione della tabella 3:
POPOLAZIONE ITALIANA DI ETÀ >12 ANNI E CASI DI COVID-19 DIAGNOSTICATI,
OSPEDALIZZATI, RICOVERATI IN TERAPIA INTENSIVA E DECEDUTI NEGLI ULTIMI 30 GIORNI, PER STATO
VACCINALE E CLASSE D’ETÀ*

## Interesse pubblico

Siamo interessati ad elaborare dei modelli di stima di compertura vaccinale e durata nel tempo.

Ringrazio anticipatamente

**Comment by udedomenico** [comment]
Confermo l'interesse e attendo un riscontro.

**Comment by pierluigicara** [comment]
Recentemente sono giunte altre richieste analoghe (vedi ad esempio #1168 ) e la nostra risposta al momento resta la stessa: per poter pubblicare in questo repository i dati richiesti, tali dati devono essere forniti dal Ministero della Salut, ma ancora manca un'indicazione specifica da parte del Ministero al riguardo. Comunque - come ricordato anche da @fuffo00339958 nel thread citato), nel report settimanale dell'ISS si trovano le informazioni richieste (a pag.17 di https://www.epicentro.iss.it/coronavirus/bollettino/Bollettino-sorveglianza-integrata-COVID-19_8-settembre-2021.pdf che è quello più recente).
