### ISSUE TITLE
data Napoli 3 March 2020

### ISSUE THREAD

**Issue by capezza** [pcm-dpc/COVID-19#117]
Type of issue:

- Incorrect or missing data : dpc-covid19-ita-province-20200303.csv
- [ ] Incorrect or missing documentation 
- [ ] Incorrect or missing data in the dashboard 
- [ ] Layout problem in the dashboard 

## Summary

Should the value of `totale_casi` for Napoli be 17 instead of 30 on 3 March?

**Comment by umbros** [comment]
@capezza risultano 30 il 3 marzo.

2020-03-03 17:00:00 | Campania | Napoli | NA | 30

**Comment by capezza** [comment]
Mi scuso se ho capito male, ma perché nei giorni successivi (dal 4 al 7 marzo) il numero totale di casi risulta essere di nuovo 17? Non dovrebbe essere maggiore o uguale a 30?
