### ISSUE TITLE
I valori del campo totale_positivi presentano incogruenze 

### ISSUE THREAD

**Issue by udedomenico** [pcm-dpc/COVID-19#1170]
**Tipo di richiesta**:  r

## Riassunto

Ho analizzato i dati della tabella **dpc-covid19-ita-andamento-nazionale.csv** e rilevo una incorrettezza nei dati del campo _totale positivi_
Infatti se segmentiamo i dati per giorno facendo una semplice sottrazione (totale_positivi-Previous((totale_positivi) (differenza del valore di una cella con il relativo valore della cella antecedente), per alcuni giorni i dati appiano negativi, vale a dire il numero di positivi (IMPROVVISAMENTE) diminuisce. 
Essendo questo un valore incrementale non è possibile che ci sia una diminuzione, al massimo il valore potrebbe essere nullo (intendendo così che non ci sono positivi aggiunti in quel giorno). 
Potete spiegare che sta succedendo, perché quei valori negativi?

Allego [link](https://docs.google.com/spreadsheets/d/15E-krrqiKFqswkhAqvY8fyheIfADE58F/edit?usp=sharing&ouid=101758810623523773081&rtpof=true&sd=true) alla tabella che ho estratto e quindi manipolato per recuperare il numero di positivi giornaliero, per favore prestate al campo di nome _**positivi_giornaliero**_
 
Grazie per la vostra attenzione!

## Interesse pubblico

Nell'istituto dove svolgo attività di docente questa informazione mi è stata richiesta esplicitamente dagli studenti e studentesse che chiaramente hanno espresso dei dubbi sull'attendibilità dei dati che abbiamo caricato.

**Comment by Rabelaiss** [comment]
Le consiglio di leggere [dati-andamento-covid19-italia.md](https://github.com/pcm-dpc/COVID-19/blob/master/dati-andamento-covid19-italia.md) in cui viene spiegato che `totale_positivi = Totale attualmente positivi (ospedalizzati + isolamento domiciliare)` quindi se guariti + deceduti > nuovi casi allora `totale_positivi` diminuisce.

I nuovi casi giornalieri sono indicati nel file [dpc-covid19-ita-andamento-nazionale.csv](https://github.com/pcm-dpc/COVID-19/blob/master/dati-andamento-nazionale/dpc-covid19-ita-andamento-nazionale.csv) alla colonna `nuovi_positivi`, mentre i casi totali sono nella colonna `totale_casi`
