### ISSUE TITLE
Dati Campania e Sicilia

### ISSUE THREAD

**Issue by Paulsword** [pcm-dpc/COVID-19#1173]
Buongiorno.
Il dato dei positivi della Campania risulta ridotto di 2665 casi rispetto alle 24 ore precedenti, mentre nella tabella di riepilogo delle regioni è +335.
Il totale è evidentemente 456409 e non 453409.

Rimane un'incongruenza sui dati della Sicilia, che in totale sono 500 o 796 a seconda che si guardi il riepilogo o i parziali, anche per provincia (in particolare Palermo conta 355 casi, o è un errore?)

Grazie

**Comment by fotografAle** [comment]
Buonasera,
ho visto che, sul nazionale, è stato corretto il dato del totale dei contagiati.
Resta un'anomalia sul dato dei nuovi positivi che anche l'algoritmo di previsione identifica come incongruente.

Ale

**Comment by vi-enne** [comment]
Tra le [note del 30 settembre 2021](https://github.com/pcm-dpc/COVID-19/blob/master/dati-regioni/dpc-covid19-ita-regioni-20210930.csv) la Sicilia riporta:

"Il numero complessivo di tamponi positivi comunicati in data odierna, dal laboratorio principale dell'ASP di Palermo, pari a 796 - n. 296 sono relativi all'anno 2020"

296 casi sono quindi dell'anno scorso, segnalati nel totale ma non nei nuovi positivi.
