### ISSUE TITLE
Positivi tamponi antigenici / molecolari Lombardia 2021-11-03

### ISSUE THREAD

**Issue by carlotnx** [pcm-dpc/COVID-19#1177]
Tipo di issue: Dati mancanti o errati https://raw.githubusercontent.com/pcm-dpc/COVID-19/master/dati-regioni/dpc-covid19-ita-regioni.csv

Regione: Lombardia

## Riassunto

Il totale dei positivi da tamponi antigenici non è maggiore del giorno precedente 301 < 67685
Il totale dei positivi da tamponi molecolari ha avuto un incremento esagerato (+68066), simile al numero di positivi da tamponi antigenici mancanti. 

**Attesa:**

Un valore progressivo per i positivi da tamponi antigenici, un incremento simile ai giorni precedenti per i positivi da tamponi molecolari.

**Attuale:**

data,totale_positivi_test_molecolare,totale_positivi_test_antigenico_rapido
2021-11-02T17:00:00,827297,67685
2021-11-03T17:00:00,895363,301

**Comment by pierluigicara** [comment]
Grazie per la segnalazione. Dal momento che la Regione non ha notificato nulla, abbiamo girato l'osservazione al Ministero della Salute affichè facesse una verifica, sentendo eventualmente anche la Regione Lombardia.

**Comment by pierluigicara** [comment]
Il Ministero della Salute ha confermato la segnalazione. Prima dell'aggiornamento quotidiano provvederemo a correggere i dati di ieri con i nuovi dati che il Ministero trasmetterà.

**Comment by Iccegit** [comment]
per avere dati coerenti basta sottrarre il dato dei "totale_positivi_test_antigenico_rapido" del 2/11 dal "'totale_positivi_test_molecolare" del 3/11 e aggiungerlo al "totale_positivi_test_antigenico_rapido" del 3/11, pare più una svista di chi ha compilato il modulo (a questo punto credo in excel) in regione lombardia
