### ISSUE TITLE
grafico nuovi positivi - valori errati

### ISSUE THREAD

**Issue by mselenu** [pcm-dpc/COVID-19#1179]
Buongiorno
vorrei riportare un errore di input dati nel grafico nuovi positivi. Negli ultimi tempi (sicuramente negli ultimi due giorni) il grafico usa come input i "totali casi" invece del numero di incremento degli attuali positivi.
 
Vi prego di verificare.

grazie
Monica

**Comment by pierluigicara** [comment]
Grazie della segnalazione, ma non ci risulta. A titolo di esempio il grafico sull'andamento dei "Nuovi positivi" nelle dashboard riporta ieri il valore 4197 che è appunto l'incremento dei casi totali (rispetto al giorno precedente) comunicato dal Ministero della Salute.
