### ISSUE TITLE
Grazie della segnalazione, ma non ci risulta. A titolo di esempio il grafico sull'andamento dei "Nuovi positivi" nelle dashboard riporta ieri il valore 4197 che è appunto l'incremento dei casi totali (rispetto al giorno precedente) comunicato dal Ministero della Salute.

### ISSUE THREAD

**Issue by mselenu** [pcm-dpc/COVID-19#1180]
Buonasera,
in riferimento alla segnalazione 1179 e relativa risposta ricevuta che trovate in fondo al messaggio, vorrei fare un paio di considerazioni. 
Il grafico che ho segnalato si chiama "Nuovi Positivi", il valore che riporta invece é l'incremento dei casi totali che francamente non capisco come sia ottenuto, in teoria dovrebbe essere dato dalla somma delle varie informazioni: incremento nuovi positivi+ incremento dimessi/guariti + incremento decessi. forse il totale varia a causa delle correzioni che arrivano di volta in volta dalle regioni.
in ogni caso se il grafico ha titolo "nuovi positivi"non dovrebbe considerare solo la voce "incremento nuovi positivi"? 
Se invece l'input fosse confermato sarebbe piu' chiaro e corretto chiamare il grafico "casi totali" altrimenti l'informazione si interpreta in modo non corretto: leggo 4179 e penso che sia il numero di nuovi casi positivi mentre invece é l'incremento dei casi totali (sommatoria delle voci sopra).
grazie
Monica

Grazie della segnalazione, ma non ci risulta. A titolo di esempio il grafico sull'andamento dei "Nuovi positivi" nelle dashboard riporta ieri il valore 4197 che è appunto l'incremento dei casi totali (rispetto al giorno precedente) comunicato dal Ministero della Salute.

_Originally posted by @pierluigicara in https://github.com/pcm-dpc/COVID-19/issues/1179#issuecomment-963860504_

**Comment by pierluigicara** [comment]
Il numero di cui si parla (nel caso di ieri era 6032) sta ad indicare la somma delle colonne "Casi identificati da test molcolare" e "Casi identificati da test antigenico rapido" nel report del Ministero della Salute. Ad es. per la Valle d'Aosta il valore 11 di ieri corrisponde a12365 (11488+877) - 12354 (11483+871), che erano i valori di ieri (tra parentesi ho riportato i valori delle due colonne anzidette).
Come è evidente non si tratta di dimessi/guariti o decessi o altro ma esclusivamente di nuovi casi identificati da test che abbiamo denominato nelle dashboard per motivi di comunicazione in "Nuovi positivi". La scelta può non piacere, ma il significato è chiaro.
