### ISSUE TITLE
Dati per provincia Duplicati in data 19/11/2021

### ISSUE THREAD

**Issue by gilegiov** [pcm-dpc/COVID-19#1184]
Nel file :    dpc-covid19-ita-province.csv
in corrispondenza della data:     19/11/2021
le righe sono duplicate.

**Comment by Rabelaiss** [comment]
@pierluigicara problema presente anche nel commit odierno

**Comment by pierluigicara** [comment]
Ok, grazie, il file è stato corretto.

**Comment by emazep** [comment]
Ma è stato introdotto un altro errore: ora nel file
https://raw.githubusercontent.com/pcm-dpc/COVID-19/master/dati-province/dpc-covid19-ita-province.csv

ci sono 3 caratteri ; (semicolon) appesi alla fine di ogni riga (che rendono il CSV illeggibile, a meno di un preprocessamento).

**Comment by pierluigicara** [comment]
Ok, adesso ci dovremmo essere :)

**Comment by emazep** [comment]
Grazie ma purtroppo permane ancora (almeno) un errore (che rende il CSV non parsabile): la riga **18166** contiene ancora 2 semicolon finali, un altro semicolon tra due campi e inoltre i primi 11 campi appaiono quotati in un'unica stringa. La riporto qui per comodità:

    "2020-07-12T17:00:00,ITA,18,Calabria,882,Fuori Regione / Provincia Autonoma,,,,28,""Dallo screening condotto su 70 migranti sbarcati ieri a Roccella Ionica sono stati intercettati 26 soggetti positivi dal  laboratorio dell'ASP di Reggio Calabria";"  in strutture dedicate,  appositamente individuate dalla Prefettura."",,,";;

Non escludo tuttavia che possano esserci ancora altri errori (mi sono fermato al primo incontrato).

Mi permetto di suggerire la redazione di un test che esegua il roundtrip completo `generazione della struttura di dati tabellare->serializzazione su file in f.to CSV->caricamento del CSV da file e deserializzazione in struttura tabellare->confronto con la struttura originale`, altrimenti temo risulti difficile verificarne la correttezza in caso dovessero intervenire cambiamenti nelle routine di acquisizione dei dati.
