### ISSUE TITLE
Spazio aggiuntivo nel nome del campo ' data' nel file delle province

### ISSUE THREAD

**Issue by fabriziomiano** [pcm-dpc/COVID-19#1186]
Tipo di issue:

- [x] Dati mancanti o errati in dati-province/dpc-covid19-ita-province.csv

## Riassunto

Il campo 'data' è stato rinominato in ' data' (spazio aggiuntivo all'inizio), ma ci si aspetta 'data' 

Grazie

**Comment by miccoli** [comment]
E questo errore si ripercuote su `dati-json/dpc-covid19-ita-province.json` dove e74ad90 ha introdotto un diff gigantesco: 

```
$ git diff --stat e74ad90^..e74ad90 dati-json/dpc-covid19-ita-province.json
 dati-json/dpc-covid19-ita-province.json | 185756 ++++++++++++++++++++--------------------
 1 file changed, 92886 insertions(+), 92870 deletions(-)
```
tutte del tipo:
```
-    "data":"2020-02-24T18:00:00",
+    " data":"2020-02-24T18:00:00",
```

**Comment by fizzi** [comment]
@fabriziomiano possiamo chiudere anche questa issue ?

**Comment by miccoli** [comment]
@fizzi ci sarebbe da rigenerare anche `dati-json/dpc-covid19-ita-province.json`

**Comment by fizzi** [comment]
Sistemato anche dati-json/dpc-covid19-ita-province.json

**Comment by ebigogno** [comment]
il problema è stato sistemato ma solo per le date precedenti al 23/11/2021 che continua a presentare il campo " data", il JSON non è più consistente e valido dal momento che ora contiene un array di elementi diversi fra loro

**Comment by miccoli** [comment]
Adesso anche me sembra tutto OK... forse si può chiudere.
