### ISSUE TITLE
Usare github Actions per chiusura vecchie issue

### ISSUE THREAD

**Issue by tiziodcaio** [pcm-dpc/COVID-19#1187]
**Tipo di richiesta**: Stallare / chiudere issue non aggiornate da mesi, in modo da aumentare la produttività

## Riassunto

ecco un esempio di come fare, se volete provo a fare una PR https://github.com/actions/stale

## Interesse pubblico

aumento produttività per gli amministratori

**Comment by vi-enne** [comment]
Ad alcune, invece, si potrebbe provare a rispondere prima di chiuderle.

**Comment by miccoli** [comment]
Si potrebbero anche chiudere tutte in colpo solo... quello che manca adesso da parte di DPC è una chiara "policy" su come trattare le issue e su quante risorse dedicarvi.

In un mondo ideale ci dovrebbe essere qualcuno del DPC che effettua un triage delle issue, assegna una categoria, e per le issue più gravi, come la #1185, inizia una procedura di mitigazione immediata. 

Solo a questo punto, per le issue non gravi (per esempio richieste di aiuto da parte degli utenti, o suggerimenti su quali dati pubblicare), sarebbe possibile e giusto procedere ad una chiusura automatica.

Come è adesso non serve a molto... non so' nemmeno perché scrivo queste considerazioni, che forse non leggerà nessuno del DPC.

**Comment by tiziodcaio** [comment]
In quel caso imponi l'uso di github discussions per le discussioni e le issue per problemi/miglioramenti concreti

**Comment by matteoopenf** [comment]
ma qualcuno realmente prende in carico le issue o vengono aperte e li muoiono?

**Comment by pierluigicara** [comment]
Stiamo consapevoli della problematica e, più in generale, stiamo predisponendo una proposta interna per migliorare l'organizzazione e la gestione complessiva dei processi di valorizzazione del patrimonio informativo del DPC, in questa proposta l'engagement con gli utenti è una delle questioni che vengono affrontate, il tutto in coerenza con le attuali Linee Guida AgID e l'attuale contesto normativo (in grande evoluzione). Attualmente per questo repository il nostro sforzo è rivolto soprattutto al miglioramento del livello di qualità complessivo dei dati in senso preventivo, durante il flusso quotidiano e negli scambi con il Ministero della Salute. Già solo questa attività richiede uno sforzo complessivo e continuativo non indifferente. Le segnalazioni che comunque arrivano sono prese in considerazione, con maggiore attenzione - naturalmente -, a quelle che riguardano problematiche sui dati pubblicati, compatibilmente con le risorse di cui disponiamo per poterle affrontare. La #1185 (ma ce ne sono molte altre) ne è un esempio.
