### ISSUE TITLE
Confronto dati tamponi totali con green pass da tamponi

### ISSUE THREAD

**Issue by sylviepaulette** [pcm-dpc/COVID-19#1189]
Buonasera, conteggiando i tamponi totali  tra il 15 ottobre ed il 14 novembre mi sono accorta che questo numero (13931423) risulta essere inferiore al numero di green pass rilasciati con tampone (18507600) ricavabile dal database: https://github.com/ministero-salute/it-dgc-opendata/blob/9bfcf97d778e4723187b96bffa8b4e26cc450ef5/data/dgc-issued.csv.
Come è possibile?

**Comment by vi-enne** [comment]
Una possibile spiegazione sono tamponi negativi di test effettuati in farmacia, della quale si hanno pero solo [evidenze aneddotiche](https://twitter.com/dani_geng/status/1459986236131753984):

_"in caso di tampone negativo in farmacia siamo autorizzati a non inserire i dati nel portale ASL ma solo nel sistema Tessera Sanitaria per l'emissione contestuale del Green Pass"_

Concordo che una spiegazione ufficiale sarebbe necessaria.

Propongo una rappresentazione grafica e il [codice](https://github.com/vi-enne/codici_utili/tree/main/confrontoGP-PC) per replicarla.

![confrontoTamponiBarre_2021-11-28](https://user-images.githubusercontent.com/44818674/143961768-c301889a-d12e-4d23-a8c2-c19dfcb18e5a.png)

**Comment by sylviepaulette** [comment]
Grazie per la spiegazione.
Quindi secondo te, ci sarebbe un modo (incrociando dati ed escludendo quelli sovrapponibili) per sapere quanti vaccinati/non vaccinati si sono sottoposti ai test?

**Comment by vi-enne** [comment]
Con i dati pubblicamente disponibili non credo, ma con quelli che ha il Ministero della Salute sicuramente: a solo titolo di esempio, entrambi i sistemi usano la Tessera Sanitaria.

**Comment by sylviepaulette** [comment]
Per entrambi i sistemi cosa intendi? il sistema della raccolta dati della protezione civile ed il sistema del ministero della salute? Inoltre, per quanto riguarda i dati sul ministero della salute ho questo: https://github.com/ministero-salute/it-dgc-opendata/blob/3409da8ecfdf1566e4518b4bc878f0db12e421a3/data/dgc-acquired.csv
Ho due voci circa il sistema tessera sanitari: "acquired by web-ts" e "acquired by operator-ts". Queste due voci sono sovrapponibili (nel senso che la seconda è inclusa nella prima) o vanno sommate? 
In pratica a cosa corrispondono?

**Comment by vi-enne** [comment]
Ripeto che con i dati pubblicamente disponibili NON è possibile.

Con i sistemi intendo quello sulle vaccinazioni e emissione di relativo Green Pass, che sono basati su Tessera Sanitaria.
Per un determinato Codice Fiscale, ad avere entrambi i dataset disaggregati e non anonimizzati, è possibile in linea teorica sapere se una persona che si sottopone al test è vaccinata oppure no.

Il pubblico non può ovviamente farlo.

**Comment by sylviepaulette** [comment]
Ovvio che i dati sensibili non possono essere resi pubblici.
Grazie comunque per le spiegazioni.

**Comment by vi-enne** [comment]
Di niente!
Rimaniamo in attesa di una risposta ufficiale.

**Comment by audetto** [comment]
Sarebbe molto interessante (per non dire necessario) avere i dati per categorie di green pass.

Essendo dati aggregati a livello nazionale, non mi sembra ci sia alcuna question di privacy.
Le categorie che mi piacerebbe vedere sono

1. con green pass rafforzato
2. senza green pass rafforzato

E' sempre piu' chiaro che le due categorie si comportano in modo molto diverso rispetto alla malattia per cui il dato totale solleva sempre piu' questioni a cui ognuno da' una risposta soggettiva e diversa.

Io direi che il totale e' praticamente inutile per avere un'idea chiara di cosa sta realmente succedendo.

**Comment by pierluigicara** [comment]
Ancora grazie a @vi-enne per la puntuale e accurata risposta (e anche per l'instancabile lavoro di ricerca e analisi che la rende possibile) e per l'aiuto indiretto che viene offerto: un bell'esempio di sussidiarietà orizzontale!
Non mi pare che ci sia molto da aggiungere, se non che la "risposta ufficiale" dovrebbe essere quella del Ministero della Salute.
