### ISSUE TITLE
Fasce di età sbagliate in popolazione-istat-regione-range.csv

### ISSUE THREAD

**Issue by jumpjack** [pcm-dpc/COVID-19#1190]
Le fasce di età in cui sono raggruppati i dati del file non sono utili per le statistiche sul covid, perchè non includono/escludono la fascia 0-12 anni, o le fasce 0-4 e 5-12, che hanno trattamenti vaccinali diversi dagli adulti.

**Comment by pierluigicara** [comment]
Grazie per la segnalzione che è condivisibile per il suo contenuto. Tuttavia i file contenuti nella cartella dati-statistici-riferimento rappresentano un test che abbiamo condotto per fornire dei dati di utilità per gli utenti. Successivamente ci siamo resi conto che non essendo titolari di tali informazioni non riusciamo a garantire l'uso ottimale di tali informazioni. 
Pertanto, si ritiene necessario reindirizzare gli utilizzatori interessati a queste informazioni al sito demo.istat.it
