### ISSUE TITLE
Errore Friuli Venezia Giulia in file dpc-covid-19-aree-nuove-g.json

### ISSUE THREAD

**Issue by jumpjack** [pcm-dpc/COVID-19#1191]
Alla riga 7.505.872 del file manca la data di fine provvedimento, quindi il risultato è che sembra che il Friuli sia in zona gialla dal 26/04/2021 invece che dal 29/11/2021 .

Inoltre, non si potrebbero separare i 150 MB di dati costanti di questo file (quelli dei confini) dai dati sui colori?

**Comment by pierluigicara** [comment]
Grazie della segnalazione. Per errore è stato cancellato il record della variazione del 31 maggio 2021 con la quale il Friuli passava alla zona bianca a seguito dell'Ordinanza del 28 maggio 2021, insieme a Molise e Sardegna, che origina appunto l'anomalia segnalata. Verrà ripubblicato il file corretto.
Per l'altra osservazione si rimanda a quanto già esposto al riguardo in numerose issue precedenti.
