### ISSUE TITLE
Visibilità di default dei dati di positività e ospedalizzazioni con suddivisione delle quantità per "Non Vaccinati", "Vaccinati", "Vaccinati incompleti", e fasce di età per le schede riepilogative.

### ISSUE THREAD

**Issue by dorvan** [pcm-dpc/COVID-19#1192]
## Riassunto

Penso sia interessante poter inserire la visibilità nelle schede riepilogative delle suddivisione delle quantità per "Non Vaccinati", "Vaccinati(min 6 mesi e oltre 6 mesi)", "Vaccinati incompleti" con le fasce di età per le schede riepilogative.

## Interesse pubblico

Penso sia doveroso avere in modo limpido l'incidenza del contagio, la distribuzione delle ospedalizzazione e TI rispetto alla copertura del vaccino soprattutto in merito ai dati sull'effettiva copertura vaccinale diffusi nei mesi scorsi, idem per le infezioni e le osedalizzazioni post terza dose.

**Comment by pierluigicara** [comment]
Abbiamo già risposto a richieste analoghe in precedenza (solo per citare le ultime vedi #1181 e #1182). Al momento la situazione non è mutata e, pertanto, si rimanda alla risposta data alla #1169.
