### ISSUE TITLE
Vaccinati e non vaccinati

### ISSUE THREAD

**Issue by DSolerte** [pcm-dpc/COVID-19#1193]
Non sarebbe meglio poter visionare sui positivi quali di questi sono vaccinati e quali non lo sono ? Soprattutto per quelli che finiscono in terapia intensiva il dato sarebbe molto più significativo a mio parere, soprattutto in vista della variante Omicron che sta iniziando a circolare.

**Comment by vi-enne** [comment]
Per facilitare il lavoro di chi gestisce le repo GitHub, è importante controllare se alla issue che si sta per aprire è già stata data risposta in passato, consultando le issue chiuse.

@pierluigicara ha già risposto alla domanda nelle issue #1168, #1169, #1181, #1182 e #1192. La riporto:

> Recentemente sono giunte altre richieste analoghe (vedi ad esempio #1168 ) e la nostra risposta al momento resta la stessa: per poter pubblicare in questo repository i dati richiesti, tali dati devono essere forniti dal Ministero della Salut, ma ancora manca un'indicazione specifica da parte del Ministero al riguardo. Comunque - come ricordato anche da @Fuffo00339958 nel thread citato), nel report settimanale dell'ISS si trovano le informazioni richieste (a pag.17 di https://www.epicentro.iss.it/coronavirus/bollettino/Bollettino-sorveglianza-integrata-COVID-19_8-settembre-2021.pdf che è quello più recente).

I dati sono estratti @maxdevblock sono disponibili qui

https://github.com/maxdevblock/covid_iss_vaccini_reports
