### ISSUE TITLE
Riga vuota nel file province

### ISSUE THREAD

**Issue by sausyn** [pcm-dpc/COVID-19#1194]
Tipo di issue:

- [x] Dati mancanti o errati 
- [ ] Errore nella documentazione 
- [ ] Errore o mancanza nella dashboard 
- [ ] Problemi di visualizzazione nella dashboard 

- Regione:
- Provincia: tutte 

## Riassunto

Riga vuota (n. 92651) nel file dati-province/dpc-covid19-ita-province.csv

**Attesa:**

Nessuna riga vuota

**Attuale:** 

La riga n. 92651 è vuota e causa problemi con gli import automatici del file

**Comment by miccoli** [comment]
Mi sono accorto anche io del problema, introdotto in 5002c1326. Mi sono permesso di fare una PR che risolve il bug.

:pray: :pray: per gli sviluppatori: prima del push guardate quale modifiche state introducendo, non è concepibile che delle righe bianche scappino così per caso!

:pray: :pray: :pray: :pray: a quando procedure di QA integrate nel flusso di lavoro? [GitHub actions](https://github.com/features/actions) è potente e facile da usare!
