### ISSUE TITLE
Pandemic data "Deaths"

### ISSUE THREAD

**Issue by mohamed-hachaichi** [pcm-dpc/COVID-19#1196]
Hey there folks, 

is there any deaths number at the province level? 

Many thanks, and good job!

**Comment by pierluigicara** [comment]
The data flow that is published in this repository does not include this information as it is documented in the appropriate sections. For further data it is advisable to consult https://www.epicentro.iss.it/coronavirus/sars-cov-2-sorveglianza-dati .
