### ISSUE TITLE
Errore nei Dati Calabria 03/12/2021

### ISSUE THREAD

**Issue by mmenniti** [pcm-dpc/COVID-19#1197]
Tipo di issue:

- [X] Dati mancanti o errati 
- [ ] Errore nella documentazione 
- [ ] Errore o mancanza nella dashboard 
- [ ] Problemi di visualizzazione nella dashboard 

- Regione: Calabria
- Provincia: 

## Riassunto

**Attesa:**

**Attuale:**

**Comment by mmenniti** [comment]
Il dato relativo al Totale persone testate in Calabria è sicuramente errato, ieri erano 1.210.692, oggi non possono essere 1.221.391 (+10.700 circa) con soli 5823 tamponi totali

**Comment by pierluigicara** [comment]
Grazie della segnalazione. Il Ministero ha certificato l'anomalia il giorno 4/12/2021 fornendo anche il dato corretto (vedi nota) e quindi abbiamo potuto conseguentemente correggere anche il dato anomalo nella medesima data.

**Comment by mmenniti** [comment]
Avevo visto, grazie mille e buon lavoro.
