### ISSUE TITLE
Dati tamponi

### ISSUE THREAD

**Issue by NicolettaK** [pcm-dpc/COVID-19#12]
Sarebbe estremamente utile avere i dati sul numero di tamponi eseguiti, per regione se non è possibile averli per provincia. 

(Grazie, avere messo su questa repo fa davvero onore al lavoro della protezione civile in questa situazione)

**Comment by etrevis** [comment]
@NicolettaK nel frattempo dai un'occhiata [qui](https://github.com/etrevis/DB-and-Visuals-Covid-19-/blob/master/Data/DB.csv). Type  = tested è il numero dei tamponi. Questi dati li ho estratti oggi dai pdf prima che creassero questa repo.

**Comment by NicolettaK** [comment]
@etrevis grazie!

**Comment by umbros** [comment]
I dati dei tamponi vengono dati per Regione, nel tracciato è l'ultimo campo. 
https://raw.githubusercontent.com/pcm-dpc/COVID-19/master/dati-regioni/dpc-covid19-ita-regioni-20200306.csv
