### ISSUE TITLE
Distinzione ospedalizzati tra vaccinati e non vaccinati

### ISSUE THREAD

**Issue by danielegts** [pcm-dpc/COVID-19#1200]
**Tipo di richiesta**:  richiesta di dati 

## Riassunto

Sarebbe interessante avere i dati riguardanti le ospedalizzazioni (in particolare le terapie intensive) suddivisi tra vaccinati e non vaccinati

## Interesse pubblico

Avere questo dato permetterebbe di analizzare la correlazione tra vaccino e ospedalizzazioni

**Comment by pierluigicara** [comment]
Abbiamo già risposto a richieste analoghe in precedenza (solo per citare le ultime vedi #1181 e #1182). Al momento la situazione non è mutata e, pertanto, si rimanda alla risposta data alla #1169.
