### ISSUE TITLE
Bolzano casi testati totali 5431200 invece di 543120

### ISSUE THREAD

**Issue by Rabelaiss** [pcm-dpc/COVID-19#1201]
il dato di oggi ha uno 0 in più

```
2021-12-09T17:00:00,ITA,21,P.A. Bolzano,...,541953,...
2021-12-10T17:00:00,ITA,21,P.A. Bolzano,...,5431200,...
```

l'errore è presente anche nel file dpc-covid19-ita-andamento-nazionale.csv

**Comment by RiccardoBorchi** [comment]
L'errore è presente a livello nazionale. In Italia le persone sottoposte a tampone per la prima volta risultano 4.975.370. Immagino ci sia più di uno zero in più, forse due, considerando che i tamponi effettuati nella stessa giornata risultano 716.287.

**Comment by Rabelaiss** [comment]
@RiccardoBorchi L'errore nel dato nazionale è causato dall'errore nel dato di Bolzano, in cui risulta un incremento di casi testati pari a
`5431200 - 541953 = 4889247`
invece di
`543120 - 541953 = 1167`

**Comment by alfredonodo** [comment]
Esatto confermo che c'è un errore di un fattore 10 per la provincia di Bolzano.

**Comment by RiccardoBorchi** [comment]
> @RiccardoBorchi L'errore nel dato nazionale è causato dall'errore nel dato di Bolzano, in cui risulta un incremento di casi testati pari a `5431200 - 541953 = 4889247` invece di `543120 - 541953 = 1167` a causa di uno `0` in più nel totale dei casi testati di Bolzano.

Sì, esatto.

**Comment by alfredonodo** [comment]
Ci sarà una rettifica?

**Comment by RiccardoBorchi** [comment]
> Ci sarà una rettifica?

Immagino e spero di sì.

**Comment by RossoDeM** [comment]
Sì, beh... non è che servano eoni per modificare
1) P.A. Bolzano 543120 anziché 5431200
2) Nazionale 38,715,745 anziché 43,603,825

**Comment by pierluigicara** [comment]
Grazie della segnalazione, il Ministero ci ha ritrasmesso i dati corretti e abbiamo fatto l'aggiornamento.
