### ISSUE TITLE
Nuovi casi: a quale data si riferiscono?

### ISSUE THREAD

**Issue by RiccardoBorchi** [pcm-dpc/COVID-19#1203]
Ciao!

Vorrei che fosse chiarito, una volta per tutte, questo punto: a quale data effettiva si riferiscono i dati giornalieri?

I dati dei bollettini quotidiani dovrebbero riferirsi al giorno precedente, giusto? Non dovrebbero tenere in considerazione i dati del giorno stesso in cui esce, anche perché tale giorno non è ancora concluso, giusto? Inoltre, escono nel primo pomeriggio e serve un po' di tempo per elaborare e trasmettere i dati.

Quindi, ad esempio, i nuovi positivi comunicati in data 19/12/2021 sono, in realtà, i nuovi positivi del 18/12/2021 e non del 19/12/2021 (come molti comunicano o fanno intendere), giusto? E non è, forse, neanche corretto dire nelle "ultime 24 ore", se il dato si riferisce a un giorno esatto (da mezzanotte a mezzanotte).

Fatemi sapere qual è la più corretta interpretazione, grazie!

**Comment by pierluigicara** [comment]
Quello che possiamo certificare con certezza è il flusso informativo (così come documentato nel readme). Ovvero che, quotidianamente e nella fascia oraria indicata, il Ministero trasmette al Dipartimento della protezione civile i dati (che raccoglie dalle regioni e province autonome) riferiti al giorno corrente (vedi scheda riepilogativa e dati province e regioni). L'unica ulteriore indicazione esplicita circa possibili scostamenti temporali da parte di singole regioni o province autonome su specifiche informazioni, viene riportata dal medesimo Ministero nelle note, che vengono anch'esse puntualmente pubblicate quotidianamente (ove presenti, naturalmente).

**Comment by RiccardoBorchi** [comment]
> Quello che possiamo certificare con certezza è il flusso informativo (così come documentato nel readme). Ovvero che, quotidianamente e nella fascia oraria indicata, il Ministero trasmette al Dipartimento della protezione civile i dati (che raccoglie dalle regioni e province autonome) riferiti al giorno corrente (vedi scheda riepilogativa e dati province e regioni). L'unica ulteriore indicazione esplicita circa possibili scostamenti temporali da parte di singole regioni o province autonome su specifiche informazioni, viene riportata dal medesimo Ministero nelle note, che vengono anch'esse puntualmente pubblicate quotidianamente (ove presenti, naturalmente).

Ho letto, ma se le Regioni trasmettono i dati entro le ore 16:30 è evidente che quei dati non possano riferirsi interamente al giorno corrente (se sono relativi a 24 ore), inoltre mancano quelli dalle ore 16:30 alle ore 23:59. Quindi, se i dati inseriti dalle Regioni sono aggiornati fino a quel momento (circa le ore 16:00), teoricamente i dati che inseriscono, se riguardano un'arco temporale di 24 ore, fanno riferimento a un periodo che va dalle ore 16 del giorno precedente alle ore 16 del giorno corrente, più o meno. Non si tratta, quindi, come pensavo, di un dato che fa riferimento a un giorno pieno (0-24), ma di un dato accavallato tra due giorni. E i dati non si riferiscono tutti i giorni, quindi, allo stesso arco temporale (per via di possibili scostamenti temporali di singole Regioni).

**Comment by RiccardoBorchi** [comment]
> Quello che possiamo certificare con certezza è il flusso informativo (così come documentato nel readme). Ovvero che, quotidianamente e nella fascia oraria indicata, il Ministero trasmette al Dipartimento della protezione civile i dati (che raccoglie dalle regioni e province autonome) riferiti al giorno corrente (vedi scheda riepilogativa e dati province e regioni). L'unica ulteriore indicazione esplicita circa possibili scostamenti temporali da parte di singole regioni o province autonome su specifiche informazioni, viene riportata dal medesimo Ministero nelle note, che vengono anch'esse puntualmente pubblicate quotidianamente (ove presenti, naturalmente).

Ho letto, ma se le Regioni trasmettono i dati entro le ore 16:30, evidentemente quei dati non si riferiscono interamente a quel giorno (se relativi a un'arco temporale di 24 ore), infatti mancherebbero i dati dalle ore 16:30 alle ore 23:59 (che dovrebbero essere, a questo punto, considerati il giorno successivo). Quindi quei dati fanno riferimento, in realtà, a un periodo che va dalle ore 16 del giorno precedente alle ore 16 del giorno corrente, più o meno. Anche se, ad esempio, il TGR Toscana indica i dati giornalieri già con l'edizione delle ore 14, quindi significa che a quell'ora la Toscana ha già trasmesso i dati aggiornati (e, per forza di cose, non possono riferirsi fino alle ore 16:30, ma al massimo fino alle ore 13:30, considerando il tempo di leggerli e inserirli nel servizio, più o meno). In questo caso viene da pensare che i dati non facciano riferimento tutti i giorni allo stesso arco temporale che, tra l'altro, può variare in base alle singole Regioni. E i dati, in questo caso, non si riferiscono a un giorno pieno (0-24), ma sono accavallati tra due giorni.

**Comment by RiccardoBorchi** [comment]
> Quello che possiamo certificare con certezza è il flusso informativo (così come documentato nel readme). Ovvero che, quotidianamente e nella fascia oraria indicata, il Ministero trasmette al Dipartimento della protezione civile i dati (che raccoglie dalle regioni e province autonome) riferiti al giorno corrente (vedi scheda riepilogativa e dati province e regioni). L'unica ulteriore indicazione esplicita circa possibili scostamenti temporali da parte di singole regioni o province autonome su specifiche informazioni, viene riportata dal medesimo Ministero nelle note, che vengono anch'esse puntualmente pubblicate quotidianamente (ove presenti, naturalmente).

Ho letto, ma se le Regioni trasmettono i dati entro le ore 16:30, evidentemente quei dati non si riferiscono interamente a quel giorno (se relativi a un'arco temporale di 24 ore), infatti mancherebbero i dati dalle ore 16:30 alle ore 23:59 (che dovrebbero essere, a questo punto, considerati il giorno successivo). Quindi quei dati fanno riferimento, in realtà, a un periodo che va dalle ore 16 del giorno precedente alle ore 16 del giorno corrente, più o meno. Anche se, ad esempio, il TGR Toscana indica i dati giornalieri già con l'edizione delle ore 14, quindi significa che a quell'ora la Toscana ha già trasmesso i dati aggiornati (e, per forza di cose, non possono riferirsi fino alle ore 16:30, ma al massimo fino alle ore 13:30, considerando il tempo di leggerli e inserirli nel servizio, più o meno). In questo caso pare che i dati non facciano riferimento tutti i giorni allo stesso arco temporale che, tra l'altro, può variare in base alle singole Regioni. E i dati, in questo caso, non si riferiscono a un giorno pieno (0-24), ma sono accavallati tra due giorni.

**Comment by Rabelaiss** [comment]
non c'è una regola generale, ogni regione fa da se, ad esempio

campania: nel [bollettino](http://www.regione.campania.it/assets/documents/agg-20122021-1700.pdf) di ieri 20/12/21 si leggono due cose
* bollettino del 20 dicembre 2021 aggiornato alle 23:59 del 19 dicembre
* il numero di deceduti fa riferimento alle ultime 48 ore

veneto: nel [bollettino](https://www.ilgazzettino.it/uploads/ckfile/202112/covid-veneto-bollettino-oggi-19-dicembre-2021_19112104.pdf) del 19/12/21 si legge
* Report del 19/12/2021 ore 8:00 (variazioni rispetto al 18/12/2021 ore 8:00)

molise: comunica ogni giorno alle 18-19 circa i dati che il giorno dopo la protezione civile carica su github

**Comment by RiccardoBorchi** [comment]
> non c'è una regola generale, ogni regione fa da se, ad esempio
> 
> campania: nel [bollettino](http://www.regione.campania.it/assets/documents/agg-20122021-1700.pdf) di ieri 20/12/21 si leggono due cose
> 
> * bollettino del 20 dicembre 2021 aggiornato alle 23:59 del 19 dicembre
> * il numero di deceduti fa riferimento alle ultime 48 ore
> 
> veneto: nel [bollettino](https://www.ilgazzettino.it/uploads/ckfile/202112/covid-veneto-bollettino-oggi-19-dicembre-2021_19112104.pdf) del 19/12/21 si legge
> 
> * Report del 19/12/2021 ore 8:00 (variazioni rispetto al 18/12/2021 ore 8:00)
> 
> molise: comunica ogni giorno alle 18-19 circa i dati che il giorno dopo la protezione civile carica su github

Infatti, è questo il punto, quindi non c'è verso di sapere i dati effettivi di un giorno intero, se invece ogni Regione comunicasse i dati alla stessa maniera e in modo puntuale, avremmo anche un dato giornaliero nazionale più uniforme.

**Comment by pierluigicara** [comment]
Può essere utile su questo tema consultare anche i Monitoraggi settimanali del Ministero della Salute, come ad es. [questo](https://www.salute.gov.it/imgs/C_17_monitoraggi_91_0_fileNazionale.pdf), dove sono evidenti le oascillazioni di cui trattasi e - più in generale - il livello di qualità complessivo degli indicatori regionali (grazie anche a @vi_enne per la segnalazione su Twitter di questo specifico monitoraggio).

**Comment by RiccardoBorchi** [comment]
> Può essere utile su questo tema consultare anche i Monitoraggi settimanali del Ministero della Salute, come ad es. [questo](https://www.salute.gov.it/imgs/C_17_monitoraggi_91_0_fileNazionale.pdf), dove sono evidenti le oascillazioni di cui trattasi e - più in generale - il livello di qualità complessivo degli indicatori regionali (grazie anche a @vi_enne per la segnalazione su Twitter di questo specifico monitoraggio).

Sì, avevo visto i report settimanali del Ministero della Salute e, in effetti, sono utili per vedere la situazione a livello settimanale, anche per capire i trend. Però rimane la questione posta perché i dati a cui si riferisce sono sempre quelli (magari con le eventuali correzioni giunte successivamente), nel senso che le settimane prese in considerazione fanno riferimento agli aggiornamenti dei bollettini e non ai giorni effettivi a cui si riferiscono i dati (perché, come specificato prima, vengono trasmessi a metà giornata e fanno riferimento, a quanto pare, anche al giorno precedente, in parte), per cui, ad esempio, il monitoraggio della settimana dal 29/11/2021 al 05/12/2021, in realtà, prende in esame anche dei dati relativi, parzialmente, al 28/11/2021 e non tutti i dati relativi al 05/12/2021. In ogni caso, certamente, i monitoraggi settimanali sono migliori per avere un'idea più complessiva della situazione, al netto di eventuali scostamenti temporali di qualche ora di singole Regioni (che, in questo caso, risultano più superflui). In sostanza, le date considerate si riferiscono agli aggiornamenti del Ministero della Salute e non all'avvenimento dell'evento (esito tampone, guarigione, decesso, ecc.).
