### ISSUE TITLE
Error su consegne-vaccini-latest.csv

### ISSUE THREAD

**Issue by marcosqlbi** [pcm-dpc/COVID-19#1204]
Tipo di issue:

- [X ] Dati mancanti o errati consegne-vaccini-latest.csv
- [ ] Errore nella documentazione 
- [ ] Errore o mancanza nella dashboard 
- [ ] Problemi di visualizzazione nella dashboard 

- Regione: tutte
- Provincia: non rilevante

## Riassunto

Nel file consegne-vaccini-latest.csv ci sono dei dati errati - diverse consegne di Moderna hanno come data 1899-12-30.

Riporto un esempio in cui il dato per LOM è errato, è sempre il primo dato di una regione nell'ordine fisico del file.

LIG,Pfizer/BioNTech,37440,2021-12-22,ITC,ITC3,7,Liguria
LOM,Moderna,106300,1899-12-30,ITC,ITC4,3,Lombardia
LOM,Pfizer/BioNTech,1620,2020-12-27,ITC,ITC4,3,Lombardia

Quelle righe dovrebbero riportare la data corretta.

**Comment by pierluigicara** [comment]
Non è questo il repo giusto dove fare questa osservazione, ma https://github.com/italia/covid19-opendata-vaccini che è sotto la responsabilità del Commissario straordinario per l'emergenza Covid-19.
