### ISSUE TITLE
Availability of new hospital admissions

### ISSUE THREAD

**Issue by edomt** [pcm-dpc/COVID-19#1205]
**Type of issue**: request for information (or data?)

## Public interest

We're working on adding more hospital & ICU data to [Our World in Data](https://ourworldindata.org/explorers/coronavirus-data-explorer), and hospital admissions are one of the most important metrics at the moment.

## Summary

Looking at [`dpc-covid19-ita-andamento-nazionale.csv`](https://github.com/pcm-dpc/COVID-19/blob/master/dati-andamento-nazionale/dpc-covid19-ita-andamento-nazionale.csv) we were able to find the following variables:

- terapia_intensiva: stock of current ICU patients
- totale_ospedalizzati: stock of current hospital patients
- ingressi_terapia_intensiva: daily new ICU admissions

But we haven't found an equivalent to that last field for daily new *hospital* admissions. Does it exist somewhere?
Thank you!

**Comment by vi-enne** [comment]
Unfortunately those data are (still) not available in this repository. 

You can find them by event date on INFN website, that publishes some of Istituto Superiore di Sanità data

https://covid19.infn.it/iss/

**Comment by pierluigicara** [comment]
The data flow that is published in this repository does not include this information as it is documented in the appropriate sections. For further data it is advisable to consult https://www.epicentro.iss.it/coronavirus/sars-cov-2-sorveglianza-dati by Istituto Superiore di Sanità and (as also suggested by @vi_enne, whom we thank) the INFN website.

**Comment by pierluigicara** [comment]
Sorry the right citation is @vi-enne
