### ISSUE TITLE
Pubblicare i dati per categorie di green pass.

### ISSUE THREAD

**Issue by audetto** [pcm-dpc/COVID-19#1207]
**Tipo di richiesta**: richiesta di dati

## Riassunto

Penso sia oramai necessario separare tutti i dati (esempio: https://github.com/pcm-dpc/COVID-19/blob/master/dati-json/dpc-covid19-ita-andamento-nazionale-latest.json) in diverse categorie di green pass / vaccinazione.

Dovrebbero esserci 2 categorie per ogni dato (almeno a livello nazionale)

1. con green pass rafforzato
2. senza

Le due categorie hanno comportamenti totalmente diversi vis a vis della malattia, per cui il dato totale e' quasi inutile.

Essendo comunque un dato a livello nazionale, non vedo nessuna implicazione a livello di privacy personale.

## Interesse pubblico

Ci sono sempre piu' speculazioni sul comportamento dei diversi gruppi rispetto alle varie fasi della malattia:

1. chi fa il tampone?
2. chi e' positivo?
3. chi si ammala?
4. chi deve essere ricoverato?
5. chi soccombe alla malattia?

In giro ci sono varie teorie (e il loro contrario) su che categorie di persone (vaccinate o no) ricadono nei 5 gruppi. Il dato relativo ai vaccini e' oramai indispensabile per qualsiasi analisi accurata dell'andamento della malattia.

E, se per assurdo, venisse fuori che la vaccinazione non cambia di una virgola la percentuale delle 5 categorie, sarebbe comunque un risulato estremamenete importante (ancora piu' importante che se i dati fossero completamente diversi).

**Comment by pierluigicara** [comment]
Al momento il flusso delle informazioni è quello riportato del readme. Fintanto che il Ministero della Salute non si farà carico di modificare le informazioni trasmesse, ad esempio integrandole come proposto, non sarà possibile modificare/integrare i dati attualmente pubblicati.

**Comment by audetto** [comment]
Capisco.
Se lo chiedo io, neanche mi guardano, ma se la Protezione Civile facesse richiesta, qualche speranza forse c'e'?

Non e' che magari hanno paura a divulgarli?

**Comment by sylviepaulette** [comment]
Concordo con te. Anche perché guardando i bollettini sorveglianza integrata iss, se si considerasse  il tasso di letalità, non sulla popolazione, ma sulle infezioni (ossia chi ha il covid quante possibilità ha di morire in base allo stato vaccinale), emergerebbe addirittura che il tasso di letalità dei non vaccinati è addirittura inferiore sia a quello di coloro che hanno uno stato vaccinale di oltre 5 mesi, ma anche di coloro che hanno fatto il booster. Considerando che il decesso avviene dopo 3 settimane dalla diagnosi. Quindi cambiando il denominatore (popolazione di riferimento con popolazione positiva) i numeri sono sconcertanti. Questo significa che o il vaccino non protegge dalla malattia, oppure le infezioni tra la popolazione vaccinata sono in numero nettamente superiore a quello dichiarato. Spiego tutto in questo articolo: https://sfero.me/article/incognite-misteri-bollettini-iss
