### ISSUE TITLE
ISS: Epidemia COVID-19 Aggiornamento nazionale 28 dicembre 2021 – ore 12:00 DATA PUBBLICAZIONE: 31 DICEMBRE 2021

### ISSUE THREAD

**Issue by Fuffo00339958** [pcm-dpc/COVID-19#1208]
Pubblicato finalmente il rapporto ISS più recente: https://www.epicentro.iss.it/coronavirus/sars-cov-2-sorveglianza-dati.   Ma a una prima occhiata, la tabella 5 a pag. 25 che riassume i vari gradi di infezione rapportati alla popolazione di NON vaccinati e VACCINATI in diversa misura, molto significativa, è errata: sono gli stessi identici valori della settimana precedente, aggiornati sono solo i periodi di riferimento. 
Comunque, dopo una rielaborazione per evidenziare gli Indici di Rischio, si evidenzia che le percentuali di occupazione per ogni tipologia di sintomo in relazione alla fascia d'età (significativamente variabili), non sono esattamente quelle citate in interviste di primari di ospedale, del tipo: "L'80% dei ricoverati è costituito dai non vaccinati", può esserlo (o anche di più) localmente, e non per tutte le fasce d'età, ad es.  per i ricoveri semplici, la % media nazionale dei non vaccinati (che costituirebbero il 13% della popolazione over12) è il 47% (con max 72% nella fascia d'età 40-59 anni); in terapia intensiva la media è 64% (con max 84% nella stessa fascia d'età, e 82% per i 12-39); per i decessi la media è 42% (max. 80% per i 12-39, 71% per i 40-59). Valori nei periodi indicati, che come detto sopra, non si capisce quali siano, e naturalmente, sempre che i dati forniti siano corretti.

Si richiede se sono accessibili i dati grezzi, per ricostruire la tabella citata, per includere anche le fasce d'età 0-4 (non vaccinabili) e 5-11 (vaccinabili), e soprattutto per offrire le viste regionali.

[ISS-COVID-Aggiornamento_28dic2021.xlsx](https://github.com/pcm-dpc/COVID-19/files/7797592/ISS-COVID-Aggiornamento_28dic2021.xlsx)

**Comment by pierluigicara** [comment]
Una possibile fonte aggiuntiva rispetto all'ISS per i dati del "sistema di sorveglianza integrata COVID-19" in Italia può essere il sito https://covid19.infn.it/iss/
