### ISSUE TITLE
Dato tamponi lazio 11/03

### ISSUE THREAD

**Issue by gabrielepinto** [pcm-dpc/COVID-19#121]
Tipo di issue:

- [X] Dati mancanti o errati 
- [ ] Errore nella documentazione 
- [ ] Errore or mancanza nella dashboard 
- [ ] Problemi di visualizzazione nella dashboard 

## Riassunto

il dato dei tamponi dell'11 Marzo è uguale a quello del giorno prima (3591). possibile ?
**Attesa:**

**Attuale:**

**Comment by umbros** [comment]
Ciao @gabrielepinto sono i dati comunicati da Regione Lazio, potrebbe essere che non sono pervenuti dati aggiornati o (ma dubito) che non siano stati fatti tamponi.
