### ISSUE TITLE
Marche Numero tamponi rapidi positivi zero

### ISSUE THREAD

**Issue by matteoopenf** [pcm-dpc/COVID-19#1211]
Tipo di issue:

- [x ] Dati mancanti o errati 
- [ ] Errore nella documentazione 
- [ ] Errore o mancanza nella dashboard 
- [ ] Problemi di visualizzazione nella dashboard 

- Regione: Marche
- Provincia: 

## Riassunto

Attualmente il pdf che riporta tutti i dati quindi tamponi fatti incrementi ecc riporta che le marche hanno i tamponi rapidi positivi con valore zero vedi allegato di seguito:

![image](https://user-images.githubusercontent.com/43987335/149354771-18119e23-9aa3-4ccf-b829-e8028e1ea72f.png)

Questo lo sto riscontrando da alcuni giorni
**Attesa:**

Come comportamento atteso, è un valore diverso da zero, essendo che so di tamponi rapidi testati e positivi
**Attuale:**  come da screen il valore è zero attualmente

**Comment by vi-enne** [comment]
Dalla [nota odierna delle Marche](https://github.com/pcm-dpc/COVID-19/blob/master/dati-regioni/dpc-covid19-ita-regioni-20220113.csv)


_"Il giorno 12 è stata firmata nella Regione Marche la circolare per il conteggio della positività anche solo con il percorso antigenico, i dati in data odierna ancora non contengono il flusso antigenico che verrà inserito dalla data del 14 gennaio 2022"_

Mi aspetto dunque che da domani il valore sia diverso da 0.

**Comment by matteoopenf** [comment]
> Dalla [nota odierna delle Marche](https://github.com/pcm-dpc/COVID-19/blob/master/dati-regioni/dpc-covid19-ita-regioni-20220113.csv)
> 
> _"Il giorno 12 è stata firmata nella Regione Marche la circolare per il conteggio della positività anche solo con il percorso antigenico, i dati in data odierna ancora non contengono il flusso antigenico che verrà inserito dalla data del 14 gennaio 2022"_
> 
> Mi aspetto dunque che da domani il valore sia diverso da 0.

ma quindi fino a ieri questo flusso non è mai stato conteggiato, esatto?
Cioè non sarebbe comunque  dovuto essere pubblicato,  poi non preso in considerazione da parte della regione?

O dal momento che non consideravano questo dato lo tenevano a zero?
Come mai però praticamente il resto delle regioni lo conteggiava praticamente?


Grazie ancora

**Comment by vi-enne** [comment]
Molte altre Regioni lo tenevano a 0, altre invece segnalavano o ancora segnalano solo i positivi al rapido che non richiedono conferma con molecolare, non conteggiando quelli poi confermati con molecolare tra i rapidi.
Altre ancora spostano i positivi al rapido a positivi al molecolare una volta confermati.

Traccia di questi cambiamenti si trova nelle note e si osserva anche dalla serie storica.

**Comment by matteoopenf** [comment]
> Molte altre Regioni lo tenevano a 0, altre invece segnalavano o ancora segnalano solo i positivi al rapido che non richiedono conferma con molecolare, non conteggiando quelli poi confermati con molecolare tra i rapidi. Altre ancora spostano i positivi al rapido a positivi al molecolare una volta confermati.
> 
> Traccia di questi cambiamenti si trova nelle note e si osserva anche dalla serie storica.

Grazie del chiarimento.

Allora a verifica di questo per chiudere la issue aspetto i dati di sta sera e domani che se è come dici diventano diversi da zero

**Comment by pierluigicara** [comment]
Grazie ancora a @vi-enne che ha già detto tutto. Posso solo aggiungere che nella nota pubblicata oggi la Regione Marche spiega che da domani comincerà a pubblicare il "flusso antigenico" (testuale).

**Comment by matteoopenf** [comment]
Confermo.

Oggi sono valorizzati.
Grazie ancora 

Matteo Mircoli
Developer | ***@***.*** 

> Il giorno 13 gen 2022, alle ore 18:33, Pierluigi Cara - DPC ***@***.***> ha scritto:
> 
> ﻿
> Closed #1211.
> 
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you authored the thread.

-- 

_
Openforce Srls Unipersonale *| www.openforce.it 
<http://www.openforce.it/> |*__ 02 21119472 | Via Tiziano,32 20145 Milano_
