### ISSUE TITLE
Incremento eccessivo dei casi testati in Veneto (+1.764.860)

### ISSUE THREAD

**Issue by Rabelaiss** [pcm-dpc/COVID-19#1212]
I casi testati del Veneto ieri erano 2.566.507 mentre oggi 4.331.367, errore o hanno aggiunto quelli derivanti da test antigenici?

**Comment by vi-enne** [comment]
[Nota Veneto del 19/01/2022](https://github.com/pcm-dpc/COVID-19/blob/master/dati-regioni/dpc-covid19-ita-regioni-20220119.csv)

_Da oggi alla voce "persone testate" sarà visualizzato il dato sulla popolazione che ha effettuato almeno un test tra antigenici o molecolari. A differenza di quanto riportato fino a ieri (18/01/2022) in cui venivano riportate le persone testate con almeno un test esclusivamente molecolare._

**Comment by Rabelaiss** [comment]
👍 m'era sfuggito

**Comment by pierluigicara** [comment]
Infatti, sempre più spesso nelle ultime settimane, le Regioni utilizzano le note per le comunicazioni relative ai dati anche per comunicazioni che riguardano  vere e proprie modifiche nelle policy sulla loro raccolta. La cosa - naturalmente - non è sfuggita all'attento @vi-enne, che puntualmente ha evidenziato la ragione della variazione segnalata.
