### ISSUE TITLE
Casi sbagliati da almeno due settimane 

### ISSUE THREAD

**Issue by samun3** [pcm-dpc/COVID-19#1214]
Tipo di issue:

- [x] Dati mancanti o errati 
- [ ] Errore nella documentazione 
- [ ] Errore o mancanza nella dashboard 
- [ ] Problemi di visualizzazione nella dashboard 

- Regione:
- Provincia: 

## Riassunto

**Attesa:**

**Attuale:** 

Salve. Da almeno due settimane i dati non coincidono con quelli del bollettino nazionale.

**Comment by pierluigicara** [comment]
Questa osservazione, per come è formulata, non è sufficientemente documentata per poterla gestire.
Si consiglia, di tenere conto delle note trasmesse dalle regioni che, nel periodo indicato, sono particolarmente rilevanti.
