### ISSUE TITLE
errore sequenzatotale positivi a test molecolari

### ISSUE THREAD

**Issue by giovannisebastiani** [pcm-dpc/COVID-19#1215]
Buonasera,
volevo segnalare un'anomalia nella sequenza del totale dei positivi ai test molecolari per alcune regioni, e.g. Veneto, Valle D'aosta, che sono in alcuni giorni decrescenti, come da tabella sottostante dei dati negli ultimi sei giorni.
grazie per l'attenzione e l'aiuto.
cordiali saluti,
Giovanni Sebastiani

    "Abruzzo"                "157046"     "157446"     "157934"     "158357"     "158768"     "159126" 
    "Basilicata"             "57961"      "58114"      "58192"      "58316"      "58379"      "58516"  
    "Bolzano"                "78827"      "78857"      "78881"      "78898"      "78916"      "78984"  
    "Calabria"               "163261"     "162991"     "163345"     "164564"     "164937"     "165390" 
    "Campania"               "847334"     "847993"     "848835"     "849621"     "850305"     "851187" 
    "EmiliaRomagna"          "850455"     "850762"     "851599"     "852599"     "853429"     "854208" 
    "FriuliVeneziaGiulia"    "182201"     "182405"     "182671"     "182876"     "183056"     "183311" 
    "Lazio"                  "834525"     "837085"     "838851"     "840546"     "841939"     "843554" 
    "Liguria"                "213950"     "214199"     "214457"     "214727"     "214944"     "215171" 
    "Lombardia"              "1321594"    "1322673"    "1324048"    "1325037"    "1326294"    "1327278"
    "Marche"                 "202261"     "202525"     "202597"     "202597"     "202833"     "203095" 
    "Molise"                 "22398"      "22407"      "22478"      "22510"      "22556"      "22597"  
    "Piemonte"               "474459"     "474722"     "475035"     "475332"     "475621"     "475872" 
    "Puglia"                 "441502"     "442109"     "442879"     "443491"     "444243"     "444885" 
    "Sardegna"               "141120"     "141342"     "141571"     "141811"     "142076"     "142283" 
    "Sicilia"                "479607"     "480002"     "480479"     "481005"     "481433"     "481937" 
    "Toscana"                "553269"     "553945"     "554766"     "555760"     "556715"     "557621" 
    "Trento"                 "42421"      "42436"      "42455"      "42466"      "42476"      "42483"  
    "Umbria"                 "117867"     "118035"     "118399"     "118644"     "118999"     "119249" 
    "ValleD'Aosta"           "13822"      "13810"      "13803"      "13800"      "13797"      "13795"  
    "Veneto"                 "742728"     "745359"     "808419"     "746501"     "746559"     "747102"

**Comment by pierluigicara** [comment]
Grazie per la segnalazione. Abbiamo già ricevuto in precedenza una analoga segnalazione per altri canali e la abbiamo già sottoposta all'attenzione del Ministero della Salute. Al momento non abbiamo però ancora avuto alcuna risposta.

**Comment by giovannisebastiani** [comment]
Grazie a lei per la pronta risposta e più in generale per tutto il lavoro
che svolgete.
il 1 marzo avevo segnalato il problema al dottor Pezzotti dell'ISS, che
conosco da lungo tempo, e lui mi aveva messo in contatto con la dottoressa
Mannoni, da cui forse avete anche ricevuto la segnalazione. dato che in
passato, quando avevo riscontrato qualche anomalia sui dati, dopo uno-due
giorni i file sul sito della Protezione Civile erano stati sostituiti, non
essendo questo accaduto ora, mi sono mosso.

Il giorno dom 6 mar 2022 alle ore 11:36 Pierluigi Cara - DPC <
***@***.***> ha scritto:

**Comment by giovannisebastiani** [comment]
la dottoressa si chiama Mammone, sorry

Il giorno dom 6 mar 2022 alle ore 11:36 Pierluigi Cara - DPC <
***@***.***> ha scritto:

**Comment by giovannisebastiani** [comment]
buongiorno,
c'è qualche novità sui dati dei test molecolari? quelli del Veneto e della
Valle D'Aosta continuano ad avere problemi. grazie.
a presto

Il giorno dom 6 mar 2022 alle ore 11:36 Pierluigi Cara - DPC <
***@***.***> ha scritto:

**Comment by pierluigicara** [comment]
Purtroppo ancora nulla. Stante l'attuale filiera operativa che sta dietro alla pubblicazione dei dati in questo repository, penso sia più utile (e mi auguro risolutivo) contattare nuovamente il Ministero della Salute, nello specifico il riferimento è l'Ufficio 5 - Prevenzione delle malattie trasmissibili e profilassi internazionale della Direzione generale della prevenzione sanitaria, dove appunto presta servizio la dott.ssa Mammone.

**Comment by pierluigicara** [comment]
In relazione alla sua segnalazione, ieri (10 marzo 2022) il Ministero ci ha ritrasmesso i dati del 2 marzo 2022, che abbiamo pertanto aggiornato.

**Comment by giovannisebastiani** [comment]
grazie del lavoro e dell'info. comunque, i dati dei positivi ai test
molecolari del Veneto, limitandosi solo agli ultimi 14 giorni, contengono
errori anche nei giorni 27, 28 ottobre e 7 marzo. ho comunicato questo alla
dottoressa Mammone, e aspetto inoltre da lei info sugli errori dei dati
della Valle D'Aosta.



Il giorno ven 11 mar 2022 alle ore 08:57 Pierluigi Cara - DPC <
***@***.***> ha scritto:

**Comment by giovannisebastiani** [comment]
Grazie mille comunque.

Il gio 10 mar 2022 15:10 Pierluigi Cara - DPC ***@***.***> ha
scritto:

**Comment by giovannisebastiani** [comment]
Buonasera,

Sul sito i dati oggi sono stati aggiornati solo fino al 19 novembre e non
al 24 novembre.
Per favore, potreste risolvere questo problema?
Grazie.

A presto e buona serata,
Giovanni Sebastiani


Il ven 11 mar 2022 08:57 Pierluigi Cara - DPC ***@***.***> ha
scritto:
