### ISSUE TITLE
GitHub Pages non funzionante

### ISSUE THREAD

**Issue by AronkyDev** [pcm-dpc/COVID-19#1216]
Tipo di issue:

- [X] Dati mancanti o errati 
- [ ] Errore nella documentazione 
- [ ] Errore o mancanza nella dashboard 
- [ ] Problemi di visualizzazione nella dashboard 

- Regione: ///
- Provincia: ///

## Riassunto

Nella repo GitHub notiamo la presenza delle funzione "GitHub Pages" attiva, tuttavia nel momento del click su quest'ultima troviamo semplicemente una pagina con codice d'errore 404. Consiglio la creazione di un Index nella repo principale che contiene semplicemente un redirect al sito della Dashboard, eventualmente con la funzione di verifica se l'utente è da Smartphone o da PC, e reindirizzarlo di conseguenza. 
Possibilmente farò una pull request dove caricherò i file originali + l'index, con la funzione già scritta.

**Attesa:**

Pagina con un qualche tipo di contenuto, o eventualmente, un redirect.

**Attuale:**

Pagina vuota con errore 404.

**Comment by pierluigicara** [comment]
Grazie per la segnalzione, a seguito della quale abbiamo corretto il redirect errato.
Per quanto riguarda la funzione "GitHub Pages", essa non è stata attivata per il repository Covid-19.
