### ISSUE TITLE
ANOMALIA REGIONE ABRUZZO. su dati FR/PA e IFDDA. ?

### ISSUE THREAD

**Issue by CT-igiul** [pcm-dpc/COVID-19#1218]
**Tipo di richiesta**:  **richiesta di informazione** 

Buongiorno,
ho rilevato un'**anomalia della Regione ABRUZZO** che non riesco a capire (giustificare) e non identificabile nella NOTA della Scheda Riassuntiva del 18/03/2022.
Allego tre screenshot con l'anomala di ieri 18/03 confrontata con un dato coerente del 17/03 
![Schermata 2022-03-19 alle 13 47 01](https://user-images.githubusercontent.com/71124532/159122896-68939d3b-9b55-44e4-91c1-619e3fecde77.png)

![Schermata 2022-03-19 alle 13 47 22](https://user-images.githubusercontent.com/71124532/159122946-c3c57421-dba5-4eb7-b8d5-176ff60a0f50.png)

![Schermata 2022-03-19 alle 13 48 12](https://user-images.githubusercontent.com/71124532/159122983-4a07c05f-09f7-45ae-aa42-952bc374dda4.png)

e due screenshot del mio Data Base con alcune valutazioni:
L'anomalia è relativa ai dati identificati come "**FUORI REGIONE / PROVINCIA AUTONOMA** " (Z_F)  e "**IN FASE DI DEFINIZIONE-AGGIORNAMENTO**" (Z_I). 

L'anomalia è identificati dall'Incidenza per 100.000 che assume valori estremamente grande si >0 che <<0 che non permettono di visualizzare gli istogrammi  provinciali 

Allego due grafici che evidenziano l'anomalia del 18/03/2022.

![Anomalie REGIONE ABRUZZO 18 03 2022](https://user-images.githubusercontent.com/71124532/159123019-433f01ef-a0e2-4230-8028-bad8527a319d.png)

- La differenza giornaliera delle due anomalie pesa rispettivamente **2.467** e **-3.298**, il saldo è **-831**;
- La differenza delle somme giornaliere delle 4 provincie pesa **+654**, 
- Il saldo dei due pesi vale -1.485 e nelle NOTE non viene indicato nulla. 
- Un aggiustamento (ridistribuzione) è stato fatto per i dati di  "**FUORI REGIONE / PROVINCIA AUTONOMA** " (Z_F)  e "**IN FASE DI DEFINIZIONE-AGGIORNAMENTO**" (Z_I),  ma non capisco come devo interpretarlo.

Qualcuno può chiarire? Grazie
Luigi

## Interesse pubblico : SI

Di seguito la sintesi delle NOTE degli ultimi giorni

![Note Schede Riepilogative dal 15 al 18 marzo 2022](https://user-images.githubusercontent.com/71124532/159123061-5e3c41c8-5356-489d-85f7-b48aefe11dfb.png)

**Comment by CT-igiul** [comment]
Aggiungo ancora **due grafici REGIONALI** in cui ho corretto manualmente le anomalie della Regione ABRUZZO ma che hanno evidenziato anche un'altra anomalia  per la Regione **VALLE D'AOSTA**, non segnalata fra le NOTE di ieri.
Le considerazioni e la richiesta sono simili.

![Schermata 2022-03-19 alle 15 24 47](https://user-images.githubusercontent.com/71124532/159126069-a060084d-adbb-4cd6-ba21-40e9a585b4d5.png)

![Schermata 2022-03-19 alle 15 25 26](https://user-images.githubusercontent.com/71124532/159126101-2fe29a18-bc63-4882-b2aa-e6eb07ae4ada.png)

![Schermata 2022-03-19 alle 15 48 00](https://user-images.githubusercontent.com/71124532/159126121-87c5ff48-5709-45ec-8bc2-1e44745cd0e6.png)

Le anomalie si creano perché si valutano NUOVI CASI POSITIVI con valori minore di zero (<0).

Saluti
Luigi

**Comment by pierluigicara** [comment]
Grazie per la segnalzione e la documentazione di corredo. Abbiamo interessato al riguiardo il Ministero della Salute che è l'Ente autorizzato ad esprimersi in merito e attendiamo un suo riscontro.

**Comment by CT-igiul** [comment]
Buongiorno  @pierluigicara 
grazie per avermi risposto, ma credo che l'issue in oggetto debba rimanere ancora aperta in attesa dei commenti del Ministero della Salute.
Il problema è più ampio e **coinvolge anche le provincie** e non solo i dati di "FUORI REGIONE / PROVINCIA AUTONOMA " (Z_F) e "IN FASE DI DEFINIZIONE-AGGIORNAMENTO" (Z_I).


![Schermata 2022-03-21 alle 11 52 33](https://user-images.githubusercontent.com/71124532/159251307-5ecf8b73-3d54-40cd-a7ac-fde0682fafb8.png)


Con riferimento alla figura precedente la domanda è questa:
Dove sono finiti i **-1.485** NUOVI CASI (positivi) LORDI DEL CUMULATIVO PROVINCIALE?

Allego tre VIDEO che ne spiegano le cause ma non le motivazioni:

VIDEO1 GitHub Incidenze Regionali negative DataBase Excel.   https://youtu.be/osGEbUeWXPE

VIDEO2 GitHub Animazione Incidende Regionali negative.  https://youtu.be/19tz8q4AbQ4

VIDEO3 GitHub Animazione Nuovi Casi Provinciali.   https://youtu.be/IgyC15g3kyE

Rimango in attesa de commenti del MdS e disponibile ai miei. Grazie
Saluti
Luigi
