### ISSUE TITLE
Errato numero di casi positivi in Liguria 11 Marzo 2020 

### ISSUE THREAD

**Issue by alexrah** [pcm-dpc/COVID-19#122]
Tipo di issue:

- [x] Dati mancanti o errati 
- [ ] Errore nella documentazione 
- [ ] Errore or mancanza nella dashboard 
- [ ] Problemi di visualizzazione nella dashboard 

## Riassunto
https://github.com/pcm-dpc/COVID-19/blob/master/dati-json/dpc-covid19-ita-regioni.json
giorno 11 Marzo 2020
per quanto concerne il dato sui contagiati in Liguria , c'e' differenza tra i dati presenti in questo repo e quelli forniti dalla regione Liguria

**Attesa:**
185 casi positivi in Liguria il 11 Marzo 2020

**Attuale:**
194 casi positivi in Liguria il 11 Marzo 2020

**UPDATE**
sembra che i dati forniti dalla Regione Liguria in conferenza stampa sono diversi da quelli forniti alla Presidenza del Consiglio...

**Comment by umbros** [comment]
Buongiorno @alexrah il processo di conferimento del dato dalle Regioni al Ministero della Salute e quindi a noi è un processo formale, eventuali dati forniti in conferenza stampa dalle Regioni, successivamente alla conferenza stampa del Capo Dipartimento della Protezione Civile non sono aggiornati qui perchè non seguono il processo di comunicazione ufficiale.

**Comment by alexrah** [comment]
Buongiorno, nella casistica riportata dal tuo esempio non avrei sollevato alcune problema; in questo caso invece, i dati forniti dalla Regione Liguria in conferenza stampa sono stati dati PRIMA della conferenza delle 18:00 del Capo Dipartimento della Protezione Civile. Quello che mi sembra di capire quindi è che non si tratti di un errore lato vostro, ma piuttosto della Regione Liguria; nello specifico i dati relativi ai contagiati forniti in conferenza stampa erano meno di quelli che hanno fornito a voi; inoltre la Regione considera un caso di decesso in più rispetto al dato ufficiale. Queste discrepanze creano confusione e rendono difficile il lavoro degli organi di stampa.
