### ISSUE TITLE
raddoppio data 25 marzo in json

### ISSUE THREAD

**Issue by CapMar00** [pcm-dpc/COVID-19#1220]
Buonasera,
su questo file avete pubblicato 2 volte i dati relativi al 25 marzo:
https://raw.githubusercontent.com/pcm-dpc/COVID-19/master/dati-json/dpc-covid19-ita-andamento-nazionale.json

Grazie

Tipo di issue:

- [ ] Dati mancanti o errati 
- [ ] Errore nella documentazione 
- [ ] Errore o mancanza nella dashboard 
- [ ] Problemi di visualizzazione nella dashboard 

- Regione:
- Provincia: 

## Riassunto

**Attesa:**

**Attuale:**

**Comment by pierluigicara** [comment]
Grazie! Corretti.
