### ISSUE TITLE
Regione Valle d'Aosta dato cumulativo  totale_positivi_test_molecolare in discesa dal 15/01/2022

### ISSUE THREAD

**Issue by magaspari** [pcm-dpc/COVID-19#1222]
Tipo di issue:

- [X] Dati mancanti o errati 
- [ ] Errore nella documentazione 
- [ ] Errore o mancanza nella dashboard 
- [ ] Problemi di visualizzazione nella dashboard 

- Regione: Valle d'Aosta
- Provincia: 

## Riassunto

Tra i dati delle regioni per la Valle d'Aosta, a partire dal  15/01.2022,  il dato cumulativo  totale_positivi_test_molecolare che precedentemente e' sempre stato in crescita, oscilla ed inizia a scendere (unico caso in Italia).
Si tratta di un errata interpretazione? 
Qualcuno riesce a spiegare il perché?

Mauro

**Comment by pierluigicara** [comment]
Abbiamo già ricevuto segnalazioni simili e le abbiamo prersentate al Ministero della Salute. Al momento non ci sono ritornate indicazioni al riguardo. Le riporto - a titolo informativo - una [comunicazione ](https://www.quotidianosanita.it/valle_d_aosta/articolo.php?articolo_id=91965) fornita in merito lo scorso gennaio da Mauro Ruffier, Dirigente della Regione Autonoma Valle d'Aosta, Assessorato Sanità, Salute e Politiche Sociali della Struttura Igiene e Sanità Pubblica e Veterinaria.
