### ISSUE TITLE
Casi testati Veneto e nazionale

### ISSUE THREAD

**Issue by RossoDeM** [pcm-dpc/COVID-19#1223]
Tipo di issue:

- [X] Dati mancanti o errati 
- [ ] Errore nella documentazione 
- [ ] Errore o mancanza nella dashboard 
- [ ] Problemi di visualizzazione nella dashboard 

- Regione: Veneto
- Provincia: 

## Riassunto

Controllare casi testati del Veneto: ieri 4,658,486 vs oggi 46,631,120 (un 1 in più?)
Nella tabella andamento nazionale è riportato 96,179,535 (ieri erano 54,083,192)

Correggete entrambe le tabelle

**Attesa:**

**Attuale:**

**Comment by pierluigicara** [comment]
Grazie della segnalazione, passiamo la segnalazione al Ministero affinchè trasmetta le indicazioni da adottare.
