### ISSUE TITLE
Differenza Decessi dati protezione civile e dati ISS

### ISSUE THREAD

**Issue by PierpaoloFerrante** [pcm-dpc/COVID-19#1224]
**Tipo di richiesta**:  richiesta di informazione

## Riassunto

Salve,

mi servirebbe capire il numero totale di decessi con COVID-19 dall'inizio della pandemia. 

I decessi totali al 29/03/2022 riportati dalla protezione civile sono 159.054 (https://github.com/pcm-dpc/COVID-19/tree/master/dati-regioni). 

I decessi totali al 29/03/2022 riportati dall'ISS sono 156.585 (https://github.com/floatingpurr/covid-19_sorveglianza_integrata_italia/blob/main/data/2022-03-29/data.xlsx,   foglio: decessi). 

Perché sono diversi?

quale si avvicina maggiormente a quello reale?

Grazie x l'attenzione

Sky a febbraio riportava i decessi ISS (https://tg24.sky.it/cronaca/2022/02/28/bollettino-coronavirus-italia-28-febbraio) 
a marzo riporta quelli della protezione civile (https://tg24.sky.it/cronaca/2022/03/29/bollettino-coronavirus-italia-29-marzo).

Grazie x l'attenzione
## Interesse pubblico

Conoscere il numero reale di decessi con COVID-19

**Comment by pierluigicara** [comment]
Le consiglio una lettura attenta di quanto riportato nel [sito ](https://www.epicentro.iss.it/coronavirus/sars-cov-2-sorveglianza-dati) ISS, con particolare riferimento alla differenza tra i flussi dati. Per quanto riguarda il caso specifico sui decessi c'è una "letteratura" molto ampia a disposizione da poter consultare, che qui non è possibile riassumere. Le consiglio - tra i tanti - gli studi congiunti di ISTAT e ISS (le riporto il report più recente: https://www.istat.it/it/archivio/266865).

**Comment by PierpaoloFerrante** [comment]
Salve Pierluigi,
ho letto i link ma non rispondono alla mia domanda, cercherò di essere più preciso.

Sono un ricercatore INAIL (https://www.scopus.com/authid/detail.uri?authorId=23011466900). Sto stimando l'incidenza del COVID-19 in Italia tramite la mortalità visto che l'alto numero di asintomatici rende i casi trovati una stima poco efficace dei casi reali.

Per le stime del primo anno (https://jphres.org/index.php/jphres/article/view/2201) ho usato i dati della protezione civile, scaricati in questa piattaforma e non avevo notato differenze con i dati ISS (ricordo di aver controllato, ma potrei ricordare male).

Ora sto scrivendo un articolo sul secondo anno ma ho notato circa 2.500 decessi di differenza tra le due fonti.

Se ho capito bene, i dati ISS dovrebbero essere aggiornati continuamente (considerando anche i ricalcoli regionali) per cui pensavo di usare quelli. Visto però che questo nuovo articolo in lavorazione si basa sull'articolo già pubblicato (https://jphres.org/index.php/jphres/article/view/2201) dovrei spiegare il cambio di scelta dati alla base delle mie stime. 

Per cui ti chiederei: è corretto scrivere in un articolo scientifico che questa volta uso i dati ISS sui decessi perché considerano i riconteggi regionali?


In modo molto semplificato i casi totali possono essere stimati così:
se p è la probabilità di morire per i contagiati COVID
                                                                        contagi=decessi/p

se assumiamo p=0.01 (in realtà dipende dall''età, vedere pag 11 di https://www.imperial.ac.uk/media/imperial-college/medicine/mrc-gida/2020-10-29-COVID19-Report-34.pdf)

al 29 marzo ottengo

con dati PC: 159054/0,01=15.905.400

con dati ISS: 156.585/0,01=15.658.500


Grazie x l'attenzione

**Comment by pierluigicara** [comment]
Premetto che il mio parere ha un valore puramente  indicativo rispetto alla serietà della questione da lei posta ed al valore scientifico del suo studio. Un parere sicuramente più appropriato andrebbe chiesto all'ISS o a ISTAT. Comunque, proprio tenendo presente gli studi effettuati dagli Istituti appena citati credo che il flusso di dati consolidato dell'ISS sia quello da prendere in considerazione per le sue valutazioni, scientifiche appunto.

**Comment by PierpaoloFerrante** [comment]
Ok, grazie.
