### ISSUE TITLE
Oltre 1mln di tamponi rapidi il 4/4

### ISSUE THREAD

**Issue by c3k** [pcm-dpc/COVID-19#1225]
Nei dati di ieri, 4/4/22, risulta un incremento di 1,3 milioni di test antigenici rispetto al giorno precedente, la media dell'ultimo mese è di circa 400.000/giorno.
Il dato è corretto?

**Comment by Rabelaiss** [comment]
https://github.com/pcm-dpc/COVID-19/blob/master/note/dpc-covid19-ita-note.csv
La Provincia Autonoma di Bolzano comunica che al dato cumulativo dei tamponi processati con test antigenico nasofaringeo sono stati aggiunti 1.171.770 tamponi sulla base del ricalcolo effettuato il 30 marzo 2022. Dell'incremento numerico rispetto a ieri, difatti, solo 1834 tamponi sono stati effettuati ieri. Di conseguenza è cambiato anche il numero delle persone testate.

**Comment by c3k** [comment]
Grazie e scusatemi, ricordavo le note all'interno dello stesso file dei dati
