### ISSUE TITLE
Anomalia TAMPONI P.A Bolzano  e NUOVI CASI(+)LORDI Regione Sicilia

### ISSUE THREAD

**Issue by CT-igiul** [pcm-dpc/COVID-19#1226]
Tipo di issue:

- **[X]** Dati mancanti o errati 
- **[X]** Errore nella documentazione 
- [ ] Errore o mancanza nella dashboard 
- [ ] Problemi di visualizzazione nella dashboard 

- Regione: **P.A. BOLZANO e SICILIA**
- Provincia: n/a

## Riassunto

- Si segnala un'evidente  anomalia legata alla **P.A. Bolzano** che con il ricalcolo dei TAMPONI (1.171.770) ha creato una evidente anomalia sull'Indice Mediatico (mio Rapporto di Proporzionalità : **RdP = 2,26%**) dopo valori @15,00% da metà marzo, tanto da non essere comunicato in TV e da creare indici discordanti su alcune importanti testate giornalistiche.

**Tabella estratta dal mio spreadsheet excel:**
![Schermata 2022-04-05 alle 09 37 54](https://user-images.githubusercontent.com/71124532/161710554-9a536ab1-a763-4227-bfcc-5718030f794e.png)

**Grafico Indice Mediatico da me commentato:**
![Schermata 2022-04-05 alle 08 52 58](https://user-images.githubusercontent.com/71124532/161710753-8dd82460-dc98-4573-9a2d-e6ca2622f80c.png)

- Si continua a notificare un'evidente anomalia sui dati del **NUOVI CASI (positivi) LORDI** individuati dalla **Regione Sicilia**.
Con riferimento alle mie note sulla Tabella, allego di seguito l'enorme mole die dei NUOVI CASI (positivi) LORDI segnalati quotidianamente dalla Regione Sicilia e mai tendenti verso un'allineamento definitivo:

**Estratto del mio spredsheet su verifica anomalie Regionali.**

![Schermata 2022-04-05 alle 09 49 21](https://user-images.githubusercontent.com/71124532/161712390-b1ab7eb3-ac54-413f-961f-c648e20d0c0d.png)

**LISTA SEGNALAZIONE DI DISALLINEMENTO NUOVI CASI(positivi) LORDI della Reg. Sicilia**

![NOTE CASI Regione SICILIA al 05 04 2022](https://user-images.githubusercontent.com/71124532/161711445-31b357fd-7ccd-4e95-b096-886806b12c94.png)**Attesa:**

Un chiarimento dal Ministero delle Salute ed una comunicazione mediatica più aderente alla realtà!
Oggi nessun Telegiornale ha parlato di Indice o Tasso di Positività ( Ripeto: non significativo per monitorare la pandemia) 
Vai sul mio sito per capire le motivazioni: https://www.luigitomaselli.com

**Attuale:** 

Si allega la documentazione - dei problemi segnalati estratta dal mio spredsheet excel.

Aggiungo i grafici dei miei Termometri Pandemici dai quali rilevo che la pandemia è in rallentamento. Vedi su mio sito per capire l''operatività dei miei Pandemometri. QUADRANTE Superiore (CRITICITÀ), QUADRANTE Inferiore (MIGLIORAMENTO).

![Schermata 2022-04-05 alle 00 20 48](https://user-images.githubusercontent.com/71124532/161716608-b389f144-cc8a-45b6-8c40-a1394fa22269.png)

![Schermata 2022-04-05 alle 00 17 24](https://user-images.githubusercontent.com/71124532/161716700-83379ff5-b7f0-4682-bf3b-83f934abdfd6.png)

![Schermata 2022-04-05 alle 00 15 56](https://user-images.githubusercontent.com/71124532/161716880-5c0bfb51-19db-409b-aefa-c9b92a56e187.png)

![Schermata 2022-04-05 alle 00 19 02](https://user-images.githubusercontent.com/71124532/161716960-2872ef65-3116-4685-a48d-5631b790c05d.png)

DA INIZIO PANDEMIA:
![Schermata 2022-04-05 alle 11 04 22](https://user-images.githubusercontent.com/71124532/161720198-ea2af1f8-9b7a-423b-b903-1598f4f460ae.png)

![Schermata 2022-04-05 alle 11 05 13](https://user-images.githubusercontent.com/71124532/161720282-57db48c9-fc9f-44de-b6dd-66ace42b7225.png)

ZOOM ai nostri giorni:
![Schermata 2022-04-05 alle 11 07 42](https://user-images.githubusercontent.com/71124532/161720400-2e6fad4c-ef44-4cfe-a0cf-f93da22c85d4.png)

Saluti
Luigi

**Comment by pierluigicara** [comment]
Grazie per la segnalazione, ma come descritto nel README e già ribadito in più occasioni è il Ministero della Salute l'ente responsabile per la fornitura e qualità dei dati e adotta le annotazioni in calce al proprio report quotidiano come strumento per documentare i casi particolari segnalati dalle regioni nel corso del monitoraggio. Riguardo ai casi posti all'attenzione, ove le indicazioni nelle suddette annotazioni non fossero ritenute sufficienti, dunque, ogni eventuale ulteriore precisazione deve essere indirizzata all'Ufficio 5 - Prevenzione delle malattie trasmissibili e profilassi internazionale della Direzione generale della prevenzuione sanitaria appunto del Ministero della Salute.
