### ISSUE TITLE
UPDATE di circa un'ora fa

### ISSUE THREAD

**Issue by CT-igiul** [pcm-dpc/COVID-19#1228]
**Tipo di richiesta**:  richiesta di informazione

## Riassunto

Buon pomeriggio,
Quando fate un UPDATE, mi riferisco a quello fatto circa un'ora fa, come faccio a capire quali sono i giorni coinvolti o l'UPDATE si riferisce solo a ieri 9 maggio? 
IAW: non riesco a capire se gli altri dati UPDATED oltre a ieri 9 giugno, fanno parte di questo UPDATE.
Forse non non ho trovato la sezione che identifica l'UPDATE.
Grazie

## Interesse pubblico

Penso di si, a meno che il dubbio sia solo mio.

Grazie
Luigi
![Schermata 2022-06-10 alle 16 21 19](https://user-images.githubusercontent.com/71124532/173086798-68d6253d-95af-42ec-8371-2a40f5876605.png)

**Comment by Rabelaiss** [comment]
Vai nella [lista dei commit](https://github.com/pcm-dpc/COVID-19/commits/master) e clicca sul nome del commit (ossia 2022-06-09 UPDATED), da lì vedrai i file e i valori modificati

**Comment by CT-igiul** [comment]
Grazie, ho imparato un'altra cosa. 👍

**Comment by aborruso** [comment]
> Grazie, ho imparato un'altra cosa. 👍

ok, per favore chiudi la issue allora.

Grazie
