### ISSUE TITLE
Dati odierni duplicati 

### ISSUE THREAD

**Issue by CapMar00** [pcm-dpc/COVID-19#1231]
Tipo di issue:

-  I dati odierni (23 agosto 2022) risultano duplicati perlomeno in questi file
https://raw.githubusercontent.com/pcm-dpc/COVID-19/master/dati-andamento-nazionale/dpc-covid19-ita-andamento-nazionale.csv
https://raw.githubusercontent.com/pcm-dpc/COVID-19/master/dati-json/dpc-covid19-ita-andamento-nazionale.json
https://raw.githubusercontent.com/pcm-dpc/COVID-19/master/dati-regioni/dpc-covid19-ita-regioni.csv

grazie

**Comment by Giodecris** [comment]
Si sono stati corretti appena accorti dell'errore.
Grazie della segnalazione
