### ISSUE TITLE
Dati regioni non aggiornati

### ISSUE THREAD

**Issue by sapienzafra** [pcm-dpc/COVID-19#1239]
- [ ] Dati mancanti o errati
https://raw.githubusercontent.com/pcm-dpc/COVID-19/master/dati-regioni/dpc-covid19-ita-regioni.csv

Buonasera,
segnalo che nel suddetto file i dati sono fermi al 2 febbraio, manca quindi la settimana dal 3 al 9 febbraio.

**Comment by CapMar00** [comment]
Buonasera,
aggiungo che mi sembra ci sia qualche problema anche nella gestione di 
https://raw.githubusercontent.com/pcm-dpc/COVID-19/master/dati-andamento-nazionale/dpc-covid19-ita-andamento-nazionale.csv
sembra esserci un EOF tra la data 2023-02-02 dell'aggiornamento della scorsa settimana e 2023-02-03 della nuova settimana, potete controllare anche questo?
grazie

**Comment by Giodecris** [comment]
Grazie per le segnalazioni.
i file sono stati aggiornati
