### ISSUE TITLE
Numero ospedalizzati

### ISSUE THREAD

**Issue by marcosalta** [pcm-dpc/COVID-19#124]
Il dato degli ospedalizzati cumulato, è un dato complessivo o viene ridotto dai dimessi e dai decessi? 

**Tipo di richiesta**: richiesta di informazione 

## Interesse pubblico

 Il calcolo della mortalità sugli ospedalizzati è in costante crescita e può dipendere anche dalla modialità di calcolo.

**Comment by mydozer** [comment]
{
        "data": "2020-03-11 17:00:00",
        "stato": "ITA",
        "codice_regione": 5,
        "denominazione_regione": "Veneto",
        "lat": 45.43490485,
        "long": 12.33845213,
        "ricoverati_con_sintomi": 262,
        "terapia_intensiva": 68,
        "totale_ospedalizzati": 330,
        "isolamento_domiciliare": 610,
        "totale_attualmente_positivi": 940,
        "nuovi_attualmente_positivi": 157,
        "dimessi_guariti": 54,
        "deceduti": 29,
        "totale_casi": 1023,
        "tamponi": 21400
    }

Prova a vedere se questi due calcoli possono chiarire

        "ricoverati_con_sintomi": 262 + "terapia_intensiva": 68 =  "totale_ospedalizzati": 330
        "totale_ospedalizzati": 330 + "isolamento_domiciliare": 610 = "totale_attualmente_positivi": 940

totale_attualmente_positivi non può ne essere morto ne dimesso/guarito (negativo). Ho trovato qualche campione non del tutto logico, credo che in alcuni casi i dati siano un po' ballerini come progressione tra un giorno ed il successivo. In piemonte tra 08/03 e 09/30 ci cono stati 23 positivi in meno senza che vi siano stati in proporzione guariti o deceduti.

**Comment by marcosalta** [comment]
Ti ringrazio, ma non mi aiuta. Mi domando se il "totale_ospedalizzati" corrisponda il numero degli ospedalizzati attuale effettivo (ovvero ospedalizzati(n-1) + nuovi ingressi(n) - decessi(n) - dimessi(n)) oppure sia semplicemente il totale di nuovi ingressi che si aggiunge al dato precedente.

**Comment by umbros** [comment]
Ciao @marcosalta ,
il totale ospedalizzati corrisponde al totale degli attuali ricoverati con sintomi + terapia intensiva, quindi possono scendere in presenza di dimessi guariti o deceduti o salire se, ovviamente ci sono altri ingressi.
Stiamo predisponendo un README dove spieghiamo meglio il significato dei dati.
