### ISSUE TITLE
Incorrect value for denominazione_regione in file dpc-covid19-ita-regioni.csv

### ISSUE THREAD

**Issue by sc24289** [pcm-dpc/COVID-19#125]
Type of issue:

- [x] Incorrect or missing data : dpc-covid19-ita-regioni.csv
- [ ] Incorrect or missing documentation 
- [ ] Incorrect or missing data in the dashboard 
- [ ] Layout problem in the dashboard 

## Summary

Latest release of the file has a row with value `'Friuli V. G. '` instead of `'Friuli Venezia Giulia'` in file`dpc-covid19-ita-regioni.csv`

**Expected:**
I was expecting `'Friuli Venezia Giulia'` in all rows that refer to that region. 

**Actual:** 
IRow with `date`  equal to 2020-03-11 17:00:00  has value 'Friuli V. G. '  in column `denominazione_regione` . That causes problem when trying to process data for automatic creation of graphs like the one here below.

---

![image](https://user-images.githubusercontent.com/33753981/76468861-4688f080-63ed-11ea-9b4d-d1e52e4fe82d.png)

**Comment by mydozer** [comment]
It seems to be the same issue reported by #92, and #123 you found on csv file.

**Comment by umbros** [comment]
Thank you. corrected
