### ISSUE TITLE
Nuovi casi attualmente positivi

### ISSUE THREAD

**Issue by ploteo** [pcm-dpc/COVID-19#126]
# Richiesta di informazione

## Riassunto

Cosa misura la voce "nuovi casi attualmente positivi"? Il dubbio deriva dal fatto che nella serie storica sono presenti dei valori negativi (ad esempio Lombardia 10/03). In questa voce mi aspettavo di trovare tutti i nuovi casi registrati in una giornata.

## Interesse pubblico

Miglior lettura dell'informazione

**Comment by CorradoLanera** [comment]
duplicato con #93 , #97
