### ISSUE TITLE
Congruenza dati 10/3 e 11/3

### ISSUE THREAD

**Issue by anbened** [pcm-dpc/COVID-19#127]
Intanto grazie per il preziosissimo lavoro
Mi sembra di capire che i dati Lombardia del 10/3 che non sono stati inviati in tempo sono stati inseriti nei dati del giorno 11/3

E' possibile fare in modo che i dati appartengano alla giornata di competenza e non a quella di messa in disponibilità?

Mi spiego: se i dati del 11/3 contengono quelli di questo giorno + quelli che non sono stati inviati il giorno prima, andiamo a modificare i dati reali utili a capire e a tracciare i fenomeni

Disponibile a supportare se serve

Grazie

**Comment by pierluigicara** [comment]
Anzitutto grazie per l'apprezzamento.
Riguardo alla questione posta, è chiara e condivisibile, tuttavia al momento non è possibile. 
Stiamo valutando come predisporre delle modalità informative per tracciare queste oscillazioni nei flussi informativi che, tuttavia, sono sotto la responsabilità della complessa filiera che fa riferimento al Ministero della Salute che è il Creator della risorsa. Il DPC, in qualità di Titolare della risorsa, si fa carico della pubblicazione, distribuzione e comunicazione al pubblico.

**Comment by anbened** [comment]
Molte grazie, Pierluigi
