### ISSUE TITLE
Proposta: file province attualmente positivi

### ISSUE THREAD

**Issue by pierpa010** [pcm-dpc/COVID-19#129]
**Tipo di richiesta**: suggerimento di miglioramento (documentazione, label, _ecc_) | 

sostituire totale casi con totale attualmente positivi oppure aggiungere quest'ultima informazione se possibile

il dato di attualmente positivi potrebbe risultare più rilevante del totale che comprende anche i casi risolti

Grazie!!!

**Comment by pierluigicara** [comment]
L'informazione "Totale attualmente positivi" è già presente, sia a livello di ciascuna regione, sia come andamento temporale degli incrementi giornalieri.
A livello di Province l'unico dato per il quale è previsto il rilevamento e la trasmissione a cura della struttura del Ministero della Salute che cura il monitoraggio dei casi è "totale casi".
