### ISSUE TITLE
e' possibile avere i dati disaggregati per fascia di eta?

### ISSUE THREAD

**Issue by MauroCapolino** [pcm-dpc/COVID-19#130]
**Type of issue**:  richiesta di informazione | richiesta di dati | suggerimento di enhancement (documentazione, label, _etc_)

**Comment by pacovi** [comment]
Seems duplicated, see https://github.com/pcm-dpc/COVID-19/issues/102

**Comment by mydozer** [comment]
Questione già affrontata qui #41

**Comment by umbros** [comment]
Grazie @pacovi e @mydozer per il supporto.
@MauroCapolino attualmente non gestiamo quell'informazione ma il dataset potrebbe avere ampliamenti in quanto a informazioni fornite. Annunceremo tutto per tempo e in CHANGELOG.

**Comment by mydozer** [comment]
@umbros grazie a voi!!

**Comment by MauroCapolino** [comment]
Salve sono un ingegnere elettronico di Roma e sto analizzando da giorni i dati per un gruppo di amici e credo che la versione desktop dovrebbe dare più info sia nazionale a regionale 

Se volete posso dare una mano nella creazione di infographic per il pubblico cosi da non avere tante persone che si devono scaricare il cdv e poi fare i modelli

Fino adesso ho usato un semplice excel con pivot e grafici automatici (in allegato aggiornato a oggi ) in allegato e qui sotto alcune idee (ovviamente le regioni vanno cambiate)

Se vi server una mano ditemelo


1) visualizzazione dei 3 dati principali (tamponi, casi e morti) e relative % di morti su totale casi e test tamponi e % incremento positivi 


2) perceptuale per regioni dei porti sul totale infettati 


3) incremento test giornalieri per regioni per vedere chi ne fa di più o di meno



4) incremento casi positivi per regione giornaliero



On 12 Mar 2020, at 18:51, Umberto Rosini <notifications@github.com> wrote:


Grazie @pacovi <https://github.com/pacovi> e @mydozer <https://github.com/mydozer> per il supporto.
@MauroCapolino <https://github.com/MauroCapolino> attualmente non gestiamo quell'informazione ma il dataset potrebbe avere ampliamenti in quanto a informazioni fornite. Annunceremo tutto per tempo e in CHANGELOG.
