### ISSUE TITLE
coordinate dato Calabria inconsistenti nel periodo

### ISSUE THREAD

**Issue by massimomartucci** [pcm-dpc/COVID-19#132]
Tipo di issue:

- [ x] Dati mancanti o errati 
- [ ] Errore nella documentazione 
- [ ] Errore or mancanza nella dashboard 
- [ ] Problemi di visualizzazione nella dashboard 

## Riassunto

le coordinate lat/long del dato relativo alla Calabria vanno uniformate: fino al 6/3 fanno riferimento a Catanzaro, dal 7/3 in poi fanno riferimento a Reggio Calabria. Andrebbero tutte uniformate a una sola città, preferibilmente Catanzaro che è il capoluogo (e che rende meglio nelle mappe) 
**Attesa:**

campi lat lon per la Calabria consistenti con il valore di Catanzaro (38.90597598	16.59440194)

**Attuale:** 
parte dei dati della Calabria con coordinate Catanzaro e parte con coordinate Reggio Calabria

**Comment by umbros** [comment]
Thank you @massimomartucci
