### ISSUE TITLE
Richiesta dati professionisti sanitari

### ISSUE THREAD

**Issue by izeosit** [pcm-dpc/COVID-19#133]
Salve è possibile ricevere i dati relativi ai professionisti sanitari?

## Riassunto
Sarebbe utile avere i dati relativi ai **professionisti sanitari** dall'inizio del monitoraggio, divisi per **regione, provincia e professione** e relativi a:
- Positivi totali
- Guariti
- Deceduti
- Positivi attuali

## Interesse pubblico

È indubbio che i professionisti sanitari stiano facendo lo sforzo più grande in questa battaglia contro COVID-19. Analizzare i dati potrebbe essere utile a:
mi

- migliorare l'attività dei professionisti (in particola laddove non vi sono ancora picchi di ricoveri)
- analizzare l'eventuale motivazioni dei casi
- rendere omaggio ai professionisti

**Comment by umbros** [comment]
Ciao @izeosit, indubbiamente utile ma in questo momento non è un dato che si gestirà, ad ogni modo ogni modifica e aggiunta di nuovi dati e informazioni sarà pubblicata in CHANGELOG.
