### ISSUE TITLE
Curva totali con evidente offset dopo pubblicazione dati 12/03

### ISSUE THREAD

**Issue by mattinew** [pcm-dpc/COVID-19#135]
Richiesta informazioni

## Riassunto
Osservando i dati pubblicati in data 12/03 si vede che il grafico dei _totale_attualmente_positivi_ ha ripreso un andamento crescente esponenziale con un netto offset causato dalla mancanza dei dati del 10/03 (rispecchiati dai dati in _dpc-covid19-ita-andamento-nazionale.csv_). 

La cosa mi sembra anomala, infatti se i dati mancanti del 10/03 fossero stati recuperati in data 11/03 (come è stato detto che sarebbe stato fatto durante la conferenza stampa del 10/03):
- se fossimo ancora in trend esponenziale crescente, mi aspetterei che i dati del 11/03 e del 12/03 fossero allineati alla curva di fitting e quindi considereremmo il dato del 10/03 un outlier.
- se invece il trend fosse decrescente, e stessimo quindi incontrando un flesso, questo spiegherebbe la posizione del dato del 11/03 ma non quella del dato del 12/03 che dovrebbe essere inferiore. Anche se questo scenario mi sembra che implichi un'evoluzione decrescente troppo rapida rispetto alle costanti di tempo viste finora.

Sono effettivamente stati recuperati i dati mancanti del 10/03 nel conteggio del 11/03. 
Visto così sembrerebbe di no.

Mi sbaglio? Qualcuno può chiarire per favore?

Grazie mille a tutti.
ciao

**Comment by Crusan** [comment]
> Sono effettivamente stati recuperati i dati mancanti del 10/03 nel conteggio del 11/03.
> Visto così sembrerebbe di no.

I dati non sono stati recuperati, ma in base alle dichiarazioni della conferenza stampa del 11/03, circa 600 dei nuovi casi riportati il 11/03 corrispondono a tamponi relativi all'10/03. 

Di conseguenza, i dati di nuovi_attualmente_positivi del 10/03 sarebbero circa 1129, mentre quelli del 11/03 sarebbero circa 1476. Il relativo rallentamento di quei giorni potrebbe essere dovuto a svariati fattori, tra cui (non sono in grado di confermare, sono solo supposizioni):

1) rallentamento dei contagi nelle prime zone rosse grazie all'effetto delle misure di contenimento attuate in tali focolai
2) rallentamento dei contagi generale grazie alle precauzioni prese dalla popolazione in seguito ai primi annunci di emergenza 

Questo può essere verificato attraverso l'analisi dei dati provinciali per vedere quali province, se del caso, hanno causato il flesso dei casi.

Spero sia d'aiuto

**Comment by mattinew** [comment]
Forse mi sono espresso male, quando dicevo _recuperati_, intendevo _compensati_ aggiungendoli ai dati del 11/03. I dati del 10/03 ormai sono quelli, e resteranno così.

Credo che la tua analisi sia corretta, relativamente agli incrementi giornalieri.
Guardando però la curva dei totali, si vede che c'è un salto (o offset) nei giorni 10 e 11 marzo, non compatibile con il recupero di quei 600 nuovi casi.

Mi sembra strano che ci sia stato un rallentamento in quelle date, smentito però poi dai dati del 12/03. Mi aspetterei un cambiamento graduale, considerando il numero di persone su cui è naturalmente mediato.

Grazie
ciao

**Comment by DataEnthusiast84** [comment]
@mattinew ciao,

effettivamente è la stessa cosa che ho notato anche io...e non mi spiego come è possibile che, il giorno 11/3 (se davvero i dati del 10/3 fossero stati caricati in data 11/3) non si veda un incremento maggiore (un "picco") evidente ma i dati seguano l'andamento esponenziale...

Io l'unica spiegazione che mi sono dato è che, probabilmente, quell'incremento dovuto al "recupero" dei dati in data 11/3 ma di "competenza" 10/3 siano stati magari compensati da "crescite meno esponenziali" di qualche altra regione...

La butto lì: non sarebbe il caso di assegnare i dati che sono stati recuperati il giorno 11/3 (ma di competenza 10/3) direttamente al giorno 10/3? Non si creerebbe così quell'offset generato dalla mancanza dei dati...

**Comment by pierluigicara** [comment]
Consiglio al riguardo di ascoltare quanto riportato oggi ( sabato 14/3) dall'Assessore al Welfare della Regione Lombardia Giulio Gallera.
