### ISSUE TITLE
Fornire a livello di provincia gli stessi dati presenti a livello regionale e nazionale

### ISSUE THREAD

**Issue by perdusemini** [pcm-dpc/COVID-19#136]
**Tipo di richiesta**:  suggerimento di miglioramento (dati)

## Riassunto
Fornire a livello di provincia gli stessi dati presenti a livello regionale e nazionale. 

## Interesse pubblico
In questo modo sarebbe possibile visualizzare i trend dei vari indicatori anche a livello di provincia, e verificare autonomamente gli effetti delle misure di contenimento.

**Comment by pescetti** [comment]
Sarebbe molto interessante, ma temo che sia un duplicato di #57 che è già stata chiusa perché i dati su base provinciale sono (erano?) troppo complessi per poterli gestire accuratamente.

**Comment by giuswal** [comment]
Oltre ad approvare la richiesta di fornire a livello di provincia gli stessi dati presenti a livello regionale e nazionale., domando per quale motivo vengono sommati i dimessi_guariti ed i deceduti a Totale_attualmente_positivi?

**Comment by pescetti** [comment]
Non so se ho capito bene la domanda, ma la situazione è:

Casi totali = Attualmente positivi + Guariti + Deceduti

Per le regioni abbiamo tutti e tre gli indicatori sulla destra, e di conseguenza anche i Casi totali che sono appunto la somma dei tre.

Per le province abbiamo solo i "Casi totali" e la richiesta presente (che poi sostanzialmente era la stessa che avevo fatto io in #57) è quella di avere tutti e tre gli indicatori.

Per la precisione, per le province anche i "Casi totali" non sono accurati al 100%, e questo è il motivo, come più volte spiegato da @umbros, per cui esiste una provincia "finta" in ogni regione che serve a fare tornare i conti.

**Comment by perdusemini** [comment]
> Sarebbe molto interessante, ma temo che sia un duplicato di #57 che è già stata chiusa perché i dati su base provinciale sono (erano?) troppo complessi per poterli gestire accuratamente.

Grazie @pescetti , avevo controllato la lista delle issue precedenti ma evidentemente mi era sfuggita.
Si, immagino che sia ulteriormente oneroso fornire lo stesso dettaglio degli altri due livelli (nazionale e regionale) anche a livello provincia. Se fossero disponibili permetterebbero di vedere i diversi trend sui singoli territori, che sicuramente stanno avendo dinamiche diverse.

**Comment by umbros** [comment]
#57

**Comment by pensierinmusica** [comment]
https://github.com/pcm-dpc/COVID-19/issues/245
