### ISSUE TITLE
Presenza nuovi_attualmente_positivi con  valori negativi

### ISSUE THREAD

**Issue by Modello-MA** [pcm-dpc/COVID-19#137]
Rilevo che nel file 

https://github.com/pcm-dpc/COVID-19/blob/master/dati-regioni/dpc-covid19-ita-regioni.csv

compaiono valori negativi dei nuovi casi di infezione (nuovi_attualmente_positivi). Chiaramente questo non e' possibile. Salta particolarmente all'occhio per il caso della lombardia il 10 marzo che mostra una fluttuazione (ben oltre la fluttuazione statistica) nell'andamento al livello nazionale.
Ho trovati 8 entry:

data | stato | codice_regione | denominazione_regione | nuovi_attualmente_positivi
-- | -- | -- | -- | --
2020-02-27 18:00:00 | ITA | 1 | Piemonte | -1
2020-03-09 18:00:00 | ITA | 1 | Piemonte | -18
2020-03-10 18:00:00 | ITA | 3 | Lombardia | -63
2020-03-01 17:00:00 | ITA | 7 | Liguria | -17
2020-03-02 18:00:00 | ITA | 7 | Liguria | -3
2020-02-26 18:00:00 | ITA | 12 | Lazio | -2
2020-02-27 18:00:00 | ITA | 19 | Sicilia | -1
2020-03-02 18:00:00 | ITA | 19 | Sicilia | -2

**Comment by mydozer** [comment]
Ciao @Modello-MA ti chiederei la cortesia di chiudere la tua segnalaizone perché il tema è già stato affrontato più volte. Puoi dare un occhio qui #93 oppure cercare nuovi_attualmente_positivi tra le issue chiuse.

Se chiudi questo ticket risparmi del tempo prezioso dei ragazzi che cercano di produrre quotidianamente dati in tempo utlie con il massimo della dovizia possibile. Grazie!!
