### ISSUE TITLE
Google spreadsheet

### ISSUE THREAD

**Issue by 0x0ece** [pcm-dpc/COVID-19#138]
**Tipo di richiesta**: suggerimento di miglioramento

## Riassunto

Ho importato i dati in G spreadsheet, si dovrebbe aggiornare ogni ora e dovrebbe essere più semplice da consumare per molti. Se interessa posso sottomettere una PR (es. link nel readme).
https://docs.google.com/spreadsheets/d/1xAyDSpzEp3n4iiu54_XL6MQxNXtrOnHSZf8zx2HZgEU/edit#gid=833526927

## Interesse pubblico

Per molti dovrebbe essere più semplice leggere/consumare i dati direttamente in uno spreadsheet.

**Comment by umbros** [comment]
Ciao @0x0ece ma di fatto il CSV può essere importato in un programma tipo Office Excel, Libreoffice Calc etc etc...

**Comment by 0x0ece** [comment]
Il punto era esattamente evitare di 1) trovare il file giusto, 2) scaricarlo da github, 3) aprire un programma tipo... 4) importare. 1 click e hai lo spreadsheet pronto con tutti i dati, aggiornati automaticamente ogni ora. Cmq ok.

**Comment by cortesimone** [comment]
Mi sembra un ottimo sistema per avere un accesso veloce ai dati.
