### ISSUE TITLE
link licenza rotto

### ISSUE THREAD

**Issue by nelsonmau** [pcm-dpc/COVID-19#14]
Come da screenshot

![EShDZxaX0AEApT-](https://user-images.githubusercontent.com/1769578/76150358-f71f8900-60a9-11ea-8095-fc1807414965.jpg)

**Comment by umbros** [comment]
Il link alla licenza punta a https://github.com/pcm-dpc/COVID-19/blob/master/LICENSE mi risulta ok!

**Comment by nemobis** [comment]
l'HTML corretto da usare per le licenze Creative Commons è indicato alla pagina
https://wiki.creativecommons.org/wiki/Marking_your_work_with_a_CC_license
