### ISSUE TITLE
Riscalare grafico "Incremento giornaliero degli attualmente positivi"

### ISSUE THREAD

**Issue by alesarrett** [pcm-dpc/COVID-19#140]
Tipo di issue:

- [ ] Dati mancanti o errati 
- [ ] Errore nella documentazione 
- [ ] Errore o mancanza nella dashboard 
- [x] Problemi di visualizzazione nella dashboard 

## Riassunto

Nella tab dei grafici della dashboard, il grafico "Incremento giornaliero degli attualmente positivi" deve essere riscalato nelle ordinate. Attualmente il valore massimo delle ordinate è 2000 mentre i valori degli scorsi 2 giorni sono maggiori.
Conseguentemente il grafico viene tagliato e non rappresenta l'andamento attuale.
![ordinate](https://user-images.githubusercontent.com/1692316/76596275-05343600-64fe-11ea-93af-bfb8f63583c1.png)

**Comment by alesarrett** [comment]
Aggiunto screenshot

**Comment by umbros** [comment]
@alesarrett grazie per la segnalazione
![immagine](https://user-images.githubusercontent.com/4085151/76609409-a2e82f00-6517-11ea-8c7c-b164cea93666.png)
