### ISSUE TITLE
Creazione dataset con dati regionali sulle terapie intensive

### ISSUE THREAD

**Issue by gianlab** [pcm-dpc/COVID-19#141]
**Tipo di richiesta**: richiesta di dati 

## Riassunto

Ciao,
finora ho fatto i seguenti reports con i vostri dati:
https://www.kaggle.com/gianlab/previsioni-ed-esplorazione-dati-covid-19-italia
https://www.kaggle.com/gianlab/esplorazione-dei-dati-province-italiane-covid-19

Ora mi vorrei occupare della terapia intensiva per ogni regione italiana... In questo momento si può calcolare la percentuale delle terapie intensive rispetto ai casi confermati della regione , ma bisognerebbe sapere i posti disponibil in terapia intensiva complessivi e per il covid19 per ogni regione. Si potrebbe creare un dataset che abbia i seguenti campi :
nome della regione, posti totali in terapia intensiva, posti disponibili per il covid, link alla notizia giornalistica . 

## Interesse pubblico

Avendo questi dati si potrebbe calcolare la soglia regionale di casi confermati nella regione che non dovrebbe essere superata facendo una proporzione. In pratica se ci sono 50 posti in terapia intensiva disponibili in Puglia per il Covid19 e l'8% è la percentuale di casi confermati in terapia intensiva in Puglia la soglia regionale è 5000/8=625 cioè il numero di casi confermati che non deve essere superato .

Si potrebbe realizzare questo datasets a cui tutti potrebbero contribuire?
Si tratta in pratica di cercare le notizie giornalistiche e aggiornare il dataset.
Grazie

**Comment by mydozer** [comment]
Ciao @gianlab, ti riporto la risposta data a suo tempo per dati non in possesso della protezione civile "..non possiamo prendere in considerazione dati che non hanno la fonte e il processo di conferimento dati stabilito con il Ministero della Sanità.." vedi #55

Rendere disponibili i dataset aggregati giornalmente è già frutto di uno sforzo abnorme, visto che partono dai reparti che oltre tutto curano i malati e poi passano di mano fino ad arrivare in un comodo repository. Credo che sapere che non ci sono più posti di terapia intensiva in un una data zona porterebbe le persone a spostarsi spontaneamente altrove, cosa che nessuno vuole.

Se vuoi creare il dataset in un tuo repository lo proietto in mappa volentieri.

Se pensi ti abbia risposto per favore chiudi questo ticket. Grazie!!

**Comment by gianlab** [comment]
Se la soglia è molto alta questo potrebbe attenuare l'ansia delle persone. Il problema potrebbe sorgere se ci si avvicina alla soglia...Comunque penso di fare il dataset andando a cercare i dati nei giornali con  pazienza. Appena ne ho uno discreto te lo faccio sapere.Ciao
