### ISSUE TITLE
Andamenti per densita' abitanti

### ISSUE THREAD

**Issue by sergiobrisio** [pcm-dpc/COVID-19#142]
**Tipo di richiesta**: <suggerimento di miglioramento>

## Riassunto
Se per ogni regione/provincia si aggiungesse il campo degli abitanti, sarebbe più semplice fare grafici del tipo numero di casi per 1000 abitanti. Ad esempio ho notato che la curva di crescita dei casi della provincia di Piacenza ha già superato il flesso (sembrerebbe l'unica), ma magari con l'osservazione degli andamenti temporali che tengano conto della densità di abitanti si potrebbe riscontrare che questo accade in altre province.

## Interesse pubblico
Immagino che il dato relativo alle statistiche che tengono conto della densità di abitanti potrebbero avere significato nel capire dove le strategie di contenimento stanno funzionando.

**Comment by tetrapharmakon** [comment]
Per l'andamento nazionale è molto facile; ho abbozzato qualcosa e adesso faccio una PR
Per l'andamento province/regioni, qualcuno dovrebbe avere la pazienza di inserire un altro json con il numero di abitanti per provincia/regione. Con le regioni alla peggio si fa a mano con google e i dati dell'ultimo censimento. Le province sono troppe!

**Comment by mydozer** [comment]
Ciao @sergiobrisio , quello che ti serve lo trovi qui https://www.tuttitalia.it/italia/ o sul portale ISTAT. Fare la statistica per ogni capoluogo di provincia è poco realistica perché i casi sono distribuiti su più comuni. Noi abbiamo aggregato l'informazione per regione. Se vuoi le informaizoni da consultare sono già pronte qui http://www.itaru.it/

**Comment by tetrapharmakon** [comment]
Ah come non detto, ecco dove sono i dati per provincia/regione :) grazie!

**Comment by minni** [comment]
Se volete ho messo su la percentuale nella visualizzazione qui:
https://minni.github.io/COVID-19/
é un fork, ho solo fatto un po' di codice JS per visualizzare solo l'andamento
https://github.com/minni/COVID-19

**Comment by bertanimauro** [comment]
Ho provato a chiedere a wikipedia. Qui un esempio per la Lombardia. Che regione hai bisogno.
https://docs.google.com/spreadsheets/d/1XdpvXK1Aa9RXCBaOsYuOsU319aDu3ZHnP-uVZAqF6cw/edit?usp=sharing

**Comment by DataEnthusiast84** [comment]
Ho fatto analisi simili per nazione e regione.

Consiglio a tutti il sito dell'Istat...si possono fare interrogazioni in real-time e forniscono i dati su ogni caratteristica della popolazione...

**Comment by lucianolorenti** [comment]
In case someone is interested In the section "Evolution of cases per province" on my [dashboard](https://itacovid-19.herokuapp.com/#Evolution-of-cases-per-province) I have the cases per provinces and the plot of cases per 1000 people. I normalized the number of cases by each province population.

**Comment by bfabio** [comment]
> on my [dashboard](https://itacovid-19.herokuapp.com/#Evolution-of-cases-per-province)

Great job @lucianolorenti :+1:

**Comment by umbros** [comment]
Hello everyone, the data we provide is interoperable by reporting the region code and province code, so any analysis you want to do with other data (I recommend that we have an official nature like those of Istat) you can do it.
