### ISSUE TITLE
Rappresentazione per regione

### ISSUE THREAD

**Issue by bhutano** [pcm-dpc/COVID-19#144]
L'attuale rappresentazione grafica dei contagi potrebbe indurre in errore. Ad esempio da un primo sguardo della cartografia italiana, se consideriamo a titolo esemplificativo la regione Molise, nella provincia di Campobasso sembrerebbe che i contagi siano avvenuti tutti nei pressi della città di Campobasso guardando il marker rosso e quindi nell'entroterra, quando al contrario la maggior parte di essi è avvenuta sulla costa, ma il pallino rosso è completamente assente lì. 

La mappa mostra i contagi per provincia ovviamente.

Potrebbe essere più immediato e veritiero, anziché utilizzare i pallini rossi sul capoluogo di provincia, delimitare i confini provinciali e colorare lo sfondo dell'intero territorio provinciale secondo un gradiente di colorazione relativo al numero dei contagi.

Ciò potrebbe rendere maggiormente l'idea della reale situazione e suscitare maggiore senso di responsabilità nei confronti delle persone che credono di non esserne ancora coinvolte..
Grazie.

**Comment by umbros** [comment]
Grazie della segnalazione  @bhutano

**Comment by bhutano** [comment]
> Grazie della segnalazione @bhutano

Grazie a te!!
