### ISSUE TITLE
Define and adhere to an unified encoding for the CSV files

### ISSUE THREAD

**Issue by miccoli** [pcm-dpc/COVID-19#147]
Type of issue:

- [x] Incorrect or missing data : `dati-province/dpc-covid19-ita-province-????????.csv`
- [x] Incorrect or missing documentation: `README.md`
- [ ] Incorrect or missing data in the dashboard 
- [ ] Layout problem in the dashboard 

## Summary

The encoding of the `dati-province/dpc-covid19-ita-province-????????.csv` files is not defined, and frequently changes.

<details>
as per abe6f19

```
dati-province/dpc-covid19-ita-province-20200224.csv: UTF-8 Unicode text
dati-province/dpc-covid19-ita-province-20200225.csv: UTF-8 Unicode text
dati-province/dpc-covid19-ita-province-20200226.csv: UTF-8 Unicode text
dati-province/dpc-covid19-ita-province-20200227.csv: UTF-8 Unicode text
dati-province/dpc-covid19-ita-province-20200228.csv: UTF-8 Unicode text
dati-province/dpc-covid19-ita-province-20200229.csv: UTF-8 Unicode text
dati-province/dpc-covid19-ita-province-20200301.csv: UTF-8 Unicode text
dati-province/dpc-covid19-ita-province-20200302.csv: UTF-8 Unicode text
dati-province/dpc-covid19-ita-province-20200303.csv: UTF-8 Unicode text
dati-province/dpc-covid19-ita-province-20200304.csv: UTF-8 Unicode text
dati-province/dpc-covid19-ita-province-20200305.csv: UTF-8 Unicode text
dati-province/dpc-covid19-ita-province-20200306.csv: UTF-8 Unicode text
dati-province/dpc-covid19-ita-province-20200307.csv: UTF-8 Unicode text
dati-province/dpc-covid19-ita-province-20200308.csv: UTF-8 Unicode text
dati-province/dpc-covid19-ita-province-20200309.csv: UTF-8 Unicode text
dati-province/dpc-covid19-ita-province-20200310.csv: UTF-8 Unicode text
dati-province/dpc-covid19-ita-province-20200311.csv: ISO-8859 text
dati-province/dpc-covid19-ita-province-20200312.csv: ISO-8859 text
```

but at 7db375c

```
dati-province/dpc-covid19-ita-province-20200224.csv: ISO-8859 text
dati-province/dpc-covid19-ita-province-20200225.csv: ISO-8859 text
dati-province/dpc-covid19-ita-province-20200226.csv: ISO-8859 text
dati-province/dpc-covid19-ita-province-20200227.csv: ISO-8859 text
dati-province/dpc-covid19-ita-province-20200228.csv: ISO-8859 text
dati-province/dpc-covid19-ita-province-20200229.csv: ISO-8859 text
dati-province/dpc-covid19-ita-province-20200301.csv: ISO-8859 text
dati-province/dpc-covid19-ita-province-20200302.csv: ISO-8859 text
dati-province/dpc-covid19-ita-province-20200303.csv: ISO-8859 text
dati-province/dpc-covid19-ita-province-20200304.csv: ISO-8859 text
dati-province/dpc-covid19-ita-province-20200305.csv: ISO-8859 text
dati-province/dpc-covid19-ita-province-20200306.csv: ISO-8859 text
dati-province/dpc-covid19-ita-province-20200307.csv: ISO-8859 text
dati-province/dpc-covid19-ita-province-20200308.csv: ISO-8859 text
dati-province/dpc-covid19-ita-province-20200309.csv: ISO-8859 text
dati-province/dpc-covid19-ita-province-20200310.csv: ISO-8859 text
```

</details>

For automated parsing it is *important* to have uniform encoding. 

I have no strong opinion on which of the two encodings is better, "ISO-8859" or "UTF-8", but please 
- choose one, 
- add it to the README, and 
- be consistent.

See also #134, where the "UTF-8" encoding is proposed.

*Grazie per l'ottimo ed instancabile lavoro!*

**Comment by umbros** [comment]
Ciao @miccoli, mi risulta che vengano prodotti tutti in UTF-8, per non fermare l'attività farò passare un batch di controllo e nel caso procedo alla conversione di quelli rimasti non UTF-8. Grazie per la segnalazione.

**Comment by bfabio** [comment]
@umbros C'è la patch in https://github.com/pcm-dpc/COVID-19/pull/134

**Comment by miccoli** [comment]
Dopo la 10844e597
```
$ file dati-province/dpc-covid19-ita-province-20200313.csv
dati-province/dpc-covid19-ita-province-20200313.csv: ISO-8859 text 
```
sembra perciò che i file siano creati di default in ISO-8859-1. Quelli in UTF-8 sembrano sbagliati, vedi #134.

Personalmente penso che se è più semplice usare la  ISO-8859-1 (Latin1), è meglio documentare questo encoding e limitarsi a questo.

**Comment by umbros** [comment]
Ciao, ho convertito tutti i file in UTF-8. Grazie per la collaborazione

**Comment by miccoli** [comment]
@umbros  at 5693f66 file `dati-province/dpc-covid19-ita-province-20200314.csv` is still  ISO-8859-1.

And Forli is still garbled. 

Please reopen this issue.
