### ISSUE TITLE
Spercificare il nome del File CODE_OF_CONDUCT.md in lingua italiana

### ISSUE THREAD

**Issue by marcodadamo** [pcm-dpc/COVID-19#148]
- suggerimenti di miglioramento del file CODE_OF_CONDUCT.md

**Tipo di richiesta**: Rinominare il file CODE_OF_CONDUCT.md 

## Riassunto
Rinominare il file da CODE_OF_CONDUCT.md a CODICE_DI_CONDOTTA.md, o qualsiasi altro nome purché sia più intuitivo e chiaro nel far comprendere che all'interno esiste un codice di condotta in lingua italiana.

In questo caso ci sono due file simili:
1. CODE_OF_CONDUCT.md
2. CODE_OF_CONDUCT_EN.md

## Interesse pubblico
In questo modo è più semplice andare ad individuare il file (patto di collaborazione) in quanto scritto in italiano. L'utente è in grado di rintracciare più facilmente l'informativa.

**Comment by mydozer** [comment]
@marcodadamo la convenzione del medesima radice nel nome è voluta, così è più facile individuare i file tradotti in diverse lingua. Se pensi ti abbia risposto per favore chiudi il ticket. Grazie!!
