### ISSUE TITLE
nuovi attualmente positivi dati json regioni

### ISSUE THREAD

**Issue by giocaputo** [pcm-dpc/COVID-19#15]
Nei dati json per regione il campo [Nuovi Attualmente Positivi], non corrispondono ai dati visualizzati nelle grafiche
http://opendatadpc.maps.arcgis.com/apps/opsdashboard/index.html#/b0c68bce2cce478eaac82fe38d4138b1

**Comment by giocaputo** [comment]
![Sum Nuovi Attialmente Positivi](https://user-images.githubusercontent.com/13033027/76150529-cb050780-60ab-11ea-9907-c942ff65ffea.png)

**Comment by umbros** [comment]
Corretto. Grazie della segnalazione!
