### ISSUE TITLE
Il file LICENCE.md e il file LICENCE_EN.md hanno lo stesso contenuto. Scritti entrambi in lingua inglese

### ISSUE THREAD

**Issue by marcodadamo** [pcm-dpc/COVID-19#150]
- suggerimenti di miglioramento dei file.md LICENSE

**Tipo di richiesta**: Modificare il contenuto del file LICENCE.md
## Riassunto
 I due file LICENCE.md e LICENCE_EN.md sono scritti entrambi in lingua inglese, pertanto il loro  contenuto è uguale. Si consiglia di cambiare il contenuto al file LICENCE.md

## Interesse pubblico
Il file LICENCE dovrebbe essere scritto in  lingua italiana così da poter essere più chiaro e comprensibile.

**Comment by umbros** [comment]
Si lo so, dobbiamo aggiornare il file con la versione in italiano

**Comment by marcodadamo** [comment]
OK Grazie
