### ISSUE TITLE
Possibile dashboard grafica, merge tra data set john hopkins e protezione civile

### ISSUE THREAD

**Issue by aleskandro** [pcm-dpc/COVID-19#151]
**Tipo di richiesta**: relativo alla pagina grafica

## Riassunto

Ho sviluppato una dashboard grafica, un po' di giorni fa, che prendeva i dati dal dataset del John Hopkins University Center. Oggi quel dataset ha un problema e, per evitare di fornire informazioni errate almeno per l'Italia, ho voluto "in urgenza" spendere un po' di tempo per una integrazione che avevo gia' in programma con il vostro dataset.

Il progetto e' assolutamente amatoriale e, per evitare di fornire informazioni errate in questa fase delicata, non fa alcuna manipolazione dei dati disponibili.

Potrei proporvi di fare un merge con il vostro repository (dietro integrazione completa del vostro dataset di cui potrei occuparmi), o una migliore integrazione qualora possibile cosi che possa essere utile per la comunita' italiana (e non).

La dashboard e' gia' online in "produzione" e disponibile su GitHub e Dockerhub, solo in lingua inglese attualmente.

https://github.com/aleskandro/covid19-charts-spreading-rapidity

https://covid-19-spreading.alessandrodistefano.eu

Attualmente l'integrazione si limita ai dati per regione.

## Interesse pubblico

Possibilita' di visualizzare in maniera grafica i dati **puri** pubblicati dalla PC e dal dataset JohnHopkins per le altre nazioni. In particolare la velocita' di contaggio e i dati assoluti per regione. Magari con le dovute specifiche per esepmio in merito alla mancaza di normalizzazione e all'"inconsistenza" dei dati dovuta alle politiche di gestione dei tamponi, differenti tra le nazioni e all'interno della stessa Italia tra le regioni e durante il tempo.

**Comment by umbros** [comment]
Grzie mille @aleskandro
