### ISSUE TITLE
Numero di giorni per raddopiare (o decuplicare) i morti (o i contagiati)

### ISSUE THREAD

**Issue by mrai5011** [pcm-dpc/COVID-19#152]
Assumendo che la progressione sia esponenziale, e finora lo e', sarebbe utile:
1. Fornire il grafico in scala log (come fa Johns Hopkins)

2. Fornire un grafico con il numero di giorni necessari per raddoppiare o decuplicare il numero di morti/casi. 

L'ho fatto per i morti e trovo il dato molto interessante (e frightening).
Se a qualcuno interessa: 
http://www.abanovus.com/COVID-19/Regioni.html 
http://www.abanovus.com/COVID-19/MacroRegioni.html 
Potrebbe essere utile per chi deve fare della pianificazione (ammesso che non ce l'abbiano gia`.

Comunque ottimo lavoro

**Comment by umbros** [comment]
Ciao @mrai5011, la dashboard pubblicata ha il solo compito informativo e sui dati reputati necessari a dare una compiuta informazione al cittadino. Magari andando avanti proporremo nuove view. Complimenti per il tuo lavoro.
