### ISSUE TITLE
Inserire avvisi nel json

### ISSUE THREAD

**Issue by downFast** [pcm-dpc/COVID-19#153]
Salve,
grazie per l'enorme ed ottimo lavoro.

È possibile inserire gli avvisi tipo:

- 10/03/2020: dati Regione Lombardia parziali.
- 11/03/2020: dati Regione Abruzzo non pervenuti.

all'interno del json?

Grazie,
buon lavoro

**Comment by LBreda** [comment]
Appoggio questa richiesta e aggiungo che sarebbe utile siano meaningful (data, regione interessata, tipo di avviso ("dati parziali", "nessun dato"))

**Comment by downFast** [comment]
Si esatto

**Comment by umbros** [comment]
Ciao @downFast e @LBreda come potete vedere nel CHANGELOG è una prossima modifica che porteremo (https://github.com/pcm-dpc/COVID-19/blob/master/CHANGELOG.md)
