### ISSUE TITLE
La dashboard non mostra il Totale Positivi

### ISSUE THREAD

**Issue by AndreaPi** [pcm-dpc/COVID-19#154]
Come da soggetto, anche se il file CSV è stato caricato, la dashboard non mostra il Totale Positivi:

![image](https://user-images.githubusercontent.com/8233615/76647865-e796b900-655d-11ea-8d0a-472e734635ef.png)

**Comment by umbros** [comment]
Siamo in risoluzione del problema. Grazie

**Comment by umbros** [comment]
Problema rientrato!
