### ISSUE TITLE
Question about the field : terapia_intensiva

### ISSUE THREAD

**Issue by JiPiBi** [pcm-dpc/COVID-19#155]
Buona sera
Sorry to ask a perhaps obvious question 
I wanted to know what is the content of the field **terapia_intensiva** : is it a current value or a cumulative one
For the 12th of March : for the whole italy, 1153 persons means that there are at this moment 1153 persons in **terapia_intensiva**  or that 1153 persons were admitted into **terapia_intensiva** from the beginning of the epidemic ?

**Comment by PatValzer** [comment]
the first.. is the total number..

**Comment by JiPiBi** [comment]
@ PatValzer
Thanks for the answer . It was my fear.
So that means that about 140 more persons are admitted in **terapia_intensiva** every day (after deducting the dead persons of the day ) 
If the pace keeps on , when the bed's saturation will be reached ? (I read that in Lombardia it's already the case)

**Comment by umbros** [comment]
Hi @JiPiBi it's the current number.
