### ISSUE TITLE
Dati complessivi con mancanza di EOL a fine file

### ISSUE THREAD

**Issue by federicofranco** [pcm-dpc/COVID-19#158]
Tipo di issue:

- [x] Dati mancanti o errati 
- [ ] Errore nella documentazione 
- [ ] Errore or mancanza nella dashboard 
- [ ] Problemi di visualizzazione nella dashboard 

## Riassunto

I file complessivi relativi a regioni province e andamento nazionale hanno un problema. L'ultima riga non si riesce a importare con strumenti di ETL come logstash in quanto non hanno alla fine della riga EOL

**Attesa:**
Esempio relativo al giorno odierno
2020-03-13 17:00:00,ITA,7426,1328,8754,6201,14955,2116,1439,1266,17660,97488
Questa linea deve avere EOL 

**Attuale:** 
Esempio relativo al giorno odierno
2020-03-13 17:00:00,ITA,7426,1328,8754,6201,14955,2116,1439,1266,17660,97488Questa linea non ha EOL

**Comment by umbros** [comment]
Su issue #161
