### ISSUE TITLE
grazie mille, thank you

### ISSUE THREAD

**Issue by wyesoslo** [pcm-dpc/COVID-19#159]
Thank you very much for making these data available!  I have been trying to track the Veneto and Venezia in particular, and data published on line don't make that possible.  I finally found the source!  Since different clusters are at different points along the curve, I think it would be helpful to see the different trajectories for each area (Lombardy, Veneto, etc) over time.  That might help predict where and when the peak will arrive for each cluster.

**Comment by umbros** [comment]
Thank you for your suggestion.
