### ISSUE TITLE
Dove sono i dati di oggi 07-03-2020

### ISSUE THREAD

**Issue by mydozer** [pcm-dpc/COVID-19#16]
Ho visto che Esri ha fatto in fretta a mettere il suo nome nella mappa con i dati aggiornati (non siete gli unici a sapere mettere un punto in mappa), però mi pare che riporti un link a questo spazio inutile che non riporta nemmeno i pdf che la Protezione Civile e l'Istituto Superiore della Sanità fino a ieri hanno reso pubblicamente.

Dove sono i nostri dati di oggi?! Dov'è il documento ministeriale che dice di distribuire i propri dati sotto la licenza Commons Creative International e per di più con licenza in lingua inglese? A che titolo usate il logo del ministero? Non vedo un documento ufficiale protocolato. Cortesemente fornite i razionali per rendere lo spazio ufficialmente responsabile del dati condivisi.

Grazie!!

p.s. è ridicolo che i dati ministeriali come canale preferenziali siano rilasciati su git hub anche se la trovo una piattaforma eccellente per altri motivi.

**Comment by etrevis** [comment]
Se tutto quello che vuoi sono i PDF ed una pagina aggiornata questa è la [mia repo](https://github.com/etrevis/DB-and-Visuals-Covid-19-).

La licenza è presente nel Readme, nemmeno i pdf hanno un numero di protocollo e sarebbero file ridondanti qui. Il canale preferenziale è tuttora un sito http, non questa repo chiaramente. 

Probabilmente l'impiegato che l'aggiorna ha anche un interesse nel fare le mappe, ma non ci vedo nulla di male.

**Comment by umbros** [comment]
@mydozer i dati sono stati aggiornati, è utile in questo momento poter migliorare il servizio una volta che lo abbiamo messo a disposizione e siamo aperti a qualsiasi suggerimento. La licenza applicata è una CC-BY in modo da poter permettere la riutilizzabilità dei dati da chiunque voglia farne uso. Per quanto riguarda il processo di comunicazione e gestione dei dati è tra Regioni, Ministero della Salute e Dipartimento della Protezione Civile.

**Comment by mydozer** [comment]
> 
> 
> Se tutto quello che vuoi sono i PDF ed una pagina aggiornata questa è la [mia repo](https://github.com/etrevis/DB-and-Visuals-Covid-19-).
> 
> La licenza è presente nel Readme, nemmeno i pdf hanno un numero di protocollo e sarebbero file ridondanti qui. Il canale preferenziale è tuttora un sito http, non questa repo chiaramente.
> 
> Probabilmente l'impiegato che l'aggiorna ha anche un interesse nel fare le mappe, ma non ci vedo nulla di male.

Grazie per la dritta, verifica i tuoi dati 07-03 pare che almeno un documento sia di ieri. Il male è che Esri metta il suo nome in mappa e che Protezione Civilie e ISS sponsorizzino così un privato in modo indebito anche se il loro servizio dovesse essere a titolo gratuito. E' scorretto! Perché non hanno messo Infodata de Il sole 24 ore o la tua azienda? 
Se si vogliono fare le cose bene, vanno fatte bene. Noi pubblichiamo i dati dal 22/02 ed è ad oggi un continuo modificare di metodo di misura, fonte ufficiale, piattaforma di riferimento. Di sicuro c'è molto margine di miglioramento.

Dalle estituzioni va pretesa e ottenuta competenza!

Grazie al gestore di questo spazio che ha aggiornato i dati quasi in tempo reale. Però ci vuole l'ufficialità visto che è referenziato nella mappa della Protezione Civile.

**Comment by mydozer** [comment]
> 
> 
> @mydozer i dati sono stati aggiornati, è utile in questo momento poter migliorare il servizio una volta che lo abbiamo messo a disposizione e siamo aperti a qualsiasi suggerimento. La licenza applicata è una CC-BY in modo da poter permettere la riutilizzabilità dei dati da chiunque voglia farne uso. Per quanto riguarda il processo di comunicazione e gestione dei dati è tra Regioni, Ministero della Salute e Dipartimento della Protezione Civile.

Lo spazio è referenziato come fonte dei dati nella mappa che la Protezione Civile cita come dashboard ufficiale! Attenzione! Togliete il link se non è autorizzato come fonte d'origine dei dati e mettete la pagina relativa della protezione civile.

Capisco e ringrazio il lavoro svolto!

Sono dati che hanno valenza ufficiale o soggetti ad errore a valle del documento ufficiale?
