### ISSUE TITLE
Ospedalizzazioni incongruenza

### ISSUE THREAD

**Issue by marcotrombetti** [pcm-dpc/COVID-19#160]
Grazie del lavoro.

l’istituto superiore di sanità riporta ospedalizzazioni al 20-25%. Nei vostri dati sono al 50-60%. Corretto? Come va interpretato?

Ref:
https://www.iss.it/web/guest/primo-piano/-/asset_publisher/o4oGR9qmvUz9/content/id/5293226

**Comment by massimo-github** [comment]
> _Lo stato clinico è disponibile solo per 2.539 casi_, di cui 518 (9,8%) asintomatici, 270 (5,1%) pauci-sintomatici, 1.622 (30,7%) con sintomi per cui non viene specificato il livello di gravità, 1.593 (30,1%) con sintomi lievi, 297 (5,6%) con sintomi severi, 985 (18,6%) critici. **Il 21% dei casi risulta ospedalizzato**, e tra quelli di cui si conosce il reparto di ricovero (1.545) il 12% risulta in terapia intensiva. L’età mediana è di 69 anni (0-18 anni: 0%; 19-50 anni: 10%; 51-70 anni: 46%; >70 anni: 44%).

Immagino tu ti riferisca al dato che ho messo in grassetto. Nota che è specificato come questo sia parziale (vedi testo in corsivo). 
Al 10/3 i positivi totali erano 8514 (numero tratto da https://github.com/pcm-dpc/COVID-19/blob/master/dati-andamento-nazionale/dpc-covid19-ita-andamento-nazionale.csv), quindi il dato si riferisce a circa un terzo di questi (non randomizzati, immagino); non mi sembra rappresentativo della situazione complessiva.

**Comment by umbros** [comment]
CIao @marcotrombetti ,
questi sono i dati che a noi pervengono dalle Regioni per il tramite del Ministero della Salute e sono aggiornati quotidianamente.
