### ISSUE TITLE
UTF-8 encoding with BOM ––– garbled "Forlì" in 'dati-province/dpc-covid19-ita-province-????????.csv'

### ISSUE THREAD

**Issue by miccoli** [pcm-dpc/COVID-19#161]
Type of issue:

- [x ] Incorrect or missing data : `dati-province/dpc-covid19-ita-province-????????.csv`
- [ ] Incorrect or missing documentation 
- [ ] Incorrect or missing data in the dashboard 
- [ ] Layout problem in the dashboard 

## Summary

This is a follow-up of #147 and #134: spelling of Forlì is wrong in a few files.

<details>

```
$ grep Cesena dati-province/dpc-covid19-ita-province-????????.csv
dati-province/dpc-covid19-ita-province-20200224.csv:2020-02-24 18:00:00,ITA,08,Emilia Romagna,040,Forlï¿½-Cesena,FC,44.22268559,12.04068608,0
dati-province/dpc-covid19-ita-province-20200225.csv:2020-02-25 18:00:00,ITA,08,Emilia Romagna,040,Forlï¿½-Cesena,FC,44.22268559,12.04068608,0
dati-province/dpc-covid19-ita-province-20200226.csv:2020-02-26 18:00:00,ITA,08,Emilia Romagna,040,Forlï¿½-Cesena,FC,44.22268559,12.04068608,0
dati-province/dpc-covid19-ita-province-20200227.csv:2020-02-27 18:00:00,ITA,08,Emilia Romagna,040,Forlï¿½-Cesena,FC,44.22268559,12.04068608,0
dati-province/dpc-covid19-ita-province-20200228.csv:2020-02-28 18:00:00,ITA,08,Emilia Romagna,040,Forlï¿½-Cesena,FC,44.22268559,12.04068608,0
dati-province/dpc-covid19-ita-province-20200229.csv:2020-02-29 17:00:00,ITA,08,Emilia Romagna,040,Forlï¿½-Cesena,FC,44.22268559,12.04068608,0
dati-province/dpc-covid19-ita-province-20200301.csv:2020-03-01 17:00:00,ITA,08,Emilia Romagna,040,Forlï¿½-Cesena,FC,44.22268559,12.04068608,1
dati-province/dpc-covid19-ita-province-20200302.csv:2020-03-02 17:00:00,ITA,08,Emilia Romagna,040,Forlï¿½-Cesena,FC,44.22268559,12.04068608,1
dati-province/dpc-covid19-ita-province-20200303.csv:2020-03-03 17:00:00,ITA,08,Emilia Romagna,040,Forlï¿½-Cesena,FC,44.22268559,12.04068608,1
dati-province/dpc-covid19-ita-province-20200304.csv:2020-03-04 17:00:00,ITA,08,Emilia Romagna,040,Forlï¿½-Cesena,FC,44.22268559,12.04068608,2
dati-province/dpc-covid19-ita-province-20200305.csv:2020-03-05 17:00:00,ITA,08,Emilia Romagna,040,Forlï¿½-Cesena,FC,44.22268559,12.04068608,4
dati-province/dpc-covid19-ita-province-20200306.csv:2020-03-06 18:00:00,ITA,08,Emilia Romagna,040,Forlï¿½-Cesena,FC,44.22268559,12.04068608,3
dati-province/dpc-covid19-ita-province-20200307.csv:2020-03-07 18:00:00,ITA,08,Emilia Romagna,040,Forlï¿½-Cesena,FC,44.22268559,12.04068608,7
dati-province/dpc-covid19-ita-province-20200308.csv:2020-03-08 18:00:00,ITA,08,Emilia Romagna,040,Forlï¿½-Cesena,FC,44.22268559,12.04068608,15
dati-province/dpc-covid19-ita-province-20200309.csv:2020-03-09 18:00:00,ITA,08,Emilia Romagna,040,Forlï¿½-Cesena,FC,44.22268559,12.04068608,16
dati-province/dpc-covid19-ita-province-20200310.csv:2020-03-10 18:00:00,ITA,08,Emilia Romagna,040,Forlï¿½-Cesena,FC,44.22268559,12.04068608,20
dati-province/dpc-covid19-ita-province-20200311.csv:2020-03-11 17:00:00,ITA,08,Emilia Romagna,040,Forlì-Cesena,FC,44.22268559,12.04068608,24
dati-province/dpc-covid19-ita-province-20200312.csv:2020-03-12 17:00:00,ITA,08,Emilia Romagna,040,Forlì-Cesena,FC,44.22268559,12.04068608,33
dati-province/dpc-covid19-ita-province-20200313.csv:2020-03-13 17:00:00,ITA,08,Emilia Romagna,040,Forlì-Cesena,FC,44.22268559,12.04068608,49
```

</details>

Please also note that now the encoding is 'UTF-8 with BOM', which is a third variant of the encodings seen so far. This will probably break software parsing the files assuming ASCII encoding.

This is also non consistent with files `dati-regioni/dpc-covid19-ita-regioni-????????.csv` which are encoded as ASCII (and therefore without a BOM).

I understand that getting the encoding right is difficult, but please, be consistent:
- all files in UTF-8 with BOM
- all files in UTF-8 *without* BOM
- all files in  ISO-8859-1.

If @bfabio (author of #134) agrees, I can provide a PR once there is consensus on the encoding.

I would strongly suggest `ISO-8859-1` and discourage UTF-8 since incorrect handling of the BOM could cause incompatibilities between *nix and Windows.

**Comment by bfabio** [comment]
> Please also note that now the encoding is 'UTF-8 with BOM',

Also, there's a `"Forlï¿½"`, which indicates the Unicode REPLACEMENT CHARACTER was converted back and forth and resulted in a formally valid UTF-8 file, but with wrong data.

> This will probably break software parsing the files assuming ASCII encoding.
You're 100% right. We should drop the BOM: it's not needed by definition with UTF-8 and can cause endless pain in the neck.

> This is also non consistent with files `dati-regioni/dpc-covid19-ita-regioni-????????.csv` which are encoded as ASCII (and therefore without a BOM).

That's expected. ASCII is a subset of UTF-8 and those files happen to not have codepoints above 127.
 
> If @bfabio (author of #134) agrees, I can provide a PR once there is consensus on the encoding.

Sure 🙂

> I would strongly suggest `ISO-8859-1` and discourage UTF-8 since incorrect handling of the BOM could cause incompatibilities between *nix and Windows.

@miccoli  I wholeheartedly agree the encoding should be consistent, but the best choice is UTF-8 with no BOM.

Please either revert 3e00173fd97 and merge #134 or merge the future patch @miccoli will provide.

**Comment by umbros** [comment]
Please check:
https://github.com/pcm-dpc/COVID-19/blob/master/dati-andamento-nazionale/dpc-covid19-ita-andamento-nazionale.csv
https://github.com/pcm-dpc/COVID-19/blob/master/dati-province/dpc-covid19-ita-province.csv
https://github.com/pcm-dpc/COVID-19/blob/master/dati-regioni/dpc-covid19-ita-regioni.csv

Thank you

**Comment by miccoli** [comment]
Check done at e080664 (below EOL is End of Line, EOF is End Of File)

> Please check:
> UTF-8 CRLF
> 
> https://github.com/pcm-dpc/COVID-19/blob/master/dati-andamento-nazionale/dpc-covid19-ita-andamento-nazionale.csv

ASCII encoding, no EOL at EOF

> https://github.com/pcm-dpc/COVID-19/blob/master/dati-province/dpc-covid19-ita-province.csv

UTF-8 without BOM, no EOL at EOF
Spelling of Forlì wrong.

> https://github.com/pcm-dpc/COVID-19/blob/master/dati-regioni/dpc-covid19-ita-regioni.csv

ASCII encoding, no EOL at EOF
Spelling of Forlì wrong.

Automatic CRLF normalisation, see <https://git-scm.com/docs/gitattributes#_code_text_code> seems  OK for the repo.

All other files unchanged.

**Comment by miccoli** [comment]
> @miccoli I wholeheartedly agree the encoding should be consistent, but the best choice is UTF-8 with no BOM.

@bfabio I agree that under normal circumstances UTF-8 without BOM is the way to go. But from the history of this repo it seems that the tools used to generate the `.csv` files work with either ISO-8859-1 or UTF-8 with BOM ; since the BOM is a total mess for most users unaware of Unicode idiosyncrasies, to guarantee consistency I think that ISO-8859-1 is a more pragmatic choice.

But here is @umbros that should express his opinion.

**Comment by umbros** [comment]
Hi, miccoli, we will set all file to UTF-8 we are working on it. Thank you for your suggestion

**Comment by umbros** [comment]
Hi @miccoli please check now:
https://github.com/pcm-dpc/COVID-19/blob/master/dati-andamento-nazionale/dpc-covid19-ita-andamento-nazionale.csv
https://github.com/pcm-dpc/COVID-19/blob/master/dati-province/dpc-covid19-ita-province.csv
https://github.com/pcm-dpc/COVID-19/blob/master/dati-regioni/dpc-covid19-ita-regioni.csv

**Comment by bfabio** [comment]
> https://github.com/pcm-dpc/COVID-19/blob/master/dati-andamento-nazionale/dpc-covid19-ita-andamento-nazionale.csv
> https://github.com/pcm-dpc/COVID-19/blob/master/dati-province/dpc-covid19-ita-province.csv
> https://github.com/pcm-dpc/COVID-19/blob/master/dati-regioni/dpc-covid19-ita-regioni.csv

Those are good, thanks.

The files in `dati-province/` from 20200224 to 20200313 still have the BOM and the garbled data for Forlì.

`dpc-covid19-ita-province-20200314.csv` is ISO-8859-1 encoded.

`dpc-covid19-ita-andamento-nazionale.json`, `dpc-covid19-ita-province.json` and `dpc-covid19-ita-regioni.json` have the BOM now (a44f27a38f139ffe)

Haven't checked for the EOF.

**Comment by miccoli** [comment]
> Haven't checked for the EOF.
At b056955 all CSV files have and EOL at EOF.

**Comment by miccoli** [comment]
> Hi, @miccoli, we will set all file to UTF-8 we are working on it. Thank you for your suggestion

With or without BOM? 

From [wikipedia](https://en.wikipedia.org/wiki/Byte_order_mark#UTF-8):

> The Unicode Standard permits the BOM in UTF-8, but does not require or recommend its use.

The current pattern is that updates to `dpc-covid19-ita-province-????????.csv ` are added in ISO-8859-1.

**Comment by umbros** [comment]
@miccoli @bfabio tonight a batch will set all files to utf-8 and check if it's all ok.
Thank you for your support.

**Comment by umbros** [comment]
Solved, thank you @miccoli and @bfabio
