### ISSUE TITLE
Hopsital data for hospitalized cases

### ISSUE THREAD

**Issue by lucabarbaglia** [pcm-dpc/COVID-19#162]
Dear, in order to check the pressure on the hospital infrastructure, it would be great to have information on which hospital patients with covid19 are treated. I would use the hospital code provided by the Italian Health Ministry at this link:
http://www.dati.salute.gov.it/dati/dettaglioDataset.jsp?menu=dati&idPag=96
Is it possible? Thanks

**Comment by umbros** [comment]
Hello, at present, we don't manage that information. If there are changes we will notify you in time and in CHANGELOG.
