### ISSUE TITLE
[Improvement] Utilizzare i dati raccolti per prevedere la diffusione del virus

### ISSUE THREAD

**Issue by franout** [pcm-dpc/COVID-19#163]
buongiorno,

sarebbe utile mettere questi dati in un algoritmo di ML in modo da prevedere in quale zone il virus si possa diffondere ed agire di conseguenza.

**Comment by umbros** [comment]
Ciao, @franout qui riportiamo i dati comunicati dalle Regioni al Ministero della Sanità ogni giorno, eventuali lavorazioni o analisi sono attività che ognuno è libero di fare secondo la propria responsabilità.
