### ISSUE TITLE
link nel APP rotto

### ISSUE THREAD

**Issue by 73stefano** [pcm-dpc/COVID-19#164]
![Schermata 2020-03-14 alle 14 35 10](https://user-images.githubusercontent.com/25998603/76683094-9c35e680-6601-11ea-8e91-0e2fe00ed7f2.png)

Tipo di issue:

- [ ] Dati mancanti o errati 
- [ ] Errore nella documentazione 
- [x ]  Errore or mancanza nella dashboard 
- [ ] Problemi di visualizzazione nella dashboard 

## Riassunto

Il link del ministero salute nella dashboard è rotto porta ad una pagina con risposta HTTP Status 400 – Bad Request
Grazie Mille

**Comment by umbros** [comment]
Corretto, grazie della segnalazione.

**Comment by 73stefano** [comment]
prego 
 buon lavoro
