### ISSUE TITLE
Lacking of data description: actual or cumulative?

### ISSUE THREAD

**Issue by MarcoBisi0** [pcm-dpc/COVID-19#165]
Type of issue:

- [ ] Incorrect or missing data : 
- [X] Incorrect or missing documentation 
- [ ] Incorrect or missing data in the dashboard 
- [ ] Layout problem in the dashboard 

## Summary
I wasn't able to find a description of the data, I can't understand which are cumulative and which are actual on a daily base

**Expected:**

Please, state for each column in data files whether the number of cases is cumulative or is pertaining to that particular day. 
Alternatively, please describe what data represent in README.md

**Actual:**

Missing data description: cumulative or actual on daily base?

**In any case, thank you for this Project. Good job!**

**Comment by umbros** [comment]
all data represent the daily situation.

**Comment by MarcoBisi0** [comment]
Dear umbros, it is clear that every data represents the daily situation. My question is which data is actual and which is cumulative. There is no doubt that only some data are cumulative, e.g. "totale_attualmente_positivi", while other are actual on a daily basis, e.g. "nuovi_attualmente_positivi".

If you take a look at "Piemonte", on 2020-03-12 "totale_attualmente_positivi"=**554** and "nuovi_attualmente_positivi"=_74_, while on 2020-03-11 "totale_attualmente_positivi"=480=**554**-_74_
It is clear to me that "totale_attualmente_positivi" is cumulative, while "nuovi_attualmente_positivi" is actual. I think it would be better to specify in the README.md

**Comment by MarcoBisi0** [comment]
Let me add that, as a good practice, it is better to clearly state what data represent
