### ISSUE TITLE
Colonna long non utilizzabile da alcune webapp

### ISSUE THREAD

**Issue by albert-one** [pcm-dpc/COVID-19#166]
**Tipo di richiesta**:suggerimento di miglioramento (documentazione, label, _ecc_)

## Riassunto

Il dato in colonna "long" non è sempre utilizzabile.

## Interesse pubblico

Alcune webapp (come umap) possono utilizzare i dati messi a disposizione tramite url in vari formati, fra cui csv e geojson. La mappa può essere dinamica con caricamento automatico alla variazione del sorgente.
Umap è basato su OSM ed è open source.
Umap ha però bisogno che la colonna della longitudine sia chiamata "lon" oppure "lng", altrimenti il dato non viene letto e non vengono georeferziate le informazioni collegate. Diversamente la mappa non viene popolata.

**Comment by umbros** [comment]
Ciao @albert-one non è opportuno rinominare i campi, quello che puoi fare è scaricare il file e ricaricarlo, ad esempio su un tuo repository, con i nomi dei campi rinominato.
