### ISSUE TITLE
Nuovi attualmente positivi, valori negativi

### ISSUE THREAD

**Issue by Smokey-it** [pcm-dpc/COVID-19#167]
Tipo di issue:

- [X ] Dati mancanti o errati - dpc-covid19-ita-regioni
- [X ] Errore nella documentazione - README
- [ ] Errore or mancanza nella dashboard 
- [ ] Problemi di visualizzazione nella dashboard 

- Regione: varie
- Provincia: N/A

## Riassunto
Nel file dpc-covid19-ita-regioni.
Nel campo nuovi_attualmente_positivi ci sono valori negativi, che smentisce il calcolo descritto nella documentazione come spedalizzati+isolamento 

**Attesa:**
il numero di spedalizzati non puo' essere negativo, cosi' come il numero di persone in isolamento. Se e' una formula, andrebbe documentata meglio

**Attuale:** 
non capisco che valori contenga, dato che un negativo non ha senso

**Comment by umbros** [comment]
Thank you for your suggestion. Il dato negativo è possibile dal momento che i totali positivi di una regione odierna potrebbero essere meno di quelli del giorno prima.

**Comment by Smokey-it** [comment]
Ok, grazie della spiegazione. Nella documentazione non andrebbe aggiunto "rispetto al giorno prima"?
Mi scuso per il disturbo
