### ISSUE TITLE
One more column in file "dati-regioni/dpc-covid19-ita-regioni-20200305.csv"

### ISSUE THREAD

**Issue by ricvolpi** [pcm-dpc/COVID-19#17]
Hi -- thank you for releasing the data. 

CSV file "dati-regioni/dpc-covid19-ita-regioni-20200305.csv" has 17 column (the additional one is unnamed), while all others in the same folder have 16.

Best,
Ric

**Comment by umbros** [comment]
Hi ricvolpi,
I'm unable to see that problem, 
https://github.com/pcm-dpc/COVID-19/blob/master/dati-regioni/dpc-covid19-ita-regioni-20200305.csv
Please can you do a pull request and I can check the file modified?

Thanks

**Comment by ricvolpi** [comment]
Hi umbros -- Sorry, I was loading it with pandas and probably it messed the file up somehow. Everything looks fine now, thanks.
