### ISSUE TITLE
Aggiungere avviso riguardante il 7 Marzo

### ISSUE THREAD

**Issue by marco-c** [pcm-dpc/COVID-19#170]
Sarebbe utile aggiungere un avviso riguardante il fatto che i dati al 7 Marzo erano parziali, come fatto per il 10 e l'11 (see also #72).

**Comment by umbros** [comment]
Inserito, grazie per la segnalazione ma al 7 ancora non mostravamo il campo Note.

**Comment by marco-c** [comment]
@umbros ancora non lo vedo tra gli avvisi :)
