### ISSUE TITLE
Storico dati JSON troncato (presente solo oggi)

### ISSUE THREAD

**Issue by pescetti** [pcm-dpc/COVID-19#171]
Tipo di issue:

- Dati mancanti o errati 

- Regione:
- Provincia: Tutte

## Riassunto

https://github.com/pcm-dpc/COVID-19/blob/master/dati-json/dpc-covid19-ita-province.json è evidentemente troncato.

**Attesa:**

Il file dovrebbe contenere lo storico dei dati fino ad oggi.

**Attuale:** 

Il file contiene solo i dati di oggi e lo storico è stato eliminato.

**Comment by flavio20002** [comment]
Thanks, I was also opening an issue for this.

**Comment by umbros** [comment]
Corretto, grazie!

**Comment by pescetti** [comment]
Grazie! Certo, soprattutto per le applicazioni che si sincronizzano in tempo reale con questo repository sarebbe bene avere qualche test automatico che dia garanzie. Li sto sviluppando in un fork e li metto volentieri a disposizione se possono essere utili (vedere issue linkata sopra nel caso).
