### ISSUE TITLE
Denominazione delle province autonome errata per il dato 14/03/2020

### ISSUE THREAD

**Issue by ludovico85** [pcm-dpc/COVID-19#172]
Tipo di issue:

- [x] Dati mancanti o errati 
- [ ] Errore nella documentazione 
- [ ] Errore or mancanza nella dashboard 
- [ ] Problemi di visualizzazione nella dashboard 

- Regione:x
- Provincia: 

## Riassunto

Nell'aggiornamento del 14/03/2020 le province autonome di Bolzano e Trento sono indicate senza il prefisso P.A.. 

**Attesa:**

**Attuale:**

**Comment by roncolat** [comment]
C'è il solito problema di Friuli V. G. nel giorno 14/03, mentre negli atri è Friuli Venezia Giulia

**Comment by umbros** [comment]
Corretto, grazie!
