### ISSUE TITLE
Dato età, sesso, stato paziente

### ISSUE THREAD

**Issue by downFast** [pcm-dpc/COVID-19#173]
Salve,
ieri nel change log avevo visto

```
Prossimi aggiornamenti
Aggiunta "Note" in "dati-regioni", "dati-province" e "dati-andamento-nazionale"
Dati per Comune, Età, Sesso, Stato paziente (Backlog)
```

Oggi `Dati per Comune, Età, Sesso, Stato paziente (Backlog)` non c'è, possiamo considerare quindi che non li avremo disponibili nel json?

Grazie mille

**Comment by umbros** [comment]
Allo stato attuale non sono previsti, ogni nuova modifica sarà prontamente comunicata. Grazie
