### ISSUE TITLE
File JSON non validi causa BOM

### ISSUE THREAD

**Issue by pescetti** [pcm-dpc/COVID-19#174]
Tipo di issue:

- x Dati mancanti o errati 
- Provincia: tutte

## Riassunto

**Attesa:** I file JSON non possono contenere un BOM. https://tools.ietf.org/html/rfc8259#section-8.1 Quindi il file JSON deve essere sprovvisto di BOM per essere valido.

**Attuale:** 

```
diff --git a/dati-json/dpc-covid19-ita-province.json b/dati-json/dpc-covid19-ita-province.json
index 2615f81..253245e 100644
--- a/dati-json/dpc-covid19-ita-province.json
+++ b/dati-json/dpc-covid19-ita-province.json
@@ -1,4 +1,4 @@
-[
+<U+FEFF>[
     {
         "data": "2020-02-24 18:00:00",
         "stato": "ITA",
```

Le modifiche di oggi aggiungono un BOM, che rende il file illeggibile dalle applicazioni conformi allo standard.

**Comment by bfabio** [comment]
See #161

**Comment by mydozer** [comment]
Tutti file JSON sono con il BOM. np++ aiuta, ma l'intergrazione è stalta

**Comment by mydozer** [comment]
@bfabio il problema è presente json sui file appena generati

**Comment by bfabio** [comment]
> @bfabio il problema è presente sui file json appena generati

Sì: https://github.com/pcm-dpc/COVID-19/issues/161#issuecomment-599107680

**Comment by mydozer** [comment]
@bfabio pardon, la mia era un'affermazione. Il #161 è relativo ai file csv e fino a ieri il problema BOM non era presente sui file JSON.

**Comment by pescetti** [comment]
La differenza è che per il CSV uno potrebbe anche dire che è questione di gusti. Nel JSON non è questione di gusti, è vietato. Cito da RFC come in descrizione:

> Implementations MUST NOT add a byte order mark (U+FEFF) to the
   beginning of a networked-transmitted JSON text.

Comunque assolutamente d'accordo anche con #161 sulla comodità di avere un encoding prevedibile e coerente anche per i CSV.

**Comment by umbros** [comment]
#161 - L'encoding è UTF-8

**Comment by mydozer** [comment]
> 
> 
> #161 - L'encoding è UTF-8

dpc-covid19-ita-andamento-nazionale.json è ancora con il BOM. Grazie!

**Comment by miccoli** [comment]
In 5693f66 il BOM è ancora presente. Prego riaprire.

**Comment by miccoli** [comment]
@umbros per cortesia, quando chiudi una issue indica la motivazione e il commit che risolve il problema. Altrimenti non si capisce nulla. Inoltre le issue chiuse possono anche essere riaperte.

**Comment by pescetti** [comment]
Segnalo per completezza che con l'ultimo aggiornamento il problema è risolto, dettagli in #180. Grazie.

**Comment by miccoli** [comment]
Grazie anche da parte mia.
