### ISSUE TITLE
Totale casi provincie Sicilia invariati da 3 giorni?

### ISSUE THREAD

**Issue by Jottoart** [pcm-dpc/COVID-19#175]
Salve,

ho notato che dal 12 Marzo il totale casi riportato per le provincie siciliane non cambia da 3 giorni, mi riferisco a questo file https://raw.githubusercontent.com/pcm-dpc/COVID-19/master/dati-province/dpc-covid19-ita-province.csv

Il totale regione Sicilia invece sembra crescere . 
Entrambi i dati, provincie e regioni sono allineati con i dati riportati dal Dipartimento della Protezione Civile. Mi chiedevo quindi se non si tratti di una questione legata ai casi totali ancora in fase di  definizione/aggiornamento.

Grazie

**Comment by umbros** [comment]
Ciao, il totale sta crescendo ma a livello provinciale sono inseriti in "In fase di definizione/aggiornamento".
