### ISSUE TITLE
Additional info - if possible

### ISSUE THREAD

**Issue by mcastagnaa** [pcm-dpc/COVID-19#176]
**Additional data**:  richiesta di dati

## Summary
It would be fantastic if three additional fields (which I believe would enhance the ability to draw inference and provide forcast) could be added:

1. number of death
2. average age of cases
3. average age of death

**Comment by umbros** [comment]
Hi, @mcastagnaa currently we do not provide this data, any changes or updates will be communicated and written in the CHANGELOG.
