### ISSUE TITLE
Latitudine e Longitudine Calabria errata

### ISSUE THREAD

**Issue by leoniDEV** [pcm-dpc/COVID-19#177]
Tipo di issue:

- [ ] Dati mancanti o errati 
- [x] Errore nella documentazione [dpc-covid19-ita-regioni-20200314.csv](https://github.com/pcm-dpc/COVID-19/blob/master/dati-regioni/dpc-covid19-ita-regioni-20200314.csv)
- [ ] Errore or mancanza nella dashboard 
- [ ] Problemi di visualizzazione nella dashboard 

- Regione: Calabria
- Provincia: 

## Riassunto
Latitudine e longitudine erratw, in tutti gli altri file vengono riportate altri valori di latitudine e longitudine

**Attesa:**

data | stato | codice_regione | denominazione_regione | lat | long | ricoverati_con_sintomi | terapia_intensiva | totale_ospedalizzati | isolamento_domiciliare | totale_attualmente_positivi | nuovi_attualmente_positivi | dimessi_guariti | deceduti | totale_casi | tamponi
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
2020-03-13 17:00:00|ITA|18|Calabria|**38.90597598**|**16.59440194**|18|3|21|16|37|5|1|0|38|504

**Attuale:** 

data | stato | codice_regione | denominazione_regione | lat | long | ricoverati_con_sintomi | terapia_intensiva | totale_ospedalizzati | isolamento_domiciliare | totale_attualmente_positivi | nuovi_attualmente_positivi | dimessi_guariti | deceduti | totale_casi | tamponi
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
2020-03-14 17:00:00|ITA|18|Calabria|**38.10922769**|**15.6434527**|22|4|26|33|59|22|1|0|60|711

**Comment by umbros** [comment]
Corretto, grazie
