### ISSUE TITLE
both Bolzano and P.A. Bolzano

### ISSUE THREAD

**Issue by gtropea** [pcm-dpc/COVID-19#179]
Type of issue:

- [X ] Incorrect or missing data : 
- [ ] Incorrect or missing documentation 
- [ ] Incorrect or missing data in the dashboard 
- [ ] Layout problem in the dashboard 

- Region:
- Province: 
P.A. Bolzano and  P.A. Trento

## Summary

in current file dpc-covid19-ita-regioni.json there is both "Bolzano" and "P.A. Bolzano".
Also there is both "Trento" and "P.A. Trento".
They have same Lat and Lon, so they are the same place. 

**Expected:**
The labels should be changed and made the same unique string "Trento" (or "P.A. Trento")

**Comment by umbros** [comment]
Corretto, grazie
