### ISSUE TITLE
grafico andamento nazionale

### ISSUE THREAD

**Issue by eros23** [pcm-dpc/COVID-19#18]
Ciao @umbros 
Il grafico andamento nazionale non si visualizza bene, magari forse è meglio farlo a settimane.
Vedi foto
[Foto](http://wordpress.assistiamoli.it/grafico-andamento-nazionale.PNG)

**Comment by umbros** [comment]
Ciao, per ora ho formattato la data in dd/mm sicuramente andando avanti l'andamento sarà messo per settimane o giornaliero utilizzando uno scrolling. Vedremo nel tempo di trovare sempre una migliore visualizzazione delle informazioni. Grazie per il suggerimento
