### ISSUE TITLE
Today Json update report a malformed JSON

### ISSUE THREAD

**Issue by saverioserravezza** [pcm-dpc/COVID-19#180]
Type of issue:

- [ ] Incorrect or missing data : dpc-covid19-ita-regioni.json, json/dpc-covid19-ita-andamento-nazionale.json

## Summary

On PHP 7.2.24 "json_decode" report a NULL object (malformed data?)

**Expected:**

Until yesterday update json_decode was parsing correctly.

**Actual:** 
Suspect there is a malformed data or syntax issue. Json validators seems parsing file correctly. I will investigate more.

**Comment by giocaputo** [comment]
i think that is not UTF-8 but UTF-8 BOM. Try to convert it before.

**Comment by lupodellasleppa** [comment]
Parsing works in Python removing first character `\ufeff`

```Python
>>> import json
>>> with open('TEMP_prov') as f:
...     covid_province = json.load(f)
... 
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/usr/lib/python3.7/json/__init__.py", line 296, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/usr/lib/python3.7/json/__init__.py", line 338, in loads
    s, 0)
json.decoder.JSONDecodeError: Unexpected UTF-8 BOM (decode using utf-8-sig): line 1 column 1 (char 0)
>>> with open('TEMP_prov') as f:
...     covid_txt = f.read()
... 
>>> covid_txt[0]
'\ufeff'
>>> covid_province = json.loads(covid_txt[1:])
>>>
```

So either decode with UTF-8 BOM or omit the first character

**Comment by bfabio** [comment]
See #174

**Comment by saverioserravezza** [comment]
YES: was Byte-order mark introduced with today update.
Thanks

`function remove_utf8_bom($text) {
    $bom = pack('H*','EFBBBF');
    $text = preg_replace("/^$bom/", '', $text);
    return $text;
}`

**Comment by AndrewDevIT** [comment]
Use this for remove UTF-8 BOM characters
```
  if(substr($data, 0, 3) == pack("CCC", 0xEF, 0xBB, 0xBF)) {
  $data= substr($data, 3);
}
```

**Comment by umbros** [comment]
Il formato è stato corretto ora è UTF-8

**Comment by pescetti** [comment]
Vero, grazie! Il BOM è stato eliminato in cd7be04d e questo risolve anche #174 che sostanzialmente era lo stesso problema. Ora il file JSON è conforme alle specifiche senza bisogno di adattare i parser.
