### ISSUE TITLE
totale casi e altri metriche, giornaliere

### ISSUE THREAD

**Issue by marcodo1976** [pcm-dpc/COVID-19#181]
**Tipo di richiesta**:  richiesta di dati 

## Riassunto

è possibile aggiungere alla base dati province i casi giornalieri?

## Interesse pubblico

in questo modo è possibile, senza ulteriori elaborazioni, avere i casi giorno x giorno e non solo la cumulata. Grazie

**Comment by umbros** [comment]
Ciao @marcodo1976, se vuoi vedere l'andamento per provincia puoi fare riferimento al totale_casi giorno per giorno e gestire così l'andamento.

**Comment by marcodo1976** [comment]
Ciao Umbros, nel totale casi viene riportata la cumulata, non il dato giornaliero. so che posso ricavarlo, ma volendo produrre dei grafici senza passare da fogli di calcolo come excel, mi sarebbe molto utile.

la base dati che sto utilizzando è questa https://raw.githubusercontent.com/pcm-dpc/COVID-19/master/dati-province/dpc-covid19-ita-province.csv
