### ISSUE TITLE
Anomalia dati nazionali: totale attualmente positivi

### ISSUE THREAD

**Issue by SimoneTinella** [pcm-dpc/COVID-19#182]
Tipo di issue:

- [X] Dati mancanti o errati 
- [ ] Errore nella documentazione
- [ ] Errore or mancanza nella dashboard
- [ ] Problemi di visualizzazione nella dashboard

## Riassunto
file: **dpc-covid19-ita-andamento-nazionale.json**

Analizzando i dati dell'andamento nazionale ho rilevato una anomalia relativo al campo **totale_attualmente_positivi** e di conseguenza anche quelli ad esso legati come **totale_casi**.

Confrontando i dati relativi ad uno specifico giorno con il giorno immediatamente precendente si nota che il campo è cresciuto esattamente della quantità di **nuovi_attualmente_positivi** il che è errato in quanto alcuni dei pazienti sono andanti a dividersi nei campi _deceduti_ e _dimessi_guariti_ non essendo quindi più ATTUALMENTE positivi, quindi il campo **totale_attualmente_positivi** dovrebbe aumentare di una quantità inferiore a **nuovi_attualmente_positivi**, in particolare l'incremento sarebbe di: **nuovi_attualmente_positivi** - _nuovi_guariti_ - _nuovi_deceduti_.

**Comment by umbros** [comment]
Ciao @SimoneTinella,
i nuovi attualmente positivi sono la differenza tra i totale attualmente positivi del giorno corrente con quelli del giorno precedente, i totale casi sono la somma di totale attualmente positivi + guariti + deceduti.

data | stato | totale_attualmente_positivi | nuovi_attualmente_positivi
-- | -- | -- | --
2/24/2020 18:00 | ITA | 221 | 221
2/25/2020   18:00 | ITA | 311 | 90
2/26/2020 18:00 | ITA | 385 | 74
2/27/2020   18:00 | ITA | 588 | 203
2/28/2020 18:00 | ITA | 821 | 233
2/29/2020   18:00 | ITA | 1049 | 228
3/1/2020 18:00 | ITA | 1577 | 528
3/2/2020   18:00 | ITA | 1835 | 258
3/3/2020 18:00 | ITA | 2263 | 428
3/4/2020   18:00 | ITA | 2706 | 443
3/5/2020 18:00 | ITA | 3296 | 590
3/6/2020   18:00 | ITA | 3916 | 620
3/7/2020 18:00 | ITA | 5061 | 1145
3/8/2020   18:00 | ITA | 6387 | 1326
3/9/2020 18:00 | ITA | 7985 | 1598
3/10/2020   18:00 | ITA | 8514 | 529
3/11/2020 17:00 | ITA | 10590 | 2076
3/12/2020   17:00 | ITA | 12839 | 2249
3/13/2020 17:00 | ITA | 14955 | 2116
3/14/2020   17:00 | ITA | 17750 | 2795

**Comment by SimoneTinella** [comment]
Ciao @umbros, ciò significa che vengono implicitamente sottratti i 'nuovi guariti' e 'nuovi deceduti' nel calcolo del parametro, derivanti dalle ospedalizzazioni e iso. domiciliari.

Ti ringrazio, il fatto che si parlasse di nuovi positivi mi ha tratto in inganno.
