### ISSUE TITLE
Dashboard  e analisi dei dati  - Google Cloud Data Studio Report Ready 

### ISSUE THREAD

**Issue by MauroCapolino** [pcm-dpc/COVID-19#183]
salve viso che il portale della protezione civile non da la possibilita di visualizzare e plottare i dati per regione combinando diversi dati ho creato un database su google cloud e dat studio che e' facilmente utilizzabile da chiunche (aggiornato in base ai vostri dati di regione)
credo che si dovrebbe mettere in linea qualcosa di 
simile per tutti. lo aggiornero ogni giorno

https://datastudio.google.com/u/0/reporting/9ce371f1-62fa-4f2e-8d3c-da4d6dff967b/page/K1YIB?s=ju3MdHn6XEo

**Comment by umbros** [comment]
Ciao @MauroCapolino grazie per il tuo contributo, la dashboard da noi rilasciata ha una funzione informativa.
