### ISSUE TITLE
Dati regionali troppo simili

### ISSUE THREAD

**Issue by vlavorini** [pcm-dpc/COVID-19#184]
**Tipo di richiesta**: richiesta di informazione 

## Interesse pubblico

Buonasera, sto analizzando il `totale_casi` per regione, ed in particolare la differenza tra un giorno ed il precedente.

Stranamente, l'andamento di tali differenziali è praticamente uguale in quasi tutte le regioni.

La cosa appare estremamente strana: sopratutto se consideriamo che si presenta anche in regioni piccole del Sud, come la Basilicata.

In allegato i plot di quattro regioni
![grad_basilicata](https://user-images.githubusercontent.com/8724860/76690846-b349f800-6644-11ea-8ffb-7762d08ac64e.png)
![grad_piemonte](https://user-images.githubusercontent.com/8724860/76690847-b47b2500-6644-11ea-9fa4-5d450179c1aa.png)
![grad_tosc](https://user-images.githubusercontent.com/8724860/76690848-b513bb80-6644-11ea-8b93-cfe1dbf3f885.png)

**Comment by umbros** [comment]
Ciao @vlavorini sono i dati forniti dalle stesse Regioni per conto del Ministero della Salute.
