### ISSUE TITLE
Abilitazione CORS

### ISSUE THREAD

**Issue by cesarecaoduro** [pcm-dpc/COVID-19#185]
Salve, continuo ad ottenere errore CORS nella mia applicazione. È possibile da parte vostra attivare il cross origin?
Grazie

**Comment by Eomm** [comment]
Non ci sono web server in questo repository che ti possono ritornare tali header, ma solo github che è già aperto:

```
curl https://raw.githubusercontent.com/pcm-dpc/COVID-19/master/dati-json/dpc-covid19-ita-andamento-nazionale.json -v
```

Ti mostrerà:

>  Access-Control-Allow-Origin: *

Ecco un esempio di come puoi recuperare i dati ed usarli:

```
<!DOCTYPE html>
<html>

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>JSON Test</title>
</head>

<body>
    <div id="myData"></div>
    <script>
        fetch('https://raw.githubusercontent.com/pcm-dpc/COVID-19/master/dati-json/dpc-covid19-ita-andamento-nazionale.json')
            .then(function (response) {
                return response.json();
            })
            .then(function (data) {
                appendData(data);
            })
            .catch(function (err) {
                console.log('error: ' + err);
            });

        function appendData(data) {
            var mainContainer = document.getElementById("myData");
            for (var i = 0; i < data.length; i++) {
                var div = document.createElement("div");
                div.innerHTML = 'terapia_intensiva: ' + data[i].terapia_intensiva;
                mainContainer.appendChild(div);
            }
        }
    </script>
</body>

</html>
```

Ti mostrerà:

![image](https://user-images.githubusercontent.com/11404065/76698254-0782c580-66a1-11ea-8717-e297a94e895a.png)

**Comment by cesarecaoduro** [comment]
Effettivamente mi da questo problema solo quando utilizzo axios. Grazie per la e grazie per il vostro lavoro!

**Comment by Eomm** [comment]
Non faccio parte della protezione civile, sono solo a casa come tutti quanti 😀

Mi associo con un grande GRAZIE a tutti quelli che stanno lavorando per informare e salvare tutti noi!
💪🏻 🟩⬜🟥 💪🏻

**Comment by umbros** [comment]
Grazie per la collaborazione @eomm

**Comment by michelesanges** [comment]
Buonasera,
anche sulla mia applicazione ottengo un errore CORS quando cerca di
collegarsi al file
https://github.com/pcm-dpc/COVID-19/blob/master/aree/geojson/dpc-covid19-ita-aree.geojson
La stessa applicazione non ha nessun problema a prendere i dati da un altro
repository, ad esempio questo:
https://github.com/benbalter/dc-wifi-social/blob/master/bars.geojson

Una differenza che vedo è che sopra la mappa OpenStreetView del secondo
file è presente il pulsante 'Raw', che permette di prelevare il link al
file.
Non vedo questo pulsante per la mappa dpc-covid19-ita-aree.geojson

Grazie.

*Michele Sanges*


Il giorno dom 15 mar 2020 alle ore 12:42 Umberto Rosini <
notifications@github.com> ha scritto:

**Comment by Recursing** [comment]
C'è il pulsante "download" che manda al link: https://github.com/pcm-dpc/COVID-19/raw/master/aree/geojson/dpc-covid19-ita-aree.geojson

**Comment by Eomm** [comment]
Ecco qua:

```
https://raw.githubusercontent.com/pcm-dpc/COVID-19/master/aree/geojson/dpc-covid19-ita-aree.geojson
```

Non c'è il pulsante ma se usi il pattern per il raw dei json, funziona 👍

**Comment by michelesanges** [comment]
Perfetto, funziona. Molte grazie.

*Michele Sanges*


Il giorno dom 15 mar 2020 alle ore 17:40 Manuel Spigolon <
notifications@github.com> ha scritto:
