### ISSUE TITLE
Dato popolazione residente su base provinciale

### ISSUE THREAD

**Issue by lota** [pcm-dpc/COVID-19#186]
Salve,
inserire nel dataset il dato della popolazione residente (ultimo censimento ISTAT) su base provinciale, potrebbe facilitare per la stima della incidenza dei vari valori sulla popolazione totale.

Mi scuso in anticipo se il suggerimento non è pertinente.

grazie
Alessandro

**Comment by umbros** [comment]
Ciao @lota, i dati che eroghiamo sono interoperabili, infatti sia per Regione che per Provincia forniamo anche il codice che può essere utilizzato per collegarlo ad altre basi dati come, appunto, quello della popolazione residente ISTAT.
