### ISSUE TITLE
dati provicia nello stesso formato della regione

### ISSUE THREAD

**Issue by MauroCapolino** [pcm-dpc/COVID-19#187]
salve nei dati delle provicie ci sono solo i casi, e' possibile avere anche gli altri dati come nelle regioni?

**Comment by DocErnesto** [comment]
E' possibile conoscere i dati Comune per Comune inteso come numero di persone residenti contagiate in quel determinato Comune? Mi chiedo inoltre perché non attivare il layer Comune sul WebGis?

**Comment by umbros** [comment]
Ciao Mauro, come già risposto, attualmente per le province gestiamo solo i totale_casi, se aggiungeremo altre informazioni vi aggiorneremo per tempo.
