### ISSUE TITLE
Question about Tamponi

### ISSUE THREAD

**Issue by JiPiBi** [pcm-dpc/COVID-19#188]
**Type of issue**:  richiesta di informazione | richiesta di dati | suggerimento di enhancement (documentazione, label, _etc_)

## Summary

How to understand the values of tamponi 

## Public interest

Buongiorno
I'm not so good in italian to detect if my question was already asked in the past issues
So apologies in advance

There is a great amount of tests = tamponi made  in Italy and it can explain the high number of discovered cases you have , but are the numbers we find in your dataset only 1rst tests on persons or do you cumulate all the tests made , even those made several times on the same people to check if they are no more affected

Thanks in advance

**Comment by umbros** [comment]
Hi @JiPiBi, the number of tests is an indicated number of tests made,1 test does not represent 1 person but 1 person may have made n tests. We report all tests made.
