### ISSUE TITLE
Richiesta dati mortalità per sesso e fascia d'età

### ISSUE THREAD

**Issue by DataScienceWorld** [pcm-dpc/COVID-19#189]
**Tipo di richiesta**:   richiesta di dati
## Riassunto
Sarebbe possibile caricare i dati di mortalità per sesso e fascia d'età? Esistono altri dati dettagliati?

## Interesse pubblico
Qualsiasi altro dettaglio sarebbe utile per le ricerche future

**Comment by umbros** [comment]
Ciao @DataScienceWorld , attualmente gestiamo questi dati e c'è un processo ufficiale di comunicazione, se aggiungeremo dati ne daremo conoscenza.

**Comment by janLuke** [comment]
Se può interessare, ho appena pubblicato una repository con dataset contenenti il numero dei casi totali e morti disaggregati per età e sesso contenuti nei report PDF dell'ISS: https://github.com/janLuke/iccas-dataset

**Comment by danielesalpietro** [comment]
@janLuke , lavoro interessante, pensi di mantenerlo aggiornato ?

**Comment by janLuke** [comment]
@danielesalpietro Se interessa a qualcuno e finché non verrano pubblicati gli stessi dati (o sperabilmente più dettagliati) da fonti ufficiali. Se l'ISS non cambia il formato della tabella, non dovrebbe richiedermi alcuno sforzo o uno sforzo minimo. Posso facilmente automatizzare anche la pubblicazione di un nuovo dataset quando un nuovo bollettino esteso viene pubblicato.

Qualche consiglio su come "pubblicizzarlo"?
