### ISSUE TITLE
suggerimento

### ISSUE THREAD

**Issue by clear2009** [pcm-dpc/COVID-19#19]
Al momento non vedo andamenti temporali che possano dare una idea delle pendenze che nel tempo si sviluppano. Ciò permetterebbe di avere una idea di sintesi sui momenti di flessione dei fenomeni.
Per maggiore completezza, alla maniera dei grafici pivot, sarebbe molto utile avere i suddetti andamenti selezionabili per ciascuna tipologia utile (provincia, regione, guariti, ricoverati, ecc...).

La saluto
Francesco

**Comment by clear2009** [comment]
mi scusi per il testo trasferito in modo non immediatamente comprensibile ma il concetto è deducibile comunque

**Comment by umbros** [comment]
Ciao @clear2009, allo stato attuale dati più dettagliati sono a livello regionale mentre a livello provinciale viene monitorato solo il totale, oltretutto, nei dati per Provincia, c'è un campo per ogni Regione denominato "In fase di definizione/aggiornamento" dove vengono inseriti quei dati in fase di allocazione sulla Provincia corretta.

**Comment by clear2009** [comment]
Buongiorno.  
Ti ringrazio per il ritorno. Sul sito prevedete anche grafici a breve?
(Visto che li stavo monitorando in proprio).
Saluti e buon lavoro 
Francesco 
--
Inviato da Libero Mail per Android Domenica, 08 Marzo 2020, 10:21AM +01:00 da Umberto Rosini  notifications@github.com :
