### ISSUE TITLE
Inserire grafico logaritmico & trend percentuali di incremento

### ISSUE THREAD

**Issue by castafeid** [pcm-dpc/COVID-19#190]
se possibile inserire un grafico logaritmico e una tabella dei trend percentuali giornalieri e settimanali (esempio: +15% in più di contagi rispetto a ieri, +80% in più di guariti rispetto a ieri, etc etc).

Grazie
Ottima Dashboard!

NC

**Comment by umbros** [comment]
Grazie del suggerimento.

**Comment by marcodadamo** [comment]
Ottimo suggerimento, se possibile sia per tutte e tre le componenti (nazionale, regionale, provinciale)

**Comment by amascolo75** [comment]
Salve e grazie per questo importantissimo servizio.
Il trend del delta % giornaliero sarebbe importante per verificare se la curva esponenziale comincia ad abbassarsi. Ad oggi, proiettando i dati dei Positivi, Guariti e Deceduti utilizzando la media dei delta % degli ultimi 5 giorni si arriva a prevedere (per esempio) che il 24 marzo si supererebbero i 100.000 positivi in Italia e il 5 aprile il milione di casi totali... Speriamo quindi che quelle percentuali si abbassino fino ad arrivare a zero e che, un bel giorno, invertano il segno in negativo.
![Immagine](https://user-images.githubusercontent.com/62217647/76709645-b30f3280-6700-11ea-9ded-bd7a2326e994.png)

**Comment by crisidev** [comment]
@castafeid i dati che richiedi sono piu' o meno disponibili in una dashboard alternaltiva: https://covid19italy.crisidev.org/

Piu' info nella issue: https://github.com/pcm-dpc/COVID-19/issues/202

**Comment by amascolo75** [comment]
Grazie mille!

**Comment by andrea-poletti-unibo** [comment]
Ho creato questa visualizzazione interattiva usando Shiny:

https://salazar019.shinyapps.io/COVID-ITA-Explorer/

Se può servire, posso mettere a disposizione il codice (in R)

**Comment by castafeid** [comment]
Grazie a tutti coloro che hanno risposto.
Massima disponibilità e collaborazione da parte di tutti per cercare di costruire un modello previsionale robusto!

Serve anche questo, non per oggi, ma per il domani ed il dopodomani.

NC

**Comment by mauroscianca98** [comment]
Ho realizzato una pagina per la visualizzazione dei dati e alcune statistiche (app android WIP):
[https://cvd19.altervista.org/home.html](url)

**Comment by alldone** [comment]
Ciao, 
ho realizzato una pagina (che è anche PWA) per consultazione su mappa ( per regione al momento ) con 
animazione dell'evoluzione della epidemia e qualche statistica ( stats )

https://www.alldone.cloud/

se serve il codice,... chiedete pure

**Comment by umbros** [comment]
Grazie a tutti per la collaborazione.
