### ISSUE TITLE
Comuni - Covid-19

### ISSUE THREAD

**Issue by DocErnesto** [pcm-dpc/COVID-19#191]
**Tipo di richiesta**:  richiesta di informazione | richiesta di dati | suggerimento di miglioramento (documentazione, label, _ecc_) | relativo alla pagina grafica

**Comment by DocErnesto** [comment]
Attivate la visualizzazione in Web Gis per Covid-19 Comune per Comune inteso come numero di persone residenti contagiate in quel determinato Comune

**Comment by umbros** [comment]
@DocErnesto allo stato attuale non gestiamo il dato dei comuni, eventuali modifiche le comunicheremo per tempo e aggiorneremo ogni visualizzazione.

**Comment by bitliner** [comment]
Pianificate di aggiungere il dato per comune? In caso, quando?

Penso sia un dato molto importante per informare e gestire meglio la diffusione del virus
