### ISSUE TITLE
Chiarimento su numero dimessi_guariti

### ISSUE THREAD

**Issue by picazio** [pcm-dpc/COVID-19#193]
**Tipo di richiesta**:  richiesta di informazione | richiesta di dati | suggerimento di miglioramento (documentazione, label, _ecc_) 

## Riassunto

Per avere il quadro completo della situazione, sarebbe utile distinguere il numero di pazienti dimessi dall'ospedale, quindi non più ospedalizzati e quelli guariti. Al momento riportate solo la colonna: dimessi_guariti, ma immagino che essa contenga la somma di queste due categorie. Se avete a disposizione questi dati, potreste condividerli?

## Interesse pubblico

Conoscere il numero di pazienti effettivamente dimessi dall'ospedale e quelli guariti, permette di completare l'informazione dei pazienti ospedalizzati e quindi di poterne valutare l'andamento in maniera corretta.

**Comment by lukwe** [comment]
Sì, sembra mancare la colonna 'guariti' per i casi di isolamento_domiciliare !

**Comment by pierluigicara** [comment]
Grazie della segnalazione ma al momento il dato che ci viene trasmesso e per il quale c'è l'autorizzazione per la pubblicazione riguarda solo "DIMESSI/GUARITI".

**Comment by picazio** [comment]
Quindi la colonna contiene solo i guariti dimessi dall'ospedale?

Grazie mille in ogni caso per l'ottimo e tempestivo lavoro che fate.

Cordialmente,
Attilio

**Comment by lukwe** [comment]
Ok grazie, ma rispetto ad altri paesi il rapporto decessi/Casi_risolti è alle stelle (44% vs 8%), credo proprio per scelte metodologiche diverse in questi conteggi. 

Possibile non vi siano precise modalità condivise e documentate da seguire dagli enti Sanitari dei vari Stati ?!
