### ISSUE TITLE
Dati nuovi casi Lombardia 10.03 errati

### ISSUE THREAD

**Issue by piersoft** [pcm-dpc/COVID-19#194]
Tipo di issue:

- [ X] Dati mancanti o errati 
- [ ] Errore nella documentazione 
- [ ] Errore or mancanza nella dashboard 
- [ ] Problemi di visualizzazione nella dashboard 

- Regione: Lombardia
- Provincia: 

## Riassunto
su questo dataset , il giorno 10.03 risultano -63 casi per la Lombardia come nuove casi giornalieri. E' stato un allineamento con i dati precedenti o è un errore non voluto?

https://github.com/pcm-dpc/COVID-19/blob/master/dati-regioni/dpc-covid19-ita-regioni-20200310.csv
**Attesa:**

correzione o spiegazione

**Attuale:**

**Comment by Recursing** [comment]
Ci sono altre issue aperte al riguardo, sicuramente #97 e #127

Val la pena mettere espendere le note nel readme che segnalano i dati inesatti?

**Comment by mydozer** [comment]
Ciao @piersoft la spiegazione è stata data qui #93. Ti chiedere i di chiudere la segnalazione e verificare eventualmente tutte le precedenti aperte in merito. Grazie!

**Comment by umbros** [comment]
Ciao @piersoft,
il dato del 09/03 riporta 4490 casi, il 10/03 sono 4427 che per differenza fanno -63, come riportato sia sulla dashboard che sul README si tratta di una comunicazione dati parziale, infatti il giorno 11/03 il valore si è impennato a 5763 che ha fatto segnare nuovi giornalieri 1336. Essendo il processo di comunicazione ufficiale non possiamo spostare dati da un giorno a l'altro pertanto la scelta è stata quella di comunicare eventuali dati non pervenuti o parziali e per questo da domani ci sarà un campo "note" in italiano e in inglese dove riporteremo per ogni riga dato eventuali informazioni sui dati. Grazie @mydozer per il supporto :) e grazie a tutti per l'attenzione e la collaborazione.
