### ISSUE TITLE
Riga vuota in coda nel file dpc-covid19-ita-andamento-nazionale.csv

### ISSUE THREAD

**Issue by Nidroide** [pcm-dpc/COVID-19#195]
Salve.

Il file in oggetto ha un riga vuota in coda.
Sebbene questo non sia un problema grave suggerisco in generale di rimuoverlo per non mandare in errore alcuni csv parser poco tolleranti o che per default non sono configurati per ignorare righe vuote.

Complimenti per l'ottimo lavoro!

**Comment by andreapede** [comment]
Confermo.

**Comment by umbros** [comment]
Corretto, grazie
