### ISSUE TITLE
Errore in province 

### ISSUE THREAD

**Issue by Tusamarco** [pcm-dpc/COVID-19#196]
Tipo di issue:

- [ x] Dati mancanti o errati dpc-covid19-ita-province.csv
- [ ] Errore nella documentazione 
- [ ] Errore or mancanza nella dashboard 
- [ ] Problemi di visualizzazione nella dashboard 

- Regione:
- Provincia: 

## Riassunto
In linea 2150 manca uno 0 (zero), o altro numero dopo la virgola 

**Attesa:**

N/A

**Attuale:** N/A

**Comment by umbros** [comment]
Ciao @Tusamarco,
errore riscontrato alla riga 2151, grazie per la segnalazione.
