### ISSUE TITLE
Migliorare la legenda dei dati

### ISSUE THREAD

**Issue by Nidroide** [pcm-dpc/COVID-19#197]
Noto che ci sono molte richieste di chiarimento sull'interpretazione dei dati.
Converrebbe pertanto migliorare la legenda nel file readme anche perché i nomi scelti a volte sono controintuitivi.

Il prefisso "totale_", ad esempio, in alcuni casi viene usato per indicare un valore cumulativo, in altri un valore attuale (es. totale_ospedalizzati che da issue #124 indica il valore degli ospedalizzati attuali).

**Comment by umbros** [comment]
Ciao,
il miglioramento del README è un'attività su cui stiamo lavorando.
una miglioria che si potrà portare è quella di mettere al fianco della voce totale_ totale_attualmente... ma penso, per non creare malfunzionamenti tra chi fa ingestione di questi dati, che sia meglio, come in parte è stato fatto specificare meglio il valore dato.

Grazie
