### ISSUE TITLE
Incongruenza totale_casi in provincia di Benevento

### ISSUE THREAD

**Issue by Nidroide** [pcm-dpc/COVID-19#198]
Salve,
da quanto ho capito totale_casi è un cumulativo, pertanto dovrebbe essere monotono crescente.
Relativamente alla provincia di Benevento in data 11/03/2020 scendono da 4 a 2.
E' possibile sapere se si tratta di un errore o di una riclassificazione (su base geografica, su esiti di tamponi errati, errori materiali, etc. etc.)?
Eventualmente aggiungere in readme l'indicazione dell'anomalia (come già visto per i parziali in Lombardia) e/o in legenda indicando che totale_casi puo' subire variazioni negative ed includendone le motivazioni (vedi issue #197).

Grazie

**Comment by umbros** [comment]
Buonasera,
il dato a livello provinciale può avere ribassi per varie ragioni, errato calcolo, perfezionamento dell'anagrafica paziente. Dobbiamo sempre tenere conto che è una situazione d'emergenza e dei dati possono subire delle variazioni da un giorno ad un altro, non è una regola ma può succedere.
