### ISSUE TITLE
Dato provincia di Viterbo

### ISSUE THREAD

**Issue by ggraziotti** [pcm-dpc/COVID-19#199]
- Regione: Lazio
- Provincia:  Viterbo

## Riassunto

Dal comunicato stampa giornaliero della Asl di Viterbo il dato degli infetti ad oggi è 31, come mai il dato da voi pubblicato è 15. Come mai questa discrepanza ?

**Attesa:**

**Attuale:**

**Comment by umbros** [comment]
La Regione Lazio ha comunicato il dato che noi abbiamo messo, eventuali comunicazioni delle ASL possono essere successive la comunicazione alla Regione e quindi al Ministero della Salute e quindi a noi, come segnalato il nostro dato è lavorato alle ore 17:00 che vuol dire un'informazione fornita almeno un'ora prima alle regioni.
