### ISSUE TITLE
Riferimenti canale ufficiale

### ISSUE THREAD

**Issue by mydozer** [pcm-dpc/COVID-19#20]
Ciao,
sarebbe possibile avere conferma nella pagina iniziale del fatto che il repository sia il canale uffciale/autorizzato di pubblicaizone dei dati della protezione civile? I dati in origine sono disponibili in pdf e poi immessi MANUALMNTE in uno dei formati che si prestano all'elaborazione?

Grazie!

**Comment by umbros** [comment]
Ciao @mydozer come puoi vedere dall'immagine
![immagine](https://user-images.githubusercontent.com/4085151/76159898-4e167400-6125-11ea-9f56-3e7ce60c3f15.png)
questo account github è quello ufficiale del Dipartimento della Protezione Civile, inizialmente i dati sono stati ricavati dal pdf adesso stiamo proceduralizzando l'attività e i dati saranno "lavorati" da un unico sistema che genererà sia i vari formati aperti che il pdf che diventerà pdf/a.
