### ISSUE TITLE
Età delle persone infette

### ISSUE THREAD

**Issue by vincenzodesanctis** [pcm-dpc/COVID-19#200]
Forse per la privacy non è possibile, ma l'ideale sarebbe aggiungere il campo "media età" per regione e per provincia.

**Comment by MarcoGermani** [comment]
No, la privacy non c'entra. Non li pubblicano e basta

**Comment by umbros** [comment]
Buongiorno @vincenzodesanctis, allo stato attuale questi dati non vegono gestiti, ogni modifica verrà opportunamente promossa.

**Comment by cryptid11** [comment]
è un'interessante vedere come decisioni che riguardano la vita di tutti vengano prese su dati segreti, c'è davvero da chiedersi cosa sia lo stato di diritto quando le decisioni per milioni di individui costruite su modelli segreti e dati segreti non possono nemmeno volendo essere discusse dal pubblico. a me sembra uno stato di cose penose non degno di un paese che si voglia definire democratico.
