### ISSUE TITLE
Dashboard alternativa

### ISSUE THREAD

**Issue by crisidev** [pcm-dpc/COVID-19#202]
**Tipo di richiesta**:  richiesta di informazione

## Riassunto

Dashboard alternativa che utilizza i dati di questo repo.

## Interesse pubblico

Salve,
abbiamo creato una dashboard alternativa a quella della protezione cicile, con un po' piu' di interattivita' per l'ultente: https://covid19italy.crisidev.org/

L'applicativo e' in Python e dispone di docker image per l'ultizzo locale. Se siete interessati, il codice puo' essere trovato qui: https://github.com/tommasobonomo/covid19-italy

**Comment by downFast** [comment]
Ciao
grazie per questo.

Che formula avete usato per lineare e logaritmica?

Grazie

**Comment by crisidev** [comment]
Viene calcolata automaticamente da [Altair](https://altair-viz.github.io/) utilizzando un dataframe Pandas dove e' caricata la basi di dati. Altair permette di specificare vari tipi di scale. Io ho fatto solo varie modifiche al sito e supporto l'hosting via HTTPS, l'idea iniziale e' di @tommasobonomo, quindi chiamo in causa lui per maggiori info.

**Comment by downFast** [comment]
ti scrivo un'email e vediamo come aggiungerci su skype cosi ti mostro una cosa e vediamo se riusciamo ad integrare?

**Comment by crisidev** [comment]
No problem!

**Comment by diego-sf** [comment]
Osservazione:
mentre il grafico per il fattore di crescita a livello nazionale pare corretto (i.e. valori in linea con la formula), il grafico per regione pare mostrare valori altamente errati (fattori di crescita nelle decine o centinaia per la Lombardia), e per di più variabili a seconda di che regioni si includono nel grafico stesso. Immagino sia un problema di organizzazione/allineamento dati nel breakdown.

**Comment by tommasobonomo** [comment]
Buongiorno!
Sono l'autore originale della dashboard, dovrei aver corretto l'errore nella visualizzazione del growth factor per le varie regioni. Era in effetti un problema di allineamento dati nel breakdown.
Rimango a disposizione per l'integrazione della dashboard, informazioni o domande :)

**Comment by tommasobonomo** [comment]
PS dato che il mirror HTTPS sembra essere down, vi rimando al mio deployment su Heroku se volete vedere i più recenti cambiamenti: [covid19italy](covid19italy.herokuapp.com)

**Comment by crisidev** [comment]
Il mirror https e' di nuovo up :) Grazie tommaso per il fix sul breakdown.

**Comment by lucianolorenti** [comment]
In case someone is interested this is another [alternative dashboard ](https://itacovid-19.herokuapp.com/ ) with the data provided by  pcm-dpc

**Comment by umbros** [comment]
Grazie mille a tutti per la collaborazione. @crisidev @downFast @tommasobonomo @lucianolorenti
