### ISSUE TITLE
Nuovo approccio (web app + app)

### ISSUE THREAD

**Issue by alexodus** [pcm-dpc/COVID-19#203]
**Tipo di richiesta**:  suggerimento di miglioramento (documentazione, label, _ecc_)

## Riassunto

Nei giorni scorsi ho realizzato un'app in flutter per poter navigare sui dati da voi forniti.  Per ovvi motivi quest'app non potrà mai essere accettata dagli store di apple e google, per delle chiare policies. Ho quindi trasformato l'app in una webapp.

https://covid-19-ita.web.app/

I dati vengono presi dai vostri open-data e messi nel cloud di firestore, tramite semplici script python.
L'app è essenziale ed in divenire. Mi piacerebbe "donarla" (compresa di codici) alla Protezione Civile, se ne avesse interesse.
Usare gli strumenti di firebase consente a questa soluzione di scalare a milioni di visitatori senza alcun problema (ovviamente tutto questo ha un costo di traffico dati e uso database, ma sono piuttosto bassi).

## Interesse pubblico

L'uso della app e della webapp potrebbe consentire alle persone una navigazione dei dati più agevole. L'app e la webapp potrebbero essere ampliate per funzionalità in maniera che solo flutter consente di fare.

**Comment by umbros** [comment]
Grazie della collaborazione @alexodus
