### ISSUE TITLE
Formato data nei dati per provincia

### ISSUE THREAD

**Issue by dawe** [pcm-dpc/COVID-19#205]
Tipo di issue:

- [X] Dati mancanti o errati `dati-province/dpc-covid19-ita-province.csv`
- [ ] Errore nella documentazione 
- [ ] Errore or mancanza nella dashboard 
- [ ] Problemi di visualizzazione nella dashboard 

- Regione: 
- Provincia: 

## Riassunto

Apparentemente dal 13/03 la data è riportata in formato YYYY-MM-DD, fino al 12/03 è in formato YYYY-DD-MM, il che comporta qualche problema nel parsing dei dati

d

**Comment by MarcoGermani** [comment]
Il Problema è un altro:
Occupandomi di statistica, e non fidandomi delle svariate proiezioni ed analisi citate da Tv e giornali, ho cercato di analizzare per mio conto i dati ufficiali pubblicati dal Sig. Umberto Rosini, tuttavia, volontariamente o per errore, i dati pubblicati sono ERRATI !
Faccio un solo esempio relativo al totale dei tamponi effettuati nella Regione Lombardia dal 24/02 al 25/02, riportato pari a 3.700, mentre il totale dal 24/02 al 26/02 è riportato pari a 3.208: cosa impossibile essendo un valore crescente giorno dopo giorno.
Questo insieme ad altri strafalcioni statistici (numeri negativi il Liguria e Sicilia), rende impossibile un’analisi seria atta a capire, almeno a livello statistico, come procede la diffusione del virus.
Ho cercato di contattare Umberto Rosini presso la Protezione Civile dove lavora al numero 06/68202926, il Ministero della Sanità, la Presidenza del Consiglio dei Ministri e la Protezione civile per avere chiarimenti, ricevendo solo non so, non dipende da noi, compili un form, tutto senza alcun esito.
Chiedo pertanto a chi sta lavorando sui dati, su quali dati sta lavorando e se è mai possibile che organi autorevoli diffondano dati errati o fuorvianti.
Spero che tutto sia fatto non volontariamente e che i dati vengano rettificati al più presto per permettere alle umili pecorelle del gregge di essere almeno informate correttamente senza essere condotte inconsapevolmente dove il politico di turno desidera.

**Comment by riccardofrosini** [comment]
Ho appena fatto checkout della repository. I dati sembrano corretti al moment per il Date format.

**Comment by MarcoGermani** [comment]
Ci sono errori forse di digitazione…
Guarda il file Excel che ho realizzato scaricandolo da: www.rightfood.it\corona.zip e se vuoi chiamami 3483325064

**Comment by riccardofrosini** [comment]
Ho scaricato i dati che ha mandato. Ho controllato la Lombardia e sembrerebbe essere corretta. Mi puo' direzionare ad esempi di errori che ha trovato.

**Comment by MarcoGermani** [comment]
Gentile Frosini,
non ho idea di cosa lei si occupa ma in Lombardia la serie dei dati relativi al totale dei tamponi fatti DEVE essere una serie crescente.
Invece riportano che il totale dei tamponi dal 24/02 al 25/02 è 3700, mentre il 26/02 il totale dei tamponi fatti diventa 3208 … cosa impossibile se non per errore.
In Liguria, Sicilia inoltre compaiono inspiegabilmente dati NEGATIVI !?!

**Comment by riccardofrosini** [comment]
Per quanto riguarda la Lombardia ha ragione il numero dovrebbe crescere. Non so perche' diminuiscono probabilmente i dati ad inizio pandemia sono poco accurati sopratutto per quanto riguarda il numero di tamponi e possibilmente falsi positivi. Il che spiegherebbe i numeri negativi di Liguria e Sicilia.

Lavoro tutti i giorni con dati "sporchi" bisogna fare quel che si puo'.

**Comment by umbros** [comment]
@dawe non mi risulta questo problema. Se mi segnali la riga e il file facciamo subito un controllo. @MarcoGermani, premeto che i dati pubblicati seguono un processo formale di comunicazione delle Regioni tramite il Ministero della Salute a noi del Dipartimento della Protezione Civile, pertanto alcune modifiche o segni negativi su alcuni giorni sono da interpretarsi come aggiustamenti o perfezionamenti del dato sempre fornito dalle Regioni.
