### ISSUE TITLE
FAKE NEWS MINISTERIALI O INCOMPETENZA DEI COLLABORATORI ?

### ISSUE THREAD

**Issue by MarcoGermani** [pcm-dpc/COVID-19#206]
Occupandomi di statistica, e non fidandomi delle svariate proiezioni ed analisi citate da Tv e giornali, ho cercato di analizzare per mio conto i dati ufficiali pubblicati dal Sig. Umberto Rosini, tuttavia, volontariamente o per errore, i dati pubblicati sono ERRATI !
Faccio un solo esempio relativo al totale dei tamponi effettuati nella Regione Lombardia dal 24/02 al 25/02, riportato pari a 3.700, mentre il totale dal 24/02 al 26/02 è riportato pari a 3.208: cosa impossibile essendo un valore crescente giorno dopo giorno.
Questo insieme ad altri strafalcioni statistici (numeri negativi il Liguria e Sicilia), rende impossibile un’analisi seria atta a capire, almeno a livello statistico, come procede la diffusione del virus.
Ho cercato di contattare Umberto Rosini presso la Protezione Civile dove lavora al numero 06/68202926, il Ministero della Sanità, la Presidenza del Consiglio dei Ministri e la Protezione civile per avere chiarimenti, ricevendo solo non so, non dipende da noi, compili un form, tutto senza alcun esito.
Chiedo pertanto a chi sta lavorando sui dati, su quali dati sta lavorando e se è mai possibile che organi autorevoli diffondano dati errati o fuorvianti.
Spero che tutto sia fatto non volontariamente e che i dati vengano rettificati al più presto per permettere alle umili pecorelle del gregge di essere almeno informate correttamente senza essere condotte inconsapevolmente dove il politico di turno desidera.
Il link ai dati (raggiungibile dal sito del Ministero e da quello della protezione Civile) dove verificare il tutto è:
https://github.com/pcm-dpc/COVID-19/blob/master/dati-regioni/dpc-covid19-ita-regioni.csv
Rimango in attesa degli sviluppi e di link verso fonti ufficiali corrette.
**Grazie**
[http:\\www.rightfood.it\fake.jpg](url)

**Comment by liuzhongwei** [comment]
Auguro agli italiani la vittoria su COVID-19 in anticipo


translate by Google, from China














At 2020-03-16 16:19:32, "MarcoGermani" <notifications@github.com> wrote:

Occupandomi di statistica, e non fidandomi delle svariate proiezioni ed analisi citate da Tv e giornali, ho cercato di analizzare per mio conto i dati ufficiali pubblicati dal Sig. Umberto Rosini, tuttavia, volontariamente o per errore, i dati pubblicati sono ERRATI !
Faccio un solo esempio relativo al totale dei tamponi effettuati nella Regione Lombardia dal 24/02 al 25/02, riportato pari a 3.700, mentre il totale dal 24/02 al 26/02 è riportato pari a 3.208: cosa impossibile essendo un valore crescente giorno dopo giorno.
Questo insieme ad altri strafalcioni statistici (numeri negativi il Liguria e Sicilia), rende impossibile un’analisi seria atta a capire, almeno a livello statistico, come procede la diffusione del virus.
Ho cercato di contattare Umberto Rosini presso la Protezione Civile dove lavora al numero 06/68202926, il Ministero della Sanità, la Presidenza del Consiglio dei Ministri e la Protezione civile per avere chiarimenti, ricevendo solo non so, non dipende da noi, compili un form, tutto senza alcun esito.
Chiedo pertanto a chi sta lavorando sui dati, su quali dati sta lavorando e se è mai possibile che organi autorevoli diffondano dati errati o fuorvianti.
Spero che tutto sia fatto non volontariamente e che i dati vengano rettificati al più presto per permettere alle umili pecorelle del gregge di essere almeno informate correttamente senza essere condotte inconsapevolmente dove il politico di turno desidera.
Il link ai dati (raggiungibile dal sito del Ministero e da quello della protezione Civile) dove verificare il tutto è:
https://github.com/pcm-dpc/COVID-19/blob/master/dati-regioni/dpc-covid19-ita-regioni.csv
Rimango in attesa degli sviluppi e di link verso fonti ufficiali corrette.
Grazie
http:\www.rightfood.it\fake.jpg

**Comment by riccardofrosini** [comment]
I dati sembrano per lo piu' corretti. Il numero di tamponi sono i totali fatti fino ad ora non quanti sono stati fatti giornalmente. Purtroppo a volte i dati potrebbero non essere completi specialmente verso l'inizio dell'emergenza.

**Comment by RomanTomz** [comment]
@MarcoGermani Liguria e Sicilia non presentano numeri negativi sui tamponi.


![image](https://user-images.githubusercontent.com/21104666/76744000-74fb2880-676b-11ea-8e54-c1614cde0423.png)

**Comment by MarcoGermani** [comment]
Mai detto che in Sicilia e Liguria ci sono dati negativi! Sono nei nuovi Positivi

**Comment by RomanTomz** [comment]
nuovi_attualmente_positivi riporta  la differenza tra i totale_attualmente_positivi del giorno corrente con i totale_attualmente_positivi del giorno precedente come gia' detto in #192. E' dunque possibile e coerente che il dato sia negativo.

**Comment by crisidev** [comment]
Temo il signor Margo Germani stia semplicemente facendo un po' di SPAM e trolling in generale.. E' joinato su github 2 ore fa.. Io lockerei il thread..

**Comment by MarcoGermani** [comment]
Gentile crisidev, non credo possa permettersi di darmi del Troll!
Il sospetto non sono io ma chi pubblica dati errati.
Vada a vedere i dati del totale dei tamponi fatti in Lombardia dal 24/2 al 25/02 (3.700) e mi spieghi (nessuno lo ha ancora fatto) come mai il totale dal 24/02 al 26/02 è sceso a 3.208.

**Comment by MarcoGermani** [comment]
Gentile Di Marcello,
è stato un mio errore derivante dal fatto che normalmente nei dati grezzi non dovrebbero essere presenti operazioni su di essi.
Trovo comunque inutile la colonna dei nuovi positivi per giorno.
Grazie comunque

**Comment by mmariotti** [comment]
@MarcoGermani è vero, qualche imprecisione c'è, in particolare nelle misure dei tamponi (l'ultima in Valle d'Aosta, cfr. 14-mar: 231 e 15-mar: 230), ma definirle "fake news" o "incompetenze" mi pare esagerato...
Soprattutto in riferimento al periodo di Febbraio: con tutto il caos che può esserci stato nel periodo iniziale, sembra del tutto normale che qualche numero sia impreciso, e che venga corretto dopo qualche giorno.
Anzi, rispetto ai dati forniti dagli altri paesi, questi Italiani sono oro colato.

**Comment by zakkos** [comment]
Questo modo fuorviante di riportare i dati è stato segnalato anche da worldometers.info che pur prendendo i dati ufficialmente da questa repo ha dovuto segnalare l'incongruenza nel modo di riportare i dati (la differenza fra gli attualmente positivi risulta più bassa del numero di nuovi positivi facendo sembrare l'emergenza meno grave) rispetto alle linee guida del WHO. L'errore del sig Germani è il non aver seguito gli altri thread dove è già stato trattato il problema. Ugualmente cambiare ORA il modo di riportare i dati non sarebbe positivo.

**Comment by MarcoGermani** [comment]
Gentile Mariotti,
è ovvio che in un flusso di dati non normalizzato ci possa essere dello sporco, ma mi sarei aspettato che i dati venissero rettificati al fine di poter aumentare l'attendibilità di qualsiasi analisi.
Il problema è che, per i soliti centri di potere (leggi orticelli), in Italia spesso ognuno fa come vuole e non vuole uniformarsi a regole comuni

**Comment by MarcoGermani** [comment]
Gentile

**Comment by MarcoGermani** [comment]
Gentile Zaccos,
allora non sono un TROLL !!
Ho scritto su questo blog, dopo aver tentato di parlare con tutti gli enti coinvolti, e dal ISS ho avuto conferma che i dati sono quelli che sono ed anche loro sono in difficoltà nel creare modelli con un'attendibilità elevata a causa dei dati sporchi.

**Comment by mmariotti** [comment]
@zakkos quando si parla di dati numerici il "facendo sembrare" non ha alcun senso... tanto più che il dato degli "attualmente positivi" è un derivato. Inoltre @MarcoGermani parla del numero totale dei tamponi, un dato primitivo (e non derivato) che dovrebbe essere monotono crescente per sua natura.

@MarcoGermani è una questione di scelta. In ambito statistico è "meglio" rettificare i dati pregressi, in qualche modo "modificando il passato".
In ambito informatico, invece, è "meglio" andare a impostare un nuovo valore che che tenga conto della correzione nel nuovo "batch".
Immagina se tutti, me compreso, che hanno strutturato un DB a supporto dei dati dovessero andare a costruire la logica di individuazione e applicazione delle rettifiche... così è un po' meno preciso ma estremamente più semplice da gestire.

**Comment by downFast** [comment]
> @MarcoGermani è vero, qualche imprecisione c'è, in particolare nelle misure dei tamponi (l'ultima in Valle d'Aosta, cfr. 14-mar: 231 e 15-mar: 230), ma definirle "fake news" o "incompetenze" mi pare esagerato...
> Soprattutto in riferimento al periodo di Febbraio: con tutto il caos che può esserci stato nel periodo iniziale, sembra del tutto normale che qualche numero sia impreciso, e che venga corretto dopo qualche giorno.
> Anzi, rispetto ai dati forniti dagli altri paesi, questi Italiani sono oro colato.

Confermo, se riuscissimo a standardizzare bene i nostri, faremo scuola per gli altri paesi e potremmo fare analisi globali, per questo caos e per i futuri di ogni settore.

**Comment by umbros** [comment]
Buongiorno a tutti, premetto che i dati pubblicati sono dati conferiti al Dipartimento della Protezione Civile dalle Regioni per il tramite del Ministero della Salute. Eventuali problemi tra un giorno e un altro dovuto a problemi di comunicazione, mancanza di dati o non conferimento dei dati saranno definiti in un apposito campo che implementeremo nei prossimi giorni (un campo note). Richiamo tutti al rispetto e ad avere toni cordiali e di assoluta collaborazione. Questo repository dati è fatto proprio per non creare fake news.

**Comment by zakkos** [comment]
@mmariotti i dati sono dati ma ovviamente quali dati e come vengono raccolti e presentati è una scelta umana e quindi soggetta a bias, il problema non è il numero in se ma l'etichetta e la scelta di riportare QUEL dato. Questa cosa è stata rilevata anche in altre issue. è un'anomalia il modo in cui viene registrato il dato rispetto al resto del mondo dove viene riportato il numero di nuovi casi punto. Il problema sorge nel momento in cui i media consumano questi dati in maniera acritica ma in questo caso l'ambiguità nasce alla fonte, concordo con @downFast sulla standardizzazione
