### ISSUE TITLE
Overwriting existing files 

### ISSUE THREAD

**Issue by trolley813** [pcm-dpc/COVID-19#207]
**Type of issue**: suggerimento di enhancement 

## Summary
(Sorry, I don't speak Italian (being native Russian speaker) so I will use English.)
The data per each day are stored in separate files, and every day a _new_ file is created, instead of rewriting existing file upon updating. Git stores full history, so if you want to see a version of a file by any date, you can do it by checking out the desired commit.  Also, some files like CSV tables are already filled with all previous data, so storing multiple copies of them per each day is useless.

## Public interest
This can (1) significantly reduce the repository size (by storing each file once) and (2) make the work with the repository more comfortable by maintaining a permalink to each file, which would always point to the latest version (this is especially good for automated data collection, e.g. for online counters).

**Comment by umbros** [comment]
Hi @trolley813, thanks gor your suggestion, I agree with you but some people find more confortable to work with separate file. We are improving our dataset and we will take in consideration your suggestion. Thank you

**Comment by downFast** [comment]
> **Type of issue**: suggerimento di enhancement
> 
> ## Summary
> (Sorry, I don't speak Italian (being native Russian speaker) so I will use English.)
> The data per each day are stored in separate files, and every day a _new_ file is created, instead of rewriting existing file upon updating. Git stores full history, so if you want to see a version of a file by any date, you can do it by checking out the desired commit. Also, some files like CSV tables are already filled with all previous data, so storing multiple copies of them per each day is useless.
> 
> ## Public interest
> This can (1) significantly reduce the repository size (by storing each file once) and (2) make the work with the repository more comfortable by maintaining a permalink to each file, which would always point to the latest version (this is especially good for automated data collection, e.g. for online counters).

You could make a call to github, download it to your server and then each day make a call and do a diff check to update whatever has changed.

**Comment by AvverbioPronome** [comment]
@trolley813 just use `dpc-covid19-ita-regioni.(csv|json)` only instead of `dpc-covid19-ita-regioni-yyyymmdd.(csv|json)`

it looks like a single file with all data, as if it was the result of `ls | grep "dpc-covid19-ita-regioni-[0-9]*.csv" | xargs cat > dpc-covid19-ita-regioni-prova.csv` (don't use this command, I tried it to check the diff, and you will get duplicated headers.)
