### ISSUE TITLE
Please provide a short README in english

### ISSUE THREAD

**Issue by OzieGamma** [pcm-dpc/COVID-19#208]
**Type of issue**: suggerimento di enhancement (documentazione, label, _etc_)

## Summary

Please provide a short paragraph in English at the top of the readme. It could be as simple as:

> This repository contains official data on COVID-19 case from the Italian Civil Protection.
> Most of the documentation here-under is in Italian but we welcome contributed translations.
> 
> In the meanwhile we recommend you use online translation tools such as [Google Translate](https://translate.google.co.uk/) or [Bing Microsoft Translator](https://www.bing.com/translator).

## Public interest
Broader audience, which is crucial for communities who will unfortunately follow in Italy's footsteps.

**Comment by umbros** [comment]
Hi @OzieGamma we are editing our README and we will publish a new one with english translation tonight.
