### ISSUE TITLE
Aggiornamento maggiore velocità

### ISSUE THREAD

**Issue by piersoft** [pcm-dpc/COVID-19#21]
Complimenti per l'iniziativa. Molto completa in ogni fase, dalla divulgazione, alla mappa alla strutturazione. 

Come miglioramento suggerisco:
1) tempi di aggiornamento. Inserire i dati quando c'è la conferenza stampa delle 18 sarebbe ideale rispetto all'aggiornamento dopo le 21
2) E' prevista la strutturazione di API per fare query temporali o spaziali?

grazie e buon lavoro!

**Comment by umbros** [comment]
Ciao @piersoft, 

- come già scritto in altra issue, siamo nella fase di miglioramento dei processi che ci permetterà di rilasciare i dati, speriamo già da oggi stesso, entro le 18:15 o comunque appena la conferenza stampa del Capo Dipartimento ha inizio;
- ho rilasciato i dati anche in formato json per una lettura e processamento più veloce, rilasciare API, visto anche il traffico che dovrebbe essere gestito è un'attività che metto in ToDo.

Grazie per i suggerimenti

**Comment by mydozer** [comment]
I dati sono già disponibili sulla mappa Esri, come mai non ci sono online memmeno i pdf? Coretesemente rendete i dati per tutti nello stesso momento o in alternativa rimuovete il brand Esri!!
 Grazie!

**Comment by Asoseil** [comment]
Salve, l'aggiornamento del json ogni quanto viene fatto? Sarebbe possibile averlo in tempo reale a seguito della conferenza stampa?

**Comment by umbros** [comment]
Oggi gli script hanno girato bene e abbiamo automatizzato il tutto. Domani puntiamo di rilasciarli durante la conferenza stampa (intorno alle 18:30). Grazie

**Comment by Asoseil** [comment]
Perfetto grazie, se avete bisogno di aiuto per realizzare delle API nessun problema a dare una mano

**Comment by mydozer** [comment]
Grazie @umbros, state rendendo un grande servizio!

**Comment by cirospat** [comment]
solo per dire un grande grazie **@umbros** per il lavoro che state facendo! Bravi e complimenti.

**Comment by AndreasLattmann** [comment]
Bravissimo @umbros , vedo che però gli script non li hai caricati, si può sempre dare una mano... (ciao @piersoft  😉😁)
a disposizione.

**Comment by mydozer** [comment]
Lavoro eccellente! Grazie!!

**Comment by sergiocima** [comment]
Buongiorno @umbros <https://github.com/umbros> i dati della Protezione Civile si discostano da quelli ISS (https://www.iss.it/documents/20126/0/Infografica_09marzo.pdf/1f62ad0a-e156-cf27-309d-26adcb1b52b4?t=1583782049035 <https://www.iss.it/documents/20126/0/Infografica_09marzo.pdf/1f62ad0a-e156-cf27-309d-26adcb1b52b4?t=1583782049035>). Per esempio il comunicato IIS, con dati aggiornati alle ore 10, dà in Lombardia 5510 casi positivi che sono di più rispetto ai 5469 rilevati dal DPC qualche ora dopo, alle 17. Immagino l'ISS faccia un suo lavoro di pulizia dati ma c’è un momento in cui vengono armonizzati o viaggiano in parallelo?
Grazie

**Comment by umbros** [comment]
Ciao a tutti, gli script sono utili al fine di lavorare i dati che ci arrivano, riguardo i dati di ISS attualmente viaggiano in parallelo anche perchè sono tempi diversi. Ogni modifica che faremo e ulteriori dati saranno comunicati in CHANGELOG. Grazie a tutti per la collaborazione e l'entusiamo! :-)
