### ISSUE TITLE
Errore nei dati per la Puglia

### ISSUE THREAD

**Issue by albiboni** [pcm-dpc/COVID-19#210]
Tipo di issue:

- [ X] Dati mancanti o errati **dpc-covid19-ita-regioni-20200316.csv e dpc-covid19-ita-province-20200316.csv**
- [ ] Errore nella documentazione 
- [ ] Errore or mancanza nella dashboard 
- [ ] Problemi di visualizzazione nella dashboard 

- Regione: **Puglia**
- Provincia: **tutte**

## Riassunto

**i dati per il giorno 16-3 non sono stati aggiornati. (il numero dei tamponi è rimasto uguale tra il 15 e 16 marzo)**

**Attesa:**

**La linea della puglia e delle province è rimasta invariata tra il 15 e il 16 marzo**

**Attuale:** 

**La linea della puglia e delle province è rimasta invariata tra il 15 e il 16 marzo**

**Comment by umbros** [comment]
Buonasera @albiboni ,
aggiungo che anche Trento non ha dato aggiornamenti:

![immagine](https://user-images.githubusercontent.com/4085151/76786352-5fabeb80-67b7-11ea-8d1d-3841036ff624.png)

Questa sera metterò in preview dei nuovi tracciati che verranno implementati a breve e dove sarà data informazione di eventuali problemi sui dati come mancati aggiornamenti o dati parziali.
