### ISSUE TITLE
Dati province liguri 16/03

### ISSUE THREAD

**Issue by francescom** [pcm-dpc/COVID-19#211]
Tipo di issue:

- [X] Dati mancanti o errati 
Dile delle province del 16/3 (oggi)

- [ ] Errore nella documentazione 
- [ ] Errore or mancanza nella dashboard 
- [ ] Problemi di visualizzazione nella dashboard 

- Regione: Liguria
- Provincia:  tutte le liguri

## Riassunto

Tutte le province liguri hanno gli stessi valori di ieri

**Attesa:**
Essendo i valori della Liguria intera più grandi di quelli di ieri ci si aspetterebbe dati maggiori anche nelle province

**Attuale:**
I dati delle province sono rimasti identici a ieri, non giustificando l'aumento ligure

(Grazie, keep up the goid work!)

**Comment by umbros** [comment]
Ciao @francescom, per quanto riguarda la Liguria, i dati sulle province confermo sono gli stessi ma sono aumentati i dati "In fase di definizione/aggiornamento" da 59 a 151.
