### ISSUE TITLE
Mancano i dati dei deceduti e dei guariti

### ISSUE THREAD

**Issue by luigimassa** [pcm-dpc/COVID-19#212]
Tipo di issue:

- [X] Dati mancanti o errati:  mancano i deceduti e i guariti
- Regione:
- Provincia: tutte

## Riassunto

Mancano i dati dei deceduti e dei guariti non solo a livello nazionale ma anche provinciale

**Comment by umbros** [comment]
@luigimassa i dati da te indicati non sono attualmente gestiti sul dataset Province.

**Comment by luigimassa** [comment]
ok grazie

**Comment by pensierinmusica** [comment]
https://github.com/pcm-dpc/COVID-19/issues/245
