### ISSUE TITLE
dati popolazione

### ISSUE THREAD

**Issue by filippo-notarnicla** [pcm-dpc/COVID-19#214]
Per cortesia, e' possibile inserire nella tabelle dati la popolazione  provinciale, regionale e nazionale
-->

**Tipo di richiesta**:  richiesta di informazione | richiesta di dati | suggerimento di miglioramento (documentazione, label, _ecc_) | relativo alla pagina grafica

**Comment by alldone** [comment]
Sempre per cortesia, lo stesso dettaglio di informazioni presente nella tabella per regione,
**(totale positivi, nuovi positivi, guariti/dimessi, ..... ecc ecc ) 
si può riproporre nella tabella province?**

grazie in anticipo

**Comment by umbros** [comment]
Ciao @filippo-notarnicla, i dati che eroghiamo sono interoperabili, infatti sia per Regione che per Provincia forniamo anche il codice che può essere utilizzato per collegarlo ad altre basi dati come, appunto, quello della popolazione residente ISTAT.
@alldone per ora gestiamo i dati che eroghiamo, ogni nuova implementazione la comunicheremo.

**Comment by filippo-notarnicla** [comment]
Il 2020-03-17 01:37 Umberto Rosini ha scritto:
> Closed #214 [1].
Per Umberto Rosini: Molte grazie!

-- 
                               filippo notarnicola

========================================
address:
         Notarnicola Filippo

         I.A.C. CNR  - Sede di Bari
         Istituto per le Applicazioni del Calcolo
         Consiglio Nazionale Ricerche

         Via Amendola 122-d
         70126 BARI (Italy)

phone:  +39 0805929741

fax:    +39 0805929770

e-mail: f.notarnicola@ba.iac.cnr.it

room:   entrance A, 9th floor, right door
