### ISSUE TITLE
Numero Casi mancanti in Regione Puglia data16/03/2020

### ISSUE THREAD

**Issue by marcodadamo** [pcm-dpc/COVID-19#215]
**Tipo di richiesta**: Numero casi accertati in Regione Puglia del 16/03/2020, mediante comunicato stampa Presidente Regione.

## Riassunto
Il Presidente della Regione Puglia ha comunicato i dati del 16/03/2020.
## [Comunicato stampa Regione Puglia](http://www.regione.puglia.it/news?p_p_auth=YRBYx1au&p_p_id=56_INSTANCE_8oLBj0XOEEsq&p_p_lifecycle=0&p_p_state=normal&p_p_mode=view&p_p_col_id=column-2&p_p_col_pos=1&p_p_col_count=6&_56_INSTANCE_8oLBj0XOEEsq_articleId=50826902&_56_INSTANCE_8oLBj0XOEEsq_groupId=3728079&_56_INSTANCE_8oLBj0XOEEsq_version=1.0&_56_INSTANCE_8oLBj0XOEEsq_categoryName=CORONAVIRUS%3A+AGGIORNAMENTO+16+MARZO+ORE+20.30&_56_INSTANCE_8oLBj0XOEEsq_back=%2Fcoronavirus%2F)

**Fotografia Tabella aggionamenti**
![image](https://user-images.githubusercontent.com/56562822/76830558-c49e2a80-6825-11ea-8a71-4880e644d9bb.png)

## Interesse pubblico
Aggiornamento dati casi in Regione Puglia in modo tale da allineare con la repository COVID-19

**Comment by CorradoLanera** [comment]
I dati della puglia di ieri (2020-03-16), riportati sia nel csv giornaliero che cumulativo, sono identici a quelli dell'altro ieri. Tutti i delta risultano quindi a zero e i cumulati non incrementano.

**Comment by pierluigicara** [comment]
Grazie delle segnalazioni. La mancanza dei dati di ieri (16.3.2020) della Regione Puglia e della P.A. di Trento sono stati ampiante resi noti e sono riportati nelle annotazioni e rispecchiano un andamento complessivo del monitoraggio che pure è stato più volte descritto nelle varie conferenze stampa DPC o delle Regioni stesse. Aspettiamo, come di consueto, gli aggiornamenti dal Ministero della Salute per poter dare il quadro odierno.
