### ISSUE TITLE
Continuare analisi

### ISSUE THREAD

**Issue by marcomatteo** [pcm-dpc/COVID-19#216]
https://github.com/pcm-dpc/COVID-19/blob/06ac1a036b6f1859684fe470a09bc762a7fbb892/elaborazioni/EDA.py#L11-L11

**Comment by pierluigicara** [comment]
Il link non appare corretto.

**Comment by marcomatteo** [comment]
> Il link non appare corretto.

Mi scuso per l'inconveniente, ho aperto involontariamente il thread.
