### ISSUE TITLE
Richiesta info dati

### ISSUE THREAD

**Issue by Checco68** [pcm-dpc/COVID-19#218]
**Tipo di richiesta**: richiesta di dati 

## Interesse pubblico

Progetto QGis 

Ciao a tutti

innanzitutto scuste se non utilizzo in maniera corretta questo canale ma è la prima volta

Quello che vorrei fare è creare un progetto QGIS da far vedere alla classe di mia figlia (3 Media) per far capire come questi dati visualizzati su una mappa siamo molto più comprensibili

In particolare volevo capire se sono disponibili a livello provinciale/ comunale i dati dei suddivisi come viene fatto a livello regionale

Grazie per la disponibilità

Francecso

**Comment by paganim** [comment]
Salve Francesco,

Certo, sono disponibili i dati suddivisi  sia in regioni e in provincie, li può trova nelle cartelle ["dati-regioni"](https://github.com/pcm-dpc/COVID-19/tree/master/dati-regioni) e ["dati-provincie"](https://github.com/pcm-dpc/COVID-19/tree/master/dati-province).

Spero di essere stato utile. Buon lavoro.

Matteo Pagani

**Comment by umbros** [comment]
Grazie @paganim per la risposta e il supporto.
Corretto @Checco68.
