### ISSUE TITLE
Grafico andamento Nazionale/Incremento Giornaliero

### ISSUE THREAD

**Issue by lorenzo-gabrielli** [pcm-dpc/COVID-19#219]
Salve,

E' possibile consentire la navigazione del dato di incremento anche a livello regionale/provinciale?

![img](https://user-images.githubusercontent.com/18683450/76850478-c1b43180-6847-11ea-8429-4e99416b8e32.PNG)

**Comment by tetrapharmakon** [comment]
Ci avevo pensato anche io; c'è un po' di lavoro da fare e dovremmo essere a conoscenza del modo in cui pcm-dpc usa i dati per generare i grafici con geoJson, ma in teoria è fattibile in tempi brevi!

**Comment by MDalprato** [comment]
Buttate un occhio qui: https://www.marcodalprato.it/covid19-italy/index.php

**Comment by umbros** [comment]
@lorenzo-gabrielli siamo in fase di implementazione di iterazioni sulla dashboard. Grazie
