### ISSUE TITLE
DATI 17/03 INCASINATI

### ISSUE THREAD

**Issue by MarcoGermani** [pcm-dpc/COVID-19#221]
Carissimi,
capisco che state nel caos ma pubblicare dati completamente incasinati no!
Nel cvs di oggi ci sono dati del 3 Aprile !!!
Ma volere almeno verificare la coerenza prima di pubblicare?

**Comment by elcoda** [comment]
L'errore delle date viene riscontrato sui dati delle regioni (sembra un banale trascinamento su qualche Excel che ha creato un incremento per ciascuna riga).
Il dato nazionale sembra ok.
Il dato delle provincie sembra ok.

Grazie per la disponibilità

**Comment by MarcoGermani** [comment]
Io non devo capire. 
Vorrei che chi fa un lavoro, pagato, lo faccia in modo corretto, oltretutto su dati di questo tipo.
Sembra che facciano apposta a creare confusione.

**Comment by albertovisentin** [comment]
Scusate, ma verranno sistemate? Grazie

**Comment by MarcoGermani** [comment]
Spero che qualcuno impari ad usare excel, esportando senza passare per Piton, che in questo caso serve perché non si sa usare Excel … e nemmeno Piton

**Comment by MarcoGermani** [comment]
Il numero da chiamare è 06/68202926 chiedere di Rosini

**Comment by elcoda** [comment]
@MarcoGermani accidenti che acidità... capita di sbagliare.

Piton si scrive Python.

**Comment by pacovi** [comment]
Tranquillo @MarcoGermani .
@elcoda  don't feed the troll... ci sono giá 3 issue con questo dopo 6 minuti.
Give them a break for god's sake...

**Comment by MarcoGermani** [comment]
Caro Ivan, in azienda se commetti questi errori fai una brutta fine. Chi sta pubblicando e tutta la catena di comando è ben pagato.

**Comment by elcoda** [comment]
@pacovi you're right, sorry.

**Comment by albertovisentin** [comment]
Scusate, senza acidità e anzi ringraziando per il quotidiano lavoro, chiedo se i dati verranno sistemati (oggi o con l'aggiornamento di domani) oppure se devo sistemarli a valle. Solo per sapere, grazie ancora

**Comment by crisidev** [comment]
I dati verranno sistemati. Ci sono gia' 4 issue uguali, portate pazienza, questa gente sta lavorando 24/7 per noi. L'importante soprattutto e' non essere scortesi e pazientare..

**Comment by MarcoGermani** [comment]
@pacovy fai meno il cretino. Qui nessuna fa il Troll e tantomeno è accettabile essere sfottuti.
Impara un po' di educazione

**Comment by albertovisentin** [comment]
> I dati verranno sistemati. Ci sono gia' 4 issue uguali, portate pazienza, questa gente sta lavorando 24/7 per noi. L'importante soprattutto e' non essere scortesi e pazientare..

Concordo in pieno. Grazie e ancora complimenti, rimango in attesa.

**Comment by MarcoGermani** [comment]
@crisidev Non farti idee sbagliate, queste persone sono dei funzionari che fanno orario di ufficio

**Comment by MarcoGermani** [comment]
@albertovisentin io con i dati ci lavoro e non è la prima volta che vengono pubblicati errati o non utilizzabili. Posso essere un po' irritato?

**Comment by albertovisentin** [comment]
@MarcoGermani coi dati ci sto lavorando pure io come te. Puoi essere come vuoi, io capisco che si possa sbagliare e che siano tutti sotto pressione. E visto che con la pressione si lavora peggio, se ne metto pure io alla fine il file sistemato lo avremo più tardi. E poi, purtroppo, sbagliare capita. Tutto qua.

**Comment by francescovallone** [comment]
@MarcoGermani puoi essere irritato ma non puoi essere irrispettoso. Aspetta che sistemino e abbassa la cresta. Anche io ci lavoro ma aspetto pazientemente sapendo che queste cose possono succedere.

**Comment by MarcoGermani** [comment]
@fancescovallone, io non sono irrispettoso, vorrei solo che chi offre un servizio lo faccia in modo corretto, queste cose non devono succedere perchè chi lavore in modo serio prima di pubblicare qualcosa lo verifica.

P.S.
"Abbassa la cresta" dillo a tuo fratello o ai tuoi amici

**Comment by umbros** [comment]
@MarcoGermani lo script è automatico c'è stato un problema sull'excel. Ti chiedo di tenere un comportamento adeguato e aderente alle regole di condotta definite.

**Comment by MarcoGermani** [comment]
Caro Umberto, 
ho aperto questa discussione segnalando il problema e suggerendo di verificare prima di pubblicare.
Poi sono arrivati i barbari

**Comment by MarcoGermani** [comment]
Caro Umberto,
è un comportamento adeguato darmi del Troll?
O frasi "Non date da mangiare al Troll" o abbassa la cresta?

**Comment by umbros** [comment]
@MarcoGermani ti invito a rispettare il codice di condotta pubblicato e non pubblicare numeri. Grazie

**Comment by MarcoGermani** [comment]
@umbros Ora i dati sembrano a posto.
Vorrei insegnarle un trucco che evita le risse e le farà fare bella figura.
Se dovesse succedere un errore di questo tipo nuovamente è sufficiente che qualche amministratore posti un frase del genere:
"Scusate ma c'è stato un errore nella pubblicazione dei dati, stiamo lavorando per aggiornarli al più presto"
