### ISSUE TITLE
Dati APRILE nel file odierno 17.03 

### ISSUE THREAD

**Issue by anbened** [pcm-dpc/COVID-19#222]
Tipo di issue:

- [X] Dati mancanti o errati : dpc-covid19-ita-regioni.csv
- [ ] Errore nella documentazione 
- [ ] Errore or mancanza nella dashboard 
- [ ] Problemi di visualizzazione nella dashboard 

- Regione:
- Provincia: 

## Riassunto

Nel file appena uscita (file giornaliero e, di conseguenza, file riepilogativo) sono presenti righe afferenti ad aprile

**Attesa:**

è possibile ricaricare il file corretto?

Molte grazie, come sempre, per il vosto lavoro!

**Comment by pacovi** [comment]
duplicated , see https://github.com/pcm-dpc/COVID-19/issues/223

**Comment by mydozer** [comment]
Nel dpc-covid19-ita-regioni.json ci sono solo due regioni con data odierna 2020-03-17

**Comment by umbros** [comment]
corretto!
