### ISSUE TITLE
I dati di oggi hanno le date sbagliate

### ISSUE THREAD

**Issue by rossodisera** [pcm-dpc/COVID-19#223]
Tipo di issue:

- [x] Dati errati in "COVID-19/dati-regioni/dpc-covid19-ita-regioni.csv"
- [ ] Errore nella documentazione 
- [ ] Errore or mancanza nella dashboard 
- [ ] Problemi di visualizzazione nella dashboard 

- Regione: tutte

## Riassunto

Il file COVID-19/dati-regioni/dpc-covid19-ita-regioni.csv di oggi ha le date sbagliate

**Comment by antoalv19** [comment]
Confermo, ci sono date fino al 5 Aprile

**Comment by Dipierrog** [comment]
Confermo, ci sono date future

**Comment by pcatta1966** [comment]
sono state trascinate e non copiate...

**Comment by tommasobonomo** [comment]
Pare che il campo "data" sia stato riempito progressivamente a partire dalla data odierna 17/03/2020 incrementando per ogni regione. Sia nel file .json che in quello .csv

**Comment by pinoli** [comment]
idem il JSON delle regioni COVID-19/dati-json/dpc-covid19-ita-regioni.json

**Comment by LBreda** [comment]
Qui se non correggono prima che se ne accorga il giornalista sbagliato parte il COMPLOTTO SANNO I DATI FUTURI E NON CIELI DICONO.

**Comment by pigreco** [comment]
la stanchezza inizia a sentirsi!!!

![image](https://user-images.githubusercontent.com/7631137/76883501-8718bc00-687c-11ea-8441-977cc3aec65a.png)

**Comment by downFast** [comment]
scusa nel file json dove? https://github.com/pcm-dpc/COVID-19/blob/master/dati-json/dpc-covid19-ita-regioni.json

**Comment by federicofranco** [comment]
Confermo quanto detto da @tommasobonomo

**Comment by onofrioP89** [comment]
Anche il file https://github.com/pcm-dpc/COVID-19/blob/master/dati-regioni/dpc-covid19-ita-regioni-20200317.csv è errato

**Comment by orion434** [comment]
Per favore, prego ridurre al minimo risposte e non creare duplicati (https://github.com/pcm-dpc/COVID-19/issues/222, https://github.com/pcm-dpc/COVID-19/issues/221) al fine di favorire il lavoro della Protezione Civile in maniera semplice e agile.

**Comment by federicofranco** [comment]
> 
> 
> la stanchezza inizia a sentirsi!!!
> 
> ![image](https://user-images.githubusercontent.com/7631137/76883501-8718bc00-687c-11ea-8441-977cc3aec65a.png)

**Comment by pauligree** [comment]
date sbagliate
buon lavoro
ciao

**Comment by MartinPham** [comment]
i dati dal futuro?

**Comment by piersoft** [comment]
si le date sono sbagliate

**Comment by avvRobertoAlma** [comment]
confermo. Ci sono errori sulle date.

**Comment by floatingpurr** [comment]
> scusate nel file json date sbagliate dove? https://github.com/pcm-dpc/COVID-19/blob/master/dati-json/dpc-covid19-ita-regioni.json

Confermo anche nel JSON, per esempio

```json
{
        "data": "2020-03-29 17:00:00",
        "stato": "ITA",
        "codice_regione": 1,
        "denominazione_regione": "Piemonte",
        "lat": 45.0732745,
        "long": 7.680687483,
        "ricoverati_con_sintomi": 1378,
        "terapia_intensiva": 206,
        "totale_ospedalizzati": 1584,
        "isolamento_domiciliare": 180,
        "totale_attualmente_positivi": 1764,
        "nuovi_attualmente_positivi": 359,
        "dimessi_guariti": 0,
        "deceduti": 133,
        "totale_casi": 1897,
        "tamponi": 6543
    }
```

Credo sia un errore alla fonte che si ripercuote sule varie serializzazioni del dato.

**Comment by mauromussin** [comment]
date sbagliate nel file nazionale, già...

**Comment by downFast** [comment]
> > scusate nel file json date sbagliate dove? https://github.com/pcm-dpc/COVID-19/blob/master/dati-json/dpc-covid19-ita-regioni.json
> 
> Confermo anche nel JSON, per esempio
> 
> ```json
> {
>         "data": "2020-03-29 17:00:00",
>         "stato": "ITA",
>         "codice_regione": 1,
>         "denominazione_regione": "Piemonte",
>         "lat": 45.0732745,
>         "long": 7.680687483,
>         "ricoverati_con_sintomi": 1378,
>         "terapia_intensiva": 206,
>         "totale_ospedalizzati": 1584,
>         "isolamento_domiciliare": 180,
>         "totale_attualmente_positivi": 1764,
>         "nuovi_attualmente_positivi": 359,
>         "dimessi_guariti": 0,
>         "deceduti": 133,
>         "totale_casi": 1897,
>         "tamponi": 6543
>     }
> ```
> 
> Credo sia un errore alla fonte che si ripercuote sule varie serializzazioni del dato.

ah ecco mi era sfuggito li, perchè qui si parlava di date future di aprile e non riuscivo a trovare l'errore. Grazie.

Mi auguro si possa aggiustare quanto prima.

**Comment by Dipierrog** [comment]
Incredibilmente la loro Dashboard funziona però. La mia si è sminchiata del tutto.

**Comment by umbros** [comment]
corretto!

**Comment by rossodisera** [comment]
Grazie per il vostro lavoro.

**Comment by floatingpurr** [comment]
Grande @umbros, un grazie a tutti voi
