### ISSUE TITLE
Bug nel numero di tamponi fatti in Lombardia il 2020-02-26

### ISSUE THREAD

**Issue by RuggieroSeccia** [pcm-dpc/COVID-19#226]
Tipo di issue:

- [ x ] Dati mancanti o errati 
- [ ] Errore nella documentazione 
- [ ] Errore or mancanza nella dashboard 
- [ ] Problemi di visualizzazione nella dashboard 

- Regione: Lombardia
- Provincia: None

## Riassunto

Il numero di tamponi riportati il 25 Feb in Lombardia è 3700 mentre il 26 Feb sono diminuiti a 3208. Se il numero di tamponi è cumulativo, ciò è ovviamente impossibile.
**Attesa:**

**Attuale:**

**Comment by umbros** [comment]
Buonasera @RuggieroSeccia, confermo il numero di tamponi comunicato dalla Regione Lombardia, si tratta, molto probabilmente di una correzione dell'informazione. Da tenere presente, come più volte già detto, che il numero dei tamponi non è indicativo delle persone "controllate" in quando una persona potrebbe aver fatto n tamponi.
