### ISSUE TITLE
Dati regionali del 17 marzo 2020 con date rilevazione errate

### ISSUE THREAD

**Issue by Fciciarelli** [pcm-dpc/COVID-19#227]
Tipo di issue:

- [ X] Dati mancanti o errati nel file regionale totale e nel file regionale del 17 marzo 2020

- Regione: solo alcune regioni

## Riassunto

Si rilevano date errate nel file csv delle regioni

Grazie.

**Comment by umbros** [comment]
@Fciciarelli il problema è stato risolto.
