### ISSUE TITLE
puglia and Trentino not reporting data form yesterday march 16th

### ISSUE THREAD

**Issue by pierorubino** [pcm-dpc/COVID-19#228]
**Type of issue**:  richiesta di informazione | richiesta di dati | suggerimento di enhancement (documentazione, label, _etc_)

## Summary

i just wonder whether you're going to adjust yesterday missing data both at regional and country wide level. thanks a lot, piero

**Comment by umbros** [comment]
Hi @pierorubino, the data not disclosed is assigned to the next day. So today the data of P.A. Trento and Puglia are updated. We are adding a "Notes" field to declare any update problems.

**Comment by pierorubino** [comment]
Thanks a lot 4 your prompt reply. I gathered that. But that would imply a kind of biased inflation of today data which will show in a jump in the dynamics. Why not - if I may - impute this  delayed info to the proper day ie yesterday ?
