### ISSUE TITLE
Un errore nel file di oggi, dpc-covid19-ita-regioni-20200317.csv

### ISSUE THREAD

**Issue by dariomenasce** [pcm-dpc/COVID-19#229]
Vorrei comunicare il fatto che il file **dpc-covid19-ita-regioni-20200317.csv** contiene delle data sbagliate. Ad esempio le righe da Sicilia a Valle d'Aosta riportano la data del 1 Aprile (poi il 2 Aprile e così via), corrompendo il risultato dei miei programmi di analisi dati.

Grazie

Dario Menasce
Ricercatore dell'Istituto Nazionale Di Fisica Nucleare.

**Comment by umbros** [comment]
@dariomenasce è stato corretto subito
