### ISSUE TITLE
Dati epidemiologici estesi

### ISSUE THREAD

**Issue by edaddi73** [pcm-dpc/COVID-19#23]
Sarebbe possibile accedere a dati piu dettagliati inclusi i timing e date dei dei primi sintomi, inclusione nelle liste dei contagiati, ed esito per ciascun paziente (anonimizzato chiaramente) ? Stiamo cercando di modernizzare l'andamento, con altri ricercatori.

**Comment by umbros** [comment]
Ciao @edaddi73, allo stato attuale vengono lavorati questi dati anche per dare un'informazione tempestiva e di facile raccordo. Capisco la necessità ma attualmente non è previsto un rilascio dei dati da te richiesti. Aggiungo un changelog al repository in modo da andare ad "annunciare" eventuali modifiche o nuovi dati che andremo a fornire.
