### ISSUE TITLE
dati delle regioni con date sbagliate

### ISSUE THREAD

**Issue by matteofloris** [pcm-dpc/COVID-19#230]
Tipo di issue:

- [X ] Dati mancanti o errati  dpc-covid19-ita-regioni-20200317.csv
- [ ] Errore nella documentazione 
- [ ] Errore or mancanza nella dashboard 
- [ ] Problemi di visualizzazione nella dashboard 

- Regione: tutte
- Provincia: 

## Riassunto

sono sbagliate le date nel file dpc-covid19-ita-regioni-20200317.csv

**Attesa:**

**Attuale:**

**Comment by umbros** [comment]
CIao @matteofloris le date sono già state corrette

**Comment by matteofloris** [comment]
grazie!
