### ISSUE TITLE
Home confinement data for Umbria

### ISSUE THREAD

**Issue by giacmir** [pcm-dpc/COVID-19#231]
**Type of issue**: Info  richiesta di informazione

## Summary
Home confinement data for Umbria don't match with official website: 
daily reports like [this](http://www.regione.umbria.it/notizie/-/asset_publisher/54m7RxsCDsHr/content/coronavirus-164-i-positivi-in-umbria-420-fuori-dall%E2%80%99isolamento-fiduciario?read_more=true) mentions many more confined people than this repository csv files.

Can you please explain what is the data source for this field and why there is such difference?
Thank you

## Public interest

Having a more precise and aligned information about home confinement may have significant impact on transparency of information.

P.S. Thanks for your valuable work.

**Comment by umbros** [comment]
hi @giacmir the data is send to us from Region by minister of healt. Perhaps the data that you see on the daily report of Umbria Region si update after they send the data to us.
