### ISSUE TITLE
Discrepancy in Puglia

### ISSUE THREAD

**Issue by gio88ciani** [pcm-dpc/COVID-19#232]
Hi .... the Apulian Data are not in agreement with what local newspaper say( https://www.bisceglieviva.it/notizie/coronavirus-nessun-decesso-in-puglia-ma-i-casi-sono-saliti-a-394/?fbclid=IwAR1qEEoSTWqiQpMdn-H0CwBZpGgvEw5jN69hDBzw6Qz4u6GryQuX_FEIFj4): it seems that Emiliano claimed 394 total cases instead of 340 here written. Can you tell more about this discrepancy?

**Type of issue**:  richiesta di informazione | richiesta di dati | suggerimento di enhancement (documentazione, label, _etc_)

**Comment by umbros** [comment]
Hi @gio88ciani we aren't a newspaper but we publish official data from Italian Region by Ministry of Healt.
