### ISSUE TITLE
Attualmenet positivi nella dashboard e' sbagliato - sono 26062

### ISSUE THREAD

**Issue by MauroCapolino** [pcm-dpc/COVID-19#234]
Tipo di issue:

- [x] Dati mancanti o errati 
- [ ] Errore nella documentazione 
- [ ] Errore or mancanza nella dashboard 
- [ ] Problemi di visualizzazione nella dashboard 

- Regione:
- Provincia: 

## Riassunto

**Attesa:**

**Attuale:**

**Comment by MauroCapolino** [comment]
in the dashboard totale attualmenet positivi e errato
http://opendatadpc.maps.arcgis.com/apps/opsdashboard/index.html#/b0c68bce2cce478eaac82fe38d4138b1

**Comment by umbros** [comment]
Ciao @MauroCapolino, la segnalazione non è riscontrabile, il dato è corretto
![immagine](https://user-images.githubusercontent.com/4085151/76942718-7ad54300-68fe-11ea-8951-458f0354918a.png)
