### ISSUE TITLE
Analisi Grafico Regioni del 17/03/2020

### ISSUE THREAD

**Issue by marcodadamo** [pcm-dpc/COVID-19#235]
**Tipo di richiesta**: Analisi grafico in base ai dati della directory COVID-19/dati-regioni/COVID-19/dati-regioni/dpc-covid19-ita-regioni-20032017.csv
## Riassunto
Dimostrazione dell'andamento giornaliero in un grafico dove vengono rappresentate tutte le regioni italiane in base ai dati prelevati dal file regioni 20032017 della repository COVID-19 

## Interesse pubblico
Fotografia dell'andamento dei dati nella giornata del 17/03/2020, dimostra il crescente numero dei casi e le regioni maggiormente coinvolte.

![immagine](https://user-images.githubusercontent.com/56562822/76906789-01f5cd00-68a5-11ea-83cf-36aab0e461c6.png)

**Comment by umbros** [comment]
Grazie @marcodadamo
