### ISSUE TITLE
Errore nei dati regionali al 17/03 per la regione FVG

### ISSUE THREAD

**Issue by nclBaz** [pcm-dpc/COVID-19#236]
Tipo di issue:

- [x] Dati mancanti o errati 
- [ ] Errore nella documentazione 
- [ ] Errore or mancanza nella dashboard 
- [ ] Problemi di visualizzazione nella dashboard 

- Regione:
- Provincia: 

## Riassunto

Nei dati regionali con data 17/03, per la regione Friuli Venezia Giulia troviamo 17 nel field dimessi_guariti, il giorno precedente essi erano 18. Ci si aspetta che il numero sia uguale o crescente rispetto ai giorni precedenti

**Attesa:**

 ` {
   "data": "2020-03-17 17:00:00",
   "denominazione_regione": "Friuli Venezia Giulia",
   "dimessi_guariti": >=18,
 }`

**Attuale:** ` {
   "data": "2020-03-17 17:00:00",
   "denominazione_regione": "Friuli Venezia Giulia",
   "dimessi_guariti": 17,
 }`

**Comment by umbros** [comment]
Ciao @nclBaz è possibile che il dato comunicato possa essere stato comunicato erroneamente o altre motivazioni.
