### ISSUE TITLE
Json nuovi_attualmente_positivi ci sono dati negativi!

### ISSUE THREAD

**Issue by jackilgeco** [pcm-dpc/COVID-19#237]
Tipo di issue:

- [x] Dati mancanti o errati 
- [ ] Errore nella documentazione 
- [ ] Errore or mancanza nella dashboard 
- [ ] Problemi di visualizzazione nella dashboard 

- Regione:
- Provincia: 

## Riassunto

**Attesa:**

**Attuale:**

**Comment by Luca46** [comment]
Confermo anche io: perchè ci sono alcuni casi in nuovi_attualmente_positivi, negativi?

**Comment by sfoglia60** [comment]
Perché è il dato è un saldo di altre variabili

**Comment by Luca46** [comment]
ma nel dataset quindi non esiste una variabile che mi dica i nuovi casi positivi di quel determinato giorno?

**Comment by sfoglia60** [comment]
Sì è la colonna 12 del csv "nuovi_attualmente_positivi". Comunque hai ragione tu, il dato negativo è un errore. Io per sviluppare le previsioni l'avevo infatti messo a zero

**Comment by Luca46** [comment]
E anche io ho proceduto come hai fatto te....ma storpiare il dato in questa maniera mi sembra una forzatura esagerata...su Wikipedia ho visto però che ci sono dataset che indicano i casi nuovi positivi.

**Comment by sfoglia60** [comment]
Beh questi non dovrebbero essere i dati ufficiali?

**Comment by umbros** [comment]
Buongiorno, i dati negativi possono essere causati da una comunicazione parziale, errata o a dati pervenuti da parte di una Regione, a livello dati non possiamo mettere a zero comunicazioni ufficiali, ovviamente, per i vostri scopi, potete fare i ragionamenti e perfezionamenti sul dato che riterrete opportuni.

**Comment by FedericoStra** [comment]
@Luca46 

> ma nel dataset quindi non esiste una variabile che mi dica i nuovi casi positivi di quel determinato giorno?

No. Devi sottrarre `totale_casi` del giorno in corso con il `totale_casi` del giorno precedente.

@sfoglia60 

> Sì è la colonna 12 del csv "nuovi_attualmente_positivi".

Sbagliato. `nuovi_attualmente_positivi` è il bilancio, ovvero nuovi casi meno guariti meno deceduti. I nuovi casi sono di più, e sono sempre un numero non negativo ovviamente.

> Io per sviluppare le previsioni l'avevo infatti messo a zero

Pessima idea.

> ma storpiare il dato in questa maniera mi sembra una forzatura esagerata

Concordo.
