### ISSUE TITLE
Previsioni sulla terapia intensiva in Italia

### ISSUE THREAD

**Issue by gianlab** [pcm-dpc/COVID-19#238]
Vi segnalo una previsione regionale a 10  giorni per le terapie intensive...Pare che il problema sia soltanto per l'Umbria , la Lombardia e la Toscana: 
https://www.kaggle.com/gianlab/previsioni-sulla-terapia-intensiva-in-italia

**Comment by umbros** [comment]
Grazie mille per la collaborazione @gianlab
