### ISSUE TITLE
Is ricoverati_con_sintomi cumulative?

### ISSUE THREAD

**Issue by phl43** [pcm-dpc/COVID-19#239]
I was wondering if the column ricoverati_con_sintomi in the dataset was cumulative or if the people who leave ICU either because they died or because they got better are removed from the data every day. I think it would be much more interesting if it was not cumulative but kept up to date, because it would be a much better indicator of the amount of stress on the Italian health care system, but at the moment I don't know so I'm not sure how to interpret this variable in the dataset.

**Comment by niklaswillrich** [comment]
I am wondering about a similar question. Does the variable  terapia_intensiva count the number of patients which are on the ICU on the particular day or does it count the number of currently hospitalised patients which were at some point of their stay on the ICU?
It would really help a lot to clarify this! BTW: this is really useful and great work you are doing. Thank you very much already.

**Comment by niklaswillrich** [comment]
Ok, my question seems to be answered in Issue #155. Sorry, for not looking first.

**Comment by umbros** [comment]
Hi, I confirm that, today or tomorrow we will publish a wiki in italian and english.

**Comment by phl43** [comment]
Sorry, I was actually talking about terapia_intensiva too, and sorry for not seeing the question had already been asked. I actually checked but I must have copy-pasted the same mistaken column name than I did in the title of my question when I searched!
