### ISSUE TITLE
Dati dal 19 al 23 Febbraio

### ISSUE THREAD

**Issue by fmossott** [pcm-dpc/COVID-19#24]
I dati attualmente partono dal 24 Febbraio, sarebbe interessante avere anche i dati a partire dal 19 Febbraio, giorni prima dell'individuazione del paziente 1.

Usando i dati e la cronologia di news su https://www.worldometers.info/coronavirus/#countries sono ricostruito a ricostruire qui giorni a livello regionale, ma probabilmente avete fonti migliori 😉
In caso, la mia ricostruzione è sul mio fork: is file aaa-* su https://github.com/fmossott/COVID-19/tree/master/dati-regioni

Grazie per i dati e per averli resi pubblici in questa modalità

**Comment by umbros** [comment]
Buongiorno @fmossott i dati in maniera strutturata sono stati raccolti  dal 24/02, quelli che noi pubblichiamo sono dati ufficiali, utilissimo il tuo dataset ma non è utilizzabile dai canali ufficiali. Grazie comunque del suggerimento e dell'informazione.
