### ISSUE TITLE
Previsione attualmente positivi

### ISSUE THREAD

**Issue by sfoglia60** [pcm-dpc/COVID-19#240]
Se può interessare, da qualche giorno sto sviluppando le previsioni del numero di positivi, con esclusione dei guariti e dei deceduti. Sto utilizzando due tecniche combinate, una curva di Gompertz sulla percentuale di contagiati rispetto ai tamponi applicati e una curva di Bass direttamente sui contagiati. Questo secondo approccio è sviluppato anche per Regione. Il file allegato è aggiornato ai dati del 16 marzo, adesso lo aggiorno con i dati di ieri
[COVID-19 - ITA_new.xlsx](https://github.com/pcm-dpc/COVID-19/files/4347795/COVID-19.-.ITA_new.xlsx)

**Comment by sfoglia60** [comment]
Previsioni aggiornate ai dati di ieri
[COVID-19 - ITA_new.xlsx](https://github.com/pcm-dpc/COVID-19/files/4347880/COVID-19.-.ITA_new.xlsx)

**Comment by peval27** [comment]
conviene che il nome del file sia tipo ..20200318.xlsx cosi si capisce per che giorno e'

**Comment by sfoglia60** [comment]
Ok ottimo consiglio

**Comment by umbros** [comment]
Grazie @sfoglia60 del contributo

**Comment by Andrea1310** [comment]
Ciao @sfoglia60 sono interessato ad approfondire la tua ricerca che ho trovato molto interessante. Potresti lasciarmi un tuo contatto?

**Comment by sfoglia60** [comment]
Ciao Andrea,

 

mi trovi a questa mail oppure su Linkedin, mi chiamo Bruno Sfogliarini

 

A presto, Bruno

 

Da: Andrea1310 <notifications@github.com> 
Inviato: giovedì 19 marzo 2020 17:11
A: pcm-dpc/COVID-19 <COVID-19@noreply.github.com>
Cc: sfoglia60 <bruno.sfogliarini@iol.it>; Mention <mention@noreply.github.com>
Oggetto: Re: [pcm-dpc/COVID-19] Previsione attualmente positivi (#240)

 

Ciao @sfoglia60 <https://github.com/sfoglia60>  sono interessato ad approfondire la tua ricerca che ho trovato molto interessante. Potresti lasciarmi un tuo contatto?
