### ISSUE TITLE
Split sul dato provinciale

### ISSUE THREAD

**Issue by simonetolomelli** [pcm-dpc/COVID-19#241]
Non sto trovando io, o no ci sono proprio, i dati con granularità maggiore per provincia? Se c'è un aggregato regionale dei casi positivi, decessi, ricoveri, TI, tamponi, eccetera, come è possibile non averlo a livello provinciale? Sono fonti diverse, non vengono condivisi?

**Comment by umbros** [comment]
Buongiorno  @simonetolomelli , allo stato attuale non gestiamo questi dati, ogni altra informazione che andremo a gestire sarà comunicata.

**Comment by pensierinmusica** [comment]
https://github.com/pcm-dpc/COVID-19/issues/245
