### ISSUE TITLE
Aggiunto BOT di Telegram @CovidITAbot

### ISSUE THREAD

**Issue by tonjo** [pcm-dpc/COVID-19#242]
Chiedo scusa se uso una issue per questa informazione, ma magari qualcuno è interessato.

**Tipo di richiesta**: Informazione (data, non richiesta)

## Riassunto
E` stato creato il bot su Telegram @CovidITAbot, con dei semplici comandi 
per interrogare (per ora) gli ultimi dati forniti da questo repository.
Si potrebbero anche generare i grafici, avendo tempo di farlo.

## Interesse pubblico
E` un modo veloce per avere gli ultimi dati.

**Comment by umbros** [comment]
Grazie @tonjo
