### ISSUE TITLE
Informazione Tamponi

### ISSUE THREAD

**Issue by CrisMon-01** [pcm-dpc/COVID-19#243]
**Tipo di richiesta**:  relativo alla pagina grafica

## Riassunto
Mettereste l'informazioni del numero di tamponi sulla mappa: http://opendatadpc.maps.arcgis.com/apps/opsdashboard/index.html#/b0c68bce2cce478eaac82fe38d4138b1

## Interesse pubblico
Avere a disposizione di tutti il quantitativo di numero di tamponi aiuterebbe anche a stimare l'entità e il rapporto di malati, mettere soltanto il numero di positivi etc senza avere il numero di tamponi non da a pieno le informazioni di questi dati, inoltre aiuterebbe a chiarire il perchè a distanza di giorni c'è ancora un alto numero di nuovi casi nonostante le misure adottate.

**Comment by umbros** [comment]
ciao @CrisMon-01 il numero dei tamponi non è indicativo delle persone che vengono controllate perchè una persona potrebbe aver fatto n tamponi, pertanto è un dato indicativo e non utile ai fini di una visualizzazione informativa

**Comment by LucScu** [comment]
è comunque un dato che se avete a disposizione potete mettere. O no?

**Comment by LucScu** [comment]
> **Tipo di richiesta**: relativo alla pagina grafica
> 
> ## Riassunto
> Mettereste l'informazioni del numero di tamponi sulla mappa: http://opendatadpc.maps.arcgis.com/apps/opsdashboard/index.html#/b0c68bce2cce478eaac82fe38d4138b1
> 
> ## Interesse pubblico
> Avere a disposizione di tutti il quantitativo di numero di tamponi aiuterebbe anche a stimare l'entità e il rapporto di malati, mettere soltanto il numero di positivi etc senza avere il numero di tamponi non da a pieno le informazioni di questi dati, inoltre aiuterebbe a chiarire il perchè a distanza di giorni c'è ancora un alto numero di nuovi casi nonostante le misure adottate.

Sai dove posso trovare questo dato?

**Comment by CrisMon-01** [comment]
> > **Tipo di richiesta**: relativo alla pagina grafica
> > ## Riassunto
> > Mettereste l'informazioni del numero di tamponi sulla mappa: http://opendatadpc.maps.arcgis.com/apps/opsdashboard/index.html#/b0c68bce2cce478eaac82fe38d4138b1
> > ## Interesse pubblico
> > Avere a disposizione di tutti il quantitativo di numero di tamponi aiuterebbe anche a stimare l'entità e il rapporto di malati, mettere soltanto il numero di positivi etc senza avere il numero di tamponi non da a pieno le informazioni di questi dati, inoltre aiuterebbe a chiarire il perchè a distanza di giorni c'è ancora un alto numero di nuovi casi nonostante le misure adottate.
> 
> @CrisMon-01 Sai dove posso trovare questo dato?

è già nei file csv giornalieri, come ultima colonna vengono elencati regione per regione (penso anche provincia per provincia ma non ho controllato), il numero di tamponi a oggi fatti

**Comment by irebo2020** [comment]
Buongiorno,
riguardo ai dati csv, il numero di tamponi riportato giornalmente sono i totali rispetto al giorno considerato (quindi includono anche quelli dei giorni precedenti), o sono relativi solo al giorno in questione?

**Comment by irebo2020** [comment]
@LucScu il dato relativo a tutti i tamponi fatti sul terriotrio nazionale purtroppo rimane coumnque poco utile, dal momento che il numero di tamponi non è costante ogni giorno, e soprattutto varia da regione in regione. Bisognerebbe normalizzare il tutto, o esprime l'incremento dei casi positivi in percentuale rispetto ai tamponi fatti. Un grafico con un incremento espresso come differenza di valori in questo caso perde di significato. Per questo chiedevo se i dati dei tamponi (ultima colonna a destra nella tabella csv) sono totali fino a quel giorno, o sono del solo giorno in questione!

**Comment by CrisMon-01** [comment]
> Buongiorno,
> riguardo ai dati csv, il numero di tamponi riportato giornalmente sono i totali rispetto al giorno considerato (quindi includono anche quelli dei giorni precedenti), o sono relativi solo al giorno in questione?

a guardare i dati di giorni consecutivi e "a campione"/giorni random, mi sembrano incrementali, ovvero sono quelli del giorno prima + oggi, ma non ne sono sicuro, è una Mia supposizione

**Comment by LucScu** [comment]
@irebo2020 infatti mi ero interessato al dato "esprimere l'incremento dei casi positivi in percentuale rispetto ai tamponi fatti", che però facendo una più attenta considerazione è irrilevante ai fini della situazione dell'epidemia e ad una sua proiezione, in quanto sicuramente i positivi non tamponati saranno sempre moltissimi.
Credo che invece sia importante avere dati corretti sul numero dei ricoverati, guariti e deceduti che dovrebbero essere affidabili e ci possono dare indicazioni sull'aumento o la diminuzione dei contagi e sul tasso di mortalità e letalità.
