### ISSUE TITLE
Co-morbidity data for children with COVID-19

### ISSUE THREAD

**Issue by jphfisher** [pcm-dpc/COVID-19#244]
## Outline
I work as a paediatrician for the NHS in the UK.  We are trying to collate data on children with pre-existing medical conditions to find out if they have different outcomes to previously well children.  This will help with planning of paediatric hospital capacity and paediatric intensive care services.

## Public interest
Getting as much data on children affected by COVID-19 and their pre-existing medical conditions will help us identify patterns so that we can better provide for their needs as the pandemic evolves.

## Request
Please could you contact me so we can discuss what data might be available.

All the best

Dr Jonathan Fisher
NIHR Academic Clinical Lecturer in Paediatric Oncology
GOS-UCL Institute of Child Health

**Comment by umbros** [comment]
Hi Dr @jphfisher thank you for you suggestion, we are expanding our dataset and we will include age. We will publish it!

**Comment by jphfisher** [comment]
Dear Umberto,

Thanks for replying.  Do you have patient-level data (i.e. one line per patient) showing which children had which co-morbidities?  This would be really valuable to start clustering patients with particular characteristics.

If you’d prefer to continue the conversation offline - email me on the email in my profile and we can then switch over to my official NHS email.

All the best, and stay well!

Jonathan

**Comment by mariabnd** [comment]
Hi @umbros 

When do you expect to include information on age/to release the expanded dataset?
