### ISSUE TITLE
Dati deceduti per provincia

### ISSUE THREAD

**Issue by pensierinmusica** [pcm-dpc/COVID-19#245]
@umbros è possibile integrare questo repo con i dati dei deceduti per provincia?

Al momento li vedo solo nell'andamento nazionale.

Avere anche i dati per provincia ci consentirebbe di capire l'efficacia di iniziative adottate localmente.

Grazie!

**Comment by anmio** [comment]
mi accodo a questo appello.
I dati dei deceduti è senza dubbio quello più attendibile.

**Comment by umbros** [comment]
Ciao @pensierinmusica e @anmio attualmente non gestiamo questo dato, eventuali modifiche al dataset sarà comunicato

**Comment by pensierinmusica** [comment]
@umbros come si può avviare una petizione perché i dati giornialieri dei deceduti per provincia siano inclusi?

È un dato molto importante per studiare l'efficacia delle misure adottate.

Grazie
