### ISSUE TITLE
Non mi tornano i conti

### ISSUE THREAD

**Issue by MarcoGuastalla** [pcm-dpc/COVID-19#246]
Sembra che il TOTALE CASI sia la sommatoria dei casi nuovi in modo progressivo (corretto) + i dimessi guariti (già conteggiati nei casi nuovi) + i deceduti (gia conteggiati nei casi nuovi).

**Comment by salvatorese** [comment]
Attualmente positivi 26062
Guariti 2941
Deceduti 2503
------------------------
Totale Positivi 31506

**Comment by mazinthebox** [comment]
Totale casi è la somma dei "dimessi guariti", dei "deceduti" e dei "positivi"

**Comment by MarcoGuastalla** [comment]
I "deceduti" e i "dimessi guariti" venivano inclusi nei "nuovi casi" nel giorno precedente? Se si, allora vengono contati due volte. O mi sbaglio?

**Comment by MarcoGuastalla** [comment]
IL TOTALE CASI dovrebbe essere solo la sommatoria dei "nuovi casi", ossia 26062.
Di questi, alcuni sono deceduti o guariti. Deceduti e guariti, erano già nuovi casi nei giorni scorsi. 
Perché sommarli ai nuovi casi a dare 31506?

**Comment by FLP86** [comment]
Ciao @Marco Guastalla, il totale casi rappresenta il numero di persone che hanno contratto l'infezione per cui è uguale a:

Persone attualmente positive + persone guarite + persone decedute.

da non confondere con le persone attualmente positive.

**Comment by MarcoGuastalla** [comment]
> Ciao @marco Guastalla, il totale casi rappresenta il numero di persone che hanno contratto l'infezione per cui è uguale a:
> 
> Persone attualmente positive + persone guarite + persone decedute.
> 
> da non confondere con le persone attualmente positive.

Grazie del commento. IL mio dubbio è: "le persone decedute o guarite", IERI erano conteggiate nei casi attualmente positivi? Se "si", allora li stiamo contando due volte. Se me lo fai capire ti ringrazio, in quanto sto giocando con Excel per tirare fuori dei flussi. Grazie

**Comment by FLP86** [comment]
Ciao,

no. I 26062 del 17/03 erano gli attualmente positivi (senza conteggiare le persone decedute o guarite).

**Comment by MarcoGuastalla** [comment]
QUindi le persone decedute o guarite, QUANDO sono state conteggiate?

**Comment by MarcoGuastalla** [comment]
OK... forse mi si sta accendendo il neurone... forse ho capito. Grazie a tutti. Se avro ancora dubbi, continuerò su questo 3d. Ciao

**Comment by umbros** [comment]
Ciao @MarcoGuastalla stiamo migliorando la descrizione del dataset, dai uno sguardo sul wiki 
https://github.com/pcm-dpc/COVID-19/wiki/1.it-Dati:-andamento-nazionale

Penso ora sia più chiaro.

Grazie comunque della segnalazione e se trovi errori segnalali pure
