### ISSUE TITLE
I dati per provincia non hanno più ospedalizzati ecc?

### ISSUE THREAD

**Issue by downFast** [pcm-dpc/COVID-19#247]
Tipo di issue:

- [ ] Dati mancanti o errati 
- [ ] Errore nella documentazione 
- [ ] Errore or mancanza nella dashboard 
- [ ] Problemi di visualizzazione nella dashboard 

- Regione:
- Provincia: 

## Riassunto

**Attesa:**

**Attuale:** 

I dati della provincia non hanno più i dettagli mentre ora le vediamo solo nel json della regione? Come mai? Li avremo?

Grazie mille

**Comment by mazinthebox** [comment]
I dati di provincia non hanno mai avuto "totale_ospedalizzati"

**Comment by umbros** [comment]
Ciao   @downFast non viene gestito quel dato per Provincia.
Grazie @mazinthebox per la precisazione

**Comment by downFast** [comment]
Gosh, troppi codici e mi stava incasinando, non sapevo più quale fosse quello coi dati nel dettaglio, my fault.

Gran lavoro, grazie
