### ISSUE TITLE
Header repeated around line 485

### ISSUE THREAD

**Issue by guivo** [pcm-dpc/COVID-19#248]
Type of issue:

- [x] Incorrect or missing data : 
- [ ] Incorrect or missing documentation 
- [ ] Incorrect or missing data in the dashboard 
- [ ] Layout problem in the dashboard 

- Region: All
- Province: 

## Summary

The header of the table is repeated at row 485

**Comment by LBreda** [comment]
This issue is replicated in the json file too.

**Comment by Achab94** [comment]
![Screenshot 2020-03-18 at 18 24 35](https://user-images.githubusercontent.com/9095461/76988914-d24ad180-6945-11ea-9ea8-4cfb75dd7f27.png)

**Comment by umbros** [comment]
Corretto! Grazie
