### ISSUE TITLE
Creazione API

### ISSUE THREAD

**Issue by alessiodl** [pcm-dpc/COVID-19#25]
Buongiorno e grazie per aver messo a disposizione i dati. 

Come probabilmente sapete, alcuni si erano già attivati per raccogliere, organizzare e rilanciare le informazioni che quotidianamente venivano messe a disposizione in consultazione sul sito del DPC e del Ministero. 

Giorni fa ho creato questo progetto che raccoglie i dati tramite web scraping e poi li pubblica sotto forma di API ReST (anche geo):

https://github.com/alessiodl/COVID19Feed2Json

Adesso che ci sono i dati ufficiali in formato machine readable, dismetterò la parte di scraping e proporrò, tramite le API, direttamente i vostri csv.  

Questo è il dashboard che ho realizzato per la divulgazione:

https://github.com/alessiodl/COVID19Dashboard

**Comment by umbros** [comment]
Ciao @alessiodl ho messo in ToDo l'attività di realizzazione di API, complimenti per ciò che hai realizzato e per la dashboard e grazie per la collaborazione.

**Comment by alessiodl** [comment]
Ciao @umbros, ho collegato stabilmente la mia API ai vostri dati. Qui trovi una pagina di documentazione:

https://covid19-it-api.herokuapp.com/doc/
