### ISSUE TITLE
Errore nel file csv regioni del 18/03/2020

### ISSUE THREAD

**Issue by emazep** [pcm-dpc/COVID-19#251]
Il file CSV di riepilogo dei dati regionali di oggi:

https://raw.githubusercontent.com/pcm-dpc/COVID-19/master/dati-regioni/dpc-covid19-ita-regioni.csv

contiene la riga delle intestazioni di colonna immediatamente sopra le righe delle singole regioni relative alla giornata di oggi.

Grazie.

**Comment by sausyn** [comment]
Il file regioni mi risulta corretto ora, il problema rimane nel file province

**Comment by Tusamarco** [comment]
dpc-covid19-ita-province.csv riga 2945 
stesso problema

**Comment by umbros** [comment]
Corretti. Grazie
