### ISSUE TITLE
Values in JSON files turned from integer to strings

### ISSUE THREAD

**Issue by bfabio** [pcm-dpc/COVID-19#254]
Type of issue:

- [x] Incorrect or missing data : `dpc-covid19-ita-province.json`, `dpc-covid19-ita-regioni.json`

- Region: All
- Province: All

## Summary

All the numbers turned into strings with 7470ab0daaaab, fe. `totale_casi` in `dpc-covid19-ita-province.json` and all the count fields (`ricoverati_con_sintomi`,`terapia_intensiva`,`totale_ospedalizzati`,`isolamento_domiciliare`,`totale_attualmente_positivi`,`nuovi_attualmente_positivi`,`dimessi_guariti`,`deceduti`,`totale_casi`,`tamponi`) in `dpc-covid19-ita-regioni.json`

**Comment by umbros** [comment]
Grazie @bfabio
