### ISSUE TITLE
Valori numerici rappresentarti come stringhe nei json

### ISSUE THREAD

**Issue by floatingpurr** [pcm-dpc/COVID-19#255]
Tipo di issue:

- [x ] Dati mancanti o errati 
- [ ] Errore nella documentazione 
- [ ] Errore or mancanza nella dashboard 
- [ ] Problemi di visualizzazione nella dashboard 

- Regione: Tutti i file JSON
- Provincia: Tutti i file JSON

## Riassunto

I valori numerici nei JSON sono stati serializzati come stringhe 

**Attesa:**
I valori numerici nei JSON dovrebbero essere valori numerici

**Comment by bfabio** [comment]
#254

**Comment by floatingpurr** [comment]
Scusate, dobbiamo aver postato in concomitanza. Chiudo qui.
