### ISSUE TITLE
Codici regione e provincia cambiati da numeri a stringhe in JSON

### ISSUE THREAD

**Issue by pescetti** [pcm-dpc/COVID-19#256]
Tipo di issue:

- Dati mancanti o errati 
- Provincia: tutte

## Riassunto

Secondo README.md il codice regione e provincia è un numero. Con i dati di stasera è stato convertito in stringa, rompendo la compatibilità con le applicazioni.

```
$ git show 7470ab0da dati-json/dpc-covid19-ita-province.json
...
diff --git a/dati-json/dpc-covid19-ita-province.json b/dati-json/dpc-covid19-ita-province.json
index 6070b63..e95b9a1 100644
--- a/dati-json/dpc-covid19-ita-province.json
+++ b/dati-json/dpc-covid19-ita-province.json
@@ -2,35329 +2,36877 @@
     {
         "data": "2020-02-24 18:00:00",
         "stato": "ITA",
-        "codice_regione": 13,
+        "codice_regione": "13",
         "denominazione_regione": "Abruzzo",
-        "codice_provincia": 69,
+        "codice_provincia": "069",
...
```

**Attesa:**

Codici regione e provincia devono essere numeri.

**Attuale:** 

Codici regione e provincia sono stringhe.

**Comment by bfabio** [comment]
Duplicate of #254

**Comment by pescetti** [comment]
Indeed, #254 is the same issue, written while I was posting mine. Closing.
