### ISSUE TITLE
Dati non aggiornati per provincia di Latina

### ISSUE THREAD

**Issue by eiannone** [pcm-dpc/COVID-19#257]
Tipo di issue:

- [x] Dati mancanti o errati dpc-covid19-ita-province-20200318.csv (e giorni precedenti)
- [ ] Errore nella documentazione
- [ ] Errore or mancanza nella dashboard
- [ ] Problemi di visualizzazione nella dashboard

- Regione: Lazio
- Provincia: Latina

## Riassunto

Da diversi giorni noto che i dati della provincia di Latina non sono aggiornati. Il numero dei pazienti positivi è fermo a 23 da diversi giorni, mentre il valore pubblicato dalla ASL provinciale risulta diverso.
Ad esempio, ad oggi il valore dovrebbe essere pari a 95, come da comunicato ufficiale: https://www.ausl.latina.it/comunicati-stampa/3145-comunicato-stampa-del-18-03-2020-coronavirus

**Comment by umbros** [comment]
@eiannone questo dipende dalla comunicazione della Regione Lazio a Ministero della Salute e quindi a noi. Può dipendere da allocazioni non definitive che la Regione non ha posto su Latina. Per noi i dati ufficiali sono quelli forniti da Regione e Ministero della Salute
