### ISSUE TITLE
Dati della Campania non aggiornati

### ISSUE THREAD

**Issue by gdenatale** [pcm-dpc/COVID-19#259]
Tipo di issue:

- [x] Dati mancanti o errati 
Campania - mancano 117 nuovi positivi (fonte Facebook De Luca ore 17 del 18/03/2020)
File PDF e CSV del 18/3/2020

- [ ] Errore nella documentazione 
- [ ] Errore or mancanza nella dashboard 
- [ ] Problemi di visualizzazione nella dashboard 

- Regione:

- Provincia: 

## Riassunto

**Attesa:**

**Attuale:**

**Comment by Tusamarco** [comment]
Confermo viene riporatata lariga del Marzo 17 due volte (stessi valori)

**Comment by umbros** [comment]
@gdenatale @Tusamarco ci sono degli orari entro i quali i dati devono essere aggiornati, i dati della Campania oggi non sono pervenuti. Nel readme mettiamo ogni informazione sul conferimento dei dati.

**Comment by gdenatale** [comment]
OK non avevo letto le note
