### ISSUE TITLE
Dati troppo incompleti 

### ISSUE THREAD

**Issue by RomeoRzz** [pcm-dpc/COVID-19#26]
Per poter applicare creare modelli di Machine Learning in grado di dare risposte previsionali per sesso, età, condizioni generali di salute, etc, non bastano i conteggi totali. Servono dati giornalieri con record per ciascun singolo caso, identificato con ID univoco, e con tutti i campi informativi sopra riportati, ed oltre... Ci fossero questi dati mi basterebbe mezz'ora per addestrare e verificare un modello sicuramente più informativo di quanto si legga ad oggi sui canali informativi.

**Comment by umbros** [comment]
Ciao @RomeoRzz, come già detto in altre issue, allo stato attuale i dati rilasciati sono quelli che stiamo lavorando, verrà riportato in CHANGELOG ogni modifica o nuova disponibilità di dati, capisco la tua necessità ma in questo momento l'obiettivo è quello dell'informazione ai cittadini.
