### ISSUE TITLE
dati europei

### ISSUE THREAD

**Issue by filippo-notarnicla** [pcm-dpc/COVID-19#260]
-->Esiste un database accessibile con dati analoghi per le altre nazioni europee?
Esiste un database europeo accessibile con tutti i dati?

**Tipo di richiesta**:  richiesta di informazione 

## Interesse pubblico

studio comparativo con modelli evolutivi

**Comment by joachimds** [comment]
Some of the files contain . separators instead of , separators !

Can i submit a pull req with the corrections?

**Comment by filippo-notarnicla** [comment]
Il 2020-03-18 20:25 Joachim De Schrijver ha scritto:
> Some of the files contain . separators instead of , separators !
> 
> Can i submit a pull req with the corrections?
> 
> --


Dear Joachim De Schrijver,

I apologize, but the use of the pull option is not immediate.

Thanks! You can reformulate the pull req.

With my very best regards

filippo notarnicola

========================================
address:
         Notarnicola Filippo

         I.A.C. CNR  - Sede di Bari
         Istituto per le Applicazioni del Calcolo
         Consiglio Nazionale Ricerche

         Via Amendola 122-d
         70126 BARI (Italy)

phone:  +39 0805929741

fax:    +39 0805929770

e-mail: f.notarnicola@ba.iac.cnr.it

room:   entrance A, 9th floor, right door

**Comment by umbros** [comment]
Ciao @filippo-notarnicla, non sono a conoscenza di dati in formato aperto ufficiali, ti segnalo il github di JHU CSSE che raccoglie vari dataset: https://github.com/CSSEGISandData/COVID-19.

@joachimds the point is used for lat and long coordinates:
2020-03-18 17:00:00,ITA,15,Campania**,40.83956555**,**14.25084984**,127,24,151,272,423,0,28,9,460,2685

@filippo-notarnicla ti ringrazio per la collaborazione ma stai chiedendo di effettuare una pull request per un problema che non c'è.
