### ISSUE TITLE
Dati europe sbagliati per l'italia come mai? 

### ISSUE THREAD

**Issue by MauroCapolino** [pcm-dpc/COVID-19#261]
scarico ogni giorno per aggiornare il mio siti sia i dati europei e quelli italiano dal vostro repository e mi sono accorto che negli ultimi 5 giorni i dati europei sull'italia sono completamenti errati e per di piu sempre in ritardo di un giorno

questa e' fa fonte ufficiale che uso e credo che dovremmo proteggere i nostri dati 

https://www.ecdc.europa.eu/en/publications-data/download-todays-data-geographic-distribution-covid-19-cases-worldwide

**Comment by umbros** [comment]
@MauroCapolino grazie per la segnalazione, domani controlleremo la fonte che utilizzano.
