### ISSUE TITLE
Nuovi contagiati

### ISSUE THREAD

**Issue by FLP86** [pcm-dpc/COVID-19#263]
Ho notato che nei report viene mostrato l'aggiornamento dei totali attualmente positivi, mentre non viene riportato l'andamento del nuovi positivi intesi come la differenza tra:il totale casi del giorno - totale casi del giorno precedente.

Mi capita di ascoltare il telegiornale e sentire la frase: " i nuovi contagiati sono xxx" dove xxx sono nuovi_attualmente_positivi. Non sarebbe più corretto dare i nuovi positivi?

**Comment by umbros** [comment]
Ciao @FLP86, per capire gli attualmente positivi ti incollo il dettaglio del wiki:


ricoverati_con_sintomi | totale dei casi positivi che sono ricoverati in reparti diversi dalla terapia intensiva|
-- | -- | 
terapia_intensiva | totale dei casi positivi che sono ricoverati in terapia intensiva | Numero |
totale_ospedalizzati | totale dei casi positivi che sono ricoverati<br>somma: ricoverati_con_sintomi e terapia_intensiva | Numero | 
isolamento_domiciliare | totale dei casi positivi che sono in isolamento a casa/struttura non ospedaliera | Numero |
totale_attualmente_positivi | totale dei casi che sono risultati positivi<br>somma totale_ospedalizzati + isolamento_domiciliare | Numero | 
nuovi_attualmente_positivi | totale dei nuovi casi positivi del giorno corrente<br>differenza: totale_attualmente_positivi (giorno corrente) - totale_attualmente_positivi (giorno precedente) | Numero |

detto ciò, i nuovi attualmente positivi sono quelli che allo stato attuale sono positivi - il numero dei positivi del giorno precedente. Quindi i nuovi positivi sono quelli definiti in nuovi_attualmente_positivi (quindi nuovi per il giorno corrente) l'attuale dei positivi al giorno corrente è definito da totale_attualmente_positivi

**Comment by pulpinex** [comment]
Buongiorno, sarebbe possibile avere nel repository anche un file con i dati completi storicizzati per singola provincia? Sarebbe utile per consentire anche ai "comuni mortali" di farsi aggregazioni e pivot. Grazie
