### ISSUE TITLE
Grafico del 18/03/2020, analisi dati nuovi casi positivi e dimessi guariti.

### ISSUE THREAD

**Issue by marcodadamo** [pcm-dpc/COVID-19#264]
**Presentazione dell'elaborazione del grafico elaborando i dati dei nuovi casi positivi e quelli dimessi guariti.**

## Riassunto
Analisi dei dati prelevati dalla Repository COVID-19 ed elaborati su un grafico, sovrapponendoli così da confrontrare l'andamento negativo (nuovi casi positivi) e quello positivo (casi dimessi). All'interno dell'elaborazione è stato indicato il dato anche dei totali positivi. 

## Interesse pubblico
Elaborazione grafico individuando l'andamento negativo e quello positivo mediante la sperimentazione della piattaforma canva.
## [APRI LINK](https://www.canva.com/design/DAD27fQJLT4/m3xPe9LyuBQ_CK_UvglXTw/view?utm_content=DAD27fQJLT4&utm_campaign=designshare&utm_medium=link&utm_source=publishsharelink)

**Comment by umbros** [comment]
grazie @marcodadamo
