### ISSUE TITLE
Nuovi attualmente positivi in Lombardia il 18/03/2020

### ISSUE THREAD

**Issue by RobertoPerico** [pcm-dpc/COVID-19#265]
Tipo di issue:

- [x] Dati mancanti o errati (`dpc-covid19-ita-regioni-20200318.csv` e `dpc-covid19-ita-regioni.csv`)
- [ ] Errore nella documentazione 
- [ ] Errore or mancanza nella dashboard 
- [ ] Problemi di visualizzazione nella dashboard 

- Regione: Lombardia
- Provincia: 

## Riassunto
Al giorno 18/03/2020 è riportato un dato errato nella colonna `nuovi_attualmente_positivi` per la regione Lombardia

**Attesa:**
In `nuovi_attualmente_positivi` per la regione Lombardia al giorno 18/03/2020 dovrebbe esserci il valore corretto

**Attuale:** In `nuovi_attualmente_positivi` per la regione Lombardia al giorno 18/03/2020 è riportato il valore 171

**Comment by umbros** [comment]
Ciao @RobertoPerico, i dati comunicati da Regione Lombardia sono quelli presenti nei tracciati,
se fai riferimento al valore totale_attualmente_positivi di oggi (18/03) sono 12266, quelli di ieri (17/03) sono 12095, la loro differenza è di 171.
