### ISSUE TITLE
Anomalia Dati P.A. Trento

### ISSUE THREAD

**Issue by ploteo** [pcm-dpc/COVID-19#267]
Tipo di issue:

- [ x] Dati mancanti o errati 
- [ ] Errore nella documentazione 
- [ ] Errore or mancanza nella dashboard 
- [ ] Problemi di visualizzazione nella dashboard 

- Regione: P.A. Trento
- Provincia: 

## Riassunto

Dati 16/03 sono apparente duplicazione dei dati 15/03 

<table>
 <thead>
  <tr>
   <th style="text-align:left;"> data </th>
   <th style="text-align:left;"> stato </th>
   <th style="text-align:left;"> codice_regione </th>
   <th style="text-align:left;"> denominazione_regione </th>
   <th style="text-align:right;"> lat </th>
   <th style="text-align:right;"> long </th>
   <th style="text-align:right;"> ricoverati_con_sintomi </th>
   <th style="text-align:right;"> terapia_intensiva </th>
   <th style="text-align:right;"> totale_ospedalizzati </th>
   <th style="text-align:right;"> isolamento_domiciliare </th>
   <th style="text-align:right;"> totale_attualmente_positivi </th>
   <th style="text-align:right;"> nuovi_attualmente_positivi </th>
   <th style="text-align:right;"> dimessi_guariti </th>
   <th style="text-align:right;"> deceduti </th>
   <th style="text-align:right;"> totale_casi </th>
   <th style="text-align:right;"> tamponi </th>
 
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:left;"> 2020-03-15 17:00:00 </td>
   <td style="text-align:left;"> ITA </td>
   <td style="text-align:left;"> 04 </td>
   <td style="text-align:left;"> Trento </td>
   <td style="text-align:right;"> 46.06894 </td>
   <td style="text-align:right;"> 11.12123 </td>
   <td style="text-align:right;"> 73 </td>
   <td style="text-align:right;"> 19 </td>
   <td style="text-align:right;"> 92 </td>
   <td style="text-align:right;"> 275 </td>
   <td style="text-align:right;"> 367 </td>
   <td style="text-align:right;"> 168 </td>
   <td style="text-align:right;"> 5 </td>
   <td style="text-align:right;"> 6 </td>
   <td style="text-align:right;"> 378 </td>
   <td style="text-align:right;"> 1006 </td>
  
  </tr>
  <tr>
   <td style="text-align:left;"> 2020-03-16 17:00:00 </td>
   <td style="text-align:left;"> ITA </td>
   <td style="text-align:left;"> 04 </td>
   <td style="text-align:left;"> Trento </td>
   <td style="text-align:right;"> 46.06894 </td>
   <td style="text-align:right;"> 11.12123 </td>
   <td style="text-align:right;"> 73 </td>
   <td style="text-align:right;"> 19 </td>
   <td style="text-align:right;"> 92 </td>
   <td style="text-align:right;"> 275 </td>
   <td style="text-align:right;"> 367 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 5 </td>
   <td style="text-align:right;"> 6 </td>
   <td style="text-align:right;"> 378 </td>
   <td style="text-align:right;"> 1006 </td>
  
  </tr>
</tbody>
</table>

**Comment by SimoneTinella** [comment]
Ciao @ploteo sulla pagina principale è presente il seguente avviso:
- 16/03/2020: dati P.A. Trento e Puglia non pervenuti.

Sarà dovuto a questo.
