### ISSUE TITLE
Riportare "nuovi_casi"

### ISSUE THREAD

**Issue by nicola** [pcm-dpc/COVID-19#268]
**Tipo di richiesta**: suggerimento di miglioramento

Volevo ringraziare per l'ottimo servizio che state offrendo a tutti gli italiani e i ricercatori in tutto il mondo.

Questa proposta chiede di aggiungere un nuovo campo chiamato `nuovi_casi` per rendere chiaro quanti siano i nuovi infetti ogni giorno.

## Riassunto

I nuovi casi (quindi i nuovi infetti) in Italia sono la differenza tra `totale_casi` di oggi meno il `totale_casi` di ieri.

Da documentazione `nuovi_attualmente_positivi` sono la differenza tra `totale_attualmente_positivi` di oggi meno `totale_attualmente_positivi` di ieri. È importante notare che questo valore non riporta i "nuovi infetti", ma quanti sono i nuovi attualmente infetti.

Il valore `nuovi_attualmente_positivi` quindi è la differenza fra  gli ospedalizzati + isolamento domiciliare di oggi, con quelli di ieri. È importante notare che in questa differenza vengono contati i nuovi guariti e deceduti (perche questi non sono piu ospedalizzati o in isolamento domiciliare).

La mia proposta è di riportare anche i `nuovi_casi` (come differenza fra `totale_casi` di oggi meno `totale_casi` di ieri), per rendere chiaro il nuovo numero di nuovi infetti.

## Interesse pubblico

Alcuni giornali, radio e news online potrebbero interpretare come `nuovi_attualmente_positivi` come `nuovi_casi`.

Ad esempio l'articolo di [Repubblica](https://www.repubblica.it/cronaca/2020/03/18/news/coronavirus_dati_in_italia_borrelli-251625311/?ref=search) scrive "2.648 positivi in più di ieri", mentre invece i nuovi positivi sono 4.207.

Sebbene i nuovi casi possono essere calcolabili dalla tabella, aggiungere il nuovo campo potrebbe evitare possibili errori in una lettura veloce.

**Comment by nicola** [comment]
Same as: https://github.com/pcm-dpc/COVID-19/issues/263

**Comment by davpirelli** [comment]
Sono d'accordo con @nicola che il dato `nuovi_attualmente_positivi` risulti un pò fuorviante.

Ad es. per la Lombardia, viene riportato +171 `nuovi_attualmente_positivi` , mentre i "nuovi infetti" sono +1493.

Infatti, leggendo `nuovi_attualmente_positivi` si pensa subito che quello sia il numero dei nuovi infetti. Tale numero però dovrebbe essere la dirrefernza tra il `totale_casi` (di oggi) - `totale_casi` del giorno precedente come dice @nicola.

**Comment by umbros** [comment]
Buongiorno,
i nuovi_attualmente_positivi sono i soggetti che in un dato giorno entrano nello stato di "ospedalizzati" o in "ricovero domiciliare" rispetto al giorno precedente è un dato che alla lunga va a decrescere e, ovviamente risente dell'informazione "guariti" e "deceduti", il totale casi del giorno, benchè comunque calcolabile è un'informazione che può essere calcolata (come ogni altro dato) per ogni altra necessità.

**Comment by heyteacher** [comment]
@nicola @davpirelli se può esservi utile qui https://github.com/heyteacher/COVID-19 trovate i JSON estesi con `totale_nuovi_casi`, `nuovi_dimessi_guariti`, `nuovi_terapia_intensiva` e altri dati calcolati partendo dai JSON ufficiale. Sono allineati ogni sera qualche minuto di ritardo rispetto alla pubblicazione di quelli ufficiali. Ovviamente repository non ufficiale. 
Nei prox giorni aggiungerò i CSV

**Comment by FedericoStra** [comment]
@heyteacher il problema non è avere un repository su github che viene visualizzato da 50 nerd. Il problema è nelle comunicazioni ufficiali alle masse. È inaccettabile che venga venduta l'informazione mendace "oggi ci sono 2648 positivi nuovi". Questa è la (cattiva) informazione divulgata dal bollettino ufficiale, che poi rimbalza da un giornale all'altro senza che nessuno controlli niente. È un problema di informazione e di trasparenza.

**Comment by heyteacher** [comment]
non entro nel merito della scelta dei dati da mostrare, evidentemente `nuovi_attualmente_positivi` era ritenuto più interessante come dato ad inizio monitoraggio

**Comment by davidfregoli** [comment]
Personalmente da sviluppatore (non nel campo di statistica/big data) che da’ un’occhiata a questi dati un paio di volte alla settimana di sfuggita, ho sempre pensato che quei “nuovi_casi” fossero quelli che uno intuitivamente si aspetta (sì in effetti la denominazione suonava sbagliata ed aveva della ridondanza). E come me ce ne saranno sai quanti...È vero che il valore che più interessa si può calcolare, ma se uno non lo sà che deve calcolarlo...e poi perchè non mostrare il dato che tutti alla fine vogliono sapere più degli altri....

**Comment by FedericoStra** [comment]
> E come me ce ne saranno sai quanti

Purtroppo ce ne sono 60.000.000 italiani.

> e poi perchè non mostrare il dato che tutti alla fine vogliono sapere più degli altri

Perché così il numero riportato risulta più piccolo e in diretta streaming si possono fare tutte le varie speculazioni fallaci tipo "il trend è in discesa", "i contagi diminuiscono", etc... Queste sono tutte cavolate che fanno inorridire e indignare chi ci capisce qualcosa.

**Comment by fscarpa58** [comment]
ad esempio ieri sul corriere sembrava che le cose andassero bene mentre in realtà i nuovi casi erano aumentati

**Comment by valemercurii** [comment]
Scrivo qui anche se chiuso per non spammare sempre sul solito argomento tra le issue aperte:
@nicola  e tutti, se i nuovi_casi sono la differenza tra totale_casi_oggi e totale_casi_ieri, qualcuno mi sa spiegare come mai, ad esempio per la regione Toscana al 05/03/2020 si hanno 23 nuovi_casi, ma 0 tamponi? Come si fanno a scoprire nuovi_casi se non si effettuano tamponi? C'è un errore? Oppure quei nuovi casi sono il risultato di tamponi fatti nei giorni precedenti?

**Comment by FedericoStra** [comment]
Non mi torna. Nel file https://github.com/pcm-dpc/COVID-19/blob/master/dati-regioni/dpc-covid19-ita-regioni.csv#L228, alla riga 228, io leggo:

data | stato | codice_regione | denominazione_regione | lat | long | ricoverati_con_sintomi | terapia_intensiva | totale_ospedalizzati | isolamento_domiciliare | totale_attualmente_positivi | nuovi_attualmente_positivi | dimessi_guariti | deceduti | totale_casi | tamponi
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
2020-03-05 17:00:00 | ITA | 09 | Toscana | 43.76923077 | 11.25588885 | 26 | 3 | 29 | 31 | 60 | 23 | 1 | 0 | 61 | 776

I tamponi risultano essere stati 776. I morti sono stati 0.

Ti stavi riferendo a un altro file?

**Comment by danielesalpietro** [comment]
Secondo me i dati c.d. "**nuovi_casi**" è un dato inutile perché non rappresenta la realtà, ma sono solo i "nuovi_casi" identificati dal sistema sanitario (tramite tamponi o tramite le indagini di screening, anche telefonico, etc.). Quindi così lascia il tempo che trova l'analisi di questo dato, il dato certo su cui basare le analisi sono i decessi. Ma la realtà fa paura a molti, molte scelte fatte sono assurde, come per esempio, lasciare uscire dagli ospedali tutto il personale sanitario....poi si chiedono come mai il virus continua a diffondersi ininterrottamente dove ci sono i focolai estesi come in Lombardia e Veneto ??? chissà, se quei 3500 medici infetti (dichiarati oggi) in queste ultime 2 settimane, entrando ed uscendo dagli ospedali (forse) qualcuno in più lo hanno infettato lungo il tragitto ospedale-casa ? spero di sbagliarmi, altrimenti qui non ne usciremo più !!

**Comment by FedericoStra** [comment]
@danielesalpietro Non mi voglio perdere a fare chiacchierate generiche, mi spiace contraddirti, ma il dato `nuovi_casi` (con tutti i suoi difetti e limiti nelle misurazioni) è utilissimo perché è quello che meglio descrive la rapidità con cui l'epidemia si diffonde. Questo è il numero che ti dice quante persone in più ogni giorno sono stare confermate positive. Se per te questo numero non è utile, allora non so proprio quale altro lo possa essere.

**Comment by danielesalpietro** [comment]
@FedericoStra a me piacerebbe tanto stare qui a fare chiacchiere generiche se la cosa non fosse davvero molto più seria di come la stanno rappresentando sui media alla gente comune. I dati non mentono (se fossero veri); mentre **il dato "nuovi_casi" altro non è che il numero di quante persone in più ogni giorno sono state confermate positive "in laboratorio"** o da screening telefonico; I numeri utili, per me (che probabilmente ho interessi diversi dai tuoi), sono altri, esempio dati certi come il confronto fra il tasso di mortalità in Italia e quello in Cina, il tasso di mortalità stimato in Cina rispetto al nostro, ed il numero di decessi "reale" da cui partire per ricalcolare tutti gli altri dati "reali" e non le favole che ci raccontano.....ma il risultato che si evince da questi modelli fa (troppo) paura. Per l'H1N1 ancora oggi non si sa esattamente quanti morti abbia fatto, il contatore si è fermato a 203.000 (dato per altro rilevato qualche anno più tardi rispetto alle cifre ufficiali); quindi per ora  l'unica cosa certa, se proprio vogliamo dare fiducia a questi dati, che in Italia si muore x4 volte di più che in Cina (sempre se vogliamo credere che la Cina sia stata davvero trasparente sui suoi numeri ?)

**Comment by valemercurii** [comment]
@FedericoStra A quanto ho capito la colonna tamponi è cumulativa, o mi sbaglio?
Se non mi sbaglio, controlla la riga precedente della regione Toscana al 04/03/2020, i tamponi sono sempre 776, quindi la differenza, che chiamo nuovi_tamponi, con 05/03/2020 è nulla. Eppure i nuovi_casi sono 23, dati per la precisione da nuovi ospedalizzati + nuovi isolati, perchè guariti e deceduti sono a zero.

Il mio dubbio nasceva da questo.

**Comment by nicola** [comment]
@valemercurii ottima osservazione, potrebbe essere che il risultato dei tamponi arriva con un giorno in ritardo?

**Comment by FedericoStra** [comment]
@valemercurii Hai ragione, la colonna tamponi sembra essere cumulativa. Diamine però quanto sono scelti male i nomi delle colonne…

La spiegazione che mi do è al seguente. I risultati positivi che arrivano in un dato giorno sono l'esito di tamponi effettuati nei giorni precedenti. I 23 tamponi risultati positivi oggi sono stati campionati qualche giorno fa, e oggi evidentemente non sono stati prelevati nuovi tamponi. Può tornare come spiegazione?

**Comment by FedericoStra** [comment]
@danielesalpietro Non metto in dubbio che ci siano altre considerazioni utili da fare. Qui però (in questo thread intendo) si sta parlando di "nuovi_casi" vs. "nuovi_attualmente_positivi", e dei pro e contro di usare un numero piuttosto che l'altro. Ai fini di questa discussione, l'unica cosa rilevante è fare osservare che i nuovi contagi giornalieri rilevati sono rappresentati da nuovi_casi, ovvero totale_casi di oggi meno totale_casi di ieri. Poi ovviamente ci saranno una miriade di nuovi contagi che sono passati inosservati perché non sono stati effettuati abbastanza tamponi etc...

**Comment by valemercurii** [comment]
> @valemercurii Hai ragione, la colonna tamponi sembra essere cumulativa. Diamine però quanto sono scelti male i nomi delle colonne…
> 
> La spiegazione che mi do è la seguente: i risultati positivi che arrivano in un dato giorno sono l'esito di tamponi effettuati nei giorni precedenti. I 23 tamponi risultati positivi oggi sono stati campionati qualche giorno fa, e oggi evidentemente non sono stati prelevati nuovi tamponi. Può tornare come spiegazione?

@FedericoStra sì ha perfettamente senso, basta tenerlo presente perchè ad esempio non ha senso usare la quota giornaliera dei tamponi per capire la percentuale giornaliera dei positivi.

**Comment by nicola** [comment]
Wooohooo! Le nuove tabelle ora riportano nuovi_positivi!
