### ISSUE TITLE
Dati Campania errati

### ISSUE THREAD

**Issue by salvatorese** [pcm-dpc/COVID-19#269]
I dati della Campania del 18 marzo sembrano errati, sono identici a quelli del 17:

    {
        "data": "2020-03-17 17:00:00",
        "stato": "ITA",
        "codice_regione": 15,
        "denominazione_regione": "Campania",
        "lat": 40.83956555,
        "long": 14.25084984,
        "ricoverati_con_sintomi": 127,
        "terapia_intensiva": 24,
        "totale_ospedalizzati": 151,
        "isolamento_domiciliare": 272,
        "totale_attualmente_positivi": 423,
        "nuovi_attualmente_positivi": 60,
        "dimessi_guariti": 28,
        "deceduti": 9,
        "totale_casi": 460,
        "tamponi": 2685
    },
    {
        "data": "2020-03-18 17:00:00",
        "stato": "ITA",
        "codice_regione": 15,
        "denominazione_regione": "Campania",
        "lat": 40.83956555,
        "long": 14.25084984,
        "ricoverati_con_sintomi": 127,
        "terapia_intensiva": 24,
        "totale_ospedalizzati": 151,
        "isolamento_domiciliare": 272,
        "totale_attualmente_positivi": 423,
        "nuovi_attualmente_positivi": 0,
        "dimessi_guariti": 28,
        "deceduti": 9,
        "totale_casi": 460,
        "tamponi": 2685
    },

https://github.com/pcm-dpc/COVID-19/blob/master/dati-json/dpc-covid19-ita-regioni.json

**Comment by SimoneTinella** [comment]
Ciao @salvatorese 

nella pagina principale è presente in seguente avviso:
- 18/03/2020: dati Regione Campania non pervenuti.

I dati sono rimasti uguali perché non sono presenti quelli nuovi.

**Comment by salvatorese** [comment]
Grazie mille
