### ISSUE TITLE
Datetime updates coming Saturday

### ISSUE THREAD

**Issue by bfabio** [pcm-dpc/COVID-19#270]
The [README.md@c2d0f67](https://github.com/pcm-dpc/COVID-19/blame/c2d0f679de4001897da872b75a4035381d536ebb/README.md#L17) is contradicting:

> Tutte le date saranno in UTC (GMT+1).
> All dates will be in UTC (GMT+1).

UTC is not GMT+1 and most likely they won't be GMT+1 in 10 days anymore, when DST kicks in.

We probably want to say "All dates will be Italian local time (Europe/Rome)".

**Comment by umbros** [comment]
Grazie @bfabio
