### ISSUE TITLE
Proposta: avere un permalink per le risorse latest

### ISSUE THREAD

**Issue by aborruso** [pcm-dpc/COVID-19#271]
Buongiorno,
i dataset di regioni e province hanno la risorsa giornaliera e quella di insieme.

Sarebbe comodo se ci fosse una risorsa `dpc-covid19-ita-province_latest.csv` e una `dpc-covid19-ita-regioni_latest.csv` (butto una query un po' rozza per spiegarmi), con i soli dati dell'ultimo giorno.

Grazie

```sql
SELECT * FROM dpc_covid19_ita_regioni 
where dpc_covid19_ita_regioni.data LIKE 
(SELECT MAX(dpc_covid19_ita_regioni.data)
FROM dpc_covid19_ita_regioni)
```

**Comment by umbros** [comment]
@aborruso, la cosa è implementabile. Grazie del suggerimento
