### ISSUE TITLE
Visualizzazione

### ISSUE THREAD

**Issue by tardini** [pcm-dpc/COVID-19#272]
**Tipo di richiesta**:  suggerimento di miglioramento (documentazione, label, _ecc_) | relativo alla pagina grafica

## Riassunto

Se puo' essere utile ho un piccolo script python che legge direttamente i vostri ottimi csv e plotta l'andamento giornaliero, dati cumulativi e giornalieri, in scala lineare e semilogaritmica, per l'Italia intera o per una regione qualsiasi. Lo condivido volentieri se a qualcuno interessa. Usa moduli comuni in python, forse "csv" puo' dipendere dal sistema operativo

## Interesse pubblico

Un utente puo' scegliere di volta in volta cosa plottare e come, senza opzioni predefinite, e anche senza connessione internet

**Comment by umbros** [comment]
grazie @tardini
