### ISSUE TITLE
Trasparenza nel numero di *nuovi casi*

### ISSUE THREAD

**Issue by FedericoStra** [pcm-dpc/COVID-19#275]
Dopo aver provato con scarsissimo successo a contattare giornali (La Stampa, Repubblica, il Messaggero) e l'Ufficio Stampa della Protezione Civile, provo a esporre anche qui il problema (non di poco conto), nella speranza che persone con una formazione più scientifica possano meglio comprendere la serietà della questione.

In breve, `nuovi_casi != nuovi_attualmente_positivi`. So che l'argomento è già stato sollevato qui (#263) e qui (#268), ma non sono state espresse approfonditamente le serie implicazioni che ha a livello di informazione nazionale.

Il numero onesto da riportare è `nuovi_casi = totale_casi(oggi) - totale_casi(ieri)`. Questo è il numero che viene riportato anche nei reports della WHO (https://www.who.int/emergencies/diseases/novel-coronavirus-2019/situation-reports) e che consente oltretutto un confronto adeguato con la situazione in altri stati. Leggere nel bollettino ufficiale della Protezione Civile che il 18 marzo si sono registrati 2648 nuovi casi è una truffa alle masse. I *nuovi casi* sono stati 4207, ben 59% in più!

A me non importa minimamente quali colonne ci sono nelle tabelle di questo repository. Per quel che mi riguarda, invece di `totale_casi` ci potete anche mettere la trasformata di Fourier, che per inciso se vi interessa è
```
array([240349.             +0.j        ,  51447.07976427+129628.22593048j,
        -3615.28922261 +74445.41430161j, -13852.95469297 +48323.90667369j,
       -15429.5        +32556.49300447j, -16370.51931449 +25969.69972797j,
       -17579.         +19334.j        , -16960.67172918 +16193.92598915j,
       -19173.5        +11957.21275005j, -18797.04530703  +7415.90667369j,
       -18531.71077739  +5698.58569839j, -19389.8887206   +2699.9996693j ,
       -18347.             +0.j        ])
```

La questione seria è come questi numeri vengono poi venduti ai cittadini. La situazione attuale è che nelle comunicazioni ufficiali viene maliziosamente spacciato un dato per un altro, e questo viene ritrasmesso da tutte le testate di giornale che si limitano a copiare senza verificare le fonti (ovvero tutte). Il cittadino inaccorto non si pone il problema della differenza fra queste due cifre. È estremamente antietico ingannarlo lasciandogli intendere che i contagi sono diminuiti quando questo non è vero. Ovviamente ci si aspetta che diminuiscano, ma al momento non è ancora evidente dai dati. Bisogna smetterla di vendere frottole.

Anche la dashboard http://arcg.is/C1unv soffre di questo problema. Ha tante lucine ed è tutta colorata, ma fallisce nell'intento di fornire una rappresentazione accurata della diffusione del contagio: manca il grafico dei nuovi casi. Il grafico "Incremento giornaliero degli attualmente positivi" è ingannevole per chiunque non abbia un dottorato in matematica, data science, etc.

**Comment by Achab94** [comment]
Suggerisco anche [questo articolo](https://www.francescocosta.net/2020/03/19/dati-ufficiali-illusione-ottica/) di Francesco Costa della redazione del Post, che esprime alcune criticità circa i dati che vengono quotidianamente pubblicati e dai quali, immagino gran parte di noi, traiamo beneficio per dashboard/analisi/stime.

Ho visto che tra gli update è programmato un ampliamento della descrizione delle varie variabili, che forse (forse) dovrebbe chiarire molti dubbi che, immagino, più di qualcuno si sta ponendo in questi giorni. Io tutt'ora mi chiedo come si possa utilizzare questi dati per stimare modelli di previsione di qualunque tipo, ma è una domanda che mi tengo per me.

**Comment by Achab94** [comment]
(Il paragrafetto della trasformata di Fourier secondo me era evitabilissimo, comunque. La questione che poni, invece, molto attuale e d'importanza, ti ringrazio)

**Comment by FedericoStra** [comment]
Alcune prove per sostanziare la mia tesi che i giornali riportano i numeri sbagliati:
- La Stampa: [In Italia il record di morti: 475 in una sola giornata. Stabile il trend dei contagi](https://www.lastampa.it/cronaca/2020/03/19/news/in-italia-il-record-di-morti-475-in-una-sola-giornata-stabile-il-trend-dei-contagi-1.38609360):
  > "I guariti sono 1.084, il 37% in più di martedì. E i nuovi contagi sono 2.648. Circa 300 meno di ieri, calcolando la cinquantina di casi giornalieri della Campania, ieri non pervenuti."

  Falso.
- Repubblica: [Coronavirus: 2470 nuovi positivi in Italia, meno di ieri. "Trend in ribasso ma servono conferme"](https://www.repubblica.it/cronaca/2020/03/16/news/coronavirus_oggi_rientra_in_italia_il_comandante_della_diamond_princess-251404715/)
  > "Oggi si registrano 2470 nuovi positivi, meno di ieri quando l'aumento su base giornaliera era stato di 2.853."

  Falso.

**Comment by FedericoStra** [comment]
@Achab94 

> Suggerisco anche questo articolo di Francesco Costa della redazione del Post

Grazie mille, è un po' lunghetto e non riesco subito, ma lo leggerò.

> Il paragrafetto della trasformata di Fourier secondo me era evitabilissimo, comunque.

Era per combattere l'idea che "il repository ufficiale contiene dati sufficienti a partire dai quali ti puoi calcolare tutte le informazioni che vuoi, quindi non c'è problema".

Il problema c'è eccome invece. Il "cittadino medio" (brr...) non ha i mezzi per accedere ai dati nudi e crudi, per condurre le sue analisi e interpretare i risultati. Il cittadino medio si collega alle 18 alla diretta del bollettino ufficiale e si beve quello che gli viene detto.

Fornire un dato piuttosto che un altro significa dare importanza, mettere in evidenza, indurre il lettore o ascoltatore a pensare che questa sia l'informazione più rilevante. Se fatto su scala nazionale tramite una comunicazione ufficiale da parte di un'istituzione pubblica, questo giochetto di barare coi numeri è deplorevole.

**Comment by DataEnthusiast84** [comment]
Mi permetto di fare una precisazione e mi scuso se possa sembrare banale.

Qui stiamo discutendo su due grandezze abbastanza diverse: i CASI TOTALI e i CASI POSITIVI.

- i **casi positivi** sono, giornalmente, i ricoverati con sintomi + terapia intensiva + isolamento domiciliare. 
- i **casi totali** sono la somma dei casi positivi + guariti + deceduti

Detto questo, penso che si debba stare molto attenti a confrontare i casi totali e i casi positivi. I casi positivi sono quelli che entrano nel "radar" del SSN da un giorno all'altro. Il +2648 significa che in un giorno sono stati ospedalizzati o isolati domiciliarmente 2648 persone.
I casi totali sono quelli che, ad oggi, sono risultati ospedalizzati, isolati domiciliarmente, deceduti o guariti e sono +4207. 

Secondo me non è "scarsa informazione" o "giocare con i numeri" o "barare". Significa analizzare le grandezze per come sono definite...tutto qui.

**Comment by FedericoStra** [comment]
Aggiungo un semplice plot dei `nuovi_casi` vs. `nuovi_attualmente_positivi` che dimostra come il divario tra i due è piuttosto marcato.
![nuovi_casi](https://user-images.githubusercontent.com/2906478/77094833-561bc100-6a0d-11ea-8b74-a841783a2c11.png)

**Comment by Achab94** [comment]
@FedericoStra 

Condivido tutto quanto. Incrocio le dita che non si diffondano post/catene su social e Whatsapp (ne stanno girando di tutti i tipi in questi giorni) in cui la gente grida al complotto del "non ci stanno presentando i dati veri" e simili derivati.

Seguo con molto interesse il thread.

**Comment by MarcoGermani** [comment]
@FedericoStra Purtroppo dopo aver parlato con chi si occupa della raccolta e della messa in linea dei dati, a fronte di una serie di errori che ho riscontrato sui dati pubblicati, l'unica motivazione, non risiede su che pubblica ma in che ha progettato la raccolta; cosa che dovrebbe essere affidata come minimo ad uno statistico in tema ad un informatico di esperto.

**Comment by DataEnthusiast84** [comment]
Aggiungo anche un'altra informazione...ci sono giorni in cui alcune province o intere regioni che non riescono a comunicare entro le 18 i dati..quindi probabilmente il dato è influenzato anche da quella mancanza..

**Comment by luconedj** [comment]
@FedericoStra appoggio pienamente il tuo punto di vista e @DataEnthusiast84 ha riassunto alla grande e questo repository ha tutte le info per estrarre le informazioni a mio avviso 'corrette'.
Credo sia necessario rivedere la semantica per nn "ingannare" il cittadino medio.

**Comment by FedericoStra** [comment]
> Secondo me non è "scarsa informazione" o "giocare con i numeri" o "barare". Significa analizzare le grandezze per come sono definite...tutto qui.

Sono d'accordo che _"tecnicamente"_ non è una bugia, a patto che il numero divulgato venga etichettato in modo appropriato. Diventa però scarsa informazione nel momento in cui induci tutti i media nazionali a scrivere cose false. Se la stampa di oggi scrive "ci 2648 infetti in più", chiunque si immagina 2648 cittadini nuovi che fino a ieri non risultavano entrati in contatto con il virus e oggi invece risultano positivi. Questo però non è corretto. Quello che è vero è che le persone nuove coinvolte sono 4207, assai di più.

> Il +2648 significa che in un giorno sono stati ospedalizzati o isolati domiciliarmente 2648 persone.

Questa frase dimostra che tu stesso sei caduto nel tranello: in un giorno sono state ospedalizzate o isolate 4207 persone nuove! Poi nel frattempo ne sono state dimesse (vive o morte), altre 1559.

**Comment by MarcoGermani** [comment]
Da una mia analisi sui dati pubblicati
![Cattura](https://user-images.githubusercontent.com/62236604/77095677-87e15780-6a0e-11ea-936c-1df104922c84.JPG)

**Comment by umbros** [comment]
@FedericoStra, innanzitutto grazie per l'intervento, può essere condivisibile, parlare di trasparenza è fuorviante, dal momento che i dati da te richiesti sono calcolabili. Ripeto che i nuovi attualmente positivi sono la differenza tra i "positivi" (nei vari stati) di oggi con quelli di ieri, è un dato calcolato, non c'è volontà di nascondere nulla... i dati sono qui aperti e disponibili a chi vuol fare qualsiasi ragionamento o elaborazione. E sono in linea con @DataEnthusiast84

**Comment by DataEnthusiast84** [comment]
"Questa frase dimostra che tu stesso sei caduto nel tranello: in un giorno sono state ospedalizzate o isolate 4207 persone nuove! Poi nel frattempo ne sono state dimesse (vive o morte), altre 1559."

ti chiedo scusa @FedericoStra ma non sono d'accordo...

Idealmente: se ci fosse un solo ospedale in Italia che cura tutti i COVID..
**quante persone nuove vedresti in ingresso?** 2648 (ricoverati con sintomi, terapia intensiva, domiciliare). 
**quant'è l'incremento di persone che hai al tuo interno?** 4207 (ospedalizzati + guariti + deceduti)
