### ISSUE TITLE
Info su latest e non

### ISSUE THREAD

**Issue by downFast** [pcm-dpc/COVID-19#276]
Tipo di issue:

- [ ] Dati mancanti o errati 
- [ ] Errore nella documentazione 
- [ ] Errore or mancanza nella dashboard 
- [ ] Problemi di visualizzazione nella dashboard 

- Regione:
- Provincia: 

## Riassunto

Scusate,
for mi sono perso qualcosa. Come mai i json ora mostrano diversi file con latest e non?

**Attesa:**

**Attuale:**

**Comment by downFast** [comment]
Capisco che magari è per non far scaricare big json, però potreste lasciare anche quello con tutti cosi possiamo valutare ed analizzare tutti i dati? Lo dico onde evitare che poi ad una certa rimarranno solo gli ultimi e le nostre app cadrebbero.

Grazie mille

**Comment by umbros** [comment]
Ciao @downFast, come richiesto e da noi condivisibile nella issue #271 abbiamo inserito per andamento nazionale, regioni e province un file latest (ultimi dati) che riporta i dati dell'ultimo giorno inserito, è una funzionalità in più che permette di fissare un url fisso e di avere i dati giornalieri senza dover ogni giorno cambiare nome. Non verrà modificato nulla. Premetto che ogni modifica verrà riportata, come stiamo facendo qui sul readme e nel changelog e operiamo in modo che nessuno sviluppo ne risenta.

**Comment by downFast** [comment]
Ottimo grazie mille
