### ISSUE TITLE
Trasparenza nel numero dei nuovi casi rev02.

### ISSUE THREAD

**Issue by FLP86** [pcm-dpc/COVID-19#277]
Ciao a tutti, sono contento che @FedericoStra abbia aperto questo issue, cosa che avevo già fatto io #263 il quale mi è stato chiuso :( e devo riaprirlo.

Non capisco per quale motivo i telegiornali non possano dare la notizia in questo modo:

i nuovi contagiati sono xxx
tenendo conto che yyy sono deceduti e zzz sono guariti
i nuovi attualmente positivi sono xxx - yyy - zzz

In questo modo anche il cittadino con una preparazione scientifica non eccelsa si renderebbe conto che il grafico del trend dei nuovi attualmente positivi serve ad indicare l'impatto sul sistema sanitario nazionale ma non indica la velocità con la quale il virus si sta espandendo.

Paradossalmente se un giorno i nuovi casi fossero ad es. 3000 ma tra i deceduti e i dimessi ce ne fossero 4000 risulterebbe che i nuovi casi (come spacciato adesso dai telegiornali e giornali) sarebbero -1000. Niente di più falso i nuovi casi sono 3000 e -1000 la diminuzione di attualmente positivi a quella data sul territorio nazionale.

**Comment by Achab94** [comment]
Temo chiudano queste Issue perchè il problema non riguarda la pubblicazione del dato (ovvero, ciò di cui si occupa questa repository), ma su chi tratta questi dati a proprio uso e consumo per due click in più.

**Comment by FedericoStra** [comment]
Paradossale che un issue intitolato "Trasparenza ..." (#275) venga bloccato, ma non sono qui per commentare su questo genere di censura. È comunque un atteggiamento molto poco professionale.

Ad ogni modo, se non era chiaro, le mie intenzioni erano delle migliori, ovvero migliorare il servizio ai cittadini. Questo repository non è per 50 nerd che sanno lanciare IPython, è uno strumento che deve servire ai cittadini per aiutarli a indirizzare le decisioni prese. La presa consapevole di decisioni passa necessariamente da una buona informazione. Al momento non c'è una qualità di informazione propriamente eccelsa in circolazione. Le notizie false superano di gran lunga le notizie corrette. Possiamo contribuire costruttivamente a migliorare la situazione senza essere liquidati bloccando i commenti, come avvenuto anche sul canale YouTube?

Mi rivolgo in particolare al senso etico del manager del repository. Il problema che ho esposto è stato compreso? Mi riferisco al problema di informare adeguatamente i cittadini, non alla decisione tecnica di quali colonne mettere nel csv.

**Comment by FLP86** [comment]
Ciao @Achab94 credo tu abbia ragione ma fatto sta che anche nella diretta della protezione civile il commissario Borrelli fa riferimento sempre ai nuovi attualmente positivi spacciandoli come nuovi casi di contagio.

Che rabbia !!!

**Comment by umbros** [comment]
Ciao @FLP86, ripeto:
gli attuali positivi sono dati da:

- ricoverati con sintomi
- ricoverati in terapia intensiva
- isolamento domiciliare

Penso sia chiaro quindi che questi 3 numeri danno l'idea di quella che è attualmente la situazione delle persone ospedalizzate o meno ma comunque positive e che sono totalizzati in "totale attualmente positivi". La differenza tra i totali di oggi e di ieri danno i nuovi casi, altri calcoli possono essere fatti in totale libertà.

**Comment by FedericoStra** [comment]
@umbros scusa ma hai letto almeno 30 secondi quello che ho scritto?

**Comment by FedericoStra** [comment]
Mi sono rivolto al repository perché mi aspettavo di trovare più apertura a una discussione tecnica. Abbiamo queste due quantità, `nuovi_casi` e `nuovi_attualmente_positivi`. Quando `nuovi_casi` scenderà a 0 (stabilmente), avremo vinto, il virus sarà debellato. Quando `nuovi_attualmente_positivi` scende a 0, l'epidemia ha soltanto trovato un equilibrio in cui le nuove persone che si ammalano ogni giorno eguagliano quelle che guariscono o muoiono. C'è una differenza significativa fra le due.

Leggere un numero piuttosto che un altro nel bollettino induce gli ascoltatori a credere che tutto finirà quando quel numero sarà sceso a 0. Questo è scorretto.

**Comment by marcodo1976** [comment]
Mi associo totalmente a @FedericoStra 

1) La metrica che misura l'andamento del contagio sono i contagi giornalieri non certo i nuovi attualmente positivi che potrebbero essere anche 0 (veicolando il falso messaggio che il contagio si è arrestato!)

2) dal punto di vista strettamente logico tale metrica, nuovi casi, si ricava banalmente come DELTA tra totale casi di oggi e quelli di ieri. Tecnicamente, per quanto mi riguarda, a causa degli strumenti utilizzati, faccio fatica a ricavarla.

**Comment by marcodo1976** [comment]
> Ciao @FLP86 e tutti quanti, ripeto:
> gli attuali positivi sono dati da:
> 
> * ricoverati con sintomi
> * ricoverati in terapia intensiva
> * isolamento domiciliare
> 
> Penso sia chiaro quindi che questi 3 numeri danno l'idea di quella che è attualmente la situazione delle persone ospedalizzate o meno ma comunque positive e che sono totalizzati in "totale attualmente positivi". La differenza tra i totali di oggi e di ieri danno i nuovi casi, altri calcoli possono essere fatti in totale libertà.

Innanzitutto ringrazio per questa repositiry. Tuttavia, come già chiesto, sarebbe utile avere il dato casi giornalieri che mi permetto di dire che per voi non sia così difficile da fornire. Renderebbe la produzione di report molto più veloce. Report che DEVONO contenere il dato casi giornalieri quale unico indicatore della progressione del virus.
