### ISSUE TITLE
there are some negatives in your data.

### ISSUE THREAD

**Issue by romabhatkoti** [pcm-dpc/COVID-19#279]
https://github.com/pcm-dpc/COVID-19/blob/master/dati-regioni/dpc-covid19-ita-regioni.csv

in your file at the location above
you have many negatives. is that a data entry error?

**Comment by umbros** [comment]
Hi @romabhatkoti, it's ok we confirm

**Comment by FedericoStra** [comment]
@romabhatkoti No, it's related to #263, #268, #275 and #277. Basically, `nuovi_attualmente_positivi` means change in the number of people *currently affected*, that is, `new_cases - recovered - deceased`. The fact of how misleading this data is is an issue that is currently discussed in so many places, although the repo managers are refusing to address the problem.
