### ISSUE TITLE
Citare la mappa online del JHU CSSE

### ISSUE THREAD

**Issue by AndreaPi** [pcm-dpc/COVID-19#28]
Bel lavoro, ma dato che essenzialmente avete clonato la mappa sviluppata al JHU CSSE dal team di Lauren Gardner, popolandola coi dati italiani:

https://gisanddata.maps.arcgis.com/apps/opsdashboard/index.html#/bda7594740fd40299423467b48e9ecf6
https://systems.jhu.edu/research/public-health/ncov/

sarebbe corretto citarla abbondantemente, sia nell'applicazione che qui, nel README del repository.

**Comment by umbros** [comment]
Ciao @AndreaPi per la rappresentazione utilizziamo un sistema che è lo stesso in uso da JHU CSSE non è stato quindi riutilizzato nulla se non utilizzato lo stesso strumento.

**Comment by AndreaPi** [comment]
Lo stesso strumento con lo stesso identico layout dei vari tab, dei grafici, ecc.

**Comment by simogasp** [comment]
Sono d'accordo con @AndreaPi , basterebbe anche solo mettere il link alla versione "globale", anche solo per completezza d'informazione per accedere ai dati e visualizzazioni mondiali. 
Non sminuisce neanche di una virgola il bel e utile lavoro che state facendo.
