### ISSUE TITLE
Dati province piemonte del 19 Marzo non aggiornati

### ISSUE THREAD

**Issue by fmossott** [pcm-dpc/COVID-19#280]
Tipo di issue:

- [ X] Dati mancanti o errati 
- [ ] Errore nella documentazione 
- [ ] Errore or mancanza nella dashboard 
- [ ] Problemi di visualizzazione nella dashboard 

- Regione: 
- Provincia: Province piemontesi

## Riassunto

Nei dati provinciali, le provincie piemontesi hanno valori invariati dal 18 al 19 Marzo. Sia nel file csv del 19 che in quello cumulativo.

**Attesa:**

Dati aggiornati per le province piemontesi aggiornati per il 19 nel csv

**Attuale:** 
Per il 19 sono riportati i dati del 18

**Comment by umbros** [comment]
Ciao @fmossott in realtà sono aggiornati ma sono inseriti in "In fase di definizione/aggiornamento" e sono 747 invece ieri alla stessa voce erano 156.
