### ISSUE TITLE
Richiesta informazione sul numero di tamponi per regione

### ISSUE THREAD

**Issue by caravagn** [pcm-dpc/COVID-19#282]
**Tipo di richiesta**:  richiesta di informazione

## Riassunto

Salve, con riferimento al [numero di tamponi per regione](https://github.com/pcm-dpc/COVID-19/blob/master/dati-regioni/dpc-covid19-ita-regioni-latest.csv), il numero riportato e' cumulativo come lo sono le altre colonne?

A senso tenderei a pensare di si, ma i dati di oggi per ad esempio Friuli, suggeriscono di no.

```
readr::read_csv('https://raw.githubusercontent.com/pcm-dpc/COVID-19/master/dati-regioni/dpc-covid19-ita-regioni.csv') %>%
  dplyr::filter(denominazione_regione == "Friuli Venezia Giulia") %>%
  dplyr::arrange(desc(data)) %>%
  filter(row_number() %in% 1:10) %>%
  select(data, tamponi)
```
```

# A tibble: 10 x 2
   data                tamponi
   <dttm>                <dbl>
 1 2020-03-19 17:00:00    4052 <---
 2 2020-03-18 17:00:00    4958
 3 2020-03-17 17:00:00    4958
 4 2020-03-16 17:00:00    4851
 5 2020-03-15 17:00:00    3407
 6 2020-03-14 17:00:00    3376
 7 2020-03-13 17:00:00    3149
 8 2020-03-12 17:00:00    2604
 9 2020-03-11 17:00:00    2073
10 2020-03-10 18:00:00    1602
```

## Interesse pubblico

Questa statistica ci permette di capire la relazione tra il numero di infetti ed il campionamento effettuato.

**Comment by miccoli** [comment]
La stessa cosa capita sporadicamente anche per campo `totale_casi`, che pur essendo sicuramente cumulativo alcune volte viene corretto al ribasso.

Per esempio il Piemonte passa da 360 a 350 casi in questi due file ( 79cdf38 )
https://github.com/pcm-dpc/COVID-19/blob/master/dati-regioni/dpc-covid19-ita-regioni-20200307.csv#L14
https://github.com/pcm-dpc/COVID-19/blob/master/dati-regioni/dpc-covid19-ita-regioni-20200308.csv#L14

Penso che si tratti di imprecisioni nella segnalazione dei casi da parte delle regioni, e che non sia colpa della Protezione Civile.

**Comment by caravagn** [comment]
Grazie @miccoli non avevo notato le altre entries con lo stesso problema..

**Comment by umbros** [comment]
Grazie @miccoli per il supporto e la precisazione, confermo in toto
