### ISSUE TITLE
Inserire dettaglio casi per dati provinciali

### ISSUE THREAD

**Issue by iosonosempreio** [pcm-dpc/COVID-19#283]
**Tipo di richiesta**: richiesta di dati | suggerimento di miglioramento

## Riassunto

Queste informazioni sono attualmente disponibili solo per i dati su scala regionale, renderle disponibili per i [dati-province](https://github.com/pcm-dpc/COVID-19/blob/master/dati-province/dpc-covid19-ita-province.csv):

- ricoverati_con_sintomi
- terapia_intensiva
- totale_ospedalizzati
- isolamento_domiciliare
- totale_attualmente_positivi
- nuovi_attualmente_positivi
- dimessi_guariti
- deceduti
- tamponi

## Interesse pubblico

Possibilità di creare visualizzazioni più informative.

Il nostro obiettivo specifico è fare una visualizzazione con un forte potere retorico che inviti le persone, ancora una volta, a "stare a casa".

**Comment by pescetti** [comment]
Temo che sia un duplicato di #57 - questa è una richiesta molto frequente e sono certo che quando saranno nelle condizioni di farlo in modo sicuro pubblicheranno anche questi dati, ma come hanno già spiegato in #57 e in molti altri duplicati questo al momento non è possibile.

**Comment by umbros** [comment]
grazie per il contributo @pescetti, confermo quanto riportato da Andrea

**Comment by iosonosempreio** [comment]
Leggendo in #57 sembra che il problema sia relativo al fatto che molti casi sono senza una provincia di riferimento. Nel caso fosse possibile rilasciarli, mi sarebbero utili ugualmente.

Nel frattempo uso i dati regionali, ma grazie delle riposte @pescetti e @umbros.
E grazie anche a tutti quelli che lavorano alla raccolta di questi dati.
