### ISSUE TITLE
Mission impossible: cooperation

### ISSUE THREAD

**Issue by Bost** [pcm-dpc/COVID-19#284]
While discussing about "how to scale the data gathering done by CSSEGISandData/COVID-19" I was [notified](https://github.com/CSSEGISandData/COVID-19/issues/1035#issuecomment-601359232) about your consolidation effort. So I followed the reference and... and I see everything is in your national language. Oh no. Why?!?

Well, using national language(s) may make the work easier for you but it effectively seals off any communication between yours and other [similar](https://github.com/opencovid19-fr/data) project(s) or in the [better case ](https://coronadatascraper.com/#sources) makes if one-directional.

Nobody from the rest of the world can learn from your example, nobody else can contribute to your effort. Everyone has to start his/her own effort from the scratch, trip over the same mistakes, etc.

Can you do something about it guys?

We have a global problem I doubt we can solve it every nation on its own.

**Comment by pescetti** [comment]
> I see everything is in your national language.

Not really correct. README.md has data description in English too. As you surely have seen since you created an issue, issues can be written in either Italian or English; and most people here can speak English too. So it should be perfectly possible for a person who cannot speak Italian to consume these data, and start conversations in English if needed.

(I'm not maintaining the repo; I'm just an ordinary user)

**Comment by mazinthebox** [comment]
> While discussing about "how to scale the data gathering done by CSSEGISandData/COVID-19" I was [notified](https://github.com/CSSEGISandData/COVID-19/issues/1035#issuecomment-601359232) about your consolidation effort. So I followed the reference and... and I see everything is in your national language. Oh no. Why?!?
> 
> Well, using national language(s) may make the work easier for you but it effectively seals off any communication between yours and other [similar](https://github.com/opencovid19-fr/data) project(s) or in the [better case ](https://coronadatascraper.com/#sources) makes if one-directional.
> 
> Nobody from the rest of the world can learn from your example, nobody else can contribute to your effort. Everyone has to start his/her own effort from the scratch, trip over the same mistakes, etc.
> 
> Can you do something about it guys?
> 
> We have a global problem I doubt we can solve it every nation on its own.

+1

**Comment by simogasp** [comment]
@Bost You are right in principle, the easiest way is always to use English so everybody can share and improve on others. 
But consider that this is an official repository of an Italian authority (contrary to the French one which is an effort of a private citizen) and it is meant to inform the people of the country.

That being said, I think there is enough information in both languages on the repository and I think it takes only a minor effort to understand the structure of the repository and of the data.

But, please, feel free to suggest improvements that we can put in place to make it more accessible to people that do not speak Italian. Saying "do something" it is not really helpful and constructive.

**Comment by umbros** [comment]
hello @Bost , what you said is correct and our effort is to "internationalize" the data by providing all the informations also in english language (thanx also to the contribution of the community). Our first goal is to inform the population but surely the breath of this emergency is worldwide. In the next few days, as we are already doing and as has been done also for the management of the issues, we will publish in the wiki all the informations in two languages (Italian and English) to explaining better the value of the fields of the datasets and more informations. Another effort is to give maximum information and transparency.

**Comment by Bost** [comment]
> Saying "do something" it is not really helpful and constructive.

For the French repo I just translated theirs README.md https://github.com/opencovid19-fr/data/pull/149 Unfortunately I can't do that for you. I don't speak your language. 

Besides, it's really hard to help out if don't know what's going on and that's because you don't understand what's being said.
