### ISSUE TITLE
Dati emessi da regione sicilia

### ISSUE THREAD

**Issue by claort** [pcm-dpc/COVID-19#285]
Buonasera,
regione sicilia emette dati alle ore 13.30 sul sito regionale con divisione casi per provincia.
(probabilmente anche altre regioni fanno cosi) 
non è possibile pubblicare questi dati nel momento in cui vengono inviati al db nazionale ? 
o in alternativa evitare pubblicazione prima di aggiornamento del vs dataset ufficiale ? 
grazie

**Comment by mazinthebox** [comment]
A quanto pare, la pubblicazione dell'attuale dataset prescinde la scelta che ogni regione prende sulla pubblicazione dei proprio dati regionali. Ifatti (come magari è possibile notare dagli avvisi) delle volte mancano, nelle pubblicazioni quotidiane, alcuni dati appunto perchè le regioni probabilmente non fanno in tempo per la raccolta.

Mi viene inoltre da pensare che ogni regione fornisca i dati alla DPC in un formato e con un template diverso e che non ci sia una informamità di dato (quantomeno non a livello regione pre elaborazione del dato).

**Comment by umbros** [comment]
@claort @mazinthebox i dati forniti dalle Regioni sono definite da apposita circolare del Ministero della Salute che ha definito i campi che allo stato attuale vengono gestiti. Eventuali comunicazioni singole successive all'invio dati sono dati aggiornati che dirama la Regione. Per processo viene tenuto il valore ufficiale a quello comunicato.
