### ISSUE TITLE
Minor data incongruence in 'dpc-covid19-ita-regioni-20200225.csv'

### ISSUE THREAD

**Issue by miccoli** [pcm-dpc/COVID-19#286]
Type of issue:

- [x] Incorrect or missing data : `COVID-19/blob/master/dati-regioni/dpc-covid19-ita-regioni-20200225.csv`
- [ ] Incorrect or missing documentation 
- [ ] Incorrect or missing data in the dashboard 
- [ ] Layout problem in the dashboard 

- Region: Sicilia
- Province: 

## Summary

**Expected:**

```
ricoverati_con_sintomi + terapia_intensiva == totale_ospedalizzati
totale_ospedalizzati + isolamento_domiciliare == totale_attualmente_positivi
```

**Actual:** 

```
2020-02-25 18:00:00,ITA,19,Sicilia,38.11569725,13.3623567,1,0,2,2,3,3,0,0,3,5
```
Thus we have 

```
ricoverati_con_sintomi =      1
terapia_intensiva =           0
totale_ospedalizzati =        2
isolamento_domiciliare =      2
totale_attualmente_positivi = 3
```

thus 

```
1 + 0 != 2
2 + 2 != 3
```

Should we simply set `totale_ospedalizzati = 1`?

**Comment by umbros** [comment]
Grazie @miccoli controlliamo

**Comment by pierluigicara** [comment]
Confermiamo l'incongruenza e procederemo con la correzione. Grazie @miccoli per la tua fattiva collaborazione
