### ISSUE TITLE
Dati Trento/Bolzano del 06 marzo

### ISSUE THREAD

**Issue by Stigni** [pcm-dpc/COVID-19#29]
I dati riferiti a "In fase di definizione/aggiornamento" del 06 marzo riferiti alle due province autonome nel file json provinciale vengono riportati con il codice_regione uguale a 21 e 22 mentre in tutti gli altri record vengono riportati con il codice_regione uguale a 4.

**Comment by umbros** [comment]
Corretto @Stigni , grazie
