### ISSUE TITLE
Arezzo: totale_casi 19/03 minore del 18/03?

### ISSUE THREAD

**Issue by marcoqu** [pcm-dpc/COVID-19#291]
**Tipo di richiesta**: richiesta di informazione

## Riassunto
Nel [file csv province](https://github.com/pcm-dpc/COVID-19/blob/master/dati-province/dpc-covid19-ita-province.csv) il valore totale_casi per il 19/03 è minore del valore del 18/03 per la provincia di Arezzo, come devo interpretare tale valore? Non è il conteggio di tutti i casi dall'inizio?

2020-03-18 17:00:00 | ITA | 09 | Toscana | 051 | Arezzo | AR | 43.46642752 | 11.88228844 | 142
-- | -- | -- | -- | -- | -- | -- | -- | -- | --

2020-03-19 17:00:00 | ITA | 09 | Toscana | 051 | Arezzo | AR | 43.46642752 | 11.88228844 | 113
-- | -- | -- | -- | -- | -- | -- | -- | -- | --

**Comment by umbros** [comment]
Ciao @marcoqu, il dato delle Province può essere da un giorno all'altro corretto per errore o per definizione migliore dei soggetti.

**Comment by marcoqu** [comment]
Chiaro, grazie.
