### ISSUE TITLE
contagi giornalieri

### ISSUE THREAD

**Issue by marcodo1976** [pcm-dpc/COVID-19#292]
**Tipo di richiesta**:  richiesta di dati

## Riassunto

E' possibile avere i contagi giornalieri? ad esempio ieri 19 marzo i contagi giornalieri sono stati 5322 tuttavia tale dato non è il db: lo si può infatti solo ricavare attraverso un'operazione. averlo in maniera "esplicita" eviterebbe complicate elaborazioni. grazie

## Interesse pubblico

Ad esempio renderebbe possibile un diagramma a barre con contagi giornalieri che farebbe meglio percepire la crescita rispetto al giorno precedente rispetto alla serie temporale sul totale contagiati.

**Comment by valemercurii** [comment]
Buongiorno @marcodo1976 ,

E' sbagliato dire che i contagi giornalieri del 19 marzo sono stati 5322, in quanto questa è la differenza tra totale_casi del 19/03 e totale_casi del 18/03. Differenza che comprende anche il numero dei nuovi_guariti e nuovi_deceduti. I guariti e deceduti non sono affatto dei "nuovi contagi", in quanto sono stati considerati come "nuovi_attualmente_positivi" già nei giorni precedenti.

L'unico dato reale che rappresenta i nuovi contagi è "nuovi_attualmente_positivi".

**Comment by FedericoStra** [comment]
@valemercurii Questa è una enorme cavolata. È il problema alla base delle richieste #263, #268, #275 and #277, che sono state tutte liquidate grossolanamente con superficialità e una professionalità davvero bassa.

I nuovi contagi rilevati avvenuti nel giorno sono la differenza fra il totale di oggi e il totale di ieri. Nel frattempo, alcune persone hanno cessato di essere malate (guarendo o morendo), pertanto la variazione nel numero di persone attualmente affette (ovvero `nuovi_attualmente_positivi`) è una quantità più piccola.

**Comment by FedericoStra** [comment]
Se ogni giorno si ammalano 1000 persone nuove e nel frattempo 1000 vengono dimesse (vive o morte), non si può certo dire che i nuovi contagi sono 0. Eppure la variazione nel numero di persone ospitalizzate o in isolamento (`nuovi_attualmente_positivi`) è 0: infatti 1000 entrano e 1000 escono.

Con il tuo ragionamento, allora tutti i fenomeni che sono circa in equilibrio (tipo gli incidenti stradali) dovrebbero riportare ogni giorno circa 0 "nuovi casi". Bello. 0 incidenti, 0 tentati omicidi, 0 stupri, 0 violenze domestiche... Ci sarebbero pure dei giorni con un numero negativo di omicidi. Stupendo.

**Comment by marcodo1976** [comment]
> Buongiorno @marcodo1976 ,
> 
> E' sbagliato dire che i contagi giornalieri del 19 marzo sono stati 5322, in quanto questa è la differenza tra totale_casi del 19/03 e totale_casi del 18/03. Differenza che comprende anche il numero dei nuovi_guariti e nuovi_deceduti. I guariti e deceduti non sono affatto dei "nuovi contagi", in quanto sono stati considerati come "nuovi_attualmente_positivi" già nei giorni precedenti.
> 
> L'unico dato reale che rappresenta i nuovi contagi è "nuovi_attualmente_positivi".

Mi pare talmente evidente che i nuovi contagi siano dati dal totale contagi meno quello di ieri che si fa fatica a replicare. E la cosa grave è che tale valore difficilmente viene menzionato nei canali di informazione mentre è questa la metrica che veramente ci dà la progressione del contagio. 
I nuovi attualmente positivi sono al netto di quelli che hanno avuto un outcome.
Provo a spiegarmi con due casi teorici:
SCENARIO 1
- ieri 100 casi
- oggi 200 casi, 50 guariti e 50 deceduti

Quindi
Nuovi attualmente positivi = 0
Nuovi casi (o contagi giornalieri o casi giornalieri) = 100

SCENARIO 2
- ieri 100 casi
- oggi 200 casi, 20 guariti e 30 deceduti

Quindi
Nuovi attualmente positivi = 50 (i 100 di ieri piu i 50 di oggi)
Nuovi casi = (sempre) 100

**Comment by valemercurii** [comment]
> Mi pare talmente evidente che i nuovi contagi siano dati dal totale contagi meno quello di ieri che si fa fatica a replicare. 

Grazie di avermi illuminata dall'alto della sua intelligenza @marcodo1976.
La avviso che cmq mi aveva già aiutata @FedericoStra, senz'altro più cortese di lei, in #294.

**Comment by FedericoStra** [comment]
> E la cosa grave è che tale valore difficilmente viene menzionato nei canali di informazione mentre è questa la metrica che veramente ci dà la progressione del contagio.

@marcodo1976 Parole sante. Io ho provato e riprovato a contattare le redazioni di una decina di giornali tra i più importanti, senza mai ricevere risposta né riuscire ad entrare in contatto con qualcuno. Prego chiunque abbia i mezzi di provare a mettersi in contatto con dei giornalisti per spiegare loro l'equivoco generato dall'ingannevole lettura del bollettino che fa Borrelli.
