### ISSUE TITLE
Dati regione prima di aggiornamento vs dataset

### ISSUE THREAD

**Issue by claort** [pcm-dpc/COVID-19#293]
@umbros 
Buongiorno non ho ricevuto risposta alla domanda del precedente issue.
Per capirci meglio la regione pubblica alle 1330 al seguente link i dati:
http://pti.regione.sicilia.it/portal/page/portal/PIR_PORTALE/PIR_ArchivioLaRegioneInforma/PIR_Coronavirusaggiornamentoprovince0319

La domanda è:
1) si può aggiornare il database appena disponibili?
2) se no si puo imporre alla regione di pubblicare i dati dopo vs aggiornamento ufficiale ?

Grazie

**Comment by pierluigicara** [comment]
1) I dati vengono aggiornati dal DPC, come di consueto, (quasi) contestualmente alla conferenza stampa del Capo del Dipartimento. 
2) La logica vorrebbe che fosse così, ma altre ragioni determinano comportamenti diversi. Se però all'autonomia che già hanno le Regioni in materia sanitaria poi ci si aggiunge l'autonomia dettata dallo statuto speciale il tutto diventa ancora più complicato. 
Quello che posso dire è che le Regioni in base alla procedura prevista dal MinSalute devono inviare i propri dati per la compilazione del bollettino giornaliero entro le 15. Per ieri a noi risultano trasmessi i dati che vedete già pubblicati e non quelli che risultano dal link trasmesso.
