### ISSUE TITLE
Contagi giornalieri modo di conteggio

### ISSUE THREAD

**Issue by davscheno** [pcm-dpc/COVID-19#294]
In merito ai nuovi contagiati giornalieri, come vanno conteggiati ? 
sono i **nuovi attualmente positivi** oppure occorre fare una sottrazione tra **totale casi** del giorno attuale meno il precedente.

la domanda è necessaria in quanto anche sui giornali vengono riportati a volte un dato piuttosto che l'altro

**Comment by SimoneTinella** [comment]
Ciao @davscheno . Per ottenere i nuovi contagi devi fare la **differenza dei totale casi**. Il campo nuovi_attualmente_positivi è la differenza di totale_attualmente_positivi  che risente dei nuovi dimessi e deceduti che quindi è inferiore ai nuovi contagi

**Comment by valemercurii** [comment]
Buongiorno @davscheno ,

I nuovi contagi giornalieri sono i **nuovi_attualmente_positivi**. In alcun modo può essere la sottrazione tra totale_casi di oggi e totale_casi di ieri come dice @SimoneTinella , in quanto questa operazione comprenderebbe anche i guariti e i deceduti che in **nessun modo** possono essere considerati dei "nuovi contagi". I guariti e i deceduti erano i nuovi casi dei giorni precedenti, ma non di certo dell'ultimo.

Il numero dei nuovi contagi giornalieri che giustamente riportano anche i media è quindi solamente quello dei **nuovi_attualmente_positivi**.

**Comment by irebo2020** [comment]
Buongiorno, 
riguardo ai dati csv, il numero di tamponi riportato giornalmente sono i totali rispetto al giorno considerato (quindi includono anche quelli dei giorni precedenti), o sono relativi solo al giorno in questione?

**Comment by irebo2020** [comment]
Scusa @davscheno, 
dov'è il format per contattare direttamente la protezione civile?

**Comment by davscheno** [comment]
> Scusa @davscheno,
> dov'è il format per contattare direttamente la protezione civile?

non so speravo che rispondessero quì

**Comment by davidfregoli** [comment]
> I nuovi contagi giornalieri sono i nuovi_attualmente_positivi

No, i NUOVI CONTAGI sono il numero di nuovi casi che si sono registrati nell'ultimo giorno. punto. questo e' quello che interessa al 99% delle persone e che ancora non ho capito come desumere da questa repo

**Comment by davscheno** [comment]
> > I nuovi contagi giornalieri sono i nuovi_attualmente_positivi
> 
> NO! I NUOVI CONTAGI sono il numero di nuovi casi che si sono registrati nell'ultimo giorno. punto. questo e' quello che interessa al 99% delle persone e che ancora non ho capito come desumere da questa repo!!!!
> 
> `nuovi_attualmente_positivi` è (_verbatim_):
> 
> > (Totale attualmente positivi attuali - Totale attualmente positivi del giorno prima)
> 
> del quale non me ne faccio una cippa perchè è influenzato dal numero di morti/guariti

come del resto il totale dei casi del giorno meno quelli del giorno prima !!!

concordo

**Comment by valemercurii** [comment]
D'accordo, dal database fornito dal dpc non si riesce a dedurre i nuovi contagi "puri" come intende lei, e non sarò certo io, utente comune a capire come dedurlo, ma è altrettanto sbagliato dire, e questo va sottolineato, perché in troppi lo stanno dicendo, che i nuovi contagi sono il _totale_casi di oggi - totale_casi di ieri_, come si deduce dalla issue #292. Numero che è maggiormente influenzato, come dice lei, da guariti e deceduti, in quanto il delta rispetto al giorno precedente è dato dalla somma di _nuovi_attualmente_positivi + nuovi_guariti + nuovi_deceduti_. Questo per dire che **nuovi_attualmente_positivi** rimane comunque il dato più affidabile del database per come è impostato ad oggi, per avere un'idea dei contagiati.

Approfitto per ringraziare i volontari della Protezione Civile che ci offrono questo servizio totalmente aperto al pubblico, che nessun altro ente governativo di altri paesi offre, e che di certo non si merita la mancanza di educazione civica che tipicamente circola online, soprattutto in un periodo come questo.

**Comment by SimoneTinella** [comment]
> D'accordo, dal database fornito dal dpc non si riesce a dedurre i nuovi contagi "puri" come intende lei, e non sarò certo io, utente comune a capire come dedurlo, ma è altrettanto sbagliato dire, e questo va sottolineato, perché in troppi lo stanno dicendo, che i nuovi contagi sono il _totale_casi di oggi - totale_casi di ieri_, come si deduce dalla issue #292. Numero che è maggiormente influenzato, come dice lei, da guariti e deceduti, in quanto il delta rispetto al giorno precedente è dato dalla somma di _nuovi_attualmente_positivi + nuovi_guariti + nuovi_deceduti_. Questo per dire che **nuovi_attualmente_positivi** rimane comunque il dato più affidabile del database per come è impostato ad oggi, per avere un'idea dei contagiati.
> 
> Approfitto per ringraziare i volontari della Protezione Civile che ci offrono questo servizio totalmente aperto al pubblico, che nessun altro ente governativo di altri paesi offre, e che di certo non si merita la mancanza di educazione civica che tipicamente circola online, soprattutto in un periodo come questo.

nuovi_attualmente_positivi + nuovi_guariti + nuovi_deceduti, questo è il reale numero di nuovi contagi.

Attenzione.
**nuovi_attualmente_positivi** essendo la differenza fra il **totale_attualmente_positivi** non rappresenta il reale numero di nuovi contagi in quanto nel totale_attualmente_positivi fra un giorno e l'altro parte delle persone sono o guarite o decedute (ahimè), andando quindi a ridurre il totale_attualmente_positivi ma non il totale_casi. Il nuovi_attualmente_positivi rappresenta quindi il 'netto', nuovi positivi - nuovi guariti - nuovi deceduti, che così su due piedi aggiungo che è una informazioni di poco conto.

Questo campo comunque ha suscitato non poche problematiche, il numero di issue che vengono aperte giornalmente è elevato, basta andare a guardare quelle chiuse per avere chiarezza. Io stesso sono incappato in questo dubbio. Basta notare comunque che durante le dirette le Protezione Civile il numero di nuovi contagi riportato non è nuovi_attualmente_positivi ma bensì proprio la differenza dei totali_casi.

**Comment by valemercurii** [comment]
In tal caso @SimoneTinella  allora non mi è chiaro come mai si considerano come "nuovi contagi" anche i nuovi_deceduti e, soprattutto, i nuovi_guariti. Un "guarito contagiato" mi suona un po' male, c'è qualcosa che mi sfugge?

**Comment by SimoneTinella** [comment]
> Non mi è chiaro come mai si considerano come "nuovi contagi" anche i nuovi_deceduti e, soprattutto, i nuovi_guariti.

Nuovi deceduti e nuovi guariti non li consideri come nuovi contagiati. Quello che trae in inganno è che in **nuovi_attualmente_positivi** questi valori sono stati sottratti implicitamente. **Totale attualmente positivi** deriva dalle **ospedalizzazioni + isolamento domiciliare**, fra un giorno e l'altro le ospedalizzazione come gli isolamenti hanno una parte che si sottrae (i guariti o deceduti) e una parte che si somma (i nuovi malati), da li poi viene fuori il **nuovi_attualmente_positivi** che è il netto fra le due. I nuovi contagi invece sono solo i nuovi malati (parte che si somma).

**Comment by mrmatd** [comment]
Scusate se mi intrometto, ma vorrei condividere il ragionamento che ho fatto.
Le persone rientranti nel **totale attualmente positivi** al tempo  t<sub>0</sub> o risultano ancora positive (_sopravvissuti positivi_) o guarite o (ahimè) decedute al tempo t<sub>1</sub>. Per calcolare i _sopravvissuti positivi_ è sufficiente fare **totale attualmente positivi** al tempo  t<sub>0</sub> - _nuovi guariti_ - _nuovi deceduti_. A questo punto il numero dei _nuovi contagiati_ sarà dato da **totale attualmente positivi** al tempo  t<sub>1</sub> - _sopravvissuti positivi_. Tale valore dovrebbe coincidere con la differenza del **totale casi** a meno che non muoia una persona che non era stata precedentemente conteggiata tra i positivi. È corretto?

**Comment by pierluigicara** [comment]
Al momento i dati disponibili sono quelli che vengono rilasciati. Vi ringraziamo delle vostre osservazioni (solo nel caso in cui siano osservate le minime regole di educazione che abbiamo anche riportato nel Codice di Condotta in home page). Sarà nostra cura dettagliare ancora meglio la documentazione sui dati in modo da renderne sempre più comprensibile il significato ai fini del loro riutilizzo e aggiornarvi tempestivamente qualora ci fossero novità sui dati.

**Comment by valemercurii** [comment]
Allora grazie @SimoneTinella , credo di seguire il vostro ragionamento adesso.
Se ho capito bene, siccome il **totale_attualmente_positivi** _di ieri_, includeva anche i **nuovi_guariti** e **nuovi_deceduti** _di oggi_, i **nuovi_contagi_oggi** dovrebbero essere:

**totale_attualmente_positivi_oggi - [ totale_attualmente_positivi_ieri - ( nuovi_guariti_oggi + nuovi_contagi_oggi ) ]**

che equivale a dire **totale_casi_oggi - totale_casi_ieri**, un po' arzigogolato ma chiaro adesso.
Credo sia in linea con ciò che dice anche @mrmatd ?

**Comment by davscheno** [comment]
> Allora grazie @SimoneTinella , credo di seguire il vostro ragionamento adesso.
> Se ho capito bene, siccome il **totale_attualmente_positivi** _di ieri_, includeva anche i **nuovi_guariti** e **nuovi_deceduti** _di oggi_, i **nuovi_contagi_oggi** dovrebbero essere:
> 
> **totale_attualmente_positivi_oggi - [ totale_attualmente_positivi_ieri - ( nuovi_guariti_oggi + nuovi_contagi_oggi ) ]**
> 
> che equivale a dire **totale_casi_oggi - totale_casi_ieri**, un po' arzigogolato ma chiaro adesso.
> Credo sia in linea con ciò che dice anche @mrmatd ?

non mi sembra tornare: 
**totale_attualmente_positivi_oggi - [ totale_attualmente_positivi_ieri - ( nuovi_guariti_oggi + nuovi_contagi_oggi ) ]**

**Comment by mrmatd** [comment]
> > Allora grazie @SimoneTinella , credo di seguire il vostro ragionamento adesso.
> > Se ho capito bene, siccome il **totale_attualmente_positivi** _di ieri_, includeva anche i **nuovi_guariti** e **nuovi_deceduti** _di oggi_, i **nuovi_contagi_oggi** dovrebbero essere:
> > **totale_attualmente_positivi_oggi - [ totale_attualmente_positivi_ieri - ( nuovi_guariti_oggi + nuovi_contagi_oggi ) ]**
> > che equivale a dire **totale_casi_oggi - totale_casi_ieri**, un po' arzigogolato ma chiaro adesso.
> > Credo sia in linea con ciò che dice anche @mrmatd ?
> 
> non mi sembra tornare:
> **totale_attualmente_positivi_oggi - [ totale_attualmente_positivi_ieri - ( nuovi_guariti_oggi + nuovi_contagi_oggi ) ]**

Penso che intendesse:
**nuovi_contagi_oggi** = **totale_attualmente_positivi_oggi - [ totale_attualmente_positivi_ieri - ( nuovi_guariti_oggi + nuovi_deceduti_oggi ) ]**

**Comment by davscheno** [comment]
> > > Allora grazie @SimoneTinella , credo di seguire il vostro ragionamento adesso.
> > > Se ho capito bene, siccome il **totale_attualmente_positivi** _di ieri_, includeva anche i **nuovi_guariti** e **nuovi_deceduti** _di oggi_, i **nuovi_contagi_oggi** dovrebbero essere:
> > > **totale_attualmente_positivi_oggi - [ totale_attualmente_positivi_ieri - ( nuovi_guariti_oggi + nuovi_contagi_oggi ) ]**
> > > che equivale a dire **totale_casi_oggi - totale_casi_ieri**, un po' arzigogolato ma chiaro adesso.
> > > Credo sia in linea con ciò che dice anche @mrmatd ?
> > 
> > 
> > non mi sembra tornare:
> > **totale_attualmente_positivi_oggi - [ totale_attualmente_positivi_ieri - ( nuovi_guariti_oggi + nuovi_contagi_oggi ) ]**
> 
> Penso che intendesse:
> **nuovi_contagi_oggi** = **totale_attualmente_positivi_oggi - [ totale_attualmente_positivi_ieri - ( nuovi_guariti_oggi + nuovi_deceduti_oggi ) ]**

si così funziona

**Comment by FedericoStra** [comment]
@valemercurii Più semplicemente, pensa a `totale_casi` come il numero di persone che in un qualche momento della loro vita sono entrate in contatto con il virus e sono risultate infette. Quante nuove infezioni sono avvenute in un giorno? Semplice, `totale_casi` di oggi meno `totale_casi` di ieri. Francamente non vedo la necessità di fare tutti questi ragionamenti arzigogolati di sopra...

Riguardo alla richiesta di @davscheno, in particolare

> la domanda è necessaria in quanto anche sui giornali vengono riportati a volte un dato piuttosto che l'altro

è un fatto molto grave che ci sia un tasso di disinformazione alle stelle. Il problema è già stato sollevato in #263, #268, #275, #277 e #292, ma l'evidenza delle cose è che la Protezione Civile pare avere tutta l'intenzione di far circolare il meno possibile questo numero (che è più significativo per misurare la velocità del contagio), per il semplice motivo che è un numero più grande.

Io esorto chiunque abbia i mezzi di farlo a cercare di avvisare i giornalisti di questa discrepanza tra quello che viene annunciato e quello che la gente invece si immagina di sentire, al fine che i giornali possano cominciare a riportare le cifre esatte.

**Comment by FedericoStra** [comment]
Per citare un esempio concreto: https://www.lastampa.it/cronaca/2020/03/20/news/l-aggiornamento-della-protezione-civile-4032-morti-quasi-38-mila-i-casi-totali-1.38617133

> Aumentano, ma di meno, i nuovi casi, che sono 4670

Falso, i nuovi casi sono 5986, più dei 5322 di ieri.

Di esempi come questo ce ne sono a vagonate: la quasi totalità della cronaca italiana a dire il vero.
