### ISSUE TITLE
Codici province

### ISSUE THREAD

**Issue by vcaponi** [pcm-dpc/COVID-19#295]
Salve e grazie dell'ottimo ed encomiabile lavoro che fate. Sarebbe possibile introdurre anche i codici ISTAT delle province (e regioni), per rendere piu' facile merging i dati con altri dati di altre origini?
Grazie ancora.

**Comment by pierluigicara** [comment]
I codici ISTAT 2019 di Regioni e Province sono già presenti nei rispettivi file csv.

**Comment by vcaponi** [comment]
Intendevo in nuovi codici alfanumerici NUTS3 esempio Torino ITC11, magari insieme al codice storico "1" Istat usa i nuovi codici per la distribuzione di dati territoriali
