### ISSUE TITLE
Ricoveri

### ISSUE THREAD

**Issue by Acco82** [pcm-dpc/COVID-19#296]
I dati sui ricoveri sono l'incidenza dei ricoveri (i nuovi ricoveri nell'arco della giornata) oppure la prevalenza in un determinato momento (quante persone sono ricoverate all'ora X del giorno t). Oppure sono la cumulata dell'incidenza?

Grazie

**Comment by pierluigicara** [comment]
I dati sui ricoveri rappresentano il numero cumulativo, che per ciascun giorno si incrementa dei ricoveri avvenuti in quel medesimo giorno.
