### ISSUE TITLE
Dato errato in ricoverati_con_sintomi in andamento nazionale del 25/02

### ISSUE THREAD

**Issue by valemercurii** [pcm-dpc/COVID-19#297]
Tipo di issue:

- [ ] Dato errato in dpc-covid19-ita-andamento-nazionale-20200225.csv
- [ ] Dato errato in dpc-covid19-ita-andamento-nazionale.csv

## Riassunto

Se il valore di ricoverati_con_sintomi è la differenza tra totale_ospedalizzati e terapia_intensiva, come risulta essere in tutti i campi di ciascuna data, allora il dato di ricoverati_con_sintomi del 25/02/2020 a livello nazionale è errato.

**Attesa:**

ricoverati_con_sintomi del 25/02/2020 a livello nazionale dovrebbe essere 115.

**Attuale:**

ricoverati_con_sintomi del 25/02/2020 a livello nazionale risulta essere 114.

**Comment by pierluigicara** [comment]
Grazie della segnalazione, stiamo correggendo l'errore che è dovuto ad una unità in più erroneamente presente per la Sicilia, che ci è stata segnalata anch'essa in precedenza.
