### ISSUE TITLE
tamponi totali

### ISSUE THREAD

**Issue by irebo2020** [pcm-dpc/COVID-19#299]
**Tipo di richiesta**:  richiesta di informazione | richiesta di dati | suggerimento di miglioramento (documentazione, label, _ecc_) | relativo alla pagina grafica

**Comment by irebo2020** [comment]
Buongiorno,
riguardo ai dati csv, il numero di tamponi riportato giornalmente sono i totali rispetto al giorno considerato (quindi includono anche quelli dei giorni precedenti), o sono relativi solo al giorno in questione?

**Comment by irebo2020** [comment]
Dal mio punto di vista ha senso confrontare i dati di incremento di casi solo in termini di variazione percentuale rispetto ai tamponi fatti, e non semplice differenza dei positivi giorno per giorno. Questo perchè i campioni analizzati variano giorno per giorno e soprattutto da regione a regione. Bisognerebbe normalizzare il tutto per avere un grafico che mostri una variazione coerente. Da qui la mia precedente domanda per capire se il numero di tamponi riportati in csv (ultima colonna a destra) si riferiscono solo al giorno considerato o sono i tamponi totali fatti fino a quel giorno!

**Comment by sfoglia60** [comment]
> Dal mio punto di vista ha senso confrontare i dati di incremento di casi solo in termini di variazione percentuale rispetto ai tamponi fatti, e non semplice differenza dei positivi giorno per giorno. Questo perchè i campioni analizzati variano giorno per giorno e soprattutto da regione a regione. Bisognerebbe normalizzare il tutto per avere un grafico che mostri una variazione coerente. Da qui la mia precedente domanda per capire se il numero di tamponi riportati in csv (ultima colonna a destra) si riferiscono solo al giorno considerato o sono i tamponi totali fatti fino a quel giorno!

Sono i tamponi totali cumulati. Anche io ho elaborato un modello sulla percentuale di attuali contagiati cumulati usando una Gompertz

**Comment by pierluigicara** [comment]
Confermo, sono i tamponi cumulati. Possono essere presenti variazioni giornaliere di singole regioni come riportato nelle note alla dashboard.
