### ISSUE TITLE
Inconsistency between CSV and JSON data

### ISSUE THREAD

**Issue by pescetti** [pcm-dpc/COVID-19#3]
There is a clear inconsistency between the CSV and JSON file for yesterday's data for Parma.

March 5th: 150 in CSV, 150 in JSON (so they match as expected):
- CSV: https://github.com/pcm-dpc/COVID-19/blob/master/dati-province/dpc-covid19-ita-province-20200305.csv#L28
- JSON: https://github.com/pcm-dpc/COVID-19/blob/master/dati-json/dpc-covid19-ita-province.json#L15680

March 6th: 181 in CSV (and in news reports), 41 in JSON:
- CSV: https://github.com/pcm-dpc/COVID-19/blob/master/dati-province/dpc-covid19-ita-province-20200306.csv#L28
- JSON: https://github.com/pcm-dpc/COVID-19/blob/master/dati-json/dpc-covid19-ita-province.json#L17216

I can probably look into regenerating the JSON from the CSV and check for more inconsistencies.

By the way, thanks for providing modern data in a format useful for analysis and coursework. Highly appreciated!

**Comment by umbros** [comment]
Thanx for suggestion!

**Comment by pescetti** [comment]
Thank you! I confirm the JSON time series for Parma is now consistent with the CSV files (and news reports).
