### ISSUE TITLE
Embed per finalità di comunicazione

### ISSUE THREAD

**Issue by keggy85** [pcm-dpc/COVID-19#30]
Buongiorno e grazie per la realizzazione, molto utile e fini comunicativi per avere in unica pagina dati certi e sempre aggiornati.

Per poterla embeddare ho provato a seguire queste istruzioni senza alcun successo: https://doc.arcgis.com/it/arcgis-online/share-maps/embed-maps-groups.htm#ESRI_SECTION1_F3F662EFF5964FF1B0890F025ABBF1EE

C'è un modo per poter embeddare questa mappa in un sito web?

Saluti
Francesco

**Comment by NoFishLikeIan** [comment]
Non sono parte del progetto, ma ho trovato la mappa embedded [qui](https://www.corriereadriatico.it/marche/coronavirus_ultime_notizie_marche_mappa_contagio_tempo_reale-5097257.html) se può aiutare.

**Comment by marcodadamo** [comment]
Nella mappa è possibile integrare e far conoscere le zone indicate dal ministero come aree di rischio e limitate sia per l'ingresso che l'uscita, come nel caso della Lombardia e di altre province limitrofi?

**Comment by keggy85** [comment]
> Non sono parte del progetto, ma ho trovato la mappa embedded [qui](https://www.corriereadriatico.it/marche/coronavirus_ultime_notizie_marche_mappa_contagio_tempo_reale-5097257.html) se può aiutare.

Grazie mille, funziona bene anche con la versione mobile giusto modificando l'altezza,

**Comment by umbros** [comment]
Confermo che l'unico modo è quello di includerlo (anche se non sono un fan dell'iframe) tramite iframe.
<iframe allowfullscreen="" frameborder="1" height="100%" marginheight="0px" width="100%" marginwidth="0px" name="dpcCOVID19Map" scrolling="no" src="https://opendatadpc.maps.arcgis.com/apps/opsdashboard/index.html#/b0c68bce2cce478eaac82fe38d4138b1" style="border:none;" ></iframe>

Il mio suggerimento è quello di linkare direttamente le due risorse:

Versione desktop: http://arcg.is/C1unv
Versione mobile: http://arcg.is/081a51
