### ISSUE TITLE
Dati su isolamento domiciliare

### ISSUE THREAD

**Issue by mzanna** [pcm-dpc/COVID-19#300]
**Tipo di richiesta**:  richiesta di informazione | richiesta di dati | suggerimento di miglioramento (documentazione, label, _ecc_) | relativo alla pagina grafica

## Riassunto

 Salve e grazie per tutto quello che state facendo... sto cercando di la discrepanza fra i dati di persone in isolamento domiciliare per il Veneto (12k secondo Zaia in conferenza stampa) e i dati sul vostro repository (2.2k all'aggiornamento di ieri).  Questa e' dovuta e' dal fatto che il Veneto cita dati che includono casi sospetti e non positivi?  Se e' cosi, sarebbe utilissimo avere dati su casi sospetti in quarantena per le regioni che forniscono questo dato.

## Interesse pubblico

Queste informazioni aiuterebbero l'analisi sull'efficacia delle politiche diagnostiche e d'isolamento prese da varie regioni, partendo con il Veneto.  (Ho un "pubic dashboard" che si basa su i vostri dati che potrete consultare qui: https://public.tableau.com/profile/michele.zanini#!/vizhome/ITALYCovid-19TrendsbyRegion/Summary)

**Comment by umbros** [comment]
Grazie per la segnalazione, approfondiremo la cosa.
