### ISSUE TITLE
Dimessi guariti ed isolamento domiciliare

### ISSUE THREAD

**Issue by AlbiBone** [pcm-dpc/COVID-19#301]
**Tipo di richiesta**:  richiesta di informazione

## Riassunto

Alcune domande connesse tra loro:
1. In accordo con la domanda #193, il conteggio dei guariti è solo riferito per i pazienti gravi che quindi si trovano in ospedale (terapia_intensiva+ricoverati_con_sintomi) e non considera i pazienti con sintomi lievi che sono in isolamento domiciliare. Corretto?
2. Visto che da quanto capisco, non c'è feedback sulla guarigione dei pazienti in isolamento domiciliare, ne consegue che il conteggio di questi ultimi non decresce mai!?
3. I pazienti in isolamento domiciliare continuano a gravare sul numero attuale di infetti (anche dopo molto tempo)?

## Interesse pubblico

Fare chiarezza sulla definizione di "dimessi_guariti" e come vengono gestiti i pazienti meno gravi che si trovano in isolamento domiciliare, nonché di fare chiarezza su come vengono gestiti questi ultimi nel conteggio totale degli infetti e dei guariti.

**Comment by jacopoc** [comment]
Premettendo che sono un utente e che quindi la mia risposta potrebbe non essere corretta, ho analizzato i dati e credo che il significato dei vari campi sia quello che ho descritto nel commento:

https://github.com/pcm-dpc/COVID-19/issues/306#issuecomment-602029641

In particolare, per rispondere alla tua domanda, il valore "dimessi_guariti" dovrebbe rappresentare il totale (cumulativo) di tutti i pazienti guariti a prescindere da dove siano stati trattati (isolamento domiciliare/ospedale/intensivo).

**Comment by danielesalpietro** [comment]
proposta:

**<dimessi_guariti_giornaliero>** = <dimessi_da_terapia_intensiva_giornaliero> + <dimessi_con_sintomi_giornaliero> + <dimessi_da_isolamento_senza_sintomi>

**<totale_dimessi_guariti>** = <dimessi_guariti_giorno_precedente> + <dimessi_guariti_giornaliero>

in questo modo non si avrebbero indicazioni precise sull'andamento e renderebbe evidente l'efficacia dei sistemi di cura/isolamento?

**Comment by AlbiBone** [comment]
`il valore "dimessi_guariti" dovrebbe rappresentare il totale (cumulativo) di tutti i pazienti guariti a prescindere da dove siano stati trattati (isolamento domiciliare/ospedale/intensivo).`

Gentile @jacopoc, non sono d'accordo con la tua affermazione, perché nel post #193 l'amministratore della protezione civile, ha dichiarato che i dati divulgati riguardano SOLO i dimessi dall'ospedale e NON hanno ci sono info sui guariti a casa i questo database, **quindi i dati NON considerano la guarigione dei malati a casa** (vedi tu stesso la [risposta](https://github.com/pcm-dpc/COVID-19/issues/193#issuecomment-599585160)).

**Comment by jacopoc** [comment]
> Gentile @jacopoc, non sono d'accordo con la tua affermazione. Questo perché nel post #193 l'amministratore della protezione civile, ha dichiarato che i dati divulgati riguardano SOLO i dimessi dall'ospedale e NON hanno ci sono info sui guariti a casa

A dire il vero, nel ticket #193, la risposta è stata:

> Grazie della segnalazione ma al momento il dato che ci viene trasmesso e per il quale c'è l'autorizzazione per la pubblicazione riguarda solo "DIMESSI/GUARITI".

Ricordo che la richiesta del post era quella di avere i dati dei dimessi e dei guariti separatamente: la risposta, a mio modo di vedere, ribadisce che al momento il solo dato che la Protezione Civile può pubblicare è quello aggregato.

**Comment by AlbiBone** [comment]
@jacopoc, probabilmente è il totale ed hai ragione, ma per quanto mi riguarda non è abbastanza chiara la faccenda e il tutto rimane abbastanza fumoso e rimangono dubbi. Per questo motivo ho sollevato questo issues proprio per chiarire.
In attesa di una risposta ufficiale, un saluto a tutti.

**Comment by EmilianoBruni** [comment]
Io sono stato in isolamento domiciliare (per ora finito per fortuna) senza aver fatto il tampone e, a posteriori, senza essere positivo. per cui qualche problemino c'è. Ma d'altra parte capisco anche che non si può entrare nel dettaglio per cui, ok, sei in isolamento, sei positivo.

**Comment by AlbiBone** [comment]
@EmilianoBruni mi è chiara la tua situazione, ma la mia domanda era più rivolta a coloro che son risultati positivi tramite tampone ma con sintomi lievi (quindi sono a casa) ma appunto non so se son considerati nei conteggi dei "dimessi".

**Comment by EmilianoBruni** [comment]
Si si. Capisco il tuo problema, ed infatti per il mio dubbio sul fatto che nel calcolo dei positivi c'è l'assunzione isolamento_domiciliare = positivo. che potrebbe non esserci, ho aperto un altro issue. Era solo per rimarcare il fatto che è difficile entrare nel dettaglio cosi sottile di capire chi è veramente positivo, chi è guarito a casa senza dire niente e cosi via.

**Comment by umbros** [comment]
Dimessi guariti, come abbiamo precisato sul wiki sono:
totale dei casi che risolvono i sintomi dell’infezione da Covid-19 e che risultano negativi in due test consecutivi effettuati a distanza di 24 ore uno dall’altro, per la ricerca di SARS-CoV-2, sulla base della nota del Ministero della Salute n. 0006607 del 29/02/2020.

**Comment by AlbiBone** [comment]
Gentile @umbros,
mi è chiaro che per essere dimessi guariti vengono fatti due tamponi consecutivi, ma la mia domanda è mirata a comprendere se viene testata la guarigione tramite tamponi dei soli malati gravi in ospedali, oppure sia dei malati in ospedale che quelli confinati a casa? In altre parole: nei "dimessi_guariti" son compresi le guarigioni dei pazienti ospedalizzati oppure dei ospedalizzati+isolamento domiciliare?

Ho il dubbio che essendo malati lievi coloro che son confinati a casa, non venga testata la loro guarigione tramite tamponi e quindi non ricadono nella statistica dei "dimessi_guariti".
