### ISSUE TITLE
Importazione dati in ArcGISonline e preview Storymaps 

### ISSUE THREAD

**Issue by lvalanzano** [pcm-dpc/COVID-19#302]
**Tipo di richiesta**:  Suggerimento per importare il csv in ARCGIS | richiesta di informazione  | richiesta di dati 

## Riassunto

Salve, seguo con attenzione lo sviluppo delle diverse discussioni ma non ho trovato suggerimenti nel campo GIS.  Io ho realizzato una storymaps con ArcGIS ma  perdo molto tempo ad aggiornare i dati, è possibile avere gli stessi datinofferti in formato CSV in formato SHAPE?
Al seguente link è possibile visualizzare l'applicazione  WebGIS che ho realizzato

https://arcg.is/ri09e

## Interesse pubblico

 Ottimizzare tempi per effettuare l'aggiornamento dei dati e dedicare tale tempo all'analisi

**Comment by pierluigicara** [comment]
Finalmente una questione GIS e complimenti per l'applicazione. Dunque, i dati nascono proprio come csv per motivi pratici e non riusciamo a modificare questa filiera, tuttavia sono resi disponibili anche in formato json (sperando che questo formato possa aiutare).

**Comment by lvalanzano** [comment]
Grazie, per la risposta e per l'apprezzamento dell'applicazione GIS, anche se è solo una bozza. 
Un grazie speciale alla scelta di condividere i dati quotidianamente sia con noi ricercatori sia ai non addetti ai lavori. Credo sia una scelta degna di un paese civile e moderno, con una democrazia matura.
Gli errori, i refusi, le sviste sono accettabili perché probabilmente sono proprio questi passi falsi che ci fanno riflettere e a volte ci mostrano soluzioni inaspettate, alimentano il dibattito. E ci sta anche che qualcuno polemizza ma voi non mollate. Non oso immaginare cosa possa essere coordinare 21 entità territoriali che lavorano in uno stato di guerra. 
Domani mi dedicherò nel migliorare le mie conoscenze del formato json e studierò un sistema per  importare in automatico i dati nel mio modello, almeno ci proverò. Vi aggiornerò sugli sviluppo.

Buon lavoro a tutti e grazie ancora per il vostro lavoro.
