### ISSUE TITLE
Ospedalizzati Piemonte 20-03-2020

### ISSUE THREAD

**Issue by mydozer** [pcm-dpc/COVID-19#303]
Tipo di issue:

- [X ] Dati mancanti o errati 
- [ ] Errore nella documentazione 
- [ ] Errore or mancanza nella dashboard 
- [ ] Problemi di visualizzazione nella dashboard 

- Regione:
Piemonte

## Riassunto
Il totale degli ospedalizzati ha avuta una considerevole diminuzione tra ieri e oggi, solo per la regione del Piemonte. Ieri eano 2279 mentre oggi sono 1541. Un cambio parecchio netto.

Potreste cortesemente confermare che Piemonte ha fornito tutti i dati di oggi?

Grazie!!

**Comment by umbros** [comment]
Confermiamo @mydozer, da notare che sono aumentati le persone in isolamento domiciliare da 218 a 1423.

**Comment by mydozer** [comment]
Grazie mille @umbros
