### ISSUE TITLE
Definizione campo tamponi

### ISSUE THREAD

**Issue by filmastroianni** [pcm-dpc/COVID-19#304]
Sarebbe possibile definire meglio il campo tamponi? Il dato riportato fa riferimento ai tamponi effettuati o ai tamponi già analizzati (di cui quindi si ha già il risultato)?

Grazie

**Comment by sidereomundi** [comment]
Non mi è oltretutto chiaro se il riferimento sia al numero cumulativo totale di tamponi (dovrebbe). Ad esempio per la regione Friuli Venezia Giulia però il numero cala nella giornata del 2020-03-19.

**Comment by sidereomundi** [comment]
> Non mi è oltretutto chiaro se il riferimento sia al numero cumulativo totale di tamponi (dovrebbe). Ad esempio per la regione Friuli Venezia Giulia però il numero cala nella giornata del 2020-03-19.

ok, vedo che questo può essere associato ad errori nei dati forniti dalle regioni..

**Comment by EmilianoBruni** [comment]
Il campo tamponi dovrebbe essere il numero di tamponi analizzati su base cumulativa dall'inizio. Per lo meno, il numero riferito all'Abruzzo corrisponde a questa considerazione sulla base di quanto dichiarato sulla pagina della regione Abruzzo. Il dato che tu giustamenti rilevi per il Friuli sarà una qualche sorta di errore.

**Comment by umbros** [comment]
Ciao: totale dei tamponi (test) effettuati, un soggetto può essere sottoposto a più tamponi quindi non è indicativo delle persone controllate.
