### ISSUE TITLE
I dati mancanti delle regioni vengono integrati successivamente?

### ISSUE THREAD

**Issue by restuccia** [pcm-dpc/COVID-19#305]
**Tipo di richiesta**: richiesta di informazione

## Riassunto

Visto il mancato aggiornamento da parte di alcune regioni in diversi giorni, i dati vengono integrati nel giorno seguente (dunque riportati nel giorno sbagliato), vengono ignorati del tutto, o i file vengono aggiornati non appena i dati diventano disponibili?

Mi riferisco in particolare ai seguenti problemi:
- 18/03/2020: dati Regione Campania non pervenuti.
- 18/03/2020: dati Provincia di Parma non pervenuti.
- 17/03/2020: dati Provincia di Rimini non aggiornati.
- 16/03/2020: dati P.A. Trento e Puglia non pervenuti.
- 11/03/2020: dati Regione Abruzzo non pervenuti.
- 10/03/2020: dati Regione Lombardia parziali.

Ad esempio, i dati della Regione Campania non pervenuti il 18/03 sono scomparsi, sono stati aggiunti in ritardo al file del 18 o sono stati comunicati tutti insieme il 19? Cosa è stato fatto per tutti i dati non pervenuti finora?

## Interesse pubblico

Accuratezza dei dati

**Comment by umbros** [comment]
Ciao @restuccia, confermo che i dati vengono reintegrati il giorno dopo.
