### ISSUE TITLE
ricoveri terapia intensiva

### ISSUE THREAD

**Issue by Acco82** [pcm-dpc/COVID-19#306]
Salve,
i ricoveri in terapia intensiva sono dati cumulati?
Ho rilevato che in Valle d'Aosta il 17/03 ci sono 6 ricoveri in terapia intensiva e il 18/03 sono 3.
Grazie

**Comment by floatingpurr** [comment]
Credo siano valori giornalieri. Lo deduco dal fato che concorrono al calcolo del `totale_attualmente_positivi`.

**Comment by Achab94** [comment]
Concordo con @floatingpurr, la variabile misura quanti pazienti sono attualmente ricoverati in terapia intensiva per ciascun giorno. E' dunque possibile che la variabile cresca o decresca nel tempo. Prendendo le differenze prime di quella variabile (ovvero, la variabile ricavata facendo la differenza tra il valore di un giorno ed quello del giorno precedente) si dovrebbe dunque trovare il "saldo di pazienti" in terapia intensiva di quel giorno: se il dato è positivo, significa che in quel giorno è cresciuto il numero di pazienti ricoverati in terapia intensiva; se il dato è negativo il contrario. In tal caso la differenza prima rileverebbe in data 18/03 un -3. Vi torna?

Leggevo comunque sul README della repo che questo pomeriggio dovrebbero pubblicare alcune descrizioni ed informazioni aggiuntive sulle variabili.

**Comment by jacopoc** [comment]
Il dato sui ricoveri in terapia intensiva (campo "terapia_intensiva") è il dato giornaliero relativo al numero di persone in degenza in terapia intensiva nel giorno. Quindi è un dato *giornaliero* e *non cumulativo*.
Attenzione però che non descrive il numero di nuovi ricoverati in terapia intensiva el giorno: per questo devi sottrarre al valore del campo terapia_intensiva il valore del giorno precedente (e, per essere un po' più precisi, dovresti sommare anche il numero di nuovi decessi).
Qui sotto riporto il significato di altri campi:

<totale_casi> = dimessi_guariti + deceduti + <totale_attualmente_positivi>
<totale_attualmente_positivi> = isolamento_domiciliare + terapia_intensiva + ricoverati_con_sintomi
<totale_ospedalizzati> = terapia_intensiva + ricoverati_con_sintomi
<nuovi_attualmente_positivi> = DELTA(totale_attualmente_positivi)

tamponi 
      |
      |
     \/
isolamento_domiciliare  <--> ricoverati_con_sintomi <--> terapia_intensiva
      |                                                                                                          |
      |                                                                                                          |
     \/                                                                                                         \/
dimessi_guariti                                                                                deceduti

**Comment by danielesalpietro** [comment]
per evitare "false" indicazioni, non sarebbe più corretto classificare:
**<totale_contagiati_identificati> = isolamento_domiciliare + terapia_intensiva + ricoverati_con_sintomi**

il **<totale_attualmente_positivi>** può essere un dato solo stimato su base statistica partendo da un dato certo il **<totale_deceduti>**, visto che la popolazione tutta non viene (ne mai verrà) dotata di tamponi (frequenti) o di sistemi di autodiagnosi precoce.

**Comment by jacopoc** [comment]
> Salve,
> i ricoveri in terapia intensiva sono dati cumulati?
> Ho rilevato che in Valle d'Aosta il 17/03 ci sono 6 ricoveri in terapia intensiva e il 18/03 sono 3.

Secondo me il giorno 18/03 in Valle d'Aosta uno dei 6 ricoverati in terapia intensiva è deceduto (portando il valore del campo "deceduti" da 2 a 3) e 2 sono stati spostati in altro reparto dell'ospedale (andando ad incrementare di 2 il valore di "ricoverati_con_sintomi").

**Comment by retegaia** [comment]
> per evitare "false" indicazioni, non sarebbe più corretto classificare:
> **<totale_contagiati_identificati> = isolamento_domiciliare + terapia_intensiva + ricoverati_con_sintomi**
> 
> il **<totale_attualmente_positivi>** può essere un dato solo stimato su base statistica partendo da un dato certo il **<totale_deceduti>**, visto che la popolazione tutta non viene (ne mai verrà) dotata di tamponi (frequenti) o di sistemi di autodiagnosi precoce.

molto corretto! Si continua a concentrare l'attenzione sui positivi quando invece occorre osservare proprio i deceduti, che al momento rappresentano il dato più triste ma anche il più affidabile.

**Comment by Acco82** [comment]
Grazie a tutti per le risposte.
Concordo anche io che i ricoveri in terapia intensiva sono un dato di prevalenza ovvero numero di ricoverati medio al giorno.
Aggiungo che a mio avviso i dati più affidabili al momento sono decessi e ricoveri in terapia intensiva e il secondo è più affidabile del primo dato che potrebbero non aver indicato come causa primaria di morte la positività al covid nel caso di patologie multiple.
I ricoveri in terapia intensiva rappresentano secondo me il dato più affidabile e robusto considerato che probabilmente i ricoveri ordinari vengono decisi con criteri eterogenei tra le regioni.

**Comment by mtinti** [comment]
Leggendo quanto detto mi domando se la differenza fra i deceduti e il numero di persone in terapia intensiva è indicativo di quanto spazio disponibile c'è negli ospedali. 

Se ieri questa differenza era 1377, significa che ieri (semplificando molto) 1377 persone non hanno trovato posto in ospedale?
![COVID2](https://user-images.githubusercontent.com/8666061/77232620-17674180-6b9a-11ea-83b4-265f7fc1a8ab.png)

**Comment by lianne** [comment]
È possibile fare un check sul dato delle terapie intensive di oggi (21 marzo) in Campania? È particolarmente elevato rispetto all’andamento dei giorni scorsi...:-(

**Comment by markul-uksw** [comment]
> I believe they are daily values. I deduce it from the fate that contribute to the calculation of the `totale_attualmente_positivi`.

Sorry for interfering, I am IT specialist, not from medical field, but it looks quite opposite to me: these make sense as cumulative counts of admissions to ICU. When you graph the data assuming it is daily (actual) count of patients in ICU, it is very smooth, monotonically rising sigmoid-like curve, like there would be only increase, every day more coming in then coming out. It's more a hunch then a proof, but it doesn't seem realistic. When you plot a graph assuming these are cumulative values, it makes more sense. I don't mind sharing my spreadsheet with graphs - m.kulczycki@uksw.edu.pl
 
Best regards and wishes of good health to all Italians - from Poland :)

**Comment by floatingpurr** [comment]
As I mentioned, according to the data definition, this seems the daily value

This is the time series of such a count. 

![image](https://user-images.githubusercontent.com/14820600/77704877-7378fe00-6fbe-11ea-8a6a-8d9cb64f4ce9.png)

Probably, the sigmoid pattern has an upper bound determined by how many ICUs are potentially available. Again, that's just my guess.

Looking forward to hearing more from data owners.

**Comment by umbros** [comment]
Ciao, sono dati cumulativi, ovviamente possono decrescere quando si passa da uno stato di terapia intensiva a ospedalizzato o deceduto o guarito. Grazie a tutti per la collaborazione

**Comment by joscit** [comment]
> Ciao, sono dati cumulativi, ovviamente possono decrescere quando si passa da uno stato di terapia intensiva a ospedalizzato o deceduto o guarito. Grazie a tutti per la collaborazione

Grazie. A questo punto 

ti(oggi)= ti(ieri)-usciti+nuovi_ti

[ti(oggi)-ti(ieri)]= nuovi_ti - usciti -> indica la differenza del dato terapia_intensiva

Se gli usciti da terapia intensiva  possono andare a ospedalizzati o deceduti o guariti come si fa a calcolare il dato <usciti> in modo da conoscere il numero delle nuove terapie intensive giornaliere ? 

grazie
giuseppe
