### ISSUE TITLE
data di riferimento positivi

### ISSUE THREAD

**Issue by mauroln** [pcm-dpc/COVID-19#307]
A quale data si riferiscono i dati dei "positivi": alla data del prelievo (tampone) o a quella dell'accertamento della positività? Immagino alla data del prelievo, ma vorrei una risposta certa
Grazie

## Riassunto

Data di imputazione dei dati riferiti ai contagiati

## Interesse pubblico

Una corretta comprensione della cronologia dei contagi è necessaria per una corretta analisi dell'andamento temporale

**Comment by Tantormai** [comment]
Se guardi i dati per Provincia vedi che i casi "altro/in fase di verifica" sono conteggiati nei casi totali del giorno che includono tutte le tipologie di casi, inclusi gli "attualmente positivi", che sono la somma di "Ricoverati con sintomi", "Terapia intensiva" e "Isolamento domiciliare". Immagino che i casi "altro/in fase di verifica" appartengano per lo più all'ultima categoria e che siano confermati, o annullati, il giorno successivo.

**Comment by pierluigicara** [comment]
L'unica data che viene riportata è quella del conferimento dei dati al Dipartimento della protezione civile da parte del Ministero della Salute, ovvero quella riportata nella colonna data.
