### ISSUE TITLE
Link to data sets

### ISSUE THREAD

**Issue by brucellino** [pcm-dpc/COVID-19#31]
The README claims :

> Dati forniti dal Ministero della Salute

Could a link / DOI to the original data set be provided?

*update 03.08.2020* :

It seems that https://www.europeandataportal.eu/data/datasets/pcm-000086-20200306-110700?locale=en and https://www.europeandataportal.eu/data/datasets/pcm-covid-19-05032020-093000?locale=en point to this repository.

**Comment by brucellino** [comment]
@umbros Perhaps there is some subtlety which escapes me, but I would like to suggest treating the data in this repository in a "FAIR" way. (for background see https://www.force11.org/group/fairgroup/fairprinciples). These are public data which demand the highest degree of trustworthiness and persistent storage. Whilst volatile, they can remain in this repo, but it would be good practice to actually deposit them in a data repository for preservation, harvesting, etc.

May I suggest the following workflow:

1. As data are updated (seems to me this is done currently on a daily basis), a tag is applied to the repo, to create a GitHub release.
1. This release is deposited to to a public repository with a persistent unique identifier associated with it:
  - https://www.dati.gov.it/
  - https://zenodo.org/

If e.g. this repository is linked to Zenodo (a catch-all scientific data repository owned and operated by @CERN), this deposition is an automatic process - new GitHub releases create new versions of the Digital Object Identifier (DOI) which uniquely and persistently identifies this data set.

Happy to help if this is deemed worthwhile.

**Comment by umbros** [comment]
Thank you for your suggestion @brucellino

**Comment by brucellino** [comment]
The pleasure is all mine. Thank you all for your work.
