### ISSUE TITLE
Aggiornamento formato date

### ISSUE THREAD

**Issue by davpirelli** [pcm-dpc/COVID-19#310]
**Tipo di richiesta**: richiesta di informazione

## Riassunto

Ho letto che oggi alle 18:30 ci sarebbe stato un cambio di formato delle date.
Avendo preparato un update del sito ad hoc, assieme ad altre modifiche, volevo solo sapere se era confermato per oggi il cambio del formato (quindi potrei aspettare per fare un rilascio) oppure se verrà riprogrammato.

## Interesse pubblico

Capire come comortarsi con le varie applicazioni e siti sviluppati che si basano sui dati ufficiali.

**Comment by EmilianoBruni** [comment]
Stesso problema ma, per fortuna, prima di lanciare l'update ho dato un'occhiata ai dati :-) Però volevo ringraziare Umberto per l'ottimo lavoro fatto da lui e dal dipartimento :-)

**Comment by davpirelli** [comment]
Concordo con te, @umbros complimenti per l'ottimo lavoro!
@EmilianoBruni infatti, io sono in attesa di sapere se rimodificare le funzioni di Carbon e fare il rilascio di altre modifiche, o se fare "tutto insieme".
Vediamo :)

**Comment by umbros** [comment]
Ciao a tutti, scusate della mancata informazione la cosa partirà da lunedì alle 18:30.

**Comment by davpirelli** [comment]
@umbros Grazie e buon weekend!
