### ISSUE TITLE
Richiesta di conferma del calcolo dei positivi nei vari campi

### ISSUE THREAD

**Issue by EmilianoBruni** [pcm-dpc/COVID-19#311]
**Tipo di richiesta**: richiesta di informazione 

## Riassunto

Sulla documentazione leggo che il  n. totale_attualmente_positivi  (e a questo punto quindi penso chesi riferisca anche a tutti i campi "positivi) è il totale attualmente positivi (ospedalizzati + isolamento domiciliare). 

Ora il problema è che, ad esempio, io sono stato in isolamento domiciliare (ormai trascorso per fortuna) perchè ho fatto una settimana in un reparto con un paziente poi risultato positivo. Ma non mi è stato fatto il tampone ne, a questo punto, suppongo di essere stato positivo. 

Quindi risultavo tra quelli in isolamento domiciliare ma non sono positivo. Il totale positivi mi aspettavo che fosse il n. di tamponi risultati positivi ad personam (tenendo conto che a qualcuno è stato fatto più di un tampone positivo per sicurezza).

## Interesse pubblico

Migliore chiarezza sul significato dei dati esposti.

**Comment by umbros** [comment]
Ciao @EmilianoBruni è un piacere risentirti, il totale positivi confermo che sono gli ospedalizzati + isolamento domiciliare.
Il numero di tamponi non da evidenza delle persone controllate perchè un soggetto potrebbe fare più tamponi. Stiamo facendo un wiki per meglio spiegare il tutto è che è in visione alla funzionalità wiki di github.
