### ISSUE TITLE
tests per region - tamponi per regione

### ISSUE THREAD

**Issue by nicolacavallini** [pcm-dpc/COVID-19#312]
**Type of issue**: richiesta di dati
## Summary

I would like to see the number of test per region per day. 
Mi piacerebbe vedere il numero di tamponi in ogni regione per ogni giorno

## Public interest

il rapporto positivi/tamponi mi sembra un buon indicatore della "densita'" di infetti rispetto alla popolazione, credo che questo numero possa variare significativamente di regione in regione.

i believe that a good indicator of the spreading of the infection is the ratio positive/tests beyond the absolute number of infected. I believe that this number could significantly vary  geographically, giving a batter view of the situation.

I can try to help elaborating/cleaning/organising the data if needed.

This is my analysis so far:
https://sites.google.com/view/covid-19-another-plot/home

**Comment by luca-conterio** [comment]
Non sono un medico o un esperto, ma ci andrei un po' con le pinze. La descrizione del dataset cita "totale dei tamponi (test) effettuati, un soggetto può essere sottoposto a più tamponi quindi non è indicativo delle persone controllate".

**Comment by MauroCapolino** [comment]
All 
I have developed and keep up to date from this site an interactive dashboard with all the possible global and Italian date and lot of analysis Including test per region, conversion rate test to cases....

I also generate an automated daily report pdf (contact me if you like to subscribe) , but the interactive version is much better for analysis. 

Here is the link
https://datastudio.google.com/u/0/reporting/9ce371f1-62fa-4f2e-8d3c-da4d6dff967b

**Comment by rabalb** [comment]
In the daily update for each region, is the number of tamponi cumulative?

**Comment by rabalb** [comment]
> In the daily update for each region, is the number of tamponi cumulative?

If yes, there are some issues with the numbers for instance of Lombardia. On the 26/02 number of tamponi 3208. On the 25/02 number of tamponi 3700.

**Comment by nicolacavallini** [comment]
pardon, my bad, data where in the cvs files. none of the previous comments were related to my question.

**Comment by MauroCapolino** [comment]
For each i report both total and increase 
In the title and in the field is specified

Mauro

**Comment by MauroCapolino** [comment]
Which page of the report so that I can check?

Mauro
