### ISSUE TITLE
National trend Wiki page

### ISSUE THREAD

**Issue by luca-conterio** [pcm-dpc/COVID-19#313]
**Type of issue**: wiki enhancement

## Summary

Translation of the national trend wiki page from italian to english.

## Public interest
Allow non-italian speakers to have a description of the fields in the dataset.<br>
Here you can find the page I translated:
[https://github.com/luca-conterio/COVID-19/wiki/1.en---Data:-national-trend](url)

**Comment by FedericoStra** [comment]
The link is broken. The printed text is a valid url, though.

More importantly, your description of `nuovi_attualmente_positivi` as "total of new positive cases in the current day" is **WRONG**. The same way as the italian version is wrong too.

See #263, #268, #275, #277, #292, #294, #315, #332.

There is a lot of people that keep misinterpret `nuovi_attualmente_positivi` as if it were the number of new infections confirmed in a day. **It is not!**. It is the change in the number of currently positive people. Some persons become positive (new infections), some other persons cease to be positive (they recover or die). `nuovi_attualmente_positivi` is the net sum: `new_cases - new_recovered - new_deceased`.

**Comment by umbros** [comment]
Hi @luca-conterio we are working on it.
