### ISSUE TITLE
Correggere descrizione di `nuovi_attualmente_positivi` nella Wiki

### ISSUE THREAD

**Issue by FedericoStra** [pcm-dpc/COVID-19#314]
Tipo di issue:

- [ ] Dati mancanti o errati 
- [x] Errore nella documentazione: https://github.com/pcm-dpc/COVID-19/wiki/1.it-Dati:-andamento-nazionale
- [ ] Errore or mancanza nella dashboard 
- [ ] Problemi di visualizzazione nella dashboard 

## Problema

L'attuale descrizione di `nuovi_attualmente_positivi` è

> totale dei nuovi casi positivi del giorno corrente

Questa descrizione è inesatta e alla base di numerosi equivoci come testimoniato da diversi issues aperti in questo repository. Il numero di nuovi casi risultati positivi nel giorno in corso si calcola come differenza tra il `totale_casi` del giorno corrente e il `totale_casi` del giorno precedente. `nuovi_attualmente_positivi` non è il "totale dei nuovi casi positivi", come scritto nella descrizione, bensì il bilancio dei casi attualmente positivi, ovvero `nuovi_casi - nuovi_dimessi_guariti - nuovi_deceduti`.

## Soluzione

Modificare la descrizione in:

> bilancio del numero di persone attualmente positive, ovvero nuovi casi meno guariti meno deceduti: `nuovi_casi - nuovi_dimessi_guariti - nuovi_deceduti`

**Comment by umbros** [comment]
@FedericoStra, abbiamo già definito che i nuovi_attualmente_positivi è dato dalla differenza di totale_attualmente positivi del giorno attuale e del giorno precedente, come già più volte indicato. Ogni altro eventuale calcolo di cui necessiti lo puoi fare con i dati a disposizione

**Comment by FedericoStra** [comment]
Questa risposta non c'entra niente con la domanda.

Il problema è nella descrizione del campo `nuovi_attualmente_positivi` nella Wiki. La definizione "totale dei nuovi casi positivi del giorno corrente" è **sbagliata**. Questo è un fatto oggettivo.

> Ogni altro eventuale calcolo di cui necessiti lo puoi fare con i dati a disposizione

Cosa c'entra? Non ho chiesto ulteriori dati. I calcoli me li so fare da me. La questione di questo issue è correggere una didascalia nella Wiki che continua a essere fraintesa da un mare di persone.
