### ISSUE TITLE
Previsioni sulle terapie intensive

### ISSUE THREAD

**Issue by gianlab** [pcm-dpc/COVID-19#316]
Salve,
Vi segnalo che ho aggiunto alla previsione sulle terapie intensive fatta col modello ARIMA, una previsione fatta tramite regressione polinomiale di grado 2 o 3 che mi pare si adatti meglio ai dati come si vede dai grafici e dalla visualizzazione del sommario dei modelli : 

https://www.kaggle.com/gianlab/previsioni-sulla-terapia-intensiva-in-italia

**Comment by danielesalpietro** [comment]
Il modello non tieni conto almeno di due variabili importanti: il numero di persone a rischio in quella regione ed il rallentamento dell'infezione dovuto all'isolamento delle persone; in molte città il numero di interazioni è  molto più basso rispetto a quanto avviene nelle città metropolitane grandi dove ci sono servizi di trasporto (metropolitana) e luoghi di concentrazione (cinema, centri commerciali, piazze, movida, etc.). 
Comunque è interessante il tuo lavoro, mi piacerebbe migliorarlo....

**Comment by gianlab** [comment]
Per modificarlo basta che ti iscrivi a kaggle, selezioni il kernel e poi Fork. Le modifiche se vuoi potresti renderle pubbliche così tutti possono vederle . Ciao
