### ISSUE TITLE
Collecting works based on this dataset

### ISSUE THREAD

**Issue by vincenzomanzoni** [pcm-dpc/COVID-19#317]
**Type of issue**:  enhancement 

## Summary
Currently, many researchers and research teams are working on the dataset provided by the Italian Protezione Civile. It would be great to have a .md file or a wiki page where the most notable works based on this data are shared, perhaps divided into categories (e.g. exploratory data analysis, interactive visualizations, modeling, ...).

## Public interest
Researchers will have an organized place where to find notable works based on this dataset, from which they can take inspiration or enhance them.

## Final note
If needed, I can help.

**Comment by umbros** [comment]
Hi @vincenzomanzoni, we choose to not publish a CONTRIBUTOR file, because we can't check the quality of products and how data is managed, you can open a personal repository and collect all the works based on our data.

Thank you for your contribution

**Comment by vincenzomanzoni** [comment]
Thanks for your prompt reply, @umbros . I'll do it. All the bests!
