### ISSUE TITLE
JUST FAKE

### ISSUE THREAD

**Issue by SxtBox** [pcm-dpc/COVID-19#319]
WHY DO YOU LIE, WHERE ARE THE THE DEAD? ALSO HITLER DOESN'T KILL HOW YOU SAY, NOTHING IS DEAD, THIS IS PUSSY GAME

**Comment by Bakuriu** [comment]
Potete segnalare l'abuso di questo utente andando sul suo profilo e cliccando "Report abuse". Io l'ho già fatto.

**Comment by dinolupo** [comment]
Segnalato, prego chiudere la issue.

**Comment by umbros** [comment]
Grazie a tutti
