### ISSUE TITLE
utilizzare doppia lingua 🇮🇹🇺🇸 sugli Issues, Pull Requests e Documentazione

### ISSUE THREAD

**Issue by natydev** [pcm-dpc/COVID-19#32]
Data l’importanza dei dati COVID-19 Italia non solo nella EU ma in tutte le aree occidentali,
forse sarebbe utile, per agevolare coloro che non parlano la lingua italiana, sforzarsi di inserire i contenuti in doppia lingua, esempio:

```
Versione Italiana: IT

Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. 

--------------------------

English version: EN

Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
```

**Comment by umbros** [comment]
Grazie della segnalazione, la metto in ToDo e faccio un ISSUE TEMPLATE con il suggerimento @natydev

**Comment by brucellino** [comment]
@umbros I suggest #34 :

1. Keep an issue template for different kinds of issues (requests, errors, etc)
1. Keep a language-specific template with relevant comment and structure 

English speakers can open the English template, Italian speakers the Italian template.
Happy to contribute further if this is deemed desirable.

**Comment by nathanshammah** [comment]
Stavo per proporre la stessa cosa soprattutto per il readme e la struttura dei json file. Se può essere utile posso incominciare a tradurre io con una pull request. Ottima iniziativa, se capisco bene soppianta quella non ufficiale di @ondatait.

**Comment by umbros** [comment]
Ciao, stiamo realizzando una nuova versione del README e le issue già sono in doppia lingua. Grazie a tutti.
