### ISSUE TITLE
Aggiunta di Contributing guidelines

### ISSUE THREAD

**Issue by mberlanda** [pcm-dpc/COVID-19#322]
**Tipo di richiesta**:  richiesta di informazione  | suggerimento di miglioramento (documentazione, label, _ecc_)

## Riassunto

Le contribuzioni su questo repository sono ben accette oppure no? Ho l'impressione che al di là di qualche PR per correggere accenti o poco più nei file markdown tutte le altre siano state rigettate (delle 35 closed, solo 4 sono merged). Se non c'è la volontà di lasciar contribuire la community disabiliterei la possibilità di effetuare dei fork e aggiungere una linea nel README.

Qualora vi fosse invece la volontà di lasciar contribuire, penso che sarebbe necessario aggiungere delle contributing guidelines definendo:
* lingua del repository: al momento la comunicazione è mista inglese/italiano
* scope delle contribuzioni: può essere interessante proporre delle implementazioni alcune suggerite in vari linguaggi al fine di procedere a delle forme di visualizzazioni (e anche di analisi statistiche) da applicare ai dati forniti?

## Interesse pubblico

La stragrande maggioranza delle pull requests su questo repository sono rigettate. Presumibilmente mancano delle chiare guidelines su come e in che misura contribuire.

Se l'obiettivo è unicamente la pubblicazione dei dati e non si accettano altre iniziative (es. snippet di codice etc), probabilmente sarebbe opportuno indicarlo esplicitamente.

**Comment by umbros** [comment]
Ciao @mberlanda,
lo scopo di questo repository è quello di erogare dati, non software di trasformazione o rappresentazione dati, le pr che arrivano che riguardano tool vengono rigettate ma sono benvenute quelle dove si segnala errore dei dati (spesso risolviamo la cosa in pochi minuti noi qui). Quindi non è un "non considerare" i contributi di altri ma una policy di questo repository (approfitto per scriverla). Relativamente al CONTRIBUTOR file è stato scelto di non mettere un elenco di lavori fatti sulla base di questi dati perchè essendo il tema molto delicato non possiamo avere il controllo su quello che viene fatto su quei dati. Ovviamente chiunque può pubblicare sul proprio repository ogni tool e scrivere che utilizza i nostri dati.
