### ISSUE TITLE
Total deaths

### ISSUE THREAD

**Issue by krzbar** [pcm-dpc/COVID-19#323]
**Type of issue**:  richiesta di informazione | richiesta di dati | suggerimento di enhancement (documentazione, label, _etc_)

## Summary

I apologize, if this information is provided in Italian and I missed it. I think there was something concerning the provinces on this (/issues/156 ? provinces only manage positive cases) but maybe there is information concerning this on the national Italian level? Is it possible to obtain the total number of deceased per day in Italy (or individual provinces)? In *regioni* files you have a column "deceduti" but this I understand is the number of deceased in the given province on the given day that were tested positive? Even if this would only be available on the national (and not provinicial level) I still believe it would be extremely useful.

## Public interest

This will allow for putting the covid positive deaths in a proper perspective and I believe for extracting a huge amount of information about the pandemic's dynamics.

**Comment by jacopoc** [comment]
You can derive the number of deaths per day in Italy by subtracting the value of the field "deceduti" with the value of the same field on the day before:
https://github.com/pcm-dpc/COVID-19/blob/master/dati-andamento-nazionale/dpc-covid19-ita-andamento-nazionale.csv

**Comment by krzbar** [comment]
Thanks! But I think that deceduti is the number of covid-19 deceased positive for the given day?
What I am asking about is the total number of deceased per day in Italy: covid-19 positive and negative summed.

**Comment by jacopoc** [comment]
> Thanks! But I think that deceduti is the number of covid-19 deceased positive for the given day?

"deceduti" is the *cumulative* number of covid-19 deceased positive since the start of the emergency.

> What I am asking about is the total number of deceased per day in Italy: covid-19 positive and negative summed.

I see what you mean now: yes, it would be useful to know.

**Comment by GiacomoA92** [comment]
So you mean the number for deceased for any reason?
Unfortunately this is not possible to obtain for every day. There simply does not exist a central authority that obtains & publishes such information on a daily basis. The best there is Istat probably http://dati.istat.it/Index.aspx?QueryId=19670 which has statistics for the past months.

**Comment by aldogangemi** [comment]
Hello, I need the COVID death data per province for research purposes: currently there is only the data per region. Any chance I can get it?
Thanks

**Comment by krzbar** [comment]
Thank you! I will have a look at the istat.it service.

**Comment by mazinthebox** [comment]
> Hello, I need the COVID death data per province for research purposes: currently there is only the data per region. Any chance I can get it?
> Thanks

Not for now, as they said.

**Comment by umbros** [comment]
I confirm what is said there. Thank you for collaborations
