### ISSUE TITLE
Modificata nome dei campi da ITALIANO a INGLESE

### ISSUE THREAD

**Issue by danielesalpietro** [pcm-dpc/COVID-19#325]
Visto l'interessa a livello mondiale dei dati pubblicati, si richiede se non si possa cambiare i nomi dei campi da Italiano a Inglese per rendere più comprensibili le informazioni anche al resto del mondo.

**Comment by FedericoStra** [comment]
Possibilmente adottando un lessico adeguato in modo tale che non ci siano ambiguità, come invece sono presenti allo stato attuale. Delle etichette ragionevoli sono per esempio: `total_cases`, `new_cases`, `total_recovered`, `total_deceased`, `currently_positive`, `delta_positive`, `currently_hospitalized`, `currently_quarantined`, `currently_icu`...

**Comment by umbros** [comment]
@danielesalpietro stiamo preparando un wiki dove verranno spiegati anche in lingua inglese il significato dei campi. @FedericoStra grazie ma riteniamo che le etichette siano ragionevoli.

**Comment by danielesalpietro** [comment]
> @danielesalpietro stiamo preparando un wiki dove verranno spiegati anche in lingua inglese il significato dei campi. <

il significato dei campi che metterete sul wiki si perderà nella notte dei tempi, i file vengono importanti su altri sistemi e verranno commentati nel codice e nei documenti; se l'origine fosse già in inglese aiuterebbe molto tutti; sul wiki potreste mettere i campi in inglese e la spiegazione in italiano...... credo che il mondo scientifico vi ringrazierebbe molto ;-)

**Comment by AvverbioPronome** [comment]
@danielesalpietro sono d'accordo che sarebbe stato meglio partire con le etichette in inglese, ma cambiarle in corso d'opera romperà quasi sicuramente tutto il software che analizza questi dati. Non ne vale la pena.

**Comment by danielesalpietro** [comment]
Se non lo fate voi, che siete la fonte primaria, lo faranno sicuramente altri, creare un secondo folder con suffisso _ENG  <dati-province_ENG> dove scaricare la copia dei file con i campi in Inglese, non credo vi costerebbe troppo tempo e non romperà quasi sicuramente nulla, che dici ? 

Se iniziate voi a fornire un modello di dati standard, gli altri paesi vi seguiranno e forse arriveremo ad avere uno standard per tutti i paesi; ne avremmo tutti un vantaggio incredibile potendo poi condividere anche script ed algoritmi comuni..... pensateci, tanto quest'emergenza non finirà presto.... avete tutto il tempo per sistemare bene le cose ;-)

**Comment by AvverbioPronome** [comment]
Un secondo folder, ma diosanto, perché sei così complicato.

Ti basta scriverti uno scriptino che chiama `sed -i s/nome_italiano/nome_inglese/g nome_cartella/*` ogni volta che cloni.

**Comment by danielesalpietro** [comment]
vedo che non mi hai capito, colpa mia.... io non ne facevo un problema "tecnico", ma di standard....pazienza.
