### ISSUE TITLE
[Help wanted][check] Mappa Coronavirus non più aggiornata - dati vecchi - errori nelle note!!

### ISSUE THREAD

**Issue by AlbertoP64** [pcm-dpc/COVID-19#326]
Tipo di issue:
- [x] Dati mancanti o errati (vedi sotto) DATI VECCHI!
- Regione: ALL

## Riassunto
ATTENZIONE: La mappa Coronavirus Italia (protezione civile)
 non è aggiornata (i dati sono vecchi), e vi sono degli errori
 indicati nel box delle note (angolo inferiore sinistro)

**Attesa:**
> dati attuali aggiornati (per confronto) dalla pagina del Ministero della salute:
[pagina dati Coronavirus ultim'ora Ministero della Salute](http://www.salute.gov.it/portale/nuovocoronavirus/dettaglioContenutiNuovoCoronavirus.jsp?lingua=italiano&id=5351&area=nuovoCoronavirus&menu=vuoto)

La situazione in Italia: 21 marzo 2020, ore 18.00
ATTUALMENTE POSITIVI 42681
DECEDUTI 4825
GUARITI 6072

**Attuale:**
> Dati di questa mappa (dashboard) (linkata anche dalla pagina di cui sopra):
http://opendatadpc.maps.arcgis.com/apps/opsdashboard/index.html#/b0c68bce2cce478eaac82fe38d4138b1

Ultimo aggiornamento  21/03/2020 17:00
Totale positivi 47.021
Deceduti 4.032 (in attesa di conferma ISS)
Guariti   5.129

> come vedete dal confronto, Sulla mappa ci sono dati molto vecchi!!

> Note (box angolo inferiore sinistro):

18/03 - Dati Campania non aggiornati
18/03 - Dati Parma non aggiornati
17/03 - Dati Rimini non aggiornati
16/03 - Dati P.A. Trento e Puglia non pervenuti
11/03 - Dati Abruzzo non pervenuti
10/03 - Dati Lombardia parziali
07/03 - Dati Brescia +300 esiti positivi

> Non so se questi messaggi siano correlati con il problema sui dati

** Related Issues:
#324 (open)
#211 (closed but why?)

**Comment by umbros** [comment]
@AlbertoP64 i dati erano in aggiornamento, non risulta quanto da te segnalato, le note sono solo per i dati mancanti o parziali.

**Comment by AlbertoP64** [comment]
@umbros , ma che cosa vuol dire "i dati erano in aggiornamento, non risulta quanto da te segnalato" Scusa?
I dati *non erano* aggiornati, mentre adesso improvvisamente lo sono!
Quindi, non mi sembra corretto questo atteggiamento.
Se c'era un problema, non si capisce perché non dirlo.
Se non c'era, perché allora i dati erano fermi?
Preferisco di gran lunga l'atteggiamento responsabile di chi non si nasconde dietro le negazioni.
Non ho parole, se questa dashboard è di gestione istituzionale, mi aspetto più serietà e trasparenza.
Ed un ringraziamento, magari, per chi si sbatte, scusate, per mettersi a segnalarvi un problema di cui evidentemente non avevate contezza.
