### ISSUE TITLE
Errore in dati Arezzo

### ISSUE THREAD

**Issue by liso88** [pcm-dpc/COVID-19#328]
Tipo di issue:

- [X] Dati mancanti o errati in dpc-covid19-ita-province
- [ ] Errore nella documentazione 
- [ ] Errore or mancanza nella dashboard 
- [ ] Problemi di visualizzazione nella dashboard 

- Regione: Toscana
- Provincia: Arezzo

## Riassunto

Il numero dei casi total del 19 marzo sono inferiori a quelli del 18 marzo, la progressione è : 71
71
142
113
124
136

c'è un errore nel 18 marzo

**Comment by umbros** [comment]
Ciao, grazie della segnalazione, abbiamo notato questo problema ed è un riallineamento e perfezionamento dati della P.A. Trento.
