### ISSUE TITLE
Progetto

### ISSUE THREAD

**Issue by vinci00** [pcm-dpc/COVID-19#33]
La ho contattata per un progetto rigurdante questa repo alla mail rosini@agid.gov.it e su linkedin con un messaggio privato, la prego di farmi sapere cosa ne pensa,
Grazie

**Comment by umbros** [comment]
@vinci00 non lavoro più ad AgID, rispondo su linkedin.

**Comment by vinci00** [comment]
Buon pomeriggio, non ho più avuto sue notizie, su linkedin sono vincentbianchetti.
Mi faccia sapre, grazie.
