### ISSUE TITLE
Errore su nuovi attualmente positivi per il giorno 22-03

### ISSUE THREAD

**Issue by raistant** [pcm-dpc/COVID-19#330]
Tipo di issue:

- [ *] Dati mancanti o errati: COVID-19/dati-andamento-nazionale/dpc-covid19-ita-andamento-nazionale.csv

## Riassunto

Nuovi attualmente positivi per il giorno 22-03 segnalati come 3957, in realtà dovrebbero essere 3657.

**Comment by alessandroAmedei** [comment]
Stavo per inviare una issue. Confermo errore.

**Comment by raistant** [comment]
Grazie per la conferma.
Speriamo correggano quanto prima

Fossero tutti così gli errori :-)

**Comment by pigreco** [comment]
Non riesco a capire l'errore dove sia:

nel wiki:
```
totale dei nuovi casi positivi del giorno corrente
differenza: totale_attualmente_positivi (giorno corrente) - totale_attualmente_positivi (giorno precedente)
```

`totale_attualmente_positivi (giorno corrente)` = `46638`
`totale_attualmente_positivi (giorno precedente)` = `42681`

la differenza fa : `3957`

**Comment by raistant** [comment]
quando ho segnalato c'era scritto 46338. per quello avevo segnalato l'incongruenza. poi hanno modificato a 46638.

**Comment by umbros** [comment]
Ciao, 
ieri non era partito l'aggiornamento del csv, che abbiamo fatto subito dopo. forse dipende da quello.

Grazie
