### ISSUE TITLE
[Enhancement] - Separate duplicate Lat, Long geodata fields from the actual data

### ISSUE THREAD

**Issue by orion434** [pcm-dpc/COVID-19#331]
**Type of issue**:
suggerimento di enhancement (documentazione, label, _etc_)

## Summary

Data from Provincie and Regioni (e.g. https://github.com/pcm-dpc/COVID-19/blob/master/dati-regioni/dpc-covid19-ita-regioni.csv) have latitude and longitude data for each entry. 
This data are always the same for each regione and provincia, and could be taken out of the current dataset and stored in a separate table. In addition, these are not integer data (with several digits) in an otherwise table of data, strings and integer fields.

Similar reasoning might be done on 'codice_regione/provincia' and 'denominazione_regione/provincia' but in this case, at least one key/identifier must be retained to identify correctly the data.

**Advantages of the current format**

- For each row you have all the information you need, and therefore is easier to read by a person on directly from the original file.

- It might reduce errors when producing the file in assigning data to the correct field (e.g. checking that the provincia Roma is in the Lazio region rather than provincia 58 is in region 12)

**Drawbacks of the current format**
- Produces redundant geographical information that increases the total file size and clutters the tables. 

**Advantages of the proposed format**

- If the current format was chosen on purpose (e.g. for data visualisation), the same results could be obtained merging the numerical data (e.g. join via the ref. code 'codice_regione/provincia' ) with a newly created table with those fields: codice_regione/provincia, denominazione_regione/provincia, (sigla_provincia), lat, lon.  

**Example of reduction in file size**
- dpc-covid19-ita-region.csv could go down by ~40%  (53 to 32 KB)
- dpc-covid19-ita-province.csv could go down by ~65% (279 to 98 KB)

## Public interest

- Removing duplicate fields results in having a smaller file size (resulting in faster computation), and no duplicate data. 
- People/researcher interested only in numerical data, and not in their geolocalisation, can download only those data, while the same results could still be achieved using the extra geolocalisation table.
 
**Proposed label**: enhancement. 

**<ins>Please, to reduce at minimum the time spent reading by moderators (and focus on more urgent tasks), think before commenting, and do comment only if you are adding valuable data or insight. Thank you.</ins>**

**Comment by pierluigicara** [comment]
Thanks @orion434 for your suggestion. I really agree with you about your consideration which can be syntetized as a normalization issue. Actually we need the schema you see when we producing and updating tha map and, at the moment, we cannot allocate more resource in further activity and therefore is easier for as "simply" put tha data as is in the repository. Anyway we are also working in a database organization of the data (normalized) that could be help you, but I'm not able to say you when we could release it.
