### ISSUE TITLE
Incorrect calculation of total numbers

### ISSUE THREAD

**Issue by javixeneize** [pcm-dpc/COVID-19#332]
Hi

I have a question regarding the total number of cases as i dont understand how it is being calculated. If you take as example the two first days, on 24th Feb there were 229 total cases. The day after, with 90 positives, the number moved to 322, when it should have gone to 319 isnt it?

The total number is the addition of positives+healed+deaths, so the explanation i have is that the number of deceased people (3) is being counted twice, both as an active case and as a death.

In my opinion, there should be an extra field, for the number of active positives. So, when somebody is healed or deceased, it decreases the number of active positives.

Going back to the original example, on the second day, the number of active positives should have gone up by 87 instead of 90, as there have been 90 new positives, but there are also 3 new deaths.

Looking forward to hear from you

thanks

**Comment by luca-conterio** [comment]
I think deaths are not counted in the new positive cases field, since they are not new positive cases (they could have the virus from previous days...). So on the 25th Feb you have 322 total cases, which is equal to the previous day 229 total cases, plus 90 new positive cases, plus 3 new deaths.

**Comment by javixeneize** [comment]
Thanks for the answer.

On 24th, the total number of cases was 229. If you add 90 new positives, the total number of cases is 319, not 322, as those 3 deaths have already been considered as a positive, isnt it?

**Comment by cirocorvino** [comment]
> On 24th, the total number of cases was 229. If you add 90 new positives, the total number of cases is 319, not 322, as those 3 deaths have already been considered as a positive, isnt it?

maybe the death people weren't among positives the day before, because they have been counted as positive only after their death. In Italy the test for positivty to the virus gets done also after death.

**Comment by javixeneize** [comment]
then, the number of positives that day should be 93 instead of 90, as those 3 deaths also count as positive.

Same happens with healed. I was expecting that when somebody is healed, the number of active cases decrease. Between 25th and26th, there are 74 new positives and 2 new healed. The number of positives increases in 74 (311+75=385) when it should increase only in 72 (311+75-2)

I think it should be reviewed as it well might be that the real number of cases or active cases is lower than the official figure.

**Comment by jacopoc** [comment]
Hi @javixeneize, please have a look at my comment:
https://github.com/pcm-dpc/COVID-19/issues/306#issuecomment-602029641

I hope it helps.

**Comment by FedericoStra** [comment]
@javixeneize This is indeed a serious problem in the current presentation of the dataset. The variable `nuovi_attualmente_positivi` is NOT the number of new infections confirmed every day (which is the difference between `totale_casi` of the day minus `totale_casi` of the previous day). `nuovi_attualmente_positivi` is instead the number of new infections minus the number of recovered persons minus the number of deceased persons.

See also #263, #268, #275, #277, #292, #294.

**Comment by javixeneize** [comment]
Thanks! Maybe it should be advertised in the readme or in a better place for the sake of transparency.

Thanks for the clarity on the data. Much appreciated. 

Sii forte ragazzi!
