### ISSUE TITLE
Dati Regione Puglia 22/03/2020 da rettificare.

### ISSUE THREAD

**Issue by marcodadamo** [pcm-dpc/COVID-19#333]
Tipo issue
- [X] Dati mancanti o errati
- [ ] Errore nella documentazione 
- [ ] Errore or mancanza nella dashboard 
- [ ] Problemi di visualizzazione nella dashboard 

- Regione: Puglia
- Provincia: 

## Riassunto
In riferimento alla directory  [COVID-19/dati-json/dpc-covid19-ita-regioni.json] nelle righe di codice, in riferimento alla Regione Puglia, nella voce **nuovi attualmente positivi** il numero è di 106, mentre leggendo il Bollettino Epidemiologico della stessa regione afferma 111 casi **risultati positivi** di cui alla data di riferimento, vedasi il link -> http://www.regione.puglia.it/news?p_p_auth=2Nt5tAnT&p_p_id=56_INSTANCE_8oLBj0XOEEsq&p_p_lifecycle=0&p_p_state=normal&p_p_mode=view&p_p_col_id=column-2&p_p_col_pos=1&p_p_col_count=6&_56_INSTANCE_8oLBj0XOEEsq_articleId=51022132&_56_INSTANCE_8oLBj0XOEEsq_groupId=3728079&_56_INSTANCE_8oLBj0XOEEsq_version=1.3&_56_INSTANCE_8oLBj0XOEEsq_categoryName=BOLLETTINO+EPIDEMIOLOGICO+REGIONE+PUGLIA+22%2F03%2F2020&_56_INSTANCE_8oLBj0XOEEsq_back=%2Fcoronavirus%2F

**Attuale:** Rettificare il dato da 106 a 111 attuali comunicati dal bollettino epidemiologico.
 {
        "data": "2020-03-22 17:00:00",
        "stato": "ITA",
        "codice_regione": 16,
        "denominazione_regione": "Puglia",
        "lat": 41.12559576,
        "long": 16.86736689,
        "ricoverati_con_sintomi": 252,
        "terapia_intensiva": 37,
        "totale_ospedalizzati": 289,
        "isolamento_domiciliare": 459,
        "totale_attualmente_positivi": 748,
        "nuovi_attualmente_positivi": 106,
        "dimessi_guariti": 7,
        "deceduti": 31,
        "totale_casi": 786,
        "tamponi": 6160
    },

**Comment by umbros** [comment]
Ciao @marcodadamo il dato riportato è quello comunicato da Regione Puglia.
