### ISSUE TITLE
Classificazione per età Epidemia Covid-19. Bollettino Epidemiologico Regione Puglia

### ISSUE THREAD

**Issue by marcodadamo** [pcm-dpc/COVID-19#334]
**Tipo issue**: miglioramento (documentazione)

## Riassunto
La Regione Puglia, mediante il proprio bollettino epideomiologico, ha diffuso una classifica di statistica per **Gruppi di Età**. 
L'informazione, come si esprime, viene nota per un totale di 776 casi, quindi su questo numero viene calcolata una determinata stima di classificazione.

**Letalità per età**. In questo schema viene elaborato un calcolo per l'età compresa fra 0 e 9 anni - 10 e 19 anni - 20 e 29 anni, 30 e 39 anni, 40, 49 anni e via discorrendo fino a > 90. 

![immagine](https://user-images.githubusercontent.com/56562822/77261689-82933f80-6c90-11ea-94a7-ceebe1e5f1f1.png)

## Interesse pubblico
Diffondere dati così da calcolare e rendere pubblico la stima dell'età coinvolta nel contagio.
[PDF EPIDEMIOLOGICO REGIONE PUGLIA](http://www.regione.puglia.it/documents/10180/50138902/Bollettino+covid+22_03/27f0e665-5084-4db8-9380-b65dc2ee5f01)

**Comment by paolomajo** [comment]
finalmente dei dati utili

**Comment by paolomajo** [comment]
vorrei vedere i dati relativi a Bergamo classificati in questo modo

**Comment by AgriTrade0** [comment]
La Regione Puglia ha attuato un bollettino epidemilogico dove inserisce una serie di dati nel svolgere statistiche per gruppi di età. Molto utile

**Comment by marcodadamo** [comment]
La Regione Puglia ha attuato un bollettino epidemilogico dove inserisce una serie di dati nel svolgere statistiche per gruppi di età. Molto utile

**Comment by alex-train** [comment]
Il Veneto è la regione con più contagi che ha fatto più tamponi, rispetto il numero di positivi. In questa regione dovremmo avere una attendibilità statistica più evidente.
Sarebbe quindi interessante avere per il Veneto una distribuzione della letalità per fasce d'età, che risulterebbe più realistica rispetto la letalità ora calcolata in Lombardia e nelle altre regioni ad alto rapporto positività/tamponi.
Avete dei dati in merito?

**Comment by giocaputo** [comment]
ma come è calcolata questa letalità? sembrano il rapporto tra i deceduti dall'inizio e l'ultimo incremento dei positivi.

**Comment by umbros** [comment]
Ciao, noi raccogliamo i dati di ogni Regione quindi se tutte le Regioni non si allineano o non c'è un dato stabile non viene messo (parlo di aumenti del numero di dati), comunque stiamo lavorando per fare ciò.
