### ISSUE TITLE
Initial contact with the French public taskforce for open data on covid-19

### ISSUE THREAD

**Issue by mathildehg** [pcm-dpc/COVID-19#336]
**Type of issue**: Initial contact with the French public taskforce for open data on covid-19

## Summary
The French Prime Minister taskforce force for Open Data would like to discuss with you the various actions you have implemented to make data related to covid-19 available in open data. 

## Public interest

Hi ! 

I work for Etalab, the French public taskforce for open data. We are currently in charge of publishing data related to the covid-19 outbreak. 

We have been very interested in the work you've been doing on the covid data from Italy and the dashboard you've developed. Well done! Your work has been a model of inspiration for our actions in France. 

For the time being, France publishes the following data by department, age group and gender:
- number of medical acts for suspicion of covid19
- number of emergency room visits for suspicion of covid19
- number of hospitalizations for suspicion of covid19
https://www.data.gouv.fr/fr/datasets/donnees-relatives-a-lepidemie-du-covid-19/

We would like to go further and publish new data, particularly on hospital infrastructures. 

=> Will you be available in the next few days to speak with our teams ? We are very interested in your approach, the way you have accessed the data and the difficulties you may have encountered. 

Have a good day and congratulations again! 
Mathilde

**Comment by umbros** [comment]
Hi  @mathildehg it's ok for me, please write me to umberto.rosini@protezionecivile.it. Thank you.

**Comment by pierluigicara** [comment]
Hallo @mathildehg you can also write to pierluigi.cara@protezionecivile.it. Bye

**Comment by mathildehg** [comment]
Ok i will ! thank you and take care
