### ISSUE TITLE
dati di oggi 23/3 

### ISSUE THREAD

**Issue by claort** [pcm-dpc/COVID-19#337]
Buongiorno,
novit per i dati di oggi ? 
grazie

**Comment by PietroGranati** [comment]
A quanto si legge nell prima pagina:
Oggi non verranno effettuati gli aggiornamenti programmati, ma verranno fatti il 25/03

**Comment by ngshya** [comment]
> A quanto si legge nell prima pagina:
> Oggi non verranno effettuati gli aggiornamenti programmati, ma verranno fatti il 25/03

Non era riferito al formato della data?

**Comment by PietroGranati** [comment]
Sembra vengano cambiati il formato data dal 25

**Comment by claort** [comment]
si appunto era riferito a quello credo non ai dati

**Comment by PietroGranati** [comment]
Pardon, è fraintendibile, vediamo

**Comment by claort** [comment]
aspettiamo risposte ufficiali ....

**Comment by emmekappa** [comment]
https://github.com/pcm-dpc/COVID-19/commit/2356aa13850d9d912b721de023cd168ee9d2156a

certo che pushare su master senza neanche una PR mi sembra un po' azzardato di questi tempi.

`</ironia>`
(si scherza per sdrammatizzare un po'...)

**Comment by ngshya** [comment]
Qualcuno ha fonti (ufficiali e/o non) alternative?

**Comment by specialworld83** [comment]
*** Oggi non verranno effettuati gli aggiornamenti programmati, ma verranno fatti il 25/03. ***

È scritto nel readme. Strano, perchè non dobbiamo sapere i numeri del contagio?

**Comment by emmekappasucchiacazzi** [comment]
puppamelo

**Comment by AndrewDevIT** [comment]
Ma i dati sono usciti, non capisco perché non li aggiornino qui dopo che diverse persone si affidano a questa repository

**Comment by Achab94** [comment]
@specialworld83 non fa riferimento ai dati quel messaggio, leggi su.

@ngshya se vuoi sapere i dati, c'è il canale Telegram t.me/covid19

**Comment by davpirelli** [comment]
> *** Oggi non verranno effettuati gli aggiornamenti programmati, ma verranno fatti il 25/03. ***
> 
> È scritto nel readme. Strano, perchè non dobbiamo sapere i numeri del contagio?

Ma cosa state dicendo... la notifica è riferita a **questo aggiornamento programmato**:

> 1. ogni data sarà convertita nel formato standard ISO8601: *YYYY-MM-DDTHH:MM:SS* - *2020-03-18T19:14:29*. Tutte le date saranno in UTC.
> 2. ad ogni dataset sarà aggiunto un campo note per dare informazioni sul dato specifico
> 3. sarà realizzato un nuovo dataset per fornire informazioni sui dati

I dati arriveranno, come sempre con un minimo di ritardo. Portiamo rispetto per chi ci lavora costantemente.

**Comment by PietroGranati** [comment]
> 
> 
> > *** Oggi non verranno effettuati gli aggiornamenti programmati, ma verranno fatti il 25/03. ***
> > È scritto nel readme. Strano, perchè non dobbiamo sapere i numeri del contagio?
> 
> Ma cosa state dicendo... la notifica è riferita a **questo aggiornamento programmato**:
> 
> > 1. ogni data sarà convertita nel formato standard ISO8601: _YYYY-MM-DDTHH:MM:SS_ - _2020-03-18T19:14:29_. Tutte le date saranno in UTC.
> > 2. ad ogni dataset sarà aggiunto un campo note per dare informazioni sul dato specifico
> > 3. sarà realizzato un nuovo dataset per fornire informazioni sui dati
> 
> I dati arriveranno, come sempre con un minimo di ritardo, abbiate pazienda..

Si io pure ho letto quello e mi ha tratto in inganno -.-

**Comment by ngshya** [comment]
> @ngshya se vuoi sapere i dati, c'è il canale Telegram t.me/covid19

Grazie! Se sai come procurare il csv di quel pdf sarebbe fantastico, altrimenti mi accontento lo stesso!

**Comment by floatingpurr** [comment]
Arrivati 2356aa1

**Comment by pierorubino** [comment]
> > *** Oggi non verranno effettuati gli aggiornamenti programmati, ma verranno fatti il 25/03. ***
> > È scritto nel readme. Strano, perchè non dobbiamo sapere i numeri del contagio?
> 
> Ma cosa state dicendo... la notifica è riferita a **questo aggiornamento programmato**:
> 
> > 1. ogni data sarà convertita nel formato standard ISO8601: _YYYY-MM-DDTHH:MM:SS_ - _2020-03-18T19:14:29_. Tutte le date saranno in UTC.
> > 2. ad ogni dataset sarà aggiunto un campo note per dare informazioni sul dato specifico
> > 3. sarà realizzato un nuovo dataset per fornire informazioni sui dati
> 
> I dati arriveranno, come sempre con un minimo di ritardo, abbiate pazienda..

Molto bene, mi stavo preoccupando. Si tratta dunque solo di aspettare

**Comment by Achab94** [comment]
Sembriamo degli eroinomani in fila davanti al SERT comunque ragazzi, io ve lo dico ahaha

**Comment by Andrea922** [comment]
I dati sono usciti
http://covid-live.it

**Comment by franjsco** [comment]
Confermo, i dati sono stati pubblicati con commit: 539e67f

**Comment by irvelervel** [comment]
Nessun problema per il ritardo, grazie mille per il lavoro che svolgete.
Il trend sembrerebbe continuare ad essere in calo --> https://dashboard.covid19med.it/

**Comment by Achab94** [comment]
Eh vabbè allora se vale tutto me la auto-cito anche io la mia dashboard: https://achab94.shinyapps.io/covid-19/

Comunque sarebbe da provare a raccoglierle tutte quante da qualche parte, @umbros che dici?

**Comment by umbros** [comment]
Sono arrivati i dati un po' in ritardo tutto qui :-)

**Comment by LorisBatacchi** [comment]
6000 vittime... è quasi la popolazione di San't Arcangelo di Romagna!

**Comment by pierorubino** [comment]
Gli ho gia elaborati
Grazie per il vostro prezioso lavoro quotidiano che consente di comprendere
un granello di una tragedia
#andratuttobene
Piero

-----------
mailto: pieroru1955@gmail.com
