### ISSUE TITLE
Incongruenza tra casi totali provinciali e quelli regionali

### ISSUE THREAD

**Issue by chuck2098** [pcm-dpc/COVID-19#341]
Buonasera a tutti,
ho notato che i casi totali positivi di tutte le province del Molise,ovvero Campobasso e Isernia, corrispondono rispettivamente a 54 casi totali e 4 casi totali; pertanto la somma tra questi due dati dovrebbe essere di  58 casi totali in tutto il Molise, mentre invece ne risultano 67.
Ho sbagliato io a consultare i dati, oppure l'errore c'è realmente?
Grazie, cordiali saluti. 

![WhatsApp Image 2020-03-23 at 19 04 37](https://user-images.githubusercontent.com/51959518/77349708-b8d9c900-6d3b-11ea-8a37-545b812cd9be.jpeg)
![WhatsApp Image 2020-03-23 at 19 04 38](https://user-images.githubusercontent.com/51959518/77349729-bd9e7d00-6d3b-11ea-9f9f-fa3e0571de46.jpeg)

**Comment by chuck2098** [comment]
Perdonatemi la dimensione delle immagini ma non so come modificare l'issue senza eliminarlo.

**Comment by umbros** [comment]
Ciao @chuck2098 è dovuto ai casi non allocati (in fase di aggiornamento +9)
