### ISSUE TITLE
Errore visualizzazione dati

### ISSUE THREAD

**Issue by FrancescoMandru** [pcm-dpc/COVID-19#342]
Salve, volevo segnalare che oggi i dati non sono visualizzati correttamente e tutti i plot non vengono visualizzati correttamente a loro volta.

Ringrazio il fantastico lavoro che il responsabile della repository sta svolgendo

**Comment by pierluigicara** [comment]
Si scusateci la piattaforma Arcgis online sta avendo dei problemi di sovraccarico, stiamo lavorando in stretto contatto con i tecnici di ESRI USA per risolvere il problema.
