### ISSUE TITLE
E' davvero possibile che i nuovi casi di Covid19 a Bologna il 23 marzo sono 833? Forse sono 733...

### ISSUE THREAD

**Issue by sebzan73** [pcm-dpc/COVID-19#343]
Potete verificare se c'è stato un errore di comunicazione o digitazione del dato? Guardando la serie storica c'è un picco inspiegabile in data odierna.

**Comment by pierluigicara** [comment]
Confermo il numero 833 pervenuto dal Ministero della Salute e riportato dal DPC.
