### ISSUE TITLE
Andamento tamponi Lazio bizzarro

### ISSUE THREAD

**Issue by valemercurii** [pcm-dpc/COVID-19#344]
**Tipo di richiesta**: richiesta di informazione

## Riassunto

Andando a calcolare i tamponi giornalieri della regione Lazio (tamponi_oggi - tamponi_ieri) si nota un andamento bizzarro in particolare dal 17 marzo dove si alternano giorni con migliaia di tamponi a giorni con tamponi nulli. Sarebbe interessante capire se il dato è reale o se la regione comunica il dato a giorni alterni.

## Interesse pubblico

Nel Lazio è stata dichiarata una zona rossa, Fondi, oltre ad essere la regione dello Spallanzani di Roma. E' quindi di interesse mediatico e nazionale il fatto che l'informazione dei tamponi venga fornita costantemente e sia quanto più realistica possibile.

![image](https://user-images.githubusercontent.com/22960535/77369020-dcae0680-6d5d-11ea-88d0-c025969d6caa.png)

**Comment by AlbiBone** [comment]
> se la regione comunica il dato a giorni alterni

A questo punto direi che è l'ipotesi più plausibile.

**Comment by umbros** [comment]
Se viene preso sempre il latest è impossibile che venga 0...

**Comment by valemercurii** [comment]
Perdonami @umbros ma non ti ho capito,

Sempre ammesso che la colonna tamponi sia cumulativa:

Esempio 1:
tamponi Lazio 18/03 = 1145
tamponi Lazio 19/03 = 1145
quindi, tamponi effettuati il 19/03 = 1145 - 1145 = 0

Esempio 2:
tamponi Lazio 20/03 = 13889
tamponi Lazio 21/03 = 13889
quindi, tamponi effettuati il 21/03 = 13889 - 13889 = 0
