### ISSUE TITLE
Dati statistici dettagliati per Piacenza

### ISSUE THREAD

**Issue by epode** [pcm-dpc/COVID-19#345]
È possibile avere dati più specifici per Piacenza per quanto riguarda i decessi?
Età
Dove presumibilmente hanno contratto il virus?
Dove sono deceduti?
(Ospedale o casa)
Sarebbe cosa seria avere una visione più ampia della pandemia, anche per debellare il problema!

**Comment by umbros** [comment]
Grazie @epode ma al momento non gestiamo questi dati e alcuni di essi sarebbero di difficilissimo reperimento.
