### ISSUE TITLE
numero di tamponi eseguiti o analizzati?

### ISSUE THREAD

**Issue by 2hclo2** [pcm-dpc/COVID-19#346]
**Tipo di richiesta**:  richiesta di informazione 

## Riassunto

Buongiorno, vorrei sapere se il numero dei tamponi che viene diffuso quotidianamente si riferisce al numero di tamponi effettuati oppure al numero di tamponi analizzati. mi sembra di capire che il test è molto oneroso e per avere il risultato è necessario aspettare molte ore. 
inoltre guardando i dati diffusi a livello provinciale e confrontando due giorni, si notano incrementi del numero di positivi in corrispondenza di un numero stazionario di tamponi. 

## Interesse pubblico

sarebbe molto utile chiarire questo aspetto per fornire statistiche più accurate del numero di tamponi positivi sul totale.

grazie mille
m

**Comment by umbros** [comment]
Ciao @2hclo2  totale dei tamponi eseguiti e analizzati.

tamponi | totale dei tamponi (test) effettuati, un soggetto può essere  sottoposto a più tamponi quindi non è indicativo delle persone  controllate
-- | --
