### ISSUE TITLE
I campi totale_ospedalizzati e isolamento_domiciliare sono cumulativi?

### ISSUE THREAD

**Issue by giocaputo** [pcm-dpc/COVID-19#347]
ho provato a cercare qualcosa a riguardo ma non ho trovato.

Volevo capire se i dati dei campi totale_ospedalizzati e isolamento_domiciliare sono dati giornalieri oppure cumulativi.

Grazie come sempre

**Comment by alessandroAmedei** [comment]
Basta fare il conto e vedi che sono il totale fino ad oggi. Se vuoi l'incremento giornaliero devi fare la differenza.

**Comment by nserio67** [comment]
Intende che sono gli attualmente ospedalizzati e in isolamento domiciliare o la cumulata totale fino ad oggi?

**Comment by umbros** [comment]
@giocaputo si trata di dati cumulativi

**Comment by giocaputo** [comment]
Scusa se riapro, ma se i dati sono cumulativi  come faccio a capire gli ospedalizzati e in isolamento_domiciliare attuali?

**Comment by alessandroAmedei** [comment]
@giocaputo I dati che vedi ad oggi sono i dati attuali, ovvero cumulativi! Ti indicano quante persone in Italia sono ospedalizzati e in terapia intensiva per covid19. Cosa non ti torna?

**Comment by EmilianoBruni** [comment]
In che senso cumulativi? Da quello che ho capito io sono il numero di persone che OGGI sono ricoverate e che OGGI sono in isolamento domiciliare. Tant'è che il dato scende alcuni giorni. Poi ovviamente se voglio sapere quante persone ho oggi ricoverare rispetto a ieri, sottraggo oggi-ieri.

Ho capito male?
