### ISSUE TITLE
Incongruenza dati prov Torino, 29/02...02/03

### ISSUE THREAD

**Issue by AlbiBone** [pcm-dpc/COVID-19#348]
Tipo di issue:

- [x] Dati mancanti o errati 
- [ ] Errore nella documentazione 
- [ ] Errore or mancanza nella dashboard 
- [ ] Problemi di visualizzazione nella dashboard 

- Regione: Piemonte
- Provincia: Torino

## Riassunto

Incongruenze nel numero di CasiTotali per la provincia di Torino nel periodo 29/02 ... 02/03.

**Attesa:**

Mi aspetterei un numero che continua ad accumularsi.

**Attuale:** 

Giorno 29/02, Tot_casi provincia Torino = 11
Giorno 01/03, Tot_casi provincia Torino = 49
Giorno 02/03, Tot_casi provincia Torino = 6

Come è possibile che il numero sia calato, visto che si tratta del numero totale di casi, ed è cumulavito?

**Comment by maurobarbieri** [comment]
Ho verificato lo stesso problema in varie serie di dati provinciali.
Di seguito copio il dettaglio delle date con problemi.
Propongo una spiegazione: i valori negativi potrebbero essere dovuti al fatto che alcuni dati dei contagiati siano stati rivisti a livello provinciale, perche' includessero dei casi sospetti ma non confermati, quindi eliminati dal conteggio successivo.

Formato: Provincia, data, numero cumulativo contagiati, differenza rispetto al dato cumulativo del giorno precedente

Arezzo,19/03/2020,113,-29
Bari,28/02/2020,0,-1
Benevento,11/03/2020,2,-2
Biella,09/03/2020,18,-1
Cagliari,12/03/2020,11,-4
Campobasso,18/03/2020,24,-1
Caserta,11/03/2020,26,-8
Catanzaro,11/03/2020,2,-1
Cosenza,11/03/2020,5,-1
Crotone,14/03/2020,5,-2
Enna,07/03/2020,0,-1
Firenze,27/02/2020,1,-1
Firenze,29/02/2020,5,-2
Firenze,02/03/2020,4,-1
ForliCesena,06/03/2020,3,-1
Frosinone,19/03/2020,48,-6
Gorizia,16/03/2020,16,-15
Imperia,17/03/2020,76,-2
Imperia,23/03/2020,160,-8
Matera,21/03/2020,8,-1
Monza,08/03/2020,59,-2
Napoli,04/03/2020,17,-13
Perugia,02/03/2020,1,-1
Perugia,09/03/2020,12,-3
Pistoia,26/02/2020,0,-1
Pordenone,15/03/2020,42,-3
Rieti,12/03/2020,2,-1
Roma,10/03/2020,76,-15
Rovigo,12/03/2020,13,-1
Savona,01/03/2020,19,-22
Savona,02/03/2020,16,-3
Savona,04/03/2020,19,-1
Savona,06/03/2020,15,-5
SudSardegna,15/03/2020,3,-2
Teramo,03/03/2020,3,-2
Terni,11/03/2020,18,-6
Torino,27/02/2020,2,-1
Torino,02/03/2020,6,-43
Torino,09/03/2020,87,-2
Trieste,03/03/2020,2,-7
Trieste,15/03/2020,140,-8
Udine,17/03/2020,145,-7
Verbano,09/03/2020,11,-2
Vercelli,06/03/2020,7,-1
Vercelli,09/03/2020,11,-4
Vibo,10/03/2020,1,-1
Vibo,15/03/2020,6,-11
Viterbo,12/03/2020,5,-5

**Comment by AlbiBone** [comment]
> alcuni dati dei contagiati siano stati rivisti a livello provinciale, perche' includessero dei casi sospetti ma non confermati, quindi eliminati dal conteggio successivo.

In effetti @maurobarbieri, spiegherebbe tutto la tua ipotesi, anche se personalmente avrei preferito avere dei dati certi nel conteggio dei casi, senza inserire anche i sospetti senza verificare l'effettivo contagio. Vediamo cosa rispondono le autorità a tal riguardo. Un saluto.

**Comment by umbros** [comment]
Ciao a tutti, la revisione dei dati è da considerarsi come un aggiustamento delle informazioni. Essendo in un momento di emergenza purtroppo è una cosa che può capitare.
