### ISSUE TITLE
Geo data names ISO standard

### ISSUE THREAD

**Issue by matrixxus** [pcm-dpc/COVID-19#349]
Hello,

first of all, thank you for the good work you're doing in making this data available in the public domain, despite the difficult circumstances.

I am raising this message, to see if it would be possible to add new columns (not to compromise existing usage of this data), in which the geo names and codes would comply with 
https://en.wikipedia.org/wiki/ISO_3166-2:IT
https://it.wikipedia.org/wiki/ISO_3166-2:IT

I am at the moment creating this reports for public usage: https://datastudio.google.com/reporting/2c29e71d-2c5b-4228-945e-c5dd4e09d3c2/page/PoMJB but google APIs require the iso standard for geo names, so as a workaround I am concatenating the LAT+LONG+region/province name atm which isn't the best solution.

Kind regards,

**Comment by matrixxus** [comment]
The difference between current region names vs lat+long method can be seen here:
https://datastudio.google.com/reporting/2c29e71d-2c5b-4228-945e-c5dd4e09d3c2/page/WtUJB

**Comment by pierluigicara** [comment]
First of all thanks for the encouragement. Regarding the question posed, it is worthy of attention. 
For us, however, the reference coding system will remain that of ISTAT, however we will try to relate it as shown in the wikipedia links. Stay tuned.

**Comment by matrixxus** [comment]
Thank you very much for your reply.
