### ISSUE TITLE
GeoJson Aree contenimento

### ISSUE THREAD

**Issue by piersoft** [pcm-dpc/COVID-19#35]
Per permettere interoperabilità con mappe dinamiche, è possibile avere anche il GeoJson delle aree di contenimento , tempestivamente aggiornato quando variate gli shape files?

**Comment by umbros** [comment]
ToDo

**Comment by umbros** [comment]
Done! 
https://github.com/pcm-dpc/COVID-19/tree/master/aree

**Comment by roberto-butti** [comment]
Great work @umbros !!! Thank you for your effort!

**Comment by roberto-butti** [comment]
Hi @umbros  i was parsing the geojson, 
I see all coordinates in this format : 707700.307199999690056, 5025720.619
My expectation was to have latitude and longitude in degrees format (-90 +90 and -180 + 180).

**Comment by roberto-butti** [comment]
> Hi @umbros i was parsing the geojson,
> I see all coordinates in this format : 707700.307199999690056, 5025720.619
> My expectation was to have latitude and longitude in degrees format (-90 +90 and -180 + 180).

Ok, with the latest update 9th march, everything is fine. Thank you!
