### ISSUE TITLE
Tamponi per pazienti presumibilmente guariti in isolamento domiciliare

### ISSUE THREAD

**Issue by AlbiBone** [pcm-dpc/COVID-19#350]
Vengono eseguiti i tamponi per attestare la guarigione ai pazienti in isolamento domiciliare?
In altre parole, c'è traccia in questo database (nella colonna `dimessi_guariti`), della guarigione dei pazienti in isolamento domiciliare?

**Comment by umbros** [comment]
Ciao @AlbiBone come dichiarato nel nostro wiki 👍 

tamponi | totale dei tamponi (test) effettuati, un soggetto può essere  sottoposto a più tamponi quindi non è indicativo delle persone  controllate
-- | --
