### ISSUE TITLE
Richiesta dati letalità per fasce d'età nel Veneto

### ISSUE THREAD

**Issue by alex-train** [pcm-dpc/COVID-19#351]
**Tipo di richiesta**: richiesta di dati 

**## Riassunto**
La Regione Lombardia ha avuto sinora 3776 deceduti su 28761 positivi, a fronte di 73242 tamponi fatti. Quindi il tasso di letalità è del 13,12%, rispetto il numero di positivi individuati.

Se consideriamo la Regione Veneto, 192 deceduti, su 5505 positivi individuati e 61115 tamponi effettuati, abbiamo un tasso di letalità del 3,48%. Circa un quarto!

A parte concause difficili da discriminare, il grosso problema è sul numero di tamponi effettuati. in Lombardia, hanno fatto tanti tamponi, ma non abbastanza per affermare che i contagiati siano "solo" 28 mila. Ancora, ogni 5 tamponi ci sono 2 positivi.
In Veneto, hanno fatto un numero di tamponi pari a circa 11 volte il numero di positivi individuati.

Quindi, il dato della Lombardia è statisticamente errato (ma anche per altre regioni è lo stesso) e sta falsando i risultati su tutto il territorio nazionale.

->>>Mi servono i dati della letalità nel Veneto, per fascia d'età, da applicare alla statistica delle atre regioni più colpite. <<<-

**## Interesse pubblico**

Questi dati serviranno a ricondurre il fenomeno, in un ambito statitistico più realistico e aderente ai risultati di altre regioni del mondo, vincendo panico e sgomento nella popolazione.

**Comment by umbros** [comment]
Grazie, stiamo lavorando per fornire maggiori dati e informazioni. Appena disponibili ve li comunicheremo.
