### ISSUE TITLE
orario DATI

### ISSUE THREAD

**Issue by claort** [pcm-dpc/COVID-19#352]
Buongiorno,
si riesce ad avere per una volta i dati contestualmente alla conferenza stampa ? 
vengono passati dalle regioni entro le 15 non si capisce perchè l'aggiornamento avviene sempre dopo 30 min da conferenza .
si riesce a ridurre questo tempo ? 

grazie

**Comment by AndrewDevIT** [comment]
Anche perché siti come worldometers.info ricevono subito i dati e invece qua vengono aggiornati dopo diversi minuti

**Comment by alexodus** [comment]
se i dati si danno prima della conferenza, i giornali li prenderebbero da qui e quindi la conferenza non avrebbe alcun senso.
Al massimo si può chiedere di anticipare l'orario della conferenza stampa.  Ma non credo sia possibile con un "issue" su github

**Comment by lp74** [comment]
> Buongiorno,
> si riesce ad avere per una volta i dati contestualmente alla conferenza stampa ?
> vengono passati dalle regioni entro le 15 non si capisce perchè l'aggiornamento avviene sempre dopo 30 min da conferenza .
> si riesce a ridurre questo tempo ?
> 
> grazie

Buonasera, è possibile avere i dati subito dopo la conferenza stampa?
Grazie per il servizio

**Comment by umbros** [comment]
Ciao a tutti,
per policy è stato deciso di dare i dati durante la conferenza stampa o comunque entro le 19.
