### ISSUE TITLE
dati non aggiornati in dpc-covid19-ita-andamento-nazionale-latest.cs

### ISSUE THREAD

**Issue by gsantopaolo** [pcm-dpc/COVID-19#353]
- [ ] Dati mancanti o errati dpc-covid19-ita-andamento-nazionale-latest.cs

## Riassunto

i dati nel file dpc-covid19-ita-andamento-nazionale-latest.cs ad oggi 24/3/2020 non sono aggiornati come da file https://github.com/pcm-dpc/COVID-19/blob/master/dati-andamento-nazionale/dpc-covid19-ita-andamento-nazionale.csv

sembra che il file oggi non sia stato aggiornato

![image](https://user-images.githubusercontent.com/9937149/77460517-7975b000-6e01-11ea-8ec0-d9a4bd6ebcc1.png)

**Comment by umbros** [comment]
Ciao, corretto
