### ISSUE TITLE
Dati Dimessi FVG errati

### ISSUE THREAD

**Issue by nclBaz** [pcm-dpc/COVID-19#355]
Buonasera, i dati del totale dimessi in Friuli Venezia Giulia sono nuovamente errati in quanto è un dato che deve essere cumulativo e non può decrescere. Credo che sarebbe opportuna una segnalazione a chi fornisce i dati per tale regione, in quanto come si può evincere nella rappresentazione sottostante i grafici e i dati perdono di credibilità:
[Dashboard Covid](https://dashboard.covid19med.it/?region=6)

Se invece ritenete che la dashboard indicata abbia interpretato male i dati sarebbe utile per tutti saperlo. Grazie e complimenti per il lavoro.

Tipo di issue:

- [x] Dati mancanti o errati 
- [ ] Errore nella documentazione 
- [ ] Errore or mancanza nella dashboard 
- [ ] Problemi di visualizzazione nella dashboard 

- Regione: FVG

**Attesa:**

Ci si aspetta che il numero dimessi_guariti sia uguale o maggiore al giorno precedente

**Attuale:** 

```javascript
    {
        "data": "2020-03-24 17:00:00",
        "stato": "ITA",
        "codice_regione": 6,
        "denominazione_regione": "Friuli Venezia Giulia",
        "dimessi_guariti": 80, <-- numero inferiore al giorno precedente
    }
```

**Comment by umbros** [comment]
@nclBaz, è possibile che un soggetto definito guarito ma in successivi controlli non è completamente guarito o semplice errore materiale
