### ISSUE TITLE
Problema nei campi della tabella delle regioni

### ISSUE THREAD

**Issue by mzanrosso** [pcm-dpc/COVID-19#356]
Avete inserito un campo long che nella maggior parte dei db indica una tipologia di dato e rende così impossibile il parsing veloce

**Comment by umbros** [comment]
@mzanrosso è semplicemente una label non so che db utilizzi ma se possiamo aiutarti volentieri...

**Comment by mzanrosso** [comment]
Si lo so che è una label ma se riusciste a modificare “long” in qualcos’altro sarebbe fantastico

**Comment by mzanrosso** [comment]
È possibile sapere quando la modifica sarà effettuata?

**Comment by umbros** [comment]
modifica effettuata
