### ISSUE TITLE
Request for clarity on new data tomorrow

### ISSUE THREAD

**Issue by cdolan-coatue** [pcm-dpc/COVID-19#357]
**Type of issue**: Request for information

## Summary

Thank you for providing information that `3. sarà realizzato un nuovo dataset per fornire informazioni sui dati /  a new dataset will be released to give informations on data`. Based on this description I am unclear on what this data is and am hoping you can provide more information and ideally a schema for the data. 

## Public interest

This data is very helpful and valuable. We appreciate your efforts to provide this data. This request would help allow us and other to ingest this data faster. 

Ciao

**Comment by umbros** [comment]
Hi,
today wi well add 2 new information: note_it and note_en and we will change the date format from yyyy-mm-dd hh:mm:ss to yyyy-mm-ddThh:mm:ss

**Comment by alessandroAmedei** [comment]
Will you change the dateformat of every field in the repository or just of the new ones?

**Comment by umbros** [comment]
Every field

**Comment by umbros** [comment]
Examples:

**dati_regioni**
data,stato,codice_regione,denominazione_regione,lat,long,ricoverati_con_sintomi,terapia_intensiva,totale_ospedalizzati,isolamento_domiciliare,totale_attualmente_positivi,nuovi_attualmente_positivi,dimessi_guariti,deceduti,totale_casi,tamponi,note_it,note_en
2020-03-24T17:00:00,ITA,13,Abruzzo,42.35122196,13.39843823,234,57,291,331,622,17,21,46,689,4294,,

**dati_province**
data,stato,codice_regione,denominazione_regione,codice_provincia,denominazione_provincia,sigla_provincia,lat,long,totale_casi,note_it,note_en
2020-03-24T17:00:00,ITA,13,Abruzzo,069,Chieti,CH,42.35103167,14.16754574,133,,

**dati_andamento_nazionale**
data,stato,ricoverati_con_sintomi,terapia_intensiva,totale_ospedalizzati,isolamento_domiciliare,totale_attualmente_positivi,nuovi_attualmente_positivi,dimessi_guariti,deceduti,totale_casi,tamponi,note_it,note_en
2020-03-24T17:00:00,ITA,21937,3396,25333,28697,54030,3612,8326,6820,69176,296964,,

**Comment by cdolan-coatue** [comment]
@umbros Thank you for this
