### ISSUE TITLE
ospedalizzati e isolamento domiciliare attuali

### ISSUE THREAD

**Issue by giocaputo** [pcm-dpc/COVID-19#359]
Riguardo la issue https://github.com/pcm-dpc/COVID-19/issues/347

Scusa se riapro, 
volevo capire se i dati sono cumulativi come faccio a capire gli ospedalizzati e in isolamento_domiciliare attuali?

**Comment by alessandroAmedei** [comment]
@giocaputo I dati che vedi ad oggi sono i dati attuali, ovvero cumulativi! Ti indicano quante persone in Italia sono ospedalizzati e in terapia intensiva per covid19. Cosa non ti torna?

**Comment by EmilianoBruni** [comment]
Quello che ho capito è che quei numeri sono il numero di persone che OGGI sono ricoverate e che OGGI sono in isolamento domiciliare. Tant'è che il dato scende alcuni giorni. Poi ovviamente se voglio sapere quante persone ho oggi ricoverare rispetto a ieri, sottraggo oggi-ieri.

Ho capito male?

**Comment by giocaputo** [comment]
La domanda è : il numero di quei due campi, sono cumulativi, quindi dall'inizio dall'epidemia?
La risposta alla domanda era cumulativi, se non ho capito male.
Ma quindi quali sono quelli che effettivamente oggi sono in isolamento domiciliare / ospedalizzati.

**Comment by EmilianoBruni** [comment]
Secondo me no, varie regioni hanno, in alcuni giorni valori minori rispetto a giorni precedenti. Questi per esempio sono rispettivamente Abruzzo e Marche. 

![abruzzo ricoverati](https://user-images.githubusercontent.com/8313282/77572729-c758e980-6ecf-11ea-9f8d-f54dd210e107.png)
![marche ricoverati](https://user-images.githubusercontent.com/8313282/77572737-cb850700-6ecf-11ea-8bc1-89efa8b5faf3.png)

**Comment by duckyb** [comment]
> @giocaputo 
> come faccio a capire gli ospedalizzati e in isolamento_domiciliare attuali?

ospedalizzati_attuali = (ospedalizzati - dimessi_guariti - deceduti)

Per quanto riguarda isolamento domiciliare attuale la vedo dura

**Comment by giocaputo** [comment]
@umbros ci aiuti ? Grazie TANTE come sempre

**Comment by giocaputo** [comment]
Quello che vorrei capire anche è come far a capire quanti oggi sono entrati in terapia intensiva? La differenza tra ieri e oggi è negativa. Grazie

**Comment by EmilianoBruni** [comment]
> 
> 
> Quello che vorrei capire anche è come far a capire quanti oggi sono entrati in terapia intensiva? La differenza tra ieri e oggi è negativa. Grazie

Quindi vuole dire che alcune tra sono uscite dall'ICU più pazienti di quanti sono stati ricoverati nel reparto. Se nessuno è stato ricoverato in ICU, vuole dire quel quel numero negativo che vedi è il numero di pazienti dimesso dalla ICU.
