### ISSUE TITLE
Progressivo Regioni e Province

### ISSUE THREAD

**Issue by piersoft** [pcm-dpc/COVID-19#36]
Insieme all'andamento sarebbe molto utile avere il progressivo (ultima rilevazione) per le province e regioni.

grazie

**Comment by umbros** [comment]
Ciao @piersoft , il progressivo è per data, ogni nome file ha un formato dpc-covid19-xxxx-yyymmdd.csv, all'interno del file unico il progressivo è dato dalla data.
