### ISSUE TITLE
Contagi con patologie, decessi con patologie

### ISSUE THREAD

**Issue by marcodo1976** [pcm-dpc/COVID-19#360]
**Tipo di richiesta**: richiesta di dati

## Riassunto
Introdurre metriche
- casi con almeno 2 patologie
- decessi con almeno 2 patologie

## Interesse pubblico
Al momento sappiamo genericamente che la letalità aumenta con età e presenza patologie pregresse. Ma queste due variabili sono tra loro correlate positivamente. Poter discriminare tra chi ha patologie e chi non le ha, sarebbe utile per capire quale delle due variabili impatta maggiormente sulla letalità.

**Comment by umbros** [comment]
I dati delle patologie sono elaborati da ISS
