### ISSUE TITLE
Question about "Tamponi" column

### ISSUE THREAD

**Issue by rladeira** [pcm-dpc/COVID-19#361]
The description for "tamponi" column says it's the amount of tests performed. Given that, which of the following option is the right one?

1) the amount of tests performed, whose results were already disclosed. In this scenario, all positive tests would already be adding to the positive counts, with no additional results to be disclosed in the next day.
2) the amount of tests performed, but not necessarily with the most recent ones disclosed, since it takes 24h to have the final result. In this scenario, some results would be added to positive counts in the next day.

**Comment by floatingpurr** [comment]
I take advantage of this issue to add another related question. 

Are data about tests (aka tamponi) describing: 
1. **the raw number of performed tests** (and so we have to take into account that the same person could be tested more than once) 
2. or **the amount of people tested** at least once? 

It's not clear to me if the relation between tests and people is a many-to-one (i.e., case 1) or a one-to-one (i.e., case 2).

Thanks

**Comment by floatingpurr** [comment]
> I take advantage of this issue to add another related question.
> 
> Are data about tests (aka tamponi) describing:
> 
> 1. **the raw number of performed tests** (and so we have to take into account that the same person could be tested more than once)
> 2. or **the amount of people tested** at least once?
> 
> It's not clear to me if the relation between tests and people is a many-to-one (i.e., case 1) or a one-to-one (i.e., case 2).
> 
> Thanks

Whoops, the answer to my question is here #350.

**Comment by umbros** [comment]
:) It's ok @floatingpurr #350

**Comment by rladeira** [comment]
@umbros, It is not clear for me. Is it option 1 or 2?

**Comment by whitesnakeftw** [comment]
@rladeira Option 1.

**Comment by rladeira** [comment]
Thanks!
