### ISSUE TITLE
tabella dati disponibili

### ISSUE THREAD

**Issue by rtrunfio** [pcm-dpc/COVID-19#362]
**Tipo di richiesta**:  richiesta di dati
Dalla sezione download della pagina riepilogativa della P.C. è possibile recuperare in formato .csv i dati giornalieri aggiornati, rispettivamente di  Regioni - Province - Andamento nazionale.

Mentre per regioni e nazionale sono presenti numerosi campi dove sono accorpati i dati, dai ricoverati con sintomi a quelli in rianimazione, dai deceduti fino ai tamponi effettuati ecc., per quanto riguarda i dati provinciali i file riportano soltanto il campo "totale casi".

Vorrei poter conoscere e recuperare i dati relativi, ad esempio, ai deceduti o i tamponi effettuati, suddivisi per le singole province, visto che questi dati, poi cumulati, dovrebbero andare costituire la base per i dati regionali e nazionali riportati. 
Sono disponibili tabelle relative a questi dati ?
Grazie.
 
Scrivi qui il riassunto della richiesta.
-->richiesta dati scorporati per provincia relativi ai decessi

**Comment by umbros** [comment]
Ciao @rtrunfio stiamo lavorando su questo fronte. Comunicheremo tutto appena possibile.

**Comment by rtrunfio** [comment]
ciao Umberto. Grazie.

Il Mer 25 Mar 2020, 19:50 Umberto Rosini <notifications@github.com> ha
scritto:
