### ISSUE TITLE
Change of end of line delimiter from \n to \r

### ISSUE THREAD

**Issue by Kurtpenter** [pcm-dpc/COVID-19#364]
Type of issue:
- [X] Incorrect or missing data : dati-andamento-nazionale/dpc-covid19-ita-andamento-nazionale.csv

## Summary

Change of end of line delimiter from \n to \r.

Was it done on purpose? It may break automation of consumers of this file.

**Expected:**
data,stato,ricoverati_con_sintomi,terapia_intensiva,totale_ospedalizzati,isolamento_domiciliare,totale_attualmente_positivi,nuovi_attualmente_positivi,dimessi_guariti,deceduti,totale_casi,tamponi,note_it,note_en\n

**Actual:**
data,stato,ricoverati_con_sintomi,terapia_intensiva,totale_ospedalizzati,isolamento_domiciliare,totale_attualmente_positivi,nuovi_attualmente_positivi,dimessi_guariti,deceduti,totale_casi,tamponi,note_it,note_en\r

**Comment by umbros** [comment]
Solved all file UTF-8 CRLF
