### ISSUE TITLE
Rispondete adeguatamente alle domande in conferenza stampa

### ISSUE THREAD

**Issue by FedericoStra** [pcm-dpc/COVID-19#365]
Scrivo qua perché l'ufficio stampa non risponde. 

# Rispondete adeguatamente alle domande dei giornalisti in conferenza stampa

Alla conferenza stampa di oggi, 25 marzo, ([link](https://youtu.be/a5r-XsD0KMw?t=1140) su YouTube) un giornalista chiede:

> I nuovi tamponi positivi, cioè i nuovi diagnosticati positivi al COVID, sono da cercare facendo una sottrazione sulla "colonna arancione", cioè del totale positivi? (Si riferisce alla colonna in [questo file](https://github.com/pcm-dpc/COVID-19/blob/master/schede-riepilogative/regioni/dpc-covid19-ita-scheda-regioni-20200325.pdf))
>
> Perché di solito ci date il dato degli attualmente contagiati?
>
> Questo ha creato un po' di spaesamento perché ieri uno cresceva rispetto al giorno prima e l'altro diminuiva rispetto al giorno prima.

La risposta data dal tizio che non si è neanche presentato è stata un ingarbugliamento di parole che girava su se stesso senza arrivare a comunicare niente. Mi meraviglio che il giornalista non abbia reiterato la domanda a cui non era stata data risposta. Una risposta adeguata necessitava chiaramente di una spiegazione di cosa sono i "nuovi attualmente positivi" e cosa sono i "nuovi contagi", unita a delle spiegazioni su perché un numero può essere più interessante o utile dell'altro. Un conto è non fornire il numero di nuovi contagi di propria sponte, un altro è blaterare un po' di parole per non rispondere una domanda diretta di un giornalista.

Per inciso, i numeri di oggi sono:
- incremento delle persone positive: +3491;
- nuovi contagi: 5210.

## Interesse pubblico

Ovvio. Qualità dell'informazione e trasparenza con i cittadini.

**Comment by umbros** [comment]
@FedericoStra ti rimando alla netiquette (CODE_OF_CONDUCT) definita per il repository. Qui non si accusa, qui si suggerisce e collabora.

**Comment by FedericoStra** [comment]
@umbros Mi pare che non ci sia nessuna accusa nel mio commento precedente. "Rispondete alle domande" è un suggerimento. Ovviamente non è un suggerimento per i mantainers del repository: è un suggerimento per l'ufficio stampa. Inoltrate internamente il messaggio a chi di dovere.
