### ISSUE TITLE
Codice Avvisi

### ISSUE THREAD

**Issue by francescovallone** [pcm-dpc/COVID-19#366]
**Tipo di richiesta**:  richiesta di informazione
## Riassunto
Salve ho notato che su readme il codice avvisi viene scritto nel formato Adnp-IT-ID ma sul file avvisi.json risulta essere apd-IT-ID c'è una differenza tra i due dati?

**Comment by umbros** [comment]
No francesco, abbiamo definito meglio il naming e nella giornata di domani lo metteremo nel readme e nel wiki, stiamo referenziato gli avvisi passati e entro le 19:30 saranno tutti definiti.
