### ISSUE TITLE
DATI SICILIA RICOVERATI E ISOL. DOMICILIARE

### ISSUE THREAD

**Issue by claort** [pcm-dpc/COVID-19#368]
è STATA ELIMINATA ISSUE 367 
ECCO DI SEGUITO I DATI RICHIESTI

dai csv:

2020-03-23T17:00:00 | ITA | 19 | Sicilia | 38.11569725 | 13.3623567 | 250 | 60 | 310 | 371 | 681
è corretto (e anche la somma 681 torna) 

2020-03-24T17:00:00 | ITA | 19 | Sicilia | 38.11569725 | 13.3623567 | 250 | 60 | 310 | 489 | 799
NON sembra corretto (vedi correzione)                                             270   67   337   462  799

2020-03-25T17:00:00 | ITA | 19 | Sicilia | 38.11569725 | 13.3623567 | 259 | 80 | 339 | 597 | 936 | 
NON sembra corretto (vedi correzione)                                             319   ok   399   537 ok 

i dati di cui sopra da me indicati come correzioni corrispondono a quanto pubblicato anche dalla regione

**Comment by umbros** [comment]
Ah ma li stai mettendo il relazione ai dati che da Regione Sicilia?

**Comment by claort** [comment]
tutti gli altri giorni erano corrispondenti
ma in ogni caso non torna la somma del giorno 24. 
Perchè secondo i CSV il numero dei ricoverati e della terapia intensitva è uguale a quello del giorno prima e non è corretto . vi torna ?

**Comment by claort** [comment]
i dati inviati comunque li ho presi in automatico i giorni scorsi dal file json in rete 
ecco il mio sito http://www.claudioortega.it/brief/covid.php 
è connesso direttamente ai json pubblicati

**Comment by umbros** [comment]
@claort non so che dirti mi spiace comunque mi sembra che ora siano ok, complimenti per il tuo lavoro... e siamo a disposizione se vuoi segnalarci altro.
