### ISSUE TITLE
Roma - discrepanza nuovi casi con i dati pubblicati dalla regione Lazio

### ISSUE THREAD

**Issue by marcomoauro** [pcm-dpc/COVID-19#369]
Tipo di issue:

- [x] Dati mancanti o errati 
- [ ] Errore nella documentazione 
- [ ] Errore or mancanza nella dashboard 
- [ ] Problemi di visualizzazione nella dashboard 

La regione Lazio pubblica ogni giorno i dati dei nuovi contagiati del Lazio con granularità a livello di provincia. Il fatto è che confrontando questi valori con quelli che sono presenti in questo dataset il numero totale dei casi è corretta, ma risulta errato a livello provinciale.
Dai vostri file otteniamo che i nuovi contagi (totale di oggi - ieri) risulta per le province:
Roma       = 1428 - 1287 = 141
Frosinone = 106 - 97 = 9
Rieti          = 39 - 33 = 6
Latina       = 198 - 182 = 16
Viterbo     = 122 - 121 = 1

Mentre la regione ha pubblicato questi dati:
Roma       = 114
Frosinone = 26
Rieti          = 5
Latina       = 11
Viterbo     = 17

Fonti:
https://user-images.githubusercontent.com/27300747/77575765-4fd98900-6ed4-11ea-9691-0a696b70c1fc.jpg
https://user-images.githubusercontent.com/27300747/77575770-51a34c80-6ed4-11ea-9d3d-ab631ca6d166.jpg
https://user-images.githubusercontent.com/27300747/77575761-4e0fc580-6ed4-11ea-846d-91b4d24e4401.jpg
https://user-images.githubusercontent.com/27300747/77575692-36d0d800-6ed4-11ea-96db-af678fae3c9a.jpg
https://user-images.githubusercontent.com/27300747/77575756-4c460200-6ed4-11ea-8181-0e8a5c01a08b.jpg

## Riassunto
discrepanza tra i nuovi casi pubblicati in questo dataset rispetto a quelli pubblicati dalla regione

**Comment by umbros** [comment]
Ciao @marcomoauro i dati sono comunicati da Regione Lazio per il tramite del Ministero della Salute, a colpo d'occhio non mi sembrano dei totali ma incrementali; ad ogni modo verificheremo. grazie
