### ISSUE TITLE
Andamenti Regionali e provinciali

### ISSUE THREAD

**Issue by danielamazza** [pcm-dpc/COVID-19#37]
Visto che i dati ci sono, la butto lì: sarebbe bello far sì che quando si clicca su una regione o una provincia, venissero visualizzati sulla destra i grafici degli  andamenti e dell'incremento giornaliero di di quella regione o provincia (non solo nazionale).  
Inoltre i grafici potrebbero riferirsi anche agli altri dati: 
- ricoverati con sintomi
- terapia intensiva
- totale ospedalizzati
ecc. 
Mi riferisco alla tabella: https://github.com/pcm-dpc/COVID-19/blob/master/dati-regioni/dpc-covid19-ita-master.xlsx 
Non abbiamo questi dati anche per provincia?
Grazie a tutti, state facendo un bellissimo lavoro!

**Comment by doppioandante** [comment]
Per vedere gli andamenti regionali dei positivi mi sono fatto questo: https://enrico.acqua.team/covid-19/

**Comment by giocaputo** [comment]
Ho creato dei grafici dove poter visualizzare alcuni dati riguardanti il
Corina Virus. COVID-19

https://public.tableau.com/profile/giovanni.caputo#!/vizhome/COVID-19_15836095988890/NewDashboard?publish=yes


Giovanni Caputo

Il giorno dom 8 mar 2020 alle ore 17:33 Enrico Lumetti <
notifications@github.com> ha scritto:

**Comment by umbros** [comment]
@danielamazza allo stato attuale non gestiamo questi dati.
Grazie a tutti per la collaborazione.

**Comment by pensierinmusica** [comment]
https://github.com/pcm-dpc/COVID-19/issues/245
