### ISSUE TITLE
Errore Tamponi Lombardia in dpc-covid19-ita-regioni.csv

### ISSUE THREAD

**Issue by leotuni** [pcm-dpc/COVID-19#370]
Tipo di issue:

- Dati mancanti o errati  dpc-covid19-ita-regioni.csv

- Regione: Lombardia

## Riassunto
Numero totale tamponi regione lombardia sale e poi scende tra il 2020-02-25T e 2020-02-26T

data | denominazione_regione | tamponi
-- | -- | --
2020-02-24T18:00:00 | Lombardia | 1463
2020-02-25T18:00:00 | Lombardia | **3700** 
2020-02-26T18:00:00 | Lombardia | 3208

Visto che è il numero totale è impossible.

**Comment by umbros** [comment]
Possibile un ricalcolo, se la Regione ci notifica che ci sono problemi sui dati lo scriviamo in note
