### ISSUE TITLE
Udine in  probabile errore 17/3

### ISSUE THREAD

**Issue by furiop** [pcm-dpc/COVID-19#372]
Tipo di issue:

- [x] Dati mancanti o errati dpc-covid19-ita-province-20200317.csv
- Regione: Friuli Venezia Giulia 
- Provincia: Udine

## Riassunto

Il numero 145 relativo a Udine è inconsistente rispetto ai dati precedentie successivi:

129, 153, * 145 *, 181, 266

Grazie e mi scuso per il disturbo.
Grazie per l'ottimo lavoro.
Furio Petrossi

**Comment by duckyb** [comment]
Duplicato di #358

**Comment by umbros** [comment]
#358
