### ISSUE TITLE
dati-comune

### ISSUE THREAD

**Issue by sinanatra** [pcm-dpc/COVID-19#373]
È possibile avere un dataset su scala comunale  per un maggiore zoom del contagio?

**Comment by duckyb** [comment]
Vedi #61 e #191

**Comment by mottolini** [comment]
Una risposta, quasi definitiva, è stata data qui: https://github.com/pcm-dpc/COVID-19/issues/606
Sto cercando quindi di capire a chi andare a bussare adesso

**Comment by umbros** [comment]
i dati comunali non sono gestiti da questo repository. ISS li mostra sulle proprie dashboard.
