### ISSUE TITLE
data type and consolidation

### ISSUE THREAD

**Issue by piedea** [pcm-dpc/COVID-19#374]
This is a new issue of the same title. Hopefully I will be more clear about the need or I will receive better instruction for download.

In order to follow with prediction analysts, it’s necessary to have **ALL** the data available, on a national basis, consolidated in one large excel table csv format and international numeric format.
I mean in a single file updated every day: single city, province, region, national, gender, age... everythink in a single file for all the data since the day 1 of the infection !

Not single small aumont of data relate to a single day.

Most likely will be an important work of modeling and table population.
I’m imaging a large and strait forward simple table containing all the data published in Italy since the raising of the infection.

I looking forward to ear from you.

Thank you

**Comment by piedea** [comment]
Sorry but, even if many persons says that the file a need as mentioned is already in the repository I can't be able to find it.
I repeat it only one file all the informations at the maximum level of detail.
Thank you

**Comment by kidpixo** [comment]
You are using the `latest` version of each dataset, check : 

* [COVID-19/dpc-covid19-ita-andamento-nazionale.csv at master · pcm-dpc/COVID-19](https://github.com/pcm-dpc/COVID-19/blob/master/dati-andamento-nazionale/dpc-covid19-ita-andamento-nazionale.csv)
* [COVID-19/dpc-covid19-ita-regioni.csv at master · pcm-dpc/COVID-19](https://github.com/pcm-dpc/COVID-19/blob/master/dati-regioni/dpc-covid19-ita-regioni.csv)
* [COVID-19/dpc-covid19-ita-province.csv at master · pcm-dpc/COVID-19](https://github.com/pcm-dpc/COVID-19/blob/master/dati-province/dpc-covid19-ita-province.csv)

**Comment by umbros** [comment]
Ok
