### ISSUE TITLE
Dati tamponi inconsistenti per regione FVG

### ISSUE THREAD

**Issue by GabryB** [pcm-dpc/COVID-19#375]
Tipo di issue:

- [x] Dati mancanti o errati 
- [ ] Errore nella documentazione 
- [ ] Errore or mancanza nella dashboard 
- [ ] Problemi di visualizzazione nella dashboard 

- Regione: Friuli Venezia Giulia
- Provincia: 

## Riassunto

Nelle tabelle delle regioni [](https://github.com/pcm-dpc/COVID-19/tree/master/dati-regioni) il numero di tamponi per il Friuli Venezia Giula del 19/3 è inferiore a quelli del 17/3 e del 18/3

17/3 4958 tamponi

18/3 4958 tamponi

19/3 4052 tamponi

**Attesa:**

**Attuale:**

**Comment by umbros** [comment]
Eventuali comunicazioni di inconsistenza o problemi sui dati comunicate dalle Regioni sono riepilogate in note (italiano e inglese)
