### ISSUE TITLE
Dati incoerenti 'dimessi_guariti' per regione FVG

### ISSUE THREAD

**Issue by GT-Rex** [pcm-dpc/COVID-19#376]
Tipo di issue:

- [x] Dati mancanti o errati <dpc-covid19-ita-regioni.csv>

- Regione:Friuli  Venezia Giulia
- Provincia: 

## Riassunto

Nelle tabelle delle regioni il numero ''dimessi_guariti ''per il Friuli Venezia Giula del 24/3 è inferiore a quelli del 23/3 

data    dimessi_guariti
23/3       105
24/3        80     !
25/3       158
anche precedentemente ....
data    dimessi_guariti
16/3       18
17/3       17    !
18/3       15     !
19/3       41

**Comment by umbros** [comment]
Eventuali comunicazioni di inconsistenza o problemi sui dati comunicate dalle Regioni sono riepilogate in note (italiano e inglese)
