### ISSUE TITLE
Guariti comprende anche quelli da isolamento domiciliare?

### ISSUE THREAD

**Issue by pierpa010** [pcm-dpc/COVID-19#377]
il dato è relativo solo a chi è stato ospedalizzato? se si perchè non è specificato nel read me?
si può avere una conferma ufficiale?

Grazie

**Comment by injarn** [comment]
Palesemente se viene riscontrato un caso positivo che non necessita di cure ospedaliere ma solo di isolamento domiciliare, una volta guarito viene censito. In caso di positività la quarantena è obbligatoria e si viene sorvegliati, quindi, tamponati per evidenziare eventuale negatività dopo un certo arco di tempo.

**Comment by pierpa010** [comment]
non è così palese, fai una ricerca nelle issue chiuse..

**Comment by umbros** [comment]
Messa nota esplicativa nella specifica dei dati
