### ISSUE TITLE
Dati apparentemente inconsistenti

### ISSUE THREAD

**Issue by mrai5011** [pcm-dpc/COVID-19#38]
Ci sono 18 casi in cui il totale_casi diminuisce da un giorno al successivo. E.g. Savona il 29FEB20 - 49 casi, il 01MAR20 -19 casi.
[province-err.pdf](https://github.com/pcm-dpc/COVID-19/files/4303468/province-err.pdf)

**Comment by umbros** [comment]
Ciao mrai, si questo è normale perchè può esserci movimento all'interno delle province o riallocazioni. Per i nuovi casi o variazioni puoi far riferimento a quelle per Regioni e andamento.
