### ISSUE TITLE
aggiornare classificazione numerica e relativa legenda 

### ISSUE THREAD

**Issue by groundrace** [pcm-dpc/COVID-19#380]
## Problemi di visualizzazione nella dashboard

L'attuale ripartizione del numero di contagi non pare adeguata ai numeri dei casi attualmente presenti nella dashboard
![image](https://user-images.githubusercontent.com/3225570/77677604-38f86c80-6f90-11ea-9931-dc76762917c4.png).
Ad esempio nonostante le differenze quasi tutte le province risultano uguali come ampiezza del cerchio:
![image](https://user-images.githubusercontent.com/3225570/77677747-69d8a180-6f90-11ea-9c6b-02a1c5afd2ca.png)

Suggerisco una revisione della classificazione, magari usando un normale natural breaks

**Comment by umbros** [comment]
Grazie della segnalazione @groundrace, modifica effettuata.
