### ISSUE TITLE
Morti per Regione Errati/Mancanti e Dimessi/Guariti 

### ISSUE THREAD

**Issue by mariadellarovere** [pcm-dpc/COVID-19#381]
Tipo di issue:

- [x] Dati mancanti o errati 
- [x] Errore nella documentazione 
- [ ] Errore or mancanza nella dashboard 
- [ ] Problemi di visualizzazione nella dashboard 

- Regione: PIEMONTE
- Provincia: 

## Riassunto

Ciao nel report regione per regione i MORTI IN PIEMONTE SONO 449, Esattamente come ieri 25/03. Inoltre i DIMESSI GUARITI sono passati da 19 il 25/03 a 135 il 26/03. Una crescita molto strana.

**Attesa:**

**Attuale:**

**Comment by umbros** [comment]
Ciao, confermo che è il dato pervenuto.

**Comment by mariadellarovere** [comment]
@umbros al TG hanno parlato di circa 100 morti in più.
