### ISSUE TITLE
Dati provinciali incompleti

### ISSUE THREAD

**Issue by gaedol** [pcm-dpc/COVID-19#383]
Tipo di issue:

- [X] Dati mancanti o errati 
- [ ] Errore nella documentazione 
- [ ] Errore or mancanza nella dashboard 
- [ ] Problemi di visualizzazione nella dashboard 

- Regione: Non di interesse
- Provincia: Tutte

## Riassunto

I dati provinciali mancano di ogni informazione eccetto il numero totale di casi. Sarebbe invece utile avere i dati anche di casi attivi, deceduti, in isolamento a casa, ospedalizzati, in terapia intensiva.

**Comment by umbros** [comment]
@gaedol ci sono altre risposte in merito, per ora gestiamo questi ma stiamo lavorando per ampliare la base dati.
