### ISSUE TITLE
Encoding CSV del 2020-03-26

### ISSUE THREAD

**Issue by leoniDEV** [pcm-dpc/COVID-19#384]
Tipo di issue:

- [ ] Dati mancanti o errati 
- [x] Errore nella documentazione 
- [ ] Errore or mancanza nella dashboard 
- [ ] Problemi di visualizzazione nella dashboard 

## Riassunto

L'encoding del file [dpc-covid19-ita-province-20200326.csv](https://github.com/pcm-dpc/COVID-19/blob/master/dati-province/dpc-covid19-ita-province-20200326.csv)
sembra essere ANSI invece che UTF-8
**Attesa:**
character encoding UTF-8 (come gli altri precedenti)

**Attuale:** 
character encoding ANSI

**Comment by umbros** [comment]
Grazie  @leoniDEV , corretto
