### ISSUE TITLE
Dati non idonei

### ISSUE THREAD

**Issue by mazinthebox** [pcm-dpc/COVID-19#386]
Tipo di issue:

- [X ] Dati mancanti o errati nel file [ita-note-it-json](https://github.com/pcm-dpc/COVID-19/blob/master/dati-json/dpc-covid19-ita-note-it.json)

- Provincia: Lombardia

## Riassunto
Nelle prime 3 note la chiave **note** ha un valore non idoneo

**Attesa:**
VIsto che il file è quello Italiano, dovrebbe esserci scritto il campo note in Italiano

**Attuale:**
Il campo note presenta la dicitura in inglese

**Comment by umbros** [comment]
Ciao @mazinthebox stiamo modificando il wiki e sarà poi esplicita l'informazione, il codice nota dipende se è dato parziale (pd) o dato non comunicato (nd)
