### ISSUE TITLE
Piemonte's deceduti error

### ISSUE THREAD

**Issue by pnicorelli** [pcm-dpc/COVID-19#387]
Type of issue:

- [x] Incorrect or missing data : 
- [ ] Incorrect or missing documentation 
- [ ] Incorrect or missing data in the dashboard 
- [ ] Layout problem in the dashboard 

- Region: Piemonte
- Date: 26/03/2020
## Summary

According to https://www.regione.piemonte.it/web/pinforma/notizie/coronavirus-gli-aggiornamenti-dalla-regione-piemonte on file https://github.com/pcm-dpc/COVID-19/blob/master/dati-regioni/dpc-covid19-ita-regioni.csv row 665, field "deceduti" should be 545

**Actual:**

Actual is 449 (same of yesterday )

**Comment by umbros** [comment]
Ciao @pnicorelli è arrivato il dato in ritardo e stiamo procedendo alla correzione.

**Comment by pnicorelli** [comment]
@umbros per evenienze simili preferite una issue o una PR? Oppure è solo rumore per voi? giusto per capire.
