### ISSUE TITLE
Totale Tamponi comprende anche i 2 test per dichiarare la guarigione ?

### ISSUE THREAD

**Issue by lukwe** [pcm-dpc/COVID-19#388]
**Tipo di richiesta**:  richiesta di informazione 

## Riassunto

Come da subject: il Totale tamponi è relativo solo al monitoraggio di nuovi casi o vengono conteggiati anche i 2 tamponi effettuati per dimissione di pazienti guariti !?

## Interesse pubblico

Chiarimento metodologico generale, che permette la corretta interpretazione dei dati.

**Comment by floatingpurr** [comment]
Direi di sì. Da' un'occhiata qui #350

**Comment by lukwe** [comment]
Ok, chiuso issue !

..quindi il gran parlare su plot 'nuovi_positivi/numero_tamponi / day' andrebbe riazzerato alla luce di questo fattore. 

Il numero reale di test giornalieri effettuati per individuare nuovi casi è: 

`Totale tamponi -2*guariti_dimessi`

**Comment by luca-conterio** [comment]
Immagino che i tamponi vengano effettuati periodicamente sui pazienti, quindi probabilmente non è neanche così semplice... magari in un giorno molti tamponi sono effettuati su pazienti che continuano a presentare i sintomi, non credo basti sottrate 2*guariti_dimessi (sarebbe come sottrarre solo gli ultimi due tamponi effettuati ad un paziente)

**Comment by lukwe** [comment]
ok certo, credo faccian di tutto per non sprecare reagenti e tempo ma può essere anche questo. 

Quindi sul piano formale possiam solo dire che il fattore correttivo da sottrarre sarebbe  2*numero_guariti  + K*numero_ricoverati  (K impossibile da stimare, dipende da policy locali ospedale per ospedale)

**Comment by floatingpurr** [comment]
Non so si può davvero inferire il numero di persone testate stimando un fattore correttivo sistematico. 

Per esempio, credo che una persona, anche se negativa ad un primo tampone, potrebbe doverne farne altri. Oppure una persona guarita, prima di essere riconosciuta tale dai 2 tamponi negativi, ne potrebbe aver già fatti `n` negativi.

_Just my 2 cents_
