### ISSUE TITLE
Cambio della datazione dei positivi per decorrelarli dal trend dei tamponi

### ISSUE THREAD

**Issue by algebrato** [pcm-dpc/COVID-19#389]
**Tipo di richiesta**:  Suggerisco di migliorare la datazione del numero di positivi per decorrelarli dal trend del numero di tamponi e dal ritardo del loro processamento da parte dei laboratori di analisi. 

## Riassunto

Organizzare i dati dei totali_casi non in funzione della data dell'esito dei tamponi, ma in funzione alla data del *prelievo*.

## Interesse pubblico

Attualmente la curva del contagio che risulta dai campi `positivi` e `totale_casi` ha un forte bias dovuto principalmente a due fattori:

1. Il ritardo fisiologico dei laboratori nel fornire il referto del tampone
2. Il numero di tamponi

Dato che il numero di tamponi e' una grandezza conosciuta, l'idea che vi propongo e' quella di poter organizzare i dati in funzione alla data del *prelievo* e non alla data del rilascio del referto.
Se i vari laboratori, per esempio nella giornata di oggi, al posto di fornire solo un "brutale" numero di positivi vi associassero anche la data del prelievo riferito a quel preciso tampone, si capirebbe meglio come distribuire eventuali picchi di positivita` che capitano ogni tanto nei dati.

In questo modo avremmo una curva dei contagi che sara' sempre di almeno una settimana indietro rispetto al tempo locale ma, in modo incrementale diventa statisticamente piu' rilevante. 

Il trend del numero dei tamponi, ovviamente si mitiga anche se non scompare del tutto, mentre con l'andare del tempo le fluttuazioni dovute ai tempi di processamento da parte dei laboratori di analisi dovrebbero diventare del tutto trascurabili.

Alla fine basterebbe che i laboratori, al posto di comunicare: "ci sono stati `N` postivi", dica una cosa tipo:" `n` positivi il 20 marzo, `m` positivi il 21 e `p` positivi il 22, dove `n` + `m` + `p` = `N`  " .... in questo modo si evita il picco di `N` positivi in un solo giorno. Si ha una curva dei contagi che di giorno in giorno migliora e diventa statisticamente piu` rilevante.

Ovviamente immagino che ci avete gia` pensato ma che sia una informazione a voi inaccessibile e nascosta dal "freddo" numero che viene sputato fuori dai laboratori a fine giornata, in ogni caso mi sembrava oppurtuno comunicarvelo.

my two cents

**Comment by magaspari** [comment]
Capisco la problematica che sollevi, ma in realtà dopo riflessione secondo me va bene cosi perché tecnicamente una persona diventa positiva nel momento in cui è processato il tampone ed il risultato è positivo. Del resto la data del prelievo non approssimerebbe meglio l'evento del contagio che potrebbe essere anche due settimane prima.  Sarebbe pero' utile che i dati sui tamponi fossero più ricchi riportando come suggerisci la data del prelievo ma anche altre informazioni.
