### ISSUE TITLE
Unico endpoint

### ISSUE THREAD

**Issue by marcs7** [pcm-dpc/COVID-19#39]
Sarebbe conveniente avere degli endpoint unici per sia per i dati in json che per i dati in csv oltre che ad avere i dati giorno per giorno, renderebbe più comodo il prelevmento dei dati

**Comment by umbros** [comment]
Ciao @marcs7 metto in ToDo

**Comment by marcs7** [comment]
se possibile vorrei contrinuire in qualche modo allo sviluppo del progetto

**Comment by enrichman** [comment]
@marcs7 la #62 potrebbe aiutare in qualche modo?

**Comment by marcs7** [comment]
Un po’ sì, se riesco domani lavoro a degli endpoint su un mio serve che poi renderò pubblici, se possibile vorrei che la issue rimanesse aperta così metto qui gli endpoint

**Comment by fmarco** [comment]
Ciao a tutti, io ieri ho creato questo microbackend https://github.com/fmarco/covid-19_italia_backend e tirato su un'istanza raggiungibile a questo indirizzo http://covid19italia.duckdns.org:5000/docs.
Stamani visto per caso la issue e mi piacerebbe collaborare (o tenere un repo separato a seconda di come si evolverà questo progetto :) ).

**Comment by marcs7** [comment]
salve a tutti, a causa di contrattempi non sono riuscito a scrivere una riga, entro stasera spero di riuscire a fare l'endpoint per i dati nazionali
molto probabilmete li lascerò in questa issue o farò una repo raccoglitore

**Comment by umbros** [comment]
Ciao a tutti,
stiamo ipotizzando la possibilità di fornire delle API. Vi terremo aggiornati.
