### ISSUE TITLE
Positivi asintomatici / Incremento del numero di tamponi eseguiti

### ISSUE THREAD

**Issue by glcir** [pcm-dpc/COVID-19#390]
## Riassunto
I tamponi sono effettuati su pazienti sintomatici (salvo rare eccezioni). Ogni giorno, pertanto, viene calcolato il totale casi positivi sintomatici che include i pazienti attualmente positivi (ospedalizzati o domiciliari), i guariti ed i decessi. Da alcuni giorni - in particolare da parte dai Presidenti delle Regioni Lombardia e Veneto - è stato affermato che verranno eseguiti più tamponi, anche su pazienti asintomatici appartenenti a determinate categorie. 
In altri termini, se ciò fosse vero, la crescita dei positivi sarà "viziata" da rilievi che prima non sono stati fatti e, di conseguenza, non sarà possibile valutare se le misure di contenimento stanno producendo effetti sulla diffusione del virus. Se i positivi, infatti, aumentano non sarà possibile capire se le misure di contenimento non hanno avuto effetto ovvero se l'aumento dipende dall'inclusione dei pazienti asintomatici che prima non venivano considerati.
A mio avviso, sarebbe opportuno che si specificasse nel db quanti sono i positivi asintomatici inclusi nei casi "attualmente positivi", in modo che possano essere esclusi dal conteggio e, di conseguenza, le analisi dell'andamento contagi continuerebbe a riferirsi ai soli casi positivi di pazienti sintomatici.

**Comment by magaspari** [comment]
Concordo sull'importanza di riportare l'informazione riguardo agli asintomatici, in quanto anche loro contribuiscono alla diffusione della malattia, ma a mio avviso non deve essere fatto contestualmente ai casi attivi, ma dovrebbe riguardare le conclusioni, ovvero distinguere tra guarigioni e guarigioni senza sintomi.
Tra gli attuali positivi, c'è già la categoria in_isolamento_domiciliare che comprende eventuali asintomatici.  Credo sia difficile gestire questo dato contestualmente al numero di positivi, in quanto la mancata sintomatologia è qualcosa che può' cambiare e che può quindi aver valore certo solo alla chiusura del caso al momento della guarigione.

**Comment by glcir** [comment]
Grazie per la risposta. Ho visto, comunque, che il numero dei tamponi
eseguiti negli ultimi giorni non ha subito particolare incremento, quindi
la tendenza della diffusione dei contagi a mio avviso non è alterata da
ulteriori tamponi fatti su una popolazione di riferimento più ampia.
Grazie per il prezioso lavoro che state svolgendo!
gl

Il giorno sab 28 mar 2020 alle ore 16:34 magaspari <notifications@github.com>
ha scritto:
