### ISSUE TITLE
Protocollo Emergenza Virus Italia | Sorveglianza Cittadino Attivo

### ISSUE THREAD

**Issue by AFE-admin** [pcm-dpc/COVID-19#391]
Ciao A tutti. Ho partecipato al bando pubblico con proposta di un Protocollo per dare risposte, in particolare ai pazienti in assitenza domiciliare, asintomatici e sintomatici. Si ragiona per numeri complessivi e non singole entità, quindi ho cercato di elaborare quanto potrebbe essere implementato con i vostri dati complessivi ( sorveglianza cittadino attivo ) . Questo ci consentirebbe di organizzare e coordinare l'assistenza domiciliare, mediante i centri 118, i centri medici di assistenza locali i pazienti che si sono negativizzati, gli asintomatici, quanti hanno necessità di assistenza domiciliare e di servizi. https://www.associazionefilieraeditoriale.it/p-e-v-i . Grazie

**Comment by umbros** [comment]
Grazie a te.
