### ISSUE TITLE
errore conteggio totale_casi

### ISSUE THREAD

**Issue by VitoFanelli** [pcm-dpc/COVID-19#392]
Salve, riscontro una incongruenza nel calcolo del campo totale_casi, sia a livello regionale sia nazionale.

Il totale_casi è pari alla somma dei campi totale_attualmente_positivi, dimessi_guariti e decessi (totale_casi = totale_attualmente_positivi + dimessi_guariti + decessi).

I nuovi_attualmente_positivi = totale_attualmente_positivi - totale_attualmente_positivi (giorno prima).

A logica il totale_attualmente_positivi dovrebbe essere
totale_attualmente_positivi = totale_attualmente_positivi (giorno prima) + nuovi_attualmente_positivi - dimessi_guariti -  decessi. 

Cosi la somma del totale_casi sarebbe corretta. Invece adesso tiene conto sia degli attualmente positivi non al netto dei dimessi/guariti sia dei dimessi/decessi ed è come se contasse due volte un dimesso/decesso.

Resto in attesa di delucidazioni in merito. Grazie!

**Comment by Tantormai** [comment]
Penso ci sia un errore nella formula del totale_attualmente_positivi.
Se fosse vera la formula:
1) totale_attualmente_positivi = totale_attualmente_positivi (giorno prima) + nuovi_attualmente_positivi - dimessi_guariti - decessi.
ci sarebbe un bel riferimento circolare tra totale_attualmente_positivi e nuovi_attualmente_positivi:
2) nuovi_attualmente_positivi = totale_attualmente_positivi - totale_attualmente_positivi (giorno prima).
In realtà la 1) si scrive:
1) totale_attualmente_positivi = totale_attualmente_positivi (giorno prima) + nuovi_casi - dimessi_guariti - decessi
laddove 
nuovi_casi= totale_casi- totale_casi (giorno precedente)

**Comment by jacopoc** [comment]
> A logica il totale_attualmente_positivi dovrebbe essere
> totale_attualmente_positivi = totale_attualmente_positivi (giorno prima) + nuovi_attualmente_positivi - dimessi_guariti - decessi.

A mio parere la formula proposta non è corretta; la formula corretta è:
totale_attualmente_positivi = totale_attualmente_positivi (giorno prima) + nuovi_attualmente_positivi

**Comment by duckyb** [comment]
> 1. totale_attualmente_positivi = totale_attualmente_positivi (giorno prima) + **nuovi_attualmente_positivi - dimessi_guariti - decessi**.

Questo non ha senso, dal valore nuovi_attualmente_positivi sono già sottratti i dimessi_guariti e i decessi.
Ricordo che
<code>nuovi_attualmente_positivi = nuovi_infetti - nuovi_dimessi_guariti - nuovi_decessi

**Comment by helloer00** [comment]
![schema](https://user-images.githubusercontent.com/17719313/77785766-edf85b00-705c-11ea-9335-905c224e9b85.jpg)

**Comment by helloer00** [comment]
![2020-03-27 19 06 04](https://user-images.githubusercontent.com/17719313/77786946-04071b00-705f-11ea-8647-4374c0efca51.png)

**Comment by FedericoStra** [comment]
Non sei né il primo né l'ultimo a contestare questo fatto. Ti rimando a uno a scelta fra questi link in cui ci siamo battuti affinché venga pubblicato anche `nuovi_casi` oltre a `nuovi_attualmente_positivi`: #263, #268, #275, #277, #292, #294, #308, #314, #315, #332, #338 (in particolare [qui](https://github.com/pcm-dpc/COVID-19/issues/338#issuecomment-603399204)).

**Comment by ddefrancesco** [comment]
Ciao,
ma se è vera questa:

`nuovi_attualmente_positivi = nuovi_infetti - nuovi_dimessi_guariti - nuovi_decessi`

si ha

`nuovi_infetti = nuovi_attualmente_positivi + nuovi_dimessi_guariti + nuovi_decessi`

Ossia, se leggo bene, sia i **nuovi_decessi** e i **nuovi_dimessi_guariti** farebbero parte dei **nuovi_infetti** il che è quantomeno strano per me...
Saluti

**Comment by FedericoStra** [comment]
No no no, è l'esatto contrario. `nuovi_infetti` è il numero di persone *nuove* che sono state infettate, ovvero persone che fino a ieri non risultavano infette mentre oggi sì perché hanno ricevuto il risultato positivo del tampone. `nuovi_attualmente_positivi` è invece un pessimo nome per quello che si dovrebbe invece chiamare `variazione_attualmente_positivi` o `bilancio_attualmente_positivi`. Alcune persone diventano positive (i nuovi infetti appunto), mentre altre persone smettono di essere positive perché guariscono o muoiono. Quindi il bilancio risulta essere `nuovi_attualmente_positivi = nuovi_infetti - nuovi_dimessi_guariti - nuovi_decessi`.

**Comment by giancarmine07** [comment]
quindi alla fine voi indicate i nuovi casi facendo tot casi giorno corrente meno tot casi giorno precedente o, come indicato in wiki, i nuovi casi sono quelli riportati in nuovi_attualmente_positivi??

**Comment by danielesalpietro** [comment]
@helloer00, in verità ci sarebbero anche casi come questi:

1) da terapia intensiva -> Ospedale; 
2) da Ospedale -> Isolamento, 
3) da isolamento -> deceduti (ma se non ho capito male non vengono conteggiati in quanto non sono deceduti in ospedale. restano nel limbo); 
4)  da Ospedale -> Terapia Intensiva (quelli che si aggravano o sono stati parcheggiati in attesa di un posto in terapia intensiva);
5) ci sarebbero anche quelli che da isolamento vengono trasportati al PS perché hanno bisogno di un posto in terapia intensiva, ma un posto letto non c'è più ( o perché viene dato il posto a chi ha maggiore aspettativa di vita) ed il paziente muore in ambulanza fuori dal PS (perché di certo non lo riaccompagnano a casa)....

poi ci sarebbero anche:

5) non identificati ->  deceduti (ossia non erano in isolamento: vedi RSA, anche questi non vengono conteggiati, ne viene fatta loro alcun accertamento sul covid-19)  perché non sono stati identificati e posti in isolamento (per 1000 motivi); 

E questi sono solo i deceduti diretti, poi ci sono quelli indiretti....ma questa è un altra storia che è meglio non toccare per ora.

**Comment by FedericoStra** [comment]
@giancarmine07 Nella lettura del bollettino delle 18 viene detto "l'incremento delle persone positive è blablabla". Questa cosa è tecnicamente corretta, ma può risultare fuorviante per molte persone. In particolare i giornali sono andati avanti per due settimane a scrivere che i "nuovi casi sono blablabla", scambiando un dato per un altro. Quello che contesto è che `nuovi_attualmente_positivi` non è il dato giusto sulla base del quale farsi tutte le costruzioni mentali del tipo "il trend sale, il trend scende". Semplicemente non è la quantità giusta che misura la diffusione dei contagi; è una variabile che dipende anche dalle guarigioni e dalle morti. Ci sono stati giorni in cui è stato detto erroneamente che i contagi calavano perché `nuovi_attualmente_positivi` era più piccolo solamente perché c'erano stati più guariti e morti. Questa cosa è una demenzialità assurda. Quindi, riassumendo, la PC presenta il dato in maniera tecnicamente corretta, ma è un dato che viene frainteso troppo spesso.

**Comment by ftornaboni** [comment]
Scusate, ho notato anche io tutte queste incongruenze (e sono appunto finito qui). 
Ma quindi per avere il dato "corretto" sui "nuovi contagiati" cioè detto in parole povere: "i nuovi tamponi positivi" come dobbiamo fare? Perché per avere una visione corretta dell'epidemia dovremmo avere un dato che riporta: Nuovi vivi positivi + Nuovi "morti" positivi (ovvero persone decedute a cui è stato fatto il tampone dopo il decesso)? 

Perché tutti i discorsi fatti sui giornali fino ad ora sembrano essere "inconsistenti"

Grazie

**Comment by jacopoc** [comment]
@ftornaboni 
> Ma quindi per avere il dato "corretto" sui "nuovi contagiati" cioè detto in parole povere: "i nuovi tamponi positivi" come dobbiamo fare?

Puoi ottenere questo dato sottraendo da "tot casi" del giorno il "tot casi" del giorno precedente.

**Comment by giancarmine07** [comment]
@FedericoStra capito. Abbastanza imbarazzante questa ambiguità sul dato più importante. Magari qualche riga in più di spiegazioni da parte di chi comunica i dati sarebbe stata necessaria.

**Comment by ftornaboni** [comment]
Grazie mille per il chiarimento.

**Comment by davidfregoli** [comment]
è stato aggiunto il campo "nuovi_positivi": 4053

**Comment by smicchetti** [comment]
dove posso trovare la legenda ufficiale in cui sono descritti i campi? 
In particolare vorrei leggere come sono conteggiati i "nuovi_positivi".

**Comment by davidfregoli** [comment]
nuovi positivi è "totale casi oggi" - "totale casi ieri"

**Comment by smicchetti** [comment]
non sono interessato a conoscere il dato matematico (facilmente deducibile e correttamente definito da davidfregoli) bensì alla definizione per cui rinnovo la richiesta di conoscere la legenda ufficiale.

**Comment by davidfregoli** [comment]
[qua](https://github.com/pcm-dpc/COVID-19#dati-per-regione) trovi la legenda: `Nuovi attualmente positivi (totale_casi giorno corrente - totale_casi giorno precedente)`

**Comment by FedericoStra** [comment]
> `nuovi_positivi`: Nuovi attualmente positivi (totale_casi giorno corrente - totale_casi giorno precedente)

Uhm... no! Perché c'è scritto "attualmente"?! Mamma mia queste legende... 😖

Comunque forse @smicchetti si riferiva piuttosto alla "definizione operativa" di "nuovi casi". Immagino che sia il numero di persone che nelle ultime 24 ore hanno ricevuto il risultato positivo al tampone.

**Comment by giancarmine07** [comment]
Attenzione che in "nuovi positivi" ho verificato che risultano anche quelli che risultavano positivi, hanno effettuato il tampone e risultano ancora positivi(se il dato è nuovi positivi perché rientrano anche queste persone?)...ma può darsi sia un errore di comunicazione della mia regione.
