### ISSUE TITLE
nuovi_attualmente_positivi non indicativo della diffusione dell'epidemia

### ISSUE THREAD

**Issue by JanosAudron** [pcm-dpc/COVID-19#394]
Attualmente il grafico "Incremento giornaliero degli attualmente positivi" riporta l'andamento del dato "nuovi_attualmente_positivi".
Ipoteticamente, se da ieri ci sono stati 1000 nuovi positivi e 1000 nuovi decessi, il dato "nuovi_attualmente_positivi" riporterebbe 0. Inoltre quando il contagio rallenterà, il grafico scenderà a valori negativi.
Questo trend è significativo per capire la capacità del SSN di assorbire i nuovi casi ma non è indicativo della diffusione dell'epidemia.
Sarebbe invece più interessante visualizzare nel grafico l'andamento dei nuovi positivi, calcolati come "totale_attualmente_positivi" - "totale_attualmente_positivi (giorno precedente)"

Anche a livello mediatico, le testate giornalistiche riportano i dati che comunicate come "nuovi_attualmente_positivi" come indice della diffusione, ma questo è errato.

**Comment by omareltf** [comment]
Sono d'accordo, penso che lo sappiano benissimo e sia più una questione di "preoccupare meno" essendo il numero più piccolo.

**Comment by JanosAudron** [comment]
E ma se fosse così, quando il grafico andrà sotto zero dovranno spiegare il perché...

**Comment by fpacenza** [comment]
Si, credo anche io che ne siano già a conoscenza. Se si guardano i dati forniti nel file json, in alcuni casi, la **Lombardia** riporta **nuovi_attualmente_positivi** con numero negativo (ad esempio -69 in data 2020-03-10)

       {
        "data": "2020-03-10T18:00:00",
        "stato": "ITA",
        "codice_regione": 3,
        "denominazione_regione": "Lombardia",
        "lat": 45.46679409,
        "long": 9.190347404,
        "ricoverati_con_sintomi": 3319,
        "terapia_intensiva": 466,
        "totale_ospedalizzati": 3785,
        "isolamento_domiciliare": 642,
        "totale_attualmente_positivi": 4427,
        "nuovi_attualmente_positivi": -63,
        "dimessi_guariti": 896,
        "deceduti": 468,
        "totale_casi": 5791,
        "tamponi": 21479,
        "note_it": "pd-IT-0004",
        "note_en": "pd-EN-0004"
        }

Questo dato negativo è dato dalla sottrazione di **totale_attualmente_positivi** del giorno 2020-03-10 (4427 casi) e di **totale_attualmente_positivi** del giorno 2020-03-09 (4490 casi).
Il dato da sottrarre per avere i reali **nuovi_attualmente_positivi** è **totale_casi** del giorno corrente - **totale_casi** del giorno precedente.

**Comment by JanosAudron** [comment]
Eh, ma una cosa è un file json che mai nessuno andrà a vedere, un conto è il grafico pubblicato sulla pagina della protezione civile

**Comment by Marco-Santoni** [comment]
Osservazione corretta.

**Comment by fpacenza** [comment]
Si, infatti concordo pienamente sul fatto che il dato andrebbe cambiato anche sul grafico della protezione civile... molte persone purtroppo non sono a conoscenza della realtà di questo dato... personalmente, sul mio sito web, utilizzo il dato calcolato nella maniera “corretta”...spero che questo venga aggiornato anche sul sito web della protezione civile poiché è sicuramente molto più consultato

**Comment by FedericoStra** [comment]
È già stato fatto notare almeno in queste occasioni: #263, #268, #275, #277, #292, #294, #308, #314, #315, #332, #338.

Non posso che appoggiare la richiesta di riportare anche `nuovi_casi`. Infatti, oltre a essere un dato estremamente importante per tracciare l'andamento della diffusione, è anche il numero che la WHO raccomanda di comunicare, in modo da consentire confronti più facili fra le varie nazioni (vedere per esempio anche i loro [reports](https://www.who.int/emergencies/diseases/novel-coronavirus-2019/situation-reports)). L'Italia è l'unico paese in cui viene comunicato al pubblico il bilancio dei malati. Questa cosa non ha nessun senso, ma c'è una riluttanza estrema a cambiare le cose. Worldometer ha pure messo un [avviso](https://www.who.int/emergencies/diseases/novel-coronavirus-2019/situation-reports) che allerta di visitatori a fare attenzione a come vengono comunicati i dati in Italia.

Io è da settimane che chiedo insistentemente che venga pubblicato questo numero sui bollettini ufficiali. È semplicemente assurdo che nel report ufficiale riguardante un'epidemia non compaia il numero di nuovi contagi rilevati in un giorno. Allucinante. Ho anche contattato diversi giornali per informarli del fraintendimento e ho avuto moderato successo nel far loro capire che spesso riportavano in maniera erronea i dati.

**Comment by RobertoPerico** [comment]
Aggiungo inoltre che in molte occasioni è presente un numero di nuovi positivi (calcolati con la sottrazione tra `totale_casi` di un giorno con quello precedente) che supera il numero di tamponi eseguiti quello stesso giorno (calcolato con `tamponi` - `tamponi` del giorno precedente), il che è impossibile. Al massimo si può raggiungere un tasso del 100% (tutti i tamponi presi risultano positivi). Per esempio, per il giorno 27 febbraio in lombardia risultano effettuati 112 tamponi (3320 - 3208) ma 145 positivi (403 - 258)

**Comment by pierluigicara** [comment]
Anzitutto vi ringraziamo per l'attenzione e la cura che applicate a quello che è il patrimonio informativo pubblico che il DPC e il Ministero della Salute stanno mettendo a disposizione di tutti nella forma degli open data. Questo per noi è lo scopo principale del lavoro che stiamo svolgendo e di questo repository. Non entro dunque nel merito della questione posta, non per eluderla ma per invitare tutti a prendere consapevolezza del quadro più generale dei flussi di dati messi a disposizione e del loro rispettivo significato. Parlo di flussi perchè, in realtà sono due. Senza entrare in ulteriori dettagli che qui sarebbero superflui vi invito ad ascoltare l'intervento del Presidente dell'Istituto Superiore di Sanità (ISS) Prof. Brusaferro nella conferenza stampa svolta l'altro ieri (https://www.youtube.com/watch?v=a3WdfpnYZBI). Mi pare un'ottima sintesi del ruolo dei dati DPC/MinSalute in relazioni all'analisi epidemiologica che sta svolgendo ISS. Concludo con un auspicio, che riguarda uno sviluppo che intenderemmo attuare, ovvero che tali flussi possano essere meglio coordinati in futuro per facilitare le vostre attività e (speriamo) rendere sempre più soddisfacenti ed efficaci le vostre valutazioni. Buon lavoro a tutti da noi.

**Comment by FedericoStra** [comment]
> Non entro dunque nel merito della questione posta, non per eluderla ma per invitare tutti a prendere consapevolezza del quadro più generale dei flussi di dati messi a disposizione e del loro rispettivo significato.

@pierluigicara Cosa vorrebbe dire questa risposta? Qual è la motivazione della chiusura dell'issue? Io vedo solo un link a YouTube e un auspicio. In che modo giustificano in maniera soddisfacente di questo issue?!

> **Senza entrare in ulteriori dettagli che qui sarebbero superflui** vi invito ad ascoltare l'intervento del Presidente dell'Istituto Superiore di Sanità (ISS) Prof. Brusaferro nella conferenza stampa svolta l'altro ieri (https://www.youtube.com/watch?v=a3WdfpnYZBI).

No ma per carità, entriamoci pure nei dettagli! Che cosa non è chiaro nella proposta di questo issue?

**Comment by JanosAudron** [comment]
> Anzitutto vi ringraziamo per l'attenzione e la cura che applicate a quello che è il patrimonio informativo pubblico che il DPC e il Ministero della Salute stanno mettendo a disposizione di tutti nella forma degli open data. Questo per noi è lo scopo principale del lavoro che stiamo svolgendo e di questo repository. Non entro dunque nel merito della questione posta, non per eluderla ma per invitare tutti a prendere consapevolezza del quadro più generale dei flussi di dati messi a disposizione e del loro rispettivo significato. Parlo di flussi perchè, in realtà sono due. Senza entrare in ulteriori dettagli che qui sarebbero superflui vi invito ad ascoltare l'intervento del Presidente dell'Istituto Superiore di Sanità (ISS) Prof. Brusaferro nella conferenza stampa svolta l'altro ieri (https://www.youtube.com/watch?v=a3WdfpnYZBI). Mi pare un'ottima sintesi del ruolo dei dati DPC/MinSalute in relazioni all'analisi epidemiologica che sta svolgendo ISS. Concludo con un auspicio, che riguarda uno sviluppo che intenderemmo attuare, ovvero che tali flussi possano essere meglio coordinati in futuro per facilitare le vostre attività e (speriamo) rendere sempre più soddisfacenti ed efficaci le vostre valutazioni. Buon lavoro a tutti da noi.

Senza "entrare in ulteriori dettagli" ci spiegate cortesemente il motivo di aggiungere la dashboard "Nuovi positivi",se quello che dicevamo era errato? Grazie
![image](https://user-images.githubusercontent.com/1606318/77991595-a4da2c80-7324-11ea-907e-6dfa838f0c5d.png)

**Comment by Marco-Santoni** [comment]
![image](https://user-images.githubusercontent.com/5029487/78219319-9116fd80-74bf-11ea-98e0-763bfb65d5b2.png)

Grazie per aver migliorato la definizione del dato 🙏
