### ISSUE TITLE
Richiesta info "codice provincia" e "denominazione_provincia"

### ISSUE THREAD

**Issue by theRosyProject** [pcm-dpc/COVID-19#395]
**Tipo di richiesta**: richiesta di informazione 

## Riassunto
Nel dataset master/dati-province/dpc-covid19-ita-province.csv alla voce codice 
provincia e denominazione_provincia sono inseriti dei valori definiti come In
fase di definizione/aggiornamento. Posso chiedere, aldilà del significato del
contenuto delle celle, se questa struttura rimarrà inalterata in futuro o se 
sono previste delle modifiche per questo campo? Ad esempio rimozione o aggiunta
di nuove righe al dataset? grazie per il vostro lavoro.

## Interesse pubblico
Il campo non è chiaro e non sono chiare le azioni future che si intendono 
effettuare per la voce in questione. Il mantenimento della struttura del
dataset è importante per chi effettua elaborazioni dati in automatico.

**Comment by umbros** [comment]
Ciao @theRosyProject ti spiego subito, essendo un momento di grossa emergenza, spesso ci sono pazienti che possono essere trasferiti e quindi non è certa la loro localizzazione, per questo abbiamo aggiunto una provincia "In fase di definizione/aggiornamento" per ogni regione dove mettere quelli attualmente non "allocati" o in fase di "allocazione".
