### ISSUE TITLE
file json provincia mancano dati giorni precedenti

### ISSUE THREAD

**Issue by claort** [pcm-dpc/COVID-19#396]
file json provincia
mancano dati giorni precedenti

**Comment by lp74** [comment]
confermo, mancano i dati dei gg precedenti nelle province

**Comment by marcochiodo** [comment]
Confermo

**Comment by pinoli** [comment]
Nel file **dpc-covid19-ita-province-latest.json** sono presenti i dati di solo 2 giorni, 26/3 e 27/3
Nel file **dpc-covid19-ita-province.json** sono presenti i dati solo del 26/3

**Comment by umbros** [comment]
Corretto, grazie a tutti per la segnalazione.
