### ISSUE TITLE
Il file json per le province contiene solo i dati del 27/03

### ISSUE THREAD

**Issue by salv-orlando** [pcm-dpc/COVID-19#397]
Tipo di issue:

- [X ] Dati mancanti o errati: dati-json/dpc-covid19-ita-province.json 
- [ ] Errore nella documentazione 
- [ ] Errore or mancanza nella dashboard 
- [ ] Problemi di visualizzazione nella dashboard 

- Regione:
- Provincia: 

## Riassunto

Il file sembra contenere solo i dati del 27/03

**Attesa:**

Dati a partire dal 24/02

**Attuale:** 

Solo dati del 27/03

Sembra una ricorrenza di Issue #171 - credo sia piu' semplice per voi aggiornare la repo, ma se preferite ho il diff pronto.

**Comment by umbros** [comment]
Corretto, grazie.
