### ISSUE TITLE
Dati a livello provinciale - Possibile Errore

### ISSUE THREAD

**Issue by lorenzo-gabrielli** [pcm-dpc/COVID-19#399]
Salve,

Credo che ci sia un errore (almeno con i dati della toscana)
Sembra che il numero totale di casi delle province toscane sia uguale a quello di ieri.
Lo credo poco plausibile

Se cercate la stringa 2020-03-26T17:00:00,ITA,09,Toscana,046,Lucca, Troverete 481 casi
Se cercate la stringa 2020-03-27T17:00:00,ITA,09,Toscana,046,Lucca, Troverete sempre gli stessi 481 totali.

Forse è stato concatenato due volte lo stesso file?

Grazie

Tipo di issue:

- [ ] Dati mancanti o errati 
- [ ] Errore nella documentazione 
- [ ] Errore or mancanza nella dashboard 
- [ ] Problemi di visualizzazione nella dashboard 

- Regione:
- Provincia: 

## Riassunto

**Attesa:**

**Attuale:**

**Comment by umbros** [comment]
Ciao,
corretto, i dati aggiuntivi sono nel campo In fase di definizione/aggiornamento
