### ISSUE TITLE
Unico File per dati regionali e provinciali

### ISSUE THREAD

**Issue by DataEnthusiast84** [pcm-dpc/COVID-19#4]
Buongiorno a tutti,

innanzitutto un sincero e profondo ringraziamento per il lavoro della Protezione Civile e soprattutto, per aver reso pubblici i dati in formato "open" e facilmente interrogabili.

Mi permetto solo di fare una singola osservazione: affinché sia facilitata l'elaborazione attraverso strumenti "terzi" e applicazioni e software di business intelligence si potrebbe creare un singolo file .csv e non singoli file distinti per giorno...

Un ringraziamento sentito a tutti coloro che in questo momento lavorano affinché si possa uscire nel più breve tempo possibile da questa epidemia.

Alessandro.

**Comment by umbros** [comment]
Alessandro, la cosa è fattibile, in questo momendo stiamo gestendo la risoluzione di eventuali malfunzionamenti e migliorie generali dei processi e rilascio dati. Metto come ToDo l'attività e sarà disponibile dalla giornata di domani. Nel frattempo abbiamo rilasciato 3 file json per andamento nazionale, dati comuni e dati province complessivi.

**Comment by DataEnthusiast84** [comment]
@umbros Grazie davvero! L'ho proposto semplicemente perchè non tutti i software si interfacciano con JSON.

Complimenti ancora per l'ottimo lavoro!!!!

P.S: riguardo la "granularità" dei dati, questi pubblicati sono al massimo livello di dettaglio? Dal punto di vista geografico si hanno ad esempio ulteriori dettagli a livello comunale?

**Comment by pescetti** [comment]
Questi CSV contengono già la data come colonna, quindi concatenarli è molto semplice.

```
(head -1 dpc-covid19-ita-province-20200224.csv && for i in dpc-covid19-ita-province-* ; do tail -n+2 $i; done) > dpc-province-aggregato.csv
```

Allego il file risultante. [dpc-province-aggregato.zip](https://github.com/pcm-dpc/COVID-19/files/4302210/dpc-province-aggregato.zip)

Oppure si può convertire il JSON in CSV con uno dei tanti convertitori anche online che lo fanno.

Insomma, non penso che servano ulteriori varianti, i CSV per giorno e il file JSON unico soddisfano tutte le necessità e poi tocca a ciascuno effettuare la preparazione dei dati ai suoi scopi.

**Comment by salvofedele** [comment]
Fa

> Questi CSV contengono già la data come colonna, quindi concatenarli è molto semplice.
> 
> ```
> (head -1 dpc-covid19-ita-province-20200224.csv && for i in dpc-covid19-ita-province-* ; do tail -n+2 $i; done) > dpc-province-aggregato.csv
> ```
> 
> Allego il file risultante. [dpc-province-aggregato.zip](https://github.com/pcm-dpc/COVID-19/files/4302210/dpc-province-aggregato.zip)
> 
> Oppure si può convertire il JSON (che è già un file unico) in CSV con uno dei tanti convertitori anche online che lo fanno.
> 
> Insomma, non penso che servano ulteriori varianti, i CSV per giorno e il file JSON unico soddisfano tutte le necessità e poi tocca a ciascuno effettuare la preparazione dei dati ai propri scopi.
Grazie molte

**Comment by etrevis** [comment]
Grazie mille per rendere i dati disponibili!

Concordo con @pescetti che aggiungere un file è un po' ridondante, ma non fa' male diciamo.
Nel frattempo manterrò uno copia aggiornata nella mia [repo](https://github.com/etrevis/DB-and-Visuals-Covid-19-/tree/master/Data).

**Comment by miccoli** [comment]
Mi permetto di sconsigliare l'aggiunta di un file complessivo in formato `.csv` 

È sempre una cattiva idea avere la stessa informazione in due file differenti: in caso di discordanza, quale è quello giusto?

Visto che è relativamente facile generare il `.csv` complessivo e che @etrevis fornisce questo servizio mi sembra inutile appesantire questa repo.

> "A man with a watch knows what time it is. A man with two watches is never sure."  :wink:

**Comment by Furbessem** [comment]
Mi permetto di consigliare che l'istituzione di livello nazionale consigli un formato unico per la raccolta dati dalle varie strutture operative in modo da superare una storica divisione dell'organizzazione dei servizi sul territorio da regione a regione.

Almeno per questa emergenza.

L'autonomia delle regioni è sancita e sacrosanta, ma in caso di emergenza non vorrei che si rallentassero le attività (o il flusso di informazioni) per mancato coordinamento.

Grazie ancora.

**Comment by umbros** [comment]
Grazie a tutti per i commenti, i file sono stati messi a disposizione sia in formato json che csv
https://github.com/pcm-dpc/COVID-19/blob/master/dati-andamento-nazionale/dpc-covid19-ita-andamento-nazionale.csv
https://github.com/pcm-dpc/COVID-19/blob/master/dati-province/dpc-covid19-ita-province.csv
https://github.com/pcm-dpc/COVID-19/blob/master/dati-regioni/dpc-covid19-ita-regioni.csv
https://github.com/pcm-dpc/COVID-19/blob/master/dati-json/dpc-covid19-ita-andamento-nazionale.json
https://github.com/pcm-dpc/COVID-19/blob/master/dati-json/dpc-covid19-ita-province.json
https://github.com/pcm-dpc/COVID-19/blob/master/dati-json/dpc-covid19-ita-regioni.json
