### ISSUE TITLE
Cambiata la denominazione Ospedalizzati

### ISSUE THREAD

**Issue by DataEnthusiast84** [pcm-dpc/COVID-19#40]
Utilizzo i dati JSON...

Penso 5 ore fa - data dell'ultimo aggiornamento - la denominazione è cambiata da "ospedalizzati" a "totale_ospedalizzati"....
Attenzione...

**Comment by umbros** [comment]
Ciao @DataEnthusiast84 ,
confermo, come specificato suCHANGELOG e README, ho messo in andamento i dati, aggregati a livello nazionale con le stesse informazioni del dato Regioni.
