### ISSUE TITLE
Mancato aggiornamento `totale_casi` in Toscana

### ISSUE THREAD

**Issue by mircozanchi** [pcm-dpc/COVID-19#400]
Tipo di issue:

- [x] Dati mancanti o errati in`/dati-province/dpc-covid19-ita-province-20200327.csv`
- [ ] Errore nella documentazione 
- [ ] Errore or mancanza nella dashboard 
- [ ] Problemi di visualizzazione nella dashboard 

- Regione: Toscana
- Provincia: Tutte le province

## Riassunto

I valori del campo `totale_casi` nel file `/dati-province/dpc-covid19-ita-province-20200327.csv` per le province della regione Toscana sono uguali ai valori del giorno precedente.

**Attesa:**
Dati aggiornati al giorno 2020-03-27 per le province della regione Toscana.

**Attuale:**
Dati non aggiornati.

**Comment by lp74** [comment]
confermo, i dati provinciali per la toscana sono anomali

**Comment by umbros** [comment]
Come per altri, i dati province per la Toscana, sono in "In fase di definizione/aggiornamento"
