### ISSUE TITLE
Dati Toscana 27/03 identici a 26/03

### ISSUE THREAD

**Issue by salatest** [pcm-dpc/COVID-19#401]
Il file csv del 27/03 ha gli stessi dati inerenti la Toscana del file del 26/03, dato che non ci sono segnalazioni di mancato ricevimento dati dalla Toscana nella home della protezione civile, è un errore di compilazione?

**Comment by umbros** [comment]
No, confermiamo, i dati sono in "In fase di definizione/aggiornamento" della Regione Toscana

**Comment by lp74** [comment]
Grazie
