### ISSUE TITLE
[request] Feature: nuovi_deceduti

### ISSUE THREAD

**Issue by mzanrosso** [pcm-dpc/COVID-19#403]
È possibile che i database implementino un nuovo campo “nuovi_deceduti” che come nel caso di “nuovi_attualmente_positivi” fornisca un andamento giornaliero utile.

**Comment by umbros** [comment]
Ciao @mzanrosso è calcolabile. Quindi ogni valore che volete calcolare ovviamente lo potete fare sulla base dei dati che eroghiamo.
