### ISSUE TITLE
Isolam domiciliare Sicilia 

### ISSUE THREAD

**Issue by claort** [pcm-dpc/COVID-19#404]
Dati riportati in JSON e csv per oggi 658
Dati riportati dalla regione 668

Ecco screen 
![151077379](https://user-images.githubusercontent.com/38251311/77797170-e80c7500-7070-11ea-927a-1d3179a42db7.JPG)

Potete dirmi perché non corrisponde? 
Grazie

**Comment by umbros** [comment]
Ciao, i dati da noi espressi sono quelli comunicati dalle Regioni tramite il Ministero della Salute, eventuali inconsistenze possono essere dovute da errori di immissione dati o elaborazioni successive.

**Comment by claort** [comment]
grazie
