### ISSUE TITLE
Totale_casi per province non è cumulato

### ISSUE THREAD

**Issue by marcofranchin** [pcm-dpc/COVID-19#406]
Ho osservato che nella variabile "totale_casi" a proposito dei dati per province, per alcune province capita che in giorni successivi vi sia un calo nel valore di questa variabile. Questo non dovrebbe accadere dato che i dati sono cumulati.

Ad esempio, per Arezzo dal 18/03/2020 al 19/2020 si passa da un totale_casi di 142 a un totale_casi di 113.

**Comment by nicola-d** [comment]
Si, ho notato anche io.
Porto un altro esempio:

16/03/2020, provincia di Udine, totale casi 152
17/03/2020, provincia di Udine, totale casi 145

**Comment by umbros** [comment]
Ciao,
il totale casi potrebbero essere rivisti, per questo abbiamo aggiunto per ogni regione una provincia di "appoggio" (In fase di definizione/aggiornamento), la situazione è quella di cura delle persone e sistemazione delle anagrafiche quindi potrebbero capitare modifiche. Le Regioni stanno affrontando una situazione di totale emergenza quindi possono esserci inconsistenze.
