### ISSUE TITLE
Dato tamponi totali inconsistente per regione FVG il 19/03/2020

### ISSUE THREAD

**Issue by nicola-d** [pcm-dpc/COVID-19#407]
Tipo di issue:
Dati mancanti o errati (in dpc-covid19-ita-regioni.csv e relativi equivalenti)

- Regione: Friuli Venezia Giulia

Riassunto

Dato tamponi totali inconsistente per regione FVG il 19/03/2020, dato inferiore a quello del giorno precedente. (Stesso problema rilevato in altri "ISSUES" per altre regioni)

Attesa:
Ci si aspetterebbe un numero totale di tamponi superiore o uguale al giorno precedente

Attuale:
Dato inferiore al giorno precedente.

**Comment by umbros** [comment]
Ciao,
il dato dei tamponi come altri possono essere rivisti. Capiamo che non è una situazione "normale" ma siamo in uno stato di emergenza nazionale e quindi potrebbero capitare errori di comunicazione dati.
