### ISSUE TITLE
dati-province Toscana giorno 27 marzo

### ISSUE THREAD

**Issue by sil-vio** [pcm-dpc/COVID-19#409]
Tipo di issue:
- [ ] Dati errati  dpc-covid19-ita-province.csv

- Regione: Toscana 
- Provincia: tutte le province

## Riassunto
Per tutte le province della toscana per il giorno 27 marzo i dati riportano lo stesso numero del giorno precedente

**Comment by DisherProject** [comment]
Come puoi leggere sul [bollettino](https://www.toscana-notizie.it/web/toscana-notizie/-/coronavirus-224-nuovi-casi-in-toscana.-3.450-i-contagi-dall-inizio) della regione di ieri _"A causa di temporanei problemi tecnici del sistema informativo non è possibile fornire i dati suddivisi per provincia dei tamponi risultati positivi."_, quindi credo che in loro mancanza ci si sia limitati a riportare quelli del giorno precedente

**Comment by sil-vio** [comment]
capito,
grazie per la risposta
