### ISSUE TITLE
Tamponi: cumulativo o giornaliero?

### ISSUE THREAD

**Issue by p43b1** [pcm-dpc/COVID-19#412]
Buongiorno,

il dato sul numero dei tamponi regionali è cumulativo oppure il numero indicato indica i tamponi effettuatisolamente nelle ultime 24h? Lo chiedo perchè nella descrizione in homepage non è specificato.

Grazie

**Comment by floatingpurr** [comment]
Direi cumulativo. E occhia al fatto che:

> totale dei tamponi (test) effettuati, un soggetto può essere sottoposto a più tamponi quindi non è indicativo delle persone controllate

Dai un'occhiata [qui](https://github.com/pcm-dpc/COVID-19/wiki/1.it-Dati:-andamento-nazionale)

**Comment by p43b1** [comment]
> 
> 
> Direi cumulativo. E occhia al fatto che:
> 
> > totale dei tamponi (test) effettuati, un soggetto può essere sottoposto a più tamponi quindi non è indicativo delle persone controllate
> 
> Dai un'occhiata [qui](https://github.com/pcm-dpc/COVID-19/wiki/1.it-Dati:-andamento-nazionale)

grazie mille quella pagina mi era completamente sfuggita!

Forse bisognerebbe aggiornare anche la homepage allora :)

**Comment by andre0341** [comment]
tra l'altro sarebbe comodo distinguere il dato di tamponi fatti e il dato di pazienti/soggetti (dato univoco) cui sono stati somministrati.

**Comment by andrea993** [comment]
Ma se i dati sui tamponi sono cumulativi come è possibile che non Emilia Romagna i dati dicano
28 marzo 52.991 tamponi
29 marzo 52.991 tamponi
30 marzo 50.990 tamponi
Con comunque aumento dei positivi?

**Comment by Nidroide** [comment]
In Lombardia il dato sui tamponi è 3700 il 25 febbraio e 3208 il 26 febbraio trattasi di un errore?

**Comment by ambr89** [comment]
Anche L'emilia romagna ha dei problemi con il dato dei tamponi, 
28/03 tamponi: 52991
29/03 tamponi: 52991
30/03 tamponi: 50990

**Comment by daemonPainter** [comment]
@ambr89 and @Nidroide se siete sicuri dei vostri controlli, mi sento di chiedervi di aprire un ticket a riguardo, se non lo avete già fatto. Con un commento in questo ticket è difficile per chi mantiene tenere tutto in ordine. Sono sicuro che apprezzeranno.

@p43b1 concordo, ma forse sarebbe meglio cominciare a costruire la wiki?

**Comment by ambr89** [comment]
@daemonPainter concordo su tutto!

**Comment by umbros** [comment]
Grazie per la collaborazione, il dato tamponi è suscettibile di riconteggi. Suggerisco di vedere il dato casi testati
