### ISSUE TITLE
Problema nel campo data dovuto al cambio di orario?

### ISSUE THREAD

**Issue by EmilianoBruni** [pcm-dpc/COVID-19#414]
Tipo di issue:

- [ X] Dati mancanti o errati 
- [ ] Errore nella documentazione 
- [ ] Errore or mancanza nella dashboard 
- [ ] Problemi di visualizzazione nella dashboard 

## Riassunto

Tenendo conto che il campo data dovrebbe essere in UTC, oggi il campo data riporta

"data": "2020-03-29T17:00:00"

che sono le 19 ora italiana.

Non dovrebbe essere

"data": "2020-03-29T16:00:00"?

**Comment by umbros** [comment]
Ciao @EmilianoBruni,
il campo orario è solo indicativo dell'orario di processamento
