### ISSUE TITLE
Applicazione di visualizzazione per Android

### ISSUE THREAD

**Issue by ant9000** [pcm-dpc/COVID-19#415]
Ho sviluppato un semplice visualizzatore del dataset delle regioni, in Flutter. Se può essere interessante, non ho problemi a rendere pubblico il codice - o a cederlo a voi per farne qualsiasi uso.

Antonio Galea

**Comment by Staturn2020** [comment]
potresti inviarmelo ?

**Comment by ant9000** [comment]
Ben volentieri, ma GitHub non me lo lascia allegare.

**Comment by ant9000** [comment]
Ho pubblicato il codice, sotto licenza GPLv3, qui:

   https://github.com/ant9000/COVID19Italia

Una release binaria per Android è disponibile qui:
 
   https://github.com/ant9000/COVID19Italia/releases/download/v1.0/covid19italia.apk

Il progetto è scritto in Flutter, quindi lo stesso codice dovrebbe funzionare anche per creare una app su iOS - ma non dispongo di un sistema Apple per compilarlo e verificare.

Antonio Galea

**Comment by helloer00** [comment]
Salve io ho scritto una app per iOS che legge e visualizza i dati della protezione civile. Se volete vi invio il progetto.

**Comment by umbros** [comment]
Grazie a tutti per la collaborazione
