### ISSUE TITLE
Tamponi Emilia Romagna

### ISSUE THREAD

**Issue by lucalazzaris** [pcm-dpc/COVID-19#416]
Possibile non siano stati fatti tamponi in Emilia Romagna? il dato da ieri a oggi non è cambiato
Grazie.

**Comment by DisherProject** [comment]
Stando a quanto [comunica](https://www.regione.emilia-romagna.it/notizie/attualita/coronavirus-aggiornamento-29marzo) la regione: _"oggi, per un problema tecnico, non è disponibile l’aggiornamento sul numero esatto dei test effettuati"_. Penso che in assenza del dato si sia riportato quello del giorno prima.

**Comment by Tantormai** [comment]
E che oggi siano diminuiti di 2,000 unità rispetto al 28 Marzo?

**Comment by umbros** [comment]
Ciao, Regione Emilia Romagna ha comunicato che riconteggiando i tamponi c'è stato un errore di calcolo, il dato odierno è quello attuale.

**Comment by lucalazzaris** [comment]
Ciò che servirebbe è, oltre all’attuale, conoscere come sono distribuiti
gli incrementi, nei giorni scorsi. Ciò al fine di confrontarli
correttamente coi nuovi positivi. Grazie.



Luca Lazzaris

Elastica s.r.l.

http://elastica.eu

tel +39 051 221411



*Da:* Umberto Rosini <notifications@github.com>
*Inviato:* lunedì 30 marzo 2020 20:01
*A:* pcm-dpc/COVID-19 <COVID-19@noreply.github.com>
*Cc:* lucalazzaris <lucalazzaris@elastica.eu>; Author <
author@noreply.github.com>
*Oggetto:* Re: [pcm-dpc/COVID-19] Tamponi Emilia Romagna (#416)



Ciao, Regione Emilia Romagna ha comunicato che riconteggiando i tamponi c'è
stato un errore di calcolo, il dato odierno è quello attuale.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/pcm-dpc/COVID-19/issues/416#issuecomment-606151816>, or
unsubscribe
