### ISSUE TITLE
Grafici per Regioni e Province

### ISSUE THREAD

**Issue by amadvance** [pcm-dpc/COVID-19#417]
Per chi è interessato, ho creato una raccolta di grafici per regione e provincia.

E' online a questo indirizzo: https://amadvance.github.io/covid19-italy/

Il repository è https://github.com/amadvance/covid19-italy

**Comment by FedericoStra** [comment]
+1 per il grafico "crescita vs. totale casi"

**Comment by armando-basile** [comment]
Per la Campania ho creato questo partendo sempre dai csv su questo repositorio
[https://covid-campania.integrazioneweb.com](url)

**Comment by amadvance** [comment]
Solo per segnalare che ho aggiunto a https://amadvance.github.io/covid19-italy/ le stime future del proseguimento dell'epidemia ultilizzando lo strumento di calcolo https://it.mathworks.com/matlabcentral/fileexchange/74658-fitviruscovid19

**Comment by FedericoStra** [comment]
@amadvance Fantastico!

**Comment by umbros** [comment]
Grazie @amadvance
