### ISSUE TITLE
File di configurazione per Logstash (ELK)

### ISSUE THREAD

**Issue by markdevil87** [pcm-dpc/COVID-19#418]
**Tipo di richiesta**: suggerimento di miglioramento (documentazione, label, _ecc_)

## Riassunto

File di configurazione per l'import dei file con Logstash

## Interesse pubblico

Per chi ne avesse bisogno, ho creato un file di configurazione per l'import dei dati giornalieri con Logstash indicizzandoli su Elasticsearch per poterli graficare con Kibana.

Lo script importa i file giornalieri dalle directory:
* dati-province
* dati-regioni
* dati-andamento-nazionale

Di seguito il link al repository:
https://github.com/markdevil87/COVID-19-italy-elk

**Comment by umbros** [comment]
Grazie mille per il contributo @markdevil87
