### ISSUE TITLE
Dati inconsistenti Calabria 23/03

### ISSUE THREAD

**Issue by mzanrosso** [pcm-dpc/COVID-19#419]
Dati presi dai file “andamento regionale” 
Errore regione “Calabria” colonna “totale_decessi”:

Il 22/03 il totale dei morti ammontava a 8
Il 23/03 ammontava a 7
Il 24/03 ammontava a 10

Chiaramente il totale dei morti non può diminuire da un giorno all’altro

**Comment by umbros** [comment]
Ciao @mzanrosso grazie della segnalazione.
Confermiamo che è il dato inviato da Regione Calabria, controlliamo l'accaduto.

**Comment by DisherProject** [comment]
Casomai potesse servire, la regione indicava 7 decessi per il 22/03 ([bollettino](https://www.regione.calabria.it/website/portaltemplates/view/view.cfm?17176))
