### ISSUE TITLE
Dashboard - Rendering dei "Totale positivi" e "attualmente positivi" incongruenti

### ISSUE THREAD

**Issue by danielegaliffa** [pcm-dpc/COVID-19#42]
Nella [dashboard appena pubblicata](http://opendatadpc.maps.arcgis.com/apps/opsdashboard/index.html#/b0c68bce2cce478eaac82fe38d4138b1) sembrava esserci un refuso sul totale dei positivi (5,833) che è il dato di ieri.

![Screenshot (182)](https://user-images.githubusercontent.com/785619/76168092-7a091800-616c-11ea-9dbf-0254299fe27a.png)

Ho poi notato che c'è stato un aggiornamento, ma i nuovi dati sembrano non essere consistenti (attualmente positivi: 5,061 mentre prima erano 6,387.

![Screenshot (184)](https://user-images.githubusercontent.com/785619/76168097-842b1680-616c-11ea-902b-51e8e1cfaa91.png)

Sbaglio ad interpretare qualcosa?

**Comment by danielegaliffa** [comment]
Ora pare che il bug sia stato fixato

![Screenshot (185)](https://user-images.githubusercontent.com/785619/76168144-0b788a00-616d-11ea-936b-37e601692877.png)

**Comment by umbros** [comment]
Ciao @Daniele, eravamo in aggiornamento, grazie comunque per la segnalazione.
