### ISSUE TITLE
CSVs to DB

### ISSUE THREAD

**Issue by davide83** [pcm-dpc/COVID-19#420]
I published a BASH script that requires csvkit as Gist.
I'm using it to Import from github.com/pcm-dpc/COVID-19 the CSV files as tables into an SQLite database then deploy the DB file to Metabase to do some analytics.

Here the link to the Gist:
https://gist.github.com/davide83/2299c1aa3d6468bb092d11b460655078

I hope it could be useful for some of you that need a DB as source.

The next step should be to implement a sort of GitHub Actions to automize this job.

Let free to use, share, fork and contribute!

**Comment by MarcoGermani** [comment]
Auguri

**Comment by davide83** [comment]
Fyi,

I recently published a project that daily import the CSV data files as tables into an database from this repository and save it into an Sqlite3 DB file.

https://github.com/davide83/COVID19-DB

I hope it could helpful for someone.


###
PS. Grazie a tutte e tutti per il vostro straodinario contributo e impegno in ogni emergenza!
###

**Comment by alessiosavi** [comment]
Questo le salva su influxdb solo quando avvengono commit sulla repo.

https://github.com/alessiosavi/COVID-19_graphs
