### ISSUE TITLE
Aggiungere sezione progetti Open Source correlati

### ISSUE THREAD

**Issue by SimoneTinella** [pcm-dpc/COVID-19#422]
**Tipo di richiesta**:  suggerimento di miglioramento 

## Riassunto

Salve,
sarebbe possibile aggiungere una sezione all'interno della wiki o readme generale dove elencare i progetti che la community realizza usando i dati da voi forniti?

Noto che vengono spesso aperte issues relative a nuove dashboard o app mobile sviluppate (io stesso ne ho realizzata una ma non ho aperto l'issue), sarebbe comodo avere un elenco così da poter scoprire cosa ha realizzato la community e chi ha offerto un contributo. 

Grazie.

## Interesse pubblico

Rendere facilmente accessibili i progetti a supporto sviluppati dalla community.

**Comment by umbros** [comment]
Ciao @SimoneTinella,
stiamo pensando al fatto di mettere una sezione CONTRIBUTOR.
