### ISSUE TITLE
Stringa invece di numero nel JSON Dati nazionali

### ISSUE THREAD

**Issue by floatingpurr** [pcm-dpc/COVID-19#424]
Tipo di issue:

- [x] Dati mancanti o errati 
- [ ] Errore nella documentazione 
- [ ] Errore or mancanza nella dashboard 
- [ ] Problemi di visualizzazione nella dashboard 

Dati nazionali

## Riassunto

Nel file https://github.com/pcm-dpc/COVID-19/blob/master/dati-json/dpc-covid19-ita-andamento-nazionale.json è riportato un numero come una stringa

`"totale_casi": "101739",`

**Attesa:**

`"totale_casi": 101739,`

**Attuale:**

**Comment by Datalux** [comment]
Anche nel file https://github.com/pcm-dpc/COVID-19/blob/master/dati-json/dpc-covid19-ita-andamento-nazionale-latest.json

**Comment by umbros** [comment]
Corretto,
grazie.

**Comment by alexodus** [comment]
> Corretto,
> grazie.

possiamo darvi una mano a gestire bene gli script che utilizzate?
Perché pare che gestiate a mano. Vedi errore dell'altro giorno.

**Comment by alexodus** [comment]
I dati voi li avete molti minuti prima.....fare un check sui dati che mandate in giro sarebbe opportuno (ed evita che le app e dashboard realizzate vadano a ramengo). Altrimenti se mettete sempre dati sbagliati (2 errori in 3 giorni) l'utilità di questa servizio viene meno
