### ISSUE TITLE
dpc-covid19-ita-regioni-20200330 valori

### ISSUE THREAD

**Issue by bagaini** [pcm-dpc/COVID-19#428]
dpc-covid19-ita-regioni-20200330.csv ha numerose regioni con valori negativi di "nuovi_attualmente_positivi" . Ad esempio, Lombardia, = -386

Tipo di issue:

- [ ] Dati mancanti o errati 
- [ ] Errore nella documentazione 
- [ ] Errore or mancanza nella dashboard 
- [ ] Problemi di visualizzazione nella dashboard 

- Regione:
- Provincia: 

## Riassunto

**Attesa:**

**Attuale:**

**Comment by Tantormai** [comment]
E' corretto.
In Lombardia oggi sono stati rilevati 1,154 nuovi casi, ma 1,082 persone sono guarite e 458 sono decedute, quindi oggi risultano 386 persone infette meno di ieri.

**Comment by berna1995** [comment]
Però a questo punto c'è un problema, perchè chiamare il record _nuovi_attualmente_positivi_ se è semplicemente la differenza col giorno prima? Come facciamo a sapere quanti sono i tamponi positivi su quelli fatti?

**Comment by umbros** [comment]
Stiamo risolvendo e gestendo la questione grazie.

**Comment by danielesalpietro** [comment]
@berna1995 , prendi il numero e mettiti in fila ed attendi, sono settimane e decine di post che evidenziamo il problema, ma per ora "a loro" va bene così.....

**Comment by Tantormai** [comment]
I nuovi casi rilevati oggi sono dati da:
totale_casi(di oggi) - totale_casi(di ieri)
In realtà, però, i due numeri suddetti sono gli esiti dei tamponi registrati nel giorno, ma non necessariamente eseguiti in quel giorno. I dati provinciali, infatti, evidenziano la presenza di un certo numero di casi "in fase di definizione" che sono già contabilizzati nel totale_casi di quel giorno.

**Comment by berna1995** [comment]
Quelli dunque non sono i nuovi positivi registrati, è il delta dei positivi totali del giorno i-esimo e il giorno i-1-esimo. Il nome _nuovi_attualmente_positivi_ a mio avviso è fuorviante.
