### ISSUE TITLE
Numero negativo in 'Nuovi attualmente positivi' della regione Lombardia

### ISSUE THREAD

**Issue by MattRighetti** [pcm-dpc/COVID-19#429]
https://github.com/pcm-dpc/COVID-19/blob/149ebb079d38f08e7433476ce2c9f9fa44ff5ff2/dati-json/dpc-covid19-ita-regioni-latest.json#L194

**Comment by umbros** [comment]
Ciao,
stiamo lavorando sul dato. grazie della segnalazione

**Comment by FedericoStra** [comment]
@MattRighetti Niente di sorprendente: evidentemente sono guarite/morte più persone di quante sono state contagiate. `nuovi_attualmente_positivi = nuovi_contagi - nuove_guarigioni - nuove_morti` è il bilancio dei malati, quindi può essere negativo.
