### ISSUE TITLE
Format error in dati-province/dpc-covid19-ita-province-20200308.csv

### ISSUE THREAD

**Issue by miccoli** [pcm-dpc/COVID-19#43]
`casi_totali` should be `totale_casi` in header

**Comment by pigreco** [comment]
![image](https://user-images.githubusercontent.com/7631137/76169339-7b8c0d80-6177-11ea-913c-dc8a4648f01d.png)

https://github.com/pcm-dpc/COVID-19/blob/master/dati-province/dpc-covid19-ita-province.csv#L1666

**Comment by umbros** [comment]
Grazie per la segnalazione! Corretto!

**Comment by miccoli** [comment]
As per https://github.com/pcm-dpc/COVID-19/blob/6101ff61043d91b22bf63f1f8694c5ba005efcf6/dati-province/dpc-covid19-ita-province-20200308.csv#L1 the bug is still here, please reopen

**Comment by miccoli** [comment]
@umbros please, when you close an issue, reference the commit e.g. f44c14af7f75871d4cd9ee045b49f6036e48c9fd which is supposed to solve the problem. This will speedup checking if the issue was treated properly.
