### ISSUE TITLE
Tamponi Emilia Romagna errati

### ISSUE THREAD

**Issue by Frengos23** [pcm-dpc/COVID-19#430]
valore ultimi 4 giorni 47798 52991 52991 50990
Oggi avremmo -2001, il che è impossibile 
Grazie

**Comment by umbros** [comment]
Ciao, il dato dei tamponi è un cumulativo. Stiamo controllando il dato di emilia romagna.

**Comment by gpinnaan** [comment]
Scusate la richiesta di precisione ma l'issue andrebbe chiuso quando viene risolto. L'errore nei tamponi é ancora presente e anche se si é presa visione andrebbe lasciato aperto. O mi sbaglio?
