### ISSUE TITLE
Nuovi positivi negativi in più regioni

### ISSUE THREAD

**Issue by ftornaboni** [pcm-dpc/COVID-19#431]
Ciao, 

Per i dati del 30 marzo oltre che, come già segnalato, in Lombardia hai dei numeri negativi anche in Friuli, Umbria e Valle D'Aosta.

ps. 
Grazie per il lavoro che stai facendo

**Comment by umbros** [comment]
Ciao @ftornaboni stiamo lavorando a questo aspetto, ma confermiamo la correttezza dei dati. Grazie

**Comment by FedericoStra** [comment]
@ftornaboni Niente di sorprendente: evidentemente sono guarite/morte più persone di quante sono state contagiate. `nuovi_attualmente_positivi = nuovi_contagi - nuove_guarigioni - nuove_morti` è il bilancio dei malati, quindi può essere negativo.
