### ISSUE TITLE
error

### ISSUE THREAD

**Issue by ilante** [pcm-dpc/COVID-19#432]
Hello there,

#This site has your repo listed as their source of data: 
https://www.worldometers.info/coronavirus/country/italy/ 

Comparing the daily new cases in Italy reported in your table - I saw that the numbers **do not match**. 

Maybe there is a glitch? 

The source listed (you) is: 
https://github.com/pcm-dpc/COVID-19/blob/master/dati-andamento-nazionale/dpc-covid19-ita-andamento-nazionale-latest.csv 

It says that on **March 30 2020** there where **nuovi_attualmente_positivi** 
(new cases of today) **1648**. 
The table on worldometers however shows **+4,050**. 
This is a number nowhere to be found in the table of your source on your repo.
It would be sad if the whole world thinks you had twice as much cases than actually true.

![Screen Shot 2020-03-30 at 20 29 52](https://user-images.githubusercontent.com/44288547/77948164-429e0f00-72c5-11ea-856d-0f9aee9041c5.png)

Here it states again the date and the differing number
![Screen Shot 2020-03-30 at 20 31 11](https://user-images.githubusercontent.com/44288547/77948290-7ed16f80-72c5-11ea-98e2-545002055adb.png)

Have a nice evening,
Greetings ilante

**Comment by floatingpurr** [comment]
**4,050** is the variation of the **total cases** (i.e., _totale_casi_) compared to the previous day

**1,648** is the variation of the **active cases** (i.e., _totale_attualmente_positivi_) compared to the previous day

**Comment by umbros** [comment]
Hi @ilante the new_cases calculated by worldometers is not the date "nuovi_attualmente_positivi" that is totale_attualmente_positivi (today) - totale_attualmente_positivi (yesterday) for us is just a variation, to better align our data tomorrow we will introduce new_positives in our dataset.
