### ISSUE TITLE
Incongruenza dati bollettino puglia con dati regionali

### ISSUE THREAD

**Issue by giocaputo** [pcm-dpc/COVID-19#433]
Incongruenza con i dati del bollettino regionale puglia.

http://www.regione.puglia.it/news;jsessionid=2D249D75A3CC01076838934DCDB50CE4?p_p_auth=JYAq0Bea&p_p_id=56_INSTANCE_8oLBj0XOEEsq&p_p_lifecycle=0&p_p_state=normal&p_p_mode=view&p_p_col_id=column-2&p_p_col_count=3&_56_INSTANCE_8oLBj0XOEEsq_articleId=51297750&_56_INSTANCE_8oLBj0XOEEsq_groupId=3728079&_56_INSTANCE_8oLBj0XOEEsq_version=1.0&_56_INSTANCE_8oLBj0XOEEsq_categoryName=BOLLETTINO+EPIDEMIOLOGICO+REGIONE+PUGLIA+30%2F03%2F2020&_56_INSTANCE_8oLBj0XOEEsq_back=%2Fweb%2Fguest%2Fcoronavirus%2Faggiornamenti

**Comment by umbros** [comment]
Ciao @giocaputo il dato di Regione Puglia, molto probabilmente, ha un aggiornamento successivo all'orario di conferimento del dato a noi tramite Ministero della Salute. Grazie della segnalazione.
