### ISSUE TITLE
Significato e anomalie campo NUOVI POSITIVI

### ISSUE THREAD

**Issue by Lorenzo-Mira** [pcm-dpc/COVID-19#434]
Il dato "nuovi positivi" è negativo in Lombardia nei giorni 10 mar (già annotato come "dati incompleti") e 30 Mar, in cui assume valore -386. Tali valori sono coerenti con la variazione dei casi attualmente positivi, che infatti diminuiscono. Tuttavia non si spiegano con l'andamento di "totale casi" al netto di deceduti e guariti. Più in generale nella stessa data il numero di casi totali Lombardia aumenta di circa mille unità, che è incompatibile con un numero negativo di nuovi casi, che anzi al netto di guariti e deceduti dovrebbe essere maggiore. La stampa in modo appropriato riprende il delta giornaliero dei "casi totali" chiamandoli nuovi contagi.

Tipo di issue:

- [x ] Dati mancanti o errati 
- [ ] Errore nella documentazione 
- [ ] Errore or mancanza nella dashboard 
- [ ] Problemi di visualizzazione nella dashboard 

- Regione:
- Provincia: 

## Riassunto

**Attesa:**

**Attuale:**

**Comment by umbros** [comment]
Ciao @Lorenzo-Mira, abbiamo appena ora caricato nel README l'aggiornamento di domani dove verrà chiarito il senso del campo a cui fai riferimento e il nuovo campo "nuovi_positivi" che verrà introdotto da domani

**Comment by Lorenzo-Mira** [comment]
Eccellente, grazie per il lavoro incredibilmente utile che state facendo

Il mar 31 mar 2020, 00:07 Umberto Rosini <notifications@github.com> ha
scritto:
