### ISSUE TITLE
Coerenza dati Abruzzo 30/3

### ISSUE THREAD

**Issue by DataEnthusiast84** [pcm-dpc/COVID-19#435]
**Tipo di richiesta**:  richiesta di informazione 

## Riassunto

In data 30/03 per l'Abruzzo risultano:

1.169 positivi (incremento rispetto al giorno precedente: 0)
1.345 casi totali (incremento rispetto al giorno precedente: +52)
391 ospedalizzati (incremento rispetto al giorno precedente: -6)
778 in isolamento domiciliare (incremento rispetto al giorno precedente: +6)
102 deceduti (incremento rispetto al giorno precedente: +14)
74 guariti (incremento rispetto al giorno precedente: +38)

La mia domanda è: Se il 30/3 sono "usciti" dal sistema 52 pazienti (14 deceduti + 38 guariti), e il numero dei positivi è lo stesso (1.169), perchè il numero di casi totali si incrementa di 52?

Mi spiego meglio: le categorie "decessi" e "guariti" sono a cascata rispetto agli ospedalizzati e isolamento domiciliare (cioè il flusso dati prevede che i pazienti transitino prima nelle categorie "ospedalizzati" e "isolamento domiciliare" e poi da lì in sequenza in "guariti" o "decessi") oppure si può verificare che i decessi e le guarigioni avvengano indipendentemente dal fatto che i pazienti transitino o meno nelle categorie "ospedalizzati" o "isolamento domiciliare"?

 

-->

## Interesse pubblico

Lettura corretta dei dati

**Comment by DisherProject** [comment]
> La mia domanda è: Se il 30/3 sono "usciti" dal sistema 52 pazienti (14 deceduti + 38 guariti), e il numero dei positivi è lo stesso (1.169), perchè il numero di casi totali si incrementa di 52?

Significa che nello stesso giorno sono risultati positivi ai test esattamente 52 individui. Se 52 persone "escono" dal conteggio e in 52 vi "entrano", ecco che il totale dei _positivi_ rimane invariato, ma il numero _totale_ di casi deve aumentare.

> Mi spiego meglio: le categorie "decessi" e "guariti" sono a cascata rispetto agli ospedalizzati e isolamento domiciliare (cioè il flusso dati prevede che i pazienti transitino prima nelle categorie "ospedalizzati" e "isolamento domiciliare" e poi da lì in sequenza in "guariti" o "decessi") oppure si può verificare che i decessi e le guarigioni avvengano indipendentemente dal fatto che i pazienti transitino o meno nelle categorie "ospedalizzati" o "isolamento domiciliare"?

Sono per la tua prima spiegazione. Penso che per essere messo nel conto dei "guariti" o "decessi" devi essere stato sottoposto al tampone, e quindi essere stato conteggiato tra gli ospedalizzati o tra chi è messo in quarantena. Ci sono stati casi di tamponi fatti post mortem, ma allora sarebbero almeno stati aggiunti al totale.
