### ISSUE TITLE
Example of use of your data and request for english translations of all columns

### ISSUE THREAD

**Issue by mvanreek** [pcm-dpc/COVID-19#436]
Hi,

First of all, I think you did a great job making your country's COVID19-data 'open data', I don't know of any other country in EU who did that, at least not Spain and Netherlands, where the COVID19-data was published as open data (so on Github) by the public ('volunteers). 
I wrote a blog-post about these open data sets and yours, and used them to create a PowerBI-report 'Deaths in IT, ES and NL', see:

https://worktimesheet2014.blogspot.com/2020/03/covid-19-analysis-of-number-of-deaths.html

One suggestion to make your data even more open (for international use):
could you add in your wiki the english translations of all columns, and a short description of the content of each file.

Thanks, and keep up the good work you are doing!

ANDRÀ TUTTO BENE!

regards,

Maarten van Reek

**Comment by umbros** [comment]
@mvanreek thank you, we are preparing a wiki and tomorrow the wiki will be online. At @12:00 we will do an update on dataset.

**Comment by mvanreek** [comment]
I checked, but couldn't find it,could you share the (English) wiki page please?

**Comment by fabriziomiano** [comment]
> I checked, but couldn't find it,could you share the (English) wiki page please?

Have a look here
https://covidashit.herokuapp.com/

I went ahead and translated the 11 series of data myself. 
Hope this helps. 

Cheers

**Comment by mvanreek** [comment]
Thanks #fabriziomiano. 
I added your link on my latests blog-post: 
[https://worktimesheet2014.blogspot.com/2020/03/covid-19-analysis-of-number-of-deaths.html](https://worktimesheet2014.blogspot.com/2020/03/covid-19-analysis-of-number-of-deaths.html)
