### ISSUE TITLE
Previsioni sull'incremento dei positivi nei prossimi giorni

### ISSUE THREAD

**Issue by gianlab** [pcm-dpc/COVID-19#437]
Come si vede dalla previsione sull'andamento dell'incremento dei casi positivi giornalieri fatta tramite il modello ARIMA non è possibile in questo momento stabilire se si avrà un andamento crescente o decrescente di tale incremento. Questo nonostante nell'ultimo giorno, come si vede dal grafico precendente, l'incremento dei nuovi positivi sia passato da 3815 del 29 marzo a 1648 del 30 marzo:

https://www.kaggle.com/gianlab/previsioni-ed-esplorazione-dati-covid-19-italia

**Comment by umbros** [comment]
Grazie mille peri il contributo @gianlab

**Comment by danielesalpietro** [comment]
@gianlab  qualsiasi previsione fatta su questi dati è inattendibile al fine di fare previsioni, perché i dati forniti dalle regioni sono "parziali", le informazioni arrivano dagli ospedali i quali contano solo ciò che passa da loro, tutti gli altri casi ( e sono molti ) oggi non vengono minimamente presi in considerazione (neppure i dati che provengono dai medici di famiglia vengono consolidati a livello di regione). Secondo me, questi dati hanno  senso solo per valutare quanto una struttura ospedaliera (regionale) è sotto stress, ma una volta raggiunto il numero massimo di pazienti gestibili, tutti gli altri restano "non gestiti" e seguono un iter, purtroppo, fuori controllo. Quindi il fatto che ci siano meno "nuovi_positivi" spesso significa che quella struttura non è più in grado di gestire di più....ma non che non ci siano più nuovi positivi o siano in misura inferiore ai giorni precedenti. Anche la questione tamponi è un fritto misto di "intepretazioni", basta pensare che per un paziente potrebbe fare più tamponi (da 2 a 10 o più) nell'arco di tutto il periodo che resta "ospedalizzato" o a domicilio per controllare come evolve il virus. Inoltre manca qualsiasi dato relativamente all'età dei pazienti, quindi per ora si tratta di numeri e basta.
