### ISSUE TITLE
Nomi colonne - Incremento Giornaliero Attualmente Positivi

### ISSUE THREAD

**Issue by pistillo-alessandro** [pcm-dpc/COVID-19#438]
- [ ] Errore or mancanza nella dashboard

## Riassunto
Continuate a chiamarlo "Incremento Giornaliero Attualmente Positivi". Il nome era corretto, anche se non rappresentava i "Nuovi Positivi". La parola "Attualmente" faceva capire che si riferiva ad una situazione temporanea, prima di passare nell'altra categoria Morti/Guariti.
Il numero degli "Attualmente Positivi" aumenta con i nuovi contagiati, ma d'altra parte ogni giorno diminuisce con guariti o dei decessi.

Sono d'accordo con la decisione rendere disponibile il dato "Nuovi positivi".
Questo numero non è più influenzato da quante persone muoiono o guariscono. Quindi giustamente non fa distinzione tra le sottocategorie Morti/Guariti/AttualmentePositivi.
Ma di fatto il suo nome potrebbe essere "Variazione Totale Positivi"

In questo provo a dare una spiegazione dei vari nomi, e fasi:
https://www.linkedin.com/posts/alessandro-pistillo-44b5853a_sanitaeqpubblica-istruzione-machinelearning-activity-6650354100007391232-4pfG

**Comment by umbros** [comment]
Ciao @pistillo-alessandro grazie mille per la segnalazione, domani rilasceremo il wiki dove spiegheremo bene tutta la semantica dei dati. Chiamiamo nuovi positivi per uniformità ai naming internazionali.
