### ISSUE TITLE
The file dpc-covid19-ita-province.json has one wrong date

### ISSUE THREAD

**Issue by matteopelagatti** [pcm-dpc/COVID-19#44]
If you look at the file "dpc-covid19-ita-province.json" converted into a data frame, you will see that at record 1665 the field "data" contains the word "data" instead of the date "2020-03-08 18:00:00".
Thanks for your work.
Best,
Matteo

**Comment by miccoli** [comment]
Maybe related to #43, since I assume that `.json` is generated from csv data.

**Comment by xfranky** [comment]
Then maybe also related to #45, likely due to a differently formatted source file from which the csv was populated

**Comment by umbros** [comment]
Grazie per la segnalazione! Corretto.
