### ISSUE TITLE
Tamponi Emilia Romagna

### ISSUE THREAD

**Issue by camposanto95** [pcm-dpc/COVID-19#440]
Ciao, il totale dei tamponi in ER di 3 gg fa e 2 gg fa è uguale poichè mancavano i 3.5k comunicati successivamente durante la conferenza. Secondo i dati di ieri però il totale è diminuito, da 52k (55.5k circa aggiungendo i 3.5k) a 50k. Ci sta un errore di scrittura?

**Comment by umbros** [comment]
Ciao @camposanto95 il totale dei tamponi attuali è quello corretto, hanno avuto un problemi sui conteggi risolto ieri.
