### ISSUE TITLE
Campo totale_attualmente_positivi sparito?

### ISSUE THREAD

**Issue by plucky81** [pcm-dpc/COVID-19#441]
**Tipo di richiesta**:  richiesta di informazione | richiesta di dati | suggerimento di miglioramento (documentazione, label, _ecc_) | relativo alla pagina grafica

**Comment by dan88v** [comment]
È stato rinominato in "totale_positivi".

> - Modifica: "totale_attualmente_positivi" rinominato in "totale_positivi" (ricoverati_con_sintomi + terapia_intensiva + totale_ospedalizzati) in "dati_regioni" and "dati_andamento_nazionale"

**Comment by plucky81** [comment]
Sì ho appena notato dall'History. Scusate.
Grazie.
