### ISSUE TITLE
Numero tamponi necessario per regione.

### ISSUE THREAD

**Issue by biomichele** [pcm-dpc/COVID-19#443]
Ciao,
spero qualcuno possa aiutarmi e mi scuso se faccio qualche errore, ma è la prima volta.
Vorrei capire se questi dati possono aiutarmi a conoscere quale sarà la necessità di test da effettuare per singola regione nei prossimi giorni.
Questo aiuterebbe a distribuire al meglio i test che per ovvie ragioni sono disponibili in misura limitata e eviterebbe di distribuire troppi test a regioni che al momento non necessitano di cosi tanti test quanti ne chiedono.
Ho analizzato i dati e credo che indicatori importanti siano il numero di persone attualmente positive e il numero di test effettuati giornalmente (considerando che molte persone devono rifare il test più volte fino a quando non risultino negativi). Se se calcola il rapporto numero test/numero positivi possiamo capire se il numero di test è il fattore limitante e  in qualche modo vada a saturazione, se cosi mi aspetto che debbano aumentare il numero di test giornaliero per intercettare tutti i positivi.
Il rapporto di positivi su non positivi (es: 1 positivo su 3 test fatti) aiuta ma non so quale sia il limite per dire che i test sono a saturazione.
Spero sia stato sufficientemente chiaro nella spiegazione.
Mi piacerebbe avere la vostra opinione e eventualmente qualche suggerimento.

Grazie mille a tutti e complimenti per il lavoro che state svolgendo.

**Comment by danielesalpietro** [comment]
Credo che ogni regione abbia indicato quanti test al giorno sono in grado di fare/garantire (es. lombardia 5.000; in ogni caso, lo si può ricavare con buona approssimazione dai dati storici: tamponi_giornalieri= tamponi (n) - tamponi (n-1);

ora cosa altro sappiamo?
a) sappiamo quanti nuovi_casi al giorno per ciascuna regione vengono confermati e sappiamo anche che servono 2 tamponi positivi per avere la sicurezza della positività; 

b) sappiamo anche che il 10% sono falsi positivi (errore del sistema di analisi molecolare usato);

c) che per avere conferma della negatività servono comunque 2 tamponi (e questo vale sia per chi è ospedalizzato, ma anche per chi è in isolamento/quarantena;

d) che tutti i medici/infermieri e forze dell'ordine dovrebbero fare il tampone almeno una volta al giorno (meglio due) ? 

e) che non basta disporre dei tamponi, ma servono anche i reagenti (cosa per altro ultimamente difficilmente reperibili, tutto il mondo è alla ricerca di questi prodotti e si combattono battaglie senza frontiere per accaparrarseli, così come per le mascherine ed i respiratori);

f) che anche se si esce dall'ospedalizzazione, i casi più gravi restano "altamente contagiosi" per 2 settimane; il che mi fa supporre che per avere una certezza, (prima di tornare in libertà) qualcuno dovrebbe verificare con altri 2 tamponi (mal contanti quindi ogni positivo dovrebbe aver bisogno da 2 a 8-10 tamponi nell'arco di 40/60 giorni.

g) che se prendessimo per esempio la lombardia, con 5.000 tamponi al giorno, ho sentito Fontana dichiarare che per fare anche una sola tamponatura a tutta la popolazione lombarda, servirebbero 3 anni !!!

h) che è inutile fare il tampone a chi ha già avuto il virus (asintomatico) da più di 2-4 settimane, queste persone hanno nel sangue gli anticorpi e quindi sarebbero tutte persone che potrebbero tornare al lavoro (o potrebbero dare una mano essendo (forse) immuni a nuovi contagi ?)

ora, se la regione lombardia può contare su 5000 tamponi al giorno (sempre che abbia tutto il necessario e le macchine possano lavorare 7 giorni su 7; personale compreso); immagino che le altre regioni possano contare su un numero giornaliero più basso (ma andrebbe verificato con i numeri e fonti alla mano);

Quindi, non ho la risposta che cercavi, ma qualche idea su come trovarla forse si....

**Comment by biomichele** [comment]
Grazie mille per le informazioni utili. Ci sono punti in più da considerare.
Il limite dei test in questo momento sono i reagenti che purtroppo non sono prodotti in quantità sufficienti ed è quindi necessario allocarli al meglio.
Conoscere il limite oltre il quale un aumento dei test non porti nessun vantaggio aiuterebbe le aziende a lavorare meglio con le regioni. Io faccio parte di una di queste e stiamo provando in ogni modo a ottimizzare questo aspetto. Sopratutto serve per oggettivare ad alcune regioni il fatto che non possiamo fornire le quantità che chiedono e che in alcuni casi sono estremamente alte.
Proverò a incrociare i dati e tirare fuori qualcosa di sensato.
