### ISSUE TITLE
Possibile errore dati in definizione/aggiornamento provincie/Liguria

### ISSUE THREAD

**Issue by gidiemme72** [pcm-dpc/COVID-19#444]
Nel file dpc-covid19-ita-province.csv, per la regione LIGURIA i numeri "in fase di definizione/aggiornamento" sono in decisa crescita di giorno in giorno (ultimo dato 1422, più di Lombardia e Veneto...). Come mai?
Mi viene il dubbio che siano comunicati oppure trascritti in modo erroneamente cumulato...

**Comment by gidiemme72** [comment]
Aggiornamento:
ieri (01/04/2020) il dato "in fase di definizione/aggiornamento" per la Liguria è esattamente pari alla somma dei tot casi delle 4 provincie GE+IM+SP+SV =1.830.
Qualcuno può verificare la congruità di tale dato?
Non è inverosimile che solo in Liguria ci sia un tale numero di casi non ancora assegnati ad alcuna provincia?

**Comment by username02** [comment]
O magari, se c'è qualche ragione per cui in Liguria (e solo in Liguria) i casi non assegnati ad alcuna provincia superano addirittura quelli assegnati, potrebbe valer la pena di darne indicazione in qualche nota.
Ma non se ne trova traccia da nessuna parte.
Mi scuso se insisto con il quesito: non c'è davvero margine di errore nei dati riportati o nelle trascrizioni, relativamente a questa regione?
