### ISSUE TITLE
Array nel json regioni

### ISSUE THREAD

**Issue by LBreda** [pcm-dpc/COVID-19#446]
Sul JSON regioni viene aperto un array in riga 15878 senza che abbia significato semantico:

https://github.com/pcm-dpc/COVID-19/blob/31424492495da7173577e2d73781a1f9087339f0/dati-json/dpc-covid19-ita-regioni.json#L15878

**Comment by cairomassimo** [comment]
Confermo il problema.
Però è il JSON delle regioni, non le province (titolo errato)

**Comment by LBreda** [comment]
> Però è il JSON delle regioni, non le province (titolo errato)
Molto vero, ho corretto.

**Comment by umbros** [comment]
Corretto, grazie a tutti.
