### ISSUE TITLE
errore formato dpc-covid19-ita-regioni.json

### ISSUE THREAD

**Issue by fabriziomiano** [pcm-dpc/COVID-19#447]
Tipo di issue:

- [X] Dati mancanti o errati in `dpc-covid19-ita-regioni.json`
- Regione: tutte

## Riassunto
L'elemento successivo a questo, e' un array invece che un altro dizionario / oggetto
```
    {
        "data": "2020-03-30T17:00:00",
        "stato": "ITA",
        "codice_regione": 5,
        "denominazione_regione": "Veneto",
        "lat": 45.43490485,
        "long": 12.33845213,
        "ricoverati_con_sintomi": 1633,
        "terapia_intensiva": 356,
        "totale_ospedalizzati": 1989,
        "isolamento_domiciliare": 5575,
        "totale_positivi": 7564,
        "variazione_totale_positivi": 313,
        "nuovi_positivi": 366,
        "dimessi_guariti": 747,
        "deceduti": 413,
        "totale_casi": 8724,
        "tamponi": 99941,
        "note_it": "",
        "note_en": ""
    }
```

**Comment by alexodus** [comment]
OH MIO DIO!!! SEMPRE GLI STESSI ERRORI!!!! Ragazzi della protezione civile,  fare un JSON è facillissimo. STATE FACENDO IMPAZZIRE TUTTI QUELLI CHE PRENDONO I DATI DA QUESTO REPOSITORY GITHUB.

**Comment by floatingpurr** [comment]
Confermo problema su JSON. Potrebbe convenire prendere i dati in formato CSV? Sono più stabili?

**Comment by irvelervel** [comment]
Confermo il problema

**Comment by psonic** [comment]
Confermo.

**Comment by umbros** [comment]
@alexodus abbiamo cambiato i tracciati e c'è stato un semplice errore di parsing. Stiamo correggendo

**Comment by fabriziomiano** [comment]
Grazie mille @umbros per il lavoro che fate. Siete dei grandi!

**Comment by andreamag00** [comment]
Anche per me i dati regione danno errore; grazie PC per il lavoro che fare e per star correggendo
