### ISSUE TITLE
Dati per provincia 20200308 errati

### ISSUE THREAD

**Issue by xfranky** [pcm-dpc/COVID-19#45]
Nei dati per provincia del 20200308, ho riscontrato i seguenti problemi:
- Diversi dati del totale casi sono associati alla provincia sbagliata (e.g. Padova e Vicenza in Veneto)
- La Provincia di Forlì-Cesena è scritta con l'apostrofo invece dell'accento

PS complimenti per l'iniziativa :)

**Comment by skebby11** [comment]
Segnalo che anche per la provincia 035 (Reggio nell’Emilia), risultano dati incongruenti nel json rispetto al PDF. Grazie.

**Comment by LorenzoInvernizzi92** [comment]
Aggiungo:

- Bergamo presenta 53 casi totali, quando il giorno prima aveva 761 casi

**Comment by dbaroncelli** [comment]
Prato risulta avere 24 casi, quando ieri ne aveva 3. C'è qualche errore.

**Comment by xfranky** [comment]
Comunque sembra che tutti i dati siano rimescolati solo tra province all'interno della stessa regione.

**Comment by LorenzoInvernizzi92** [comment]
se avviene un'estrazione automatica dei dati dal file https://github.com/pcm-dpc/COVID-19/blob/master/schede-riepilogative/province/dpc-covid19-ita-scheda-province-20200308.pdf allora non è avvenuta correttamente.

**Comment by mateonunez** [comment]
Segnalo anche che la provincia di codice 12 (varese) presenta 997 casi

**Comment by xfranky** [comment]
> se avviene un'estrazione automatica dei dati dal file https://github.com/pcm-dpc/COVID-19/blob/master/schede-riepilogative/province/dpc-covid19-ita-scheda-province-20200308.pdf allora non è avvenuta correttamente.

Non credo sia quello il caso, visto che nel PDF Forlì è scritta con l'accento, mentre nei dati errati di oggi è venuto fuori con l'apostrofo

**Comment by dbaroncelli** [comment]
in questa vostra dashboard, i dati delle province sono corretti:
http://arcg.is/C1unv
attingete quindi a fonti diverse?

**Comment by fprofiliARS** [comment]
confermo, dati per provincia errati per 8 marzo

**Comment by pigreco** [comment]
https://github.com/pcm-dpc/COVID-19/blob/master/dati-province/dpc-covid19-ita-province.csv#L1666

![image](https://user-images.githubusercontent.com/7631137/76169358-a8d8bb80-6177-11ea-9703-64cfaf450671.png)

**Comment by umbros** [comment]
Grazie delle segnalazioni. Corretto!
