### ISSUE TITLE
Dati province 31/03/2020 uguali a 30/03/2020

### ISSUE THREAD

**Issue by emazep** [pcm-dpc/COVID-19#452]
* I dati delle province odierni (31/03/2020) sono gli stessi di ieri (30/03/2020).
* presenza di righe spurie nel file CSV (valore "In fase di definizione/aggiornamento" nella colonna denominazione_provincia).

Il file è:

https://github.com/pcm-dpc/COVID-19/blob/master/dati-province/dpc-covid19-ita-province.csv

**Comment by alexodus** [comment]
Fanno sempre gli stessi errori. E non vogliono aiuto dall'esterno. Hanno fatto 3 errori in 4 giorni e non possiamo quindi avere degli script automatici.

**Comment by umbros** [comment]
@alexodus abbiamo cambiato i tracciati ed è un semplice errore di script. Non è questione di aiuto.
Grazie @emazep

**Comment by danielesalpietro** [comment]
@emazep  la variazione dei dati si aggira in percentuale a 1-3% da 3-4 giorno, non credo che si stia appiattendo la curva dei contagi, a me sembra invece che abbiamo raggiunto il massimo della capacità che le strutture ospedaliere possono gestire, se questo è vero, dovremo attendere un aumento degli ospedalizzati non appena aumenteranno i posti letto nella terapia intensiva o nei reparti dove vengono gestiti i casi meno "gravi".....nel frattempo tempo che stiano aumentando i decessi "a casa" che nessuno conteggia perché non fanno parte dei decessi di casi ospedalizzati.

**Comment by emazep** [comment]
@danielesalpietro immagino ti stia riferendo alle mie considerazioni pubblicate su https://www.facebook.com/StatisticheCovid19

Se così fosse, sarebbe meglio rispondere lì ;-)

In ogni caso sia le terapie intensive che le ospedalizzazioni totali sono in continua discesa (in valore assoluto) da quasi un mese, quindi ormai siamo ben lontani da qualsiasi ipotesi di saturazione delle risorse ospedaliere (ad oggi ci sono appena 1501 terapie intensive, vale a dire poco più di un terzo del valore di picco e forse un sesto della capacità totale) e nondimeno la percentuale sugli attualmente positivi continua a scendere, peraltro avvicinandosi ad un valore limite (circa l'1,5%) che indicherebbe chiaramente una relazione strutturale, allo stato delle attuali terapie.
