### ISSUE TITLE
VI SERVE UN SUPPORTO!

### ISSUE THREAD

**Issue by alexodus** [pcm-dpc/COVID-19#454]
## Riassunto
Ragazzi, diciamocelo in tutta franchezza: state gestendo malissimo questo repo github.
Si vede lontano un miglio che non avete uno script serio e con i test di validazione.
Penso che la community degli sviluppatori potrebbe tranquillamente darvi una mano.
Negli 4 giorni avete fatto 3 errori e questo diventa un casino per tutti coloro (anche nel mondo) che devono prendere i dati da questo repository. 
Vi chiedo l'umiltà di accettare aiuti esterni: non facciamoci riconoscere dall'esterno come dei peracottari, su!!!!

**Comment by umbros** [comment]
@alexodus grazie del tuo commento. Ti invito a rispettare i codici di comportamento.
Grazie

**Comment by tehKapa** [comment]
è possibile che il dato comunicato possa essere stato comunicato erroneamente o altre motivazioni.
