### ISSUE TITLE
Error in file dpc-covid19-ita-regioni.json in 31th of march

### ISSUE THREAD

**Issue by SamanFekri** [pcm-dpc/COVID-19#455]
Type of issue:

- [x] Incorrect or missing data : dpc-covid19-ita-regioni.json
- [ ] Incorrect or missing documentation 
- [ ] Incorrect or missing data in the dashboard 
- [ ] Layout problem in the dashboard 

- Region:
- Province: 

## Summary

31st march is array instead of being JSON object for each province

**Expected:**
the 31st of march we expect a JSON object for each province

**Actual:** 
Now we get an array for 31st of march and that array contains JSON object for each province

**Comment by umbros** [comment]
It's ok now thank you
