### ISSUE TITLE
Nome campi latitudine longitudione inconsistenti

### ISSUE THREAD

**Issue by leoniDEV** [pcm-dpc/COVID-19#456]
Tipo di issue:

- [x] Dati mancanti o errati 
- [ ] Errore nella documentazione 
- [ ] Errore or mancanza nella dashboard 
- [ ] Problemi di visualizzazione nella dashboard 

- Regione: https://github.com/pcm-dpc/COVID-19/blob/master/dati-regioni/dpc-covid19-ita-regioni-20200331.csv
- Provincia: 

## Riassunto
Nome campi lat e long nel CSV dei dati regionali della data del 31/03 inconsistenti con gli altri files

**Attesa:** lat, long

**Attuale:**  latitudine, longitudine

**Comment by umbros** [comment]
Corretto grazie
