### ISSUE TITLE
Bug formato json dpc-covid19-ita-regioni.json

### ISSUE THREAD

**Issue by mydozer** [pcm-dpc/COVID-19#457]
Tipo di issue:

- [ ] Dati mancanti o errati dpc-covid19-ita-regioni.json

## Riassunto
Riga 15878

        "totale_casi": 8724,
        "tamponi": 99941,
        "note_it": "",
        "note_en": ""
    **},
    [
        {**
            "data": "2020-03-31T17:00:00",
            "stato": "ITA",
            "codice_regione": 13,
            "denominazione_regione": "Abruzzo",
            "latitudine": 42.35122196,
            "longitudine": 13.39843823,
            "ricoverati_con_sintomi": 335,
            "terapia_intensiva": 73,
            "totale_ospedalizzati": 408,
            "isolamento_domiciliare": 783,
            "totale_positivi": 1191,
            "variazione_totale_positivi

**Attesa:**

**Attuale:**

**Comment by umbros** [comment]
Grazie della segnalazione. Corretto.
