### ISSUE TITLE
Dato "variazione_totale_positivi" negativo nel file "dpc-covid19-ita-regioni.csv" riga 746

### ISSUE THREAD

**Issue by FrancescoLoro** [pcm-dpc/COVID-19#458]
Tipo di issue:

- [X] Dati mancanti o errati 
- [ ] Errore nella documentazione 
- [ ] Errore or mancanza nella dashboard 
- [ ] Problemi di visualizzazione nella dashboard 

- Regione: Lombardia
- Provincia: 

## Riassunto

**Attesa:**

**Attuale:**

**Comment by umbros** [comment]
Corretto, quella è una variazione del dato totale positivi, abbiamo aggiunto i nuovi positivi che invece è la differenza tra totali casi di oggi - totale casi di ieri
