### ISSUE TITLE
Add 'deaths' to data by Province

### ISSUE THREAD

**Issue by pmeridian** [pcm-dpc/COVID-19#459]
**Richiesta di dati**: 
## Summary

add also deaths and possibly recovered for the data by province in additional to 'totale_casi'

## Public interest

Allows to do a detailed study of the mortality in specific regions comparing official deaths with data from 'anagrafe'

**Comment by magaspari** [comment]
See issue #378 you will find some data there, unfortunately not all the regions transmit this information. They actually should do it!

**Comment by pmeridian** [comment]
Thanks. I’ve checked the data from @cassiudders.

**Comment by cassiudders** [comment]
@pmeridian we are still digging. sadly every region do different work
