### ISSUE TITLE
Emilia-Romagna VS Emilia Romagna

### ISSUE THREAD

**Issue by DataEnthusiast84** [pcm-dpc/COVID-19#460]
Tipo di issue:

- [ ] Dati mancanti o errati 
- [X] Errore nella documentazione 
- [ ] Errore or mancanza nella dashboard 
- [ ] Problemi di visualizzazione nella dashboard 

- Regione: Emilia Romagna
- Provincia: 

## Riassunto

Emilia-Romagna per il 31/3 è stata codificata come Emilia Romagna (senza il trattino). Questo porta ad errori in anagrafica per chi usa il nome della Regione.

**Attesa:**

Correzione per il 31/3 dell'etichetta Emilia Romagna in Emilia-Romagna

**Attuale:**

**Comment by umbros** [comment]
Ciao @DataEnthusiast84 ho controllato ed è tutto decodificato con il trattino, dove hai trovato l'errore?

**Comment by bellaceragit** [comment]
Ciao @umbros, forse non hai capito il commento di @DataEnthusiast84: la modifica fatta da ieri a oggi sulla regione "Emilia-Romagna" crea problemi a chi, per esempio, ha archiviato il nome "Emilia Romagna", e non "Emilia-Romagna", nei propri database.

**Comment by umbros** [comment]
Ciao @bellaceragit,
era un'attività di normalizzazione prevista anche perchè la Regione Emilia-Romagna si scrive con il trattino quindi è giusto riportare l'esatta denominazione. Stiamo mettendo su un sistema di notifiche di prossime release delle informazioni in modo da tenere tutti aggiornati.
