### ISSUE TITLE
Modifiche effettuate alla struttura files .csv

### ISSUE THREAD

**Issue by rickymazzo** [pcm-dpc/COVID-19#461]
Buonasera, mi chiedevo fosse possibile ripristinare la struttura dei files .csv che è stata portata avanti fino a 2 giorni fa (29 Marzo 2020).
I files .csv attuali contengono modifiche strutturali. Queste stanno causando l'impossibilità di aggiornare il mio progetto.

**Comment by umbros** [comment]
Buonasera @rickymazzo abbiamo comunicato ieri sera la modifica che è volta ad una maggiore informazione avendo introdotto i nuovi positivi che era un dato richiesto sebbene calcolabile, se vuoi tenere la struttura devi semplicemente eliminare la colonna nuovi positivi e, se ragioni a nome colonna, rinominare le colonne come scritto nel changelog.

**Comment by bellaceragit** [comment]
Sì ma non è efficiente: non immagino quante persone che seguono questi dati oggi dovranno impiegare (t = Npersone * Ntempo) per aggiornare i propri databases.

**Comment by umbros** [comment]
Ciao @bellaceragit stiamo mettendo su un sistema per notificare modifiche prima di farle. Capisco la problematica ma penso che sia anche importante manutenere il dato. :)
