### ISSUE TITLE
Emilia Romagna aggiunta trattino

### ISSUE THREAD

**Issue by jacklapinza** [pcm-dpc/COVID-19#464]
E' stato aggiunto un trattino tra "Emilia-Romagna" che prima non c'era, questo potrebbe causare diversi problemi a chi ha implementato il codice dando per scontato che i nomi delle regioni non avrebbero subito variazioni.

**Comment by anbened** [comment]
Rientra nelle modifiche comunicate sul README.md:

Modifica: Regione "Emilia Romagna" rinominato in "Emilia-Romagna" in "dati-regioni" e "dati-province" ("denominazione_regione")

Attenzione, che sono state fatte anche altre modifiche:

Modifica: "totale_attualmente_positivi" rinominato in "totale_positivi" (ricoverati_con_sintomi + terapia_intensiva + isolamento domiciliare) in "dati_regioni" e "dati_andamento_nazionale"

Modifica: "nuovi_attualmente_positivi" rinominato in "variazione_totale_positivi" (totale_attualmente positivi giorno corrente - totale_attualmente positivi giorno precedente) in "dati_regioni" e "dati_andamento_nazionale"

Aggiunta: "nuovi_positivi" (totale_casi giorno corrente - totale_casi giorno precedente) in "dati_regioni" e "dati_andamento_nazionale"

**Comment by umbros** [comment]
Grazie @anbened,
@jacklapinza nella fretta avevamo denominato Emilia-Romagna senza trattino all'inizio ma il nostro consiglio è di far riferimento alle coordinate e codici regione/provincia.
