### ISSUE TITLE
dati province  toscana  27 mar e nuova colonna regioni

### ISSUE THREAD

**Issue by filipporigacci** [pcm-dpc/COVID-19#465]
Apparentemente nei csv relativi alle province del giorno 27 marzo 2020 i dati relativi alle province toscane sono identici a quelli del giorno precedente. E' un errore o i dati sono davvero identici? Grazie.
Inoltre mi permetto di suggerire, nel caso di aggiunta di nuove colonne nei tracciati csv, come per esempio accaduto oggi nel tracciato csv delle regioni, di farlo in coda al singolo tracciato in modo da non inficiare la pubblicazione di chi gestisce il dato csv in modo posizionale.
Grazie per il lavoro che state facendo.

**Comment by DisherProject** [comment]
> Apparentemente nei csv relativi alle province del giorno 27 marzo 2020 i dati relativi alle province toscane sono identici a quelli del giorno precedente. E' un errore o i dati sono davvero identici?

Per quanto riguarda il tuo dubbio, i dati per quel giorno non erano disponibili. Puoi dare uno sguardo qui #409

**Comment by filipporigacci** [comment]
grazie
