### ISSUE TITLE
Codice regione Provincie autonome Trento e Bolzano

### ISSUE THREAD

**Issue by cicoph** [pcm-dpc/COVID-19#469]
**Tipo di richiesta**:  suggerimento di miglioramento

## Riassunto
Sarebbe meglio dare alle provincie autonome di Trento e Bolzano un codice regione differente visto che vengono stampati all'interno del dataset delle regioni.

## Interesse pubblico

In questo modo le mappe interattive in geojson possono essere più pulite a livello di codice
Grazie :)

**Comment by pierluigicara** [comment]
La nostra scelta è stata fin dall'inizio di aderire alla codifica ISTAT. Questo nel caso delle due PA di Trento e Bolzano effettivamente stride un po', nel senso che ISTAT fa riferimento alla Regione Trentino Alto-Adige, ma trattandosi di questioni relative alla salute, la materia è di competenza delle province autonome e quindi la Regione non entra in gioco. Non possiamo però, malgrado questa discrepanza, attribuire codici regioni non ISTAT.
