### ISSUE TITLE
Dashboard con redash.io

### ISSUE THREAD

**Issue by alessandrocaprarelli** [pcm-dpc/COVID-19#47]
Ciao,

i dati json qui pubblicati possono essere usati per creare delle viste in redash.io in maniera molto semplice. 
Qui un'esempio che ho creato in 30 minuti al massimo: https://app.redash.io/covid-italia/public/dashboards/cAtrICNP1OyqPqL6M85tYoY3dnXreF4kMM5VzcjZ.

Si potrebbero creare delle dashboard per avere una visione d'insieme dei vari dati.

**Comment by brucellino** [comment]
non per minimizzare l'impegno, ma potresti spiegare quale beneficio _aggiunga_ avere un'altro dashboard? I data sono gli stessi, non sono arrichiti in alcun modo, vero? Mi sfugge sicuramente dei dettagli...

Forse sarebbe il caso di avere un documento con dei collegamenti a contributi di questo tipo aggiunto al repo? 

_e.g._ 

```markdown
<!-- CONTRIBUTING.md --> 

If you have created a derivative work (dashboard and would like to include a reference to it here, please open an issue using the "derivative work" issue template, and it could be added to the list below

## Derivative works

- 
```

Si potrebbe aggiungere un issue template come descritto per aiutare i maintainer a decidere se includere o meno.
