### ISSUE TITLE
Analisi dei dati covid-19

### ISSUE THREAD

**Issue by francescobianca** [pcm-dpc/COVID-19#470]
Volevo ringraziarvi per i dati che postate ogni giorno e del grande lavoro che state svolgendo!

Ho fatto una piccola analisi dei dati e provato a tirar fuori un modello di previsione futura studiando modelli con le caratteristiche della "**Exponential & logistic growth**".  L'ho fatto più per un'esercitazione di data visualization ed ml. Se vi va di dare uno sguardo vi lascio il link alla repo:

https://github.com/francescobianca/Covid-19-Italy-DataAnalysis

**Comment by Rabelaiss** [comment]
Bel lavoro! Se riesci prova anche il modello SIR per aumentare la precisione.

**Comment by francescobianca** [comment]
Ciao grazie mille! Avevo utilizzato un qualcosa simile in un altro progetto universitario. In quel caso avevo implementato questo in Python [Spread_of_influence](https://github.com/francescobianca/Mining-Evolving-Topics/blob/master/sapienza/first_task/spread_of_influence_algorithm.py). Proverò ad effettuare queste modifiche allora!

**Comment by umbros** [comment]
Grazie @francescobianca  e grazie a tutti per i contributi, presto chiederemo di fare una raccolta dei lavori come contributor e li elencheremo. Grazie

**Comment by amadvance** [comment]
@Rabelaiss Grazie del link! Ho integrato quel modello nei grafici di: https://amadvance.github.io/covid19-italy/

**Comment by maxdevblock** [comment]
@francescobianca molto bello! complimenti!
Sto provando anche io a fare qualche analisi, ma non essendo un matematico i miei strumenti sono piuttosto limitati, mi fare piacere avere un tuo parere
https://github.com/maxdevblock/covid-19-italy
grazie :-)

**Comment by francescobianca** [comment]
Ciao @maxdevblock no anzi bel lavoro! Se vuoi badare anche alla forma visiva ti consiglio di utilizzare [plotly](https://plotly.com/) per i grafici! Io ho appena inserito anche dati mondiali e realizzato un grafico animato che mostra l'evoluzione del virus a livello globale (se ti va dai un occhiata sul mio colab)

**Comment by RickySal** [comment]
@maxdevblock Confermo quanto detto da @francescobianca , bel lavoro e si, plotly è un ottimo strumento. Io ho realizzato grafici di regioni e province con Plotly ed è fantastico perchè permette una semplice navigazione tra i dati ed una integrazione altrettanto semplice.

[graficicovid19.org](graficicovid19.org)

**Comment by maxdevblock** [comment]
Grazie @francescobianca e @maxdevblock per i consigli. Tutti strumenti nuovi per me plotly e colab. Direi che ho tempo per studiarli con calma :-)
Dove trovo il tuo colab?

**Comment by francescobianca** [comment]
[Repo](https://github.com/francescobianca/Covid-19-Italy-DataAnalysis) sul realdme c'è un tasto open in colab!

**Comment by alessandroAmedei** [comment]
Qui trovate una mia dashboard https://covid19-alessandroamedei.firebaseapp.com/ , spero possa essere utile!

**Comment by Rabelaiss** [comment]
Previsioni giornaliere del numero di contagi (nuovi e totali) per ciascuna regione Italiana, per l'italia e per il mondo, effettuate con modello logistico e modello SIR.
https://www.facebook.com/groups/PrevisioniCoronaVirus/

**Comment by maxdevblock** [comment]
@francescobianca ah sì certo questo lo avevo visto, pensavo avessi tipo un account con altri lavori (sto dando un'occhiata a plotly ma non ho ancora iniziato con colab :blush:)

**Comment by maxdevblock** [comment]
@francescobianca sono riuscito finalmente a trovare il modo di interpolare (quasi) tutti i dati di tutte le regioni italiane sulla gaussiana.
https://www.maxpierini.it/ncov/covid-italy-regions-forecast.html

su GItHub, la repo con il codice
https://github.com/maxdevblock/covid-19-italy/blob/master/covid-italy-regions-forecast.ipynb

Il problema era che la funzione `curve_fit` di `scipy.optimize`, con pochi dati e molto dispersi, ha bisogno di parametri iniziali ipotizzati `p0` che si avvicinino il più possibile ai parametri che descrivono la curva.

**Comment by Paulsword** [comment]
@maxdevblock @francescobianca Complimenti per i vostri lavori. Posso chiedervi se avete considerato il problema del numero di guariti, nel quale in questa repository pare non siano inclusi i guariti a casa che non sono passati per l'ospedale (o quanto meno il dato sembra molto disomogeneo tra le regioni)? Grazie mille

**Comment by maxdevblock** [comment]
> @maxdevblock @francescobianca Complimenti per i vostri lavori. Posso chiedervi se avete considerato il problema del numero di guariti, nel quale in questa repository pare non siano inclusi i guariti a casa che non sono passati per l'ospedale (o quanto meno il dato sembra molto disomogeneo tra le regioni)? Grazie mille

Ciao, grazie.
Non sono sicuro che nei `dimessi_guariti` non siano contemplati anche i guariti da `isolamento_domiciliare`. Chiediamo a @umbros
