### ISSUE TITLE
Dati errati per PROVINCIA ISERNIA alla data 2020-03-28T17:00:00

### ISSUE THREAD

**Issue by roncolat** [pcm-dpc/COVID-19#471]
Tipo di issue:

- [x] Dati mancanti o errati 
- [ ] Errore nella documentazione 
- [ ] Errore or mancanza nella dashboard 
- [ ] Problemi di visualizzazione nella dashboard 

- Regione: MOLISE
- Provincia: ISERNIA

## Riassunto
La serie di TOTALE_CASI per questa provincia è errata per il giorno 28 Marzo. Infatti è dal 26 Marzo che sono registrati sempre 9 casi.

**Attesa:**

Al giorno indicato la tabella dovrebbe essere 9 casi totali 

**Attuale:** 
Al giorno indicato la tabella riporta 13 casi totali 

Un saluto! Complimenti per il servizio.

**Comment by umbros** [comment]
Ciao @roncolat questi sono i dati comunicati da Regione Molise, eventuali differenze potrebbero dipendere da errori di conteggio.

**Comment by roncolat** [comment]
Caro Umberto,

sono assolutamente d’accordo con te. Ti segnalo una seconda incongruenza per la provincia di Imperia, che ti riporto qui sotto:

[cid:image003.png@01D60907.BDB560D0]

Come è possibile che i casi TOTALI di una PROVINCIA diminuiscano? Per un dato singolo come quello di ISERNIA penso che sia un errore di trascrizione, ma per la provincia di IMPERIA penso che qualcosa non torni. Nell’ultima colonna della tabella sopra si vede infatti che i casi totali al giorno 28 Marzo sono 236. Poi, il giorno successivo diminuiscono, poi aumentano, e poi diminuiscono.

A mio parere è un dato che deve sempre aumentare o rimanere costante.

Mi puoi cortesemente confermarmi che è corretta l’assunzione scritta in grassetto?

Un cordiale saluto!

Carlo Roncolato
35020 Albignasego (PD)
Da: Umberto Rosini<mailto:notifications@github.com>
Inviato: mercoledì 1 aprile 2020 23:35
A: pcm-dpc/COVID-19<mailto:COVID-19@noreply.github.com>
Cc: Carlo Roncolato<mailto:croncolato@hotmail.com>; Mention<mailto:mention@noreply.github.com>
Oggetto: Re: [pcm-dpc/COVID-19] Dati errati per PROVINCIA ISERNIA alla data 2020-03-28T17:00:00 (#471)


Closed #471<https://github.com/pcm-dpc/COVID-19/issues/471>.
