### ISSUE TITLE
Suggerimento per nomenclatura

### ISSUE THREAD

**Issue by maxdevblock** [pcm-dpc/COVID-19#472]
**Tipo di richiesta**: suggerimento di miglioramento della nomenclatura

## Riassunto

La attuale nomenclatura
`totale_positivi`
`variazione_totale_positivi`
`nuovi_positivi`
`totale_casi`
è fuorviante (`nuovi_positivi` si riferisce alla variazione sul `totale_casi` e `variazione_totale_positivi` ai riferisce alla variazione sul `totale_positivi`) e potrebbe generare incomprensioni nell'eventualità di un prossimo utilizzo di test estesi differenti da quello comunemente chiamato _tampone_.

Il nome `positivi` si riferisce ovviamente all'_essere positivi a un test_.
Se parliamo del tampone, questo indica che il soggetto è _attualmente infetto_ ovvero che è stato contagiato e non è né deceduto, né guarito.
Ma effettuando, ad esempio, un test sugli anticorpi, essere _positivo_ significherebbe semplicemente _essere stato contagiato_ a prescindere dall'eventuale guarigione.

Mi permetto quindi di suggerirvi di modificare la nomenclatura in
`totale_casi` -> invariato `totale_casi`
`nuovi_positivi` -> `nuovi_casi` o `variazione_totale_casi`
in riferimento ai contagi (casi) totali avvenuti che, ad esempio, potrebbero essere anche definiti attraverso test differenti dal tampone, quale appunto il test degli anticorpi, a prescindere dall'attuale condizione (infetto vivo, guarito vivo, deceduto)
e
`totale_positivi` -> `totale_infetti`
`variazione_totale_positivi ` -> `nuovi_infetti` o `variazione_totale_infetti`
in riferimento agli attuali soggetti vivi infetti, non guariti.

## Interesse pubblico

La definizione di una nomenclatura univoca e chiara può preparare il repository ad accogliere nuove informazioni, derivanti da altri possibili strumenti diagnostici utilizzati in un prossimo futuro, e faciliterebbe molto l'analisi dei dati.

PS: grazie per il Vostro lavoro!

**Comment by umbros** [comment]
Ciao @maxdevblock,
https://github.com/pcm-dpc/COVID-19/wiki/1.it-Dati:-andamento-nazionale
Mi dai riscontro se è chiaro come specificati i campi? ad esempio di andamento nazionale.

Grazie

**Comment by RickySal** [comment]
Scusate l'intromissione, chiedo gentilmente se modifiche di questo tipo (che possono equivalere a modifiche di interfacce software) possono essere notificate con congruo anticipo in maniera tale da permettere un fluido funzionamento di tutti i servizi dipendenti dai vostri dati. Grazie e scusate ancora.

**Comment by maxdevblock** [comment]
> Ciao @maxdevblock,
> https://github.com/pcm-dpc/COVID-19/wiki/1.it-Dati:-andamento-nazionale
> Mi dai riscontro se è chiaro come specificati i campi? ad esempio di andamento nazionale.
> 
> Grazie

Ciao @umbros 
certo sì, i dati sono sicuramente consistenti, nel senso che i calcoli nella colonna *Standard/Calcolo* corrispondono.

Il suggerimento era riferito all'attuale dibattito scientifico sul numero reale di contagi totali come qui
https://www.imperial.ac.uk/media/imperial-college/medicine/sph/ide/gida-fellowships/Imperial-College-COVID19-Europe-estimates-and-NPI-impact-30-03-2020.pdf
e qui
https://science.sciencemag.org/content/early/2020/03/24/science.abb3221
e all'aver notato che la Protezione Civile e la regione Lombardia chiedono di compilare un questionario anonimo sullo stato di salute ed eventuale contatto con soggetti infetti.
Immagino dunque che si tenderà, in un prossimo futuro, a cercare di definire non solo i casi conclamati (ospedalizzati o in isolamento) ma il totale dei contagi.

In quest'ottica, suggerivo che `totale_positivi` (attualmente = `totale_ospedalizzati` + `isolamento_domiciliare`) potrebbe generare confusione nel caso si trovassero altri metodi per definire gli infetti (anche pauci/a-sintomatici, non ospedalizzati) e i contagiati (guariti che sono stati infetti, pauci/a-sintomatici, non ospedalizzati, non in isolamento domiciliare).

Ma come dice @RickySal effettivamente è forse meglio trovare nuove nomenclature nel caso di nuovi dati, invece di modificare l'attuale.

Grazie della risposta tempestiva :)

**Comment by RickySal** [comment]
Beh in ogni caso non voglio bloccare nessuna modifica eh sia chiaro. Personalmente sono disposto a modificare una riga di codice, basta saperlo per tempo però, altrimenti si rischiano disservizi. Sarebbe utile a tal scopo creare un file che notifichi con almeno 24 ore di anticipo tali modifiche.

**Comment by umbros** [comment]
Ciao,
la modifica di ieri ha avuto una tempestività maggiore ma normalmente nel changelog in italiano e inglese mettiamo le modifiche future con le date. Riguardo il questionario di Regione Lombardia è un'iniziativa di Regione Lombardia. Qui mettiamo dati che sono necessari all'attività del Dipartimento della Protezione Civile Nazionale. Comunque ogni suggerimento è sempre il benvenuto e terremo sicuramente in conto il vostro. Grazie
