### ISSUE TITLE
Errore morti Veneto

### ISSUE THREAD

**Issue by cassiudders** [pcm-dpc/COVID-19#475]
- [ ] Dati mancanti o errati - dpc-covid19-ita-regioni-20200401.csv 

- Regione: Veneto

I morti totali del Veneto sono 489 e non 499, come da report regionale delle 17 che al solito è la fonte del vostro aggiornamento

[https://www.ilgiornaledivicenza.it/filedelivery/policy:7.2744251:1585758387/aggiornamento%20casi%20-%20e%20ricoveri%201.4%20ore%2017.00.pdf.pdf?mobile_stay=1](url)

**Comment by umbros** [comment]
Ciao @cassiudders questi sono i dati comunicati dal veneto.

**Comment by cassiudders** [comment]
ciò non toglie che c'è un errore....o dite che fra le 17 e le 18 sono morte dieci persone????

**Comment by cassiudders** [comment]
@umbros magari domani fate un check col report della regione....anticipare dei morti sembra poco produttivo oltre che malaugurante
grazie comunque del lavoro che svolgete
