### ISSUE TITLE
Aiuto su file

### ISSUE THREAD

**Issue by MilosVf** [pcm-dpc/COVID-19#476]
Ciao, innanzitutto complimenti per il lavoro, davvero molto belloIn questi gironi mi sto addentrando nella visualizzazione di vari dati, in particolare delle regioni italiane. Questo è uno dei pochi file con le regioni, sto cercando di creare una mappa con folium stile choropleth ma non riesco a capire dove sto sbagliando visto che non mi viene.  Il problema è la mancanza della key_on... potresti dirmi se c'è una soluzione o il file non è semplicemente adatto per questo?

Grazie mille

**Comment by downFast** [comment]
@MilosVf usa leaflet https://leafletjs.com/examples/choropleth/

**Comment by umbros** [comment]
grazie @downFast per il supporto!
