### ISSUE TITLE
Brutta cosa la censura

### ISSUE THREAD

**Issue by MarcoGermani** [pcm-dpc/COVID-19#477]
@umbros 
Gentile Rosini,
non vedo più l'argomento che avevo aperto ieri dove lamentavo errori sui dati della Lombardia. Forse era scomodo ed è stato eliminato ?

Le ricordo che attendo ancora una risposta sulla progressione dei tamponi in Lombardia dal 24 al 27 febbraio che dovrebbe essere una serie crescente. 

Saluti

**Comment by MarcoGermani** [comment]
@heyteacher
Non ritiene che i dati debbano essere corretti o secondo lei possono darci dati a caso?

**Comment by gpinnaan** [comment]
Anche i dati dei tamponi dell'Emilia Romagna hanno degli errori e dopo che lo si é fatto notare l'issue é stato chiuso dicendo che effettivamente c'era un errore da controllare che poi però non é stato corretto. Ormai analizzare questi dati puó essere massimo un passatempo privo di scopo

**Comment by MarcoGermani** [comment]
La responsabilità non è di chi pubblica ma da chi coordina che dovrebbe dimettersi

**Comment by danielesalpietro** [comment]
Effettivamente controllando il numero # di Issue in stato "Open" e Closed , si evince che gli amministratori "spesso" censurano le richieste; immagino possano dare una spiegazione? forse i contenuti sono OT ? mi auguro che sia così, non potrei comprendere un motivo diverso altrimenti.

**Comment by MarcoGermani** [comment]
Non sono Off Topic ma scomodi. Prima mi hanno dato del Troll poi mi hanno accusato di incompetenza poi non sapendo cosa rispondere alle mie corrette analisi dei dati hanno cancellato la discussione come faranno con questa. E' VERGOGNOSO !

**Comment by umbros** [comment]
Ciao, vengono cancellate semplicemente le issue che non sono issue e quindi a scopo collaborativo e che non rispettano il codice di condotta pubblicati. Non c'è nulla di scomodo @MarcoGermani , non avremmo messo trasparentemente i dati, quindi ti invito nuovamente a rispettar eil codice di condotta. Grazie.

**Comment by umbros** [comment]
Aggiungo che relativamente ai dati essendo in un momento di emergenza possono esserci degli errori di comunicazione e ritardi che potrebbero comportare errore sulle serie e su questo c'è sempre stata massima trasparenza.
