### ISSUE TITLE
campo "nuovi positivi" negativo

### ISSUE THREAD

**Issue by fcaruso** [pcm-dpc/COVID-19#478]
## Grafici su andamento e diffusione - "nuovi positivi" negativi

Ho implementato e messo a disposizione delle funzioni python per creare grafici sulla diffusione del corona-virus. 
Trovate ulteriori informazioni a questo [link](fcaruso.github.io/coronavirus_diffusion.html)
A volte il valore dei nuovi positivi è negativo...non capisco come interpretare questo dato.
Ringrazio anticipatamente per l'eventuale chiarimento e, soprattutto, per il lavoro che state facendo!

**Comment by Rabelaiss** [comment]
Il numero nuovi attualmente positivi NON indica i nuovi malati, bensì la differenza `nuovi malati - nuovi decessi - nuovi guariti`. Quindi indica quante persone in più o in meno rispetto a ieri ci sono negli ospedali e in quarantena.
![aaaa](https://user-images.githubusercontent.com/20670578/78232343-63887f00-74d4-11ea-8ab7-e3a232483202.jpg)

**Comment by umbros** [comment]
Ciao,
non mi risulta che ci siano negativi in nuovi positivi, forse in variazione totali positivi.
Grazie per il contributo.

**Comment by Rabelaiss** [comment]
In realtà c'è un dato negativo per il Piemonte al giorno 2020-02-27, in tale data, infatti, il `totale_casi` passa da 3 a 2.

**Comment by Rabelaiss** [comment]
@umbros in totale ci sono 5 valori negativi nella colonna `nuovi_positivi` del file `dpc-covid19-ita-regioni`:
PIEMONTE
2020-02-27	-1
2020-03-09	-10

LIGURIA
2020-03-01	-17
2020-03-02	-3

SICILIA
2020-03-02	-2
