### ISSUE TITLE
Web App per consultazione nazionale e regionale, unita a consultazione di tutti gli altri paesi 

### ISSUE THREAD

**Issue by dariolr** [pcm-dpc/COVID-19#479]
Salve,

attraverso i vostri dati [json](https://github.com/pcm-dpc/COVID-19/tree/master/dati-json) ho creato una web app per consultare i dati dell'Italia sia a livello nazionale che regionale.

sono presenti anche [dati internazionali](https://github.com/NovelCOVID/API) per una consultazione di tutti i paesi.
per gli Stati Uniti la consultazione è anche a livello statale.

### Interesse pubblico

web app responsive facilmente utilizzabile sia su smartphone che su tablet.

http://dariolr.github.io/covid-19/

**Comment by umbros** [comment]
grazie mille per il contributo @dariolr
