### ISSUE TITLE
Incosistenza tamponi Emilia Romagna

### ISSUE THREAD

**Issue by gpinnaan** [pcm-dpc/COVID-19#480]
Ho letto in un issue chiuso che il numero di tamponi fatto in Emilia-Romagna aveva degli errori che poi sono stati corretti. I valori sono quelli che partono dal 28/03 con  52991 tamponi per poi rimanere uguali come il  29/03  come segnalato nelle news per poi passare a 50990 il 30/03  quinidi con un incremento NEGATIVO di tamponi e gli ultimi 2 giorni avere i valori 54532 e 58457 rispettivamente.  Il problema é che anche se l'ultimo valore risulta corretto quelli precedenti risultano non avere senso. La mia domanda é se é normale che non vengano corretti anche i valori precedenti. Avere i valori corretti dei tamponi é importante per poter correggere l'andamento del numero totale dei casi.

**Comment by umbros** [comment]
@gpinnaan i dati che eroghiamo sono dati giornalieri comunicati dalle Regioni che in questo momento sono totalmente immerse nella gestione dell'emergenza, quindi la scelta è stata quella di prendere i dati comunicati e non modificare a posteriori perchè vorrebbe dire integrare dei processi che appesantirebbero ulteriormente le attività.
