### ISSUE TITLE
info su utilizzo dei dati

### ISSUE THREAD

**Issue by Zaleuco-tech** [pcm-dpc/COVID-19#481]
Buongiorno, 
spero di non essere ot, vorrei sapere se è lecito realizzare una app a scopo informatico, totalmente gratuita priva di quasiasi annuncio pubblicitario e chiaramente non a scopo di lucro, che utilizzi i dati messi a disposizione rappresentandoli con grafici
grazie 
chiedo scusa se sono OT
Achille

**Comment by amadvance** [comment]
Il repository è in licenza CC-BY-4

Questa pagina spiega cosa puoi fare con queta licenza: https://creativecommons.org/licenses/by/4.0/deed.it

Mia interpretazione: In pratica, si. Basta che dici da dove provengono i dati e mostri un link alla licenza.

**Comment by umbros** [comment]
Correttissimo @amadvance, i dati sono totalmente liberi di poter essere utilizzati e lavorati basta citare la fonte.
