### ISSUE TITLE
Numero guariti non in linea con quanto dichiarato da testate giornalistiche

### ISSUE THREAD

**Issue by AlbiBone** [pcm-dpc/COVID-19#482]
**Tipo di richiesta**:  richiesta di informazione

## Riassunto

Ci sono articoli di giornale ([link](https://www.ilpost.it/2020/04/02/guariti-coronavirus-protezione-civile/)) che dichiarano che i `dimessi_guariti`, sono solo coloro che prima erano in ospedale e che ora non non sono più gravi e che quindi vengono dimessi in isolamento casalingo per far posto ad altri malati gravi.
D'altro canto, in accordo con il Wiki di questo repository ([link](https://github.com/pcm-dpc/COVID-19/wiki/1.it-Dati:-andamento-nazionale)), i `dimessi_guariti` sono:
> totale dei casi che risolvono i sintomi dell’infezione da Covid-19 e che risultano negativi in due test consecutivi effettuati a distanza di 24 ore uno dall’altro, per la ricerca di SARS-CoV-2, sulla base della nota del Ministero della Salute n. 0006607 del 29/02/2020

## Interesse pubblico

Fare chiarezza su chi viene conteggiato come `dimessi_guariti`:
-  sia dall'ospedale se son realmente guariti (con i relativi 2 tamponi consecutivi), oppure son malati con sintomi in miglioramento che son dimessi dall'ospedale per liberare spazi utili ad altri pazienti più gravi (ragionevole, visto la saturazione del SSN).
- se vengono fatti tamponi anche alle persone in isolamento a casa (dubito visto la gravità della situazione e la maggior urgenza a fare tamponi per le persone più gravi in ospedale).

**Comment by umbros** [comment]
Ciao, la dicitura esatta è quanto stabilito dalla nota del Ministero della Salute.
