### ISSUE TITLE
[NOT an issue] - COVIdashIT

### ISSUE THREAD

**Issue by fabriziomiano** [pcm-dpc/COVID-19#483]
**This is not an issue** 

Sorry in advance if this is not the appropriate place. I usally don't make this kind of posts in github-issues section, but I've noticed that several people are nicely "advertising" web tools to visualize the data the Civil Protection guys are kindly providing, so I thought I'd give my 2 cents.

## Public interest

As I was browsing the official Civil Protection dashboard I felt like some information was missing and something slimmer and more informative could've been realised. Please, do not take this as criticism towards the official dashboard.
 
I made a simple dashboard using that provides the user with the most relevant information with syntetic cards - for the daily trend - and a chart with **all the data categories** in the JSON data files.
I think people who are curious and want to visualize the general trend could benefit from this dashboard as it extensively goes through all the different categories.

Here is the link of what I called <a href="https://covidashit.herokuapp.com/" target="_blank">COVIdashIT</a>

Feedback / commnts are much appreciated
![image](https://user-images.githubusercontent.com/29355604/78246607-b587cf80-74e9-11ea-92a5-dda4c909dabe.png)

**Comment by umbros** [comment]
Grazie mille per il contributo @fabriziomiano.
