### ISSUE TITLE
App Android Open Source con grafici, istogrammi e statistiche

### ISSUE THREAD

**Issue by SimoneTinella** [pcm-dpc/COVID-19#484]
Chiedo anticipatamente scusa per l'off topic, ma come molti altri offro qui il mio contributo.

## Riassunto

Salve,
per offrire un po' di supporto ho avviato un progetto Open Source (sotto licenza MIT) relativo allo sviluppo di un app nativa per Android dal quale è possibile visualizzare tutti i dati da voi forniti su base nazionale, regionale e provinciale. Ho aggiunto anche alcune misure a cui è possibile risalire dai vostri dati (come i nuovi dimessi guariti e i nuovi deceduti), aggiungendo in fine anche alcune statistiche e la possibilità di visualizzare il tutto attraverso grafici temporali e istogrammi per il confronto fra regioni/province.

Il tutto è disponibile ai seguenti link dove sono presenti anche degli screenshot per una rapida visione (apk incluso)
https://simonetinella.github.io/Stato_COVID19_Italia_Android/
https://github.com/SimoneTinella/Stato_COVID19_Italia_Android

Grazie.

## Interesse pubblico

Fruizione di un pratico strumento per l'accesso ai dati per finiti informativi e di analisi.

**Comment by umbros** [comment]
Grazie per il contributo @SimoneTinella
