### ISSUE TITLE
Mappa Sinottica Bollettino Regione Puglia - disponibilità del numero di contagi per paese

### ISSUE THREAD

**Issue by marcyborg** [pcm-dpc/COVID-19#485]
Il Bollettino della Regione Puglia, ad esempio http://www.regione.puglia.it/news;jsessionid=2D249D75A3CC01076838934DCDB50CE4?p_p_auth=JYAq0Bea&p_p_id=56_INSTANCE_8oLBj0XOEEsq&p_p_lifecycle=0&p_p_state=normal&p_p_mode=view&p_p_col_id=column-2&p_p_col_count=3&_56_INSTANCE_8oLBj0XOEEsq_articleId=51297750&_56_INSTANCE_8oLBj0XOEEsq_groupId=3728079&_56_INSTANCE_8oLBj0XOEEsq_version=1.0&_56_INSTANCE_8oLBj0XOEEsq_categoryName=BOLLETTINO+EPIDEMIOLOGICO+REGIONE+PUGLIA+30%2F03%2F2020&_56_INSTANCE_8oLBj0XOEEsq_back=%2Fweb%2Fguest%2Fcoronavirus%2Faggiornamenti, presenta una mappa sinottica dove a ogni comune è associato un diverso colore, a seconda del range di casi confermati (0-5, 6-10-11-20 ecc.).
Sarebbe possibile avere questi dati nel riepilogo giornaliero? 
Grazie e Buon Lavoro.

**Comment by umbros** [comment]
Ciao @marcyborg allo stato attuale questa informazione non è prodotta nel report che ci viene fornito dalle Regioni per il tramite del Ministero della Salute
