### ISSUE TITLE
Dati imprecisi e non omogenei: proposta di aggiunta disclaimer

### ISSUE THREAD

**Issue by mordacheno** [pcm-dpc/COVID-19#486]
Preso atto che i dati comunicati dalle Regioni sono imprecisi e non omogenei, propongo di aggiungere un disclaimer ben visibile nel cruscotto geografico interattivo e nella documentazione, anche per avvisare in maniera trasparente chiunque avesse intenzione elaborare statistiche e proiezioni a partire da tali dati imprecisi e non omogenei.

Entrando maggiormente nel dettaglio in merito alla qualità dei dati - ovviamente non dipendente da chi ha realizzato e effettua la manutenzione del cruscotto- segnalo ad esempio che:

- Il numero di decessi è probabilmente ampiamente sottostimato. Si veda ad esempio:
"Andamento della Mortalità Giornaliera (SiSMG) nelle città italiane in relazione all’epidemia di Covid-19" disponibile su http://www.epiprev.it/node/4785/
"Andamento dei decessi del 2020" disponibile su https://www.istat.it/it/archivio/240401

- Il dato dei guariti è probabilmente sovrastimato, dal momento che la "categoria eterogenea dei dimessi/guariti viene fatta coincidere con le guarigioni", come meglio spiegato qui:
https://www.sanita24.ilsole24ore.com/art/aziende-e-regioni/2020-04-02/coronavirus-cartabellotta-fondazione-gimbe-sovrastimato-numero-guariti-rischi-serve-chiarezza-orientare-scelte-103855.php?uuid=ADkV6eH

- Il dato dei tamponi potrebbe corrispondere al numero di tamponi effettuati e non al numero di tamponi analizzati, con una sovrastima anche del 10%. In Piemonte in base ai dati inseriti nel bollettino ufficiale e seguendo il metodo di analisi già utilizzato dal quotidiano La Stampa i tamponi ancora da analizzare erano 3260 (dato ricavato partendo dai 31135 tamponi eseguiti, sottraendo i 17957 tamponi negativi e i 9918 tamponi positivi). In Veneto ieri Zaia parlava di "10 mila tamponi bloccati nei frigo", senza però fornire cifre utili a comprendere se nel numero di tamponi comunicato alla Protezione Civile (pari a 112746) rientrassero quei diecimila tamponi effettuati ma non ancora analizzati.

Fonti:

https://www.regione.piemonte.it/web/pinforma/notizie/coronavirus-gli-aggiornamenti-dalla-regione-piemonte

https://www.lastampa.it/torino/2020/03/15/news/il-coronavirus-non-si-ferma-e-fa-altri-15-morti-nella-notte-in-piemonte-1.38596210

http://www.rainews.it/dl/rainews/articoli/Coronavirus-Fontana-Trend-piatto-Zaia-Veneto-in-queste-settimane-ci-giochiamo-il-futuro-a5139959-c784-4c65-86b7-7670cdf1321f.html

**Comment by umbros** [comment]
Ciao @mordacheno noi pubblichiamo i dati che dalle Regioni vengono comunicati al Ministero della Salute, per noi i dati sono stabili, se poi ci sono delle problematiche sui dati lo segnaliamo nei campi note, ma direi che essendo il repository ufficiale è questa la fonte di riferimento. Grazie comunque per la segnalazione.

**Comment by CostaGiuseppe** [comment]
> Ciao @mordacheno noi pubblichiamo i dati che dalle Regioni vengono comunicati al Ministero della Salute, per noi i dati sono stabili, se poi ci sono delle problematiche sui dati lo segnaliamo nei campi note, ma direi che essendo il repository ufficiale è questa la fonte di riferimento. Grazie comunque per la segnalazione.

praticamente una risposta non risposta. Ma comunque in linea con le non risposte che vengono date dai capi della protezione civile.
