### ISSUE TITLE
Missing numeric value in dpc-covid19-ita-province-20200311.csv

### ISSUE THREAD

**Issue by brunato** [pcm-dpc/COVID-19#487]
Type of issue:

- [ x ] Incorrect or missing data : `dati-province/dpc-covid19-ita-province-20200311.csv`
- [ ] Incorrect or missing documentation 
- [ ] Incorrect or missing data in the dashboard 
- [ ] Layout problem in the dashboard 

- Region: `Sicilia`
- Province: `994,In fase di definizione/aggiornamento`

## Summary

The column *totale_casi* has an empty value at row 103. This can be problematic to automatic recognize this column as numeric data.

**Expected:**

`2020-03-11T17:00:00,ITA,19,Sicilia,994,In fase di definizione/aggiornamento,,0,0,0,,`

**Actual:** 

`2020-03-11T17:00:00,ITA,19,Sicilia,994,In fase di definizione/aggiornamento,,0,0,,,`

**Comment by umbros** [comment]
Thank you @brunato the issue was corrected.
