### ISSUE TITLE
[NOT an issue] Grafici interattivi per provincia e regione

### ISSUE THREAD

**Issue by RickySal** [pcm-dpc/COVID-19#488]
Buonasera, ho appena apportato una modifica maggiore al sito che ospita i grafici interattivi [graficicovid19.org](https://graficicovid19.org). Ora è possibile visualizzare i grafici anche per PROVINCIA (con derivate). Appena riesco inserirò anche i dati dei casi in aggiornamento.
Nel caso non doveste visualizzare le modifiche fate CTRL+F5, ho fatto una piccola cavolata con la cache scusate!

GRAFICI PER REGIONE E PROVINCIA:
graficicovid19.org

**Comment by umbros** [comment]
Grazie mille per la collaborazione @RickySal
