### ISSUE TITLE
Aggiornamento Province. Dati anomali nella colonna "totale_casi" del giorno 8 marzo

### ISSUE THREAD

**Issue by evoblue** [pcm-dpc/COVID-19#49]
Nei dati delle province (file dpc-covid19-ita-province.csv ma anche dpc-covid19-ita-province-20200308.csv) l'aggiornamento dell' 8 Marzo nella colonna "totale_casi"  riporta dati poco realistici per molte province (esempio Bergamo , Cremona , Lodi, etc. ). Si tratta quasi certamente di un errore. 

Inoltre diversi parser mi segnalano righe con formati numerici malformati nel file dpc-covid19-ita-province.csv

Grazie per questo utile lavoro.

**Comment by LucaMare2** [comment]
Ho appena controllato i dati delle province di Bergamo, Cremona, Lodi e in generale quelli delle province lombarde e mi risultano corretti e coerenti con [quelli pubblicati da Regione Lombardia.](https://www.lombardianotizie.online/coronavirus-casi-lombardia/)

**Comment by evoblue** [comment]
Sono stati aggiornati mentre scrivevo.
Problema risolto.
