### ISSUE TITLE
Variazione positivi con numero negativo

### ISSUE THREAD

**Issue by PiMasGit** [pcm-dpc/COVID-19#490]
Buongiorno,
grazie mille per il grande lavoro che state facendo, questi dati sono davvero preziosi. Ho una domanda riguardo ai dati di alcune regioni (Liguria, Piemonte, Sicilia). In questi casi ci sono dei dati per i "nuovi_positivi" negativi (esempio: Liguria, 01/03/2020), non capisco cosa questo significhi. Sarebbe possibile avere una spiegazione per questo?
Vorrei anche chiedere come è possibile calcolare l'incidenza giornaliera da questi dati: per ora la sto calcolando come differenza tra i valori di "totale_casi" tra un giorno e quello precedente. Esiste un metodo migliore? 
Grazie ancora per il vostro lavoro,
Pietro

**Comment by umbros** [comment]
Ciao @PiMasGit il negativo di liguria è dovuto ad un riconteggio delle persone in totali casi. Quindi il fatto di riconteggiare i casi ha generato un negativo sui nuovi positivi.

**Comment by PiMasGit** [comment]
> Ciao @PiMasGit il negativo di liguria è dovuto ad un riconteggio delle persone in totali casi. Quindi il fatto di riconteggiare i casi ha generato un negativo sui nuovi positivi.

Grazie per avermi risposto. Non capisco però come calcolare l'incidenza perché così facendo avrei dei numeri negativi. Su quali valori mi dovrei basare?

**Comment by umbros** [comment]
Va bene sui numeri su cui ti basi ma essendo in un contesto emergenziale i dati possono variare. Quindi va bene usare i nuovi_positivi per lo scopo che ti serve. (erano i "primi" giorni)
