### ISSUE TITLE
Richiesta dati su posti in terapia intensiva totali e disponibili

### ISSUE THREAD

**Issue by danielesalpietro** [pcm-dpc/COVID-19#491]
Da varie fonti di informazioni risultano circa 6.000/6.100 posti in terapia intensiva in tutta italia; sappiamo che al momento  sono occupati circa 4.000 in Italia più X in Germania; è possibile includere i posti_reali_disponibili_terapia_intensiva per ogni regione fra i date che pubblicate.

Poi ci sarebbe da chiedersi anche come mai 2.000 posti di terapia intensiva non sono usati per i Covid-19, ma suppongo (e spero che sia davvero così) che siano occupati anche da altri casi urgenti non Covid-19......

Grazie

**Comment by downFast** [comment]
Ciao @danielesalpietro 
io li ho scaricati da http://www.dati.salute.gov.it/dati/dettaglioDataset.jsp?menu=dati&idPag=17

E mi sono creato anche il json.

Ma è pericoloso usarli, potrebbe creare confusione, infatti ho preferito evitare. Intanto sarebbero da considerare quelli tropicali, intensiva e pneumologia ma non possiamo esattamente dare dati del genere, alcuni ospedali hanno dovuto fare urgenze di ogni tipo, quindi potremmo creare casini facendo analisi rispetto ai posti letto. 

Io ho preferito evitare.

**Comment by danielesalpietro** [comment]
@downFast concordo con te, ma non capisco perché gli ospedali gli assessori non forniscano dati più chiari in merito ai posti letto disponibili per la terapia intensiva, avrebbero più attenzione da parte di tutti e dei media; lasciando invece circolare il numero di posti letti = 6100; e poi dichiarando che ne usiamo solo 4000, non ha senso....... 

Grazie comunque per la fonte, userò questi dati.....
