### ISSUE TITLE
Potreste inserire gli avvisi nelle note?

### ISSUE THREAD

**Issue by downFast** [pcm-dpc/COVID-19#492]
Salve,
abbiamo gli avvisi:

- 29/03/2020: dati Regione Emilia-Romagna parziali (dato tampone non aggiornato).
- 26/03/2020: dati Regione Piemonte parziali (-50 deceduti - comunicazione tardiva).
- 18/03/2020: dati Regione Campania non pervenuti.
- 18/03/2020: dati Provincia di Parma non pervenuti.
- 17/03/2020: dati Provincia di Rimini non aggiornati.
- 16/03/2020: dati P.A. Trento e Puglia non pervenuti.
- 11/03/2020: dati Regione Abruzzo non pervenuti.
- 10/03/2020: dati Regione Lombardia parziali.
- 07/03/2020: dati Brescia +300 esiti positivi

Potreste inserirli nel campo note?

`"note_it": "",`

In modo tale da poter mostrare il dato di quella data con la nota relativa o laddove volessimo?

Grazie per il lavoro che state svolgendo.

**Comment by umbros** [comment]
Ciao downfast, il messaggio è dettagliato nel dataset note https://github.com/pcm-dpc/COVID-19/tree/master/note in italiano e inglese e referenziato lì per maggiore comodità. Stiamo preparando un wiki con le informazioni necessarie e dovrebbe essere pronto al massimo per lunedì.

**Comment by downFast** [comment]
Ciao @umbros , grazie, sarebbe stato bello averlo già nel json anche a dire il vero.

Grazie comunque
