### ISSUE TITLE
codici identificativi uguali

### ISSUE THREAD

**Issue by mzanrosso** [pcm-dpc/COVID-19#493]
Ciao,
Nella tabella dei dati regionali è indicata con il codice 04 sia Bolzano sia Trento;
Presuppongo che quel codice sia univoco e che quindi sia un errore da correggere.

**Comment by paxtibi** [comment]
Quello è il codice ISTAT.

**Comment by paxtibi** [comment]
Se vuoi approfondire https://www.istat.it/storage/codici-unita-amministrative/Archivio-elenco-comuni-codici-e-denominazioni_Anni-2018-2020.zip
:)

**Comment by umbros** [comment]
Ciao, esatto come riporta @paxtibi sarebbe una cosa da risolvere ma dobbiamo attenerci a quanto dice ISTAT altrimenti si perde l'interoperabilità.
