### ISSUE TITLE
denominazione_regione

### ISSUE THREAD

**Issue by Infragal** [pcm-dpc/COVID-19#497]
**Tipo di richiesta**:  richiesta di informazione | richiesta di dati | suggerimento di miglioramento (documentazione, label, _ecc_) | relativo alla pagina grafica

## Interesse pubblico
Sarebbe possibile riportare la descrizione attuale "Emilia-Romagna" a quella originale "Emilia Romagna"; in pratica, eliminare semplicemente il trattino?
Sarebbe coerente con quella delle altre regioni a nome multiplo; es.: Friuli Venezia Giulia, Valle d'Aosta.
Non è semplicemente un fattore estetico, ma influisce sull'elaborazione successiva dei dati estratti.

Grazie per l'attenzione
Francesco Galdieri
-->

**Comment by downFast** [comment]
Soluzione flash potrebbe essere...

```
var replaceInArray = function(str){
  return str.replace(/\s+/g, "+")
}
var regionNames = ["Lombardia, "Lazio", "Friuli Venezia Giulia", "Valle d'Aosta", "Emilia-Romagna"];
regionNames.map(replaceInArray);
```

**Comment by paxtibi** [comment]
Emilia-Romagna E' la denominazione Istat.
Se proprio dobbiamo parlare di "-"   Friuli Venezia Giulia che non usa la stessa denominazione Istat. 
Istat (se non erro) usa i trattini in:
04 "Trentino-Alto Adige" 
06 "Friuli-Venezia Giulia"
08 "Emilia-Romagna"
:)

**Comment by pierluigicara** [comment]
Mi spiace la denominazione ISTAT per 06 è Friuli Venezia Giulia (senza trattino), per 04 e 08 invece c'è il trattino e la nostra scelta è di essere conformi a ISTAT

**Comment by paxtibi** [comment]
Premesso che la trovo una questione di bassissima importanza se il nome ha il "-" o meno, l'importante che sia coerente del dataset esposto. 

@Infragal  basta una query sul db per codice regione, poi metti la descrizione come preferisci.
@pierluigicara 
Ho riscaricato i dati dall'istat qualche giorno fa https://www.istat.it/it/archivio/6789 (Archivio-elenco-comuni-codici-e-denominazioni_Anni 2018-2020.zip\Elenco-codici-statistici-e-denominazioni-al-31_12_2019.xls)
Quelli che mettono a disposizione riportanto il trattino.
Faccio riferimento a quelli :) Se avete un'altro archivio da consultare, ed è pubblico, mi piacerebbe consultarlo. Giusto per studiarlo.

Riporto solo i dati d'interesse giusto per un rapido confronto. 

Codice Regione;Denominazione regione
01;Piemonte
02;Valle d'Aosta/Vallée d'Aoste
03;Lombardia
04;Trentino-Alto Adige/Südtirol
05;Veneto
06;Friuli-Venezia Giulia
07;Liguria
08;Emilia-Romagna
09;Toscana
10;Umbria
11;Marche
12;Lazio
13;Abruzzo
14;Molise
15;Campania
16;Puglia
17;Basilicata
18;Calabria
19;Sicilia
20;Sardegna

**Comment by pierluigicara** [comment]
Condivido la scarsa importanza ma ringrazio per l'informazione sul link istat "discordante" (purtroppo anche un medesimo ente non riesce ad armonizzare tutti i suoi contenuti). Il link che usiamo noi è quello cartografico ovvero gli shape 2020 in https://www.istat.it/it/archivio/222527.
