### ISSUE TITLE
dashboard requires PCM credentials for access

### ISSUE THREAD

**Issue by GiorgioBalestrieri** [pcm-dpc/COVID-19#498]
When trying to access the dashboard at [http://arcg.is/C1unv](http://arcg.is/C1unv), I get prompted for PCM credentials as shown below. This didn't use to happen until a few hours ago.

Thanks! 

![image](https://user-images.githubusercontent.com/17710158/78388187-ded75700-75e0-11ea-8d24-f41ef5c2b699.png)

**Comment by qzagarese** [comment]
Please clarify whether this is a technical issue or an intended decision, because closing that dashboard really defeats the purpose of transparency that has been pursued so far.

**Comment by umbros** [comment]
Ciao @GiorgioBalestrieri stavamo facendo un aggiornamento ad alcuni componenti, ora è tutto ok.
Grazie della segnalazione. @qzagarese no problem for transparency just maintenance.

**Comment by qzagarese** [comment]
@umbros thank you for the quick reply.
The new graph is really helpful.
