### ISSUE TITLE
Dati regionali e provinciali incongruenti

### ISSUE THREAD

**Issue by WMangini** [pcm-dpc/COVID-19#5]
Ciao e complimenti per la mappa interattiva realizzata. 

Segnalo che, al momento, i dati su base regionale e provinciale non combaciano, almeno per quanto riguarda la Campania.

Buon lavoro.

**Comment by umbros** [comment]
Ciao @WMangini puoi darmi maggiori dettagli?

**Comment by WMangini** [comment]
Nella mappa che mostra la stratificazione per regioni, risultano, al momento, 57 casi totali in Campania. Passando poi alla mappa per provincie, sono riportati solo 17 casi nella provincia di Napoli.

**Comment by ctrlbru** [comment]
e 40 in fase di definizione, quindi 57

**Comment by umbros** [comment]
Si, è corretto perchè 40 sono in fase di definizione quindi non li possiamo collocare su mappa. Hai suggerimenti secondo te di come si potrebbero mostrare su mappa?

**Comment by WMangini** [comment]
Allora si potrebbe pensare di aggiungere questa informazione aggiuntiva (numero di casi in fase di definizione) nella mappa per provincie per far tornare i conti. Oppure, alternativamente, mostrare solo i casi confermati nella mappa per regioni.
Rinnovo i complimenti, comunque, per il lavoro svolto. Sarà di utilità sia alle forze dell'ordine che alla popolazione.

**Comment by umbros** [comment]
Grazie a te per i suggerimenti e la collaborazione.
