### ISSUE TITLE
Un paio di null nel file dpc-covid19-ita-regioni.json

### ISSUE THREAD

**Issue by mydozer** [pcm-dpc/COVID-19#50]
Ciao, ci sono un paio di valori null nel file dpc-covid19-ita-regioni.json, va interpretato come non disponibile o è assimilabile a 0?
`{
        "data": "2020-03-07 18:00:00",
        "stato": "ITA",
        "codice_regione": 20,
        "denominazione_regione": "Sardegna",
        "lat": 39.21531192,
        "long": 9.110616306,
        "ricoverati_con_sintomi": 2,
        "terapia_intensiva": null,
        "totale_ospedalizzati": 2,
        "isolamento_domiciliare": 3,
        "totale_attualmente_positivi": 5,
        "nuovi_attualmente_positivi": 0,
        "dimessi_guariti": 0,
        "deceduti": 0,
        "totale_casi": 5,
        "tamponi": 99
    },
    {
        "data": "2020-03-07 18:00:00",
        "stato": "ITA",
        "codice_regione": 19,
        "denominazione_regione": "Sicilia",
        "lat": 38.11569725,
        "long": 13.3623567,
        "ricoverati_con_sintomi": 8,
        "terapia_intensiva": null,
        "totale_ospedalizzati": 8,
        "isolamento_domiciliare": 25,
        "totale_attualmente_positivi": 33,
        "nuovi_attualmente_positivi": 11,
        "dimessi_guariti": 2,
        "deceduti": 0,
        "totale_casi": 35,
        "tamponi": 643
    }`

**Comment by umbros** [comment]
@mydozer grazie della segnalazione.
