### ISSUE TITLE
Excel con link

### ISSUE THREAD

**Issue by hankskorpio** [pcm-dpc/COVID-19#500]
Ho creato un excel (Office365) con linked data e qualche chart per regioni. Per chi può interessare lo trovate qua :

https://github.com/hankskorpio/Covid19-ITA-EXCEL

sentitevi pure liberi di migliorarlo :)

Grazie e scusate il disturbo.

**Comment by Infragal** [comment]
Grazie mille.
Alla prossima

**Comment by danilort** [comment]
Ottimo.
Sarebbe interessante aggiungere la percentuale di infetti rispetto la popolazione, perche' il numero degli infetti non e' significativo.

ESEMPIO:
Toscana: 3.7 milioni di abitanti, 5600 infetti (0.15%)
Valle d'aosta: 125mila abitanti, 748 infetti (0.60%)

Se la valle d'aosta arrivasse (speriamo di no) a 125mila infetti, avrebbe il 100% della popolazione ammalata.
Mentre se la toscana arrivasse a 125mila infetti, avrebbe ancora 3.6 milioni di sani.

Ciao

**Comment by hankskorpio** [comment]
Buona osservazione, appena ho una mezz'ora ci lavoro. Nel frattempo ho fatto un piccolo update con miglioramenti negli assi e il chart dei tamponi.

**Comment by umbros** [comment]
Grazie del contributo
