### ISSUE TITLE
Go corona go

### ISSUE THREAD

**Issue by shivam12k** [pcm-dpc/COVID-19#501]

**Comment by umbros** [comment]
@shivam12k voglio pensare che go corona go sia un qualche progetto scritto in GoLang.

**Comment by shivam12k** [comment]
I don't know how to use git I just try to learn , in order to learn male this project

**Comment by shivam12k** [comment]
@umbros  ehi non so come usare github e per errore sono entrato nel tuo progetto e penso di aver creato un nuovo progetto e cambio il nome.
