### ISSUE TITLE
colonna tamponi

### ISSUE THREAD

**Issue by fscarpa58** [pcm-dpc/COVID-19#502]
buongiorno
volevo chiedere se la colonna tamponi si riferisce a "tamponi fatti" o "tamponi elaborati"
Facendo le differenze (tamponi oggi meno tamponi ieri) per ottenere i tamponi giornalieri ho notato una componente periodica a periodo settimanale praticamente in fase con la stessa componente rilevabile sui contagi giornalieri (casi totali oggi - casi totali ieri). Da questo fatto, considerando difficile che i risultati dei tamponi vengano elaborati (analizzati) istantaneamente o in una settimana esatta, ne dedurrei che il numero di tamponi riportato faccia riferimento non hai tamponi eseguiti ma hai tamponi analizzati.

**Tipo di richiesta**:  richiesta di informazione | richiesta di dati | suggerimento di miglioramento (documentazione, label, _ecc_) | relativo alla pagina grafica

**Comment by Tantormai** [comment]
fscarpa58, temo che stia facendo un'analisi troppo raffinata per l'indeterminazione che i dati presentano.
In Liguria, ad esempio, il numero di casi "In fase di definizione/aggiornamento" crescono dal 14 Marzo e ieri erano arrivati a quasi 2,000 (1,975 per la precisione).
Cosa significa? Che ogni giorno in Liguria si fanno più tamponi di quelli che poi si riescono ad analizzare?
Da notare che questi casi da definire sono però già sommati al totale_casi, come si può verificare confrontando i numeri delle Province con quelli della Regione. Se si pensa che i casi_totali della Liguria sono 3,965, metà sono ancora da definire.

**Comment by fscarpa58** [comment]
grazie. 
sono abituato all'incertezza e agli errori dei dati. Quello che mi manca sono le informazioni precise sul che tipo di dati sto davvero lavorando (es. i tamponi). I dati liguri sono troppo ballerini. Quelli nazionali sono accettabili. questa è l'oscillazione a cui mi riferivo e che trova spiegazione, a mio avviso, solo assumendo che per tamponi si intenda "tamponi perfezionati" con annesso risultato
![image](https://user-images.githubusercontent.com/28668119/78454149-8b274500-7696-11ea-82c3-a6c631531489.png)
un saluto e buon lavoro

**Comment by biomichele** [comment]
Ciao fscarpa58,
Anche io sono focalizzato sui tamponi, in particolare su rapporto nuovi casi positivi su taponi fatti.
Io credo che la fase che tu vedi sia dovuta a una saturazione dei tamponi fatti sui positivi. Se i tamponi fatti giornalmente sono il fattore limitante nell'identificazione di nuovi positivi ovviamente i due parametri viaggiano insieme. Credo inoltre ci sia un intervallo di tempo tra quando prelievi il tampone a quando lo esegui. Questa seconda fare da subito l'esito quindi non credo ci sia una fase di perfezionamento del risultato.
Concordo che il dato che si analizza deve essere pulito e chiaro. Stesso problema con i numeri dei guariti/dimessi. Ci sono dichiarazioni che dicono che non siano le persone che tornano negative ma quelle dimesse anche in attesa del tampone di controllo per verificare la negativizzazione.
La mia domanda è: ci sono delle linee guida standard nel recuperare questi dati? E tutte le regioni si comportano nello stesso modo?

**Comment by mordacheno** [comment]
Avevo posto questa e altre questioni, nella Issue [[#486]](https://github.com/pcm-dpc/COVID-19/issues/486) 

Si tratta - probabilmente per la maggior parte delle Regioni - di tamponi effettuati e non tamponi analizzati.

Tutti i laboratori hanno una coda di tamponi da analizzare e li lavorano ragionevolmente con priorità diverse. Sebbene non ci sia stata alcun chiarimento ufficiale in merito, questo lo si può dedurre ad esempio da:

- analisi delle statistiche regionali riportate dalla Protezione Civile
Anche ad inzio emergenza - e quindi con un numero di tamponi da analizzare ridotto - risultavano giorni con un numero di nuovi casi positivi superiore al numero di nuovi tamponi comunicati quel giorno. Ad esempio, se non ho fatto male i conti:

Emilia Romagna 3 marzo: 39 nuovi tamponi, 85 nuovi positivi
Lombardia 5 marzo: 216 nuovi tamponi, 431 nuovi positivi
Veneto 9 marzo: 38 nuovi tamponi, 74 nuovi positivi
Piemonte 13 marzo: 226 nuovi tamponi, 260 nuovi positivi

- Analisi del dati presenti sul cruscotto ufficiale della Regione Lombardia, disponibile [qui](https://lispa.maps.arcgis.com/apps/opsdashboard/index.html#/637ec3dc28ec4ea591cc5c724f127701)

In quel cruscotto il totale dei positivi giorno per giorno - a livello regionale e provinciale - è sensibilmente diverso da quello riportato dallla Protezione Civile. La motivazione è spiegata abbastanza bene nelle note, dove si chiarisce come nel bollettino della Protezione Civile "vengono riportati i dati dei nuovi positivi di cui si è venuti a conoscenza  a prescindere dalla data in cui il laboratorio ha ricevuto il tampone".

- Analisi dei bollettini della Regione Piemonte, disponibili [qui](https://www.regione.piemonte.it/web/pinforma/notizie/coronavirus-gli-aggiornamenti-dalla-regione-piemonte)

Qui viene comunicato il dato dei tamponi eseguiti (che è quello che arriva alla Protezione Civile), ma talvolta veniva anche comunicato il dato dei tamponi ancora da analizzare. Secondo il quotidiano La Stampa il numero di tamponi in coda si può calcolare semplicemente partendo dal totale dei tamponi eseguiti, sottraendo i tamponi negativi e i casi positivi. Alle 19 del 1 aprile, ad esempio, risultavano in coda ben 3260 tamponi sui 31135 effettuati (più del 10% insomma).
L'articolo de La Stampa del 15 marzo è disponibile [qui](https://www.lastampa.it/torino/2020/03/15/news/il-coronavirus-non-si-ferma-e-fa-altri-15-morti-nella-notte-in-piemonte-1.38596210)

**Comment by mordacheno** [comment]
> Concordo che il dato che si analizza deve essere pulito e chiaro. Stesso problema con i numeri dei guariti/dimessi. Ci sono dichiarazioni che dicono che non siano le persone che tornano negative ma quelle dimesse anche in attesa del tampone di controllo per verificare la negativizzazione.
> La mia domanda è: ci sono delle linee guida standard nel recuperare questi dati? E tutte le regioni si comportano nello stesso modo?

Sul dato dei guariti - anche questo chiaramente impreciso e non uniforme -  si veda il brillante lavoro di ricerca di GIMBE e YouTrend, di cui si parla ad esempio [qui](https://www.sanita24.ilsole24ore.com/art/aziende-e-regioni/2020-04-02/coronavirus-cartabellotta-fondazione-gimbe-sovrastimato-numero-guariti-rischi-serve-chiarezza-orientare-scelte-103855.php?uuid=ADkV6eH)

**Comment by fscarpa58** [comment]
@mordacheno 
grazie. ho controllato ed in effetti  a volte i nuovi positivi superano i nuovi tamponi.
Continuo a non spiegarmi la sincronia  di fase fra i dati.  a meno che mediamente a livello nazionale ci sia proprio un ritardo di 7 giorni. ma ne dubito.

**Comment by tmontanaro** [comment]
Buonasera,
cercando di capire il significato del campo "numero di tamponi" mi sono accorto, leggendo i commenti a questa ed alle altre issue associate, che forse, tra le opzioni che state considerando manchi un'opzione.

Ovvero, guardando al giorno X, il dato sul numero di tamponi potrebbe rappresentare:
- il numero di tamponi effettuati nella giornata X (e il cui risultato, quindi, si saprà tra n giorni, dove n è un numero non fisso e non prevedibile)
- il numero di tamponi effettuati in passato ed il cui risultato sia stato reso noto nella giornata X

Per il primo caso mi sorgono gli stessi dubbi che avete presentato (se vengono contati anche quelli che sono stati messi in frigo in attesa che qualcuno li analizzi ecc), ma mi sembra un numero abbastanza inutile ai fini statistici. Considerando il fatto che ogni tampone viene analizzato con tempistiche diverse, i nuovi positivi di oggi sono il frutto di tamponi effettuati nel passato.
Mentre, spero vivamente che il numero riportato sia rappresentato dalla seconda descrizione (o che quanto meno chi sta dicendo che il numero di casi sta diminuendo si basi su quello).

Qualcuno è riuscito a capire quale delle 2 descrizioni meglio rappresenta il dato riportato?

**Comment by fscarpa58** [comment]
E' la stessa domanda che ho sollevato nel post di apertura. Lei l'ha fatto in modo molto più chiaro. Non mi intendo di analisi mediche ma sono esperto in analisi del segnale, identificazione di sistema errori di misura e cose del genere. La domanda sorgeva dal riscontro di una forte correlazione fra incremento casi totali (2a colonna da destra della scheda, ultima voce, Italia) e il numero giornaliero di tamponi.  Una tale correlazione (vedi grafico più sopra)  sembra indicare che il caso B  (seconda descrizione da lei indicata) a causa della sottostante evidente componente periodica in fase.
Se infatti i tamponi fossero quelli effettuati il giorno stesso i relativi risultati, a causa della quantità di laboratori che effettuano le analisi sul territorio,  avrebbe un ritardo variabile con conseguente spread e assenza di disturbo strutturato (periodico) . E' verò che contro tale ipotesi si evidenziano casi in cui l'incremento dei  casi totali è maggiore del numero di tamponi , ma ascrivo la cosa ad errori materiali di riporto del dato o di altro tipo. Questa è  la mia opinione. Chi invece sostiene la prima ipotesi deve trovare una spiegazione alla "signature" periodica che si adatti al caso.

**Comment by magaspari** [comment]
Guardando i dati, ovvero la serie storica dei tamponi, non sfugge che nella giornata di lunedì i tamponi risultano sempre più bassi.  Dato che non ha senso comunicare il tampone fatto senza i risultati dell'analisi, a che pro? sembra che l'abbassamento dei lunedì sia dovuto alla minor capacita dei laboratori di analisi nella domenica oppure al fatto che il lunedì ci sono meno tamponi da analizzare, perché meno ne vengono fatti la domenica.  Essendoci pero' di fatto una coda di tamponi da analizzare opterei per la prima ipotesi.
Quindi secondo me si tratta probabilmente del numero di tamponi effettuati in passato la cui analisi è stata fatta il giorno precedente. 

Tenendo conto che c'è un processo di trasmissione dati tra laboratori regioni e protezione civile e' possibile che i laboratori trasmettano i dati tutte le sere in regione e che questa il giorno successivo li inserisca nei rapporti che vengono poi riportati su questo sito.

NB. ipotizzo e basta sulla base di alcune evidenze! :)

**Comment by umbros** [comment]
ciao, sono tutti i tamponi eseguiti, per i singoli casi abbiamo introdotto il campo casi testati che sono i singoli casi

**Comment by tmontanaro** [comment]
> ciao, sono tutti i tamponi eseguiti, per i singoli casi abbiamo introdotto il campo casi testati che sono i singoli casi

Grazie per la news, però ho paura che questo non chiuda la issue.
Resta da capire:
- se i risultati riportati con "tamponi" si riferiscano ai tamponi effettuati quel giorno o ai tamponi il cui risultato sia stato reso noto quel giorno

(ed a questo punto si aggiungono le domande:)
- con "casi_testati" si intende il numero di persone sottoposte a **tampone** in quel giorno o il numero di persone sottoposte a tampone nei giorni precedenti e il cui risultato è stato reso noto quel giorno?
OPPURE
- con "casi_testati" si intende il numero di persone sottoposte a **test sierologico** in quel giorno o il numero di persone sottoposte a tampone nei giorni precedenti e il cui risultato è stato reso noto quel giorno?

Grazie in anticipo per l'ulteriore chiarimento
