### ISSUE TITLE
Dati sbagliati per Bologna e Trento per il 4/4/2020

### ISSUE THREAD

**Issue by gaedol** [pcm-dpc/COVID-19#504]
Tipo di issue:

- [x] Dati mancanti o errati 
- [ ] Errore nella documentazione 
- [ ] Errore or mancanza nella dashboard 
- [ ] Problemi di visualizzazione nella dashboard 

- Regione: Emilia e Trentino
- Provincia: Bologna e Trento

## Riassunto

I dati per il 4/4/2020 per Bologna e Trento non sono in accordo con le rispettive AUSL. Le differenze non sono imputabili ad un semplice "sfasamento" dei report.

In particolare, per i casi totali di Bologna il numero riportato e` 2429, mentre il report della AUSL e` 2127 (attuali positivi)+ 183 (deceduti)+ 525 (guariti clinicamente) + 123 (guariti) = 2958.
Il report della AUSL e` consultabile qui: https://www.ausl.bologna.it/per-i-cittadini/coronavirus/report-casi-positivi-e-in-sorveglianza/Report%20casi%20e%20sorveglianza%20AUSL%20BO%204.04.2020.pdf/attachment_download/file

Per il Trentino, il numero riportato e` 2220, ma la AUSL riporta un numero di 2984. Il numero e` ricavabile da qui: https://patn.maps.arcgis.com/apps/opsdashboard/index.html#/30d39ef2c83a47d285512a4685235843

La mia attesa sarebbe di vedere questi numeri essere in accordo. In particolare c'e` da notare che per il 4/4/20 la provincia Trentina ha riportato 95 nuovi casi, il che non giustifica la differenza di 764 casi (per esempio per una mancata sincronia nella comunicazione al dipartimento di PC e l'aggiornamento del sito. Il medesimo ragionamento si applica a Bologna, che ha riportato 84 nuovi casi nella provincia, ben lontano da una differenza di 529 notata in questa issue.

Grazie mille, buon lavoro.

**Comment by tintin203** [comment]
Per quanto riguarda Bologna, i dati sono quelli forniti da Regione Emilia Romagna visibili qui https://www.regione.emilia-romagna.it/notizie/2020/aprile/coronavirus-laggiornamento-16-540-i-casi-positivi-in-emilia-romagna-608-i-casi-lievi-in-isolamento-a-domicilio-sono-7.166 Ausl Bologna non comprende tutta la provincia di Bologna (Imola è fuori)

**Comment by umbros** [comment]
I dati sono sempre comunicati dalle Regioni, potrebbero esserci differenze di orario di comunicazione.
