### ISSUE TITLE
Visualizzazione positivi sulla dashboard

### ISSUE THREAD

**Issue by gaedol** [pcm-dpc/COVID-19#505]
Tipo di issue:

- [ ] Dati mancanti o errati 
- [ ] Errore nella documentazione 
- [ ] Errore or mancanza nella dashboard 
- [x] Problemi di visualizzazione nella dashboard 

- Regione: Italia
- Provincia: 

## Riassunto

Utilizzare delle pallette bidimensionali per rappresentare il numero dei positivi per regione o provincia è di dubbia utilità. In generale rappresentare un numero con un elemento bidimensionale è pessima pratica (interpretation bias, Edward Tufte, ecc). In particolare, non è chiaro come il diametro delle palle venga calcolato, cosí che, pur con molta buona volontà non si capisce bene cosa stia succedendo. Per maggiore informazione si può leggere questo: https://makingmaps.net/2007/08/28/perceptual-scaling-of-map-symbols/

Sarebbe MOLTO meglio uniformare questa visualizzazione per esempio colorando in una scala continua tutta la regione/provincia, usando la misura di positivi/1000 persone (o positivi/10000 persone). In questo modo si trasmetterebbe immediatamente il senso di "densità" di infezione.

Grazie mille, buon lavoro.

PS
mi riferisco a questa dashboard: http://arcg.is/C1unv

**Comment by umbros** [comment]
Grazie mille per il suggerimento molto apprezzato.
