### ISSUE TITLE
Un'altra visualizzazione

### ISSUE THREAD

**Issue by michelemottini** [pcm-dpc/COVID-19#506]
Ho creato una pagina che visualizza i dati nazionali, per regione e provincia graficamente: https://michelemottini.github.io/Covita/

Grazie mille per avere messo a disposizione tutti i dati!

**Comment by downFast** [comment]
Ciao @michelemottini  come hai fatto ad inserire le date in italiano sotto? Non ci stavo riuscendo, riesci ad inserire il codice di chart js qui please? Grazie!

**Comment by michelemottini** [comment]
Ho aggiunto alla visualizzazione la comparazione di ogni dato tra tutte le regioni e i valori relativi alla popolazione per ogni regione e nazionali

**Comment by pierluigicara** [comment]
Grazie Michele anzitutto per il riconoscimento del nostro sforzo per l'apertura e il riutilizzo dei dati e poi per la segnalazione della tua pagina di visualizzazione (interessante anche la comparazione dei valori rispetto alla popolazione).
