### ISSUE TITLE
Dati sbagliati Valle d'Aosta

### ISSUE THREAD

**Issue by fisholo** [pcm-dpc/COVID-19#507]
Tipo di issue:

- [x] Dati mancanti o errati 
- [ ] Errore nella documentazione 
- [ ] Errore or mancanza nella dashboard 
- [ ] Problemi di visualizzazione nella dashboard 

- Regione: Valle d'Aosta
- Provincia: Aosta

## Riassunto

In dpc-covid19-ita-regioni.csv di ieri, 4 Aprile 2020, il campo ricoverati_con_sintomi tiene conto solamente della struttura Ospedale Parini e non della Struttura St. Pierre nella quale sono ricoverati altri 29 casi.  
Fonte https://www.regione.vda.it/pressevda/Eventi/coronavirus_i.aspx. 

Grazie per il lavoro che state facendo per tutti noi.

**Comment by umbros** [comment]
Ciao @fisholo la comunicazione dei dati avviene dalle Regioni per il tramite del Ministero della Salute, è possibile che sia stato fatto un aggiornamento successivo. Grazie per la segnalazione.
