### ISSUE TITLE
Info errate nel README.md

### ISSUE THREAD

**Issue by danilort** [pcm-dpc/COVID-19#508]
Tipo di issue:

- [ ] Dati mancanti o errati 
- [X] Errore nella documentazione: file README.md
- [ ] Errore or mancanza nella dashboard 
- [ ] Problemi di visualizzazione nella dashboard 

- Regione:
- Provincia: 

## Riassunto

Il file README.md dice:

> Aggiornamenti schema dataset 30/03/2019 @ 12:00 (Ora italiana)
> Dataset schema update 30/03/2019 @ 12:00 (Italian hour)

ma nel 2019 il COVID ancora non esisteva.

**Attesa:**
30/03/2020

**Attuale:** 
30/03/2019

Saluti
Danilo

**Comment by umbros** [comment]
Grazie Danilo
