### ISSUE TITLE
variazione_totale_positivi | errori

### ISSUE THREAD

**Issue by AFE-admin** [pcm-dpc/COVID-19#509]
Verificate, mi risulta che per le Regioni EMILIA ROMAGNA | LAZIO | LOMBARDIA | PIEMONTE non è stata riportata la trascrizione del 24/02 
VENETO da un totale di 9061 non corrispondente al totale_positivi di 9093

**Comment by umbros** [comment]
Grazie @AFE-admin analizziamo la cosa.
