### ISSUE TITLE
E' possibile codificare il tampone in tampone effettuato per sintomi o per sorveglianza? allo stato attuale sarebbe importante conoscere l'indicazione al tampone che ha delle forti ripercussioni anche di tipo prognostico.

### ISSUE THREAD

**Issue by camarelli** [pcm-dpc/COVID-19#510]
**Tipo di richiesta**:  richiesta di informazione | richiesta di dati | suggerimento di miglioramento (documentazione, label, _ecc_) | relativo alla pagina grafica

**Comment by umbros** [comment]
Ciao @camarelli 
allo stato attuale non è possibile questa distinzione. Ogni aggiornamento sarà riportato.
