### ISSUE TITLE
I dati del Lazio di oggi 5 Aprile riportano 123 nuovi casi, ma il numero di tamponi eseguiti oggi è solo 32.

### ISSUE THREAD

**Issue by Tantormai** [pcm-dpc/COVID-19#511]
**Tipo di richiesta**:  richiesta di informazione | richiesta di dati | suggerimento di miglioramento (documentazione, label, _ecc_) | relativo alla pagina grafica

**Comment by umbros** [comment]
@Tantormai sono i dati comunicati dalla Regione Lazio per il tramite del Ministero della Salute, relativamente alla documentazione ci stiamo lavorando. Grazie
