### ISSUE TITLE
i casi odierni di genova sono corretti?

### ISSUE THREAD

**Issue by sergiofadini** [pcm-dpc/COVID-19#512]
**Tipo di richiesta**:  richiesta di informazione | richiesta di dati | suggerimento di miglioramento (documentazione, label, _ecc_) | relativo alla pagina grafica

**Comment by sergiofadini** [comment]
mi sembra strano che da ieri a oggi ci siano stati oltre 600 casi, nel database iri era fermo a 1312 casi totali (4 aprile), oggi sarebbero oltre 1900 (5 aprile)

**Comment by heyteacher** [comment]
I dati liguri di ieri risentono dei test effettuati nelle RSA https://twitter.com/RegLiguria/status/1246850954835656704?s=19

**Comment by auino** [comment]
In ogni caso, ho notato anche io che i dati genovesi per il periodo che va dal 4 aprile [1] al 5 aprile [2] (+oltre 600) non sono coerenti con quelli regionali [3] (+199). Mi sfugge qualcosa?

[1] https://github.com/pcm-dpc/COVID-19/blob/master/dati-province/dpc-covid19-ita-province-20200404.csv
[2] https://github.com/pcm-dpc/COVID-19/blob/master/dati-province/dpc-covid19-ita-province-20200405.csv
[3] https://github.com/pcm-dpc/COVID-19/blob/master/dati-regioni/dpc-covid19-ita-regioni-20200405.csv

**Comment by heyteacher** [comment]
considera che ogni regione ha una provincia fittizia denominata  "in fase di definizione/aggiornamento" che  contiene i dati regionali non ancora assegnati alle province di appartenenza. nel weekend questo dato e crollato in liguria , quindi immagino che qualcuno si è messo ad attribuire i dati alle singole province. 
https://heyteacher.github.io/COVID-19/#/Liguria

**Comment by gidiemme72** [comment]
Confermo cheh anno assegnato i fasi "in fase di definizione/aggiornamento", per cui ieri tutte le provincie liguri hanno degli incrementi "anomali (Savona +181%).

Avrebbero dovuto assegnarli retrodatandoli alla data del tampone...... Chissa se è possibile...?

**Comment by auino** [comment]
I conti continuano a non quadrare, ma sicuramente sbaglio io: dai dati del 5 aprile, il totale dei casi in Liguria risulta pari a 4449 [1], mentre da [2] per le quattro province liguri è pari a 1924 (Genova) + 586 (Imperia) + 445 (La Spezia) + 734 (Savona) = 3689. Pare dunque esserci una differenza di 760 casi. Dove sbaglio?

[1] https://github.com/pcm-dpc/COVID-19/blob/master/dati-regioni/dpc-covid19-ita-regioni-20200405.csv
[2] https://github.com/pcm-dpc/COVID-19/blob/master/dati-province/dpc-covid19-ita-province-20200405.csv

**Comment by dace74** [comment]
> I conti continuano a non quadrare, ma sicuramente sbaglio io: dai dati del 5 aprile, il totale dei casi in Liguria risulta pari a 4449 [1], mentre da [2] per le quattro province liguri è pari a 1924 (Genova) + 586 (Imperia) + 445 (La Spezia) + 734 (Savona) = 3689. Pare dunque esserci una differenza di 760 casi. Dove sbaglio?
> 
> [1] https://github.com/pcm-dpc/COVID-19/blob/master/dati-regioni/dpc-covid19-ita-regioni-20200405.csv
> [2] https://github.com/pcm-dpc/COVID-19/blob/master/dati-province/dpc-covid19-ita-province-20200405.csv

Sono giusti ti manca il dato di 760 dell'ultima che non hai aggiunto.

**Comment by auino** [comment]
Perfetto, grazie @dace74. Chiarissimo ora, anche il messaggio di @heyteacher.

**Comment by paolorossi** [comment]
Su Spezia però l'incremento misurato il giorno 04/04 è stato in proporzione molto più contenuto rispetto al resto della regione. Secondo voi in quella provincia i test delle RSA erano già inclusi o si deve ancora procedere a questa integrazione?
