### ISSUE TITLE
Guariti lombardi: perchè solo da ospedale?

### ISSUE THREAD

**Issue by Paulsword** [pcm-dpc/COVID-19#513]
**Tipo di richiesta**:
Chiarimento sul numero guariti Lombardia

## Riassunto
La Regione Lombardia mostra in conferenza stampa due numeri relativi ai dimessi (totali): il primo oggi è 13.426, si riferisce ai dimessi "con un passaggio da ospedale". Corrisponde al dato comunicato dal Ministero. Il secondo è di 14.798, "per cui non si rileva nessun passaggio". Il totale dimessi mostrato è quindi 28.224. La domanda è: perché il secondo numero viene escluso dal conteggio del Ministero?

## Interesse pubblico
Fa una bella differenza, spiegherebbe perché siamo davvero a plateau, con un bilancio nuovi casi/outcome che si pareggia, includendo tutti i dimessi-guariti. Grazie

**Comment by Paulsword** [comment]
![coronavirus-laggiornamento-di-regione-lombardia-111-nuovi-casi-a-monza-e_26ebb5d0-7759-11ea-83a7-0f14dc4ab687_700_455_big_gallery_linked_i](https://user-images.githubusercontent.com/45740116/78508927-b68b5c00-778a-11ea-9bdf-4370be9cb394.jpg)

**Comment by downFast** [comment]
https://github.com/pcm-dpc/COVID-19/issues/514

**Comment by downFast** [comment]
https://www.sanita24.ilsole24ore.com/art/aziende-e-regioni/2020-04-02/coronavirus-cartabellotta-fondazione-gimbe-sovrastimato-numero-guariti-rischi-serve-chiarezza-orientare-scelte-103855.php?uuid=ADkV6eH

**Comment by umbros** [comment]
Ciao nel repository, allo stato attuale vengono riportati i dimessi guariti
