### ISSUE TITLE
Dati errati nel numero di test effettuati 

### ISSUE THREAD

**Issue by carlocenedese** [pcm-dpc/COVID-19#515]
Tipo di issue:

- [x] Dati mancanti o errati 

- Regione: Friuli ed Emilia

## Riassunto
Il numero di test effettuati non è scorretto in alcune regioni, per esempio nel case del Friuli Venezia Giulia il dumero diminuisce in alcuni casi. Inoltre alcune volte il numero di nuovi infetti è superiore al numero di test effettuati, ovviamente questo è impossibilie. Ho riscontrato questo problema anche nel caso dei dati dell'Emilia Romagna. Allego piccola analisi Matlab in cui questo è messo in luce.
[Matlab_COVID19.pdf](https://github.com/pcm-dpc/COVID-19/files/4437605/Matlab_COVID19.pdf)

**Attesa:**

**Attuale:**

**Comment by umbros** [comment]
Grazie mille, conosciamo bene le oscillazioni ma sono dovute spesso a riconteggi. Grazie della segnalazione.
