### ISSUE TITLE
Uscita dall'ospedale in attesa di tampone

### ISSUE THREAD

**Issue by stucco81** [pcm-dpc/COVID-19#516]
Ciao a tutti,

un chiarimento, quando uno esce dall'ospedale, ma:

-  è in attesa di tampone
- o resta in isolamento post tampone negativo 

che verifichi l'assenza di COVID-19 viene inserito fra i dimessi guariti o passa in isolamento domiciliare?

Vorrei capire se i dimessi vanno ad incrementare il numero degli isolamenti domiciliari

Grazie

**Tipo di richiesta**:  richiesta di informazione | richiesta di dati | suggerimento di miglioramento (documentazione, label, _ecc_) | relativo alla pagina grafica

**Comment by Paulsword** [comment]
Le ultime tre issue girano attorno allo stesso problema, che merita assolutamente una precisazione ufficiale. Non è chiaro se, come pare valga per la Lombardia, i guariti in questa repository siano solo quelli provenienti dagli ospedali (e siano esclusi i guariti in isolamento domiciliare che non hanno abbiano fatto un passaggio in ospedale). Non è chiaro se i dimessi in attesa di tampone siano conteggiati anch'essi nel pool degli isolamenti domiciliari (che negherebbe quanto detto prima) o se in alternativa siano conteggiati già nei guariti prima della conferma (che risulterebbe difforme alla definizione ufficiale di guarito). Non è chiaro quali siano i criteri adottati da ogni regione.

**Comment by Rabelaiss** [comment]
@Paulsword salve, sa se la questione è stata risolta? la ringrazio

**Comment by Paulsword** [comment]
Non che io sappia

**Comment by Rabelaiss** [comment]
@umbros direi che si può chiudere, un positivo viene classificato guarito solo se il tampone ha esito negativo
