### ISSUE TITLE
Errore lettura file RAW

### ISSUE THREAD

**Issue by FrancescoMandru** [pcm-dpc/COVID-19#518]
Quando cerco di caricare il formato raw della tabella andamento nazione appare il seguente errore:

ParserError: Error tokenizing data. C error: Expected 15 fields in line 23, saw 17

I dati sono caricati nel modo seguente

nazionale_ita = pd.read_csv('https://raw.githubusercontent.com/pcm-dpc/COVID-19/master/dati-andamento-nazionale/dpc-covid19-ita-andamento-nazionale.csv')
nazionale_ita.head()

Posso evitare l'errore non considerando le seguenti righe:

b'Skipping line 23: expected 15 fields, saw 17\nSkipping line 25: expected 15 fields, saw 17\n'

**Comment by umbros** [comment]
Ciao,
utilizziamo anche noi pandas e non abbiamo questo problema. Puoi provare su altri csv?
Grazie.

**Comment by sapienzafra** [comment]
Togliendo i campi note commenti su quelle righe funziona

**Comment by emazep** [comment]
Confermo il problema: la linea 24 contiene 17 campi anziché gli attesi 15.

**Comment by xhantos** [comment]
Confermo che ottengo lo stesso errore per lo stesso file. In effetti andando a guardare direttamente il file (https://raw.githubusercontent.com/pcm-dpc/COVID-19/master/dati-andamento-nazionale/dpc-covid19-ita-andamento-nazionale.csv) alla riga 23 e alla riga 25 le note in italiano e inglese sono ognuna su due colonne, mentre lo spazio teorica sarebbe uno

**Comment by FrancescoMandru** [comment]
Esatto, ci sono dei problemi ad esempio qui:

2020-03-16T17:00:00,ITA,11025,1851,12876,10197,23073,2470,3233,2749,2158,27980,137962,nd-IT-0004,nd-IT-0006,nd-EN-0004,nd-EN-0006

Ci sono delle annotazioni in più

**Comment by umbros** [comment]
Corretto, grazie per la segnalazione @FrancescoMandru e a tutti

**Comment by emazep** [comment]
Grazie, ma il file non è stato ancora ricaricato (non è per mettere fretta: lo segnalo solo nel caso si sia dimenticato di farlo). Grazie!

**Comment by emazep** [comment]
OK grazie, a posto!

**Comment by umbros** [comment]
Ciao @emazep il file è stato caricato con l'ultima commit.
