### ISSUE TITLE
Inconstistenza dati di oggi [08/03] (Trento-Bolzano)

### ISSUE THREAD

**Issue by enrichman** [pcm-dpc/COVID-19#52]
Un paio di inconsistenze sul codice delle regioni delle province di Trento e Bolzano (21 e 22 invece di 04).

https://github.com/pcm-dpc/COVID-19/blob/master/dati-province/dpc-covid19-ita-province-20200308.csv

**Comment by miccoli** [comment]
This seems to be a recurring problem: see #29

**Comment by miccoli** [comment]
BTW, the header line is still wrong, see #43 and
https://github.com/pcm-dpc/COVID-19/blob/6101ff61043d91b22bf63f1f8694c5ba005efcf6/dati-province/dpc-covid19-ita-province-20200308.csv#L1

As per README I expect `totale_casi` and not `casi_totali`

**Comment by umbros** [comment]
Problem corrected! Now the script put 04 on Trento and 04 on Bolzano.
Thank you for suggestion.
