### ISSUE TITLE
al 6/4 Forlì è scritto male

### ISSUE THREAD

**Issue by jjgiozz** [pcm-dpc/COVID-19#520]
Tipo di issue:

- [ ] Dati mancanti o errati 
- [ ] Errore nella documentazione 
- [ ] Errore or mancanza nella dashboard 
- [ ] Problemi di visualizzazione nella dashboard 

- Regione:
- Provincia: 

## Riassunto

**Attesa:**

**Attuale:**

**Comment by umbros** [comment]
Grazie @jjgiozz, corretto.
