### ISSUE TITLE
 Significato dei numeri nel campo "in fase di definizione/aggiornamento" 

### ISSUE THREAD

**Issue by Tantormai** [pcm-dpc/COVID-19#523]
Definizione del significato dei numeri nel campo  "in fase di definizione/aggiornamento" presente in ogni Regione.

Il file dpc-covid19-ita-province.csv presenta per ogni regione un campo chiamato  "in fase di definizione/aggiornamento". I numeri contenuti in questi campi si sommano a quelli delle altre province della stessa Regione per formare il totale_casi.
Cosa rappresentano questi casi?
Tamponi effettuati nella Regione dei quali non si conosce ancora l'esito?
O tamponi dall'esito positivo non ancora attribuiti (no si capisce il perché) a una specifica provincia?
Nel primo caso il totale_casi potrebbe anche diminuire da un giorno all'altro se molti dei casi in sospeso del giorno precedente dessero esito negativo il giorno dopo e gli esiti positivi derivanti da nuovi tamponi analizzati il secondo giorno fosse inferiore a detti casi negativi del giorno precedente.
Nel secondo caso, giustificato dal fatto che i casi in corso di definizione sono già sommati ai casi totali, non si capisce cosa impedisca di assegnarli subito alla Provincia di provenienza.
Tra l'altro spesso il numero di "in fase di definizione/aggiornamento" continua a crescere nel tempo, vedi il caso della Liguria che dal 14 Marzo al 4 Aprile è passata da pochissimi casi a oltre 2000 per poi ridursi il 5 Aprile a 760 casi, nonostante che quel giorno siano stati eseguiti 960 nuovi tamponi.

**Comment by gidiemme72** [comment]
Hai lo stesso identico mio dubbio che alla fine è stato chiarito dalla Regione Liguria. Sono casi positivi che non venivano assegnati perchè le Asl cercavano l'ultimo domicilio di residenza (ed evidentemente si perdevano nella ricerca.......). Dopo varie segnalazioni, in Regione hanno deciso di "risolvere" assegnando quei 1.300 in un colpo solo il 5 Aprile in base alle Asl di competenza e non in base al domicilio.
Quindi, hanno scombinato un po' i dati provinciali (che ora il 5 Aprile hanno degli incrementi non reali), mentre quelli regionali erano e restano corretti perchè quei casi erano comunque positivi di competenza della Regione.

**Comment by AFE-admin** [comment]
Infatti, i DATI liguria non corrispondono con quelli Nazionali !

**Comment by Rabelaiss** [comment]
Ogni Regione ha due "Province" denominate "Fuori Regione / Provincia Autonoma" utile ad indicare dati relativi a soggetti fuori Regione o Provincia Autonoma e "In fase di definizione/aggiornamento", utile ad indicare i dati ancora non assegnati alle Province..

@umbros direi che si può chiudere
