### ISSUE TITLE
Possibile errore nel `totale_casi` delle province Liguri

### ISSUE THREAD

**Issue by ggbaro** [pcm-dpc/COVID-19#524]
- [X] Dati mancanti o errati
   -  `dpc-covid19-ita-province-2020040[5-7].csv` -> `totale_casi`
   - `dpc-covid19-ita-province.csv` -> `totale_casi`

- Regione:
   - *Liguria*
- Provincia:
  - *Savona*
  - *Genova*
  - *Imperia*
  - *La Spezia*

## Riassunto
L'immagine è piuttosto auto-esplicativa, non ci dovrebbe essere nessun balzo di questo tipo, nè una diminuzione del totale casi (salvo mia cattiva interpretazione del dizionario delle metriche). E' una qualche dinamica congiunturale, un problema inerente un cambio di policy/comunicazione dati o c'è qualcosa che non va nella repo?
Pare che le province liguri siano le sole ad avere questo balzo
![newplot (37)](https://user-images.githubusercontent.com/46573388/78695697-b6ac6880-78fe-11ea-95f5-76e463d74c75.png)

**Comment by umbros** [comment]
Ciao @ggbaro aggiungi i +961 di "In fase di definizione/aggiornamento" della Regione Liguria.
