### ISSUE TITLE
Licenza in lingua italiana

### ISSUE THREAD

**Issue by mydozer** [pcm-dpc/COVID-19#53]
Sarebbe utile dare riferimenti in lingua italiana anche per la licenza

https://creativecommons.org/licenses/by/4.0/deed.it

**Comment by brucellino** [comment]
Mi sono chiesto perché non viene applicato la [Italian Open Data License](https://www.dati.gov.it/content/italian-open-data-license-v20)?

**Comment by umbros** [comment]
Ciao @mydozer verrà messa in giornata la versione italiana, @brucellino non abbiamo utilizzato l'Italia Open Data License perchè ha una dimensione "italiana" e non a più largo respiro o conoscenza come la Creative Commons (CC-BY).

**Comment by pierluigicara** [comment]
a completamento di quanto già detto c'è anche l'indicazioone della Commissione Europea nella [decisione ](https://ec.europa.eu/transparency/regdoc/rep/3/2019/EN/C-2019-1655-F1-EN-MAIN-PART-1.PDF)del 22 febbraio 2019.

**Comment by nemobis** [comment]
È scorretto usare la CC-BY per questo genere di dati: quale copyright viene affermato esista? Chi sarebbe il detentore del copyright? Quale attribuzione viene richiesta? Come si fa a fornirla in una tabella, in un contatore dove ci sia spazio solo per una manciata di caratteri e cosí via? È anche self-defeating perché, se l'"autore" di questi file richiede l'attribuzione, i riutilizzatori possono semplicemente affermare di aver preso i dati da un'altra parte, e quindi si diseduca all'uso e citazione di fonti ufficiali.

Questi sono fatti nel pubblico dominio, l'unica scelta appropriata è la CC-0.

Infatti anche la decisione di cui sopra non impone certo la CC-BY laddove non abbia senso:

> Without prejudice to the preceding article, raw data, metadata or other documents of
comparable nature may alternatively be distributed under the provisions of the Creative
Commons Universal Public Domain Dedication deed (CC0 1.0).

**Comment by pierluigicara** [comment]
Il detentore del diritto in questione è il titolare del dato, cioè il Dipartimento della protezione civile in quanto il suo Rappresentante legale è il Commissario delegato alla gestione dell'emergenza e incaricato di coordinare il monitoraggio sanitario effettuato dal Ministero della Salute e darne la relativa comunicazione istituzionale. In ciascun metadato associato ai dataset è chiaramente specificato. Il diritto che viene espresso, inoltre, è il diritto attestato dalla Direttiva 96/9/CE al costitutore di una banca dati che - pur priva di carattere creativo e contenente semplici dati - ha, tuttavia, richiesto un investimento rilevante, per la quale è tutelato solo il diritto sui generis per quanto riguarda l’estrazione e il reimpiego di parti sostanziali della banca dati stessa. La licenza adottata gestisce questo tipo di autorizzazione in caso di riuso da parte di terzi.

**Comment by nemobis** [comment]
Se il Dipartimento della protezione civile afferma di possedere diritti 
sui generis su questi dati, ma non copyright, sarebbe utile dirlo 
esplicitamente. I diritti sui generis infatti esistono solo in UE.

Proprio per via dei diritti sui generis è utile usare la CC-0, che 
elimina gli inutili ostacoli da essi creati, nonché lo svantaggio 
competitivo che essi creano per le aziende e altri riutilizzatori 
italiani e UE (che si trovano a dover competere con aziende USA a cui 
tali restrizioni non si applicano). La stessa commissione UE del resto 
ha concluso che i diritti sui generis sono inutili quando non dannosi:
<https://ec.europa.eu/digital-single-market/en/news/study-support-evaluation-database-directive>

Se tuttavia si insiste a voler restringere i dati con una licenza che 
richiede l'attribuzione, è necessario usarla correttamente. In 
particolare è opportuno specificare quale attribuzione sia preferita dal 
licenziante, usando la sezione 3(a)(1)(A)(i) della licenza. Per ottenere 
i risultati desiderati senza effetti collaterali indesiderati, potrebbe 
inoltre essere utile una dichiarazione in relazione alla sezione 4(c) 
ove chiarire quali usi non siano considerati una "porzione sostanziale" 
dal licenziante, in modo che tali usi possano procedere senza attribuzione.

**Comment by umbros** [comment]
@nemobis io la faccio molto semplice... la cc by è di pubblico dominio definendo la fonte che su dati della pubblica amministrazione e quindi ufficiali è la base... altrimenti non ci sarebbe distinzione tra un soggetto che fa raccolta dati da giornali e quello pubblicato da noi.
