### ISSUE TITLE
Errore nel file dati province #531

### ISSUE THREAD

**Issue by ggbaro** [pcm-dpc/COVID-19#532]
SOLUZIONE
#531

- [X] Dati mancanti o errati  https://github.com/pcm-dpc/COVID-19/blob/master/dati-province/dpc-covid19-ita-province.csv
- [ ] Errore nella documentazione 
- [ ] Errore or mancanza nella dashboard 
- [ ] Problemi di visualizzazione nella dashboard 

![image](https://user-images.githubusercontent.com/46573388/78808084-3b61ba00-79c5-11ea-8de0-05f5003296c3.png)

**Comment by umbros** [comment]
corretto. grazie @ggbaro
