### ISSUE TITLE
Grafico nuovi positivi

### ISSUE THREAD

**Issue by massimo7000** [pcm-dpc/COVID-19#533]
Credo che il grafico dei nuovi positivi contiene dai errati, ieri erano +880 circa, sbagliati anche quelli di oggi +1125 circa, in questo momento segna +3000 circa ieri e +4000 circa oggi.

http://opendatadpc.maps.arcgis.com/apps/opsdashboard/index.html#/b0c68bce2cce478eaac82fe38d4138b1

Saluti

**Comment by umbros** [comment]
Ciao @massimo7000 i dati riportati sono corretti il calcolo nuovi positivi è dato da totale casi di oggi - totale casi di ieri.
