### ISSUE TITLE
Leviamo il numero di casi totali e quello di isolamento domiciliare

### ISSUE THREAD

**Issue by andy835** [pcm-dpc/COVID-19#539]
Che senso ha mettere un report dove viene inserito i positivi giornalieri + i deceduti giornalieri + i guariti giornalieri?
Che senso ha mettere un report dove chi è in isolamento domiciliare ha zero o pochi sintomi? spero in una risposta

**Comment by umbros** [comment]
@andy835 se non si vuole tenere conto di campi del dataset è assolutamente possibile farlo e focalizzarsi su quelli che si ritiene opportuno utilizzare per le proprie analisi/scopi.
