### ISSUE TITLE
Il link al download dei dati per le shape delle aree misure di contenimento non è corretto.

### ISSUE THREAD

**Issue by alemar11** [pcm-dpc/COVID-19#54]
Il link al download dei dati per le shape delle aree misure di contenimento non è corretto.

- link attuale:
https://github.com/pcm-dpc/COVID-19/tree/master/shape-aree-contenimento

- link (presumibilmente) corretto:
https://github.com/pcm-dpc/COVID-19/tree/master/aree

<img width="328" alt="Schermata 2020-03-08 alle 22 07 53" src="https://user-images.githubusercontent.com/1273940/76171312-e8a89e80-6189-11ea-82a4-b3049d094794.png">

**Comment by umbros** [comment]
Corretto, grazie!
