### ISSUE TITLE
Note json - Almeno una delle note è in lingua inglese

### ISSUE THREAD

**Issue by mydozer** [pcm-dpc/COVID-19#543]
- [X ] Dati mancanti o errati dpc-covid19-ita-note-it.json

{
        "codice": "dc-IT-0001",
        "data": "2020-04-12T17:00:00",
        "dataset": "dati-province",
        "stato": "ITA",
        "codice_regione": 4,
        "regione": "P.A. Bolzano",
        "codice_provincia": 21,
        "provincia": "Bolzano",
        "sigla_provincia": "BZ",
        "tipologia_avviso": "data correction",
        "avviso": "recalculation of informations",
        "note": "recalculation recovered (-110 compared to yesterday)"
    }
Sarebbe preferibile avere le informazioni in lingua italiana. Se necessario il supporto multilingua aggiungere un ulteriore file con le taduzioni in lingua desiderata.

Grazie. Buona Pasqua!!!

**Comment by umbros** [comment]
grazie della segnalazione @mydozer errore nello script che lo genera per il dataset province. Corretto!
