### ISSUE TITLE
Note json - L'attributo dataset è cambiato

### ISSUE THREAD

**Issue by mydozer** [pcm-dpc/COVID-19#544]
- [ X] Dati mancanti o errati dpc-covid19-ita-note-it.json

E' cambiato l'insieme dei valori attribuiti dataset nel file delle note.
prima
dati_regioni
andamento_nazionale
dati_province

adesso
dati-regioni
dati-andamento-nazionale
dati-province

 {
        "codice": "nd-IT-0010",
        "data": "2020-03-18T17:00:00",
        "dataset": "dati-province",
        "stato": "ITA",
        "codice_regione": 8,
        "regione": "Emilia-Romagna",
        "codice_provincia": 34,
        "provincia": "Parma",
        "sigla_provincia": "PR",
        "tipologia_avviso": "nessun dato",
        "avviso": "non sono stati comunicati dati",
        "note": ""
    },
    {
        "codice": "nd-IT-0011",
        "data": "2020-03-18T17:00:00",
        "dataset": "dati-regioni",
        "stato": "ITA",
        "codice_regione": 8,
        "regione": "Emilia-Romagna",
        "codice_provincia": 34,
        "provincia": "Parma",
        "sigla_provincia": "PR",
        "tipologia_avviso": "nessun dato",
        "avviso": "non sono stati comunicati dati",
        "note": ""
    },
    {
        "codice": "nd-IT-0012",
        "data": "2020-03-18T17:00:00",
        "dataset": "dati-andamento-nazionale",
        "stato": "ITA",
        "codice_regione": 8,
        "regione": "Emilia-Romagna",
        "codice_provincia": 34,
        "provincia": "Parma",
        "sigla_provincia": "PR",
        "tipologia_avviso": "nessun dato",
        "avviso": "non sono stati comunicati dati",
        "note": ""
    }

Sarebbe preferibile non modificarlo ulteriormente perché crea discontinuità nelll'interfaccia di integrazione con i dati.

Grazie!!

**Comment by umbros** [comment]
Ciao @mydozer i valori sono stati rinominati come le cartelle in cui sono contenuti i dati.
