### ISSUE TITLE
Informazioni mancanti

### ISSUE THREAD

**Issue by marcobambini** [pcm-dpc/COVID-19#547]
Avrei qualche domanda e spero possiate darmi qualche risposta:
1. Perché i Dati per Regione contengono più informazioni dei Dati per Provincia (che contiene il solo valore di totale_casi)?
2. Perché i Dati per Provincia non contengono il campo Comune?

Esite un repo dove posso trovare le informazioni mancanti?  Il sindaco del mio Comune vorrebbe sapere l'andamento anche dei guariti in modo da poter rassicurare le popolazione.

**Comment by dace74** [comment]
> Esite un repo dove posso trovare le informazioni mancanti? Il sindaco del mio Comune vorrebbe sapere l'andamento anche dei guariti in modo da poter rassicurare le popolazione.

Il piemonte aveva fatto una info su 
https://www.regione.piemonte.it/web/covid-19-mappa-dei-contagi-piemonte
(tralascio la fruibilità della cosa in termini pratici).
Il Sindaco può comunque chiedere , in quanto sua prerogativa, all'ASL i dati, anonimi, relativi al Suo comune.
Ammesso che l'ASL di zona abbia la situazione sopratutto dei domiciliari.

**Comment by marcobambini** [comment]
Grazie
