### ISSUE TITLE
Rendere in lingua inglese i dataset e nomi dei campi

### ISSUE THREAD

**Issue by pigreco** [pcm-dpc/COVID-19#548]
Ho letto nei CHANGELOG l'ipotesi in oggetto.

Manifesto il mio dissenso.

grazie.

**Comment by umbros** [comment]
Lo abbiamo messo in ipotesi proprio per raccogliere indicazioni. Grazie @pigreco e invito altri a dare il proprio parere.

**Comment by Achab94** [comment]
Intendete anche _inglesizzare_ i nomi di province/regioni (se sì, come?), o solo i nomi delle colonne (variabili) del dataset? 
Nel secondo caso penso che per chiunque di noi possieda progetti/dashboard che utilizzano questi dataset, basti fare nu CTRL+F "nome vecchio" -> sostituisci con "nome_nuovo". Io uso R e su RStudio si fa in mezzo secondo, ma immagino che valga lo stesso per qualunque editor di codice.

**Comment by bfabio** [comment]
Ho paura che sia tardi per cambiare i file JSON, ma credo sia preferibile e si possa fare almeno per le API in arrivo ([CHANGELOG.md#prossimi-aggiornamenti](https://github.com/pcm-dpc/COVID-19/blob/master/CHANGELOG.md#prossimi-aggiornamenti))

**Comment by umbros** [comment]
Come impatto lo vedo semplice, abbiamo tanta richiesta anche all'estero, abbiamo ipotizzato che per 5 giorni saranno tenuti label italiane (legacy) e altri flussi in inglese e poi il passaggio a solo label inglesi. Nomi regioni non cambiano

**Comment by pigreco** [comment]
> Come impatto lo vedo semplice, abbiamo tanta richiesta anche all'estero, abbiamo ipotizzato che per 5 giorni saranno tenuti label italiane (legacy) e altri flussi in inglese e poi il passaggio a solo label inglesi. Nomi regioni non cambiano

Domanda: perché favorire l'estero e non gli italiani o chi legge l'italiano?? La traduzione in inglese che vantaggio ha rispetto a mantenerlo in italiano??

grazie per le eventuali risposte e buon lavoro

**Comment by ngshya** [comment]
non è più semplice mantenere tutto in italiano e per chi vuole i campi in inglese fornire un file nuovo a parte con le traduzioni dei campi e dei file da italiano a inglese (come c'è già in README)? 

non tutti purtroppo leggono le issues o le modifiche di README tutti i giorni, un cambio di nomi di tutte le colonne e di tutti i file potrebbe rompere tantissime pipelines automatizzate e deployate che ci sono già e che dipendono da questo repo.
