### ISSUE TITLE
ERRORE TAMPONI TOTALI MARCHE DEL 13/04/2020

### ISSUE THREAD

**Issue by UserMike1975** [pcm-dpc/COVID-19#549]
NELLA TABELLA RIEPILOGATIVA DELLE REGIONI, E' ERRATO IL DATO DEI TAMPONI MARCHE.
LA TABELLA DI OGGI RIPORTA UN TOTALE DI 28.379, A FRONTE DEL DATO DI 21.057 DI IERI.
7.000 TAMPONI IN UN GIORNO E' IMPOSSIBILE PER LE MARCHE.
INOLTRE LA REGIONE MARCHE ATTRAVERSO IL GORES HA RIPORTATO COME DATO DEI TEST EFFETUATI 21.513.
LINK: http://www.regione.marche.it/portals/0/Salute/CORONAVIRUS/DatiGORES/GORESgiallo13042020_12.pdf

Tipo di issue:

- [ ] Dati mancanti o errati 
- [ ] Errore nella documentazione 
- [ ] Errore or mancanza nella dashboard 
- [ ] Problemi di visualizzazione nella dashboard 

- Regione:
- Provincia: 

## Riassunto

**Attesa:**

**Attuale:**

**Comment by umbros** [comment]
Ciao @UserMike1975 questo è quanto comunicato da Regione Marche a Ministero della Salute, vediamo domani se comunicano un errore.

**Comment by UserMike1975** [comment]
ok, cmq errore evidente.
