### ISSUE TITLE
Differenza tra variazione_totale_positivi e nuovi_positivi

### ISSUE THREAD

**Issue by FrancescoMandru** [pcm-dpc/COVID-19#550]
Non ho ben capito la differenza tra queste due colonne e cosa rappresentano

**Comment by picomiles** [comment]
**variazione_totale_positivi** = totale_positivi giorno corrente - totale_positivi giorno precedente

**nuovi_positivi** = totale_casi giorno corrente - totale_casi giorno precedente

Il campo **totale_positivi** accoglie il numero degli ammalati del giorno corrente (somma di soggetti ospedalizzati e soggetti in isolamento domiciliare)

Il **campo totale_casi** è la somma degli ammalati (totale_positivi), dei guariti/dimessi e dei deceduti al giorno corrente.

**Comment by Sanco-RR** [comment]
Buonasera

Definirei i **nuovi_positivi** in altro modo:
Sono tutte quelle persone che, nelle ultime 24 ore, dopo essere state sottoposte a tampone, sono risultate positive. E' un valore che viene dalla positività al tampone.
E' chiaro che se il valore di questi nuovi_positivi viene sommato a quello del totale_casi al giorno precedente si ottiene il totale_casi al giorno corrente.

Definirei anche il **totale_casi** in modo diverso:
Sono tutte quelle persone che, dall'inizio dell'infezione, dopo essere state sottoposte a tampone, sono risultate positive. Anche questo valore viene dalla positività al tampone.

**Comment by maxdevblock** [comment]
Il `totale_positivi` corrisponde agli I(nfetti) nel modello epidemiologico SIR (S -> I -> R), quindi sono gli attuali casi risultati positivi ai test, non guariti e non deceduti. La sua variazione `variazione_totale_positivi` corrisponde dunque al ∆I giornaliero nel modello SIR.
Il `totale_casi` è invece il totale di tutti i contagi avvenuti dall'inizio ed è uguale a I + D(edecuti) + G(uariti) dove D+G=R(imossi) nel modello SIR.
Il dato infetti è l'unico a non essere cumulativo: mentre sia il totale dei casi che guariti e deceduti hanno andamento sigmoide, gli infetti possono essere descritti solo dalla somma T - R (che risulta in una gaussiana asimmetrica).

**Comment by umbros** [comment]
coretto quanto riportato da @maxdevblock
