### ISSUE TITLE
Errore acquisizione file dpc-covid19-ita-province.csv

### ISSUE THREAD

**Issue by marcogiannuzzi90** [pcm-dpc/COVID-19#551]
Ciao,

ho notato che oggi il file dpc-covid19-ita-province.csv anzichè avere la classica struttura tabellare, oggi risulta un file delimitato con la virgola.
L'ho notato perchè attraverso uno strumento di BI, ho schedulato l'acquisizione automatica del link e fino a stasera non mi dava errori.

![image](https://user-images.githubusercontent.com/62606604/79148949-a3017600-7dc6-11ea-9f01-a6eae8cdf6f0.png)

quando invece fino a ieri la struttura era come quella delle regioni che è la seguente

![image](https://user-images.githubusercontent.com/62606604/79149005-c0cedb00-7dc6-11ea-8c53-d9a22b202133.png)

**Comment by dace74** [comment]
Ciao,
ho verificato ma c'è il file giusto
