### ISSUE TITLE
Errore dati dimessi_guariti P.A. Bolzano

### ISSUE THREAD

**Issue by VenturiniLeonardo** [pcm-dpc/COVID-19#552]
I dati del numero di dimessi_guariti P.A. Bolzano dal giorno 11/04/2020 risultano errati in quanto passano da un numero di 488, al giorno successivo (12/04), a 378. Com'è possibile ciò?

**Comment by pierluigicara** [comment]
Se guardi il log quotidiano riportato nel file Note trovi un riscontro.
