### ISSUE TITLE
Pagina con grafici interattivi

### ISSUE THREAD

**Issue by mrmatd** [pcm-dpc/COVID-19#553]
Buongiorno, ho creato una pagina con dei grafici interattivi sull’andamento dei casi, dei deceduti e dei tamponi nelle varie regioni italiane. Per tener conto del diverso numero di abitanti di quest'ultime ho utilizzato i dati relativi (nello specifico i dati per milione di abitanti).

Link: https://mrmatd.github.io/Covid-19-ITA/

**Comment by umbros** [comment]
Grazie
