### ISSUE TITLE
Marche differenza sui tamponi tra voi e la regione

### ISSUE THREAD

**Issue by andy835** [pcm-dpc/COVID-19#554]
loro 21949
http://www.regione.marche.it/portals/0/Salute/CORONAVIRUS/DatiGORES/GORESgiallo14042020_12.pdf

voi 29160
perchè?

**Comment by Sanco-RR** [comment]
Buonasera
mi sembrava di aver letto ieri un post relativo ad un probabile errore. Il dato della PC era di 28.379 contro quello comunicato dalla Regione di 21.513. 
Forse si trascinano questo errore da ieri. Non so, ma non trovo più il post.

**Comment by Sanco-RR** [comment]
Trovato!
Discussione chiusa ma non so perchè.
https://github.com/pcm-dpc/COVID-19/issues/549

**Comment by umbros** [comment]
Ciao @andy835 Regione Marche riferisce dei soggetti singoli testati non è il totale tamponi. Speriamo che questa informazione si stabilizzi per tutte le regioni.
