### ISSUE TITLE
Dati errati in FVG 14/04

### ISSUE THREAD

**Issue by MITEL-UNIUD** [pcm-dpc/COVID-19#555]
- [x] Dati mancanti o errati 
- [ ] Errore nella documentazione 
- [ ] Errore or mancanza nella dashboard 
- [ ] Problemi di visualizzazione nella dashboard 

- Regione: Friuli - Venezia Giulia
- Provincia: 

## Riassunto
I dati relativi ai guariti del  Friuli Venezia Giulia, e quelli dipendenti,  in data 14/04/2020 sono errati.

**Attesa:**

Il comunicato della Regione:
Palmanova, 14 apr - I casi accertati positivi al Coronavirus in
Friuli Venezia Giulia sono 2.520, con un incremento di 38 unità
rispetto a ieri. I totalmente guariti sono 628, mentre i
clinicamente guariti (persone senza più sintomi ma non ancora
negative al tampone) sono 380. Sono 4 i decessi in più rispetto
alla comunicazione di ieri, che portano a 206 il numero
complessivo di morti da Covid-19.

Lo ha comunicato il vicegovernatore con delega alla Salute e
Protezione civile, Riccardo Riccardi, dalla sede operativa di
Palmanova.

Per quanto riguarda i decessi, quello di Trieste è il territorio
più colpito con 106; seguono Udine (59), Pordenone (38) e Gorizia
(3).
Sono 28 i pazienti che attualmente si trovano in terapia
intensiva, mentre i ricoverati in altri reparti risultano essere
166 e le persone in isolamento domiciliare sono 1112. 

       "isolamento_domiciliare": 1112,
        "totale_positivi": 1306,
        "variazione_totale_positivi": -1,
        "nuovi_positivi": 38,
        "dimessi_guariti": 1008,

**Attuale:** 
       "isolamento_domiciliare": 705,
        "totale_positivi": 899,
        "variazione_totale_positivi": -408,
        "nuovi_positivi": 38,
        "dimessi_guariti": 1415,

**Comment by andy835** [comment]
hanno fatto confusione con i dati di ieri mettendo la data di oggi
Bilancio coronavirus Udine Friuli, 14 aprile 2020
„

casi accertati positivi al Coronavirus in Friuli Venezia Giulia sono 2.520, con un incremento di 38 unità rispetto a ieri, quando il dato ha fatto registrare un più 51. I totalmente guariti sono 628, mentre i clinicamente guariti (persone senza più sintomi ma non ancora negative al tampone) sono 788. Sono 4 i decessi in più rispetto alla comunicazione di ieri, che portano a 206 il numero complessivo di morti da Covid-19.
“

Potrebbe interessarti: https://www.udinetoday.it/attualita/bilancio-coronavirus-udine-friuli-14-aprile-2020.html

**Comment by MITEL-UNIUD** [comment]
In realtà dopo il primo comunicato ne ha rilasciato un secondo, che è quello che ho messo io.

**Comment by umbros** [comment]
Hanno inviato i dati corretti oggi - vedi note

**Comment by MITEL-UNIUD** [comment]
Nel dataset però rimane il dato di ieri prima dell'errata corrige.
