### ISSUE TITLE
Numero dei tamponi

### ISSUE THREAD

**Issue by FrancescoMandru** [pcm-dpc/COVID-19#556]
Non capisco se il numero di tamponi riportati dalla protezione Civile sia il numero di tamponi che sono stati fatti oggi o il numero di tamponi che sono stati analizzati oggi

**Comment by mimlar** [comment]
Per quanto riguarda la Basilicata, sono certo che il numero indicato dalla Protezione Civile corrisponde ai tamponi analizzati nella giornata.

**Comment by dace74** [comment]
> Non capisco se il numero di tamponi riportati dalla protezione Civile sia il numero di tamponi che sono stati fatti oggi o il numero di tamponi che sono stati analizzati oggi

Se cerchi nelle varie ISSUES l'argomento è stato già trattato ampiamente.
CIAO

PS:credo che non ci sia una linea nazionale e quindi poca normalizzazione del dato sul territorio nazionale.

**Comment by Alexwilmac** [comment]
A dir la verità è piuttosto chiaro che è il totale cumulato, visto che aumenta sempre. 
Anche perché, se fosse il dato giornaliero, sommandoli tutti vorrebbe dire che, al 18/4 avrebbero fatto
21 864 181 tamponi... ;)

**Comment by dace74** [comment]
> A dir la verità è piuttosto chiaro che è il totale cumulato, visto che aumenta sempre.
> Anche perché, se fosse il dato giornaliero, sommandoli tutti vorrebbe dire che, al 18/4 avrebbero fatto
> 21 864 181 tamponi... ;)

@Alexwilmac no bè credo che il quesito fosse relativo al dato giornaliero:quelli comunicati sono i tamponi effettuati nella giornata X o processati nella giornata X? Io posso fare anche 1000 tamponi ma se poi ne processo 100 quel "1000" ha tutta un'altra lettura.

**Comment by Alexwilmac** [comment]
Il dato giornaliero ce lo ricaviamo da soli, per differenza rispetto al giorno precedente: non vedo la difficoltà.
Quello che dicono a parole, ripeto, non lo so perché non li ascolti. Qui abbiamo i dati ufficiali e non c'è nemmeno bisogno della laurea in statistica per interpretarli ;) Basta leggerli e fare una sottrazione...

**Comment by Patrizia1972** [comment]
Il problema rimane. Notizia di oggi il numero di tamponi effettuati non corrisponde a quello fatto la prima volta al paziente perchè a oggi, 20.4.2020, i tamponi risultano 1.398.024 però le persone che li hanno fatti sono 943.951... quindi ogni persona in media ha fatto un tampone e mezzo... (il dato scoorporato giorno per giorno si può avere?) ... inoltre il numero di tamponi giornaliero non ho capito se corrisponde al numero di tamponi effettuati e mandati in laboratorio oppure al numero di tamponi di cui si ha l'esito in quella giornata, perchè nel primo caso il risultato di quei tamponi può essere messo in relazioni con i positivi per lo meno del giorno dopo, ma non nel giorno stesso, visto che il tempo di analisi di un tampone è di almeno 24h.... scusate ma non mi occupo di statistica sanitaria però volendo utilizzare questi dati, vorrei essere sicura di utilizzarli nel modo corretto... oppure evitare di utilizzarli se non sono correttamente interpretabili.

**Comment by Alexwilmac** [comment]
Per quanto riguarda la prima questione, pur senza essere un addetto ai lavori, conosco personalmente persone che hanno avuto più tamponi e quindi è normalissima questa discrepanza.
D'altronde, in questo caso mi sento di avallare questa scelta: in fondo (e qui già entriamo nella seconda questione) quello che a me (personalissimamente) interessa è sapere, in un dato giorno, quale % di tamponi è risultata positiva (ossia il numero di nuovi casi divisa per i tamponi di quel giorno).
E per finire solo con la seconda questione, è chiaro che c'è il problema del lasso di tempo fra quando viene effettuato il tampone e quando viene conosciuto il risultato; ma qui non se ne esce, con i mezzi attuali (e quindi con i dati che ne scaturiscono). 
Ora, a parte il fatto che si potrebbe anche ragionevolmente calcolare un tempo medio di "emissione" dei risultati e, a quel punto, usare come denominatore i tamponi fatti in quel giorno. 
Ma, il punto è che, da statistici dobbiamo capire che il problema è relativamente importante nel senso che, immaginando ad es. che il tempo per arrivare al risultato fosse di UN giorno, non è che il denominatore (ossia i nuovi tamponi) sia stato mai diversissimo da un giorno all'altro (specie da alcune settimane a questa parte).
È facile vedere che la serie delle % giornaliere di tamponi positivi, cambia poco rapportando i nuovi casi di oggi ai nuovi tamponi di oggi o invece rapportandoli ai nuovi di ieri.
Tra l'altro, una serie giornaliera non è molto indicata, secondo me, in fenomeni di questo tipo: molto meglio una serie perequata.
Io, per es., me la sono perequata a 5gg; in televisione ho sentito che l'hanno perequata a 7.
Solo con una perequazione abbiamo restituito un andamento più regolare e, soprattutto, a quel punto che si rapporti al giorno attuale o al precedente o a quello che volete, diventa ancor meno influente.

**Comment by Patrizia1972** [comment]
Concordo in parte con quanto dici, ma riporto le tue parole: "quello che a me (personalissimamente) interessa è sapere, in un dato giorno, quale % di tamponi è risultata positiva (ossia il numero di nuovi casi divisa per i tamponi di quel giorno)." ...se non sai se l'esito dei tamponi è di quel giorno non ha molto senso questo rapporto e mi sta bene che puoi "risolverlo" con una perequazione, però se in mezzo ci sono anche i tamponi ripetuti sulle stesse persone (e non sai quanti ne fanno alla stessa persona, perchè per i guariti sono almeno 2) il rumore che introduci è troppo per passarci sopra con una media... inoltre, ma forse sarà che io sono molto pignola quando metto a disposizione dei dati... se sono in grado di dirci oggi il numero delle persone testate... dici che non è possibile ottenere quel dato giornaliero o cumulato?...  il numero di tamponi poi non è così stabile... così come non lo è quello dei positivi... quindi immagino che errore + errore... generi andamenti (e non parlo di conclusioni perchè non mi permetterei mai, visto che non è il mio campo) falsati... per quanto riguarda le medie io le sto facendo a 5, 7 e 10 giorni per vedere l'andamento indipendentemente dalle fluttuazioni giornaliere. Ho letto un articolo molto interessante su StatGroup-19 su FB che incrocia le medie mobili a più distanze per avere conferma del cambio di tendenza dell'andamento di un fenomeno...

**Comment by umbros** [comment]
Ciao, i tamponi sono riferiti ai risultati dei tamponi pervenuti alla data di oggi. Abbiamo aggiunto i casi testati

**Comment by Alexwilmac** [comment]
Quindi, per essere sicuro di aver capito: casi testati sono il numero di persone che hanno fatto il tampone almeno una volta, giusto?
Mentre il numero dei tamponi, come ovvio, conteggia anche test multipli sulla stessa persona.
