### ISSUE TITLE
demo pygeoapi con dati live in formato OGC API - Features

### ISSUE THREAD

**Issue by francbartoli** [pcm-dpc/COVID-19#557]
## Riassunto

[pygeoapi](https://pygeoapi.io/) è un progetto open source sviluppato in python che fornisce l'implementazione della nuova generazione di standard geografici [OGC API](http://www.ogcapi.org/) basata sulla moderna specifica [OpenAPI](https://www.openapis.org/), evoluzione dei precedenti WMS, WFS, WCS e WPS.

## Interesse pubblico

Il server espone e ripubblica una REST API web con i dati globali della JHU e quelli del DPC dai servizi FeatureServer dei rispettivi ArcGIS secondo lo standard di riferimento [OGC API - Features](http://www.ogcapi.org/) (la nuova generazione di servizi geografici a cura dell'[OGC](https://www.ogc.org/)) esponendo un endpoint _OpenAPI_ a questo indirizzo [https://demo.pygeoapi.io/covid-19/openapi?f=html](https://demo.pygeoapi.io/covid-19/openapi?f=html).
Il servizio è navigabile da browser tramite formato html o consumabile in formato GeoJSON, alcune url di esempio possono essere trovate qui [https://github.com/geopython/demo.pygeoapi.io/tree/master/services/pygeoapi_covid-19#italy](https://github.com/geopython/demo.pygeoapi.io/tree/master/services/pygeoapi_covid-19#italy).

Non appena verrà fatto il merge di questa PR [https://github.com/geopython/pygeoapi/pull/410](https://github.com/geopython/pygeoapi/pull/410) sarò in grado di esporre nelle stesse modalità tutti i dati presi direttamente da questo repository in modo da avere tutta la serie temporale che può essere interrogata in modalità live. Il layer proveniente da ArcGIS espone solo il dato attuale.

Spero possa essere utile a qualcuno. cc @umbros

**Comment by francbartoli** [comment]
Dimenticavo:

credits @aborruso per l'idea di utilizzare direttamente il driver CSV in GDAL piuttosto che il server ESRI.

**Comment by francbartoli** [comment]
Update:

Abbiamo aggiornato la configurazione ed ora ci sono tutte e due le collezioni delle serie temporali assieme a quelle attuali:

- serie temporale regioni - [https://demo.pygeoapi.io/covid-19/collections/cases_italy_timeseries_per_region](https://demo.pygeoapi.io/covid-19/collections/cases_italy_timeseries_per_region)

- ultima giornata regioni - [https://demo.pygeoapi.io/covid-19/collections/cases_italy_per_region_latest](https://demo.pygeoapi.io/covid-19/collections/cases_italy_per_region_latest)

- serie temporale province - [https://demo.pygeoapi.io/covid-19/collections/cases_italy_timeseries_per_province](https://demo.pygeoapi.io/covid-19/collections/cases_italy_timeseries_per_province)

- ultima giornata province [https://demo.pygeoapi.io/covid-19/collections/cases_italy_per_province_latest](https://demo.pygeoapi.io/covid-19/collections/cases_italy_per_province_latest)

Alcune possibili query:

- serie temporale nel Lazio: [https://demo.pygeoapi.io/covid-19/collections/cases_italy_timeseries_per_region/items?denominazione_regione=lazio&f=json](https://demo.pygeoapi.io/covid-19/collections/cases_italy_timeseries_per_region/items?denominazione_regione=lazio&f=json)

- serie temporale nelle regioni del sud : [https://demo.pygeoapi.io/covid-19/collections/cases_italy_per_region/items?bbox=10.616226,36.721480,18.855972,41.738721&f=json](https://demo.pygeoapi.io/covid-19/collections/cases_italy_per_region/items?bbox=10.616226,36.721480,18.855972,41.738721&f=json)

serie temporale nelle province del Lazio: [https://demo.pygeoapi.io/covid-19/collections/cases_italy_timeseries_per_province/items?denominazione_regione=lazio&f=json](https://demo.pygeoapi.io/covid-19/collections/cases_italy_timeseries_per_province/items?denominazione_regione=lazio&f=json)

serie temporale della provincia di Rome: [https://demo.pygeoapi.io/covid-19/collections/cases_italy_timeseries_per_province/items?denominazione_provincia=roma&f=json](https://demo.pygeoapi.io/covid-19/collections/cases_italy_timeseries_per_province/items?denominazione_provincia=roma&f=json)

serie temporale nelle province del sud: [https://demo.pygeoapi.io/covid-19/collections/cases_italy_timeseries_per_province/items?bbox=10.616226,36.721480,18.855972,41.738721&f=json](https://demo.pygeoapi.io/covid-19/collections/cases_italy_timeseries_per_province/items?bbox=10.616226,36.721480,18.855972,41.738721&f=json)

**Comment by umbros** [comment]
Grazie @francbartoli
