### ISSUE TITLE
Conteggio decessi

### ISSUE THREAD

**Issue by dace74** [pcm-dpc/COVID-19#558]
Saluti a tutti, ho cercato tra le varie ISSUES ma non ho trovato riscontro.
Il numero "deceduti" nella colonna come viene computato?
Mi spiego:si fa riferimento ai fogli ISTAT(compilati in reparto) del giorno precedente la pubblicazione dei dati o si considerano anche decessi casalinghi?
Si considerano decessi di persone che erano state tamponate e quindi COVID+ o nel computo si fa riferimento anche a deceduti non tamponati?

Chiedo in quanto in questi ultimi 4 giorni si stanno compensando le riduzioni di posti letto in RIA con un numero di decessi che oscilla sempre tra le 500 e 600 persone al giorno e considerando nell'insieme anche le dimissioni non trovo riscontro se non nel computare anche esterni(es. decessi in RSA, che però molte volte non sono stati tamponati e non hanno diagnosi finale di COVID).

Grazie.

**Comment by Kisswolf72** [comment]
seguo

**Comment by Sanco-RR** [comment]
Buonasera;
da quello che posso capire guardando le tabelle, e da quello che ho sentito nelle interviste, tutti i deceduti sono stati tamponati risultando positivi.

**Comment by Pieffe68** [comment]
Alcuni dati odierni, cumulativi, riportano un valore inferiore rispetto a quelli di ieri.
Ad esempio i deceduti totali di ogni regione...
Sono state riviste le cartelle mediche... e quindi sono usciti dal totale COVID-19 ?

**Comment by Pieffe68** [comment]
Alcuni dati odierni, cumulativi, riportano un valore inferiore rispetto a quelli di ieri. In particolare, i deceduti totali di ogni regione...
Ad esempio, Lombardia:
fino a ieri, deceduti 11377
compresi quelli di oggi, deceduti 10511

Sono state forse riviste le cartelle mediche e sono stati quindi tolti casi dal totale COVID-19 ?
Ciò accade in tutte le Regioni perchè oggi sono stati tutti aggiornati in un colpo solo?
Se si: Che valore hanno avuto le correzioni? Ogni quanto tempo sono validati i dati da Roma? Era già accaduto che nella sere storica fossero tolti casi?

**Comment by dace74** [comment]
> Buonasera;
> da quello che posso capire guardando le tabelle, e da quello che ho sentito nelle interviste, tutti i deceduti sono stati tamponati risultando positivi.

Delle varie interviste ho capito che c'è poco da prendere per assodato:anche perchè a questo punto mi sorge la domanda:se OGNI deceduto è tamponato ho tamponi in eccesso che non mi spiego.
Es. giorno 29-03 Regione Piemonte
estrapolo: totale positivi 7268 / deceduti 684 /tamponi 24058 
E' chiaro che c'è un surplus di tamponi per cui non ho la sicurezza che in quei 24mila ci siano tutti i deceduti, oltre ad avere un plus di tamponi che a questo punto non so con che criterio sono fatti e distribuiti( senza considerare che non viene dato il gap di errore, che c'è per forza operatore e/o macchina dipendente).

Quindi il mio quesito resta:come computo la mortalità anche perchè in scheda ISTAT in reparto/struttura/domicilio non si indica come causa di morte "COVID" quindi ritengo sia fondamentale capire come si arriva al numero di morti per comprendere se si è sovrastimato l'indice di mortalità (non credo!) o sottostimato.
In considerazione che c'è sempre quel grandissimo gap statistico per cui la Lombardia, numeri attuali alla mano, avrebbe una mortalità del virus qualcosa come 6/7 volte l'indice medio mondiale di mortalità (che si aggira al 3%).

**Comment by Paulsword** [comment]
Scusa @dace74 ma mi sfugge come tu possa sperare di definire se i decessi siano tutti, troppi o troppo pochi in base a questa repository. Certamente non ci sono qui i deceduti non confermati COVID, di cui sapremo forse da ISTAT sulla base delle cancellazioni anagrafiche. Per il resto il surplus di tamponi è evidentemente costituito dai controlli e dai tanti test negativi.

**Comment by morano-ma** [comment]
Nei decessi vengono considerati tutti quelli che sono deceduti e che sono risultati positivi al tampone.
Il surplus dei tamponi è dato dal fatto che il conteggio non riporta solo i tamponi risultati positivi e degli eventuali deceduti, ma comprende anche tutti quei tamponi che sono risultati o negativi già dalla prima analisi o che sono tamponi di controllo (da quanto dichiarato una persona può ricevere dai 3 tamponi in su). Per quanto riguarda invece l'indice di mortalità darne ora una definizione certa è, a mio avviso, azzardato, in quanto:

- i dati del contagio possono essere considerati parziali (il che non vuol dire che siano errati): sappiamo bene che non è possibile al giorno d'oggi effettuare tamponi su tutta la popolazione, il che permetterebbe di vedere sia l'effettiva diffusione del virus, sia eventualmente modificare la sua incidenza;

- bisogna valutare, la più volte citata, distinzione tra "morti col coronavirus" e "morti a causa del coronavirus", (analisi che viene fatta successivamente dal ISS) che certamente non diminuisce il numero di decessi, ma sicuramente fornirà un quadro più completo della situazione.

**Comment by dace74** [comment]
> Scusa @dace74 ma mi sfugge come tu possa sperare di definire se i decessi siano tutti, troppi o troppo pochi in base a questa repository. Certamente non ci sono qui i deceduti non confermati COVID, di cui sapremo forse da ISTAT sulla base delle cancellazioni anagrafiche. Per il resto il surplus di tamponi è evidentemente costituito dai controlli e dai tanti test negativi.

Bè @Paulsword  ma infatti quello che sostengo è che parlare di "decessi" ed usarlo come dato di rebound per capire se l'andamento è positivo o meno nella fase lockdown ha ben poco senso se non chiariamo cosa mettiamo nel calderone dei decessi. Solo COVID+? Solo tamponati? Prendiamo le schede ISTAT del giorno prima(dove non si mette come causa di morte il COVID)?
Senza considerare che "decessi" senza dire il "dove" ha ancora meno senso:ospedalieri?domicilio?RSA?
Ad oggi più si va avanti e più avvallo chi ancora tempo addietro poneva dubbi sull'utilità di maneggiare questi dati che sono oltremodo grezzi.

**Comment by dace74** [comment]
> Nei decessi vengono considerati tutti quelli che sono deceduti e che sono risultati positivi al tampone.
> Il surplus dei tamponi è dato dal fatto che il conteggio non riporta solo i tamponi risultati positivi e degli eventuali deceduti, ma comprende anche tutti quei tamponi che sono risultati o negativi già dalla prima analisi o che sono tamponi di controllo (da quanto dichiarato una persona può ricevere dai 3 tamponi in su). Per quanto riguarda invece l'indice di mortalità darne ora una definizione certa è, a mio avviso, azzardato, in quanto:
> 
> * i dati del contagio possono essere considerati parziali (il che non vuol dire che siano errati): sappiamo bene che non è possibile al giorno d'oggi effettuare tamponi su tutta la popolazione, il che permetterebbe di vedere sia l'effettiva diffusione del virus, sia eventualmente modificare la sua incidenza;
> * bisogna valutare, la più volte citata, distinzione tra "morti col coronavirus" e "morti a causa del coronavirus", (analisi che viene fatta successivamente dal ISS) che certamente non diminuisce il numero di decessi, ma sicuramente fornirà un quadro più completo della situazione.

@morano-ma :ok, ma se si prende il numero dei decessi come conditio sine qua non per dirigere politiche di chiusura/riapertura, credo sia allora auspicabile che il dato sia il più pulito possibile, perchè ad oggi i tre dati:contagi-tamponi.-decessi che sono il mantra per gestire l'andamento del virus sono abbondantemente da rivedere e rivalutare alla luce delle tante osservazioni che leggiamo qua dentro.

**Comment by umbros** [comment]
Ciao, non sono dati da ISTAT ma sono i decessi comunicati dalle Regioni con e per covid-19
