### ISSUE TITLE
Grafico Andamento nazionale valori dell'asse orizzontale non visualizzabili

### ISSUE THREAD

**Issue by marcodadamo** [pcm-dpc/COVID-19#56]
![image](https://user-images.githubusercontent.com/56562822/76171821-ca45a180-618f-11ea-82f9-0955ac94449f.png)
Come di evince nel **grafico andamento nazionale**, l'asse orizzontale ha valori sovrapposti e non leggibili, lo stesso è anche per il grafico **Incremento giornaliero degli attualmente positivi**
![image](https://user-images.githubusercontent.com/56562822/76171859-29a3b180-6190-11ea-8a91-d5173131ab72.png)

**Comment by tehKapa** [comment]
Ho provato a replicare una dashboard con un layout simile a quello pubblicato dalla Protezione Civile. La sovrapposizione delle date può essere dovuta a questa impostazione non selezionata? 

![COVID-19 - GitHub #56 (1)](https://user-images.githubusercontent.com/6388707/76207333-dd8f5600-61fd-11ea-9a69-248bb613b47d.gif)

**Comment by caesarsol** [comment]
Non conosco direttamente ArcGis, ma:
 - sicuramente bisogna sincerarsi che le date siano lette come date, altrimenti vengono viste come colonna categorica
 - un classico modo per risolvere è ruotare le label di 45°, in genere è possibile in tutti i software di charting

Spero di non aver detto ovvietà :)

**Comment by marcodadamo** [comment]
Ho riscontrato che il problema n. #56 è stato risolto, pertanto lo inserisco come azione chiusa.
