### ISSUE TITLE
il nome del file PDF https://github.com/pcm-dpc/COVID-19/blob/master/schede-riepilogative/province/ripartizione%20per%20provincia%2016%20aprile%202020.pdf è in un formato diverso da quello dei giorni precedenti

### ISSUE THREAD

**Issue by 123cobloc** [pcm-dpc/COVID-19#560]
Tipo di issue:

- [ ] Dati mancanti o errati 
- [x] Errore nella documentazione 
- [ ] Errore or mancanza nella dashboard 
- [ ] Problemi di visualizzazione nella dashboard 

- Regione:
- Provincia: 

## Riassunto

**Attesa:**

**Attuale:**

**Comment by umbros** [comment]
corretto grazie @123cobloc
