### ISSUE TITLE
Dati Json latest non aggiornati

### ISSUE THREAD

**Issue by mautorresi** [pcm-dpc/COVID-19#561]
Salve,

I dati "latest" in json non sono stati aggiornati.

**Comment by mautorresi** [comment]
Mi correggo,

Sono aggiornati solo quelli delle province. Regioni e andamento nazionali non sono ancora stati aggiornati.

**Comment by EmilianoBruni** [comment]
Confermo, lastest json regione non aggiornato

**Comment by umbros** [comment]
aggiornato grazie della segnalazione
