### ISSUE TITLE
Non è stato aggiornato il file json andamento-nazionale-latest presenta ancora la data di ieri

### ISSUE THREAD

**Issue by nuke86** [pcm-dpc/COVID-19#562]
Tipo di issue:

- [x] Dati mancanti o errati 
- [ ] Errore nella documentazione 
- [ ] Errore or mancanza nella dashboard 
- [ ] Problemi di visualizzazione nella dashboard 

- Regione:
- Provincia: 

## Riassunto

**Attesa:**

**Attuale:**

**Comment by EmilianoBruni** [comment]
#561

**Comment by EmilianoBruni** [comment]
Duplicate of #561

**Comment by umbros** [comment]
#561
