### ISSUE TITLE
File JSON “latest” non aggiornato

### ISSUE THREAD

**Issue by alessiorubicini** [pcm-dpc/COVID-19#563]
Tipo di issue:

- Dati mancanti o errati, file: dati-json/dcp-covid19-ita-andamento-nazionale-latest.json

## Riassunto

I dati non sono stati aggiornati e sono fermi al 15 aprile 2020.

**Attesa:**

Il file JSON dovrebbe essere aggiornato ogni giorno.

**Attuale:**
Attualmente mancano i dati del 16 aprile che non si trovano su dati-json/dcp-covid19-ita-andamento-nazionale latest

**Comment by EmilianoBruni** [comment]
Duplicate of #561

**Comment by umbros** [comment]
#561
