### ISSUE TITLE
Test sierologici

### ISSUE THREAD

**Issue by federico-vitale** [pcm-dpc/COVID-19#564]
**Tipo di richiesta**: richiesta di informazione

## Riassunto
Buonasera, visto l'inizio dei test sierologici in alcune aree geografiche, vorrei chiedere se è prevista una repo apposita (o l'integrazione di questa) con i dati circa i risultati rilevati. Un saluto e grazie per l'ottimo lavoro!

(https://www.corriere.it/cronache/20_aprile_16/coronavirus-esiti-primi-test-anticorpi-10percento-casi-59574716-8021-11ea-8804-717fbf79e066.shtml)

## Interesse pubblico
Ampliare la base di dati disponibile al pubblico.

**Comment by umbros** [comment]
ciao @federico-vitale se i dati saranno gestiti li aggiungeremo a questa.

**Comment by federico-vitale** [comment]
Ciao, grazie! Buon lavoro
