### ISSUE TITLE
Dati dei positivi ATTUALI per provincia

### ISSUE THREAD

**Issue by pescetti** [pcm-dpc/COVID-19#57]
Uso i dati provinciali, dopo varie operazioni automatiche di aggiustamento, per costruire una heatmap animata che mostra la diffusione del Coronavirus in Italia in modo più leggibile rispetto alle varie dashboard puntuali:

http://data.pescetti.it/2020-03-coronavirus-near-me/

![screenshot-8296](https://user-images.githubusercontent.com/1452177/76172686-b3577d00-6198-11ea-8189-4f2992f24e9e.png)

Tuttavia, quando i guariti cominceranno ad essere significativi, emergerà il problema che i dati dei guariti (se capisco bene) sono disponibili solo per regione. Per provincia abbiamo i casi **totali**, che non decrescono mai.

Esistono i dati sui casi **attuali** (malati, quindi esclusi i guariti e esclusi i deceduti) per provincia? Altrimenti le aree rosse nel grafico non si restringeranno mai, a meno di intervenire sulla base del dato regionale.

**Comment by umbros** [comment]
Complimenti per il tuo lavoro @pescetti, il dato per Provincia è molto variabile ed è difficile da gestire (abbiamo molti soggetti non assegnati ad alcuna provincia), quindi per ora non possiamo fornirti le informazioni da te chieste, ma le attività sono sempre in evoluzione.

**Comment by pescetti** [comment]
Capisco. Grazie comunque e nell'attesa cercherò di incorporare qualche meccanismo che riporti (in sola visualizzazione, non nei dati) nelle province i dati che al momento sono solo per regione: guariti, decessi e casi attivi non assegnati alle province.

**Comment by iosonosempreio** [comment]
Nel caso fosse possibile rilasciarli, mi sarebbero utili anche se parte dei casi non sono ricollegabili ad una specifica provincia.
