### ISSUE TITLE
Errore dati province di oggi 

### ISSUE THREAD

**Issue by FrancescoMandru** [pcm-dpc/COVID-19#574]
I dati delle province sono stati mal caricati e non vengono letti correttamente

**Comment by NandayDev** [comment]
Confermo, nel csv https://github.com/pcm-dpc/COVID-19/blob/master/dati-province/dpc-covid19-ita-province.csv è stato ripetuto l'header, 
alla riga 7170

<img width="803" alt="screenshot_45" src="https://user-images.githubusercontent.com/60286366/79777998-5bd03380-8338-11ea-911c-ee24f186ce8b.png">

**Comment by Pinellus** [comment]
Confermo, riga 7170 c'è la ripetizione dell'header.

**Comment by umbros** [comment]
Corretto grazie!
