### ISSUE TITLE
csv dati per province

### ISSUE THREAD

**Issue by piobel50** [pcm-dpc/COVID-19#575]
salve, non pubblicate i dati di dettaglio per province ?

grazie

**Comment by umbros** [comment]
ancora no @piobel50 ci focalizziamo sul bacino di interesse nostro che è quello nazionale e regionale... spero che le regioni rilascino i dati

**Comment by piobel50** [comment]
ok ma come è possibile avere i dati delle regioni senza avere quelli delle province ?

quindi come sta andando milano piuttosto che bergamo non è dato sapere ?

**Comment by ELISA-19** [comment]
salve è possibile avere gli stessi dati delle regioni anche per le province?? non sempre le regioni pubblicano..........
