### ISSUE TITLE
Inconsistenza file dpc-covid19-ita-province.json

### ISSUE THREAD

**Issue by mydozer** [pcm-dpc/COVID-19#58]
nei dati disponibili al 08/03 è presente il seguente dato errato
`{
        "data": "data",
        "stato": "stato",
        "codice_regione": "codice_regione",
        "denominazione_regione": "denominazione_regione",
        "codice_provincia": "codice_provincia",
        "denominazione_provincia": "denominazione_provincia",
        "sigla_provincia": "sigla_provincia",
        "lat": "lat",
        "long": "long",
        "totale_casi": "casi_totali"
    },`

**Comment by umbros** [comment]
@mydozer grazie della segnalazione.
