### ISSUE TITLE
dpc-covid19-ita-regioni - 19 campi invece di 20

### ISSUE THREAD

**Issue by slma80** [pcm-dpc/COVID-19#580]
Tipo di issue:

- [x] Dati mancanti o errati : dpc-covid19-ita-regioni-20200311.csv e dpc-covid19-ita-regioni-20200410.csv
- [ ] Errore nella documentazione 
- [ ] Errore or mancanza nella dashboard 
- [ ] Problemi di visualizzazione nella dashboard 

- Regione:
- Provincia: 

## Riassunto
I file citati contengono alcune righe che non rispecchiano il tracciato indicato, nello specifico contengono 19 campi invece dei 20 presenti nell'header

Saluti
Luca

**Comment by umbros** [comment]
Corretto, grazie
