### ISSUE TITLE
csv per province

### ISSUE THREAD

**Issue by piobel50** [pcm-dpc/COVID-19#581]
grazie per la risposta

 ma come è possibile avere i dati delle regioni senza avere quelli delle province ?

quindi come sta andando milano piuttosto che bergamo non è dato sapere ?

**Comment by mordacheno** [comment]
Per la Lombardia c'è questa ottima Dashboard:
https://www.samueleastuti.it/2020/03/25/covid-19-dashboard-interattiva-della-situazione-in-lombardia/
