### ISSUE TITLE
JSON note-en e note-it scambiati

### ISSUE THREAD

**Issue by DjMike238** [pcm-dpc/COVID-19#582]
Tipo di issue:

- [X] Dati mancanti o errati (`dati-json/dpc-covid19-ita-note-it.json`)
- [ ] Errore nella documentazione 
- [ ] Errore or mancanza nella dashboard 
- [ ] Problemi di visualizzazione nella dashboard 

- Regione:
- Provincia: 

## Riassunto

Il file `dati-json/dpc-covid19-ita-note-it.json` è stato caricato come `dati-json/dpc-covid19-ita-note-en.json` nell'ultimo aggiornamento dei dati (2020-04-21).

**Comment by umbros** [comment]
corretto grazie
