### ISSUE TITLE
Campo casi_testati con valori non numerici

### ISSUE THREAD

**Issue by ElCresh** [pcm-dpc/COVID-19#583]
Tipo di issue:

- [ ] Dati mancanti o errati dpc-covid19-ita-regioni e dpc-covid19-ita-andamento-nazionale

- Regione: Tutte

## Riassunto

Il campo 'casi_testati' presenta valori '' (stringa vuota) che non rientrano nel campo del tipo dichiarato, ovvero Numerico.

**Attesa:**

E' auspicabile che il valore in caso di mancato calcolo possa essere 0

**Attuale:** '' (stringa vuota)

**Comment by smartm0use** [comment]
Cosa rappresenta esattamente il campo "casi testati"?

**Comment by ElCresh** [comment]
Riporto dalla descrizione nel README:

casi_testati > Totale dei soggetti sottoposti al test.

**Comment by marcosbrana** [comment]
> 
> 
> Riporto dalla descrizione nel README:
> 
> casi_testati > Totale dei soggetti sottoposti al test

Non ho capito la differenza tra Tamponi e casi testati, qualcuno può spiegarmela?
Grazie
Marco

**Comment by smartm0use** [comment]
C'è una mia [issue](https://github.com/pcm-dpc/COVID-19/issues/525) sul significato del campo "tamponi", perché non è chiaro se indicativa del numero di tamponi effettuati o del numero di persone a cui è stato effettuato il tampone (ad una persona potrebbero essere prelevati 2 o più tamponi, uno in cui viene riscontrata la positività ed altri a oltranza fin quando non viene rilevata la negatività).

Questo eventuale ambiguità viene risolta proprio dal recente campo "casi_testati", che rappresenta proprio il numero di persone a cui è stato effettuato il tampone.

Resta aperta però un'altra [issue](https://github.com/pcm-dpc/COVID-19/issues/577), in quanto non è dato sapere se il numero di tamponi corrisponde ai tamponi analizzati con esito, oppure ai tamponi prelevati ma non ancora analizzati.

**Comment by Paulsword** [comment]
Nella stragrande maggioranza dei casi mi pare del tutto evidente la correlazione numerica tra il numero di tamponi e i casi positivi della giornata, il che suggerisce, credo senza grossi dubbi, che il conto dei tamponi si riferisce ai test chiusi, refertati, non a quelli prelevati o in lavorazione.

**Comment by pgubara** [comment]
ma i casi testati sono calcolati o comuinicati dagli ospedali / medici di base?

**Comment by ElCresh** [comment]
Perdonatemi tutti ma non stiamo un po' uscendo dalla pertinenza della mia segnalazione?

**Comment by umbros** [comment]
Ciao a tutti, casi testati cominciamo dal 19 aprile, i giorni precedenti (dobbiamo controllare il pregresso) sono impostati vuoti (null)

**Comment by ElCresh** [comment]
Il problema di usare un campo null o empty su un campo numerico (sia esso integer, double o similari) è che essendo delle tipologie basi non accettano tale valore. Hanno bisogno di un dato di defualt che sia 0 o fuori scala (per far capire che il dato sia invalido). Mantenendo i CSV così come sono ora ad esempio è impossibile importarli senza elaborazione su DB MySQL (o derivati) senza trattare tutti i campi come puro testo.

**Comment by vi-enne** [comment]
> Nella stragrande maggioranza dei casi mi pare del tutto evidente la correlazione numerica tra il numero di tamponi e i casi positivi della giornata, il che suggerisce, credo senza grossi dubbi, che il conto dei tamponi si riferisce ai test chiusi, refertati, non a quelli prelevati o in lavorazione.

E' chiaramente falso per almeno la Toscana, che comunica i dati dei tamponi effettuati alla protezione civile e il numero di test chiusi nel comunicato regionale e i due numeri differiscono.
