### ISSUE TITLE
500 internal server error sul Raw dei file

### ISSUE THREAD

**Issue by Achab94** [pcm-dpc/COVID-19#588]
Ciao, 
immagino sia un problema diffuso su tutta la piattaforma Github, ma l'accesso alla versione Raw dei dati restituisce un 500: internal server error. Qua per esempio [il link ](https://raw.githubusercontent.com/pcm-dpc/COVID-19/master/dati-andamento-nazionale/dpc-covid19-ita-andamento-nazionale.csv) al raw del csv sui dati nazionali.

Ne sapete qualcosa?

**Comment by bfabio** [comment]
GitHub sta avendo problemi: https://www.githubstatus.com/.

**Comment by umbros** [comment]
Ciao, era un errore github. Confermo.
