### ISSUE TITLE
Forniture formato json va in errore

### ISSUE THREAD

**Issue by filipic** [pcm-dpc/COVID-19#589]
Tipo di issue:

- [X] Dati mancanti o errati https://raw.githubusercontent.com/pcm-dpc/COVID-19/master/dati-contratti-dpc-forniture/dati-json/dpc-covid19-dati-contratti-dpc-forniture.json
- [ ] Errore nella documentazione 
- [ ] Errore or mancanza nella dashboard 
- [ ] Problemi di visualizzazione nella dashboard 

- Regione:
- Provincia: 

## Riassunto

La url del raw del file delle forniture in formato json raggiungibile [qui](https://raw.githubusercontent.com/pcm-dpc/COVID-19/master/dati-contratti-dpc-forniture/dati-json/dpc-covid19-dati-contratti-dpc-forniture.json) va in errore: ` 500: Internal Server Error`.

Fino alle ore 14.00 del 23/04 non si verificava invece alcun inconveniente.

**Attesa:**

**Attuale:**

**Comment by bfabio** [comment]
Duplicate of #588.

**Comment by umbros** [comment]
#588
