### ISSUE TITLE
Domanda su nuovi_attualmente_positivi

### ISSUE THREAD

**Issue by giacomoalonzi** [pcm-dpc/COVID-19#59]
Salve, il dato `nuovi_attualmente_positivi` rispetto a cosa/quando? giorno precedente?

Grazie

**Comment by dbaroncelli** [comment]
mi pare sia la differenza tra il valore `attualmente_positivi` di oggi e quello di ieri

**Comment by giocaputo** [comment]
È in valore assoluto il numero dei positivi giorno per giorno

Il lun 9 mar 2020, 01:04 dbaroncelli <notifications@github.com> ha scritto:

**Comment by umbros** [comment]
ciao @giacomoalonzi, gli attualmente positivi sono, come riportato nel readme, la somma di ospedalizzati e isolamento domiciliare, i nuovi positivi sono la differenza tra ieri e oggi come dice @dbaroncelli ovvero l'incremento giornaliero degli attualmente positivi.

**Comment by giacomoalonzi** [comment]
Perfetto grazie mille!

**Comment by alessiosavi** [comment]
Ogni punto dell'immagine corrisponde a una entry json del dataset. Quindi ogni punto corrisponde ai casi del giorno?

![image](https://user-images.githubusercontent.com/31842468/76467904-fb6dde00-63ea-11ea-9a9b-728d2d87e2ba.png)
