### ISSUE TITLE
La colonna dei casi_testati in https://github.com/pcm-dpc/COVID-19/blob/master/dati-regioni/dpc-covid19-ita-regioni-20200423.csv contiene i dati in ordine errato

### ISSUE THREAD

**Issue by 123cobloc** [pcm-dpc/COVID-19#590]
Tipo di issue:

- [x] Dati mancanti o errati 
- [ ] Errore nella documentazione 
- [ ] Errore or mancanza nella dashboard 
- [ ] Problemi di visualizzazione nella dashboard 

- Regione:
- Provincia: 

## Riassunto

**Attesa:**

**Attuale:**

**Comment by davpirelli** [comment]
Anche i file JSON, per 10 regioni controllate. Tutte hanno valori sballati, es per gli ultimi 4 giorni di regione lombardia:

23/04/2020: 49403
22/04/2020: 184323
21/04/2020: 173333
20/04/2020: 273333
e cosi via, @umbros

**Comment by Paulsword** [comment]
Pasticcioni!

**Comment by umbros** [comment]
corretto, grazie
