### ISSUE TITLE
Dati errati casi testati Veneto

### ISSUE THREAD

**Issue by DataEnthusiast84** [pcm-dpc/COVID-19#591]
Tipo di issue:

- [X] Dati mancanti o errati 
- [ ] Errore nella documentazione 
- [ ] Errore or mancanza nella dashboard 
- [ ] Problemi di visualizzazione nella dashboard 

- Regione: Veneto
- Provincia: 

## Riassunto

"casi_testati": 4478 del giorno 23 Aprile 2020

Credo che il valore sia errato...

**Attesa:**

Un dato sicuramente maggiore a 171735 che è il numero dei casi testati il 22/4/2020

[EDIT]: credo che il problema sia diffuso per tutte le Regioni... come segnalato anche in #590 
L'errore è presente anche nel file JSON...

**Comment by Patrizia1972** [comment]
si confermo anche io i valori sono sono compatibili assolutamente con la realtà

**Comment by davpirelli** [comment]
confermo, non solo per il Veneto, ma su 10 regioni controllate tutte hanno valori sballati, es per gli ultimi 3 giorni di regione lombardia:

23/04/2020: 49403
22/04/2020: 184323
21/04/2020: 173333
20/04/2020: 273333
e cosi via, @umbros

**Comment by umbros** [comment]
Corretto, grazie
