### ISSUE TITLE
ISTAT pubblica i dati (VERI) sui decessi, comune per comune

### ISSUE THREAD

**Issue by danielesalpietro** [pcm-dpc/COVID-19#592]
ECCO I DATI REALI 

Il sistema consente di visualizzare per singolo comune il valore cumulato dei decessi dal 1 gennaio al 4 aprile.

https://www.istat.it/it/archivio/241428

Il grafico viene aggiornato solo dopo aver selezionato oltre alla regione e la provincia anche il comune dall’elenco a tendina.

Per due anni (a scelta dell’utente tra il 2015 e il 2020) è possibile selezionare inoltre la classe di età, il genere e uno o più mesi tra i 4 considerati.

I dati presentati non consentono una visualizzazione a livello regionale e/o provinciale.

Interessante il confronto fra i decessi del 2019, quelli del 2020, ed i numeri che vengono pubblicati qui e dati in pasto ai media...... un errore del +30% in difetto in molte casi....

Interessante ?

**Comment by Patrizia1972** [comment]
Molto interessante, grazie mille, io stavo isando i dati scaricabili. Anche se la percentuale di comuni coperti è ancora bassa.... ma ci vuole molto tempo a verifciare i dati

**Comment by umbros** [comment]
Ciao, è molto interessante per fare proiezioni e analisi e avere un quadro sulla situazione dei decessi. In ISTAT vengono contati tutti i decessi.
