### ISSUE TITLE
Alcune incongruenze dati Marche del 23/04/2020

### ISSUE THREAD

**Issue by MicheleAlfinito** [pcm-dpc/COVID-19#593]
[GORESblu23042020_9.pdf](https://github.com/pcm-dpc/COVID-19/files/4525671/GORESblu23042020_9.pdf)
- Regione: Marche
## Riassunto

Buongiorno, innanzitutto ringrazio per l'aggiunta della colonna "casi_testati" a partire dal 19/04 e mi auguro che possano essere reperiti dati in questo campo anche per lo storico.
Segnalo una incongruenza numerica tra il valore nella colonna "casi_testati" del file odierno https://github.com/pcm-dpc/COVID-19/blob/master/dati-regioni/dpc-covid19-ita-regioni-20200423.csv relativo alle Marche, pari a 18656 ed il numero di "campioni testati totali" così come riportatato dal GORES, pari a 31673 e visibile in questo link (pagina 2):
http://www.regione.marche.it/portals/0/Salute/CORONAVIRUS/DatiGORES/GORESblu23042020_9.pdf
Allego anche il file pdf. Curiosamente ho notato che il valore 31673 è identico al valore attribuito al Lazio nel vostro file dpc-covid19-ita-regioni-20200423.csv. Una svista? 
C'è anche un'altra questione secondo me di importanza cardinale e penso che possa riguardare anche per altre regioni la modalità con la quale vi vengono forniti i dati, se necessario apro una nuova issue, ditemi voi:
Sempre nella riga delle Marche, del file https://github.com/pcm-dpc/COVID-19/blob/master/dati-regioni/dpc-covid19-ita-regioni-20200423.csv nella colonna "nuovi_positivi" è riportato il valore 28.
Lo stesso valore è riportato nel file DatiGores che ho linkato sopra, ma si riferisce alla colonna "Campioni Positivi giornalieri per SARS-Cov-2". Ora il dubbio che mi viene è che tale valore debba piuttosto essere attribuito come somma al "totale_positivi" del giorno precedente, ovvero lo si debba ottenere per differenza e comparire nella colonna "variazione_totale_positivi" del giorno corrente, piuttosto che alla colonna "nuovi_positivi" che sappiamo essere in realtà una "variazione dei casi", inclusiva pertanto anche delle variazioni di dimessi/guariti e deceduti.
Resto in attesa di ragguagli in merito, Grazie

**Comment by umbros** [comment]
Ciao,
i dati sono quelli inviati a noi da regione marche tramite il ministero. Comunichiamo la cosa.
