### ISSUE TITLE
Fonte più rapida per la scheda riepilogativa regionale

### ISSUE THREAD

**Issue by Rabelaiss** [pcm-dpc/COVID-19#595]
Buona sera, premetto che ho aperto questo issue non per discutere di problemi relativi ai dati, quindi mi scuso in anticipo dato che è un utilizzo improprio.

Fino ad ora, pensavo che il sito github della protezione civile fosse il modo più veloce per reperire i bollettini, in particolare quelli con le colonne colorate (questa per intenderci https://i.imgur.com/Co3Aiph.png), tuttativa oggi sono venuto a conoscenza di un canale telegram dove la scheda riepilogativa viene pubblicata alle 17:55 circa, mentre qui su github alle 18:15 circa.

Sapete quale sia la fonte alternativa dove poter trovare in anticipo i bollettini?
Vi ringrazio e scusate ancora per aver aperto l'issue

**Comment by umbros** [comment]
@Rabelaiss non disponiamo di un account telegram ufficiale del Dipartimento della Protezione Civile, invitiamo pertanto (per garantire la fonte) di fare riferimento a questo repository e al sito ufficiale.
