### ISSUE TITLE
Numero di pazienti in terapia intensiva

### ISSUE THREAD

**Issue by FabrizioDG** [pcm-dpc/COVID-19#6]
Buonasera,

prima di tutto grazie per il lavoro che state svolgendo. Vorrei chiedere se è possibile inserire nell'andamento nazionale giorno per giorno una colonna relativa al numero di pazienti in terapia intensiva. Riesco a trovare questo dato relativo ad oggi, ma non sono riuscito a trovare da nessuna parte l'andamento giornaliero.

Grazie mille,
buon lavoro!

**Comment by umbros** [comment]
Corretto, attualmente non viene riportato nell'andamento. Metto l'attività come enhancement.

**Comment by asx451** [comment]
Aggiungo che manca anche l'informazione sui ricoverati con sintomi. Grazie.

**Comment by FabrizioDG** [comment]
Grazie mille per la rapida risposta!
Riguardo il commento di asx451 il numero totale di casi ospedalizzati é già presente. Una volta ricevuta l'informazione su quanti sono i casi in terapia intensiva puoi dedurre i casi lievi sapendo il numero totale.

**Comment by asx451** [comment]
@FabrizioDG sei sicuro? Io, avendo il numero di ricoverati con sintomi, potrei ricavare anche il numero di persone in quarantena domiciliare. Facendo come dici tu, invece, per differenza otterrei un valore che mi ricomprende sia quelli a casa + quelli "lievi" in ospedale. Sbaglio?

**Comment by FabrizioDG** [comment]
> @FabrizioDG sei sicuro? Io, avendo il numero di ricoverati con sintomi, potrei ricavare anche il numero di persone in quarantena domiciliare. Facendo come dici tu, invece, per differenza otterrei un valore che mi ricomprende sia quelli a casa + quelli "lievi" in ospedale. Sbaglio?

Se vai in questo file qui: https://github.com/pcm-dpc/COVID-19/blob/master/dati-andamento-nazionale/dpc-covid19-ita-andamento-nazionale.csv

già troverai  diviso il numero di persone in quarantena domiciliare e anche il numero di persone ospedalizzate. Una volta che sai il numero di persone in terapia intensiva, i casi lievi ospidalizzati li fai per differenza. Almeno questo mi sembra di aver capito che vorresti sapere, magari ho capito male io.

**Comment by asx451** [comment]
@FabrizioDG grazie! con i TI si ricava tutto. Ottimo.

**Comment by umbros** [comment]
Ciao, grazie a tutti, ho modificato il dataset andamento mettendo i totali nazionali delle informazioni per Regione.
