### ISSUE TITLE
in dpc-covid19-ita-province.csv il valore di "totale_casi" non è sepre crescente per una specifica provincia

### ISSUE THREAD

**Issue by evoblue** [pcm-dpc/COVID-19#60]
Nel file "dpc-covid19-ita-province.csv" dello storico delle province la colonna "totale_casi" di Napoli riporta il valore di 30 casi il giorno 3/3/2020 mentre il giorno prima e il giorno dopo sono 17. 

I valore di "totale_casi"  non dovrebbe essere sempre crescente ?

Si tratta di un errore oppure interpreto male io questo dato ?

**Comment by umbros** [comment]
@evoblue come detto in altre issue, il dato delle Province è molto variabile tantochè spesso non c'è assegnazione di tutti le persone nella provincia corretta.
