### ISSUE TITLE
regioni-latest.csv non è aggiornato al 26 aprile.

### ISSUE THREAD

**Issue by pierangelo1982** [pcm-dpc/COVID-19#600]
Tipo di issue:

- [x] Dati mancanti o errati 
- [ ] Errore nella documentazione 
- [ ] Errore or mancanza nella dashboard 
- [ ] Problemi di visualizzazione nella dashboard 

- Regione:
- Provincia: 

## Riassunto

**Attesa:**

**Attuale:**

**Comment by umbros** [comment]
aggiornato
