### ISSUE TITLE
Persone testate parziale negativo Veneto e VdA

### ISSUE THREAD

**Issue by Paulsword** [pcm-dpc/COVID-19#601]
Tipo di issue:

- [ ] Dati mancanti o errati 
- [ ] Errore nella documentazione 
- [ ] Errore or mancanza nella dashboard 
- [ ] Problemi di visualizzazione nella dashboard 

- Regione:
- Provincia: 

## Riassunto

**Attesa:**

**Attuale:**

**Comment by umbros** [comment]
Ciao @Paulsword,
su Valle d'Aosta è stata aggiunta la nota: 26/04/2020: dati Regione Valle d'Aosta ricalcolati (casi testati), Veneto non ha ancora comunicato note sui dati.
