### ISSUE TITLE
Campo "dimessi_guariti" Friuli 26/04/2020

### ISSUE THREAD

**Issue by MicheleAlfinito** [pcm-dpc/COVID-19#604]
- [x] Errore nella documentazione 
- [ ] Errore or mancanza nella dashboard 
- [ ] Problemi di visualizzazione nella dashboard 

- Regione: Friuli Venezia Giulia
- Provincia: 

## Riassunto

Buongiorno, mi domandavo se il campo "dimessi_guariti" sia da considerarsi cumulativo, come quello dei "tamponi" o "casi_testati", perchè facendo la differenza, nella riga del Friuli Venezia Giulia, tra "dimessi_guariti" di oggi e quelli di ieri ottengo -151. In tutte le altre Regioni la variazione è positiva. Vedo anche un problema analogo per i "casi_testati" di Veneto e Valle d'Aosta.

**Comment by Rabelaiss** [comment]
I campi casi_totali, dimessi_guariti, deceduti sono tutti cumulativi. Se un giorno il dato cala, probabilmente significa che hanno corretto un errore di conteggio commesso in precedenza... È capitato molte volte.

**Comment by MicheleAlfinito** [comment]
Grazie

Il mar 28 apr 2020, 09:57 Rabelaiss <notifications@github.com> ha scritto:
