### ISSUE TITLE
Perché non distribuite i dati per comune?

### ISSUE THREAD

**Issue by mottolini** [pcm-dpc/COVID-19#606]
Ogni giorno la protezione civile comunica a ogni comune i dati di propria pertinenza, compresi i nominativi delle persone infette da "tenere in quarantena" e di conseguenza da assistere.
Il dato provinciale che qui pubblicate è ovviamente la somma di quelli comunali che già possedete.
Perché, nonostante l'elevato numero di richieste (https://github.com/pcm-dpc/COVID-19/issues?q=is%3Aissue+comuni+) vi ostinate a non rendere pubblici i dati a livello comunale?

L'unica cosa che si è portati a pensare è che vogliate evitare confronti con i dati Istat.
Nei comuni della bergamasca i sindaci di loro iniziativa hanno reso pubblici i dati che voi gli avete inviato e si sono verificate discrepanze altissime. Un esempio: per voi Nembro in marzo ha avuto 76 vittime da covid19, mentre i morti totali sono stati 135, contro i 14 dell'anno precedente.

**Comment by pierluigicara** [comment]
Come lei sa la "protezione civile" fa riferimento ad un "Servizio Nazionale" composto da un numero molto elevato di soggetti e ciascuno di questi ha una sua autonomia e responsabilità. Le dico questo non per burocratizzare la risposta ma come elemento di realtà. Quindi la risposta è che a livello nazionale questi dati non li abbiamo. I dati che pubblichiamo ci pervengono dal Ministero della Salute e dsponiamo solo dei dati provinciali che lei sicuramente conosce. I dati a livello comunale sono raccolti dal complesso dei laboratori regionali che compongono il sistema di sorveglianza epidemiologica dell'Istituto Superiore di Sanità che li aggrega a partire da dati individuali. Questi dati ad oggi vengono pubblicati dall'ISS, anche se non come opern data. Ecco come stanno le cose.

**Comment by mottolini** [comment]
Grazie innanzitutto per la risposta, ben diversa da quella data a simili richieste nel passato.
Quindi, se ho capito bene e non è saltata una negazione nella sua frase finale, voi i dati comunali non li avete perché l'Istituto Superiore di Sanità, che li ha, non li pubblica in modalità "open data". Li pubblica però in modalità privata verso qualcuno, tra cui non è compresa la Protezione Civile.
Le chiedo solo l'ultima gentilezza i confermarmi se ho capito bene, in modo che possa indirizzare la mia richiesta agli enti corretti.

Purtroppo, infatti, io "non so". Sono un comune cittadino che pensa che lo Stato, come entità astratta, agisca per il bene del suo popolo, ma invece vedo che a fronte di qualcuno che pubblica dati, come voi, c'è qualcun altro che li nasconde mentre infermieri, medici e cittadini muoiono e si impoveriscono giorno dopo giorno.

**Comment by maxu** [comment]
Sono d'accordo: la granularità dei dati è indispensabile per avere numeri reali e non manipolabili. I numeri esistono, e credo non solo a livello comunale ma nelle grandi città anche per municipi.

**Comment by pierluigicara** [comment]
Ecco il sito dove l'ISS pubblica i dati di cui parlavo: https://www.epicentro.iss.it/coronavirus/sars-cov-2-sorveglianza-dati. In particolare, questo è il link  https://www.epicentro.iss.it/coronavirus/bollettino/Bolletino-sorveglianza-integrata-COVID-19_23-aprile-2020_appendix.pdf al report dove sono mostrati i dati per comune. Invito anche a leggere la nota metodologica, i disclaimer e ogni altra informazione "accessoria" presente, utile per capire e utilizzare in modo appropriato le informazioni rese disponibili. ISS non pubblica in modalità "privata", ma solo in modalità non riutilizzabile, cioè non in open data. Ora questo non significa che ISS "nasconda" i dati. Tenga, infine, presente che esistono specifiche limitazioni imposte dall'autorità Garante per la protezione dei dati personali alla pubblicazione di dati che - anche indirettamente - possano portare all'identificazione di una persona e tutti i dati covid a livello comunale per la gran parte rientrano in questa casistica. Può fare anche lei facilmente una verifica su uno qualsiasi dei dataset comunali a cui faceva riferimento, contando quanti sono i casi dove ciascun indicatore è <=3. Come vede dunque la situazione è molto complessa, come sempre, ma ancora di più durante la gestione di una emergenza.

**Comment by maxu** [comment]
Ma la nota che dice "LA TABELLA NON INCLUDE I CASI CON SESSO NON NOTO" cosa starebbe a significare?

**Comment by mottolini** [comment]
Grazie @pierluigicara, ora tutto è chiaro.
Nel caso avesse un nominativo di qualcuno all'interno dell'ISS sensibile al tema della condivisione dei dati in modo open, anziché premasticato, la prego di indicarmelo privatamente.
