### ISSUE TITLE
Dati di oggi province 28/04/20

### ISSUE THREAD

**Issue by FrancescoMandru** [pcm-dpc/COVID-19#607]
Qualcuno sa cosa è successo ai dati di oggi?
![download](https://user-images.githubusercontent.com/43784964/80510528-22707700-897b-11ea-91d0-2b1fef58a144.png)

**Comment by paxtibi** [comment]
![immagine](https://user-images.githubusercontent.com/18218025/80510987-c9551300-897b-11ea-99a7-e3a1b17fce55.png)

Non vedo nulla di strano nel mio import.
Prova a vedere cosa stai leggendo

**Comment by anbened** [comment]
> ![immagine](https://user-images.githubusercontent.com/18218025/80510987-c9551300-897b-11ea-99a7-e3a1b17fce55.png)
> 
> Non vedo nulla di strano nel mio import.
> Prova a vedere cosa stai leggendo

Le righe di oggi 28/04, nel dataset csv delle province, sono duplicati

**Comment by FrancescoMandru** [comment]
Il mio file non è mai stato cambiato e conta il totale dei casi da diverse settimane, quindi ci dev'essere stato un update scorretto dei dati, oppure un aggiornamento di qualche tipo

**Comment by paxtibi** [comment]
@anbened dice che i dati provinciali hanno problemi. 
Personalmente importo solo quelli regionali. Quindi a me il problema non dovrebbe porsi. 
L'import viene eseguito in un db e poi estraggo le somme a seconda dei filtri in pagina...
Non vedo picchi come nel tuo grafico.


![immagine](https://user-images.githubusercontent.com/18218025/80511959-1c7b9580-897d-11ea-96d5-7d660f2557d2.png)

**Comment by FrancescoMandru** [comment]
Si è un problema di dati provinciali

**Comment by anbened** [comment]
> @anbened dice che i dati provinciali hanno problemi.
> Personalmente importo solo quelli regionali. Quindi a me il problema non dovrebbe porsi.
> L'import viene eseguito in un db e poi estraggo le somme a seconda dei filtri in pagina...
> Non vedo picchi come nel tuo grafico.
> 
> ![immagine](https://user-images.githubusercontent.com/18218025/80511959-1c7b9580-897d-11ea-96d5-7d660f2557d2.png)

Se vedi il file:

https://raw.githubusercontent.com/pcm-dpc/COVID-19/master/dati-province/dpc-covid19-ita-province.csv

E cerchi questa stringa:

2020-04-28T17:00:00,ITA,03,Lombardia,017,Brescia

la trovi due volte.

**Comment by Rabelaiss** [comment]
Tutti i dati di oggi per le province sono ripetuti due volte

**Comment by paxtibi** [comment]
> 
> 
> > @anbened dice che i dati provinciali hanno problemi.
> > Personalmente importo solo quelli regionali. Quindi a me il problema non dovrebbe porsi.
> > L'import viene eseguito in un db e poi estraggo le somme a seconda dei filtri in pagina...
> > Non vedo picchi come nel tuo grafico.
> > ![immagine](https://user-images.githubusercontent.com/18218025/80511959-1c7b9580-897d-11ea-96d5-7d660f2557d2.png)
> 
> Se vedi il file:
> 
> https://raw.githubusercontent.com/pcm-dpc/COVID-19/master/dati-province/dpc-covid19-ita-province.csv
> 
> E cerchi questa stringa:
> 
> 2020-04-28T17:00:00,ITA,03,Lombardia,017,Brescia
> 
> la trovi due volte.

Non mettevo in dubbio le tue parole :) Ma riportavo l'autore della segnalazione per correttezza. ;)

**Comment by FrancescoMandru** [comment]
@paxtibi Avrei dovuto specificare la tabella che ho utilizzato, scusatemi.

**Comment by anbened** [comment]
Se serve, ho caricato il file senza le righe duplicate qui: 

https://github.com/anbened/dati/blob/master/province.csv

**Comment by umbros** [comment]
corretto grazie
