### ISSUE TITLE
Chiavi ripetute nel csv delle province

### ISSUE THREAD

**Issue by ngshya** [pcm-dpc/COVID-19#608]
Tipo di issue:

- [ ] Dati mancanti o errati 

## Riassunto

Nel file dpc-covid19-ita-province.csv ci sono chiavi doppie. Per esempio 
2020-04-28T17:00:00,ITA,01,Piemonte,001,Torino è ripetuto su due righe. 

**Attesa:**
I dati riferiti al 28 aprile compaiano solo una volta per provincia. 

**Attuale:** 
I dati riferiti al 28 aprile compaiano due volte per provincia su due righe diverse.

**Comment by anbened** [comment]
@umbros ciao, riuscite a correggere?

Il file CSV odierno, 28/04, delle province ha le righe duplicate per oggi

**Comment by bellaceragit** [comment]
Buongiorno,
mi unisco alle richieste qui sopra: è stato incollato due volte il file odierno dentro al file globale delle province (dpc-covid19-ita-province.csv). Andrebbe sistemato, grazie.

**Comment by ngshya** [comment]
Credo che sia lo stesso problema segnaalto qui: #607

**Comment by umbros** [comment]
corretto grazie
