### ISSUE TITLE
Dati 28 aprile presenti 2 volte

### ISSUE THREAD

**Issue by 7heEnd** [pcm-dpc/COVID-19#609]
Tipo di issue:

- [x] Dati mancanti o errati 
- [ ] Errore nella documentazione 
- [ ] Errore or mancanza nella dashboard 
- [ ] Problemi di visualizzazione nella dashboard 

- Regione:
- Provincia: 

## Riassunto

**Attesa:**

**Attuale:**

**Comment by umbros** [comment]
#607
