### ISSUE TITLE
Dati per Comune

### ISSUE THREAD

**Issue by nelsonmau** [pcm-dpc/COVID-19#61]
È previsto il rilascio del dati per Comune? 

- Se sì, quando?
- Se no, perché

Grazie

**Comment by marcodadamo** [comment]
Sarebbe utile avere informazioni di dati per ogni comune ma, sicuramente diventerebbe abbastanza complessa la gestione. 
A mio parere va bene così com'è impostata la gestione dei dati province e regioni.

**Comment by nelsonmau** [comment]
ciao @marcodadamo, avere dati per comune permetterebbe ad esempio di:
- capire quali sono i Comuni più esposti al rischio
- essere anche di monito per i cittadini nel rispettare in maniera più stringente i divieti

**Comment by pescetti** [comment]
I dati per Comune sarebbero molto utili anche per le mappe, ma come da discussione in https://github.com/pcm-dpc/COVID-19/issues/57 sembra che al momento già sulle province non riescano ad avere con precisione alcuni dati importanti (casi guariti ad esempio) che sono disponibili solo per regione. E' una limitazione, ma speriamo che riescano a migliorare il lavoro già molto buono che hanno fatto. Ad ora, i dati sono davvero completi solo su base regionale.

**Comment by bottecchiamauro** [comment]
Confermo sarebbe molto utile avere anche i dati per comune. 

- capire quali sono i Comuni più esposti al rischio

- essere anche di monito per i cittadini nel rispettare in maniera più stringente i divieti

**Comment by aborruso** [comment]
In una prossima release sarebbe molto interessante avere i dati comunali.

Immagino che sia un dato disponibile, così come immagine che rilasciarlo comporti un lavoro preparatorio. Per questo parlo di next release.

Grazie

**Comment by Easyinve** [comment]
Sì, sarebbe molto utile il dato comunale soprattutto per calcolare l'incidenza ogni mille abitanti per andare oltre le dot map e iniziare a fare un'analisi territoriale un po' più approfondita.

**Comment by dcrespi** [comment]
Alcune provincia sono enormi, BG ha 243 comuni, Brescia 205, ed estensioni molto grandi. Da nord a Sud della provincia di BS ci sono 120 Km .... il dato per comune serve eccome !

**Comment by irvine76** [comment]
Avere i dati comunali sarebbe importante per fornire un'informazione corretta ai cittadini. La Lombardia lo fa, perché non estendere a tutta Italia?

**Comment by dcrespi** [comment]
> Avere i dati comunali sarebbe importante per fornire un'informazione corretta ai cittadini. La Lombardia lo fa, perché non estendere a tutta Italia?

Scusa ma dove vedi che li pubblica la Lombardia ? URL ?

**Comment by colibri17** [comment]
I dati comunali sono utili, ma ragazzi parliamoci chiaro: qui per fare qualcosa di veramente utile occorrerebbe avere i dati raw a livello di singola persona: dove è stato negli ultimi giorni e cosa ha fatto (dati dai cellulari = dati google + dati chiamate + dati whatsapp), quali è la sua rete sociale (Facebook, Instagram), chi sono i suoi parenti e dove abita (dati anagrafe), quale è la sua storia clinica (dati del sistema sanitario). Allora si che veramente la data science può dare un aiuto forte al problema. 

Abbiamo problemi di privacy? Benissimo, che si crei una task force di 50 persone, ai quali fai firmare col sangue 10 NDA, ma che abbiamo accesso a ogni cosa possibile e immaginabile.

Qui si tratta di SALVARE DELLE VITE

**Comment by Easyinve** [comment]
No, in realtà Lombardia non li pubblica. I dataset vengono gestiti dalle Ats del territorio e poi elaborati da Regione, ma solo per elaborazione interna o per le mappe che vengono mostrate durante le conferenze stampa pomeridiane.

**Comment by filmastroianni** [comment]
Può dare una mano a vedere se c'è un pattern di distribuzione attorno a certe aree e come si evolvono sicuramente. Come qualcuno dice per essere realmente utili a isolare i casi sarebbero serviti addirittura ancora più granulari. Ma penso anche che qualche "investigatore" del virus quei dati li abbia e li abbia usati.

**Comment by Furbessem** [comment]
> No, in realtà Lombardia non li pubblica. I dataset vengono gestiti dalle Ats del territorio e poi elaborati da Regione, ma solo per elaborazione interna o per le mappe che vengono mostrate durante le conferenze stampa pomeridiane.

Le regioni dovrebbero ricevere indicazione di come raccoglierli sia in termini di struttura sia in termini di tempistiche. Le "elaborazioni interne" pur necessarie e dovute, non devono rallentare il processo di raccolta nè distruggere informazione su piattaforma nazionale.

**Comment by umbros** [comment]
@nelsonmau i dati per comune non hanno una compiutezza tale e garanzia della reale affidabilità. Anche nelle statistiche per Provincia molti dati non sono assegnati alle province e vengono definiti in "In fase di definizione/aggiornamento" che è una "provincia di appoggio" creata per ogni Regione per poter allineare i dati totali. Perfezionando il sistema si potranno avere più dati e li riporteremo nei CHANGELOG. Grazie a tutti per la collaborazione.

**Comment by nelsonmau** [comment]
grazie per aver verificato @umbros

**Comment by irvine76** [comment]
Scusate, avevo visto il lavoro di @Easyinve sulle incidenze per comune e credevo fossero di dominio pubblico. Invece reperirli è stato frutto della sua bravura.
