### ISSUE TITLE
Blank lines in the COVID-19/dati-andamento-nazionale/dpc-covid19-ita-andamento-nazionale.csv file makes the data parser using external user fail. We are using Denodo Paltform 

### ISSUE THREAD

**Issue by kthangaraj2401** [pcm-dpc/COVID-19#612]
Type of issue:

- [x] Incorrect or missing data :  COVID-19/dati-andamento-nazionale/dpc-covid19-ita-andamento-nazionale.csv 

Blank lines in the file makes the data parser using external user fail. We are using Denodo Paltform 

- Region: India
- Province: Tamilnadu

## Summary

Blank lines in the file makes the data parser using external user fail. We are using Denodo Paltform to read the files provide in this repository - dpc-covid19-ita-andamento-nazionale.csv 

**Expected:**

No blank lines at the end of the file 

**Actual:** <
Blank lines at the end of the file

**Comment by LucaZeta** [comment]
I'm experiencing the same problem described by kthangaraj2401, importing dpc-covid19-ita-andamento-nazionale.csv by Excel
It looks like the problem was indroduced by <CR><LF> has been added at the end of last line of file.

**Comment by umbros** [comment]
correct!
