### ISSUE TITLE
Totale_positivi di oggi è una stringa

### ISSUE THREAD

**Issue by DarkFighterLuke** [pcm-dpc/COVID-19#615]
Tipo di issue:

I dati di oggi nel file json sull'andamento nazionale completo hanno un campo intero inserito per sbaglio come stringa.

Fino alla correzione molti applicativi che si basano sui dati potrebbero riscontare problemi...

**Comment by alexodus** [comment]
Andrebbe fatto un validatore per i dati inseriti. Almeno si evitano questi stessi problemi che di tanto in tanto capitano su questa base dati.

**Comment by DarkFighterLuke** [comment]
> Andrebbe fatto un validatore per i dati inseriti. Almeno si evitano questi stessi problemi che di tanto in tanto capitano su questa base dati.

Sono d'accordissimo...

**Comment by berna1995** [comment]
Ho creato una pull request: https://github.com/pcm-dpc/COVID-19/pull/616
Ho fatto in passato un validatore di dati in python, quello però controllava alcune proprietà dei dati, non se i dati erano di "tipo" corretto; ad ogni modo la pull request di suddetto validatore è stata ignorata.

**Comment by umbros** [comment]
corretto grazie!

**Comment by alexodus** [comment]
> Ho creato una pull request: #616
> Ho fatto in passato un validatore di dati in python, quello però controllava alcune proprietà dei dati, non se i dati erano di "tipo" corretto; ad ogni modo la pull request di suddetto validatore è stata ignorata.

Non accettaranno mai i tuoi contributi
