### ISSUE TITLE
Dati in Stata

### ISSUE THREAD

**Issue by dmaimo** [pcm-dpc/COVID-19#617]
Buonasera, 

Uso stata come data processor. Hi provato ad importare i dati provinciali ma il software non riesce a farlo correttamente. C'è un modo per avere una formattazione dei dati pulita e semplice? Giusto per fare un esempio quando importo i dati provinciali cumukativi, compaiono due variabili K ed L alla fine dei dati che sono vuo te e comunque non visibili nel file originale. Potete darmi qualche indicazione in proposito?

**Tipo di richiesta**:  richiesta di informazione

**Comment by umbros** [comment]
Ciao, K e L sono campi "note", potresti ignorare tale importazione

**Comment by dmaimo** [comment]
Non è così semplice. Nel senso che sia che importi automaticamente i csv, sia che faccia un copia ed incolla ne viene fuori un file i cui dati vengono letti come stringa e non come numeri.  Se elimino K ed L, i dati vengono importati come numeri (ovviamente quelli che sono numeri) ma il loro ordinamento è incomprensibile. Per esempio se provo ad ordinare i dati per codice provincia, questi vengono ordinati in maniera confusa. 
Non so se hai familiarità con stata, ma quando provo a generale una variabile numerica identificativa per le provincie usando il comando egen=gropu(codice_provincia), viene creato un valore numerico che è per esempio 1 non per la provincia con il numero identificativo più basso, ma per un gruppo eterogeneo di provincie.
