### ISSUE TITLE
dpc-covid19-ita-province-latest

### ISSUE THREAD

**Issue by pigreco** [pcm-dpc/COVID-19#618]
il file in oggetto è l'unico non aggiornato, rimasto al 30-04-2020.

Segnalo perché sembra una svista.

grazie per tutto.

![image](https://user-images.githubusercontent.com/7631137/80823789-84c8b200-8bdd-11ea-85c3-1111bc77155f.png)

**Comment by umbros** [comment]
Grazie della segnalazione, non è partito nel commit.
