### ISSUE TITLE
Inferenza errata da parte di lettori non esperti

### ISSUE THREAD

**Issue by code001-it** [pcm-dpc/COVID-19#619]
suggerimento di miglioramento relativo alla pagina grafica

## Riassunto
Per come è messo il grafico riassuntivo, tra breve si arriverà ad avere che la curva dei Guariti sarà sopra la curva dei casi Positivi. Ciò trarrà in inganno chi con le informazioni e i dati agisce solo a livello istintivo e non con ragionamento!
Non pensate che siano una minoranza: anche gente molto preparata davanti a cose che la preoccupano reagisce in modo assolutamente irrazionale.
Ritengo pertanto che sarebbe ora di  passare ad altro grafico con i guariti e i positivi e i morti comunque aggregati in modo tale da far comprendere che la situazione non è "alle spalle".
L'attuale grafico potrebbe diventare il Tab secondario rispetto ad un Grafico con aggregazioni a scelta (come ora per selezionare Nuovi/Variazioni del grafico sottostante)
Sono esperto di come la mente funziona e soprattutto di come inferisce la realtà. L'informazione che dà un effetto opposto di quello che dovrebbe, anche se errata a causa della sua lettura e quindi non colpevole per propria volontà, può diventare comunque pericolosa!
Vi ricordo che anche una minima discesa della sensazione di allerta farà approssimare a Zero la curva più avanti!

## Interesse pubblico

Se il grafico darà l'esatta sensazione di quanto lavoro c'è ancora da fare, chi lo leggerà non abbasserà la guardia con la sensazione che tutto sia prossimo a finire

Grazie per l'attenzione
Luca

**Comment by corradopetrelli** [comment]
Condivido a pieno ciò che dici

**Comment by pierluigicara** [comment]
L'idea mi pare ragionevole e la soluzione tecnica proposta è fattibile, come giustamente osservato.
Sarebbero davvero utile, se possibile, un maggiore approfondimento nella descrizione del problema intravisto - viste le competenze evidenziate -, come pure della soluzione auspicabile: ci sarebbe di grande aiuto. Al momento, inotre, siamo in un delicato momento di passaggio dalla Fase1 alla Fase2 in cui il monitoraggio - così come è stato concepito fino ad ora - dovrebbe conformarsi ai nuovi dispositivi giuridici introdotti. Questo giusto per dire che comunque è il momento giusto per pensarci. Grazie

**Comment by code001-it** [comment]
Giusto per tenere aperta la discussione e avere un paio di spunti su cui pensare:
visto che stiamo parlando di una fase 2, se aprissimo come principale una tabella nuova che lavori su numeri più bassi (primo vantaggio)che  fossero riferiti al giorno e non più somma?

E se i grafici fossero "in pila"? 

Ormai la criticità legata alle terapie intensive è finita e ci interessa solo sapere l'andamento generale per capire quanto è lontana la fine dell'epidemia. La paura della morte di massa sembra in parte scongiurata, per cui l'interesse è nel vedere i sintomi della fine emergenza.

Visto che ci sono i seguenti legami (approssimativi)
- i morti di oggi sono stati contaminati 24 giorni fa
- i dimessi 20 giorni fa
- i ricoverati 12 giorni fa
potrebbe essere interessante avere non solo la visione dei dati odierni con il criterio statistico quotidiano usato finora, ma anche una visione con le parti del grafo che si riallineano in relazione all'origine del fenomento che descrivono, per cui shiftati indietro dei giorni relativi al loro ritardo di sisitema, per cui i morti di oggi slittano (con l'ozione apposita scelta) a 24 giorni fa etc.

In questo modo si possoono anche tracciare grossolanamente le conseguenze dei provvedimenti adottati a livello politico/organizzativo
