### ISSUE TITLE
Aggiunta di 282 casi di decessi in un singolo giorno per effetto del ricalcolo

### ISSUE THREAD

**Issue by francescom** [pcm-dpc/COVID-19#620]
Tipo di issue:

- [X] Dati mancanti o errati, tutti i file di province e Regioni
- [ ] Errore nella documentazione 
- [ ] Errore or mancanza nella dashboard 
- [ ] Problemi di visualizzazione nella dashboard 

- Regione: Lombardia (il 02/05/2020 ma tutte)
- Provincia: tutte

## Riassunto

Da vostra nota:

- 02/05/2020: dati Regione Lombardia ricalcolati 329 decessi (47 di oggi e 282 da riconteggio di aprile)

Questi 282 decessi riportati dovrebbero avere una data della fatalità avvenuta, a meno che veramente non si abbia idea del giorno, e venire aggiunti ai rispettivi giorni, altrimenti non ha nessun senso tenere online tutti i file del passato se poi non vengono modificati in caso di ricalcolo.

I problemi  sono:

- La percezione dell'utente è che 329 persone siano morte in Lombardia ieri per COVID.

- Un ricercatore che utilizzi i dati per effettuare analisi dovrà andare a mano a spulciare tutte le note e non saprà comunque come comportarsi, se togliere dal computo gli aggiunti, se distribuirli a caso lungo il mese, o se lasciarli tutti in quel giorno come forniti.

**Attesa:**

Ci si sarebbe aspettati che i 282 casi inseriti avessero una data ciascuno e quindi venissero inseriti nei rispettivi giorni.

**Attuale:** A fine mese sembra che si siano registrati 282 decessi in più rispetto ai 47 realmente avvenuti.

**Comment by umbros** [comment]
Ciao @francescom concordo con il tuo suggerimento ma non abbiamo questa informazione da Regione Lombardia.
