### ISSUE TITLE
Casi testati, chiarimento metodologico 

### ISSUE THREAD

**Issue by vi-enne** [pcm-dpc/COVID-19#621]
**Tipo di richiesta**:  richiesta di informazione 

## Riassunto

Conosco la differenza fra tamponi e casi testati:

Numero tamponi si riferisce al numero di tamponi effettuati, mentre casi testati si riferisce al numero di singole persone sottoposte a tampone.

Dato che una stessa persona può essere sottoposta a più di un tampone (ad esempio, per accertarne al guarigione), numero tamponi >= numero casi testati.

La mia richiesta di chiarimento riguarda se le singole persone testate sono ancora contate in assoluto oppure ogni giorno.

Se fossero contate ogni giorno, se si effettuasse un tampone alla persona A il giorno 1 e due tamponi alla stessa persona il giorno 2, i casi testati sarebbero 1 e 1 per i due giorni, ma 2 in totale.

Sembra assurdo, ma è un errore metodologico facile da fare.

Avreste una fonte ufficiale che descriva il metodo di raccolta dei casi testati?

Grazie

## Interesse pubblico
Chiarezza

**Comment by umbros** [comment]
Ciao @vi-enne, contate in assoluto, il dato è un complessivo.

**Comment by vi-enne** [comment]
Grazie @umbros della risposta.

Questo conferma che Basilicata e Calabria non fanno tamponi di controllo per le guarigioni o che i loro dati sui tamponi sono SBAGLIATI.
