### ISSUE TITLE
Errore nuovi positivi Regione Sardegna file JSON

### ISSUE THREAD

**Issue by simonefanari** [pcm-dpc/COVID-19#622]
Tipo di issue:

- [x] Dati mancanti o errati 
- [ ] Errore nella documentazione 
- [ ] Errore or mancanza nella dashboard 
- [ ] Problemi di visualizzazione nella dashboard 

- Regione: Sardegna

## Riassunto

 File json dpc-covid19-ita-regioni.json relativamente  alla Regione Sardegna riporta erroneamente  "nuovi_positivi": -2.

**Comment by umbros** [comment]
Ciao @simonefanari c'è stato un riconteggio ed è sballato il calcolo di nuovi positivi che deve sempre tendere a 0, abbiamo inserito una nota sul riconteggio.
