### ISSUE TITLE
Dati comunicati dal Trentino vs dati DPC + Nuova Classificazione dei contagi

### ISSUE THREAD

**Issue by Rabelaiss** [pcm-dpc/COVID-19#623]
Il presidente della Provincia autonoma di Trento, Maurizio Fugatti, ha ieri [comunicato](https://www.ufficiostampa.provincia.tn.it/Comunicati/Coronavirus-2-decessi-e-28-nuovi-contagi-nelle-ultime-24-ore) che nel Trentino ci sono stati 28 nuovi casi e 2 decessi.
I dati della DPC riportano 16 nuovi casi (11 a Trento, 5 a Bolzano) e 4 decessi (1 a Trento, 3 a Bolzano).

Nell'articolo di Fugatti viene però affermato che
> nei prossimi giorni si terrà conto di una nuova classificazione dei contagi voluta dal Ministero della Salute per avere un quadro più chiaro e maggiormente aderente alla realtà della situazione. I nuovi contagi verranno classificati in due fattispecie: le persone che hanno manifestato i sintomi negli ultimi 5 giorni, in questo caso in Trentino sono 11, e coloro che, invece, li hanno avuti in precedenza, in questo caso sono 17. Da qui il totale di 28 nuovi contagiati registrato oggi.

Come interpretare il dato "11 persone hanno manifestato sintomi degli ultimi 5 giorni", quando la differenza tra i casi totali di ieri (in Trentino) e i casi totali di 5 giorni fa è 4258-4116=142?

Inoltre, questa nuova classificazione di cui parla l'articolo cambierà il modo in cui il DPC comunicherà i dati?

**Comment by vitop72** [comment]
ma solo il trentino fa così o anche altre? dove sta riportata questa nuova "classificazione dei contagi" sul sito del ministero della salute?

**Comment by Rabelaiss** [comment]
@vitop72 non lo so, speravo rispondesse la protezione civile per chiarire la cosa

**Comment by acecondor** [comment]
Sembra che la P.A. di Trento abbia (più o meno volontariamente) erroneamente interpretato una circolare del Ministero della Salute: https://www.ildolomiti.it/cronaca/2020/coronavirus-miracolo-trentino-come-cambiando-la-comunicazione-dei-dati-la-provincia-di-trento-e-passata-dalla-zona-rossa-a-covid-free
