### ISSUE TITLE
API Rest

### ISSUE THREAD

**Issue by 3nomis** [pcm-dpc/COVID-19#624]
Avete in programma di fare una API REST chiamabile?

**Comment by downFast** [comment]
> Avete in programma di fare una API REST chiamabile?

le ha già git volendo o si fa uno scraping o download dei json con un cron job, idealmente se risolvessero alcuni dei dubbi posti nei tanti issues sarebbe tempo meglio usato che per creare delle REST API che possiamo far da soli, è una manna dal cielo già che abbiano fornito un json

**Comment by umbros** [comment]
@downFast il mettere a disposizione API Rest (in previsione c'è la predisposizione di API Rest e GraphQL) non è soltanto un fatto applicativo ma anche di traffico network e resilienza del sistema in quanto le API potrebbero essere chiamate ad ogni interrogazione di dashboard o altri sistemi. Stay tuned!

**Comment by downFast** [comment]
> @downFast il mettere a disposizione API Rest (in previsione c'è la predisposizione di API Rest e GraphQL) non è soltanto un fatto applicativo ma anche di traffico network e resilienza del sistema in quanto le API potrebbero essere chiamate ad ogni interrogazione di dashboard o altri sistemi. Stay tuned!

esatto quindi se ognuno di noi prendesse come stiamo facendo i dati direttamente da qui, non ci sarebbe alcun problema, come non li ha ora, di traffico e resilienza, lasciando voi più tempo per il perfezionamento dei dati raccolti più che altro

Avevo chiesto in precedenza la possibilità di unificare le note nel file json con i nati, in modo tale che mostrando i dati potremmo dire ecco oggi 100 ma calcolate che N non sono pervenuti. Cosi da evitare confusioni. Alla fine sarebbe da fare un merge note con il file json, non so perchè non lo abbiate fatto

**Comment by umbros** [comment]
@downFast i dati sui vari tracciati sono lincabili, cmq se mi dici la issue la esaminiamo, grazie

**Comment by downFast** [comment]
> @downFast i dati sui vari tracciati sono lincabili, cmq se mi dici la issue la esaminiamo, grazie

Ma no guarda lasciare stare la issue non preoccuparti, grazie. Era giusto cosi per dire, vedi qui che ci sono ora (tempo fa non c'erano, avevo chiesto l'inserimento delle note che prima venivano semplicemente mostrate in rosso in home page qui mentre ora sono in json )

https://github.com/pcm-dpc/COVID-19/tree/master/dati-json

Quindi giusto per una questione di facilità, si potrebbe fare un merge di questa roba e appenderla come oggetto nel json (anche quello storico giornaliero), cosi che poi volendo possiamo mostrare quella info. Giusto perché al momento prendiamo un dato json e poi quel json a parte, si potrebbe fare un merge dei due e fare cosi un'unica chiamata, that's it.

**Comment by aborruso** [comment]
@3nomis ci sono delle API non ufficiali qui https://github.com/pcm-dpc/COVID-19/issues/557
