### ISSUE TITLE
dati Lombardia

### ISSUE THREAD

**Issue by mschips** [pcm-dpc/COVID-19#626]
**richiesta di informazione**: 

Ciao, so che simili issues sono state già aperte ma non ho trovato le risposte che cercavo.
Vorrei un chiarimento a proposito dei dati della Lombardia.

- Cosa si intende nei dati riportati dalla regione per “Dimessi”? Sono i “Guariti”?
- A prima vista sembra che la differenza tra dimessi e soggetti con un passaggio in ospedale coincida con il vostro comparto “isolamento domiciliare”, è così? E la restante parte?
- In che modo calcolate il numero di Dimessi/Guariti ? Non sono riuscita a risalire a nessuna corrispondenza con i dati sul sito della regione.

Grazie mille per la repository e le informazioni!!

**Comment by vi-enne** [comment]
Qui c'è un articolo interessante del Sole 24 Ore.
Potrebbe rispondere alla tua domanda :)

https://www.infodata.ilsole24ore.com/2020/04/10/la-regione-lombardia-sovrastima-guariti-covid-19-laccusa-della-fondazione-gimbe/

**Comment by Paulsword** [comment]
Oggi per la prima volta mettono mano agli isolamenti domiciliari, che fino a ieri erano gestiti come cumulativi (corrispondono ai dimessi senza passaggio in ospedale nelle slide della regione, mentre per guariti hanno sempre notificato tutti e solo i dimessi dagli ospedali).
