### ISSUE TITLE
dati-regioni

### ISSUE THREAD

**Issue by dami2491** [pcm-dpc/COVID-19#627]
Nella cartella dei "dati-regioni" nel file dei dati aggiornati al 26 febbraio (dpc-covid19-ita-regioni-20200226.csv) e precisamente nella colonna dei "totale_casi" in Piemonte viene riportato che erano presenti 3 casi totali mentre nel file successivo, dei dati aggiornati al 27 Febbraio (dpc-covid19-ita-regioni-20200227.csv) c'è scritto che erano 2. Errore di battitura ?

**Comment by umbros** [comment]
@dami2491 è quanto comunicato dalla Regione, possibile un caso di riconteggio.
