### ISSUE TITLE
Probabile refuso data record note Basilicata in dpc-covid19-ita-note-it.json

### ISSUE THREAD

**Issue by mydozer** [pcm-dpc/COVID-19#629]
Ciao!

- Dati mancanti o errati dpc-covid19-ita-note-it.json

- Regione: Basilicata

nel file json sono presenti record che sembrano duplicati

        "codice": "dc-IT-0022",
        "data": "2020-05-07T17:00:00",
        "dataset": "dati-regioni",
        "stato": "ITA",
        "codice_regione": 17,
        "regione": "Basilicata",
        "codice_provincia": null,
        "provincia": "",
        "sigla_provincia": "",
        "tipologia_avviso": "correzione dati",
        "avviso": "ricalcolo delle informazioni",
        "note": "ricalcolo casi positivi (diminuzione)"
    },
    {
        "codice": "dc-IT-0023",
        "data": "2020-05-07T17:00:00",
        "dataset": "dati-andamento-nazionale",
        "stato": "ITA",
        "codice_regione": 17,
        "regione": "Basilicata",
        "codice_provincia": null,
        "provincia": "",
        "sigla_provincia": "",
        "tipologia_avviso": "correzione dati",
        "avviso": "ricalcolo delle informazioni",
        "note": "ricalcolo casi positivi (diminuzione)"
    },
    {
        "codice": "dc-IT-0024",
        "data": "2020-05-07T17:00:00",
        "dataset": "dati-regioni",
        "stato": "ITA",
        "codice_regione": 17,
        "regione": "Basilicata",
        "codice_provincia": null,
        "provincia": "",
        "sigla_provincia": "",
        "tipologia_avviso": "correzione dati",
        "avviso": "ricalcolo delle informazioni",
        "note": "ricalcolo casi positivi (diminuzione)"
    },
    {
        "codice": "dc-IT-0025",
        "data": "2020-05-07T17:00:00",
        "dataset": "dati-andamento-nazionale",
        "stato": "ITA",
        "codice_regione": 17,
        "regione": "Basilicata",
        "codice_provincia": null,
        "provincia": "",
        "sigla_provincia": "",
        "tipologia_avviso": "correzione dati",
        "avviso": "ricalcolo delle informazioni",
        "note": "ricalcolo casi positivi (diminuzione)"
    }

E' corretta la data? Si riferisce ai dati odierni 08/05?

Grazie!!

**Comment by umbros** [comment]
Ciao, è corretto perchè si è verificato il problema anche domani (comunicato da Regione Basilicata) motivo per il quale su nuovi positivi abbiamo -1
