### ISSUE TITLE
Problematiche repository: pull brach master

### ISSUE THREAD

**Issue by mydozer** [pcm-dpc/COVID-19#630]
Ciao,
è il secondo giorno di fila che l'operazione di pull non permette di fare il merge automatico del brach master. Ieri ho dovuto rinominare il branch master in master_old per poter fare un pull pulito. Oggi il problema si è ripresentato. State facendo per caso facendo fork del branch master ad ogni rilascio?

Dai riferimenti sembra che nessuno dei master dei giorni precedenti abbia ereditato la storia del predecessore.

Vedi immagine

![image](https://user-images.githubusercontent.com/61920330/81479069-5b350980-9221-11ea-85f0-408385e7c4e0.png)

Grazie!!

**Comment by umbros** [comment]
Ciao @mydozer, nessuna attività di fork o in generale sui branch se non push. A noi non sono risultati problemi di pull, Se la cosa si ripresenta possiamo contattare Github.  Grazie della segnalazione.

**Comment by umbros** [comment]
@mydozer ti risultano ancora i problemi segnalati?

**Comment by mydozer** [comment]
Ciao @umbros, negli ultimi due giorni non ho rilevato nessun problema. Grazie!!

**Comment by umbros** [comment]
grazie a te
