### ISSUE TITLE
Nuovi dati

### ISSUE THREAD

**Issue by Paulsword** [pcm-dpc/COVID-19#633]
@umbros innanzitutto grazie per il bel lavoro, che è sicuramente un primo passo nella direzione giusta.
Come ben noto, dal decreto del 26 aprile, la pdc ha richiesto alle Regioni/PA di integrare i dati con nuove informazioni, per consentire un monitoraggio più tempestivo e puntuale dell'epidemia, che include alcuni elementi di flusso, non solo statici (per chi non avesse in mente vi rimando alle ultime tabelle di questo [link](https://ilsegnalatore.info/le-basi-epidemiologiche-del-decreto-fase2/)).

In particolare e sintetizzando, si richiede che vi sia almeno il 60% (e con trend in miglioramento) dei:
- casi sintomatici che includano indicazione della data di inizio sintomi
- casi ricoverati in reparto che includano indicazione della data di ricovero
- casi ricoverati in terapia intensiva che includano indicazione della data di ammissione in TI
- casi con indicazione del comune di domicilio o residenza.

Dunque chiedo se vi sia alcuna prospettiva di ottenere questi dati, o simili, o aggregazioni di essi, qui o presso altre fonti.

Grazie per qualsiasi risposta.

**Comment by umbros** [comment]
Ciao @Paulsword stiamo lavorando con salute per la pubblicazione di tali dati
