### ISSUE TITLE
Anomalia dati variazione nuovi positivi

### ISSUE THREAD

**Issue by gianlucamalato** [pcm-dpc/COVID-19#635]
Tipo di issue:

- [x] Dati mancanti o errati dpc-covid19-ita-andamento-nazionale.csv

## Riassunto

Il dato di oggi della variazione del totale positivi nel totale nazionale non quadra con quanto riportato sul sito della Protezione Civile (-1222).
**Attesa:** -1222

**Attuale:** 486

**Comment by framilano** [comment]
Sono stati caricati gli stessi dati del 19 aprile, pare sia in correzione [#635](https://github.com/pcm-dpc/COVID-19/issues/638)

**Comment by umbros** [comment]
Corretto!
