### ISSUE TITLE
ERRORE data nel tracciato odierno dpc-covid19-ita-regioni.csv

### ISSUE THREAD

**Issue by anbened** [pcm-dpc/COVID-19#636]
Errore data nel file:

https://raw.githubusercontent.com/pcm-dpc/COVID-19/master/dati-regioni/dpc-covid19-ita-regioni.csv

20202020-05-12T17:00:00,ITA,13,Abruzzo

**Comment by lp74** [comment]
Confermo che anche a me i dati appaiono inconsistenti

**Comment by pinoli** [comment]
Non voglio aprire un seconda issue ma i dati rilasciati oggi sono errati e incompatibili con l'andamento dei valori precedenti.

Questo errore è presente nei dati-json e presumibilmente anche negli altri dataset
Es.: il totale casi passa da 219814 di ieri ai 178972 di oggi.

**Comment by 123cobloc** [comment]
errore nelle colonne 
dimessi_guariti | deceduti | totale_casi | tamponi

**Comment by gianlucamalato** [comment]
Concordo. Il dato ha un formato errato.

**Comment by giova86** [comment]
I dati sono del 19 Aprile....oltre che nel formato sbagliato

**Comment by Paulsword** [comment]
E' finito dentro il dataset del 19 aprile

**Comment by umbros** [comment]
corretto!
