### ISSUE TITLE
Wrong Data Uploaded

### ISSUE THREAD

**Issue by Jakibrn** [pcm-dpc/COVID-19#637]
Tipo di issue:

- [ ] Dati mancanti o errati 
- [X] Errore nella documentazione 
- [ ] Errore or mancanza nella dashboard 
- [ ] Problemi di visualizzazione nella dashboard

**Comment by giova86** [comment]
riga 1369 regioni è sbagliata!! 20202020...

**Comment by dallanoce** [comment]
Sembrerebbe siano stati aggiunti erroneamente come dati odierni (12 Maggio) i dati relativi al 19 aprile 2020.

**Comment by Tantormai** [comment]
Sì, i dati dei files csv sono quelli del 19 Aprile.
Sono corretti solo i files pdf.

**Comment by umbros** [comment]
Corretto!
