### ISSUE TITLE
Totale casi inconsistente sul riepilogo nazionale

### ISSUE THREAD

**Issue by emazep** [pcm-dpc/COVID-19#638]
Oggi abbiamo un totale casi di 178972 unità contro le 219814 di ieri, cosa chiaramente impossibile visto che il dato cumulato deve essere non decrescente. Sospetto anche altre incongruenze, che ora verificherò meglio.

File:
https://raw.githubusercontent.com/pcm-dpc/COVID-19/master/dati-andamento-nazionale/dpc-covid19-ita-andamento-nazionale.csv

**Comment by lp74** [comment]
Confermo

**Comment by Rabelaiss** [comment]
I dati sono tutti sballati, anche quelli regionali

**Comment by hardhu** [comment]
I dati del Veneto sono visibilmente sbagliati

**Comment by massi-paci** [comment]
Sembra siano stati pubblicati gli stessi dati del 19/04

**Comment by giova86** [comment]
hanno messo i dati del 19 aprile...

**Comment by emazep** [comment]
Confermo un altro errore: 2635 terapie intensive oggi, chiaramente impossibile. I dati odierni (perlomeno) del riepilogo nazionale appaiono completamente falsati, si prega di correggerli.

**Comment by framilano** [comment]
Parecchie incongruenze, nei deceduti, nei guariti e probabilmente anche nel calcolo dei positivi
Tutto questo nei dati di andamento nazionale

**Comment by umbros** [comment]
in correzione

**Comment by MohammedAlrozzi** [comment]
umbria numbers as well. they are not correct.

**Comment by gerrygeko** [comment]
anche la data del nel csv dei dati regionali ha un formato non corretto per l'Abruzzo

**Comment by umbros** [comment]
corretto!
