### ISSUE TITLE
DATI 12 Maggio 2020 completamente sballati

### ISSUE THREAD

**Issue by alexodus** [pcm-dpc/COVID-19#639]
I dati del giorno sono completamente sballati

**Comment by arystay** [comment]
Seguo. Anche io sto notando problemi in questi dati

**Comment by oriana1975** [comment]
Del tutto sbagliati e diversi da quelli riportati nel pdf

**Comment by Rabelaiss** [comment]
già segnalato qui https://github.com/pcm-dpc/COVID-19/issues/638
stanno risolvendo

**Comment by umbros** [comment]
corretto!

**Comment by vitop72** [comment]
COMPLETAMENTE sbagliati.. a leggere solo i numeri della terapia intensiva del 12/5 si arriva a 2635

**Comment by alexodus** [comment]
ragà sono  degli incompetenti

**Comment by alexodus** [comment]
stiamo facendo figure di merda a livello mondiale...le issue aperte dagli stranieri! mahhhh
