### ISSUE TITLE
Dati del 12-05

### ISSUE THREAD

**Issue by unbombarolo** [pcm-dpc/COVID-19#640]
**Tipo di richiesta**: richiesta di dati 

## Riassunto

I dati del 12-05 sono replicati dal 19-04

## Interesse pubblico

Per qualche motivo, i dati numerici di oggi sono identici a quelli del 19 aprile: probabilmente c'è stato un errore di trascrizione. Vi pregherei di aggiornare i file. Grazie!

**Comment by umbros** [comment]
corretto!

**Comment by unbombarolo** [comment]
Grazie!
