### ISSUE TITLE
Buon pomeriggio. I dati contenuti nei file csv nazionale e regionale di oggi 12 Maggio corrispondono a quelli del 19 Aprile

### ISSUE THREAD

**Issue by Simonepu** [pcm-dpc/COVID-19#641]
Tipo di issue:

- [ ] Dati mancanti o errati 
- [ ] Errore nella documentazione 
- [ ] Errore or mancanza nella dashboard 
- [ ] Problemi di visualizzazione nella dashboard 

- Regione:
- Provincia: 

## Riassunto

**Attesa:**

**Attuale:**

**Comment by Simonepu** [comment]
ADESSO SONO CORRETTI. Grazie

**Comment by umbros** [comment]
corretto!
