### ISSUE TITLE
Possibile errore nei numeri di dpc-covid19-ita-regioni.csv

### ISSUE THREAD

**Issue by sapienzafra** [pcm-dpc/COVID-19#644]
Con il file dpc-covid19-ita-regioni.csv di ieri il mio script per il giorno 11 maggio calcolava correttamente 82.488 attualmente positivi. Con il file di oggi, sempre nel giorno 11 maggio ne calcola 77.028.
È possibile che ci sia un errore?

**Comment by umbros** [comment]
@sapienzafra c'è stato un errore nello script oggi è risolto. Puoi rifare pull.

**Comment by kr4lizec** [comment]
Il problema era stato segnalato nell'issue https://github.com/pcm-dpc/COVID-19/issues/638
Come mai è stato cancellato?

**Comment by sapienzafra** [comment]
Con il nuovo pull è tutto in ordine,
un saluto e grazie

**Comment by umbros** [comment]
@kr4lizec erano molti ripetuti

**Comment by kr4lizec** [comment]
Grazie!
