### ISSUE TITLE
Errore dati riepilogo regionale

### ISSUE THREAD

**Issue by emazep** [pcm-dpc/COVID-19#645]
Nei dati del riepilogo regionale per la giornata in corrispondenza della data di ieri 2020-05-11 manca la riga relativa al Veneto (ma l'errore è dovuto all'ultima commit di oggi, essendo tale riga presente nella commit di ieri).

File:
https://raw.githubusercontent.com/pcm-dpc/COVID-19/master/dati-regioni/dpc-covid19-ita-regioni.csv

**Comment by umbros** [comment]
Corretto!
