### ISSUE TITLE
positivi Bergamo

### ISSUE THREAD

**Issue by Babidi90** [pcm-dpc/COVID-19#646]
e' possibile che il recupoero dei positivi in lombardia sia tutto a Bergamo?
c'è un incremento importante di positivi più di 500 rispetto gli ultimi giorni, media 50.

**Comment by anbened** [comment]
BS: 13.748 +128 (ieri +70)
BG: 12.294 +503 (ieri +50)

Le altre città mi sembrano in linea

**Comment by umbros** [comment]
Ciao, abbiamo messo un avviso comunicatoci da Regione Lombardia per la giornata di oggi:
"aggiunti 419 casi positivi con diagnosi prima degli ultimi 7 giorni"

**Comment by Babidi90** [comment]
Grazie, la mia domanda era se quei 419 recuperati non siano tutti o quasi a bg ?
Grazie per la risposta

Inviato da iPhone

Il giorno 12 mag 2020, alle ore 19:31, Umberto Rosini <notifications@github.com<mailto:notifications@github.com>> ha scritto:


Ciao, abbiamo messo un avviso comunicatoci da Regione Lombardia per la giornata di oggi:
"aggiunti 419 casi positivi con diagnosi prima degli ultimi 7 giorni"
