### ISSUE TITLE
Ennesimo errore: dati numerici in formato stringa

### ISSUE THREAD

**Issue by alexodus** [pcm-dpc/COVID-19#647]
Un errore dietro l'altro. Ma prendete qualcuno bravo no? Bohh!

**Comment by umbros** [comment]
@alexodus possono esserci dei problemi tecnici e vengono risolti subito. Grazie della segnalazione!

**Comment by alexodus** [comment]
E' un errore capitato altre 2 volte. Avete degli script evidentemente sballati. Metteteli a disposizione e fatevi dare una mano. Sono già 2 volte che mando notifice alle app per dei dati inconsistenti.

**Comment by umbros** [comment]
@alexodus gli script non sono sballati dato che come dici tu è capitato 2 volte in 82 giorni di caricamento dati. Riguardo la mano siamo assolutamente aperti
