### ISSUE TITLE
Le date in in /note/dpc-covid19-ita-note-it.csv dell'ultima nota non sono corrette

### ISSUE THREAD

**Issue by francescom** [pcm-dpc/COVID-19#648]
Tipo di issue:

- [X] Dati mancanti o errati /note/dpc-covid19-ita-note-it.csv
- [ ] Errore nella documentazione 
- [ ] Errore or mancanza nella dashboard 
- [ ] Problemi di visualizzazione nella dashboard 

- Regione: Lombardia
- Provincia: 

## Riassunto

Segnalo una leggera incorrettezza nei dati delle note.

Le date dell'ultima nota in /note/dpc-covid19-ita-note-it.csv sono assegnate al 2020-05-06

mentre la stessa nota è correttamente assegnata al 12/05/2020 in /avvisi.md 

**Attesa:**

dc-IT-0026,2020-05-**12**T17:00:00,dati-regioni,ITA,03,Lombardia,,,,correzione dati,ricalcolo delle informazioni,aggiunti 419 casi positivi con diagnosi prima degli ultimi 7 giorni

dc-IT-0027,2020-05-**12**T17:00:00,dati-andamento-nazionale,ITA,03,Lombardia,,,,correzione dati,ricalcolo delle informazioni,aggiunti 419 casi positivi con diagnosi prima degli ultimi 7 giorni

(in fondo a note/dpc-covid19-ita-note-it.csv)

**Attuale:** 

dc-IT-0026,2020-05-06T17:00:00,dati-regioni,ITA,03,Lombardia,,,,correzione dati,ricalcolo delle informazioni,aggiunti 419 casi positivi con diagnosi prima degli ultimi 7 giorni
dc-IT-0027,2020-05-06T17:00:00,dati-andamento-nazionale,ITA,03,Lombardia,,,,correzione dati,ricalcolo delle informazioni,aggiunti 419 casi positivi con diagnosi prima degli ultimi 7 giorni

(in fondo a note/dpc-covid19-ita-note-it.csv)

**Comment by umbros** [comment]
corretto grazie
