### ISSUE TITLE
Che fine ha fatto il Wiki?

### ISSUE THREAD

**Issue by maurosaladino** [pcm-dpc/COVID-19#649]
Salve, leggendo i vari Issues presenti mi è capitato più volte di leggere dei chiarimenti sul significato dei dati (spesso molto interessanti) facendo riferimento ad un Wiki disponibile al seguente url:

https://github.com/pcm-dpc/COVID-19/wiki/1.it-Dati:-andamento-nazionale

Dal momento che l'url non è raggiungibile, potrei sapere che fine ha fatto il Wiki?
Grazie

**Comment by umbros** [comment]
Ciao Mauro,
abbiamo deciso di utilizzare le pagine direttamente sul repository e stiamo traduecneod le parti in inglese.
