### ISSUE TITLE
Conversione proiezione

### ISSUE THREAD

**Issue by piersoft** [pcm-dpc/COVID-19#65]
Salve su:
https://github.com/pcm-dpc/COVID-19/tree/master/aree/geojson

sarebbe più corretto mettere una proiezione WGS84 EPSG4326 in modo da poterla utilizzare più facilmente con i tools opensource classici.
Lo stesso github non riesce a mostrare l'anteprima.
thanks

Tipo di issue:

- [ ] Dati mancanti o errati 
- [ ] Errore nella documentazione 
- [ ] Errore or mancanza nella dashboard 
- [ ] Problemi di visualizzazione nella dashboard 

## Riassunto

**Attesa:**

**Attuale:**

**Comment by tehKapa** [comment]
@piersoft your issue seems to have been resolved with [this commit](https://github.com/pcm-dpc/COVID-19/commit/9a397331e5270f7f80e0bf399fb1fab244046ad4

**Comment by umbros** [comment]
Ciao @piersoft ora è visualizzato correttamente anche su github oltre che su geojson.io
![immagine](https://user-images.githubusercontent.com/4085151/76315269-a477e400-62d8-11ea-87c3-6816493b4fd7.png)
