### ISSUE TITLE
Conteggi cumulativi decrescenti e bug addizionali

### ISSUE THREAD

**Issue by emanuele-guidotti** [pcm-dpc/COVID-19#651]
Tipo di issue:

- [x] Dati mancanti o errati 
- [ ] Errore nella documentazione 
- [ ] Errore or mancanza nella dashboard 
- [ ] Problemi di visualizzazione nella dashboard 

- Regione: Multiple
- Provincia: Multiple

## Riassunto

Abbiamo rilevato vari errori nei dati quali: 

- casi confermati maggiori di casi testati
- conteggi cumulativi decrescenti 

Potete trovare un log aggiornato degli errori a questo indirizzo:
https://covid19datahub.io/articles/iso/ITA.html

**Attesa:**

Spero il tool possa aiutare nell'identificazione e risoluzione dei bug.

**Attuale:** 

Vedi link sopra

-- Emanuele

**Comment by umbros** [comment]
Ciao @emanuele-guidotti grazie per l'analisi è la stessa effettuata da noi e che segnaliamo alle Regioni, quando c'è una comunicazione di problemi la segnaliamo in note ma i dati sono inseriti dalle Regioni stesse.

**Comment by emanuele-guidotti** [comment]
Capisco, mi sorprende la quantità di records in cui i conteggi cumulativi sono decrescenti (la maggioranza dei 142 errori rilevati). 

Questa tipologia di bug è già segnalata alle Regioni e viene corretta nel file https://github.com/pcm-dpc/COVID-19/blob/master/dati-regioni/dpc-covid19-ita-regioni.csv

Ho capito bene?
