### ISSUE TITLE
All data for codice_regione = 4 removed

### ISSUE THREAD

**Issue by SamanFekri** [pcm-dpc/COVID-19#652]
Type of issue:

- [x] Incorrect or missing data : dpc-covid19-ita-regioni.json 
- [ ] Incorrect or missing documentation 
- [ ] Incorrect or missing data in the dashboard 
- [ ] Layout problem in the dashboard 

- Region:
- Province: 

## Summary

Data be back **Expected:**

There is no data for codice_regione == 4 in it

**Comment by vi-enne** [comment]
The change has been announced 11 days ago in this issue #625

**Comment by umbros** [comment]
Hi  @SamanFekri the codice_regione = 4 is inside the directory "legacy-data": ex dati regioni: "codice_regione": 4, "denominazione_regione": "P.A. Bolzano", inside the current dir now the codice_regione is 21 for P.A. Bolzano and 22 for P.A. Trento, the change was done yesterday.
