### ISSUE TITLE
Errore Casi Testati Emilia

### ISSUE THREAD

**Issue by Babidi90** [pcm-dpc/COVID-19#653]
I casi testati in Emilia sono 163117 solo +50 rispetto a ieri (163067).
Potete verificare?

Tipo di issue:

- [x] Dati mancanti o errati 
- [ ] Errore nella documentazione 
- [ ] Errore or mancanza nella dashboard 
- [ ] Problemi di visualizzazione nella dashboard 

- Regione:
- Provincia: 

## Riassunto

**Attesa:**

**Attuale:**

**Comment by umbros** [comment]
Ciao, sono quelli comunicati da Regione Emilia Romagna, i casi testati sono != da tamponi
