### ISSUE TITLE
-531 delta dimessi_guariti P.A. Trento

### ISSUE THREAD

**Issue by emazep** [pcm-dpc/COVID-19#654]
La P.A. di Trento riporta oggi (22/05/2020) un **delta** dei **dimessi_guariti** negativo (che già di per sé costituisce un errore), peraltro con un valore assoluto esorbitante: **-531** (il valore del campo **dimessi_guariti** è di **3326** oggi e di **3857** ieri, mentre trattandosi di un valore cumulato dovrebbe essere ovviamente non decrescente).

**Comment by Paulsword** [comment]
E devono comunicare 8 numeri. Dico 8, non 8000. Pasticcioni.

**Comment by emazep** [comment]
La cosa assurda è che non ci sia nemmeno uno straccio di controllo di consistenza, almeno sulla monotonia dei dati cumulati :-(

**Comment by vi-enne** [comment]
I dati della PA Trento comunicati alla Protezione Civile sono dichiaratamente sottostimati: [qui](https://www.ildolomiti.it/cronaca/2020/coronavirus-miracolo-trentino-come-cambiando-la-comunicazione-dei-dati-la-provincia-di-trento-e-passata-dalla-zona-rossa-a-covid-free) un articolo e [qui](https://www.ufficiostampa.provincia.tn.it/Comunicati/Coronavirus-dieci-contagiati-e-due-decessi-oggi-in-Trentino?fbclid=IwAR3Ey4EsnFoN66-_gF_IZ2IXuQrwi1AOyy0ZP1XD-O04S2uPnYV_sEx8T8g) il comunicato provinciale del 19 maggio da confrontare con la tabella PC.

Questo fa sì che numerose incongruenze appaiano e appariranno nei prossimi giorni: mi aspetto infatti che presto il numero dei guariti supererà il numero di casi totali!

**Comment by emazep** [comment]
@vi-enne: gli errori da te segnalati sono sempre stati corretti attraverso un incremento o decremento (artificiale) dei nuovi casi giornalieri dei giorni successivi, ovvero dei campi **totale_casi** e, di conseguenza **nuovi_positivi** (cosa che già costituisce una bestialità), per cui non c'è ragione di un intervento sui **dimessi_guariti** (cosa che costituirebbe una bestialità al quadrato).

**Comment by umbros** [comment]
Ciao a tutti, al momento non c'è stato comunicato da P.A. Trento riconteggio o errori sui dati. Stiamo controllando la cosa e comunque per policy mettiamo l'avviso solo se questo è notificato dal soggetto che comunica il dato. Grazie a tutti per le segnalazioni.

**Comment by vi-enne** [comment]
> @vi-enne: gli errori da te segnalati sono sempre stati corretti attraverso un incremento o decremento (artificiale) dei nuovi casi giornalieri dei giorni successivi, ovvero dei campi **totale_casi** e, di conseguenza, **nuovi_positivi**

Vero in generale, pero' questo intervento non e' stato ancora fatto per PA Trento da quando e' iniziata la discrepanza (nell'articolo del mio commento precedente si risale ad almeno l'8 maggio).

Riguardo lo specifico errore segnalato, credo sia legato a questo problema: 
- PA Trento non segnala i positivi che non hanno sintomi negli ultimi 5 giorni
- Ne segue che questi positivi non sono ricoverati con sintomi e nemmeno in terapia intensiva (per definizione)
- Dovrebbero quindi finire in Isolamento Domiciliare o almeno in Dimessi/Guariti

Mi sembra che ieri PA Trento abbia maldestramente tentato di "bilanciare" spostando casi da Isolamento Domiciliare a Dimessi/Guariti, ma senza aggiornare ne' nuovi_positivi, ne' casi_totali, ne' Isolamento Domiciliare.
Accortosi della variazione estrema di isolamento domiciliaire, oggi hanno continuato a fornire l'informazione coerentemente al 20 maggio.
