### ISSUE TITLE
P.A. Trento, dati del 22-05-2020

### ISSUE THREAD

**Issue by davidebaltieri31** [pcm-dpc/COVID-19#655]
Tra ieri e oggi (22-05) i dati regionali su isolamento domiciliare e totale positivi per la P.A. di Trento sono variati di oltre 500 unità, ma non vi è nessuna nota se si tratta di un ricalcolo o meno. 
Possibile errore nei dati?

**Comment by vi-enne** [comment]
Puoi confrontare #623 e #654

**Comment by ecor** [comment]
Avevo scritto tempo fa, i dati che la Provincia Autonoma di Trento prende per ufficiali sono i seguenti: https://covid19trentino.fbk.eu/  redatti dalla Fondazione Bruno Kessler. Ci sono divegernza con i dati della Protezione Civile gia' da marzo.

**Comment by vi-enne** [comment]
> Avevo scritto tempo fa, i dati che la Provincia Autonoma di Trento prende per ufficiali sono i seguenti: https://covid19trentino.fbk.eu/ redatti dalla Fondazione Bruno Kessler di Trento. Ci sono divegernza con i dati della Protezione Civile gia' da marzo.

Grazie del link, davvero interessante.

Rimane la domanda del perche' la PA Trento non comunichi questi dati alla Protezione Civile.

Inoltre, e' PA Trento a prendere per ufficiali i dati della FBK, o la FBK a prendere per ufficiali i dati delle comunicazione regionali della PA Trento?
E' una differenza sottile ma importante.
