### ISSUE TITLE
Encoding sbagliato per il file dpc-covid19-ita-province-20200520.csv

### ISSUE THREAD

**Issue by lucalista** [pcm-dpc/COVID-19#657]
Tipo di issue:

- [ ] Dati mancanti o errati 
- [ ] Errore nella documentazione 
- [ ] Errore o mancanza nella dashboard 
- [x] Problemi di visualizzazione nella dashboard 

- Regione: Emilia Romagna
- Provincia: Forlì-Cesena

## Riassunto

Il file dpc-covid19-ita-province-20200520.csv è codificato iso-8859-1 anziché utf-8.
Per questo motivo, la provincia di Forlì può creare problemi di interpretazione perché il carattere accentato può essere interpretato in maniera incorretta.

Di seguito quanto risulta sul file scaricato dal repository:

$ file -bi dpc-covid19-ita-province-20200520.csv
text/plain; charset=iso-8859-1
$ file -bi dpc-covid19-ita-province-20200521.csv
text/plain; charset=utf-8

**Attesa:**

**Attuale:**

**Comment by umbros** [comment]
@lucalista corretto, grazie.
