### ISSUE TITLE
Errore data note

### ISSUE THREAD

**Issue by vi-enne** [pcm-dpc/COVID-19#658]
Tipo di issue:

- [x] Dati mancanti o errati  [dpc-covid19-ita-note-it.csv](https://github.com/pcm-dpc/COVID-19/blob/master/note/dpc-covid19-ita-note-it.csv)
- [ ] Errore nella documentazione 
- [ ] Errore or mancanza nella dashboard 
- [ ] Problemi di visualizzazione nella dashboard 

- Regione:
- Provincia: 

## Riassunto
Le date delle note dc-IT- 30, 31, 32, 33 sembrano errate: riportano aprile, ma le note fanno riferimento a maggio.
Stessa cosa per le note in inglese.

**Comment by umbros** [comment]
Grazie corretto!
