### ISSUE TITLE
Excel

### ISSUE THREAD

**Issue by Fuffo00339958** [pcm-dpc/COVID-19#663]
Buon giorno, sono Fulvio Freschi, pensionato di Roma, ho preparato dei grafici semplificati (forse non abbastanza) per far capire meglio la situazione COVID-19 ai pensionati non troppo avvezzi alle raffigurazioni statistiche, invitando chi è più attivo ad aggiornarsi da sè giornalmente tabelle e grafici con i dati che Lei mette a disposizione, nella maniera più semplice possibile; ho riscontrato che a seconda del browser con il quale si pescano i dati, danno un risultato differente, con copiatura semplice (non solo testo, che per alcuni può essere difficilina): Firefox riporta nel foglio excel i dati su 44 righe (intervallate da una vuota), mentre Chrome (anche Opera, non ho modo di vedere Edge) dà le 22 righe originarie, traslate però tra l'intestazione e i idati, spostati di una colonna a destra (poco male), ma peggio, le province autonome sono denominate PA e non P.A. (e mi pareva non fosse sempre così, ora forse è sistemato), e questo sballa la ricerca, se non con funzioni di correzione che appesantiscono il file, poi alcune regioni iniziano con la minuscola (poco male).
N.B.: ho utilizzato un indicatore particolare, il rapporto tra i Casi attivi e il numero max del periodo (quello giornaliero, non quello successivo), indica quanto le strutture territoriali riescono a risolvere, si nota che in Umbria, Bolzano, Valle d'Aosta, Basilicata l'epidemia si stia quasi spegnendo, con pochissimi Nuovi casi.
Ho archiviato i miei files in un vecchio sito dei Cobas ormai quasi fuori uso: http://pensionati.cobas.it/pensionati/ARCHIVIO
E' un problema irrisolvibile di Chrome?

Altra questione: i dati sono verificati? Quelli del Trentino, il 21 maggio hanno visto uno spostamento di più di 500 individui, da DIMESSI/GUARITI a Isolamento domiciliare, il che è strano, avrebbe avuto più senso il  contrario anche se sensazionale: avrebbero cambiato il metodo di conteggio o di parametro, cioè sono correzioni giustificate? (si vede bene dai grafici, in allegato, che è il documento che distribuisco)
Grazie!

**Comment by vi-enne** [comment]
Per PA Trento, confronti le issues #623, #654, #655 e i dati della Fondazione Bruno Kessler https://covid19trentino.fbk.eu/

**Comment by umbros** [comment]
Buonasera @Fuffo00339958, i dati che rilasciamo sono in formato csv che, da come ho capito, usando lei excel possono essere importati, copia i dati nella visualizzazione di github? in tal caso la invito a utilizzare la funzione download e scaricare i file stessi, mi dica se con questa soluzione ha risolto

**Comment by Fuffo00339958** [comment]
Non vedo disponibile un download, forse perchè uso windows 7? cmq. tutti gli altri scarichi sono cmq. da elaborare, e il progetto prevede un uso il più semplice possibile, per incoraggiare i meno pratici e non spaventarli con troppe difficoltà: "apri la pagina di github", "cerca il file per data", "copia i dati"; "apri il file excel", "incollali nel punto giusto" ed excel fa tutto automaticamente, facilmente convertibile in .pdf . Così ho preferito una gestione interna al file excel. A chi può interessare, anche per modifiche da personalizzare, si trova il file nel sito indicato sopra nel primo issue.
Si può modificare il titolo dell'issue, anche perchè con un errore di battitura "Qustioni" e sostituirlo con Excel o simili? 
Grazie

**Comment by umbros** [comment]
Buonasera,
![immagine](https://user-images.githubusercontent.com/4085151/83045309-af275700-a045-11ea-9b0d-24bc9b1c6d58.png)
nell'immagine vede il pulsante "Clone or download" e cliccando si apre una finestra con un pulsante con la dicitura "Download ZIP" le farà scaricare ogni volta tutto comprese gli ultimi dati. Per qualsiasi altra info resto a disposizione.

**Comment by Fuffo00339958** [comment]
OK, visto da dove scaricare i dati grezzi. Ma scarica proprio tutto, oltre 230 MB, materiale che in gran parte rimane inutilizzato, e poi i dati grezzi estratti vanno cmq. divisi per colonne. Per l'uso excel, mi pare più comodo il copia integrale e poi incolla. Grazie!

**Comment by umbros** [comment]
Ok,
può scaricare ogni giorno il file aggiornato:

https://raw.githubusercontent.com/pcm-dpc/COVID-19/master/dati-regioni/dpc-covid19-ita-regioni-latest.csv

questo è il csv
