### ISSUE TITLE
Misspelling Forlì

### ISSUE THREAD

**Issue by nickthegeek2877** [pcm-dpc/COVID-19#664]
Tipo di issue:

- [x] Dati mancanti o errati 
- [ ] Errore nella documentazione 
- [ ] Errore or mancanza nella dashboard 
- [ ] Problemi di visualizzazione nella dashboard 

- Regione:
- Provincia: 

## Riassunto

Salve, il resoconto odierno provinciale ha un typo:  "Forl“-Cesena" nel file dati-province/dpc-covid19-ita-province-20200526.csv e di conseguenza anche in dati-province/dpc-covid19-ita-province.csv per la data di oggi 26 maggio 2020.

**Comment by umbros** [comment]
Corretto grazie!

**Comment by nickthegeek2877** [comment]
Grazie. Va corretto anche dati-province/dpc-covid19-ita-province.csv, che mi sembra ancora non lo sia.
