### ISSUE TITLE
Dove sono i dati richiesti dal dpcm 26 aprile?

### ISSUE THREAD

**Issue by Paulsword** [pcm-dpc/COVID-19#665]
@umbros Grazie per il lavoro sin qui, illuminato dalla felice intuizione originaria di condividere i dati del Ministero con il pubblico e da voi ben gestito, al netto dei pasticci delle regioni.

Ora però questi numeri, che non scorporano i nuovi veri positivi sintomatici dai tamponi di screening, e non danno informazioni immediate dei ricoveri, né delle provenienze, non bastano davvero più.

Qualche settimana fa avevate ammesso che stavate lavorando sui nuovi dati, richiesti dal dpcm 26 aprile come conditio per proseguire il monitoraggio in fase 2. Che ne è stato?

Grazie per un aggiornamento.

Per chiarimenti di dettaglio rimando tutti qui https://ilsegnalatore.info/i-numeri-nascosti-dellepidemia/

**Comment by umbros** [comment]
@Paulsword stiamo lavorando con il Ministero su questo tema aggiorno il canale tutto.
