### ISSUE TITLE
Casi provincia Barletta 28/05

### ISSUE THREAD

**Issue by anbened** [pcm-dpc/COVID-19#667]
Il dato di Barletta passa da 383 casi (27/05) a 652 casi (+269 oggi, 28/05)

E' un dato corretto?
Non vedo alcuna nota in caso di ricalcolo

Grazie, as usual

**Comment by Paulsword** [comment]
Con 2 casi in più in tutta la Puglia

**Comment by Paulsword** [comment]
Tutto chiaro, hanno scambiato Brindisi con BAT

**Comment by anbened** [comment]
... che cala di 270 casi. Hai ragione, non avevo notato
Ci sta che sia così

Attendiamo conferma dal team di @umbros :-)

**Comment by umbros** [comment]
Segnalato e corretto, grazie a tutti
