### ISSUE TITLE
Deceduti Marche

### ISSUE THREAD

**Issue by vitop72** [pcm-dpc/COVID-19#669]
I deceduti della regione marche erano ieri 997, oggi 986 con un "decremento" di -11.
E' una correzione dei dati della regione comunicato a parte o un errore?
Grazie

**Comment by Fuffo00339958** [comment]
dal sito Regione Marche:
29/05/2020CORONAVIRUS MARCHE: aggiornamento Gores delle ore 12.00
--
Il Gores ha inviato nel pomeriggio la scheda gialla con gli aggiornamenti alle 12 di oggi. Si segnala che è in corso un’attività di revisione di tutti i casi di attribuzione incerta di decesso, per cui oggi sono stati sottratti al totale 11 decessi, che da revisione non risultano classificabili come Covid-19 positivi. https://www.regione.marche.it/portals/0/Salute/CORONAVIRUS/DatiGORES/Goresgiallo29052020.pdf
