### ISSUE TITLE
Dettagli dei dati per provincia

### ISSUE THREAD

**Issue by nunziantimo** [pcm-dpc/COVID-19#67]
Sarebbero da aggiornare i dati per provincia, non solo con il numero totale ma anche deceduti/terapia intensiva/ricoverati/Isolamento domiciliare ecc

**Comment by caesarsol** [comment]
Ciao, 
ai fini di rendere più chiaro il problema ai manutentori del repo sarebbe ottima qualche informazione in più sul problema riscontrato.
Le colonne di cui parli non sono aggiornate nel senso che il dato è rimasto indietro?

**Comment by nunziantimo** [comment]
Al momento è riportato solo il totale_casi, per le varie province.

Dovrebbe essere diviso più granularmente, come i dati nazionali.

Manca di fatto la suddivisione dei casi totali, in deceduti/guariti/terapia intensiva/ricoverati/isolamento domiciliare.

**Comment by pacovi** [comment]
https://github.com/pcm-dpc/COVID-19/issues/37

**Comment by pensierinmusica** [comment]
https://github.com/pcm-dpc/COVID-19/issues/245
