### ISSUE TITLE
Duplicazione di codice per le note

### ISSUE THREAD

**Issue by estorti** [pcm-dpc/COVID-19#670]
Tipo di issue:

- Dati mancanti o errati 

- Regione: Marche
- Provincia: 

## Riassunto

Il codice dc-IT-0035 utilizzato nella nota di oggi per le Marche risulta duplicato, in quanto già assegnato il 2020-05-25 ad una nota sulla Sardegna. 
Anche il dataset sulle note EN riporta questo stesso codice.

**Attesa:**

Propongo di rinumerare le nota dc-IT-0035 come dc-IT-0036 e rinumerare la dc-IT-0036 come dc-IT-0037 (e le corrispondenti note in inglese) ed aggiornare anche il riferimento sui dataset nazionale e regionale.

**Attuale:**

**Comment by umbros** [comment]
corretto grazie @estorti
