### ISSUE TITLE
recent Venezia data are incorrect

### ISSUE THREAD

**Issue by wyesoslo** [pcm-dpc/COVID-19#672]
It is impossible for the total number of cases - which is cumulative - to go down, but 26 May shows 2657 cases, 27 May shows 2660 cases, 28 May shows (again) 2657 cases, and 29 May shows 2656 cases.

**Comment by Rabelaiss** [comment]
Usually when it happens is due to a recount

**Comment by wyesoslo** [comment]
Thanks for replying.  If what you say is the case, you probably received incorrect information for several days in a row, and may still be receiving incorrect information, since the total count has now gone down twice.  I wonder if Treviso and Venezia got interchanged on some days, starting with 26 May, or if one of them was duplicated for the other.  Starting on 23 May, here's the Venezia sequence on the left, and the Treviso sequence on the right.  Note that they both have the same number on 28 May, which of course is possible, if somewhat unlikely.
2649.  2654
2649.  2655
2652.  2655
2657.   2656
2660.  2656
2657.   2657
2656.  2657

**Comment by umbros** [comment]
Thank you
