### ISSUE TITLE
Abruzzo 30 maggio 

### ISSUE THREAD

**Issue by Cristinaluci** [pcm-dpc/COVID-19#673]
Tipo di issue:

- [ ] Dati mancanti o errati 
- [ ] Errore nella documentazione 
- [x] Errore or mancanza nella dashboard 
- [ ] Problemi di visualizzazione nella dashboard 

- Regione: Abruzzo
- Provincia: 

## Riassunto

I dati del 30 maggio Abruzzo non sono aggiornati rispetto al 29 maggio, sono gli stessi di ieri per tutti i valori?
**Attesa:**

**Attuale:**

**Comment by Cristinaluci** [comment]
I dati del 30 maggio Abruzzo non sono aggiornati rispetto al 29 maggio, sono gli stessi di ieri per tutti i valori?

**Comment by vi-enne** [comment]
Dalle [note](https://github.com/pcm-dpc/COVID-19/blob/master/note/dpc-covid19-ita-note-it.csv):


> Abruzzo:  nessun dato | non sono stati comunicati dati | aggiornamento dati non pervenuto

**Comment by Rabelaiss** [comment]
speriamo che non facciano lo stesso anche altre regioni
