### ISSUE TITLE
Genova 28 maggio

### ISSUE THREAD

**Issue by auino** [pcm-dpc/COVID-19#674]
Non mi son chiari i dati di Genova del [28 maggio](https://github.com/pcm-dpc/COVID-19/blob/master/dati-province/dpc-covid19-ita-province-20200528.csv): risultano in totale 5638 casi (+22 rispetto ai 5616 casi del [27 maggio](https://github.com/pcm-dpc/COVID-19/blob/master/dati-province/dpc-covid19-ita-province-20200527.csv)).

Tuttavia, il [28 maggio in tutta la Liguria](https://github.com/pcm-dpc/COVID-19/blob/master/dati-regioni/dpc-covid19-ita-regioni-20200528.csv) sono stati misurati 9605 casi totali, contro 9589 del [27 maggio (in Liguria)](https://github.com/pcm-dpc/COVID-19/blob/master/dati-regioni/dpc-covid19-ita-regioni-20200528.csv), dunque con un incremento di 16 casi per l'intera regione.

Come mai è presente questa asimmetria?

**Comment by vi-enne** [comment]
Se confronta le altre province liguri per gli stessi due giorni, può osservare come il totale dei casi di alcune diminuisca. Il 28 maggio si registrano 26 casi in più, ma se ne tolgono 10, per un totale di 16.

Può essere un ricalcolo, così come un errore.
