### ISSUE TITLE
All Regions all days single CSV file

### ISSUE THREAD

**Issue by tomdehavas** [pcm-dpc/COVID-19#675]
I have attached a
[ItaliaPerRegioneDiGiorno.txt](https://github.com/pcm-dpc/COVID-19/files/4707577/ItaliaPerRegioneDiGiorno.txt)

 file with data records for each region on each day generated by a screen scrape from: 

https://flo.uri.sh/story/267741/embed#slide-8 

I could not find such a single file in your data. Do you want such a file? Do you want the screen scrapper program?

I am a British resident living permanently in Liguria and have done a lot of work on forecasting for Italy with SEIR model. It can be seen here  http://www.britalian.it/en/covid19/model.html#italy you can also download the forecast spreadsheet and generate your own.

I am not familiar with the use of GitHub and so if my work is useful here then could somebody email me at tomdehavas@gmail.com and let me know if you are already publishing the file format I mentioned or if you would like my work.

**Comment by vi-enne** [comment]
Is it possible that your file is similar to [this one](https://github.com/pcm-dpc/COVID-19/blob/master/dati-regioni/dpc-covid19-ita-regioni.csv), already available in this repository?

**Comment by tomdehavas** [comment]
Thank you, yes that's it. Were the forcasting spreadsheets of any use?

**Comment by vi-enne** [comment]
Disclosure: I do not work for Protezione Civile

I looked at your page and your work seems interesting. I would suggest to compute some kind of error metrics (MSE for example) and compare it against the value for a SIR model to increase the validity of your work.

Take care!
