### ISSUE TITLE
La somma non fa il totale.

### ISSUE THREAD

**Issue by MarkusderK** [pcm-dpc/COVID-19#676]
Tipo di issue:

- [x] Dati mancanti o errati nel file dpc-covid19-ita-scheda-regioni-20200531.pdf

## Riassunto

Oggi sono indicati 

Ricoverati | Terapia Intensiva | Isolamento | Guariti | Morti | Totale

6387 | 435 | 35253 | 157507 | 33415 | 232997

Ma il totale per regione è 233019. Ritengo ci sia un errore o nei ricoverati o nei pazienti in isolamento domiciliare.

**Comment by oriana1975** [comment]
stavo per fare lo stesso commento
anche nel PDF (comuncato stampa) c'è lo stesso errore
guariti + deceduti + totale positivi = casi totali
ma oggi
157507 + 33415 + 42075 = ‭232.997‬ e non 233.019 indicato

**Comment by RossoDeM** [comment]
Anche la tabella nazionale giornaliera .csv 
Non si può lasciare così.
O è sbagliato il totale positivi, oppure una delle voci che lo compongono (dimessi e guariti o isolamenti)
se fossero gli isolamenti condizionano anche i contagi attivi.
Ballano 22

**Comment by oriana1975** [comment]
> Anche la tabella nazionale giornaliera .csv
> Non si può lasciare così.
> O è sbagliato il totale positivi, oppure una delle voci che lo compongono (dimessi e guariti o isolamenti)
> se fossero gli isolamenti condizionano anche i contagi attivi.
> Ballano 22
> Tendo a escludere i decessi. Spero

in ogni caso l'addizione non torna...
i dati dei file sono coerenti con quelli esposti, ma l'errore sta proprio nella base dati (secondo me)

**Comment by rse-299** [comment]
La somma dei positivi torna con le singole componenti. Ritengo probabile che l'errore sia o nei deceduti o nei guariti

**Comment by umbros** [comment]
Stiamo gestendo la cosa su Regione Abruzzo che è dove si è verificato il problema. A breve aggiorneremo.

**Comment by RossoDeM** [comment]
> > Anche la tabella nazionale giornaliera .csv
> > Non si può lasciare così.
> > O è sbagliato il totale positivi, oppure una delle voci che lo compongono (dimessi e guariti o isolamenti)
> > se fossero gli isolamenti condizionano anche i contagi attivi.
> > Ballano 22
> > Tendo a escludere i decessi. Spero
> 
> in ogni caso l'addizione non torna...
> i dati dei file sono coerenti con quelli esposti, ma l'errore sta proprio nella base dati (secondo me)

I conti devono sempre tornare. Non si può dire solo che c'è una discrepanza come da commento su FB da parte della P.C. per dati parziali dell'Abruzzo. I 22 vanno messi da qualche parte

**Comment by RossoDeM** [comment]
> Stiamo gestendo la cosa su Regione Abruzzo che è dove si è verificato il problema. A breve aggiorneremo.

GRAZIE Umbros (anche per il lavoraccio in genere da 24.02). Però dovete fare un nuovo comunicato stampa e rifare post su social. Mi raccomando. È importante

**Comment by umbros** [comment]
Ciao a tutti,
avevamo già prima della issue evidenziato il problema del +22 dell'Abruzzo, il dato, che su Province Abruzzo è, per totali, su 3244, non è dettagliato per Regioni, per cui, ad oggi c'è un disallineamento tra totale province abruzzo di 3244 e totale regione abruzzo 3222. La scelta è quella di tenere quanto comunicato dall'Abruzzo su province e tenere i calcoli del totale casi su 3222 su Regioni. I dati sono stati corretti sia sui dati open che sulla dashboard. Grazie a tutti per la collaborazione.

**Comment by antmas-eng** [comment]
Volevo segnalare che i dati, anche dopo l'ultimo aggiornamento, non superano il controllo che "nuovi positivi" deve essere uguale a "sommatoria (variazione totale positivi, variazione dimessi guariti, variazione deceduti). Sia sul dataset nazionale che regionale. Potete verificare? Grazie.

**Comment by miccoli** [comment]
> Ciao a tutti,
> avevamo già prima della issue evidenziato il problema del +22 dell'Abruzzo, il dato, che su Province Abruzzo è, per totali, su 3244, non è dettagliato per Regioni, per cui, ad oggi c'è un disallineamento tra totale province abruzzo di 3244 e totale regione abruzzo 3222. La scelta è quella di tenere quanto comunicato dall'Abruzzo su province e tenere i calcoli del totale casi su 3222 su Regioni. I dati sono stati corretti sia sui dati open che sulla dashboard. Grazie a tutti per la collaborazione.

@umbros accetto la scelta di DPC di pubblicare dati incongruenti. L'incongruenza dovrebbe però essere segnalata nelle note, altrimenti ogni 5 giorni qualcuno apre una issue perché è impossibile trovare questo problema leggendo solo le issue aperte.
