### ISSUE TITLE
Calcolo nuovi positivi

### ISSUE THREAD

**Issue by antmas-eng** [pcm-dpc/COVID-19#677]
Tipo di issue:

- [X] Dati mancanti o errati 
dpc-covid19-ita-andamento-nazionale.json 
dpc-covid19-ita-regioni.json

## Riassunto
Buonasera, volevo segnalare che i dati, anche dopo l'ultimo aggiornamento, non superano il controllo che "nuovi positivi" dovrebbe essere uguale a "sommatoria (variazione totale positivi, variazione dimessi guariti, variazione deceduti) (diff 22). Sia sul dataset nazionale che regionale (Abruzzo). Potete verificare? Grazie.

**Attesa:**

**Attuale:**

**Comment by DavideMagno** [comment]
+1

**Comment by vi-enne** [comment]
Confrontare #676

**Comment by umbros** [comment]
Corretto grazie! Oggi Regione Abruzzo dovrebbe risolvere i problemi sui calcoli

**Comment by umbros** [comment]
Corretto grazie! Oggi Regione Abruzzo dovrebbe risolvere i problemi sui calcoli
