### ISSUE TITLE
Nuovi casi in Italia 1 giugno, 178 o 200?

### ISSUE THREAD

**Issue by Rabelaiss** [pcm-dpc/COVID-19#678]
Nella tabella riepilogativa è segnato il valore +178, ma facendo la somma dal file dpc-covid19-ita-regioni.csv esce 200. 

Il problema riguarda la regione Abruzzo che da una parte segna 1 nuovo casa, da un altra 23 nuovi casi

**Comment by anbened** [comment]
Ciao @Rabelaiss 

Sui dati di ieri, 31 maggio, circolano due bollettini con numeri diversi (in uno i casi totali sono 232.997, nell'altro 233.019)

Credo la spiegazione sia qui:
https://twitter.com/DPCgov/status/1267158102899675136

**Comment by umbros** [comment]
Ciao @Rabelaiss il problema è risultato da una comunicazione parziale dei dati che ora è stata riallineata.

**Comment by emazep** [comment]
@umbros, il problema permane: quanti sono i nuovi positivi di oggi, **178** oppure **200**? Se sono 178, allora è sbagliato il **totale_casi** di oggi o di ieri (o entrambi), in quanto la loro differenza dà 200. Se sono 200, allora è sbagliato il valore del campo **nuovi_positivi** (che riporta 178). Se lasciati così, sarebbe la prima volta che i dati violano (perfino) la loro coerenza interna.

**Comment by RossoDeM** [comment]
> @umbros, il problema permane: quanti sono i nuovi positivi di oggi, **178** oppure **200**? Se sono 178, allora è sbagliato il **totale_casi** di oggi o di ieri (o entrambi), in quanto la loro differenza dà 200. Se sono 200, allora è sbagliato il valore del campo **nuovi_positivi** (che riporta 178). Se lasciati così, sarebbe la prima volta che i dati violano (perfino) la loro coerenza interna.
> 
> Parlo del file:
> https://github.com/pcm-dpc/COVID-19/blob/master/dati-andamento-nazionale/dpc-covid19-ita-andamento-nazionale.csv

In una issue parallela, avevo evidenziato lo stesso problema anche dopo la sia chiusura, proprio perché lasciare 178 in vece di correggerlo a 200, non solo avrebbe creato un precedente di inconsistenza nel calcolo (si era presentato anche il giorno prima per il totale positivi, poi corretto), ma anche perché l'errore si sarebbe trascinato a oggi. E infatti l'hanno corretto un'ora fa, perché evidentemente i conti non tornavano più. L'allineamento era stato fatto correttamente nella tabella regionale, rispetto al giorno prima. Ma la tabella nazionale non poteva rimanere così.
Il problema però rimane la verifica prima della pubblicazione del bollettino delle 18 (tra l'altro in mano ai media decine di minuti prima).
Il 31 maggio erano stati comunicati +355 nuovi positivi invece dei corretti +333 (comunicati solo in serata modificando il post). Ieri +178 invece di +200. Il saldo dei due giorni è lo stesso, ma cambia parecchio a livello di informazione al pubblico.
