### ISSUE TITLE
Le tabelle dovrebbero essere coerenti all'interno della repo

### ISSUE THREAD

**Issue by vi-enne** [pcm-dpc/COVID-19#679]
Tipo di issue:

- [x] Dati mancanti o errati 
- [ ] Errore nella documentazione 
- [ ] Errore or mancanza nella dashboard 
- [ ] Problemi di visualizzazione nella dashboard 

- Regione: Abruzzo
- Provincia: 

## Riassunto
Le tabelle dovrebbero essere consistenti all'interno della repo.
Mi riferisco al caso dell'Abruzzo degli ultimi giorni e alle tabelle del [20200531](https://github.com/pcm-dpc/COVID-19/blob/master/dati-regioni/dpc-covid19-ita-regioni-20200531.csv) e del [20200601](https://github.com/pcm-dpc/COVID-19/blob/master/dati-regioni/dpc-covid19-ita-regioni-20200601.csv).
Ho compreso la situazione e il ricalcolo, ma le tabelle in questa repo dovrebbero essere consistenti tra di loro:

1. O ieri si registrano -15 nuovi positivi (7 nuovi - 22 eliminati) e oggi 23 (1 nuovo + 22 reintegrati)
2. O ieri si registrano 7 nuovi positivi e oggi 1 nuovo positivo

Avere una tabella di ieri con -15 e una di oggi con +1 non e' consistente e danneggia molti sistemi che si basano sui dati di questa repo per le loro analisi.

Grazie,
Vittorio

**Attesa:**
Tabelle di riepilogo consistenti.

**Attuale:** 
Dati Abruzzo 20200531 e 20200601

**Comment by miccoli** [comment]
Ho notato anche io una inconsistenza nei dati dell'Abruzzo per il 2020-05-31

In particolare nel file `dpc-covid19-ita-regioni-20200531.csv` abbiamo
`totale_casi = 3222` ma facendo la somma dei casi provinciali in `dpc-covid19-ita-province-20200531.csv` risultano `822 + 246 + 1522 + 654 = 3244`

Probabilmente c'è un errore di trascrizione dei dati da qualche parte.

**Comment by vi-enne** [comment]
> Ho notato anche io una inconsistenza nei dati dell'Abruzzo per il 2020-05-31
> 
> In particolare nel file `dpc-covid19-ita-regioni-20200531.csv` abbiamo
> `totale_casi = 3222` ma facendo la somma dei casi provinciali in `dpc-covid19-ita-province-20200531.csv` risultano `822 + 246 + 1522 + 654 = 3244`
> 
> Probabilmente c'è un errore di trascrizione dei dati da qualche parte.

Può confrontare #676, #677, #678. 

Si e' cercato di risolvere il problema al meglio dei dati disponibili, ma si e' mancato di coerenza interna.

**Comment by miccoli** [comment]
@umbros ma non sarebbe meglio a questo punto mettere

| data | totale_casi | nuovi_positivi |
|-----|------------|-------------|
| 2020-05-30 | 3237 | 0 |
| 2020-05-31 | 3244 |  7 |
| 2020-06-01 | 3245 | 1 |

che torna tutto, anche con i dati provinciali??

**Comment by umbros** [comment]
Ciao, 
c'è stato un errore di comunicazione dei dati e domani saranno bonificati i dati del 31 in modo che i dati saranno coerenti.

**Comment by vi-enne** [comment]
Grazie @umbros 

Consiglio di tenere almeno una issue aperta, altrimenti entro domani ne verranno create altre,
