### ISSUE TITLE
Casi di oggi 178 o 200?

### ISSUE THREAD

**Issue by vitop72** [pcm-dpc/COVID-19#680]
Nella [scheda riepilogo](https://github.com/pcm-dpc/COVID-19/blob/master/schede-riepilogative/regioni/dpc-covid19-ita-scheda-regioni-20200601.pdf) di oggi si rilevano **+178 casi**.

Dalla variazione dei [dati regionali di oggi](https://github.com/pcm-dpc/COVID-19/blob/master/dati-regioni/dpc-covid19-ita-regioni.csv) rispetto a quelli di ieri se ne rilevano **+200**.

**Comment by vi-enne** [comment]
Vedi #678 
Sulla mancata coerenza, vedi #679

**Comment by vitop72** [comment]
> Vedi #678

Cosa sarebbe stato riallineato? La scherda regioni o i dati csv?

> Sulla mancata coerenza, vedi #679

Non è mica chiara la risposta definitiva in merito.

**Comment by RossoDeM** [comment]
Dovrebbero essere +200 visto che i dati di ieri erano stati corretti. +178 è la differenza rispetto al primo dato pubblicato di positivi totali nazionali. Andrebbe corretto a +200. Oppure va ripristinato il dato di ieri precedente.

233197 - 232997 = 200

**Comment by vi-enne** [comment]
> > Vedi #678
> 
> Cosa sarebbe stato riallineato? La scheda regioni o i dati csv?
> 
> > Sulla mancata coerenza, vedi #679
> 
> Non è mica chiara la risposta definitiva in merito.

Sono stati riallineati sia la scheda regione che i dati csv.

Sono d'accordo che la questione e' ancora aperta, ho indicato le issues precedenti per fornirle informazioni in merito già disponibili.

**Comment by vitop72** [comment]
> > > Vedi #678
> > 
> > 
> > Cosa sarebbe stato riallineato? La scheda regioni o i dati csv?
> > > Sulla mancata coerenza, vedi #679
> > 
> > 
> > Non è mica chiara la risposta definitiva in merito.
> 
> Sono stati riallineati sia la scheda regione che i dati csv.
> 
> Sono d'accordo che la questione e' ancora aperta, ho indicato le issues precedenti per fornirle informazioni in merito già disponibili.

Grazie. Certo che su numeri ormai così piccoli rilevare queste anomalie è frustante..

**Comment by Simonepu** [comment]
Nell’andamento nazionale c’è comunque qualcosa che non va.
Nuovi positivi 178 – (158.355 - 157.507) – (33.475 - 33.415) = - 730 (variazione totale positivi), c’è una differenza di 22 (che coincide con quella di ieri) che da qualche parte sarà …

**Comment by RossoDeM** [comment]
> Nell’andamento nazionale c’è comunque qualcosa che non va.
> Nuovi positivi 178 – (158.355 - 157.507) – (33.475 - 33.415) = - 730 (variazione totale positivi), c’è una differenza di 22 (che coincide con quella di ieri) che da qualche parte sarà …

Sì, tutti i dati sono corretti tranne i nuovi positivi, che sono 200 invece di 178. Ieri erano stati corretti da 355 a 333. E così sono rimasti. 200 + 333 = 178 + 355.
Se ieri erano stati corretti a 333 non possono essere oggi 178.

1 dato di ieri 233019 +355
2 dato corretto 232997 +333
3 dato odierno 233197 +200 (non +178)

**Comment by RossoDeM** [comment]
Nella tabella nazionale la somma di tutti i dati parziali dà correttamente il numero totale di positivi. Il problema è solo nella variazione giornaliera, che è stata calcolata sul primo dato pubblicato ieri (non quello poi corretto). Sono sempre quei 22. Se ieri erano stati tolti (da 355 a 333), oggi vanno aggiunti nella variazione (da 178 a 200). Sempre che i parziali siano giusti.

**Comment by umbros** [comment]
ok il dato di oggi che disegna l'attuale situazione, domani verrà allineato il dato abruzzo del 31/05.

**Comment by vitop72** [comment]
> ok il dato di oggi che disegna l'attuale situazione, domani verrà allineato il dato abruzzo del 31/05.

umbros però si può avere un breve riepilogo per capire:

casi di ieri ITA
casi di oggi ITA
casi di ieri ABRUZZO
casi di oggi ABRUZZO

Grazie

**Comment by RossoDeM** [comment]
> ok il dato di oggi che disegna l'attuale situazione, domani verrà allineato il dato abruzzo del 31/05.

Non vorrei insistere, ma secondo me così vi portate dietro l'errore anche a domani in merito ai nuovi positivi. La tabella Abruzzo secondo me è corretta a oggi, perché ieri lasciando il disallineamento comunque era come se i cosiddetti "in fase di aggiornamento" fossero -22 invece di 0. Oggi coincidendo somma province con contagi totali il TBA torna a 0.
Invece su nazionale tutti i dati sono corretti tranne i nuovi contagi (basta correggere 178 con 200).
Non vorrei che domani siamo punto e capo
