### ISSUE TITLE
Andamento nazionale 2020-06-01 non coerente

### ISSUE THREAD

**Issue by vi-enne** [pcm-dpc/COVID-19#682]
Tipo di issue:

- [x] Dati mancanti o errati 
- [ ] Errore nella documentazione 
- [ ] Errore or mancanza nella dashboard 
- [ ] Problemi di visualizzazione nella dashboard 

- Regione:
- Provincia: 

## Riassunto
I dati dell'[andamento nazionale 2020-06-01](https://github.com/pcm-dpc/COVID-19/blob/master/dati-andamento-nazionale/dpc-covid19-ita-andamento-nazionale-20200601.csv) sono ancora non coerenti.
Il file dovrebbe riportare "nuovi_positivi = 178" e non "nuovi_positivi = 200" per essere coerente con gli altri file della repo, in particolare con il file [andamento nazionale 2020-05-31](https://github.com/pcm-dpc/COVID-19/blob/master/dati-andamento-nazionale/dpc-covid19-ita-andamento-nazionale-20200531.csv) che riporta "nuovi_positivi = 355".

**Attesa:**
2020-06-01
"nuovi_positivi = 178"

**Attuale:** 
2020-06-01
"nuovi_positivi = 200"

**Comment by umbros** [comment]
Ciao refuso in fase di correzione dati. Grazie @vi-enne
