### ISSUE TITLE
Dati difformi da quelli pubblicati dalla Regione Siciliana

### ISSUE THREAD

**Issue by picomiles** [pcm-dpc/COVID-19#683]
Tipo di issue:

- [x] Dati mancanti o errati https://github.com/pcm-dpc/COVID-19/blob/master/dati-regioni/dpc-covid19-ita-regioni-20200602.csv
- [ ] Errore nella documentazione 
- [ ] Errore or mancanza nella dashboard 
- [ ] Problemi di visualizzazione nella dashboard 

- Regione: Sicilia
- Provincia: 

## Riassunto

I dati del 2 Giugno sono difformi da quelli pubblicati dalla Regione; in particolare il dato da voi riportato nel campo isolamento_domiciliare = 897 invece di 893 (come riportato dalla Regione), di conseguenza risultano influenzati anche i campi totale_positivi = 966 (invece di 962 come riportato dalla Regione), il campo variazione_totale_positivi = -1 (invece di -5), dimessi_guariti = 2206 (invece di 2210) 
**Attesa:**

Sapere quali siano i dati corretti
![immagine](https://user-images.githubusercontent.com/13104/83563469-768eee00-a51b-11ea-9708-972855c152db.png)

**Comment by umbros** [comment]
Ciao i dati pubblicati sono comunicati dalla stessa Regione.
