### ISSUE TITLE
Riepilogo - nome virus sbagliato

### ISSUE THREAD

**Issue by eutampieri** [pcm-dpc/COVID-19#684]
Tipo di issue:

- [x] Dati mancanti o errati 
- [ ] Errore nella documentazione 
- [ ] Errore or mancanza nella dashboard 
- [ ] Problemi di visualizzazione nella dashboard 

- Regione: N.A
- Provincia: N.A

## Riassunto

Nei documenti riepilogativi è presente una cella contenente la didascalia "POSITIVI AL nCov"

**Attesa:**

la cella dovrebbe essere denominata "POSITIVI AL SARS-CoV-2", seguendo quindi la denominazione ufficiale del virus e non quella provvisoria (https://en.wikipedia.org/wiki/Novel_coronavirus?wprov=sfti1 e più nello specifico https://en.wikipedia.org/wiki/Severe_acute_respiratory_syndrome_coronavirus_2?wprov=sfti1)

> Severe acute respiratory syndrome coronavirus 2 (SARS-CoV-2) is the strain of coronavirus that causes coronavirus disease 2019 (COVID-19), a respiratory illness. Colloquially known as simply the coronavirus, it was previously referred to by its provisional name, 2019 novel coronavirus (2019-nCoV),

**Attuale:** 
La cella usa la denominazione provvisoria.

**Comment by umbros** [comment]
Ciao,
dove hai trovato la stringa errata?

**Comment by eutampieri** [comment]
@umbros nella cella unita delle schede riepilogativa, sopra le celle gialle
https://github.com/pcm-dpc/COVID-19/blob/master/schede-riepilogative/regioni/dpc-covid19-ita-scheda-regioni-20200513.pdf

**Comment by umbros** [comment]
La scheda è in fase di revisione e riporterà l'esatta dicitura, grazie per la segnalazione @eutampieri
