### ISSUE TITLE
Errore nel formato delle note italiane csv in data odierna

### ISSUE THREAD

**Issue by DarkFighterLuke** [pcm-dpc/COVID-19#685]
`We can make this file beautiful and searchable if this error is corrected: It looks like row 78 should actually have 12 columns, instead of 11. in line 77.`

File di riferimento: https://raw.githubusercontent.com/pcm-dpc/COVID-19/master/note/dpc-covid19-ita-note-it.csv

@umbros

**Comment by DarkFighterLuke** [comment]
Insomma, non posso usufruire ancora dei dati perchè l'errore persiste...

**Comment by umbros** [comment]
Corretto @DarkFighterLuke grazie della segnalazione
