### ISSUE TITLE
Dati Campania errati per il giorno 6/6/2020

### ISSUE THREAD

**Issue by ppatierno** [pcm-dpc/COVID-19#686]
Tipo di issue:

- [x] Dati mancanti o errati 
- [ ] Errore nella documentazione 
- [ ] Errore or mancanza nella dashboard 
- [ ] Problemi di visualizzazione nella dashboard 

- Regione: Campania
- Provincia: 

## Riassunto

Come riportato sul sito ufficiale della regione Campania [qui](http://www.regione.campania.it/imprese/it/news/primo-piano/covid-19-aggiornamento-u726) i nuovi positivi in data 6/6/2020 sono 4 e non 0.
Anche gli altri valori come complessivo positivi e complessivo tamponi sono errati.
Sembra che nei dati del repository siano assenti tali dati, comunicati in ritardo dalla regione Campania?

**Attesa:**

Totali positivi Campania pari a 4, totale complessivo positivi 4826, totale complessivo tampni 217898 in data 6/6/2020.

**Attuale:**

Totali positivi Campania pari a 0, totale complessivo positivi 4822, totale complessivo tamponi 215404 (mancano i 2494 tamponi eseguiti) in data 6/6/2020.

**Comment by vi-enne** [comment]
L'aggiornamento linkato è delle 22 del 6/6, quindi dopo la comunicazione alla Protezione Civile.

Immagino verranno riportati nelle tabelle del 7/6.

**Comment by ppatierno** [comment]
Si è vero, ma così si rischia di "falsare" in qualche modo l'andamento giornaliero. Non sarebbe meglio aggiornare i dati del 6/6?

**Comment by vi-enne** [comment]
> Si è vero, ma così si rischia di "falsare" in qualche modo l'andamento giornaliero. Non sarebbe meglio aggiornare i dati del 6/6?

Non sono d'accordo, i dati sono sempre aggiornati alle 17 e diffusi alle 18. Modificando adesso il metodo si rischia di non essere coerenti con i i dati precedenti.

Può vedere le comunicazioni della PC come una fotografia della situazione come comunicata dalle regioni alle 17 di tutti i giorni.

**Comment by ppatierno** [comment]
Sicuramente è una foto di come "vengono comunicati" i dati ma è una foto "sbagliata" del giorno perchè i 4 positivi sono stati rilevati il 6/6 e non il 7/6. Si dirà che la Campania ha avuto 0 positivi per 2 giorni consecutivi (il 5/6 ed il 6/6) ma in realtà non è così.

**Comment by vi-enne** [comment]
> Sicuramente è una foto di come "vengono comunicati" i dati ma è una foto "sbagliata" del giorno perchè i 4 positivi sono stati rilevati il 6/6 e non il 7/6. Si dirà che la Campania ha avuto 0 positivi per 2 giorni consecutivi (il 5/6 ed il 6/6) ma in realtà non è così.

Questo è un errore di come vengono interpretati i dati e non una issue della repository. 

La PC riporta correttamente che entro le 17 del 6/6 la Campania ha comunicato 0 nuovi casi.
La prego di notare come nei file della PC vengano indicato data e ora.

**Comment by ppatierno** [comment]
Capisco ma a questo punto penso che la PC debba fare le comunicazioni con un giorno di ritardo ed utrilizzare i dati reali. Comunicare quindi il 7/6, cosa è accaduto il 6/6.
Riportare i dati in questo modo comporta errate comunicazioni delle testate online (vedi La Repubblica che indicava 0 casi positivi in Campania alle ore 18 sulla base di questi dati comunicati) e quindi una errata percezione delle persone. Ieri, tutti "felici" agli 0 contagi in Campania, oggi i nuovi positivi saranno "falsati" da un +4 di ieri.
Sinceramente avrebbe più senso rimandare ogni annuncio con un giorno di ritardo se le regioni hanno i dati ufficiali così tardi (vedi la Campania alle ore 22).
Capisco che questo è stato il modus operandi in questi mesi quindi chiudo la issue, nonostante non condivida.

**Comment by umbros** [comment]
Noi, definendo anche l'ora di comunicazione congeliamo il dato a quell'ora e i dati sono comunicati dalle Regioni stesse.
