### ISSUE TITLE
Region totals don't agree with province totals

### ISSUE THREAD

**Issue by Jmuccigr** [pcm-dpc/COVID-19#687]
Type of issue:

- [ x] Incorrect or missing data : 
- [ ] Incorrect or missing documentation 
- [ ] Incorrect or missing data in the dashboard 
- [ ] Layout problem in the dashboard 

- Region: Campania, Lazio, Lombardia
- Province: 

## Summary

For 7/6, the regional totals of nuovi_positivi do not agree with the provincial totals for the same provinces (listed above).

For example, Lazio has 11 nuovi_positivi in the regional data file, but Rome is at 17 and all the other provinces are 0 in the provincial data file.

**Expected:**

Sum of provincial data equals total provided in regional data.
**Actual:** 
Sum of provincial data does not equal total provided in regional data.

**Comment by pierluigicara** [comment]
Everything is ok: yesterday Lazio was 7801 today 7812 with Rome +17 but "altro/in fase di verifica" is -6 so the difference +11 is correct.

**Comment by Jmuccigr** [comment]
Non capisco. 

6 dei 17 nuovi casi a Roma sono anche nel gruppo “altro”. Allora, quali sono, positivi o da verificare? Mi sembrano due categorie diverse. 

Vuol dire che i casi “altro” sono sempre già  in altri campi?

**Comment by pierluigicara** [comment]
Esatto, il campo "altro" comprende casi ancora non attribuiti ad una provincia, ma che concorrono al conteggio del numero di casi totali della regione (che li ricomprende).

**Comment by Jmuccigr** [comment]
Grazie per la spiegazione.

Quindi vuol dire che, per esempio, il 7 giugno, 6 casi erano presi da "altro" e dati a "Roma"? Cioè, 6 dei 17 casi a Roma non erano nuovi, ma nuovamente assegnati alla provincia? In tal caso le differenze giornalieri in "totale_casi" per le province non sono composte completamente da casi nuovi.
