### ISSUE TITLE
aggiungere numero verde

### ISSUE THREAD

**Issue by pigreco** [pcm-dpc/COVID-19#69]
Ottimo lavoro fin qui fatto, complimenti.

Perché non aggiungere il [numero verde](http://www.salute.gov.it/portale/nuovocoronavirus/dettaglioContenutiNuovoCoronavirus.jsp?lingua=italiano&id=5364&area=nuovoCoronavirus&menu=vuoto) per ogni `Regione`??
magari da visualizzare nella webMap:
![image](https://user-images.githubusercontent.com/7631137/76205255-280ed380-61fa-11ea-8ffd-cd01519d4321.png)

allego gist:

https://gist.github.com/pigreco/48b49add3b62e1c590abc78e5a64ef15

**Comment by umbros** [comment]
Grazie @pigreco , ottimo suggerimento.

Metto la cosa in enhancement.

**Comment by umbros** [comment]
Ciao, per una questione di gestione dell'informazione, l'informazione non verrà gestita nel repository.
Grazie @pigreco
