### ISSUE TITLE
Casi Campania 12/06/2020

### ISSUE THREAD

**Issue by vitop72** [pcm-dpc/COVID-19#692]
Il casi campania di oggi sembrano essere -229.
Cosa vuol dire??

**Comment by Rabelaiss** [comment]
leggi qua http://www.protezionecivile.gov.it/media-comunicazione/comunicati-stampa/-/content-view/view/1286455
comunque se c'è già aperto un issue sullo stesso argomento meglio se commenti là invece di aprire una nuova ;)

**Comment by vitop72** [comment]
> comunque se c'è già aperto un issue sullo stesso argomento meglio se commenti là invece di aprire una nuova ;)

Nel momento in cui ho aperto l'issue non ce n'era nessuna sul tema già aperta.

**Comment by umbros** [comment]
#691
