### ISSUE TITLE
Dati Campania 12/6/20 non coincidenti tra CSV e JSON

### ISSUE THREAD

**Issue by scapodicasa** [pcm-dpc/COVID-19#693]
Tipo di issue:

- [X] Dati mancanti o errati  dati-regioni/dpc-covid19-ita-regioni-latest.csv,  dati-json/dpc-covid19-ita-andamento-nazionale-latest.json
- [ ] Errore nella documentazione 
- [ ] Errore or mancanza nella dashboard 
- [ ] Problemi di visualizzazione nella dashboard 

- Regione: Campania
- Provincia: N/A

## Riassunto

I dati non corrispondono tra i due formati

**Comment by umbros** [comment]
aggiornati, grazie @scapodicasa
