### ISSUE TITLE
Nuovi positivi nazionali e Lombardia incompatibili.

### ISSUE THREAD

**Issue by emazep** [pcm-dpc/COVID-19#694]
Oggi si hanno **163** nuovi positivi nel riepilogo nazionale:
https://github.com/pcm-dpc/COVID-19/blob/master/dati-andamento-nazionale/dpc-covid19-ita-andamento-nazionale.csv

e **272** nella sola Lombardia:
https://github.com/pcm-dpc/COVID-19/blob/master/dati-regioni/dpc-covid19-ita-regioni.csv

Dovuto probabilmente ai **-229** nuovi positivi della Campania.

**Comment by umbros** [comment]
Confermo che tale calcolo è dovuto dal ricalcolo di Regione Campania (-230 positivi), grazie comunque della segnalazione @emazep

**Comment by emazep** [comment]
Grazie per la conferma, ma verrà corretto (oggi) o ce lo teniamo così? :-)
