### ISSUE TITLE
Inconsistenza nei dati del 12 giugno?

### ISSUE THREAD

**Issue by Doc73** [pcm-dpc/COVID-19#695]
Tipo di issue:

- [X] Dati mancanti o errati: [https://github.com/pcm-dpc/COVID-19/blob/master/dati-andamento-nazionale/dpc-covid19-ita-andamento-nazionale-latest.csv](https://github.com/pcm-dpc/COVID-19/blob/master/dati-andamento-nazionale/dpc-covid19-ita-andamento-nazionale-latest.csv)
- [ ] Errore nella documentazione 
- [ ] Errore or mancanza nella dashboard 
- [ ] Problemi di visualizzazione nella dashboard 

- Regione: Lombardia
- Provincia: 

## Riassunto
Gentilissimi signori,
dalla tabella relativa all'andamento nazionale del 12 giugno, risulta che i `nuovi_positivi` in Italia sarebbero 163, ma la corrispondente tabella delle regioni, indica un totale di  `nuovi_positivi` della sola Lombardia di 272 (cf. [https://github.com/pcm-dpc/COVID-19/blob/master/dati-regioni/dpc-covid19-ita-regioni-latest.csv](https://github.com/pcm-dpc/COVID-19/blob/master/dati-regioni/dpc-covid19-ita-regioni-latest.csv))

Come è possibile? Mi sbaglio io?

Cordiali saluti,
Domenico Cufalo

**Comment by umbros** [comment]
@Doc73 veda la issue #692 c'è stato un riconteggio su Campania e Bolzano
