### ISSUE TITLE
Nuovi positivi negativi oggi in Campania

### ISSUE THREAD

**Issue by lucalista** [pcm-dpc/COVID-19#697]
Tipo di issue:

- [x] Dati mancanti o errati 
- [ ] Errore nella documentazione 
- [ ] Errore or mancanza nella dashboard 
- [ ] Problemi di visualizzazione nella dashboard 

- Regione: Campania
- Provincia: -

## Riassunto
Oggi il numero di nuovi_positivi in Campania è negativo, -229.
Immagino che sia un errore.

**Attesa:**
Un numero > 0

**Attuale:**
-229

**Comment by RossoDeM** [comment]
> Tipo di issue:
> 
> * [x]  Dati mancanti o errati
> * [ ]  Errore nella documentazione
> * [ ]  Errore or mancanza nella dashboard
> * [ ]  Problemi di visualizzazione nella dashboard
> * Regione: Campania
> * Provincia: -
> 
> ## Riassunto
> Oggi il numero di nuovi_positivi in Campania è negativo, -229.
> Immagino che sia un errore.
> 
> **Attesa:**
> Un numero > 0
> 
> **Attuale:**
> -229

È un ricalcolo specificato nelle note. In realtà pare siano 230. Sono falsi positivi sfornati dalla regione. Tant'è che incidono sul nazionale che avrebbe 163 nuovi positivi con 272 in Lombardia. Erano state aperte e poi chiuse altre issues in merito.

**Comment by RossoDeM** [comment]
Comunque faccio presente a Umbros che questa cosa di dover aspettare decine di minuti l'aggiornamento del repository quando ormai le veline ai media sono state inviate in anticipo ben prima del bollettino (i post pubblici della PC sui social non riportano le note e il comunicato ufficiale non lo cliccano e leggono tutti), diventa un po' imbarazzante. Vedi casi Abruzzo.
Sarebbe il caso di anticipare il repository per tutte le verifiche incrociate e risolvere le issues anche grazie al contributo qui degli utenti, che insieme a Umbros sono quelli che davvero si sbattono.

**Comment by umbros** [comment]
ciao @RossoDeM, 
le verifiche vengono effettuate, i casi che tu riporti partono da comunicazioni delle Regioni stesse, essendoci dei tempi di pubblicazione fissi ci possono essere errori che puntiamo sempre a risolvere. In questi giorni stiamo lavorando per la digitalizzazione del processo che porterà ad un miglioramento dei flussi.
