### ISSUE TITLE
Errore numero nuovi contagiati in Lombardia del 12/6/2020

### ISSUE THREAD

**Issue by pasmer** [pcm-dpc/COVID-19#698]
Tipo di issue:

- [x] Dati mancanti o errati 
- [ ] Errore nella documentazione 
- [ ] Errore or mancanza nella dashboard 
- [ ] Problemi di visualizzazione nella dashboard 

- Regione:
- Provincia: 

## Riassunto

**Attesa:**

**Attuale:**

**Comment by 123cobloc** [comment]
Il numero è uguale a quello riportato dalla regione ([https://www.lombardianotizie.online/coronavirus-casi-lombardia/])
