### ISSUE TITLE
Numero esorbitante dimessi_guariti Lazio

### ISSUE THREAD

**Issue by emazep** [pcm-dpc/COVID-19#699]
Oggi il Lazio riporta un delta giornaliero di dimessi guariti pari a **865** (e ieri ne aveva riportati **317**), dopo che negli ultimi 15 giorni tale valore era in media intorno alle **50** unità. Un numero così abnorme fa pensare ad un conguaglio, ma non ve n'è traccia negli avvisi.

**Comment by umbros** [comment]
Ciao @emazep sono i dati comunicati dalla stessa regione Lazio che ha notificato solo il riconteggio dei deceduti.
