### ISSUE TITLE
Numero di deceduti

### ISSUE THREAD

**Issue by Barbabosco** [pcm-dpc/COVID-19#7]
Grazie innanzitutto per questo prezioso lavoro. È possibile inserire anche i numeri relativi ai decessi? 
Grazie, un saluto,
Andrea Magnabosco

**Comment by umbros** [comment]
Ciao @Barbabosco allo stato attuale i deceduti vengono gestiti per totale per Regione.

**Comment by Barbabosco** [comment]
Grazie della risposta velocissima, gentilissimo.
Visti i numeri purtroppo in crescita, penso sarebbe un'informazione utile.
Buon lavoro!
