### ISSUE TITLE
Numero posti letto

### ISSUE THREAD

**Issue by olistik** [pcm-dpc/COVID-19#70]
**Tipo di richiesta**: suggerimento di miglioramento

## Riassunto

Sarebbe utile tenere traccia della disponibilità dei posti letto (totali/in uso), se possibile a livello di singolo istituto ospedaliero o aggregato a livello provinciale e regionale.

## Interesse pubblico

È uno degli indici da più il senso della gravità nel caso di saturazione della capacità di accoglienza del SSN.

[Questo dataset](https://t.co/tUDULPCfGi?amp=1) è stato aggiornato solo 2 mesi fa. Non so se è possibile ottenere dei dati più aggiornati.

**Comment by piersoft** [comment]
@olistik è anche vero però che stanno variando dinamicamente i posti perchè stanno attrezzando ulteriori posti e sale oltre a spostare i pazienti grazi in altri ospedali.

**Comment by olistik** [comment]
> @olistik è anche vero però che stanno variando dinamicamente i posti perchè stanno attrezzando ulteriori posti e sale oltre a spostare i pazienti grazi in altri ospedali.

@piersoft è un dato dinamico, è vero.
Sembra che da tale caratteristica tu abbia tratto qualche conclusione. È così?

**Comment by umbros** [comment]
@olistik ti ringrazio, attualmente la gestione dei posti letto, terapia intensiva... e segue altri processi come l'utilizzo della CROSS:
https://www.facebook.com/plugins/post.php?href=https%3A%2F%2Fwww.facebook.com%2FDPCgov%2Fposts%2F680817136035521&width=500

Comunque ogni nuovo dataset disponibile sarà comunicato in CHANGELOG
