### ISSUE TITLE
Vedremo mai il resto dei dati?

### ISSUE THREAD

**Issue by Paulsword** [pcm-dpc/COVID-19#700]
Lo so, l'ho chiesto altre volte, e mi è sempre stato risposto, con cortesia, che ci si stava lavorando.
Abbiamo qualche chance di vedere aggiunti al dataset i numeri dei casi sintomatici, distinti dagli screening? O, per dirla con altre parole, l'indicazione della data di insorgenza dei sintomi?

Qui spiego meglio: https://ilsegnalatore.info/quel-che-ancora-ci-manca/

Grazie sempre.

**Comment by umbros** [comment]
Ciao @Paulsword,
i dati che vengono presi dalle Regioni da Ministero della Salute e ISS sono erogati e resi pubblici, per quanto riguarda i dati di competenza e necessità per il Dipartimento della Protezione Civile li eroghiamo anche in opendata. In questo momento si sta perfezionando il processo di erogazione del dato, eventuali altri opendata saranno comunicati da chi li produrrà.
