### ISSUE TITLE
Segnalo un piccolo errore: la differenza fra il totale casi di oggi e il totale casi di ieri (301) non corrisponde al numero dei nuovi positivi (303)

### ISSUE THREAD

**Issue by Simonepu** [pcm-dpc/COVID-19#702]
Tipo di issue:

- [ ] Dati mancanti o errati 
- [ ] Errore nella documentazione 
- [ ] Errore or mancanza nella dashboard 
- [ ] Problemi di visualizzazione nella dashboard 

- Regione:
- Provincia: 

## Riassunto

**Attesa:**

**Attuale:**

**Comment by umbros** [comment]
E' stato notificato il dato del ricalcolo dei dati di PA Bolzano
