### ISSUE TITLE
Incongruenza dati P.A. Bolzano dopo ricalcolo totale_positivi del 2020-06-15

### ISSUE THREAD

**Issue by miccoli** [pcm-dpc/COVID-19#703]
Tipo di issue:

- [X] Dati mancanti o errati 
- [ ] Errore nella documentazione 
- [ ] Errore or mancanza nella dashboard 
- [ ] Problemi di visualizzazione nella dashboard 

- Regione: P.A. Bolzano
- Provincia: 

## Riassunto

la colonna `nuovi_positivi` al tempo `T` rappresenta sempre la differenza tra `totale_positivi` al tempo `T` e `T-1`. In caso di riconteggi il valore di `nuovi_positivi` può anche essere negativo. (Vedi per esempio la Campania il [2020-06-12](https://github.com/pcm-dpc/COVID-19/blob/0eb81a0c71e980afd85437184be8b63a9e3e7359/dati-regioni/dpc-covid19-ita-regioni-20200612.csv))

Per questo motivo mi aspetto che `nuovi_positivi` sia -1  (e non 0) per P.A. Bolzano in seguito al riconteggio del 2020-06-15, vedi [dati-regioni/dpc-covid19-ita-regioni-20200615.csv](https://github.com/pcm-dpc/COVID-19/blob/2e41d15cbc0dce3113b7f3274f3b2479b5d2487b/dati-regioni/dpc-covid19-ita-regioni-20200615.csv)

**Attesa:**

**Attuale:**

**Comment by umbros** [comment]
Proprio per evitare il problema Campania è stato deciso di mettere a 0 il dato nuovi positivi di PA Bolzano.

**Comment by miccoli** [comment]
@umbros: non potete cambiare definizione delle variabili ogni giorno! Se fino ad oggi avete seguito la definizione di `nuovi_positivi` "esatta" non è possibile che senza nessun avviso da un momento all'altro la definizione diventi `max(0, totale_positivi(d) - totale_positivi(d-1)`.

**Comment by miccoli** [comment]
La decisione di correggere *saltuariamente* il valore `nuovi_positivi` per evitare valori negativi ha tanti effetti negativi: per esempio la somma cumulativa di `nuovi_positivi` non è più uguale al valore `totale_casi`. Inoltre non si capisce perché iniziare arbitrariamente da questa data, mentre in passato si è mantenuto rigorosamente la definizione

```
nuovi_positivi = (totale_casi giorno corrente - totale_casi giorno precedente)
```

Mi sembra che la chiusura di questa issue sia definitiva. Non contesto la decisione, ma per favore deve essere aggiornata la definizione di `nuovi_positivi`, che allo stato attuale non è corretta.
