### ISSUE TITLE
Tamponi Campania del 17/06

### ISSUE THREAD

**Issue by vitop72** [pcm-dpc/COVID-19#704]
E' corretto il numero di tamponi comunicati da Regione Campania?
Risultano essere (per differenza tra ieri e oggi) oltre 15mila, dato mai realizzato dalla regione in un solo giorno.

**Comment by Rabelaiss** [comment]
dalla pagina facebook della campania

> Il dato include anche i 12.862 tamponi dello screening su commissioni d'esame e personale scolastico (con 0 positivi).
