### ISSUE TITLE
Nuovi positivi ieri e oggi non corrispondono ai calcoli

### ISSUE THREAD

**Issue by RossoDeM** [pcm-dpc/COVID-19#705]
Tipo di issue:

- [X] Dati mancanti o errati 
- [ ] Errore nella documentazione 
- [ ] Errore or mancanza nella dashboard 
- [ ] Problemi di visualizzazione nella dashboard 

- Regione:
- Provincia: 

## Riassunto

Nel csv del riepilogo andamento nazionale, i nuovi positivi di ieri (modificati) e oggi non collimano col risultato del calcolo dei parziali. Pur avendo letto la nota in merito all'Abruzzo, non basta cambiare solo il singolo dato. I calcoli devono sempre tornare. Oggi dà +331, perché il totale di ieri non è stato modificato (solo appunto i nuovi positivi). E non mi sembra che sia stata corretta la tabella di aprile. 
Attendo verifica

**Attesa:**

**Attuale:**

**Comment by umbros** [comment]
@RossoDeM vedi nota, Regione Abruzzo ricalcolo -2 positivi

**Comment by RossoDeM** [comment]
> @RossoDeM vedi nota, Regione Abruzzo ricalcolo -2 positivi

Come specificato ho letto la nota che da riferimento a 14/06 e aprile. Dico solo che avete modificato i nuovi positivi di ieri senza correggere i parziali (e il totale), oggi se calcolare tutti i parziali il conto nuovi positivi non torna.

**Comment by RossoDeM** [comment]
Mi permetto di insistere perché:
16.06 Tot. 237500 +210 (invariato)
17.06 Tot. 237828 +328 (cambiato in +329)
18.06 Tot. 238159 +331 (invece riporta 333)

Qualcosa non va, se i totali non sono stati corretti. E comunque se si correggono vale anche per i parziali che li compongono
I conti devono sempre tornare, secondo me
Grazie ancora

**Comment by vi-enne** [comment]
> Mi permetto di insistere perché:
> 16.06 Tot. 237500 +210 (invariato)
> 17.06 Tot. 237828 +328 (cambiato in +329)
> 18.06 Tot. 238159 +331 (invece riporta 333)
> 
> Qualcosa non va, se i totali non sono stati corretti. E comunque se si correggono vale anche per i parziali che li compongono
> I conti devono sempre tornare, secondo me
> Grazie ancora

Pare si sia deciso che le tabelle non debbano più essere coerenti per evitare valori negativi.
Vedi #703 

Non sto giudicando la scelta, fornisco solo un'informazione in più

**Comment by RossoDeM** [comment]
Aggiungo che non torna nemmeno nelle tabelle regioni di ieri e oggi riga Abruzzo:
16.06 Tot. 3280 +1 (ok)
17.06 Tot. 3281 +1 (riportate +2)
18.06 Tot. 3281 =   (riportate ancora +2)
però se a questo punto (accertata la discrepanza) correggete solo i totali e non anche una delle voci che li compongono (tipo isolamenti), allora è un problema.
Lo dico perché io uso fogli sheet uno per ogni regione e riepilogo nazionale con l'evoluzione temporale di ognuna (date per riga dal 24.04) e calcoli automatici una volta inserite le singole voci.

**Comment by RossoDeM** [comment]
> > Mi permetto di insistere perché:
> > 16.06 Tot. 237500 +210 (invariato)
> > 17.06 Tot. 237828 +328 (cambiato in +329)
> > 18.06 Tot. 238159 +331 (invece riporta 333)
> > Qualcosa non va, se i totali non sono stati corretti. E comunque se si correggono vale anche per i parziali che li compongono
> > I conti devono sempre tornare, secondo me
> > Grazie ancora
> 
> Pare si sia deciso che le tabelle non debbano più essere coerenti per evitare valori negativi.
> Vedi #703
> 
> Non sto giudicando la scelta, fornisco solo un'informazione in più

In realtà, a fatica, fino a oggi tutto tornava. D'ora in avanti non ha più senso. Personalmente, quattro mesi da buttare.
È una scelta molto pressapochista e poco rispettosa.
Anche per chi compila.
