### ISSUE TITLE
dimessi guariti inseriti come stringa

### ISSUE THREAD

**Issue by frankplus** [pcm-dpc/COVID-19#706]
Tipo di issue: Dati errati

Nell'ultimo inserimento (18 giugno 2020) nei file 
_dpc-covid19-ita-andamento-nazionale-latest.json_
_dpc-covid19-ita-andamento-nazionale.json_
il numero di dimessi guariti è stato inserito come stringa invece che intero:
```
"dimessi_guariti": "180544",
```

**Comment by umbros** [comment]
Grazie della segnalazione @frankplus, corretto.
