### ISSUE TITLE
Dati positivi giornalieri regionali sbagliati

### ISSUE THREAD

**Issue by jacoisback** [pcm-dpc/COVID-19#707]
I positivi giornalieri non corrispondono, nel file delle regioni, alla differenza tra i totali positivi di oggi meno quelli di ieri.
Verificato per Friuli e Lombardia, ma penso riguardino tutti.

**Comment by umbros** [comment]
Ciao @jacoisback, la differenza è solo sull'Abruzzo per la nota messa.

**Comment by RossoDeM** [comment]
> Ciao @jacoisback, la differenza è solo sull'Abruzzo per la nota messa.



> Ciao @jacoisback, la differenza è solo sull'Abruzzo per la nota messa.

Ciao @umbros, vorrei delucidazioni in merito al proseguimento della issue #705, e aspetto a commentare in merito.
Grazie.
