### ISSUE TITLE
Formato dimessi guariti errati nel json dati nazionali

### ISSUE THREAD

**Issue by DarkFighterLuke** [pcm-dpc/COVID-19#708]
Dimesso guariti è una stringa anziché un intero nel file https://github.com/pcm-dpc/COVID-19/blob/master/dati-json/dpc-covid19-ita-andamento-nazionale.json in data 18 giugno 2020.

Correggete al più presto, grazie.

**Comment by umbros** [comment]
corretto, grazie @DarkFighterLuke
