### ISSUE TITLE
numeri negativi nel campo "nuovi_positivi"

### ISSUE THREAD

**Issue by PierpaoloFerrante** [pcm-dpc/COVID-19#709]
**Tipo di richiesta**:  richiesta  informazioni
## Riassunto

Buongiorno,
nel campo "nuovi_positivi" ho trovato i seguenti valori negativi

date | region | nuovi_positivi
-- | -- | --
27/02/2020 | Piemonte | -1
01/03/2020 | Liguria | -17
02/03/2020 | Liguria | -3
02/03/2020 | Sicilia | -2
09/03/2020 | Piemonte | -10
17/04/2020 | Calabria | -18
04/05/2020 | Sardegna | -2
07/05/2020 | Basilicata | -16
08/05/2020 | Basilicata | -1
19/05/2020 | Marche | -3
25/05/2020 | Sardegna | -2
09/06/2020 | Sardegna | -1
12/06/2020 | Campania | -229

come si spiega?

Grazie 

## Interesse pubblico

Chiarimento sul contenuto di un campo

**Comment by umbros** [comment]
Ciao @PierpaoloFerrante, come da note i negativi sono dovuti a ricalcolo dei dati

**Comment by PierpaoloFerrante** [comment]
grazie
