### ISSUE TITLE
Decrease in total data

### ISSUE THREAD

**Issue by federico-vitale** [pcm-dpc/COVID-19#71]
**Type of issue**: richiesta di informazione

## Summary
Hi! I found some cases where the value of total data is decreasing from one day to the next (e.g. the total number of swabs in Lombardy decrease from 25/2 to 26/2). My question is whether this is okay and how should this be treated analysing the data.

Thank you for the great work! :)

## Public interest

Ease of interpretation of data

**Comment by umbros** [comment]
Hi  @federico-vitale, issue #108

**Comment by federico-vitale** [comment]
@umbros Thanks!
