### ISSUE TITLE
File riepilogo nazionale non aggiornato.

### ISSUE THREAD

**Issue by emazep** [pcm-dpc/COVID-19#710]
Il seguente file:
https://github.com/pcm-dpc/COVID-19/blob/master/dati-andamento-nazionale/dpc-covid19-ita-andamento-nazionale.csv

**non risulta aggiornato nell'ultima commit** di qualche minuto fa (il record più recente è relativo al **18/06/2020**, cioè ieri).

Il file non è stato proprio inserito nella commit (forse perché non aggiornato), visto che l'ultima versione è quella committata ieri.

**Comment by umbros** [comment]
grazie @emazep corretto!

**Comment by emazep** [comment]
A latere segnalo che non risulta (ancora) aggiornato neanche:
https://github.com/pcm-dpc/COVID-19/blob/master/dati-andamento-nazionale/dpc-covid19-ita-andamento-nazionale-latest.csv

(Benché per me personalmente questo file non sia di interesse).
