### ISSUE TITLE
nuovi_positivi 19/06/2020

### ISSUE THREAD

**Issue by alexl83** [pcm-dpc/COVID-19#711]
Tipo di issue: Dati mancanti o errati
- [x] Dati mancanti o errati 
- [ ] Errore nella documentazione 
- [ ] Errore or mancanza nella dashboard 
- [ ] Problemi di visualizzazione nella dashboard 

- Regione: N/A
- Provincia:  N/A

## Riassunto

la colonna 'nuovi_positivi' del file https://github.com/pcm-dpc/COVID-19/raw/master/dati-andamento-nazionale/dpc-covid19-ita-andamento-nazionale.csv
riporta il valore '251' nella riga relativa al 19/06
Tuttavia la differenza tra 'totale_casi' del 19/06 e 'totale_casi' riportati il giorno 18/06 é '-148'

totale_casi 18/06: 238.159
totale_casi 19/06: 238.011

**Attesa:**

valore 'nuovi_positivi' '-148'

**Attuale:** 

valore 'nuovi_positivi': '251'

**Comment by Simonepu** [comment]
L'errore deve trovarsi in qualche altro dato, perché il totale casi, per sua natura, non può diminuire

**Comment by RossoDeM** [comment]
Devono lasciare il numero in negativo (allora la nota ha un senso), oppure le regioni devono ricalcolare anche una voce interna (tipo gli isolamenti) che incide sul totale.
Lasciare i dati incoerenti non è una buona scelta, e gli errori si accumuleranno (per la verità da ieri) giorno dopo giorno.
Ovviamente è impossibile modificare tabelle passate.
Il succo è che non basta lasciare i nuovi positivi contando solo quelli delle ultime 24 ore. I -399 di oggi devono risultare all'interno delle tabelle, non solo nelle note.

**Comment by RossoDeM** [comment]
Ieri erano indicati 333 invece di 331 (due sempre dell'Abruzzo)

**Comment by alexl83** [comment]
non sono un data scientist, quindi posso esprimere solo quanto mi suggerisca il buonsenso, ovvero che i conti devono sempre tornare, altrimenti non sono attendibili.

Nel mio foglio di calcolo ho una colonna aggiuntiva che calcola i 'nuovi positivi' in base alla definizione espressa nel formato dati di questo repo, così oggi mi sono accorto di questa discrepanza abbastanza vistosa.

Spero che venga risolta questa discrepanza
Grazie :)
Alessandro

**Comment by RossoDeM** [comment]
> non sono un data scientist, quindi posso esprimere solo quanto mi suggerisca il buonsenso, ovvero che i conti devono sempre tornare, altrimenti non sono attendibili.
> 
> Nel mio foglio di calcolo ho una colonna aggiuntiva che calcola i 'nuovi positivi' in base alla definizione espressa nel formato dati di questo repo, così oggi mi sono accorto di questa discrepanza abbastanza vistosa.
> 
> Spero che venga risolta.
> Grazie :)
> Alessandro

Guarda, il problema sussisteva anche ieri per i due dell'Abruzzo (che se non era per la Sicilia oggi, è quella che dai primi di giugno crea problemi con questi ricalcoli.
Io stesso ho un foglio Excel per ogni regione (con province a lato) e andamento nazionale, con calcoli automatici (anche di percentuali come incidenza, copertura e letalità). E ogni foglio ha una riga per ogni giorno. 
Quindi mi basta solo inserire tutte le voci parziali e i totali vengono calcolati automaticamente con tutte le variazioni giornaliere di tutte le voci.
Quindi, sapessi quanto per me sia importante la precisione.
Oltretutto ho un foglio che ricava i contagi totali (calcolati automaticamente) da ogni foglio regione, fa la somma e la confronta col totale della tabella nazionale (TRUE o FALSE).

**Comment by umbros** [comment]
Ciao, è stato notificato un ricalcolo casi da parte di Regione Sicilia
https://github.com/pcm-dpc/COVID-19/tree/master/note
https://github.com/pcm-dpc/COVID-19/blob/master/avvisi.md

**Comment by Nikkiolan** [comment]
Buon giorno, vorrei sapere come mai ieri i nuovi casi sono negativi (che senso ha?) come possono essere diminuiti i casi totali? se guardiamo questa pagina: https://www.agrimed420.com/covid/  ed evidenziamo gli ultimi giorni (in ato a sinistra) si notano delle discrepanze nei grafici,
Grazie mille per il tempo dedicatomi.

**Comment by umbros** [comment]
@Nikkiolan ci sono stati dei ricalcoli come notifichiamo sempre nelle note.

**Comment by RossoDeM** [comment]
> @Nikkiolan ci sono stati dei ricalcoli come notifichiamo sempre nelle note.

Sì, okay @umbros. Abbiamo letto le note, ma vi sfugge il problema che stiamo ponendo. È il metodo che è sbagliato.

**Comment by Nikkiolan** [comment]
> @Nikkiolan ci sono stati dei ricalcoli come notifichiamo sempre nelle note.

non sarebbe piu' corretto rettificare i giorni precedenti? (in cui erano stati aggiunti ) oppure conteggiarli tra i guariti? perche' gestendo cosi' i ricalcoli, si toglie credibilita' a tutto il sistema, chi crederebbe mai ad un grafico dove i nuovi casi sono negativi? gia' e' pieno internet di sottosviluppati che gridano a complotti vari, che non credono ai dati, non credono al virus e via dicendo (ogni giorno ne inventano una e faccio fatica a stargli dietro) in questo modo pero' diventa difficile per me smentirli e cercare di farli ragionare.
Grazie mille per la gentile e celere risposta, e per il tempo dedicatomi.
cordialmente, nicola.
