### ISSUE TITLE
Variazione Intensive del 19/06/2020

### ISSUE THREAD

**Issue by MicheleAlfinito** [pcm-dpc/COVID-19#712]
Tipo di issue:

- [X] Dati mancanti o errati 
- [ ] Errore nella documentazione 
- [ ] Errore or mancanza nella dashboard 
- [ ] Problemi di visualizzazione nella dashboard 

- Regione:
- Provincia: 

## Riassunto

Facendo la differenza tra i dati del campo terapia_intensiva tra i file dpc-covid19-ita-regioni-20200619.csv e dpc-covid19-ita-regioni-20200618.csv e sommando le variazioni, a livello Nazionale risulta esserci una variazione di "-7" anzichè i "+7" dichiarati in http://www.salute.gov.it/portale/nuovocoronavirus/dettaglioContenutiNuovoCoronavirus.jsp?area=nuovoCoronavirus&id=5351&lingua=italiano&menu=vuoto

**Attesa:**

Verificare ed eventualmente correggere

**Comment by umbros** [comment]
Confermo la cosa e comunichiamo l'errore ai colleghi del Ministero della Salute.
Grazie

**Comment by MicheleAlfinito** [comment]
Grazie a voi, per il lavoro che svolgete

Il sab 20 giu 2020, 10:46 Umberto Rosini <notifications@github.com> ha
scritto:
