### ISSUE TITLE
Cala il numero di casi totali in Sicilia?

### ISSUE THREAD

**Issue by lucalista** [pcm-dpc/COVID-19#713]
Tipo di issue:

- [ x] Dati mancanti o errati 
- [ ] Errore nella documentazione 
- [ ] Errore or mancanza nella dashboard 
- [ ] Problemi di visualizzazione nella dashboard 

- Regione: Sicilia
- Provincia: 

## Riassunto

Il numero di casi totali in Sicilia scende a 3070 dal precedente 3464. Stessa cosa in diverse province Siciliane.

Il numero dovrebbe essere crescente, a meno che non si tratti di un riconteggio.

**Attesa:**

almeno 3464
Il numero totale dovrebbe essere sempre crescente.

**Attuale:** 
3070

**Comment by umbros** [comment]
Ciao, è stato notificato un ricalcolo casi da parte di Regione Sicilia
https://github.com/pcm-dpc/COVID-19/tree/master/note
https://github.com/pcm-dpc/COVID-19/blob/master/avvisi.md

**Comment by picomiles** [comment]
Scusate se mi inserisco anche io (e a issue già chiusa) ma se è corretto attenersi ai criteri con cui vengono determinati i valori dei vari campi, osservo che ieri, nel campo nuovi_positivi è stato esposto il valore 3, mentre stando alla definizione del campo il  valore da esporre avrebbe dovuto essere -394, ovvero totale_casi del 19/6/20 (3070) - totale_casi del 18/6/20 (3464). Inoltre nelle note si indica in -397 il valore della rettifica del totale_casi (erroneamente indicati come "casi positivi" che è un campo che non esiste). A questo punto mi chiedo se anche in fase di correzione non sia stato commesso un ulteriore errore; qual è l'esatta variazione in diminuzione del totale_casi? -394 o -397? e a questo punto mi chiedo anche quale sia l'esatto valore del totale_casi, 3070 o 3073?

**Comment by umbros** [comment]
Ciao @picomiles i casi positivi si intende quelli che sono attualmente positivi, relativamente al ricalcolo sono 397 come da nota: https://github.com/pcm-dpc/COVID-19/blob/master/schede-riepilogative/regioni/dpc-covid19-ita-scheda-regioni-20200619.pdf, 3 sono quelli "nuovi positivi" del giorno 19/06.
