### ISSUE TITLE
Andamento nazionale latest non aggiornato (19 giugno)

### ISSUE THREAD

**Issue by Doc73** [pcm-dpc/COVID-19#714]
Tipo di issue:

- [x] Dati mancanti o errati 
- [ ] Errore nella documentazione 
- [ ] Errore or mancanza nella dashboard 
- [ ] Problemi di visualizzazione nella dashboard 

- Regione:
- Provincia: 

## Riassunto

Come in oggetto, non risulta aggiornato ai dati di oggi il file

COVID-19/dati-andamento-nazionale/dpc-covid19-ita-andamento-nazionale-latest.csv

Grazie mille!

**Attuale:**

**Comment by umbros** [comment]
corretto grazie @Doc73
