### ISSUE TITLE
Come posso citare questo repository su pubblicazioni scientifiche? Grazie!

### ISSUE THREAD

**Issue by hedph3lym** [pcm-dpc/COVID-19#715]
**Tipo di richiesta**:  richiesta di informazione | richiesta di dati | suggerimento di miglioramento (documentazione, label, _ecc_) | relativo alla pagina grafica

**Comment by umbros** [comment]
@hedph3lym nei prossimi giorni metteremo due elenchi sui lavori  e pubblicazioni basate su questo repository.
