### ISSUE TITLE
Nuovi casi in Campania 6 o 7?

### ISSUE THREAD

**Issue by Rabelaiss** [pcm-dpc/COVID-19#717]
La regione Campania ha comunicato [6 nuovi casi](https://scontent-mxp1-1.xx.fbcdn.net/v/t1.0-9/105598569_3550558234973743_710116253089257361_o.jpg?_nc_cat=106&_nc_sid=8024bb&_nc_ohc=7g-4MyuENJkAX_ojkVD&_nc_ht=scontent-mxp1-1.xx&oh=644fe2343933ae8e52b0c12615cad6d0&oe=5F163817), la Protezione Civile 7 nuovi casi.
Entrambi hanno comunicato 4624 casi in totale.
Negli avvisi non compare nulla a riguardo. Si sa qualcosa?

**Comment by umbros** [comment]
I dati che eroghiamo sono quelli forniti dalla Regione stessa, quindi potrebbe essere che hanno comunicato il dato in un momento diverso.
