### ISSUE TITLE
Maggiori Dati per Provincia / Comune

### ISSUE THREAD

**Issue by yokaotoko** [pcm-dpc/COVID-19#718]
All'interno di varie regioni (penso alla Lombardia) la notevole disparità dei contagi (e presumibilmente di conseguenza anche di ricoverati, deceduti, etc.) registrati nelle varie province rende molto poco significativo il dato aggregato: per conoscere stato ed andamento dell'epidemia sarebbe molto più utile avere anche a livello provinciale il dettaglio tutti i dati disponibili per regione/stato: ricoverati_con_sintomi, terapia_intensiva, totale_ospedalizzati, isolamento_domiciliare, totale_positivi, variazione_totale_positivi, nuovi_positivi, dimessi_guariti, deceduti, totale_casi, tamponi.

Allo stesso modo potrebbe essere molto significativo il dato a livello comunale; quantomeno il numero dei contagi registrati.

**Comment by umbros** [comment]
@yokaotoko attualmente sono questi i dati che vengono rilasciati, ci saranno nuovi dati che saranno rilasciati nei prossimi giorni e verranno comunicati opportunamente.

**Comment by yokaotoko** [comment]
@umbros che "attualmente sono questi i dati che vengono rilasciati" me ne sono accorto ;)
ritengo semplicemente che non siano sufficienti per avere un quadro decentemente esaustivo... spero nei "nuovi dati che saranno rilasciati nei prossimi giorni"
