### ISSUE TITLE
non aggiornato il 23/06/2020 il file dpc-covid19-ita-andamento-nazionale.json

### ISSUE THREAD

**Issue by alexodus** [pcm-dpc/COVID-19#719]
Tipo di issue:

- [ ] Dati mancanti o errati 
- [ ] Errore nella documentazione 
- [ ] Errore or mancanza nella dashboard 
- [ ] Problemi di visualizzazione nella dashboard 

- Regione:
- Provincia: 

## Riassunto

**Attesa:**

**Attuale:**

**Comment by umbros** [comment]
corretto @alexodus grazie
