### ISSUE TITLE
Totale contagiati al 7 Marzo

### ISSUE THREAD

**Issue by marco-c** [pcm-dpc/COVID-19#72]
Tipo di issue:

- [x] Dati mancanti o errati

## Riassunto

Da https://www.lastampa.it/cronaca/2020/03/07/news/i-numeri-dell-allarme-in-lombardia-da-28-a-350-ricoverati-in-due-settimane-1.38563905: "Un dato in forte crescita rispetto a ieri, ma c'erano oltre 300 tamponi che ieri non erano ancora stati caricati dal laboratorio di Brescia. L'incremento di 800 unità deve  quindi essere riallineato".
Avete tenuto conto di questa cosa nei dati relativi al 7 Marzo?

**Comment by umbros** [comment]
@marco-c, i dati comunicati sono quelli delle Regioni al Ministero della Sanità, se un laboratorio invia o la Regione non carica il giorno stesso i numeri, quelli vanno computati nel giorno di comunicazione perchè è una comunicazione al Ministero della Sanità, quindi i "nuovi positivi" vengono assegnati al giorno di comunicazione e non al giorno di esito. E' una rigidità di processo necessaria per tenere una gestione ordinata dei dati.

**Comment by marco-c** [comment]
@umbros capisco. Purtroppo molti stanno basando i loro modelli matematici di diffusione senza considerare questa discrepanza, è un peccato.

**Comment by marco-c** [comment]
@umbros è possibile aggiungere questo problema agli avvisi, come avete fatto per il 10 e l'11?
