### ISSUE TITLE
incremento casi totali non coerente con nuovi positivi

### ISSUE THREAD

**Issue by gabriele2605** [pcm-dpc/COVID-19#721]
Tipo di issue:

- [ x] Dati mancanti o errati 
- [ ] Errore nella documentazione 
- [ ] Errore or mancanza nella dashboard 
- [ ] Problemi di visualizzazione nella dashboard 

- Regione:
- Provincia: 

## Riassunto
ieri 23 6 erano riportati 238833 e oggi 24 6  sono riportati 239410, cioè un incremento di 577 casi.
tuttavia i nuovi casi sono riportati essere 190
--

--

**Comment by vitop72** [comment]
E' dovuto ad un (orribile) ricalcolo della PA di trento comunicato negli avvisi.

**Comment by gabriele2605** [comment]
Corretto. Issue chiusa
