### ISSUE TITLE
Delta casi province 24 giugno anomalo

### ISSUE THREAD

**Issue by vitop72** [pcm-dpc/COVID-19#722]
Il delta casi tra oggi (24/6) e ieri (23/6) nei dati province è anomalo e non coerente con i dati regionali.
Esempio:

Trento | P.A. Trento | 387
Teramo | Abruzzo | 154
Pistoia | Toscana | 62
Latina | Lazio | 49
Pescara | Abruzzo | 42
Frosinone | Lazio | 38
Milano | Lombardia | 29
Viterbo | Lazio | 27
Pisa | Toscana | 25

**Comment by umbros** [comment]
Stiamo controllando la cosa, sta cambiando il sistema di caricamento dei dati

**Comment by Paulsword** [comment]
Ci sono moltissime province in negativo sui nuovi casi, specie Emilia Romagna e Toscana

**Comment by dallanoce** [comment]
Sembra esserci una discrepanza anche sui dati dell'andamento nazionale. Il delta dei casi di oggi é 577(colonna totale casi) ma nella colonna nuovi casi sono riportati 190.

**Comment by umbros** [comment]
Ciao, i dati a livello provinciale sono ora per residenza e non più per ospedalizzazione.
C'è stato un ricalcolo importante su P.A. Trento.

**Comment by Paulsword** [comment]
> Sembra esserci una discrepanza anche sui dati dell'andamento nazionale. Il delta dei casi di oggi é 577(colonna totale casi) ma nella colonna nuovi casi sono riportati 190.

Quella è la differenza con i casi trentini

**Comment by Paulsword** [comment]
> Ciao, i dati a livello provinciale sono ora per residenza e non più per ospedalizzazione.
> C'è stato un ricalcolo importante su P.A. Trento.

Ma che modo è di cambiare? Senza comunicare niente?

**Comment by Jmuccigr** [comment]
> > Ciao, i dati a livello provinciale sono ora per residenza e non più per ospedalizzazione.
> > C'è stato un ricalcolo importante su P.A. Trento.
> 
> Ma che modo è di cambiare? Senza comunicare niente?

E senza cambiare i dati precedenti?

**Comment by Paulsword** [comment]
> Ma è successo qualcos'altro, visto che molte hanno oggi un numero di nuovi casi diminuito da ieri?
> 
> Arezzo -21
> Bologna -52
> Chieti -202
> Firenze -333
> Forlì-Cesena -16
> Genova -338
> Grosseto -36
> Imperia -84
> L'Aquila -21
> La Spezia -42
> Livorno -83
> Lucca -19
> Massa Carrara -2
> Modena -78
> Piacenza -116
> Prato -45
> Ravenna -16
> Reggio nell'Emilia -88
> Rimini -42
> Roma -107
> Rovigo -1
> Savona -57
> Siena -14

Leggi i commenti e capisci

**Comment by Jmuccigr** [comment]
Quindi tutti i valori negativi sono attribuiti al cambio a provincia di residenza? E PA Trento ha fatto una grande correzione?

Il primo sembra di meritare un “avviso”.
