### ISSUE TITLE
Si possono avere note con dati precisi?

### ISSUE THREAD

**Issue by sapienzafra** [pcm-dpc/COVID-19#723]
In queste giornate di "ricalcoli", chi come me utilizza il repository per la generazione di grafici e statistiche si trova in difficoltà, perché ogni giorno c'è una discrepanza sui numeri. Visto che, per quel che ho capito, si è scelto di non correggere i dati passati ma di affidare le segnalazioni alle note, avevo intenzione di implementare una routine che ne tenesse conto. Vedo però che le note sono spesso vaghe o incomplete. Un esempio, quello di ieri a Trento: quanti casi/decessi sono stati sottratti/aggiunti? Relativi a quale/i giorno/i?
Grazie e saluti

**Comment by Nikkiolan** [comment]
Questa cosa dei ricalcoli sta mettendo in difficolta' anche me, ieri ho avuto una discussione con una ragazza, la quale sosteneva, dati alla mano, che a Trento erano risorte 31 persone... ora io me lo auguro, spero che sia vero, e sono felice per questi fortunati che sono risorti, ma allora come mai i tg non ne parlano? nessuno e' andato ad intervistarli? magari per vedere se sono capaci di camminare sulle acque o moltiplicare pesci...
Grazie mille per il lavoro difficilissimo che state portando avanti, malgrado in internet si respiri una fastidiosa aria di scetticismo.
Cordialmente Nicola.

**Comment by RossoDeM** [comment]
> Questa cosa dei ricalcoli sta mettendo in difficolta' anche me, ieri ho avuto una discussione con una ragazza, la quale sosteneva, dati alla mano, che a Trento erano risorte 31 persone... ora io me lo auguro, spero che sia vero, e sono felice per questi fortunati che sono risorti, ma allora come mai i tg non ne parlano? nessuno e' andato ad intervistarli? magari per vedere se sono capaci di camminare sulle acque o moltiplicare pesci...
> Grazie mille per il lavoro difficilissimo che state portando avanti, malgrado in internet si respiri una fastidiosa aria di scetticismo.
> Cordialmente Nicola.

Hanno scelto di perseverare nell'errore metodologico, mantenendo l'inconsistenza dei dati.
Invece di correggere le singole voci e i relativi totali, a partire dai dati provinciali, ricalcolano arbitrariamente le variazioni solo in base alle comunicazioni, giustificandosi con le note.
Le note devono essere un asterisco di dati e calcoli corretti, non sbagliati.
Ma ormai è parlare al muro.
L'ho detto la settimana scorsa che facevano uno strafalcione, e che se lo sarebbero portati dietro per tutti i giorni a seguire.
E questo si aggiunge al gravissimo errore di non aver mai distinto i dimessi dai guariti, il che non solo da mesi altera la percezione della realtà ma soprattutto incide sul dato dei contagi ancora attivi (che ovviamente dovrebbero comprendere anche i clinicamente ma non definitivamente guariti). Un caso ancora aperto.
Quanto ai 31 trentini sono già stati scritturati da Romero: sì è risorto pure lui e stanno tutti trotterellando sul set. Gli altri 2 ancora nel limbo sono andati alla ricerca dei leocorni per un doppio misto.
Cordialmente, ma con infinita amarezza.

**Comment by umbros** [comment]
@RossoDeM capisco quanto da te detto ma riportiamo i dati forniti da Regioni e Ministero della Salute. Le note sono quelle fornite dalle Regioni stesse, se ci sono dei ricalcoli dove non è possibile indicarne il giorno è inconsistente anche mettere o diminuire numeri in giorni a caso. Non è una giustificazione ma il periodo a cui si riferiscono i ricalcoli è quello dei momenti più intensi della pandemia in Italia.

**Comment by RossoDeM** [comment]
> @RossoDeM capisco quanto da te detto ma riportiamo i dati forniti da Regioni e Ministero della Salute. Le note sono quelle fornite dalle Regioni stesse, se ci sono dei ricalcoli dove non è possibile indicarne il giorno è inconsistente anche mettere o diminuire numeri in giorni a caso. Non è una giustificazione ma il periodo a cui si riferiscono i ricalcoli è quello dei momenti più intensi della pandemia in Italia.

Mi rendo conto, ma il punto è che se le variazioni giornaliere sino corrette e fotografano il reale, i valori assoluti di giornata non lo sono, sia come totali sia come singole voci, tanto nella tabella nazionale quanto in quella delle regioni.
So benissimo che non ha senso rimettere le mani su tabelle di giorni precedenti (anche di mesi o peggio date desaparecidas). Ma alla fine i conti devono tornare per ricavare correttamente le statistiche in base all'andamento temporale e alle tendenze, per una precisa analisi.
È questo il senso di avere open data ed essere ospitati su una piattaforma come GitHub.
Se ignorate le issues che cercano di darvi una mano e che vi avvertono che state sbagliando nel metodo e nell'approccio (e che le palle di neve possono diventare valanghe), poi però non lamentatevi che il grande pubblico a cui vi rivolgete coi bollettini non vi segua più (se non peggio).

**Comment by Nikkiolan** [comment]
> @RossoDeM capisco quanto da te detto ma riportiamo i dati forniti da Regioni e Ministero della Salute. Le note sono quelle fornite dalle Regioni stesse, se ci sono dei ricalcoli dove non è possibile indicarne il giorno è inconsistente anche mettere o diminuire numeri in giorni a caso. Non è una giustificazione ma il periodo a cui si riferiscono i ricalcoli è quello dei momenti più intensi della pandemia in Italia.

Non e' possibile determinare il giorno in cui ci fu lo sbaglio, ma basta levare i morti dai giorni in cui quella regione ne ha avuti di piu', se per esempio a Trento ad aprile in un giorno ci sono stati 100 morti, basta mettere che ne ha avuti 70, oppure si possono spalmare tra i 10 giorni di massimo, e levare 3 morti da ognuno di quelli, in questo modo non si andrebbero ad alterare i grafici e gli andamenti degli ultimi giorni, che sono i piu importanti per capire l'andamento della situazione odierna,

**Comment by umbros** [comment]
@RossoDeM la decisione presa è quella di non toccare quelli precedenti, nessuno ignora le issue. Andare a modificare numeri spalmandoli su giorni ha lo stesso valore di modificarlo in uno con la differenza che su uno viene messa una nota.
