### ISSUE TITLE
Dati provinciali

### ISSUE THREAD

**Issue by AlfaCent** [pcm-dpc/COVID-19#724]
Buongiorno,
ho rilevato notevoli variazioni nei dati dei casi positivi in varie regioni: Emilia Romagna, Toscana, Liguria,...

Sono correzioni di dati errati?

Nulla è riportato negli avvisi.

Saluti e grazie
AF

**Tipo di richiesta**:  richiesta di informazione | richiesta di dati | suggerimento di miglioramento (documentazione, label, _ecc_) | relativo alla pagina grafica

**Comment by Paulsword** [comment]
@umbros ha già risposto alla domanda, e chiuso la discussione - secondo me un po' prematuramente, visto che infatti altri pongono la stessa issue, anche perché, da quel che pare, il criterio di attribuzione dei casi per residenza non è ancora andato a buon fine in tutte le regioni, ma solo in un piccolo numero, peraltro sufficiente a scombinare il quadro non poco.T
Torno a dire che, senza nulla volere a @umbros, sono modifiche che avrebbero richiesto, se non altro per rispetto nei confronti degli utenti, adeguato preavviso.

**Comment by umbros** [comment]
@Paulsword, differentemente dalla modifica dei dataset, il dato che ci viene comunicato, come da ultimi comunicati stampa è affidato a Ministero della Salute.

**Comment by vi-enne** [comment]
> @Paulsword, differentemente dalla modifica dei dataset, il dato che ci viene comunicato, come da ultimi comunicati stampa è affidato a Ministero della Salute.

La Protezione Civile ricevera quindi i dati da una sola fonte (Ministero della Salute) invece che da 21 (Regioni e PA)?
Grazie

**Comment by umbros** [comment]
Ciao @vi-enne si il Dipartimento della Protezione Civile supporterà il Ministero della Salute nella pubblicazione della dashboard e degli opendata ma i dati saranno rilasciati da Ministero della Salute. Potrebbero esserci degli allineamenti e modifiche di dataset che correttamente come dice @Paulsword saranno comunicati per tempo e tenuto un legacy di una settimana sui dataset attualmente pubblicati.
