### ISSUE TITLE
Incrementi totali errati

### ISSUE THREAD

**Issue by p1et4o** [pcm-dpc/COVID-19#725]
Tipo di issue:

- [X ] Dati mancanti o errati 
- [ ] Errore nella documentazione 
- [ ] Errore or mancanza nella dashboard 
- [ ] Problemi di visualizzazione nella dashboard 

## Riassunto

Il totale casi del 22 giugno è di 238720
Il totale casi del 23 giugno è di 238833 ( +113 )
Il totale casi del 24 giugno è di 239410 ( +577 )

Gli incrementi dei casi totali risultano errati in quanto il 23 giugno sono stati riportati +122 casi ed il 24 giugno +190

**Attesa:**

**Attuale:**

**Comment by umbros** [comment]
In base ai ricalcoli le Regioni e Ministero della Salute hanno ricalcolato i valori, comunicando delle note.
