### ISSUE TITLE
Protezione Civile e Ministero della Salute

### ISSUE THREAD

**Issue by Salvatore-Curiale** [pcm-dpc/COVID-19#728]
**Tipo di richiesta**:  richiesta di informazione 

## Riassunto

Ho letto che dal 25 giugno (oggi) il flusso dei dati non sarà più gestito dalla protezione civile ma direttamente dal Ministero della Salute. Volevo quindi sapere se questo servizio verrà mantenuto ed aggiornato, oppure sospeso (speriamo di no), oppure trasferito su un altro link.

## Interesse pubblico

Continuare a ricevere i dati in formato aperto

**Comment by umbros** [comment]
Confermiamo che il servizio sarà mantenuto, ciò che cambia è semplicemente il soggetto che comunica i dati giornalieri, la parte opendata e dashboard sarà sempre gestita dal Dipartimento della Protezione Civile
