### ISSUE TITLE
Possibile inversione righe dati

### ISSUE THREAD

**Issue by 123cobloc** [pcm-dpc/COVID-19#729]
Tipo di issue:

- [x] Dati mancanti o errati 
- [ ] Errore nella documentazione 
- [ ] Errore or mancanza nella dashboard 
- [ ] Problemi di visualizzazione nella dashboard 

- Regione:
- Provincia: 

## Riassunto

File CSV 25/06/2020 spostamento di 11k casi da Lombardia a Liguria

**Attesa:**

**Attuale:**

**Comment by umbros** [comment]
Stiamo correggendo le regioni

**Comment by Paulsword** [comment]
E' un'inversione o una ricollocazione secondo il principio della residenza? Chissà

**Comment by umbros** [comment]
Regioni corrette.

**Comment by 123cobloc** [comment]
dpc-covid19-ita-regioni-20200625.csv non aggiornato
dpc-covid19-ita-regioni-latest.csv e dpc-covid19-ita-regioni.csv dati del 25/06 ordinati per codice regione e non seguendo l'ordine alfabetico (come fatto fino ad oggi)
