### ISSUE TITLE
Errore per i dati relativi al Piemonte - aggiornamento 9 marzo

### ISSUE THREAD

**Issue by domenicorossi** [pcm-dpc/COVID-19#73]
Segnalo che i dati relativi al Piemonte nell'ultima segnalazione non coincidono con quelli comunicati ufficialmente dalla Regione Piemonte. Segue il comunicato:
"In Piemonte sono diventate 380 le persone risultate positive al Coronavirus, mentre quelle negative al test sono 1.238. Gli esami in corso sono 238.

Territorialmente, i casi positivi sono così distribuiti: 101 a Torino, 58 ad Asti, 63 ad Alessandria, 20 a Biella, 13 a Cuneo, 19 a Novara, 12 a Vercelli e 11 nel VCO. I casi positivi provenienti da fuori regione sono 16, mentre 67 casi sono ancora in fase di elaborazione e attribuzione territoriale.

In rianimazione sono ricoverate 61 persone e in altri reparti 120; in isolamento domiciliare ce ne sono 186. I decessi sono 13."
Qui il link: https://www.regione.piemonte.it/web/pinforma/notizie/coronavirus-gli-aggiornamenti-dalla-regione-piemonte

Tipo di issue:

- [ ] Dati mancanti o errati 
- [ ] Errore nella documentazione 
- [ ] Errore or mancanza nella dashboard 
- [ ] Problemi di visualizzazione nella dashboard 

## Riassunto

**Attesa:**

**Attuale:**

**Comment by marcodadamo** [comment]
Nella directory COVID-19/dati-regioni/dpc-covid19-ita-regioni-20200309.csv, alla regione **Piemonte** nella voce della tabella **"nuovi attualmente positivi"**, viene riportato il valore in negativo **(-18)**

**Comment by alesarrett** [comment]
Confermo entrambe le incongruenze: il "totale_casi" sarebbe diminuito di 10 unità tra l'8 e il 9 marzo (da 360 a 350) e i "nuovi_attualmente_positivi" è un numero negativo (-18).

**Comment by umbros** [comment]
Ciao a tutti, i dati sono corretti per quanto comunicati dalle Regioni al Ministero della Salute, eventuali comunicazioni delle Regioni, in momenti successivi il conferimento dei dati non vengono reintegrati perchè non seguono il canale ufficiale. Ripeto che questo è il repository ufficiale dei dati e necessita (questo può generare, a volte, anche ritardi) di un processo formale.
