### ISSUE TITLE
Dati corrispondenti alle regioni sbagliate per il 25/6

### ISSUE THREAD

**Issue by lucalista** [pcm-dpc/COVID-19#730]
Tipo di issue:

- [X] Dati mancanti o errati 
- [ ] Errore nella documentazione 
- [ ] Errore or mancanza nella dashboard 
- [ ] Problemi di visualizzazione nella dashboard 

- Regione: Tutte
- Provincia: 

## Riassunto

Nei files è cambiato l'ordine delle regioni: il 25/6 l'ordine è per codice regione anziché alfabetico. Però, i contenuti dei files sembrano rispecchiare il vecchio ordinamento. Ad esempio, la Campania ha 282325 casi totali.

**Attesa:**

Rivedere l'ordinamento e i dati corrispondenti alle regioni.

**Attuale:**

**Comment by 123cobloc** [comment]
dpc-covid19-ita-regioni-20200625.csv non corretto
dpc-covid19-ita-regioni-latest.csv e dpc-covid19-ita-regioni.csv dati ordinati per codice regione e non seguendo l'ordine alfabetico

**Comment by Babidi90** [comment]
la deonominazione geografica non è ordinata in maniera corretta rispetto ai dati

**Comment by emazep** [comment]
Per giunta i codici regione sono stati alterati: da carattere sono diventati numerici (01->1, 02->2 ecc.)

**Comment by umbros** [comment]
Controlliamo

**Comment by umbros** [comment]
I dati sono corretti, i codici regione sono con lo zero ora.

**Comment by emazep** [comment]
I codici sono stati corretti, ma i dati ancora no: ad esempio in Lombardia risultano 2 (due) nuovi positivi oggi.

**Comment by lucalista** [comment]
Non mi pare, guardate l'ultimo issue sottoposto: la Campania ha i dati sbagliati.
