### ISSUE TITLE
Chieti 25 giugno

### ISSUE THREAD

**Issue by vitop72** [pcm-dpc/COVID-19#731]
Ancora oggi sul tracciato delle province c'è qualcosa che non va.
Questa la situazione di CHIETI con il dato cumulato dei casi ed il delta degli ultimi gg.
Oggi segna un improbabile +186..

22/6 | 832 |  
23/6 | 832 | 0
24/6 | 630 | -202
25/6 | 816 | 186

**Comment by umbros** [comment]
Ciao @vitop72 ora le province vengono date per residenza e non più per ospedalizzazione da Ministero della Salute.

**Comment by vitop72** [comment]
> Ciao @vitop72 ora le province vengono date per residenza e non più per ospedalizzazione da Ministero della Salute.

Ciao @umbros , questo che quoto me lo hai scritto ieri 24/6. Quindi abbiamo capito che fino al 23/6 c'è stato un metodo di calcolo (per ospedalizzazione) e dal 24/6 un nuovo metodo (per residenza).
Nell'esempio fatto adesso CHIETI ieri, fino al 23/6 aveva 832 casi. Ieri a seguito del ricalcolo per residenza risultava avere 630 casi. Ma oggi che se ne leggono nuovamente 816 cosa è accaduto? Spero la domanda sia chiara.
