### ISSUE TITLE
Dati nuovi positivi incorretti Campania. Ricalcolo o errore?

### ISSUE THREAD

**Issue by MarioMarietto** [pcm-dpc/COVID-19#732]
Tipo di issue:

- [x] Dati mancanti o errati 
- [ ] Errore nella documentazione 
- [ ] Errore or mancanza nella dashboard
- [ ] Problemi di visualizzazione nella dashboard

- Regione: Campania
- Provincia: 

## Riassunto

Nella dashboard, viene visualizzato un numero di nuovi positivi per la Campania, diverso da quanto emanato nel bollettino del 25/06

**Attesa:**

Secondo l'ultimo bollettino emanato dalla Regione Campania (http://www.regione.campania.it/assets/documents/agg-25062020-1700.pdf), i nuovi positivi dovrebbero essere 17.

**Attuale:** 
Nella dashboard, vengono indicati 47 nuovi positivi.

**Comment by umbros** [comment]
Sono dati comunicati dalla Regione Campania. Forse dipende da orari o momenti differenti.

**Comment by lucalista** [comment]
Avevo segnalato la stessa cosa, hanno chiuso dicendo che era un problema di codice che ora ha lo zero. Non mi pare che sia così, come scrivi i dati sembrano errati.

**Comment by umbros** [comment]
luca, corretto il problema. Grazie

**Comment by lucalista** [comment]
OK, ora mi sembra a posto, grazie.
