### ISSUE TITLE
Si potrebbe ripristinare l'ordine delle regioni fino a ieri?

### ISSUE THREAD

**Issue by marco8251** [pcm-dpc/COVID-19#733]
Chi raccoglie questi dati da 3 mesi ora ha il problema di doverli risequenziare a mano. Perchè è stato cambiato l'ordine?

**Comment by umbros** [comment]
@marco8251 l'ordinamento per denominazione è stato ripristinato, ti consiglio, però di prendere i dati per codice regione (che tra l'altro a livello di interoperabilità ti può servire anche per il collegamento con altri dataset.
