### ISSUE TITLE
Colonna nuovi_positivi di oggi 26-6-2020

### ISSUE THREAD

**Issue by Tantormai** [pcm-dpc/COVID-19#734]
La colonna nuovi_positivi sembra mostrare dati scambiati tra di loro.
Ad esempio:
Lombardia:     2
Liguria:       170

**Comment by Jmuccigr** [comment]
> La colonna nuovi_positivi sembra mostrare dati scambiati tra di loro.
> Ad esempio:
> Lombardia: 2
> Liguria: 170

Corretto adesso. Ri-scaricare.

Io vedo un sacco di "in fase..." risolti. Perché? E c'e una nuova categoria per province di "fuori PA"

**Comment by umbros** [comment]
Ciao @Jmuccigr la categoria fuori PA è un nuovo indicatore che viene ora specificato, sulle province comunicheremo entro domani le modifiche e le logiche avvenute.
