### ISSUE TITLE
Errore nel file dei dati sulle province in json in data odierna

### ISSUE THREAD

**Issue by DarkFighterLuke** [pcm-dpc/COVID-19#735]
C'è un qualche errore di tipo nel file json dei dati provinciali completi: https://github.com/pcm-dpc/COVID-19/blob/master/dati-json/dpc-covid19-ita-province.json

**Comment by umbros** [comment]
Ciao,
abbiamo controllato e non risultano errori. Ci sono solo dei dati in più per indicare dati "fuori Regione/P.A." per Provincia.

**Comment by pinoli** [comment]
confermo che c'è un errore nel JSON delle province, evidenziato [qui](https://github.com/pcm-dpc/COVID-19/issues/738). L'annidamento dei dati per la giornata di oggi è diverso rispetto a tutto il resto del dataset e previene l'aggiornamento dei report che si basano sugli endpoint JSON.
