### ISSUE TITLE
Ordine dati provinciali del 25 giugno

### ISSUE THREAD

**Issue by Doc73** [pcm-dpc/COVID-19#736]
**Tipo di richiesta**:  suggerimento di miglioramento (documentazione, label, _ecc_)

## Riassunto

Gentilissimi Signori,
ho visto che nel file [https://github.com/pcm-dpc/COVID-19/blob/master/dati-province/dpc-covid19-ita-province.csv](https://github.com/pcm-dpc/COVID-19/blob/master/dati-province/dpc-covid19-ita-province.csv) i dati relativi alla data odierna (25 giugno) presentano un ordine diverso rispetto a quelli precedenti.

È possibile modificare di conseguenza tutti gli altri oppure ritornare all'ordine precedente?

Grazie mille in anticipo,
Domenico

**Comment by umbros** [comment]
Ciao @Doc73 le province sono state modificate, domani effettueremo la modifica. Comunque consiglio di lavorare per codice.
