### ISSUE TITLE
errore in json delle province

### ISSUE THREAD

**Issue by alexodus** [pcm-dpc/COVID-19#738]
Compare un "[" all'interno del json errato
![image](https://user-images.githubusercontent.com/2721510/85771886-a09f8e80-b71c-11ea-80d0-36993cc74e6b.png)

**Comment by pinoli** [comment]
confermo che anche il mio report non si aggiorna per via della modifica da Record a List del contenuto del JSON per la data odierna.

**Comment by umbros** [comment]
Grazie @alexodus per la precisazione, il file validava sintatticamente ma effettivamente era presente l'errore che è stato corretto. grazie
