### ISSUE TITLE
Format csv province

### ISSUE THREAD

**Issue by Paulsword** [pcm-dpc/COVID-19#739]
I dati contenuti in https://raw.githubusercontent.com/pcm-dpc/COVID-19/master/dati-province/dpc-covid19-ita-province-20200625.csv mostrano, rispetto ai giorni precedenti, e senza alcun preavviso, le colonne lat e long modificate in latitudine e longitudine, e diverse altre modifiche di format, evidenti all'importazione della tabella (ordine delle righe, formato dei numeri delle colonne codici_provincia e totale_casi), e 149 righe anzichè 128 (casi fuori regione/PA).

Chiedo cortesemente se queste modifiche sono da considerarsi definitive (almeno per un po') o si è trattato di un caso.

**Comment by umbros** [comment]
Ciao @Paulsword,
latitudine e longitudine sono stati corretti, è stato aggiunto un valore "casi fuori regione/PA" che non è una modifica al dataset ma altre informazioni sul dataset che sono presenti da ieri. Per domani è previsto un nuovo dataset con altri campi che verrà messo in "preview" e diventerà attivo da lunedì, i vecchi dataset saranno presenti per 5 giorni in modo da permettere a tutti di effettuare modifiche, riguardo l'ordine delle righe un'elaborazione opportuna dei dati non lavora a righe ma a codici, tuttavia saranno rimesse come prima.
