### ISSUE TITLE
Abruzzo non visualizzato correttamente (Desktop)

### ISSUE THREAD

**Issue by Dambrix** [pcm-dpc/COVID-19#74]
Tipo di issue:
Problemi di visualizzazione nella dashboard
![Abruzzo](https://user-images.githubusercontent.com/48296801/76251059-b6a94200-6246-11ea-80c0-7ec2a2ba05d7.gif)

Com'è possibile vedere dalla gif, quando si clicca sull'Abruzzo la mappa si sposta sulla Sardegna mostrando i dati delle province di quest'ultima. Buon lavoro.

**Comment by Rhuax** [comment]
Il problema sembra esser stato già risolto. Prova a ricontrollare :)
