### ISSUE TITLE
Update tracciato provincie 26-06-2020 ore 10:46

### ISSUE THREAD

**Issue by vitop72** [pcm-dpc/COVID-19#741]
Salve, il tracciato csv delle province di ieri, 25-06 risulta essere stato sovrascritto stamane, 26-06 alle ore 10:46.
E' possibile sapere quale è stato il motivo dell'update dei dati?
Grazie.

**Comment by umbros** [comment]
Ciao @vitop72, come potrai notare nella diff di github (https://github.com/pcm-dpc/COVID-19/commit/270615a3b00848d7f2ff1410db8601083c9272e5) è semplicemente stata cambiata la dicitura latitudine, longitudine (proveniente da un rilascio errato e corretto) in lat, long.

**Comment by vitop72** [comment]
Grazie @umbros
