### ISSUE TITLE
Codici provincia per "fuori regione" coincidono con quelli di "in fase di aggiornamento" nel file dpc-covid19-ita-province-20200625.csv

### ISSUE THREAD

**Issue by Rabelaiss** [pcm-dpc/COVID-19#742]
Nel file dpc-covid19-ita-province-20200625.csv se prendiamo il Piemonte, i campi "fuori Regione/P.A." e "In fase di definizione/aggiornamento" hanno entrambi codice 991, invece "fuori Regione/P.A." dovrebbe avere codice 981.
Problema analogo anche per le altre province

**Comment by Paulsword** [comment]
Io vedo 891 e 991

**Comment by Rabelaiss** [comment]
oggi sono corretti ma ieri no

**Comment by umbros** [comment]
Grazie @Rabelaiss, nella giornata di domani ci sarà un allineamento dei dati e correggeremo la cosa.
Grazie

**Comment by Rabelaiss** [comment]
@umbros i codici provincia per le denominazioni `fuori Regione/P.A.` nel file `dpc-covid19-ita-province-20200625.csv` sono ancora sbagliati
