### ISSUE TITLE
"Casi identificati dal sospetto diagnostico" diminuiti rispetto a ieri

### ISSUE THREAD

**Issue by Rabelaiss** [pcm-dpc/COVID-19#743]
Confrontando le schede riepilogative di oggi e ieri, si nota che i "Casi identificati dal sospetto diagnostico" sono diminuiti di 465, passando da 223905 a 223440. Invece i "Casi identificati da attività di screening" sono aumentati di 720 da 15801 a 16521, numero ben maggiore dei 259 casi odierni.
C'è stato un riconteggio?

**Comment by umbros** [comment]
@Rabelaiss non c'è stata comunicazione della cosa e abbiamo notato anche noi negli script di controllo.
