### ISSUE TITLE
lat/log o latitudine/longitudine ?

### ISSUE THREAD

**Issue by miccoli** [pcm-dpc/COVID-19#745]
Tipo di issue:

- [x] Dati mancanti o errati 
- [ ] Errore nella documentazione 
- [ ] Errore or mancanza nella dashboard 
- [ ] Problemi di visualizzazione nella dashboard 

- Regione:
- Provincia: https://github.com/pcm-dpc/COVID-19/blob/1a9edb716fcaddc21bb3c2e9d7b31abc86765b2c/dati-province/dpc-covid19-ita-province-20200626.csv

## Riassunto

La riga di intestazione dei dati provinciali contiene 'latitudine/longitudine' invece che 'lat/long', cfr. #739

**Attesa:**

Intestazione con 'lat/log'

**Attuale:** 

intestazione con 'latitudine/longitudine'

Stesso errore già segnalato in #739 per il file del 25 giugno.

**Comment by umbros** [comment]
corretto @miccoli grazie della segnalazione
