### ISSUE TITLE
Chiarimento casi_da_screening

### ISSUE THREAD

**Issue by Rabelaiss** [pcm-dpc/COVID-19#746]
Anzitutto grazie al team della protezione civile per aver scorporato i casi screening dai casi totali.

Se possibile vorrei avere maggiori informazioni riguardo il dato `casi_da_screening`, cosa indica di preciso?
Inizialmente pensavo conteggiasse i casi asintomatici individuati da screening e attività di tracciamento, ma confrontando i dati comunicati dalle regioni con quelli delle vostre nuove tabelle, risultano delle discrepanze.
Ad esempio, oggi queste tre regioni hanno comunicato di aver trovato
- lombardia: 21 asintomatici
- emilia-romagna: 34 asintomatici
- piemonte 10 asintomatici

ma facendo la differenza tra la vostra tabella di oggi e quella di ieri (schede regioni) si evince che
- lombardia: 33 casi da screening
- emilia-romagna: 35 casi da screening
- piemonte: 213 casi da screening (valore maggiore del totale dei casi comunicati oggi dal piemonte (11))

**Comment by umbros** [comment]
Ciao @Rabelaiss è un dato che andremo a includere nel dataset da lunedì 19/06 ho messo la specifica nell'avviso #747
