### ISSUE TITLE
Totali casi per Provincia non presenti

### ISSUE THREAD

**Issue by MarioMarietto** [pcm-dpc/COVID-19#748]
Tipo di issue:

- [ ] Dati mancanti o errati 
- [ ] Errore nella documentazione 
- [ ] Errore or mancanza nella dashboard 
- [x] Problemi di visualizzazione nella dashboard 

- Regione:
- Provincia: 

## Riassunto

I Totali Casi per Provincia non vengono visualizzati correttamente

**Attuale:** 
I Totali Casi per Regione vengono visualizzati correttamente a differenza dei casi per Provincia nel quale al posto della lista viene visualizzato: "xxxxx"

**Comment by umbros** [comment]
@MarioMarietto quanto riportato non risulta.

**Comment by MarioMarietto** [comment]
Strano...continuo a vederlo. Forse è un problema della versione mobile? (Ho provato sia la versione mobile che quella desktop da telefono e continuo ad avere lo stesso problema. Inoltre, ho anche verificato su 2 dispositivi diversi.)
