### ISSUE TITLE
Numero guariti Liguria

### ISSUE THREAD

**Issue by 123cobloc** [pcm-dpc/COVID-19#750]
Tipo di issue:

- [ ] Dati mancanti o errati 
- [ ] Errore nella documentazione 
- [ ] Errore or mancanza nella dashboard 
- [ ] Problemi di visualizzazione nella dashboard 

- Regione: Liguria
- Provincia: 

## Riassunto

Il numero di guariti è diminuito rispetto a ieri senza nessun avviso di ricalcolo nelle note.

**Attesa:**

Numero guariti maggiore o uguale a ieri oppure nota di ricalcolo.

**Attuale:**

**Comment by umbros** [comment]
Ciao, corretto @123cobloc è diminuito di 1 valore. Non sono pervenute segnalazioni in merito; si tratta comunque sicuramente di un riconteggio.
