### ISSUE TITLE
Errore JSON in Andamento Nazionale

### ISSUE THREAD

**Issue by MarioMarietto** [pcm-dpc/COVID-19#751]
Tipo di issue:

- [ ] Dati mancanti o errati 
- [ ] Errore nella documentazione 
- [x] Errore or mancanza nella dashboard 
- [ ] Problemi di visualizzazione nella dashboard 

- Regione:
- Provincia: 

## Riassunto

Nel file: "dpc-covid19-ita-andamento-nazionale.json", alla fine del file JSON manca il bracket "]" per la chiusura dell'array.

**Comment by umbros** [comment]
Corretto, grazie @MarioMarietto
