### ISSUE TITLE
problema di validazione: codice regione e codice provincia dal 29 sono diventati stringa mentre per le altre date sono numeri

### ISSUE THREAD

**Issue by alexodus** [pcm-dpc/COVID-19#752]
dati precedenti al 29
![image](https://user-images.githubusercontent.com/2721510/86033141-c5f00d80-ba38-11ea-90d5-a2a8343e98ba.png)

dati del 29
![image](https://user-images.githubusercontent.com/2721510/86033118-b96bb500-ba38-11ea-92ea-1e6e39a3c106.png)

**Comment by alexodus** [comment]
tra l'altro aggiungendo il padding di 0 all'inizio ("066" anzichè "66")  si incasinano i database pregressi

**Comment by umbros** [comment]
@alexodus, corretto il file, ti segnalo che in realtà i codici regione e codici provincia sono son 0 all'inizio:
![image](https://user-images.githubusercontent.com/4085151/86035856-43b61800-ba3d-11ea-8321-015c5ae862f2.png)
tuttavia per una questione di continuità teniamo come int il valore.
