### ISSUE TITLE
script di validazione su repository

### ISSUE THREAD

**Issue by alexodus** [pcm-dpc/COVID-19#753]
Esponete cortesemente gli script di validazione su github, almeno possiamo darvi una mano a renderli quanto meno accettabili nel funzionamento. Quelli attuali praticamente si è capito che validano tutto (a parte validare che si tratti di un json). Grazie

**Comment by umbros** [comment]
@alexodus verranno messi tutti gli script anche se gli script sono solo una parte del processo. Comunque, vista la mole di lavoro che hanno fatto gli script direi che il funzionamento è accettabile. Grazie per la collaborazione.
