### ISSUE TITLE
Numero totale dei casi a livello nazionale del 19 Giugno 2020

### ISSUE THREAD

**Issue by NippurDeLagash** [pcm-dpc/COVID-19#754]
Tipo di issue:

- [ ] Dati mancanti o errati 

dati-andamento-nazionale/dpc-covid19-ita-andamento-nazionale-20200618.csv

- Regione: N/A
- Provincia: N/A

## Riassunto

Valore sospetto sul totale dei casi a livello nazionale nei giorni 18 oppure 19 Giugno.

Il numero totale dei casi dovrebbe essere un numero sempre crescente, invece nel giorno 19 presenta un calo di 148 casi. La sequenza è la seguente:

17 Giugno = 237.828 casi
18 Giugno = 238.159 casi
19 Giugno = 238.011 casi
20 Giugno = 238.275 casi

Probabilmente siano scambiati i dati di questi due giorni.

**Comment by umbros** [comment]
Ciao @NippurDeLagash purtroppo ci sono diversi esempi di andamenti sui casi dovuti a ricalcoli. Quando accadono queste cose viene messa una nota, in casi molto evidenti come quella del 12/06 della Campania (ricalcolo casi positivi (-230)).
