### ISSUE TITLE
Sigla provincia Napoli mancante

### ISSUE THREAD

**Issue by giuliolunati** [pcm-dpc/COVID-19#755]
Tipo di issue:

- `[x]` Dati mancanti o errati dpc-covid19-ita-province.csv
- [ ] Errore nella documentazione 
- [ ] Errore or mancanza nella dashboard 
- [ ] Problemi di visualizzazione nella dashboard 

- Regione: Campania
- Provincia: Napoli

## Riassunto
Manca la sigla_provincia
**Attesa:** "NA"

**Attuale:** ""

**Comment by umbros** [comment]
Ciao @giuliolunati, corretto sia sui csv che sui json.
Grazie

**Comment by giuliolunati** [comment]
Ottimo lavoro, complimenti! :-)
