### ISSUE TITLE
problemi codice provincia e codice regione non risolto

### ISSUE THREAD

**Issue by alexodus** [pcm-dpc/COVID-19#756]
Continuano a persistere i problemi rilevati oggi.
![image](https://user-images.githubusercontent.com/2721510/86059733-a3271e80-ba63-11ea-9797-75c720f6fb88.png)
Ribadisco necessità di condividere immediatamente vostri script validazione ed affidarli alla community

**Comment by alexodus** [comment]
tra l'altro **lat** e **long** sono diventati stringa, così per magia

**Comment by umbros** [comment]
Ciao @alexodus risolto il problema su lat e long, quello sul codice provincia e regioni non è stato trovato ma ho comunque fatto ripassare lo script di correzione, la prossima volta ti ringrazio se metti anche il file dove hai riscontrato il problema. Relativamente agli script sono batch di lavorazione dei dati che aggiungono le coordinate geografiche e fanno dei controlli sui valori riportati. Ti ringrazio per voler collaborare come stai facendo e se vuoi fai pure una pull request se dovessi trovare errori. Grazie

**Comment by alexodus** [comment]
il problema era sul file province, come nel precedente issue. Scusami se non seguo le linee guida degli issue, ma preferisco segnalare errori in modo veloce.
Adesso rilancio mia procedura di aggiornamento dati  e ti faccio sapere se è risolto. Non posso purtroppo "dirottare" sul legacy perché non ho qui con me il codice.

**Comment by umbros** [comment]
Ok ok @alexodus i tuoi contributi sono utilissimi quindi qualsiasi modo è utile
