### ISSUE TITLE
Scorporo positivi

### ISSUE THREAD

**Issue by Paulsword** [pcm-dpc/COVID-19#758]
Buonasera,

riusciamo a rimediare sui numeri dello scorporo dei positivi, o dobbiamo tenerceli così?
Lombardia era abbastanza precisa in questi giorni, oggi se ne esce con -134 da tracciamento e +196 da sierologico (su 62 nuovi casi totali). Evidente che è un ricalcolo, ma che non compare sul sito della Regione.
Idem Piemonte, Toscana, Puglia.

Qualche chance?
Grazie

**Comment by umbros** [comment]
Ciao @Paulsword,
non ci sono arrivate note in merito e anche noi abbiamo notato la differenza dei dati comunicati, attendiamo note. Grazie

**Comment by Rabelaiss** [comment]
anche liguria e abruzzo hanno più nuovi casi da screening che nuovi casi totali oggi

**Comment by umbros** [comment]
si già segnalato, perchè oltretutto la somma deve dare il totale casi.

**Comment by Rabelaiss** [comment]
@umbros perfetto
un'altra cosa, i nuovi avvisi verranno aggiunti in
https://github.com/pcm-dpc/COVID-19/blob/master/avvisi.md
come sempre, oppure in 
https://github.com/pcm-dpc/COVID-19/blob/master/note/dpc-covid19-ita-note.csv ?
chiedo perché ho notato che in `avvisi.md` non sono presenti gli ultimi due avvisi riguardo il riconteggio dei decessi nelle marche e il riconteggio dei positivi in emilia-romagna

**Comment by umbros** [comment]
Ciao @Rabelaiss la gestione delle note è cambiata verranno messi quindi sul csv e json nuovo ma caricato anche su github, stiamo facendo l'import degli avvisi :)

**Comment by umbros** [comment]
@Rabelaiss i dati nuovi di casi da tracciamento o da sierologico essendo nuovi potrebbero subire dei ricalcoli e questo vale per tutte le Regioni, stasera metto nota sul readme.
