### ISSUE TITLE
Problema con Google fogli importhtml

### ISSUE THREAD

**Issue by SilvioCaggia** [pcm-dpc/COVID-19#759]
![Screenshot_20200630-222727](https://user-images.githubusercontent.com/67659119/86174224-8c470180-bb21-11ea-8622-3976f76c2cd5.png)

Da oggi la funzione
=IMPORTHTML("https://github.com/pcm-dpc/COVID-19/blob/master/dati-regioni/dpc-covid19-ita-regioni.csv", "table", 1)
non mi funziona più ma da l'errore:
"i contenuti della risorsa all'url specificato hanno superato  la dimensione massima"
Cosa vuol dire?
È un problema della pagina web o di Fogli?
Di fatto non riesco più a caricare i dati Covid sul foglio elettronico ed elaborare dei grafici ad hoc...
Capita anche ad altri?

**Comment by Doc73** [comment]
Io uso IMPORTDATA e non riscontro problemi. Provalo!

**Comment by Fuffo00339958** [comment]
Noto che dal 29/6 la tabella dati è variata, ha due colonne in più: 
| casi_da_sospetto_diagnostico | casi_da_screening |
e naturalmente ha sballato un po' la corretta collocazione dei CASI TOTALI in un foglio Excel

**Comment by umbros** [comment]
Ciao, non è un problema di cambio colonne, è un limite sul numero record, consiglio la soluzione di @Doc73 che ringrazio

**Comment by SilvioCaggia** [comment]
> Io uso IMPORTDATA e non riscontro problemi. Provalo!

Grazie! Ho dovuto revisionare tutto dopo questa modifica (non c'è la colonna vuota all'inizio) ma adesso funziona tutto!

Se volete vedere i miei grafici automatici:

https://docs.google.com/spreadsheets/d/11S6KS8lpYq_rNYdf4uqZhKgmPSmHvG9s7S0O-dD4PH4/edit?usp=drivesdk

**Comment by Doc73** [comment]
@SilvioCaggia Complimenti per i tuoi grafici, molto più belli e articolati dei miei. Me li studierò con calma.

**Comment by SilvioCaggia** [comment]
> @SilvioCaggia Complimenti per i tuoi grafici, molto più belli e articolati dei miei. Me li studierò con calma.

Grazie!
Ogni grafico ha un foglio prima in cui sono estratti i dati tramite una query SQL che si appoggia sui dati estratti da internet in fogli precedenti.
Da worldmeters produco un Grafico a barre della percentuale dei casi sulla popolazione nei vari paesi.
Dai dati regionali della protezione civile produco un sinottico di tutte le informazioni. Puoi scegliere da una lista valori per quale regione.
C'è poi un grafico comparativo in cui si visualizza l'andamento di un dato a scelta nelle varie regioni.
Infine un tentativo di analisi della diversa letalità regionale in relazione alle RSA.

**Comment by Doc73** [comment]
@SilvioCaggia 
Sì, li ho visti! Anche io uso queries, ma sono molto meno bravo di te. Ho comunque creato due file separati, uno per l'Italia e l'altro per il mondo.
Mi vergogno, però, a diffondere i miei grafici. :smile:

**Comment by SilvioCaggia** [comment]
> @SilvioCaggia
> Sì, li ho visti! Anche io uso queries, ma sono molto meno bravo di te. Ho comunque creato due file separati, uno per l'Italia e l'altro per il mondo.
> Mi vergogno, però, a diffondere i miei grafici.

Ho dato accesso in lettura a tutti tramite il link, così non devo autorizzare singolarmente chi mi ha chiesto. Serve poter modificare i parametri (celle colorate di verde) per cui consiglio di farvi una copia per poter scegliere i parametri. Non credo si possa fare in sola lettura

**Comment by Ago1896** [comment]
Io invece continuo ad avere lo stesso problema anche con IMPORTDATA. Questa è la formula: =IMPORTDATA("https://raw.githubusercontent.com/italia/covid19-opendata-vaccini/master/dati/somministrazioni-vaccini-latest.csv")

Possibili soluzioni?

**Comment by Doc73** [comment]
@Ago1896 
Non c'è soluzione: IMPORTDATA ha limiti molto stringenti.
In questi casi, l'unica è ricorrere a scripts

**Comment by Ago1896** [comment]
> @Ago1896
> Non c'è soluzione: IMPORTDATA ha limiti molto stringenti.
> In questi casi, l'unica è ricorrere a scripts

Peccato che non ne so nulla di scripts... In ogni caso sono riuscito a ricavare i dati che volevo tramite Excel e si aggiornano automaticamente ogni 15 minuti. Ora il problema è importare questi dati in Google fogli in modo continuo. Per l'aggiornamento tramite script non c'è problema, solo che non trovo un modo/funzione per importare i dati da excel a fogli.

**Comment by Doc73** [comment]
@Ago1896 
Strumenti --> Editor di Script
e aggiungi qualcosa del genere
```
//Displays an alert as a Toast message
function displayToastAlert(message) {
  SpreadsheetApp.getActive().toast(message, "⚠️ Alert"); 
}

//Import Italy CSV file at a URL into the Google Sheet
function importCSVvaccines() {
  var csvUrl = "https://raw.githubusercontent.com/italia/covid19-opendata-vaccini/master/dati/somministrazioni-vaccini-latest.csv";
  var csvContent = UrlFetchApp.fetch(csvUrl).getContentText();
  var csvData = Utilities.parseCsv(csvContent);
  var sheet = SpreadsheetApp.getActiveSheet();
  sheet.getRange(1, 1, csvData.length, csvData[0].length).setValues(csvData);
  displayToastAlert("The CSV file was successfully imported.");
}
```

**Comment by Ago1896** [comment]
> @Ago1896
> Strumenti --> Editor di Script
> e aggiungi qualcosa del genere
> 
> ```
> //Displays an alert as a Toast message
> function displayToastAlert(message) {
>   SpreadsheetApp.getActive().toast(message, "⚠️ Alert"); 
> }
> 
> //Import Italy CSV file at a URL into the Google Sheet
> function importCSVvaccines() {
>   var csvUrl = "https://raw.githubusercontent.com/italia/covid19-opendata-vaccini/master/dati/somministrazioni-vaccini-latest.csv";
>   var csvContent = UrlFetchApp.fetch(csvUrl).getContentText();
>   var csvData = Utilities.parseCsv(csvContent);
>   var sheet = SpreadsheetApp.getActiveSheet();
>   sheet.getRange(1, 1, csvData.length, csvData[0].length).setValues(csvData);
>   displayToastAlert("The CSV file was successfully imported.");
> }
> ```

"Errore	È stato effettuato un tentativo di eseguire myFunction, ma la funzione è stata eliminata." Bohhh (sono una capra in queste cose èh!)

**Comment by Doc73** [comment]
@Ago1896 
Da me funziona, ma sono 42193 righe, quindi è prossimo ai 50000 che credo siano il limite massimo. CREDO.
Non riesco a capire da dove ti prende questa myFunction
