### ISSUE TITLE
Data non in formato ISO 8601

### ISSUE THREAD

**Issue by alessiosavi** [pcm-dpc/COVID-19#76]
Tipo di issue:

- [ ] Dati mancanti o errati 
- [X] Errore nella documentazione 
- [ ] Errore or mancanza nella dashboard 
- [ ] Problemi di visualizzazione nella dashboard 

## Riassunto

Il formato di data non rispetta lo stadard ISO 8601

**Attesa:**

2020-03-09T14:48:45+01:00
2020-03-09T14:48:45Z

**Attuale:** 

2020-03-09 14:48:45

**Comment by mydozer** [comment]
Penso tuttavia che l'orario disponibile a livello informativo al momento non aggiunga molto. In sostanza è l'ora del giorno in cui il dato è stato aggregato/elaborato ed è sempre 18.00, salvo forse qualche caso raro.

**Comment by aurasphere** [comment]
D'accordo con @mydozer ma alla fine non costa tanto sistemarlo (una replace con una regular expression) e sarebbe meglio seguire uno standard. Se serve una mano sono disponibile.

**Comment by bfabio** [comment]
@alessiosavi There's a [PR open](https://github.com/pcm-dpc/COVID-19/pull/68) for that.

**Comment by alessiosavi** [comment]
Oh, i haven't seen @bfabio. Many thanks.
