### ISSUE TITLE
Note inconsistenti con nuovo Dataset

### ISSUE THREAD

**Issue by Ares1984** [pcm-dpc/COVID-19#760]
Buongiorno, 

il campo "note" nel nuovo dataset (dpc-covid19-ita-andamento-nazionale.json) continua a contenere il riferimento al codice della nota (come il vecchio "note-it" e non il suo contenuto testuale come da specifiche.
Il file note (dpc-covid19-ita-note.csv) invece non contiene piu il riferimento al codice per cui l'accoppiamento al momento risulta impossibile.

**Comment by umbros** [comment]
Ciao @Ares1984 Stiamo allineando i dati secondo la nuova strutturazione delle note #747
