### ISSUE TITLE
Ordinamento regioni

### ISSUE THREAD

**Issue by 123cobloc** [pcm-dpc/COVID-19#761]
Tipo di issue:

- [ ] Dati mancanti o errati 
- [ ] Errore nella documentazione 
- [ ] Errore or mancanza nella dashboard 
- [ ] Problemi di visualizzazione nella dashboard 

- Regione: P.A. Bolzano e P.A. Trento
- Provincia: 

## Riassunto

Negli ultimi due file CSV le due P.A. sono ordinate in base alla P e non in base a B e T, come in tutti i file precedenti.

**Attesa:**

**Attuale:**

**Comment by vi-enne** [comment]
Questa la risposta di @umbros nella issue #747 

> Ciao @rtrunfio, nel processamento dei dati possiamo questi vengono ordinati per regione e codice provincia. Per una completa automazione del sistema un'ordinamento "fisso" è di difficile amministrazione (dovremmo scrivere riga per riga l'ordinamento), pertando sarà così. Capisco che chi usa un foglio elettronico ciò può causare problemi ma dovendo assicurare continuatività al servizio automatizzandolo non possiamo più tenere degli script "hardcoded" ma abbiamo dovuto dinamicizzare il più possibile, l'altro ordinamento è sull'ordinamento regioni fatto per "denominazione regione" (P.A. Bolzano e P.A. Trento sono ordinati in maniera alfabetica). Anche su fogli elettronici però possono essere create automazioni per valore "cella". Magari possiamo supportare nella cosa.

Consigliano di usare il campo codice_regione per fare riferimento alle singole Regioni/PA invece di affidarsi all'ordinamento delle righe.

**Comment by umbros** [comment]
Corretto, grazie @vi-enne #747
