### ISSUE TITLE
Casi nelle Marche oggi

### ISSUE THREAD

**Issue by Rabelaiss** [pcm-dpc/COVID-19#762]
La scheda riepilogativa di ieri riporta nelle Marche 6785 casi totali, mentre oggi riporta 6786 casi totali e 5 nuovi casi invece di 1
https://github.com/pcm-dpc/COVID-19/blob/master/schede-riepilogative/regioni/dpc-covid19-ita-scheda-regioni-20200701.pdf
non ci sono avvisi a riguardo, penso sia un errore

**Comment by umbros** [comment]
Ciao @Rabelaiss oggi sulle Marche c'è una nota:
https://github.com/pcm-dpc/COVID-19/blob/master/note/dpc-covid19-ita-note.csv
https://github.com/pcm-dpc/COVID-19/blob/master/avvisi.md

**01/07/2020** La Regione Marche ha comunicato il seguente ricalcolo: n.4 decessi precedentemente segnalati non risultano classificabili come COVID-19 positivi, la Regione Puglia ha comunicato il seguente ricalcolo: ha eliminato n.1 caso duplicato

**Comment by Rabelaiss** [comment]
@umbros si ma quell'avviso fa riferimento ai decessi, io parlo dei casi
nella scheda alla riga Marche e colonna Incremento casi totali (rispetto al giorno precedente) si legge 5 quando in realtà è 1 dato che oggi i casi totali sono 6786 e ieri erano 6785

**Comment by Rabelaiss** [comment]
@umbros anche per quanto riguarda Bolzano c'è un'anomalia
Sul sito http://www.provincia.bz.it/ si legge che oggi ci sono stati 2 nuovi casi a fronte di 674 tamponi con 2641 casi totali.
Nella scheda riepilogativa (stesso link di prima) si legge invece che i nuovi casi sono 3 a fronte di 674 tamponi e che i casi totali sono 2642.

**Comment by Rabelaiss** [comment]
@umbros l'anomalia dei nuovi casi nella Marche sembra essere presente solamente nella [scheda riepilogativa](https://github.com/pcm-dpc/COVID-19/blob/master/schede-riepilogative/regioni/dpc-covid19-ita-scheda-regioni-20200701.pdf), mentre l'anomalia dei casi totali di Bolzano è presente sia nella scheda riepilogativa sia nel [dpc-covid19-ita-regioni-20200701.csv](https://github.com/pcm-dpc/COVID-19/blob/master/dati-regioni/dpc-covid19-ita-regioni-20200701.csv)

**Comment by umbros** [comment]
Si @Rabelaiss il campo note è quello che le Regioni pubblicano, mentre il dataset note riporta il complessivo delle note riportato da Ministero della salute in un formato più leggibile e sulla base di note non inserite dalle Regioni.

**Comment by Rabelaiss** [comment]
@umbros non capisco la tua risposta, cosa mi sai dire a riguardo di quanto ho detto su marche e bolzano?

**Comment by umbros** [comment]
Che sono i dati comunicati da Ministero della Salute. Comunque ho segnalato la cosa

**Comment by Rabelaiss** [comment]
@umbros scusa se torno sull'argomento, ma c'è una cosa che non mi torna riguardo ai dati delle Marche.
Come sappiamo ieri nelle Marche c'è stato 1 nuovo caso, 0 nuovi decessi e una rimozione di 4 decessi vecchi in quanto non classificabili come covid.
Il totale dei decessi è quindi diminuito da 991 a 987, tuttavia il totale dei casi è aumentato di 1 (da 6785 a 6786).
Ma dalla relazione
`casi = guariti + positivi + deceduti`
segue che rimuovendo 4 deceduti, anche i casi dovrebbe diminuire della stessa quantità, a meno che i deceduti non vengano spostati nei positivi o nei guariti.
I casi totali nella Marche al 30 giugno erano 6785, mentre al 1 luglio erano 6786 (il +1 penso indichi il nuovo caso rilevato ieri), ma per quanto detto mi viene da pensare che i casi totali dovrebbero essere `6785+1-4 = 6782`.
Inoltre, andando a sommare deceduti (987), dimessi_guariti (5551) e totale_positivi (248) di ieri, il risultato è 6786 quindi, dalla relazione precedente, si evince che quei 4 decessi vecchi non sono stati rimossi, ma sono stati spostati nei guariti o nei positivi.
Spero di essere stato chiaro, in caso chiedi pure per dei chiarimenti.
Fammi sapere se il mio ragionamento è corretto oppure sbagliato.
Grazie
