### ISSUE TITLE
Nuovo formato file di note json e testo della nota. Note troncate?

### ISSUE THREAD

**Issue by mydozer** [pcm-dpc/COVID-19#764]
<!--
Tipo di issue:

- [ ] Dati mancanti o errati dpc-covid19-ita-note.json

## Riassunto

Ho trovato nel nuovo file delle note la seguente nota

{
        "data": "2020-06-01T17:00:00",
        "note": "[altre date in fase di caricamento]\"\n2020-06-25T17:00:00,"
    },

**Attesa:**
- non trovare elementi di formattazione del contenuto delle note (ad esempio ritorno a capo \n)
- non trovare contenuti in formato tecnico come la data 2020-06-25T17:00:00
- contenuto informativo che possa essere usato lato presentazione senza ulteriori elaborazioni

Sospetto ci sia stato un troncamento in fase di generazione del file json perché le note sono considerevolmente di meno rispetto a prima.

Grazie infinite per il lavoro che svolgete quotidianamente che ci permette di presentare i dati i modo consistente.

**Comment by umbros** [comment]
Ciao @mydozer no problema su un doppio apice, gestito ora tutto ok
