### ISSUE TITLE
Marche ieri rimossi 4 deceduti ma non 4 casi

### ISSUE THREAD

**Issue by Rabelaiss** [pcm-dpc/COVID-19#765]
Ieri nelle Marche c'è stato 1 nuovo caso, 0 nuovi decessi e una rimozione di 4 decessi vecchi in quanto non classificabili come covid.
Il totale dei decessi è quindi diminuito da 991 a 987, tuttavia il totale dei casi è aumentato di 1 (da 6785 a 6786).
Ma dalla relazione
`casi = guariti + positivi + deceduti`
segue che rimuovendo 4 deceduti, anche i casi dovrebbe diminuire della stessa quantità, a meno che i deceduti non vengano spostati nei positivi o nei guariti (ma da escludere essendo, appunto, morti).
I casi totali nella Marche al 30 giugno erano 6785, mentre al 1 luglio erano 6786 (il +1 immagino sia dovuto al nuovo caso rilevato ieri), ma per quanto detto i casi totali dovrebbero essere `6785+1-4 = 6782` (dove il +1 indica il nuovo caso di ieri, e -4 indica la rimozione di 4 casi).
Inoltre, andando a sommare deceduti (987), dimessi_guariti (5551) e totale_positivi (248) di ieri, il risultato è 6786 quindi, dalla relazione precedente, si evince che quei 4 decessi vecchi non sono stati rimossi, ma sono stati spostati nei guariti o nei positivi.
Il ragionamento è corretto o mi è sfuggito qualcosa?

**Comment by vitop72** [comment]
Il ragionamento è correttissimo.. Penso non dipenda da DPC. 4 mesi e mezzo di epidemia e ancora le regioni comunicano i dati in questo modo. I ricalcoli, i riconteggi, le rielaborazioni, eccetera sono REGOLA e non eccezione.

**Comment by umbros** [comment]
Ciao @Rabelaiss e @vitop72,
il riconteggio è stato effettuato in questo modo:

Le Marche hanno riportato un ricalcolo di -4 decessi e quindi partiva da un totale casi positivi di ieri di 6785 - 4 = 6781
Dai 6781 (totale positivi corretti di ieri) oggi sono arrivati a 6786, che corrisponde ad un incremento di 5 casi positivi in più.

**Comment by Rabelaiss** [comment]
@umbros il GORES ha comunicato 1 solo nuovo caso il 1/7, non 5.
L'errore dei casi totali è presente anche nei pdf della regione stessa, infatti confrontando il [riepilogo del 30/6 ](https://www.regione.marche.it/portals/0/Salute/CORONAVIRUS/DatiGORES/Gores%20gialla%2030062020%20ore%2012.pdf) con [quello del 1/7](https://www.regione.marche.it/portals/0/Salute/CORONAVIRUS/DatiGORES/Gores%20gialla%2001072020%20ore%2012.pdf) si nota come i casi decessi totali siano passati da 991 a 987, mentre i casi totali siano passati da 6785 a 6786 nonostante sia stato segnalato 1 solo caso positivo. 6786 è errato, il numero corretto è 6782 (6785-4+1).

**Comment by Rabelaiss** [comment]
@umbros @vitop72 ho scritto al GORES che gentilmente mi ha risposto risolvendo il dubbio

> Si tratta di 4 casi positivi, poi negativizzati e poi sfortunatamente deceduti per altre cause.

quindi i dati sono corretti
