### ISSUE TITLE
Numero tamponi

### ISSUE THREAD

**Issue by Paulsword** [pcm-dpc/COVID-19#766]
Non vedo note sul numero dei tamponi.
Si dice che Piemonte che dichiara 29405 test, ne abbia fatti 2900 (forse più credibile)
Abbiamo conferme?

Grazie

**Comment by vi-enne** [comment]
Confrontando con la comunicazione regionale, pare un errore di battitura: totale tamponi 425052 e non 452052.

https://www.facebook.com/regione.piemonte.official/photos/pcb.3474221412590680/3474220429257445/?type=3&theater

**Comment by Paulsword** [comment]
Ben detto @vi-enne 
Vorrei però vedere rettifica ufficiale.

**Comment by umbros** [comment]
Ciao, i dati sono stati corretti con la push delle 19:50:
https://github.com/pcm-dpc/COVID-19/commit/50dacb073c5389980086f3592e3fb85e2f7ee5dc

**Comment by RossoDeM** [comment]
> Ciao, i dati sono stati corretti con la push delle 19:50:
> [50dacb0](https://github.com/pcm-dpc/COVID-19/commit/50dacb073c5389980086f3592e3fb85e2f7ee5dc)

Dovete modificare il numero di tamponi anche nella tabella di andamento nazionale e togliere i 27000 tamponi del Piemonte frutto dell'errore di battitura.

Il dato corretto è quindi 5548815 e non 5575815.
E andrebbe rettificato che i tamponi giornalieri non erano 77096 ma 50096, perché molti media avevano sottolineato il gran numero di test effettuati.
