### ISSUE TITLE
Molise incremento tamponi negativo

### ISSUE THREAD

**Issue by Rabelaiss** [pcm-dpc/COVID-19#768]
ll Molise oggi senza un incremento di tamponi pari a -863 ma non c'è nessun avviso in merito

**Comment by Rabelaiss** [comment]
sistemato con il nuovo commit

**Comment by Rabelaiss** [comment]
dpc-covid19-ita-regioni-20200703.csv segna 23262 tamponi
dpc-covid19-ita-regioni-20200704.csv segna 22399 tamponi

**Comment by umbros** [comment]
Si @Rabelaiss c'è stato un errore di inserimento, corretto subito quindi non è stato emesso un avviso
