### ISSUE TITLE
Possibile mancanza dati Basilicata

### ISSUE THREAD

**Issue by 123cobloc** [pcm-dpc/COVID-19#769]
Tipo di issue:

- [x] Dati mancanti o errati 
- [ ] Errore nella documentazione 
- [ ] Errore or mancanza nella dashboard 
- [ ] Problemi di visualizzazione nella dashboard 

- Regione: Basilicata
- Provincia: 

## Riassunto

I dati non presentano variazioni rispetto a quelli di ieri.

**Attesa:**

Aumento quantomeno del numero di tamponi eseguiti.

**Attuale:**

**Comment by Rabelaiss** [comment]
Nell'ultimo bollettino sul sito della [regione basilicata](https://regione.basilicata.it/giunta/site/Giunta/detail.jsp?otype=1012&id=3067266) è scritto che

> Il prossimo aggiornamento è previsto per lunedì 6 luglio, alle ore 12,00 e conterrà anche i dati di domani.

**Comment by umbros** [comment]
Ciao @123cobloc e @Rabelaiss cofermiamo, abbiamo inoltrato nota al Ministero della Salute e siamo in attesa di comunicazioni

**Comment by umbros** [comment]
Ciao @123cobloc e @Rabelaiss dati allineati.
