### ISSUE TITLE
Dati Sud Sardegna

### ISSUE THREAD

**Issue by piersoft** [pcm-dpc/COVID-19#77]
Tipo di issue:

- [X ] Dati mancanti o errati 
- [ ] Errore nella documentazione 
- [ ] Errore or mancanza nella dashboard 
- [ ] Problemi di visualizzazione nella dashboard 

## Riassunto

Credo che i dati per Province qui inseriti:
https://github.com/pcm-dpc/COVID-19/tree/master/dati-province
siano incorretti per la Provincia di Sud Sardegna che accorpa varie ex province.

**Attesa:**

**Attuale:**

**Comment by umbros** [comment]
Grazie della segnalazione @piersoft, i dati che provengono dalle Regioni attraverso il Ministero della Salute sono quelli che riportiamo, attualmente per sud sardegna non risultano casi:
![immagine](https://user-images.githubusercontent.com/4085151/76309765-bf912680-62cd-11ea-88f2-9b64e103e486.png)
