### ISSUE TITLE
Casi totali da diagnosi diminuiscono da giorni in Piemonte?

### ISSUE THREAD

**Issue by SilvioCaggia** [pcm-dpc/COVID-19#770]
**Tipo di richiesta**: --> richiesta di informazione

## Riassunto

Da quando è stato aggiunta la distinzione tra casi totali da diagnosi e da screening, in Piemonte il delta giornaliero dei casi totali da diagnosi è negativo.
Cosa significa?
Che stanno correggendo ogni giorno retroattivamente il numero dei casi da screening?
Questo però inficia completamente il dato del delta giornaliero di casi da diagnosi...

## Interesse pubblico

In Piemonte il dato dei nuovi casi giornalieri da diagnosi ottenuto per differenza con il giorno precedente assume valori negativi che non hanno un senso reale.

**Comment by umbros** [comment]
Confermo @SilvioCaggia abbiamo notificato la cosa al Ministero della Salute e attendiamo info.

**Comment by Paulsword** [comment]
Suggerisco nel frattempo di correggere in base ai dati che la regione riporta qui
https://www.regione.piemonte.it/web/pinforma/notizie/coronavirus-gli-aggiornamenti-dalla-regione-piemonte?fbclid=IwAR3Hu_68zKLVZ7CbLXpe2IWdYdM4oomFjkFsPL8Nzpd2MOBRzv5wRqS3ptQ

**Comment by umbros** [comment]
Ciao, inserita la nota sul Piemonte, si riconferma ricalcolo

**Comment by SilvioCaggia** [comment]
Il problema continua a persistere... Che diavolo stanno facendo in Piemonte?
È impossibile estrarre il dato nazionale per colpa loro...

**Comment by SilvioCaggia** [comment]
Piemonte, Liguria e Puglia, continuano da un mese ad indicare ogni giorno un numero di casi da sospetto diagnostico minore del precedente.
Correggano gli errori una volta al mese, ma non possono correggerli tutti i giorni, da un mese...
