### ISSUE TITLE
Lombardia inverte tracciamento con screening

### ISSUE THREAD

**Issue by Paulsword** [pcm-dpc/COVID-19#771]
Sulla slide di Regione Lombardia il dato scorporato dei nuovi positivi (sospetto diagnostico vs screening) è invertito rispetto a quello in questo repository.
https://www.lombardianotizie.online/coronavirus-casi-lombardia/

Sono 35 + 76 oppure 76 + 35?

**Comment by Paulsword** [comment]
Scusate ma non è proprio un dettaglio. Cambia TOTALMENTE la "lettura" dei dati di oggi.
Urge conferma o correzione!!

**Comment by umbros** [comment]
Comunicata la cosa. Grazie @Paulsword

**Comment by Rabelaiss** [comment]
i dati di ieri sono ancora quelli, novità @umbros ?

**Comment by umbros** [comment]
Ciao, Regione Lombardia tramite Ministero della Salute riporta che i casi delle slide sono dati diversi che loro forniscono, ad es i debolmente positivi sono inclusi nei test sierologici, quindi non sono paragonabili.
I dati riportati sulla piattaforma ISS, sono quelli da prendere in considerazione.
