### ISSUE TITLE
Chiarimento andamento casi_da_sospetto_diagnostico 

### ISSUE THREAD

**Issue by morieri** [pcm-dpc/COVID-19#772]
Buona sera,
dai dati mi sembra di intuire che "casi_da_sospetto_diagnostico" che compare dal 25 giugno, sia un numero cumulativo.
Eppure, da un giorno al successivo questo numero spesso cala.
E' dovuto ad una reinterpretazione dei "casi_da_sospetto_diagnostico" verso i "casi_da_screening" ? 
(la somma dei due risulta sempre pari ai casi totali).

Avete spiegazioni al riguardo?
Grazie

**Comment by Rabelaiss** [comment]
Secondo me le regioni fino al 24 giugno non facevano distinzione tra clinici e screening, poi dal 25 hanno iniziato a scorporare i casi screening dal totale e di giorno in giorno ne trovano altri vecchi da aggiungere al conteggio. Ormai sono rimaste solo Piemonte, Liguria e Puglia che devono mettersi in pari, infatti i nuovi casi da screening comunicati dalle altre regioni sono sempre minori o uguali al numero di nuovi casi

**Comment by morieri** [comment]
Grazie Rabelaiss, 
il ragionamento mi sembra corretto.
Tra l'altro, dal punto di vista epidemiologico e per capire l'andamento sia del monitoraggio che della diffusione dell'infezione, sarebbe ancora più utile se mettessero la stessa distinzione per i tamponi effettuati (sospetto clinico Vs screening) e non solo per i casi positivi.

**Comment by umbros** [comment]
Ciao è un dato che viene raccolto ed è in fase di stabilizzazione dal 24 giugno. Prima non veniva raccolto.
