### ISSUE TITLE
Full Italy Datasheets for Province & Region do not load properly

### ISSUE THREAD

**Issue by MillikenDB1** [pcm-dpc/COVID-19#775]
The columns list does not match the data. Raw Data shows last column is 'notes'. The data set tries to load 'note_it' and 'note_en'. These do not match so it fails

 
#

Type of issue:

- [x] Incorrect or missing data : 
- [ ] Incorrect or missing documentation 
- [ ] Incorrect or missing data in the dashboard 
- [ ] Layout problem in the dashboard 

- Region:
- Province: 

## Summary

**Expected:**

**Actual:**

**Comment by Rabelaiss** [comment]
Do you mind providing the link to the file? Thanks

**Comment by umbros** [comment]
hi @MillikenDB1 , as reported #747 we made some enhancement to datasets, you can use the legacy folder with the old datasets (legacy) until Friday 31/07 ("legacy" directory).
