### ISSUE TITLE
File dpc-covid19-ita-province.csv

### ISSUE THREAD

**Issue by picomiles** [pcm-dpc/COVID-19#777]
Tipo di issue:

- [ ] Dati mancanti o errati 
- [ ] Errore nella documentazione 
- [ ] Errore or mancanza nella dashboard 
- [X] Problemi di visualizzazione nella dashboard 

- Regione:
- Provincia: 

## Riassunto

Nel file in oggetto convive una doppia descrizione per i dati di cui non è stata ancora definita la provincia; pur essendo caratterizzati dallo stesso codice_provincia, la descrizione ("denominazione_provincia") fino al 24 Giugno è "In fase di definizione/aggiornamento" e, a partire dal 25 Giugno, "In fase di definizione".  Nell'aggregare i dati per "denominazione_provincia" nell'ambito di una regione (volendo mantenere un ordinamento alfabetico, per esempio) questo genera due aggregazioni diverse a fronte dello stesso codice. 

**Attesa:**

La richiesta: è possibile avere una sola delle due descrizioni in modo da evitare il problema sopra descritto?

**Comment by umbros** [comment]
Ciao,
grazie per la segnalazione, tutti i file sono stati allineati e corretti.

**Comment by picomiles** [comment]
Grazie

**Comment by umbros** [comment]
Grazie a te

**Comment by picomiles** [comment]
Scusa Umberto, ma con i dati di oggi è ricomparsa "In fase di definizione" invece che "In fase di definizione/aggiornamento" e il problema si è pertanto ripresentato
