### ISSUE TITLE
ID per paziente (anonimizzato)

### ISSUE THREAD

**Issue by dbaroncelli** [pcm-dpc/COVID-19#78]
Sarebbe molto utile avere un record per paziente, anonimizzato, per permettere a tutti noi di fare analisi più approfondite e contribuire con modelli predittivi.

I campi utili sarebbero:
- ID univoco
- sesso
- età
- provincia
- stato (in isolamento, ricoverato con sintomi, in terapia intensiva, guarito, deceduto)
- data risultato test positivo
- data guarigione/decesso

L'accesso a questo tipo di dati darebbe un senso ancora più compiuto al virtuoso proposito di Open Data, in quanto riuscirebbe a innescare la condivisione di preziosi contributi analitici da parte di tutta la community.

Credo che sulla base del FOIA (Freedom Of Information Act) italiano, e della fase di criticità che sta vivendo il nostro paese, l'apertura a questi dati dovrebbe essere garantita.

Questi dati vengono già raccolti a livello locale dai vari quotidiani, ma servirebbe una consistenza univoca, open data e nazionale.

**Comment by mydozer** [comment]
Avere l'indicazione se il paziente era affetto da patologie gravi pregresse permetterebbe un'analisi ancora più approfondita.

**Comment by umbros** [comment]
@dbaroncelli @mydozer allo stato attuale i dati che rilasciamo sono quelli utili al monitoraggio informativo; non è una questione di FOIA ma una questione di tempi e processi per la gestione di tali moli di dati.
