### ISSUE TITLE
Size Dataset province (JSON) x2

### ISSUE THREAD

**Issue by fabriziomiano** [pcm-dpc/COVID-19#780]
Ciao, innanzitutto grazie per il lavoro che state svolgendo. 

Tipo di issue:

- [X] Problema coi dati in dpc-covid19-ita-province.json

## Riassunto

Sembrerebbe che in questo dataset ci siano il doppio dei dati rispetto a quelli che ci dovrebbero essere. 
In particolare, ci si aspetterebbe che il singolo dato sia univocamente identificato dalla tripla (data, regione, provincia) 
Tuttavia, e' facile verificare che, ad esempio, nel caso della tripla ("2020-02-24T18:00:00", "Sicilia", "Catania"), questo dato e' presente due volte: all'elemento 100 e all'elemento 19122.

Spero di non essermi perso qualcosa. In tal caso chiedo scusa in anticipo

**Comment by umbros** [comment]
Grazie @fabriziomiano per la segnalazione, corretto il dataset.

Umberto

**Comment by fabriziomiano** [comment]
Grandissimi.
Grazie ancora. 
Buon fine settimana
