### ISSUE TITLE
mancanza del file pdf  del 9/7/2020 

### ISSUE THREAD

**Issue by giocabilo** [pcm-dpc/COVID-19#781]
Tipo di issue:

- [ ] Dati mancanti o errati 
- [ ] Errore nella documentazione 
- [x ] Errore or mancanza nella dashboard 
- [ ] Problemi di visualizzazione nella dashboard 

- Regione:
- Provincia: 

## Riassunto

mancanza del file pdf relativo alle riepilogo delle regioni  9/7/2020 nella directory
COVID-19/schede-riepilogative

**Attesa:**

dpc-covid19-ita-scheda-regioni-20200709.pdf
**Attuale:** 
nessuna

**Comment by umbros** [comment]
Caricato. Grazie della segnalazione @giocabilo
