### ISSUE TITLE
Marche ieri 6812 casi totali, oggi 6811 ma nessun avviso a riguardo

### ISSUE THREAD

**Issue by Rabelaiss** [pcm-dpc/COVID-19#782]
Marche ieri 6812 casi totali, oggi 6811 ma nessun avviso a riguardo

**Comment by Rabelaiss** [comment]
nel file dpc-covid19-ita-province-20200719.csv per la provincia di Fermo è riportato l'avviso 

> n.1 caso di ieri risulta essere negativo

tuttavia nel file dpc-covid19-ita-scheda-regioni-20200719.pdf compare il seguente avviso

> La Regione Molise segnala che n.1 caso del 18 luglio riusulta essere negativo confermato.

ieri il molise ha registrato  nuovi casi, quindi penso che per errore nell'avviso abbiano scritto Molise invece di Marche

**Comment by umbros** [comment]
Ciao @Rabelaiss,
le note sono state caricate e comprendono anche avviso della Regione Basilicata:

"La Regione Marche segnala che 1 caso del 18 luglio riusulta essere negativo confermato, la Regione Basilicata segnala che nella giornata di domani comunicherà il numero esatto dei casi testati e dei tamponi effettuati". L'avviso è su Regione Molise. Chiesto conferma a Ministero della Salute.
