### ISSUE TITLE
Casi di importazione

### ISSUE THREAD

**Issue by Rabelaiss** [pcm-dpc/COVID-19#784]
Negli ultimi giorni i casi di importazione, ossia cittadini di nazionalità estera risultati positivi al tampone dopo l'arrivo nel nostro paese, stanno incidendo per una buona parte sui nuovi casi giornalieri in Italia.

Molte persone che guardano i bollettini che faccio a partire dai vostri dati, mi stanno chiedendo di distinguere tra casi di cittadini italiani e casi di importazione. Di solito quest'ultima informazione è comunicata da alcune regioni, ad esempio Lazio, Veneto, Emilia-Romagna, e oggi anche la Basilicata la quale ha comunicato che su 36 nuovi casi 35 sono di importazione.

Questo dato aiuterebbe ulteriormente a fare chiarezza sull'andamento del contagio in Italia.
@umbros avevate già pensato anche voi a questa possibilità? Ci sono notizie a riguardo dal Ministero della Salute?
Vi ringrazio

**Comment by vi-enne** [comment]
> Negli ultimi giorni i casi di importazione, ossia cittadini di nazionalità estera risultati positivi al tampone dopo l'arrivo nel nostro paese, stanno incidendo per una buona parte sui nuovi casi giornalieri in Italia.
> 
> Molte persone che guardano i bollettini che faccio a partire dai vostri dati, mi stanno chiedendo di distinguere tra casi di cittadini italiani e casi di importazione. Di solito quest'ultima informazione è comunicata da alcune regioni, ad esempio Lazio, Veneto, Emilia-Romagna, e oggi anche la Basilicata la quale ha comunicato che su 36 nuovi casi 35 sono di importazione.
> 
> Questo dato aiuterebbe ulteriormente a fare chiarezza sull'andamento del contagio in Italia.
> @umbros avevate già pensato anche voi a questa possibilità? Ci sono notizie a riguardo dal Ministero della Salute?
> Vi ringrazio

Mi intrometto perche' l'idea e' interessante, ma credo che una definizione chiara di caso di importazione sia ancora mancante.

E' un caso di importazione un cittadino di stato estero che si contagia in Italia?
E' un caso di importazione un cittadino di stato estero residente in Italia che si contagia in Italia?
E' un caso di importazione un cittadino italiano che si contagia all'estero ma viene diagnosticato al suo ritorno in Italia?

Che ne pensate?

**Comment by Rabelaiss** [comment]
@vi-enne cosa intendi con "cittadino di stato estero residente in Italia" ? Secondo me

caso di importazione = persona con residenza non italiana risultata positiva al tampone in italia

**Comment by vi-enne** [comment]
> @vi-enne cosa intendi con "cittadino di stato estero residente in Italia" ? Secondo me
> 
> caso di importazione = persona con residenza non italiana risultata positiva al tampone in italia

Ad esempio, la regione Lazio non specifica la residenza di quelli che chiama casi di importazione, ma si basa solo sulla cittadinanza del soggetto.
Molti dei contagiati della comunità del Bangladesh sono possibilmente residenti in Italia.

Ancora, il caso dei richiedenti asilo nel complesso della CRI a Jesolo: molti si trovavano in Italia da mesi (il caso 0 da sei mesi). Io li considererei a tutti gli effetti "residenti".

**Comment by umbros** [comment]
Ciao, allo stato attuale non è gestita l'informazione richiesta

**Comment by vi-enne** [comment]
Nell'[ultimo report ISS](http://www.quotidianosanita.it/allegati/allegato518309.pdf) sono segnalati i casi importati in Tabella 2.
Non ho ben capito a quando siano aggiornati, (ci sono varie date nel documento) ma pare al 7 luglio.

A titolo di esempio:
Calabria: importati 7 su 20
Lazio: importati 17 su 88 casi
Veneto: importati 21 su 251 casi

Pare che intendano come importati se hanno contratto l'infezione in un'altra Regione o Stato Estero.
