### ISSUE TITLE
Errore alla riga 3132 del file dpc-covid19-ita-regioni.csv

### ISSUE THREAD

**Issue by Rabelaiss** [pcm-dpc/COVID-19#785]
La riga 3132 del file [dpc-covid19-ita-regioni.csv](https://raw.githubusercontent.com/pcm-dpc/COVID-19/3c575bec7a64427fc8ce2775eff123778ca6fbcb/dati-regioni/dpc-covid19-ita-regioni.csv) contiene un unico carattere, ossia "
la riga precedente termina con "Sono stati sottratti 2 positivi erroneamente conteggiati nei giorni precedenti
è quindi evidente che per errore la " conclusiva è finita nella riga successiva

**Comment by umbros** [comment]
Corretto, grazie @Rabelaiss
