### ISSUE TITLE
Errore Dato Provinciale Bolzano

### ISSUE THREAD

**Issue by DavideMagno** [pcm-dpc/COVID-19#786]
Tipo di issue:

- [X] Dati mancanti o errati 
- [ ] Errore nella documentazione 
- [ ] Errore or mancanza nella dashboard 
- [ ] Problemi di visualizzazione nella dashboard 

- Regione: Bolzano
- Provincia: Bolzano

## Riassunto

Sul file Regionale il numero totale di positivi non cambia da ieri ed è pari a 2685, mentre sul file Provinciale c'è un calo da 2685 a 2658. Sembrerebbe esserci un errore di input con le due cifre invertite.

**Attesa:**

Mi aspetto che il file Provinciale mostri 2685

**Attuale:** 

Il file Provinciale per Bolzano mostra 2658 positivi

**Comment by umbros** [comment]
Ciao @DavideMagno,
il dato è stato corretto: https://github.com/pcm-dpc/COVID-19/commit/e39f30397ef080aade976182d9f86be2f4c167b3
