### ISSUE TITLE
Record ripetuto in andamento nazionale

### ISSUE THREAD

**Issue by emazep** [pcm-dpc/COVID-19#787]
L'ultimo record (quello relativo alla giornata di oggi) in:
https://github.com/pcm-dpc/COVID-19/blob/master/dati-andamento-nazionale/dpc-covid19-ita-andamento-nazionale.csv

è ripetuto 8 volte.

**Comment by giova86** [comment]
ultimo record ripetuto

**Comment by umbros** [comment]
Corretto grazie.
