### ISSUE TITLE
Proposta aggiornamento Formato dei Dati

### ISSUE THREAD

**Issue by maxdevblock** [pcm-dpc/COVID-19#789]
Buongiorno. Mille grazie ancora per il servizio che date!

Proposta di aggiornamento informazioni formato dati per includere i nuovi campi cumulativi `casi_da_sospetto_diagnostico` e `casi_da_screening`.

https://github.com/pcm-dpc/COVID-19/blob/master/dati-andamento-covid19-italia.md#andamento-nazionale

| Nome campo                  | Descrizione                       | Description                            | Formato                       | Esempio             |
|-----------------------------|-----------------------------------|----------------------------------------|-------------------------------|---------------------|
| **totale_casi**                 | Totale casi positivi  (casi da sospetto diagnostico + casi da screening)            | Total amount of positive cases         | Numero                        | 3                   |

**Comment by umbros** [comment]
Ciao @maxdevblock i due valori di norma, devono essere due numeri le cui somme danno totale casi, essendo un campo nuovo allo stato attuale è possibile che la somma non sia esatta rispetto al numero del totale casi. Grazie comunque per il contributo
