### ISSUE TITLE
Differenza dati WHO

### ISSUE THREAD

**Issue by stormsson** [pcm-dpc/COVID-19#79]
**Tipo di richiesta**:
 richiesta di informazione

## Riassunto

Complimenti per l'iniziativa.

I dati sul sito della WHO (https://www.who.int/emergencies/diseases/novel-coronavirus-2019/situation-reports, https://www.who.int/docs/default-source/coronaviruse/situation-reports/20200309-sitrep-49-covid-19.pdf?sfvrsn=70dabe61_4 ) differiscono da quelli presenti nel presente repo.

Es: al 9 Marzo la WHO indica 7375 casi, il repository 7985  (https://github.com/pcm-dpc/COVID-19/blob/master/dati-andamento-nazionale/dpc-covid19-ita-andamento-nazionale-20200309.csv)

- Quale delle 2 serie dati è quella corretta ? 
- c'è una causa a questa discrepanza ?

## Interesse pubblico

Identificare il valore corretto di contagi

**Comment by umbros** [comment]
@stormsson, la serie corretta, per quanto riguarda l'Italia, è quella rilasciata su questo repository che contiene i dati ufficiali che vengono comunicati dal Dipartimento della Protezione Civile. La discrepanza può dipendere dall'orario in cui i dati vegono comunicati a WHO. Comunque grazie per la segnalazione e vedremo di gestire questa cosa con Ministero della Salute e WHO.
