### ISSUE TITLE
errore nel file dpc-covid19-ita-regioni.csv

### ISSUE THREAD

**Issue by Rabelaiss** [pcm-dpc/COVID-19#790]
la riga 3215 del file [dpc-covid19-ita-regioni.csv](https://raw.githubusercontent.com/pcm-dpc/COVID-19/e59e227c087928f082b3c9a1af3ace72193b8428/dati-regioni/dpc-covid19-ita-regioni.csv) è errata

`data,stato,codice_regione,denominazione_regione,lat,long,ricoverati_con_sintomi,terapia_intensiva,totale_ospedalizzati,isolamento_domiciliare,totale_positivi,variazione_totale_positivi,nuovi_positivi,dimessi_guariti,deceduti,casi_da_sospetto_diagnostico,casi_da_screening,totale_casi,tamponi,casi_testati,note`

**Comment by umbros** [comment]
Corretto, grazie @Rabelaiss
