### ISSUE TITLE
Inconsistenza di formato sul campo "note"

### ISSUE THREAD

**Issue by estorti** [pcm-dpc/COVID-19#791]
Tipo di issue:

- [X ] Dati mancanti o errati nei dataset nazionali, regionali, provinciali relativamente al campo "note"

## Riassunto

A seguito del cambio di formato, in base a quanto leggo le note dovrebbero essere rappresentate testualmente. Tuttavia al momento coesistono il vecchio (codici) ed il nuovo formato (testo) nei dataset:

- andamento nazionale: sono presenti soltanto note con codici
- andamento regionale: sono presenti codici fino al 24 giugno, e note testuali successivamente
- andamento provinciale: come per i dati regionali.

**Attesa:**

Dato che i codici delle note non sono più disponibili (se non nella dir _legacy_, che non sarà più mantenuta dopo il 31/07), proporrei di sostituire nei dataset tutti i codici delle note con il loro testo esteso, per garantire l'interpretabilità dei dati passati.

**Comment by umbros** [comment]
I dati sono in fase di riconteggio da parte del Ministero della Salute #793
