### ISSUE TITLE
Incongruenza Nuovi Casi VdA

### ISSUE THREAD

**Issue by vi-enne** [pcm-dpc/COVID-19#792]
Tipo di issue:

- [x] Dati mancanti o errati 
- [ ] Errore nella documentazione 
- [ ] Errore or mancanza nella dashboard 
- [ ] Problemi di visualizzazione nella dashboard 

- Regione:
- Provincia: 

## Riassunto
Nella [scheda riepilogativa odierna](https://github.com/pcm-dpc/COVID-19/blob/master/schede-riepilogative/regioni/dpc-covid19-ita-scheda-regioni-latest.pdf) la Valle d'Aosta segnala 10 nuovi casi in Isolamento ma 0 nuovi positivi. Un'evidente incongruenza.

L'errore si riscontra anche nelle tabelle regionali in formato csv.

**Attesa:** Incremento casi totali VdA: 10

**Attuale:** Incremento casi totali VdA: 0

**Comment by Rabelaiss** [comment]
errori anche per bolzano e sicilia segnalati qui #793

**Comment by umbros** [comment]
#793
