### ISSUE TITLE
La Sicilia passa dai 3196 casi di ieri a 3215 casi di oggi (+19) ma nella tabella del ministero della salute appare +0. Errori anche per Bolzano e Valle d'Aosta.

### ISSUE THREAD

**Issue by Rabelaiss** [pcm-dpc/COVID-19#793]
La Sicilia passa dai 3196 casi di ieri a 3215 casi di oggi (+19) ma nella [tabella del ministero della salute](https://github.com/pcm-dpc/COVID-19/blob/master/schede-riepilogative/regioni/dpc-covid19-ita-scheda-regioni-20200728.pdf) appare 0.

Negli avvisi in basso non c'è scritto niente a riguardo.

Inoltre, sempre nella stessa tabella, negli avvisi si legge Bolzano "oggi + 2 nuovi casi di nuovi positivi rispetto al giorno precedente" eppure nella tabella compare 0.

Infine, la Valle d'Aosta passa da 1196 casi di ieri a 1206 di oggi ma nella tabella compare 0, anche in questo caso nessun avviso a riguardo.

**Comment by umbros** [comment]
Ci sono dei riconteggi del Ministero della salute, attendiamo.

**Comment by umbros** [comment]
Dati aggiornati.

**Comment by Rabelaiss** [comment]
@umbros  grazie, ma quindi i decessi delle ultime 24 ore in italia sono 12 o 11 ?
