### ISSUE TITLE
Campo "nuovi_positivi" nelle tabelle regioni inattendibile

### ISSUE THREAD

**Issue by iguandroid** [pcm-dpc/COVID-19#794]
Tipo di issue:

- [x] Dati mancanti o errati >>>> tabelle REGIONI

- Regione: chissà quali e quante...
- Provincia:  

## Riassunto

Caso #793 chiuso in modo alquanto sbrigativo e prematuro.

Totale casi ad oggi: 246488 (sommando "totale casi" di tutte le province o di tutte le regioni sui file odierni)
Totale casi ad ieri: 246286 (sommando "totale casi" di tutte le province o di tutte le regioni sui file di ieri)
Delta risultante (oggi-ieri): 202

Somma risultante oggi per "nuovi_positivi" di tutte le regioni (prima di issue #793): 181
Somma risultante oggi per "nuovi_positivi" di tutte le regioni (dopo chiusura di issue #793): 212

E' evidente che qualcosa continua a non TORNARE.

E sarebbe simpatico che prima di chiudere un incidente verificaste di non averne appena innescato un altro.

Peraltro questo "caso odierno" apre un problema più vasto, visto che a ben vedere simili discrepanze erano presenti anche nei giorni scorsi.

Totale casi al 27 Luglio: 246286 (sommando "totale casi" di tutte le province o di tutte le regioni a tale data)
Totale casi dal 26 Luglio: 246118 (sommando "totale casi" di tutte le province o di tutte le regioni a tale data)
Delta dei citati valori: 168
Somma dei "nuovi_positivi" per il 27 Luglio: 170

Totale casi dal 26 Luglio: 246118 (sommando "totale casi" di tutte le province o di tutte le regioni a tale data)
Totale casi dal 25 Luglio: 245864 (sommando "totale casi" di tutte le province o di tutte le regioni a tale data)
Delta dei citati valori: 254
Somma dei "nuovi_positivi" per il 26 Luglio: 255

Totale casi dal 25 Luglio: 245864 (sommando "totale casi" di tutte le province o di tutte le regioni a tale data)
Totale casi dal 24 Luglio: 245590 (sommando "totale casi" di tutte le province o di tutte le regioni a tale data)
Delta dei citati valori: 274
Somma dei "nuovi_positivi" per il 25 Luglio: 275

Mi fermo qua.

**Attesa:**

Sarebbe apprezzato che almeno i file per regione omnicomprensivi (dpc-covid19-ita-regioni.csv) potessero essere sistemati con valori CONGRUENTI per l'intera serie storica (naturalmente sarebbe opportuno intervenire anche sui giornalieri).

In sostanza il campo "nuovi_positivi" o lo fornite corretto, oppure lasciate perdere e ognuno se lo calcolerà, come accadeva all'inizio!

Darcelo precalcolato, è cosa graditissima a condizione che sia un valore corretto.
Si osservi che mentre alcuni degli esempi che ho fornito implicano scostamenti di una o due unità, lo scostamento nella circostanza odierna era nell'ordine del 10% (prima di issue #793) ed è tuttora di circa il 5% (dopo la chiusura di issue #793 

**Attuale:**

**Comment by Rabelaiss** [comment]
Non mi sembra che nella tua analisi abbia tenuto conto dei riconteggi segnalati negli avvisi.
Ad esempio oggi Bolzano ha rimosso 10 casi, dunque i casi totali di ieri diventano 246276 invece di 246286, e dunque il delta è 212.
Analogamente, ieri la Sardegna ha rimosso 2 casi, e correggendo i dati il delta risulta 170.

Per ognuna di queste correzioni aggiungo una riga di codice nel mio programma, in modo che il risultato finale sia quello corretto

**Comment by iguandroid** [comment]
Beh... allora cambiate la definizione di "nuovi_positivi" nelle documentazione, perché è evidentemente inappropriata.

(cit.: "totale_casi giorno corrente - totale_casi giorno precedente")

**Comment by NeverWise** [comment]
Stesso problema per quanto rigurada l'Emilia-Romagna. Urge un chiarimento.

**Comment by umbros** [comment]
@iguandroid @NeverWise tutti i chiarimenti vengono definiti dalle Regioni e Ministero della Salute in note. Lato nostro se notiamo problematiche puntiamo ovviamente a risolverlo. Vi invito quindi a contemplate note come dice @Rabelaiss quando si notano incoerenze sui dati. Grazie

**Comment by Rabelaiss** [comment]
@iguandroid il problema con i riconteggi è che non viene quasi mai comunicata la data a cui risalgono i casi rimossi, quindi non possiamo sapere i dati di quanti giorni passati dobbiamo andare a modificare.
