### ISSUE TITLE
RL oggi

### ISSUE THREAD

**Issue by franaussie** [pcm-dpc/COVID-19#797]
Rl dichiara dei sierologici. Nella tabella non ci sono un quanto il numero è identico a quello di ieri. Risultano tutti imputati a sospetto diagnostico. C’è un errore per caso? https://www.lombardianotizie.online/coronavirus-casi-lombardia/

**Comment by Rabelaiss** [comment]
penso di si, apsettiamo risposta da @umbros

**Comment by umbros** [comment]
Ciao, si conferma il dato del Ministero della Salute.
