### ISSUE TITLE
FIELD17 nei JSON regionali del 5 Marzo 2020

### ISSUE THREAD

**Issue by pinoli** [pcm-dpc/COVID-19#8]
Salve e grazie per i dati.
Sto lavorando con il JSON a livello regionale, e ho notato che i record con data uguale a 05/03/2020 hanno un campo in più rispetto agli altri, con chiave **FIELD17** e valori non nulli in diversi casi.

Posso chiedervi a cosa corrisponde questo campo?

Grazie.

**EDIT**: solo il record del 5 Marzo ha FIELD17

**Comment by sabas** [comment]
Deriva dal fatto che nel csv corrispondente c'è una colonna in più senza nome header
https://github.com/pcm-dpc/COVID-19/blob/master/dati-regioni/dpc-covid19-ita-regioni-20200305.csv

**Comment by umbros** [comment]
Corretto. Grazie della segnalazione
