### ISSUE TITLE
Parliamoci chiaro

### ISSUE THREAD

**Issue by colibri17** [pcm-dpc/COVID-19#80]
Ragazzi parliamoci chiaramente. Qui per fare qualcosa di veramente utile occorrerebbe avere i dati raw a livello di singola persona: 

- dove è stato negli ultimi giorni e cosa ha fatto (dati dai cellulari = dati google + dati chiamate) 
- quale è la sua rete sociale (Facebook, Instagram)
- quale è la sua rete famigliare e dove abita (dati anagrafe)
- quale è la sua storia clinica (dati del sistema sanitario)

Allora si che veramente la data science può dare un aiuto forte al problema. Allora si che tracci l'evoluzione del contagio con precisione e fai modelli di rischio estremamente efficaci.

Abbiamo problemi di privacy? Benissimo, che si crei una task force di 50 persone, ai quali si fa firmare col sangue 10 NDA, ma che abbiamo accesso a ogni cosa possibile e immaginabile.

Qui si tratta di SALVARE DELLE VITE

**Comment by umbros** [comment]
@colibri17 scusami ma è offtopic.
