### ISSUE TITLE
Numero tamponi ER al 31/7 errato 

### ISSUE THREAD

**Issue by vecchionico** [pcm-dpc/COVID-19#800]
Tipo di issue:

- [X] Dati mancanti o errati in dpc-covid19-ita-regioni.csv
- Regione: Emilia-Romagna

## Riassunto

Il numero di tamponi effettuati al giorno 31/7 è 655.330 e non 665.330 come riportato. Cfr.: https://www.regione.emilia-romagna.it/notizie/attualita/covid-aggiornamento-2107

**Comment by umbros** [comment]
@vecchionico c'è stato un problema tecnico sui sistemi del Ministero. Li stiamo comunque qui, tra poco ci sarà una commit correttiva. La cosa è stata comunque comunicata nelle note che ora saranno comunque riscritte.
