### ISSUE TITLE
Data errata nelle note relative al 31/07

### ISSUE THREAD

**Issue by 123cobloc** [pcm-dpc/COVID-19#801]
Tipo di issue:

- [ ] Dati mancanti o errati 
- [ ] Errore nella documentazione 
- [ ] Errore or mancanza nella dashboard 
- [ ] Problemi di visualizzazione nella dashboard 

- Regione:
- Provincia: 

## Riassunto

**Attesa:**

2020-07-31

**Attuale:**

2020-03-31

**Comment by umbros** [comment]
Corretto, grazie @123cobloc
