### ISSUE TITLE
Per favore aggiungere il totale dei casi testati per screening in "/dati-json/dpc-covid19-ita-andamento-nazionale.json" 

### ISSUE THREAD

**Issue by marinimau** [pcm-dpc/COVID-19#802]
Tipo di issue:

- [x] Dati mancanti o errati 
- [ ] Errore nella documentazione 
- [ ] Errore or mancanza nella dashboard 
- [ ] Problemi di visualizzazione nella dashboard 

- Regione: -
- Provincia: -

## Riassunto

**Attesa:**

Per favore aggiungere il totale dei casi testati per screening in "/dati-json/dpc-covid19-ita-andamento-nazionale.json" 

Totale casi testati (solo screening)

**Attuale:**

**Comment by umbros** [comment]
Ciao,
il dato è sempre presente ma parte da luglio

{
        "data": "2020-08-03T17:00:00",
        "stato": "ITA",
        "ricoverati_con_sintomi": 734,
        "terapia_intensiva": 41,
        "totale_ospedalizzati": 775,
        "isolamento_domiciliare": 11699,
        "totale_positivi": 12474,
        "variazione_totale_positivi": 18,
        "nuovi_positivi": 159,
        "dimessi_guariti": 200589,
        "deceduti": 35166,
        "casi_da_sospetto_diagnostico": 222891,
        **"casi_da_screening": 25338,**
        "totale_casi": 248229,
        "tamponi": 6940801,
        "casi_testati": 4131535,
        "note": ""
    }

**Comment by marinimau** [comment]
Buonasera,
Innanzitutto ringrazio per la risposta. 
Chiedo scusa se non sono stato preciso, provo a spiegarmi meglio: quello che chiedevo è il numero di individui distinti che sono stati sottoposti alla campagna di screening (a prescindere dall'esito del test). Il valore che Lei mi ha indicato presumo si riferisca alla parte di questi che poi è risultata positiva. Mi corregga se sbaglio.

**Comment by umbros** [comment]
Ciao @marinimau diamoci pure del tu :), 
purtroppo questi dati non sono presenti, potrebbe essere utile totale campioni o casi testati?

**Comment by marinimau** [comment]
Allora @umbros, direi di no. Quello che intendevo fare era una stima (magari con diversi intervalli di confidenza) del numero di possibili positivi sull'intera popolazione.  Il problema è che tra i casi testati ci sono tanti individui sottoposti al test per sospetto diagnostico, il campione non sarebbe abbastanza rappresentativo.
