### ISSUE TITLE
Riga 3451 errata nel file dpc-covid19-ita-regioni.csv

### ISSUE THREAD

**Issue by Rabelaiss** [pcm-dpc/COVID-19#805]
La riga 3451 del file [dpc-covid19-ita-regioni.csv](https://raw.githubusercontent.com/pcm-dpc/COVID-19/master/dati-regioni/dpc-covid19-ita-regioni.csv) contiene solamente il carattere "

Errore analogo al #785

**Comment by umbros** [comment]
corretto, grazie @Rabelaiss
