### ISSUE TITLE
Incremento "totale casi" in "attuali positivi" nella nuova UI della dashboard

### ISSUE THREAD

**Issue by MarioMarietto** [pcm-dpc/COVID-19#808]
Tipo di issue:

- [ ] Dati mancanti o errati 
- [ ] Errore nella documentazione 
- [ ] Errore or mancanza nella dashboard 
- [x] Problemi di visualizzazione nella dashboard 

## Riassunto

Nella nuova UI della dashboard, viene indicato un incremento di 552 positivi in "Attuali positivi" anzichè in "Totale casi".

**Attesa:**

L'incremento degli "Attuali positivi" dovrebbe essere 230, mentre in "Totale casi" ci dovrebbe essere l'incremento di 552 positivi.

**Comment by umbros** [comment]
Ciao @MarioMarietto grazie della segnalazione, ci stavamo lavorando.
