### ISSUE TITLE
Invalid GeoJSON

### ISSUE THREAD

**Issue by mazinthebox** [pcm-dpc/COVID-19#81]
**Richiesta:**
Assistenza sui dati forniti

**File:**
Il seguente file [dpc-covid19-ita-aree.geojson](https://github.com/pcm-dpc/COVID-19/blob/master/aree/geojson/dpc-covid19-ita-aree.geojson) presenta degli errori di formattazione che ne impediscono l'elaborazione.

**Informazioni aggiuntive:**
**JS Console:** Uncaught SyntaxError: Unexpected token ':'
**Riga:** data/aree/geojson/dpc-covid19-ita-aree.geojson:1

**Informazioni di validazione:**
_Line 2: Polygons and MultiPolygons should follow the right-hand rule
Line 3: Polygons and MultiPolygons should follow the right-hand rule
Line 4: Polygons and MultiPolygons should follow the right-hand rule
Line 5: Polygons and MultiPolygons should follow the right-hand rule
Line 6: Polygons and MultiPolygons should follow the right-hand rule
Line 7: Polygons and MultiPolygons should follow the right-hand rule
Line 8: Polygons and MultiPolygons should follow the right-hand rule
Line 9: Polygons and MultiPolygons should follow the right-hand rule
Line 10: Polygons and MultiPolygons should follow the right-hand rule
Line 11: Polygons and MultiPolygons should follow the right-hand rule
Line 12: Polygons and MultiPolygons should follow the right-hand rule
Line 13: Polygons and MultiPolygons should follow the right-hand rule
Line 14: Polygons and MultiPolygons should follow the right-hand rule
Line 15: Polygons and MultiPolygons should follow the right-hand rule
Line 16: Polygons and MultiPolygons should follow the right-hand rule
Line 17: Polygons and MultiPolygons should follow the right-hand rule
Line 18: Polygons and MultiPolygons should follow the right-hand rule
Line 19: Polygons and MultiPolygons should follow the right-hand rule
Line 20: Polygons and MultiPolygons should follow the right-hand rule
Line 21: Polygons and MultiPolygons should follow the right-hand rule
Line 22: Polygons and MultiPolygons should follow the right-hand rule
Line 23: Polygons and MultiPolygons should follow the right-hand rule
Line 24: Polygons and MultiPolygons should follow the right-hand rule
Line 25: Polygons and MultiPolygons should follow the right-hand rule
Line 26: Polygons and MultiPolygons should follow the right-hand rule
Line 27: Polygons and MultiPolygons should follow the right-hand rule
Line 28: Polygons and MultiPolygons should follow the right-hand rule
Line 29: Polygons and MultiPolygons should follow the right-hand rule
Line 30: Polygons and MultiPolygons should follow the right-hand rule
Line 31: Polygons and MultiPolygons should follow the right-hand rule
Line 32: Polygons and MultiPolygons should follow the right-hand rule
Line 33: Polygons and MultiPolygons should follow the right-hand rule
Line 34: Polygons and MultiPolygons should follow the right-hand rule
Line 35: Polygons and MultiPolygons should follow the right-hand rule
Line 36: Polygons and MultiPolygons should follow the right-hand rule
Line 37: Polygons and MultiPolygons should follow the right-hand rule_

**Comment by michelesanges** [comment]
Buongiorno,
la stessa cosa succede con tutti gli altri file geojson. Per verificarlo,
provate a trascinarli all'interno di questo sito: http://geojson.io/

*Michele Sanges*


Il giorno mar 10 mar 2020 alle ore 10:11 Giuseppe <notifications@github.com>
ha scritto:

**Comment by umbros** [comment]
@mazinthebox i file geojson, che sono stati aggiornati ora, sono leggibili da geojson.io.
![immagine](https://user-images.githubusercontent.com/4085151/76309137-6d9bd100-62cc-11ea-9419-6e1b6089a3e7.png)

**Comment by AlessandroAnnini** [comment]
Hi @umbros, why is this was closed?
