### ISSUE TITLE
Data di sbarco dei migranti

### ISSUE THREAD

**Issue by Rabelaiss** [pcm-dpc/COVID-19#811]
**Tipo di richiesta**: richiesta di dati

Con piacere leggo nelle note che alcune regioni hanno cominciato a comunicare il dato dei casi importati e dei migranti.
Tuttavia, sarebbe opportuno corredare al dato dei migranti la relativa data di sbarco, o comunque indicare più o meno da quanto tempo questi migranti si trovano in Italia. Questo dato è importante per aiutare a capire se tali casi sono autoctoni o importati: se infatti la data di sbarco risale ad almeno 1 mese, sicuramente il virus è stato contratto in Italia.

So che non gestite direttamente voi questo dato, ma se possibile vi chiedo se potete sollecitare le regioni a comunicare anche questa importante informazione.
Maggiore chiarezza sarebbe utile anche per limitare gli accanimenti nei confronti dei migranti.

**Comment by vi-enne** [comment]
Mi associo, è un'ottima idea.
Questa informazione pare essere presente nei nuovi report ISS, quindi dovrebbe essere in qualche modo reperibile.

Il numero di casi importati, definiti come individui che hanno contratto il virus all'esterno dei confini territoriali, è anche necessario per una stima più corretta di Rt per ogni Regione/PA. 
Sempre nei report ISS se ne tiene conto.

Grazie!

**Comment by umbros** [comment]
Ciao, allo stato attuale il numero non è contemplato fra quelli riportati dalle Regioni, propongo la cosa ai colleghi del Ministero. Grazie
