### ISSUE TITLE
reported death number of August 15 does not match the death pattern reported in the last weeks

### ISSUE THREAD

**Issue by MohammedAlrozzi** [pcm-dpc/COVID-19#813]
Thanks for this effort. could you please confirm if the number for (deceduti) for today 15-August is correct? does not seem so. 
Thanks a lot

best

**Comment by umbros** [comment]
Hi,
The Emilia Romagna Region announces that following an internal verification of the data on deaths, the Parma Local Health Authority reported 154 deaths that occurred in March, April and May and so far not counted. The real number for today is +4.

**Comment by MohammedAlrozzi** [comment]
Thanks a lot. Very much appreciated.

**Comment by Jmuccigr** [comment]
I realize this is a closed issue, but it's perhaps worth putting these old numbers somewhere into the past totals, so Aug 15 doesn't erroneously have such a high total.

**Comment by umbros** [comment]
Hi @Jmuccigr is impossible to set in wich date the deaths are.

**Comment by Jmuccigr** [comment]
Peccato.
