### ISSUE TITLE
Chiarimento correttezza deceduti 15 agosto

### ISSUE THREAD

**Issue by tommasobonomo** [pcm-dpc/COVID-19#814]
**Tipo di richiesta**: richiesta di informazione

## Riassunto

I deceduti cumulativi al giorno 15-08-2020 sono 35392, come si può vedere nella cartella `dati-andamento-nazionale`, sia nel file `dpc-covid19-ita-andamento-nazionale-20200815.csv` che nel file `dpc-covid19-ita-andamento-nazionale-latest.csv`. Al giorno 14-08-2020 risultano essere 35234, dalle medesime fonti. Ciò risulta in una differenza giornaliera di 158, quindi 158 persone decedute nel solo giorno 15-08-2020. Si tratta di un errore o è effettivamente il dato corretto? Dato che i maggiori organi d'informazione riportano 4 deceduti il 15-08-2020.

## Interesse pubblico

Chiarimento su il dato deceduti a livello nazionale.

**Comment by umbros** [comment]
Ciao @tommasobonomo, come riportato nelle note https://github.com/pcm-dpc/COVID-19/blob/master/note/dpc-covid19-ita-note.csv o https://github.com/pcm-dpc/COVID-19/blob/master/avvisi.md c'è stato un ricalcolo di Regione Emilia Romagna quindi effettivamente sono 4 i deceduti ma c'è il numero di aggiunti del ricalcolo che non possono essere associati agli altri mesi in quanto non facilmente ricollocabili.

**Comment by tommasobonomo** [comment]
Grazie @umbros, ti segnalo che nel file https://github.com/pcm-dpc/COVID-19/blob/master/avvisi.md non è riportata quella nota.

**Comment by umbros** [comment]
Correggo grazie :)
