### ISSUE TITLE
Numero casi testati Liguria

### ISSUE THREAD

**Issue by 123cobloc** [pcm-dpc/COVID-19#815]
Tipo di issue:

- [x] Dati mancanti o errati 
- [ ] Errore nella documentazione 
- [ ] Errore or mancanza nella dashboard 
- [ ] Problemi di visualizzazione nella dashboard 

- Regione: 
- Provincia: 

## Riassunto

**Attesa:**

**Attuale:**

**Comment by Rabelaiss** [comment]
oggi risultano 1024179 nuovi casi testati in liguria, errore di sicuro

**Comment by Rabelaiss** [comment]
c'è uno 0 in più nei casi testati totale della liguria

**Comment by alexodus** [comment]
a livello nazionale risutano: 
ieri "casi_testati": 4455931,
oggi  "casi_testati": 5500970.0,
1045039 in più

**Comment by alexodus** [comment]
PS: per coerenza meglio non usare i numeri con la virgola per i casi testati (visto che anche i tamponi sono interi)

**Comment by ornolio** [comment]
1137400 casi testati in Liguria il 17/8/2020 sono errati. 
La data nella mappa della situazione (desktop) è del 16/8/2020 -non qggiornata-, mentre i dati CSV e scheda riepilogativa sottostanti è quella aggiornata del 17/8/2020

**Comment by Rabelaiss** [comment]
@umbros a quando il commit con i dati corretti

**Comment by umbros** [comment]
Il dato è stato corretto.
