### ISSUE TITLE
Lettera aperta alla Protezione Civile sulla qualità dei dati

### ISSUE THREAD

**Issue by vi-enne** [pcm-dpc/COVID-19#817]
**Tipo di richiesta**:  richiesta di informazione | richiesta di dati | suggerimento di miglioramento 
## Riassunto

Ciao,
Scrivo senza intento polemico, ma per aprire una discussione che reputo necessaria.

Ormai troppe volte vengono pubblicati dati in questa repository (e diffusi al pubblico e alle testate giornalistiche) che presentano errori e imprecisioni. Talvolta questi errori sono evidenti perché descriverebbero situazioni straordinarie.
Alcuni esempi in ordine sparso:
-	Totale Casi Testati Liguria il 18/08/2020 #815
-	Numero tamponi ER al 31/7 errato #800
-	Errori Sicilia, Bolzano, VdA #793
-	Totale positivi Bolzano #786
-	Errore formato dati (#806, #805, #809, #801, #799, #787, #785, #780, #778, #768)

Più volte questi errori sono stati segnalati dagli utenti, e più volte si è consigliato di implementare degli script di validazione (#806, ma anche in forma privata).
Appare evidente che non siano ancora stati implementati sistemi di validazione e/o sistemi di automazione che riducano l’errore umano. Inoltre, sembra evidente da #815 che i dati comunicati dalla Regioni/PA al Ministero della Salute e poi alla Protezione Civile vengano acriticamente pubblicati senza che nessuno si accorga di queste incongruenze. Oppure (ma il pensiero è talmente assurdo che lo rifuggo) che i dati siano inseriti dalla Protezione Civile _a mano_.

Vi chiedo quindi di rendere più trasparente la catena di comunicazione dei dati, indicando per quanto possibile come le basi dati comunichino tra di loro e quali accorgimenti sono stati o saranno presi per ridurre queste situazioni spiacevoli.
Mi permetto di scrivere queste parole poiché credo che un Dipartimento importante come la Protezione Civile sia capace di raggiungere standard di elevata qualità.

Certo di una vostra rapida risposta, vi ringrazio. 
Vittorio

PS: vi prego di non chiudere questa issue fino alla ragionevole certezza che il rischio di ripetere errori del genere sia ridotto rispetto ad oggi.
Taggo @umbros per la sua celerità nelle risposte!

## Interesse pubblico

 Chiarezza e trasparenza nella comunicazione dei dati, oltre che a una riduzione degli errori, aumentano la fiducia del pubblico

**Comment by umbros** [comment]
Ciao Vittorio @vi-enne, premetto che non vedo nessuna polemica lato tuo ma ogni richiesta di delucidazioni la ritengo lecita e la risposta dovuta.

Stiamo ordinariamente fornendo i dati ormai da qualche mese e, come normale, le cose sono andate a modificarsi e a migliorarsi; 
I dati sono forniti dalle Regioni per il tramite del Ministero della Salute e questo lo abbiamo sempre evidenziato quindi penso che la "trasparenza" di processo che tu richiedi ci sia da sempre. 
Detto questo il Dipartimento della Protezione Civile continua a erogare i dati, secondo i dataset (che nel tempo sono stati integrati e perfezionati) definiti anche segnalando problemi sui dati che vengono riscontrati (quindi non c'è un mero e acritico riportare i dati su un dataset) e la modifica del dato è una modifica formale ovvero, il DPC non modifica un dato inviato formalmente dal Ministero della Salute (anche se questo è un banale errore di battitura con uno zero in più). 

Tecnicamente il processo non è più manuale come i primi tempi ma i dati vengono raccolti da una piattaforma, validati e rilasciati in formato aperto e su dashboard. Nel dettaglio sia per la generazione dei dataset che per la validazione utilizziamo python (pandas, geopandas, numpy...). Il processo è sempre Regioni, Ministero della Salute, DPC.

Il dato dei casi testati di oggi è stato un mero errore di battitura sul sistema di raccolta dati che è stato segnalato e corretto (ci sono voluti i tempi di modifica del dato che è un processo formale); e ogni volta che si sono verificati dati sui valori e problemi tecnici questi sono stati prontamente corretti. Uguale errore si era verificato per le note o per errori di "new line" che sballavano i csv (che ora sono tecnicamente gestiti). Riguardo le note, queste sono segnalate dalle Regioni stesse, se vengono evidenziate delle problematiche viene loro fatta richiesta di delucidazioni.

Detto questo, come vedi, la risposta c'è stata e assolutamente il dato è lì trasparente e il sistema pronto a recepire segnalazioni di errori o indicazioni. Quindi benvengano ulteriori sistemi che ci aiutano a far emergere eventuali errori sui dati su cui, come sempre abbiamo fatto, riscontreremo e nel caso correggeremo.

Grazie

**Comment by vi-enne** [comment]
Ciao Umberto,

Grazie mille per la tua gentile risposta! Mi fa piacere vedere confermato come la Protezione Civile ci tenga alla trasparenza e alla chiarezza, e soprattutto alla comunità creatasi su GitHub. Rinnovo la mia stima per il tuo e il vostro lavoro, in questa e altre emergenze.

Osservo con piacere l’uso di Python per la validazione dati: questo farà contente diverse persone. Plaudo anche il fatto che i file .csv siano adesso tecnicamente gestiti e quindi errori di formato non dovrebbero più verificarsi.

Sebbene la tua risposta chiarisca alcuni punti, mi rimane ancora qualche perplessità e mi sento di azzardare dei suggerimenti.
Sebbene tu abbia reiterato che il flusso dati parte dalle Regioni, passa dal Ministero della Salute e infine arriva alla Protezione Civile, la mia domanda era più specifica: come viene gestito questo flusso di dati? Per quanto possibile, sarei interessato a sapere come questi dati vengano distribuiti: via e-mail? Con una dashboard dedicata? I file sono in formato leggibile da Excel? I dati sono inseriti a mano in qualsiasi punto oltre al primo inserimento? 

Ancora, visto che la catena di trasmissione dei dati si è allungata con l’aggiunta del Ministero della Salute (come da voi prontamente segnalato), come è possibile che un dato fortemente incongruente come quello di ieri (casi testati Liguria) sia arrivato fino alla fine della catena, ovvero la Protezione Civile?

Infine, mi sembra di capire dalla tua risposta, che anche se la Protezione Civile è in grado di rilevare forti incongruenze grazie ai meccanismi di validazione dati, è comunque costretta a pubblicare una tabella con dati evidentemente sbagliati e correggerla in seguito una volta terminato il processo formale di modifica del dato. Qualora tu mi confermassi che la situazione, ne deduco che altre tabelle con dati fortemente incongruenti potrebbero essere diffuse nel futuro. 

Il mio piccolo suggerimento è di almeno riportare l’orario di pubblicazione dei dati alle 18:00 ora italiana: negli ultimi tempi infatti vengono pubblicati diverse decine di minuti prima. Tra i possibili vantaggi, un tempo maggiore per il processo formale di modifica di concludersi a buon fine prima della pubblicazione, e una rassicurante costanza.

Ti invito anche a riaprire questa issue, così che altre persone possano commentare con i loro suggerimenti e proporre ulteriori sistemi.

Grazie,
Vittorio

**Comment by Paulsword** [comment]
Ti prego non ritorniamo alle 18. Se c'è una cosa santa e benedetta è che abbiamo un'oretta in più per il commento prima dei TG. Mi oppongo fieramente. Per tutto il resto, condivido.

**Comment by umbros** [comment]
Ciao Vittorio @vi-enne,
il Ministero della Salute è sempre stato nel processo sin dall'inizio.
Il processo è automatizzato quindi non c'è invio di email.
Relativamente al controllo il sistema DPC che prepara i dataset è composto anche da un sistema che evidenzia delle incongruenze sui dati formali (comprese diminuzioni su dati che, di norma, dovrebbero andare in crescita) ma essendo il dato del Ministero della Salute e il processo formale è necessario che un'informazione venga modificata da chi l'ha caricata sia che si tratti di un errore di digitazione che di calcolo.
Relativamente al futuro è ovvio che se da un lato il processo tecnologico va ad affinarsi sempre più e quindi a ridurre le possibilità di errore, dietro l'immissione dei dati c'è comunque un'attività manuale e oltretutto i dati in questione possono avere degli errori di calcolo (che poi vengono comune notificati).
Relativamente agli orari la pubblicazione viene effettuata quando il dato è conferito e da qui ne capisci l'automazione, se il sistema fosse rigido nel non pubblicare un'informazione si potrebbe rischiare che fin quando non è corretta non pubblica e si potrebbe andare oltre l'ora in cui i mezzi di informazione e non solo aspettano i dati stessi.

Come ho già detto benvenga qualsiasi contributo.

**Comment by vi-enne** [comment]
Ciao Umberto,

Mi pare evidente allora che il processo così concepito favorisca la pubblicazione di dati anche se fortemente incongruenti, piuttosto che non pubblicare proprio i dati. Questo anche nel caso in cui i meccanismi di validazione rilevino l’incongruenza. 

Mi sembra facile quindi implementare una sistema di notifica che inserisca, in fondo alla tabella, se eventuali incongruenze sono state rilevate e se è in corso un processo di verifica del dato. Non credo che questo appesantirebbe il sistema né la lettura della tabella, e anzi permetterebbe con un colpo d’occhio di valutare se aspettare a usare i dati comunicati.

Per quanto riguarda l’orario di pubblicazione, si potrebbe anche facilmente implementare una condizione di pubblicazione non _al momento di conferimento del dato_, ma se _il dato è conferito_ **e** _un certo orario è passato_. Dal commento di @Paulsword direi magari non 18:00, ma un orario fisso: proporrei non prima delle 17:30, per avere sempre più tempo per eventuali verifiche.

Grazie,
Vittorio
