### ISSUE TITLE
Strange 'codice_regione' in COVID data.. Why not ISO codes ?

### ISSUE THREAD

**Issue by sergio239new** [pcm-dpc/COVID-19#818]
if i look at CSV files for Italian regions i see for example:

codice_regione   |   region-name
13 | Abruzzo
17 | Basilicata

.. and so on. 

But ISO 3166-2:IT code for Abruzzo is **65**, and for Basilicata - **77**

Question: why you are don't use ISO codes for Italian regions ? .. or please explain what are that codes ?

Regards

**Comment by sergio239new** [comment]
here mapping from region codes used in csv files to ISO codes for all Italian regions, if somebody need it:

REGIONS = {
    '13': 'IT-65', # Abruzzo
    '17': 'IT-77', # Basilicata
    '18': 'IT-78', # Calabria
    '15': 'IT-72', # Campania
    '08': 'IT-45', # Emilia-Romagna
    '06': 'IT-36', # Friuli-Venezia Giulia
    '12': 'IT-62', # Lazio [Latium]
    '07': 'IT-42', # Liguria
    '03': 'IT-25', # Lombardia [Lombardy]
    '11': 'IT-57', # Marche
    '14': 'IT-67', # Molise
    '21': 'IT-BZ', # Bolzano
    '22': 'IT-32', # Trentino-Alto Adige (Trentino-Südtirol)
    '01': 'IT-21', # Piemonte [Piedmont]
    '16': 'IT-75', # Puglia [Apulia]
    '20': 'IT-88', # Sardegna [Sardinia]
    '19': 'IT-82', # Sicilia [Sicily]
    '09': 'IT-52', # Toscana [Tuscany]
    '10': 'IT-55', # Umbria
    '02': 'IT-23', # Valle d'Aosta (Vallée d'Aoste) [Aosta Valley]
    '05': 'IT-34'  # Veneto [Venetia]
}

**Comment by sergio239new** [comment]
I found already an answer. This 'codice_regione' are Italian internal codes.

codice_regione - Codice della Regione (ISTAT 2019) 
here is the source: https://www.istat.it/storage/codici-unita-amministrative/Elenco-comuni-italiani.xls

Anyway, if somebody needs, above is the mapping to ISO codes..

**Comment by umbros** [comment]
Hi @sergio239new thank you for your contribution, we are based on ISTAT official codes.
