### ISSUE TITLE
Casi da sospetto diagnostico in Piemonte diminuisce tutti i giorni da quasi due mesi, non dovrebbe essere stabile o crescere?

### ISSUE THREAD

**Issue by Articxok** [pcm-dpc/COVID-19#819]
Tipo di issue:

- [ ] Dati mancanti o errati dati-regioni/dpc-covid19-ita-regioni.csv

- Regione: Piemonte

## Riassunto

Salvo piccole oscillazioni quotidiane eventualmente dovute alla rettifica di errori commessi nei giorni precedenti, ci si aspetterebbe che molti dei dati nel file dati-regioni fossero di giorno in giorno sempre non-decrescenti. Sembra fare eccezione la colonna «casi_da_sospetto_diagnostico» relativa al Piemonte.

Il dato «casi_da_sospetto_diagnostico» relativo al Piemonte segnato per il primo giorno in cui questo dato è presente (2020-06-25T17:00:00) risulta essere **27972** , lo stesso dato, relativo all'Emilia-Romagna risulta essere molto simile: **27949** .

Il dato «casi_da_sospetto_diagnostico» relativo all'Emilia-Romagna alla data di "ieri" (2020-08-17T17:00:00) risulta essere un poco più alto: **28685** (più 736). Salvo un paio di eccezioni, di giorno in giorno questo dato è cresciuto, in base ai nuovi casi diagnosticati.

**Attesa:** Per il dato «casi_da_sospetto_diagnostico» relativo al Piemonte ci aspetteremmo un andamento simile, una crescita più o meno lenta...

**Attuale:**  invece, alla data di "ieri", troviamo: **24731** ( **meno** 3241)! Scorrendo i giorni, in questo caso le eccezioni sono le volte in cui il dato è aumentato, di giorno in giorno il dato è diminuito, incomprensibilmente.

**Comment by Paulsword** [comment]
Fanno ricalcoli su casi precedenti all'introduzione dello scorporo tra tracciamento e screening. Qualcuno dovrebbe dirgli che la piantassero, una buona volta. Per fortuna il portale regionale pubblica tutti i giorni il dato pulito, che se vuoi è raccolto qui alla slide 4.
https://public.flourish.studio/story/435616/

**Comment by umbros** [comment]
@Paulsword i dati comunicati sono della Regione stessa. Chi dovrebbe piantare cosa?

**Comment by Paulsword** [comment]
Loro, la Regione Piemonte. Dovrebbero piantarla con questi ricalcoli. Non ce l'ho con te @umbros figurati

**Comment by Paulsword** [comment]
Faccio notare che solo Piemonte si è incaponito con la revisione a posteriori. Gli altri hanno giustamente accettato di non avere lo scorporo prima del 26 giugno.

**Comment by umbros** [comment]
Passo l'informazione e speriamo in un miglioramento della qualità del dato :)

**Comment by Paulsword** [comment]
grazie ;)
