### ISSUE TITLE
Derivative work in README.md

### ISSUE THREAD

**Issue by pacovi** [pcm-dpc/COVID-19#82]
**Type of issue**: suggerimento di enhancement (documentazione)

## Summary

As stated by @brucellino in https://github.com/pcm-dpc/COVID-19/issues/47#issuecomment-596377678 , would be very benefitial to have a "Derivative work" section on which ongoing visualization efforts could be shared.

## Public interest

Even if you don't have a technical backround you could see what others have put together with the data provided. Open data for everybody.

**Comment by brucellino** [comment]
hi @pacovi! I just would suggest keeping the readme clean of this section, but linking to such derivatives in the CONTRIBUTORS file.

**Comment by umbros** [comment]
Ciao @pacovi, benchè sarebbe un'ottima iniziativa, potrebbe creare problemi il fatto che dashboard potrebbero utilizzare anche dati "non ufficiali" e che potrebbero indurre il cittadino a conclusioni o analisi non corrette. Quindi, non verrà fatta una sezione CONTRIBUTORS. Ovviamente chiunque può "promuovere" in modo assolutamente personale il proprio lavoro, la regola, però, è quella di non utilizzare il logo del Dipartimento della Protezione Civile ma dichiarare l'utilizzo della fonte.
