### ISSUE TITLE
Se un residente della regione A viene trovato positivo nella regione B, il caso viene conteggiato in A o in B?

### ISSUE THREAD

**Issue by Rabelaiss** [pcm-dpc/COVID-19#825]
Se non ricordo male, dal 24 o 25 giugno
> i casi vengono assegnati a una certa provincia non più per ospedalizzazione ma per residenza/domicilio

per esempio un napoletano ricoverato a salerno viene contato tra i casi di napoli mentre prima tra i casi di salerno.
Tuttavia, da quando si è cominciato a parlare di casi importati non ne sono più tanto sicuro, spesso infatti i presidenti delle regioni lamentano la grande quantità di casi importati. Da quel che so i casi importati non sono solo persone trovate positive dopo una permanenza all'estero, ma anche dopo una permanenza in altra regione, o sbaglio?
C'è un comunicato ufficiale a riguardo?
In particolare, mi interesserebbe sapere la risposta alla domanda posta nel titolo della discussione.
Grazie

**Comment by vi-enne** [comment]
Da questo[ articolo sulla regione Basilicata](https://www.lagazzettadelmezzogiorno.it/news/home/1244816/coronavirus-in-basilicata-3-nuovi-contagi-su-502-tamponi.html) del 25/08/2020, pare che un residente della regione A trovato positivo nella regione B, venga conteggiato in A.

Nello specifico, il positivo e' residente in Puglia e trovato positivo in Basilicata, ma non e' stato conteggiato in Basilicata.
Aggiornero' il commento qualora la regione Puglia rilasci piu' informazioni nel comunicato.

Personalmente, lo trovo alquanto bizzarro.

Anche qui un chiarimento sarebbe necessario @umbros :)
Grazie!

**Comment by suracemarco** [comment]
_Si ricorda che a partire dal 24 giugno 2020, il Ministero della Salute ha modificato il sistema di rilevazione dei dati sulla diffusione del Covid-19. I casi positivi non sono più indicati secondo la provincia di notifica bensì in base alla provincia di residenza o domicilio._

comunicato regione Toscana

**Comment by Rabelaiss** [comment]
@suracemarco esatto, ma allora non capisco perché in regioni come siclia e sardegna ci sono molti casi importati da altre regioni (turisti) che vengono conteggiati in sicilia/sardegna e non nelle regioni di residenza

**Comment by suracemarco** [comment]
ma infatti non succede
come fai a dirlo?
