### ISSUE TITLE
Translation to EN

### ISSUE THREAD

**Issue by johannesschobel** [pcm-dpc/COVID-19#83]
**Type of issue**: Request for Information

## Summary

First of all, i would like to tell you, that i **really** really like the approch of releasing such data on GitHub for others to work with! :+1: that is a really awesome movement! Keep it going.

However, as I am not able to read / understand Italian, this data is not usable for me, nor am i able to process respective data. I would really like to work with provided information and provide services but am not able to read and understand the information. Would it be possible to release information in English so other devs could read / work with the data as well?

## Public interest

As indicated above, the repository would get more attention, if the data would be provided in English. Would that be possible!?

All the best

**Comment by umbros** [comment]
Hi, @johannesschobel we are working for that also thanks to contribution and pull requests.
Perhaps tomorrow we will release a README also in english language.
