### ISSUE TITLE
File regioni: mancata quotazione riga 3887

### ISSUE THREAD

**Issue by guivo** [pcm-dpc/COVID-19#831]
Manca un " di chiusura alla riga 3887

Tipo di issue:

- [x] Dati mancanti o errati 
- [ ] Errore nella documentazione 
- [ ] Errore or mancanza nella dashboard 
- [ ] Problemi di visualizzazione nella dashboard

**Comment by giova86** [comment]
esattamente... 
:-(

**Comment by umbros** [comment]
Corretto
