### ISSUE TITLE
Casi Sardegna

### ISSUE THREAD

**Issue by Paulsword** [pcm-dpc/COVID-19#832]
Il totale ieri 1912 oggi 1967
Mi sfugge perchè siano dati 57 nuovi casi e non 55

**Comment by umbros** [comment]
27/08/2020
La Regione Sardegna comunica che dal totale dei casi vengono sottratte due unità nella provincia di Nuoro, già dichiarati in data 23/08 ma con ripetuti tamponi negativi.

**Comment by Rabelaiss** [comment]
@Paulsword 

è quello che ho provato a spiegarti nei commenti sulla pagina pillole di ottimismo la settimana scorsa, [qui una parte della nostra conversazione](https://i.imgur.com/UtDMnqI.png)

la protezione civile non modifica i dati vecchi in seguito a riconteggi come quello di oggi (Sardegna ha rimosso 2 casi vecchi)

**Comment by Paulsword** [comment]
> @Paulsword
> 
> è quello che ho provato a spiegarti 

Sono un po' tonto, ci metto un po' ma poi piano piano ci arrivo.
Grazie
