### ISSUE TITLE
Nuovi casi in Italia 1462 o 1463? Nuovi casi in Abruzzo 20 o 21?

### ISSUE THREAD

**Issue by Rabelaiss** [pcm-dpc/COVID-19#834]
Dalle note di oggi si legge che
* Abruzzo: Oggi sono risultati 21 nuovi casi positivi. Dal totale però è stato sottratto 1 caso dei giorni passati
* Emilia-Romagna: In seguito a verifica sono stati eliminati 2 casi in quanto inserimento duplicato 

Il numero totale di casi comunicato ieri 263949 va pertanto corretto: 263949-2-1=263946. Facendo adesso la differenza con i casi totali di oggi 265409 si ottiene 1463.

Penso che l'errore sia dovuto al fatto che nella [scheda riepilogativa](https://github.com/pcm-dpc/COVID-19/blob/master/schede-riepilogative/regioni/dpc-covid19-ita-scheda-regioni-20200828.pdf) di oggi, la riga dell'Abruzzo riporta 20 nuovi casi, quando nella nota è scritto che i nuovi casi sono invece 21.

L'Abruzzo ieri riportava 3705 casi totali che però va corretto a seguito del riconteggio, quindi 3705-1=3704. I casi ad oggi sono 3725, e quindi la differenza fa 21.

Tuttavia, il [bollettino regionale](https://www.regione.abruzzo.it/content/coronavirus-abruzzo-dati-aggiornati-al-28-agosto-casi-positivi-3725-20) parla di 20 nuovi casi, senza far riferimento al riconteggio riportato nelle note della protezione civile.

**Comment by umbros** [comment]
Grazie Rabelaiss abbiamo notificato la cosa.
