### ISSUE TITLE
Inconsistency between data in this repo versus https://www.epicentro.iss.it/en/coronavirus/dashboard/inizio.html

### ISSUE THREAD

**Issue by metabiota-vikram** [pcm-dpc/COVID-19#835]
**Type of issue**: request for information

## Summary

We notice inconsistency between data report here vs https://www.epicentro.iss.it/en/coronavirus/dashboard/inizio.html

Fields of concern: deceduti and totale_casi

Say in this repo: https://raw.githubusercontent.com/pcm-dpc/COVID-19/master/dati-json/dpc-covid19-ita-andamento-nazionale-latest.json the cumulative deceduti = 35,472 and in https://www.epicentro.iss.it/en/coronavirus/dashboard/inizio.html the cumulative deceduti = 35,930

Similarly in this repo totale_casi = 265,409 but on https://www.epicentro.iss.it/en/coronavirus/dashboard/inizio.html the cumulative totale_casi = 263,883

Is this repo more current than https://www.epicentro.iss.it/en/coronavirus/dashboard/inizio.html?

Thank you for your clarification.

## Public interest

Data reported is consistent across different official sources.

**Comment by umbros** [comment]
Hi, We have notified ISS of the inconsistency of the data.
