### ISSUE TITLE
1058 guariti in Veneto?

### ISSUE THREAD

**Issue by Rabelaiss** [pcm-dpc/COVID-19#836]
Il dato dei guariti in Veneto relativo alle ultime 24 ore è un accumulo/riconteggio? Chiedo perché di solito fa dai 30 ai 100 guariti al giorno

**Comment by 123cobloc** [comment]
nel bollettino regionale ne sono riportati 58, per un totale di 18290 anzichè 19290

**Comment by umbros** [comment]
segnalato

**Comment by Rabelaiss** [comment]
@123cobloc  grazie

questo articolo segnala che la variazione degli attualmente positivi in veneto rispetto a ieri è +92, non -908 come riportato nei dati su github

**Comment by umbros** [comment]
Si confermano i dati trasmessi dalla Regione attraverso il Ministero della Salute.

**Comment by Rabelaiss** [comment]
> Si confermano i dati trasmessi dalla Regione attraverso il Ministero della Salute.

ossia confermati 1058 guariti in veneto? grazie

**Comment by Paulsword** [comment]
@123cobloc di quale bollettino parlavi? puoi dare link?

**Comment by Rabelaiss** [comment]
@Paulsword quello su rainews https://www.rainews.it/tgr/veneto/video/2020/08/ven-Coronavirus-covid19-fase3-bollettino-regione-Veneto-dati-sabato-29-agosto-2020-67a9cd7f-f64d-4ab1-88f4-8e1023ae46c9.html

**Comment by Paulsword** [comment]
@Rabelaiss grazie. Come te lo spieghi?

**Comment by Rabelaiss** [comment]
@Paulsword qua trovi i dati completi ufficiali del veneto https://www.facebook.com/watch/?v=393804928624666&extid=n7M1yT5sRrz7tqVq

**Comment by Rabelaiss** [comment]
> @Rabelaiss grazie. Come te lo spieghi?

penso che semplicemente chi ha inserto i dati dei guariti totali ha scritto 19290 invece di 18290

**Comment by Paulsword** [comment]
Quindi non 1058 ma 58. Perchè allora umbros conferma?

**Comment by Rabelaiss** [comment]
non saprei, ma sicuramente 1000 guariti sono improbabili se quelli normali sono 50 al giorno. La fonte del video è Azienda Zero ossia chi gestisce i dati del covid in veneto, la fonte più affidabile a riguardo

**Comment by Paulsword** [comment]
Vabbè ma si chiede conferma, e con mille in più non ci si degna nemmeno di fare la rettifica?
Ma ti pare normale?
grazie comunque.
