### ISSUE TITLE
Grafico "Totale casi" non visualizza dati di una specifica regione

### ISSUE THREAD

**Issue by MarioMarietto** [pcm-dpc/COVID-19#838]
Tipo di issue:

- [ ] Dati mancanti o errati 
- [ ] Errore nella documentazione 
- [ ] Errore or mancanza nella dashboard 
- [x] Problemi di visualizzazione nella dashboard 

## Riassunto

Selezionando una regione dal dropdown in alto a destra della dashboard e si seleziona "Andamento" in "Totale casi" viene visualizzato il grafico dei casi totali in Italia.

**Attesa:**

Dovrebbe essere visualizzato il grafico con i casi totali della specifica regione selezionata.

**Comment by umbros** [comment]
Corretto, grazie @MarioMarietto
