### ISSUE TITLE
BIAS 1000 Dimessi/Guariti Veneto

### ISSUE THREAD

**Issue by MicheleAlfinito** [pcm-dpc/COVID-19#839]
In riferimento alle issue #836 e #837 sui dati del 29/8 (ieri), sui 1000 negativi in più Regione Veneto, faccio presente che:

1) il dato cumulativo (dunque totale) dei dimessi/guariti nel Veneto del file .csv (cartella Regioni) del 30/8 (oggi) risulta tuttora affetto da tale BIAS, senza che sia pervenuta alcuna comunicazione di rettifica al riguardo (in caso di errore) o comunicazione di ricalcolo da parte del ISS;
2) non vale l'argomento che se una Regione comunica dei dati, allora il Ministero li possa prendere così come comunicati, a FRONTE delle evidenti incongruenze tra bollettino Regione Veneto e dati del Ministero: sarebbe come dare per assodata la presenza di un tavolino tondo di noce a 3 gambe in mezzo a chilometri di deserto del Sahara con un telefono rosa (a rotella di selezione) su quel tavolino: la prima cosa che un comune mortale si chiederebbe è A) come ci è finito lì e B) dov'è l'attacco del filo del telefono perchè si vede solo della sabbia. Non dico che non possa esserci quel tavolino: ma che alle domande conseguenti la risposta non è un optional, bensì obligatoria. Se non vi fossero incongruenze di dati tra i due Bollettini, il problema neppure si porrebbe.
3) in Scienza vale sempre il principio che un evento straordinario richieda prove straordinarie: insomma, una fluttuazione statistica di tale simile portata richiederebbe quantomeno due righe di spiegazione salvo, come già detto, una rettifica in caso di errore di trascrizione dei dati: eventualità che vedo, dati alla mano, molto più probabile di quanto possa apparire;
4) il link al Bollettino Regione Veneto di oggi https://www.ilgiornaledivicenza.it/filedelivery/policy:7.2892658:1598774593/Report%20informatizzato_20200830_ore8.pdf?mobile_stay=1 riporta che i negativi complessivi sono 18399 e non 19399 come invece riportato nel file https://github.com/pcm-dpc/COVID-19/blob/master/dati-regioni/dpc-covid19-ita-regioni-20200830.csv.

Vorrei far notare che le conseguenze di un simile modo di operare sono a catena:
1) il dato cumulativo dei dimessi/guariti è totalmente privo di consistenza reale;
2) il metodo di calcolo dell'indice Rt utilizzato dal Ministero tiene conto del dato dei dimessi/guariti: l'inaffidabilità di tale dato rende la stima di Rt, già per sua natura affetta da numerose variabilità ed incertezze di tipo statistico, totalmente inaffidabile.
RICHIESTA:
- rettifica del dato cumulativo in caso di errore, per quanto possa comportare (me ne rendo ben conto) l'introduzione di qualche eccezione all'algoritmo di calcolo;
- indagine tra Ministero, ISS e Regione Veneto sulle modalità di comunicazione dei dati e/o validazione degli stessi perchè, come già spiegato all'inizio, qualunque incongruenza richiede la adeguata, giusta spiegazione e non può assolutamente essere passata "in corner", perchè può innescare un processo a catena di errori conseguenti, cui è difficile a posteriori porvi rimedio se ne viene persa la traccia sorgente.
Grazie

**Comment by Rabelaiss** [comment]
Quoto, e oltre a dimessi_guariti anche isolamento_domiciliare e totale_positivi risultano errati, sia per il veneto sia per l'italia

**Comment by MicheleAlfinito** [comment]
Si, ho verificato: abbiamo 1000 attualmente positivi in meno nel Veneto (dunque anche in Italia).
Ovviamente se i casi totali non cambiano ed aumentano i guariti calano gli attivi per far stare in piedi il castello. L'unico dato forse più affidabile sono i movimenti ospedalieri, che calcolo dalla differenza oggi-ieri dei ricoverati: fortunatamente queste incongruenze sembrano intaccare più le quarantene. Dal mio foglio di calcolo riesco a stimare i nuovi casi clinici, proprio dai movimenti ospedalieri.
Grazie comunque dei tuoi interventi, sempre puntuali e precisi.

**Comment by Rabelaiss** [comment]
negli avvisi di oggi si legge

La Regione Veneto comunica il seguente ricalcolo: il numero corretto dei guariti e dell'isolamento domiciliare del giorno 29.08.20 è rispettivamente 18.290 e 2.285; il numero corretto dei guariti e dell'isolamento domiciliare del giorno 30.08.20 è rispettivamente 18.399 e 2.286;

quindi col nuovo commit dovrebbero aggiustare i dati

**Comment by umbros** [comment]
Ciao, c'è un ritardo nei flusso dati per dei ricalcoli.

**Comment by umbros** [comment]
Inviati

**Comment by Rabelaiss** [comment]
> Inviati

bene, direi che si può chiudere questione risolta

**Comment by umbros** [comment]
:-)

**Comment by MicheleAlfinito** [comment]
Confermo la congruenza dei dati. Grazie a tutti
