### ISSUE TITLE
Dati Bolzano non aggiornati

### ISSUE THREAD

**Issue by Devilmoon** [pcm-dpc/COVID-19#84]
Tipo di issue:

- [X] Dati mancanti o errati 
- [ ] Errore nella documentazione 
- [ ] Errore or mancanza nella dashboard 
- [ ] Problemi di visualizzazione nella dashboard 

## Riassunto

I dati forniti per la provincia autonoma di Bolzano non corrispondono ai dati riportati dall'azienda sanitaria dell'Alto Adige. Perché questa discrepanza? Si tratta di una differenza tra positivi al tampone e confermati dall'ISS, oppure di dati non aggiornati in tempo reale?

**Attesa:**
[52 positivi](https://www.altoadige.it/cronaca/coronavirus-in-alto-adige-52-positivi-1.2286830)

**Attuale:**
9 positivi

**Comment by umbros** [comment]
Ciao @Devilmoon i dati che vengono forniti da noi sono quelli ufficiali perchè forniti da Ministero della Salute, i dati vengono aggiornati ogni giorno a quest'ora circa per poi essere preparati al fine della conferenza stampa del Capo Dipartimento. Quindi se l'azienda sanitaria riporta altri dati sono elaborazioni successive.
