### ISSUE TITLE
Nuovi casi in Puglia del 1 settembre 39 o 41?

### ISSUE THREAD

**Issue by Rabelaiss** [pcm-dpc/COVID-19#841]
@umbros  La differenza tra casi totali del 1/9 e casi totali del 31/8 è 5479-5440=39, ma il [bollettino della regione](https://www.regione.puglia.it/documents/65725/216593/Bollettino+Covid_01092020.pdf) del 1/9 riporta 41 nuovi casi. C'è stato un riconteggio non segnalato  a seguito del quale sono stati rimossi 2 casi vecchi, oppure il numero 41 riportato sul bollettino regionale è errato?

**Comment by MicheleAlfinito** [comment]
@Rabelaiss ti do un indizio (non so quanto significativo però...): dal delta 1 day 31/8 - 30/8 fra le colonne cumulative dei "casi_testati" e "tamponi", risultavano per la Puglia al 31/8 (cioè il giorno precedente al 1/9) 2146 "casi_testati" contro 1974 "tamponi", che sono i "tamponi analizzati", cioè casi testati+seconde diagnosi (doppi tamponi) sugli stessi soggetti. Nei miei report generalmente presento tali situazioni con nota "dati parziali per...(e il nome di Regione)...", cioè significa che, a scanso di errori od omissioni di conteggi, non sono pervenuti o non sono stati registrati tutti gli esiti delle analisi dei tamponi.
Per cui potrebbe benissimo essere successo che i 2 casi in più nel Bollettino della Puglia siano collegabili a tali esiti mancanti il giorno prima. Magari dipende da quando la Regione Puglia comunica i dati al Ministero...e magari l'aggiornamento dei 2 casi in più si è verificato a posteriori, ad esempio.
Ciò non toglie che della cosa si debba tenere conto e magari aggiungere il giorno dopo quei 2 casi sia nella colonna "nuovi_positivi" sia in quella "totale_casi".

**Comment by Rabelaiss** [comment]
@umbros anche oggi i nuovi casi riportati dalla regione e da voi differiscono di due unità, 80 casi riportati dalla puglia e 78 da voi

**Comment by umbros** [comment]
Ciao a tutti, è la stessa Puglia che ha fornito i dati. Quindi sono validi quelli rilasciati qui.

**Comment by Rabelaiss** [comment]
@MicheleAlfinito 

> magari l'aggiornamento dei 2 casi in più si è verificato a posteriori

Non credo sia questo il caso dal momento che il 1/9 sia Puglia sia protezione civile hanno comunicato lo stesso numero di casi totali (5479). Se fosse come dice te allora anche i casi totali della Puglia e della protezione civile avrebbero dovuto essere diversi per 2 unità, o no?

Inoltre

1. non è ben chiaro se i numeri di tamponi e casi testati dalla protezione civile siano quelli fatti e/o quelli analizzati, inoltre potrebbe anche essere che non ci sia una linea nazionale e quindi poca normalizzazione del dato sul territorio nazionale
2. è già capitato qualche volta che una regione avesse più nuovi casi testati che tamponi (e addirittura è capitato a marzo anche che alcune regioni avessere un numero di nuovi tamponi inferiore ai nuovi casi)
3. nessuno ci garantisce che i numeri comunicati siano esenti da riconteggi, ossia in quei 2146 casi testati potrebbero essercene 400 vecchi e aggiunti al conteggio solo al 31/8 (umbros in @556 scrisse "i tamponi sono riferiti ai risultati dei tamponi pervenuti alla data di oggi", ciò sembra chiarire quanto detto in 1, però non parla di date di prelievo dei tamponi, quindi i tamponi odierni potrebbero essere non solo tamponi analizzati nelle ultime 24 ore ma anche nei giorni precedenti)

**Comment by Rabelaiss** [comment]
@umbros Grazie per la risposta! Però anche i bollettini sul sito regione.puglia.it sono forniti dalla stessa Puglia, dici che sono più attendibili quelli comunicati a voi?
