### ISSUE TITLE
In fase di controllo deceduti Emilia Romagna

### ISSUE THREAD

**Issue by umbros** [pcm-dpc/COVID-19#843]
In fase di controllo deceduti Emilia Romagna

**Comment by Rabelaiss** [comment]
Nella dashboard arcgis sono riportati 8 nuovi decessi e 35542 totali (quest'ultimo presente anche nei file csv)

Nella scheda riepilogativa del ministero sono riportati 35541 decessi totali

Tenendo conto del riconteggio dell'emilia romagna, al totale di ieri va rimossa una unità, quindi il totale decessi di ieri diventa 35533, e facendo differenza col totale di oggi 35542-35533 = 9 nuovi decessi (assumo sia più affidabile il totale che compare nei csv rispetto a quello che compare nella tabella del ministero)

**Comment by umbros** [comment]
Modificati i dati:
Emilia-Romagna
- 05/09: 4463 (0 incrementi)
- 06/09: 4464 (+1 incremento)

Totali deceduti di oggi: 8

Buona serata

**Comment by Rabelaiss** [comment]
grazie @umbros tuttavia alla riga 4077 del nuovo dpc-covid19-ita-regioni c'è errore
