### ISSUE TITLE
A quando risaliva il caso rimosso oggi dal totale dell'Emilia-Romagna?

### ISSUE THREAD

**Issue by Rabelaiss** [pcm-dpc/COVID-19#844]
Ho notato che avete modificato i casi totali e i decessi totali di ieri (sia i dati nazionali sia i dati dell'emilia-romagna) in seguito ad avviso di riconteggio dell'Emilia-Romagna, e mi sembra che una cosa simile non l'aveste mai fatta prima d'ora.

Questo è un bene perché in questo modo non dobbiamo correggere a mano i dati, tuttavia è importante anche fare chiarezza sulla data a cui risalgono i casi/decessi rimossi, se ad esempio oggi viene rimosso 1 caso diagnosticato (e aggiunto nel conteggio) il 2 settembre, allora bisogna sottrarre 1 ai casi totali di tutti i giorni che vanno da ieri al 2 settembre (non solo di ieri).

Ora, negli avvisi di oggi non compare la data a cui risalgono il caso e il decesso rimossi oggi dall'Emilia-Romagna, si legge infatti "verifica sui dati comunicati nei giorni scorsi" e "un decesso precedentemente comunicato" senza dire la data.
Avendo voi @umbros modificato solo i dati di ieri, state dicendo che il caso rimosso oggi è stato diagnosticato ieri.
Vi chiedo dunque, giusto per essere sicuri, a voi è stata notificata anche la data a cui risale il caso e questa data è ieri?
Grazie

**Comment by umbros** [comment]
Ciao @Rabelaiss,
Quando il ricalcolo é noto viene imputato al giorno altrimenti dobbiamo imputarlo al giorno stesso. Stiamo lavorando per migliorare il flusso e con gli automatismi fatti diventa piú semplice. Corretto quanto dici comunque.

**Comment by Rabelaiss** [comment]
@umbros Grazie per la rapida risposta e per i miglioramenti che state apportando.
Non ho capito però se vi è stato comunicato che il caso rimosso oggi sia stato diagnosticato ieri e quindi avete modificato solo i dati di ieri, oppure se di vostra iniziativa avete modificato solo i dati di ieri senza sapere la data di diagnosi?

p.s. alle righe 4077 e 4102 del nuovo dpc-covid19-ita-regioni.csv ci sono errori

**Comment by umbros** [comment]
Ciao @Rabelaiss,
il tracciato è stato corretto, i due dati sono su Emilia-Romagna e sono dati relativi a ieri su positivi e deceduti. Il riscontro è avvenuto oggi come notificato.
