### ISSUE TITLE
Unterminated CSV quoted field

### ISSUE THREAD

**Issue by sausyn** [pcm-dpc/COVID-19#846]
Type of issue:

Incorrect or missing data in **dati-regioni/dpc-covid19-ita-regioni.csv**

## Summary

Unterminated quoted field at row 4076:
2020-09-05T17:00:00,ITA,13,Abruzzo,42.35122196,13.39843823,32,2,34,449,483,12,13,2910,472,3396,469,3865,164140,106544,"Dal totale dei positivi è stato sottratto 1 caso precedentemente conteggiato 2 volte

**Comment by miccoli** [comment]
Fixed in PR #845

**Comment by SilvioCaggia** [comment]
Cosa significa "fixed"?
Io tuttora non riesco ad elaborare i dati su Google Sheets...
Qualcuno può chiudere l'apice in questione o toglierlo nel file?
Grazie

**Comment by miccoli** [comment]
> Cosa significa "fixed"?

Scusa, poco chiaro il mio commento: sarà "fixed" quando la PR #845 sarà incorporata nella repo.

**Comment by umbros** [comment]
Corretto grazie!
