### ISSUE TITLE
Incongruenza `totale_casi` per l'Emilia-Romagna nel giorno 2020-09-05 tra dati regionali e provinciali.

### ISSUE THREAD

**Issue by miccoli** [pcm-dpc/COVID-19#851]
Tipo di issue:

- [x] Dati mancanti o errati 
- [ ] Errore nella documentazione 
- [ ] Errore or mancanza nella dashboard 
- [ ] Problemi di visualizzazione nella dashboard 

- Regione: Emila-Romagna
- Provincia: tutte quelle in Emilia-Romagna

## Riassunto

Con riferimento alla situazione attuale (commit 7c12783) il valore di `totale_casi` per l'Emilia-Romagna del giorno 2020-09-05 è discorde tra dati regionali e provinciali.

- `dati-province/dpc-covid19-ita-province-20200905.csv`: somma `totale_casi`: **32505**
- `dati-regioni/dpc-covid19-ita-regioni-20200905.csv`: `totale_casi`: **32504**

L'incogruenza è stata introdotta con il commit f9fea610cca9b5e868d5e06261c5479990f8ce9e che ha ridotto il `totale_casi` da 32505 a 32504.

Per coerenza bisognerebbe correggere anche il file `dati-province/dpc-covid19-ita-province-20200905.csv`.

**Comment by umbros** [comment]
Stiamo riscontrando la Provincia. Grazie @miccoli

**Comment by miccoli** [comment]
L'errore è ancora presente...

**Comment by miccoli** [comment]
@Umbros scusa se insisto: l'errore dei dati è ancora presente.
