### ISSUE TITLE
Casi regioni Veneto

### ISSUE THREAD

**Issue by 123cobloc** [pcm-dpc/COVID-19#852]
Type of issue:

- [x] Incorrect or missing data 
- [ ] Incorrect or missing documentation 
- [ ] Incorrect or missing data in the dashboard 
- [ ] Layout problem in the dashboard 

- Region: Veneto

## Summary
I dati riportati nel bollettino sono diversi da quelli forniti dalla regione (Azienda Zero)

**Expected:** +152 casi per un totale di 24165

**Actual:** +105 casi per un totale di 24118

**Comment by umbros** [comment]
Si confermano quelli comunicati su piattaforma Ministero della Salute.

**Comment by Rabelaiss** [comment]
@123cobloc non capisco a cosa sia dovuta la differenza

**Comment by Rabelaiss** [comment]
@123cobloc penso che nei prossimi giorni vedremo un riconteggio come è già successo la settimana scorsa
