### ISSUE TITLE
In seguito alle note odierne, il campo totale_casi di ieri dell'Abruzzo non dovrebbe essere corretto da 3919 a 3916 e il campo nuovi_positivi da 14 a 11?

### ISSUE THREAD

**Issue by Rabelaiss** [pcm-dpc/COVID-19#854]
Nelle note di oggi si legge che dal totale dei casi positivi in Abruzzo sono stati sottratti 3 casi diagnosticati ieri. Diversamente dalla maggior parte degli altri riconteggi, questa volta si conosce la data di diagnosi dei casi rimossi, quindi è possibile in tutta sicurezza modificare i numeri di ieri.
Una situazione simile era successa il 6 settembre quando avete corretto i dati dell'Emilia-Romagna e quelli nazionali (`totale_casi` diminuito da 32505 a 32504 e `nuovi_positivi` modificato da 134 a 133, analogamente avete diminuito di una unità anche i numeri nazionali) in quanto anche in quel caso era stata comunicata la data di diagnosi.

@umbros Non dovreste procedere alla stessa maniera anche nel caso odierno dell'Abruzzo correggendo il `totale_casi` di ieri da 3919 a 3916, i `nuovi_positivi` da 14 a 11, e sottrarre 3 unità anche dai rispettivi dati nazionali di ieri?

**Comment by umbros** [comment]
Corretto @Rabelaiss sarà corretto domani.
