### ISSUE TITLE
totale_positivi non include terapia_intensiva

### ISSUE THREAD

**Issue by lcarnevale** [pcm-dpc/COVID-19#856]
Tipo di issue:

- [x] Dati mancanti o errati 
- [ ] Errore nella documentazione 
- [ ] Errore or mancanza nella dashboard 
- [ ] Problemi di visualizzazione nella dashboard 

## Riassunto

Con riferimento alla descrizione del dataset fornita a [questo](https://github.com/pcm-dpc/COVID-19/blob/master/dati-andamento-covid19-italia.md) indirizzo, non mi torna il fatto che il numero di _totale_positivi_ non conteggi anche le terapie intensive (_terapia_intensiva_). Infatti, da descrizione, il totale_positivi è:
> Totale attualmente positivi (ospedalizzati + isolamento domiciliare)

**Attesa:**

Mi aspettavo che il valore di totale_positivi includesse _terapia_intensiva_, _totale_ospedalizzati_ e _isolamento_domiciliare_.

**Attuale:** 

Attualmente il valore di _totale_positivi_ è così descritto:
> Totale attualmente positivi (ospedalizzati + isolamento domiciliare)

Lorenzo.

**Comment by Paulsword** [comment]
@lcarnevale, le Terapie Intensive si trovano dentro gli ospedali.

**Comment by lcarnevale** [comment]
> @lcarnevale, le Terapie Intensive si trovano dentro gli ospedali.

Non colgo questo punto, @Paulsword.
Anche i _totale_ospedalizzati_ si trovano dentro gli ospedali.

**Comment by umbros** [comment]
@lcarnevale la issue da te aperta non sembra trovare rispondenza puoi fare degli esempi?

**Comment by lcarnevale** [comment]
> @lcarnevale la issue da te aperta non sembra trovare rispondenza puoi fare degli esempi?

@umbros mi riferisco alla documentazione sopra linkata.
La definizione di _totale_positivi_ è:

> Totale attualmente positivi (ospedalizzati + isolamento domiciliare)

Questa cosa, concettualmente, non mi torna. I positivi dovrebbero essere tutte le persone domiciliate, ospedalizzate e in terapia intensiva. Quindi seguendo il mio ragionamento, le terapie intensive dovrebbero essere incluse.

Oppure sto distorcendo il significato dell'attributo.

**Comment by umbros** [comment]
Corretto ospedalizzati è la somma di ricoverati con sintomi + terapia intensiva

**Comment by lcarnevale** [comment]
Perfetto @umbros, grazie tante.
Chiudo la issue a questo punto.
