### ISSUE TITLE
Casi Testati maggiori dei Tamponi

### ISSUE THREAD

**Issue by Rabelaiss** [pcm-dpc/COVID-19#857]
Ultimamente accade non di rado che una regione comunichi un numero di casi testati maggiore dei tamponi, cosa che non dovrebbe essere possibile essendo i casi testati una parte dei tamponi.
Ad esempio oggi i dati del Piemonte sono 2387 tamponi e 2654 casi testati, quelli della Campania 3405 tamponi e 5241 casi testati.
L'incongruenza di questi dati è dovuta a ricalcoli (aggiunta di vecchi casi testati) o ad altri motivi?

@umbros Nell'issue #827 dicevi che in caso di dati non congruenti o probabilmente errati sarebbe stata aperta una issue per segnalare lo stato di verifica dei dati stessi, però oggi non è stata aperta l'issue per i tamponi della Campania e del Piemonte, come mai?
Grazie

**Comment by Rabelaiss** [comment]
Oggi la Campania riporta solo 735 casi testati, numero molto basso rispetto alla media di 4-5000 tamponi al giorno nelle ultime settimane.... forse centra qualcosa con il gran numero di casi testati riportati ieri?

**Comment by MicheleAlfinito** [comment]
Quoto.
Capita sovente purtroppo e lo interpreto come "dati parziali": se così fosse il calo del giorno successivo sarebbe motivato dalle analisi pervenute...ma sentiamo cosa dice Umbross al riguardo

**Comment by Rabelaiss** [comment]
anche oggi alcuni numeri strani
* campania 3901 tamponi e 4323 casi testati
* calabria stesso numero di tamponi e casi testati (1893)
* in basilicata e molise il 98-99% di tamponi sono casi testati

**Comment by umbros** [comment]
Ciao,
stiamo approfondendo il dato

**Comment by RiccardoBorchi** [comment]
Confermo il problema. Inoltre alla data del 24 Aprile c'è ancora l'errore che era stato segnalato un po' di tempo fa. A quella data, su base nazionale, ci sono 95.273 persone testate e 62.447 tamponi effettuati. Ciò è impossibile.

Potreste correggere?

Grazie.

**Comment by RiccardoBorchi** [comment]
Ciao @Rabelaiss, ho visto che hai chiuso questo "Issue", ma non mi risulta che il problema sia stato corretto. No?

**Comment by Rabelaiss** [comment]
@RiccardoBorchi ho chiuso perché il problema non può essere risolto dalla protezione civile

**Comment by RiccardoBorchi** [comment]
@Rabelaiss ok, però possono segnalarlo, ma forse lo hanno già fatto.
