### ISSUE TITLE
Precisions behind the reasons for intensive care admission

### ISSUE THREAD

**Issue by deepPhong** [pcm-dpc/COVID-19#86]
Hi! Would it be possible to have information on admission criteria to the intensive care for confirmed COVID-19 patients ? Do they all need mechanical ventilation ? Thanks a lot for your work and for making such data openly available, other countries need to follow your example!

**Type of issue**: richiesta di informazione

## Summary

What are the reasons for admission to the intensive care ?

## Public interest

The reported proportion of cases admitted to intensive care is pretty high (~10% of current cases) and some precisions behind admission criteria could be of use to other governments to anticipate their needs.

**Comment by v4l3r10** [comment]
Hi deepPhong,

for sure all patients in INTENSIVE CARE  need mechanical ventilation.
But we have two level of intensive care:
SubIntensive (without ventilation but 24/24 monitoring)
and Intensive  ( with ventilation)
I don't know if this data are referred only to Intensive or an aggregation of sub+intensive.

**Comment by umbros** [comment]
@deepPhong thank you, thanks for the compliments and this gives us the strength to go on despite we are also working on other fronts as national civil protection. Right now we manage two level of hospedalized (Hospitalised patients with symptoms and Intensive Care), subintensive is not managed and is referred to Hospitalised patients with symptoms). If we will expand our dataset we will announce that and we put it in CHANGELOG!
