### ISSUE TITLE
"denominazione_provincia": "In fase di definizione/aggiornamento" è diventata "In fase di definizione"

### ISSUE THREAD

**Issue by mydozer** [pcm-dpc/COVID-19#860]
Ciao ragazzi,
nel file dpc-covid19-ita-province.json

è stata modificata la denominazione delle province da "In fase di definizione/aggiornamento" a "In fase di definizione"

siccome utilizziamo il valore dell'attributo denominazione_provincia per clcolare i delta dopo la modifica odierna si sono verificate delle incongruenze.

Intendete mantenere il nuovo valore "In fase di definizione" oppure è possibile ripristinare "In fase di definizione/aggiornamento"?

Grazie!!

Esempio dati nel file dpc-covid19-ita-province.json
riga 387.090 dato di ieri

{
        "data": "2020-09-28T17:00:00",
        "stato": "ITA",
        "codice_regione": 13,
        "denominazione_regione": "Abruzzo",
        "codice_provincia": 979,
        "denominazione_provincia": **"In fase di definizione/aggiornamento"**,
        "sigla_provincia": null,
        "lat": null,
        "long": null,
        "totale_casi": 5,
        "note": null
    },

riga 389.028 dati odierni

{
        "data": "2020-09-29T17:00:00",
        "stato": "ITA",
        "codice_regione": 13,
        "denominazione_regione": "Abruzzo",
        "codice_provincia": 979,
        "denominazione_provincia": **"In fase di definizione"**,
        "sigla_provincia": null,
        "lat": null,
        "long": null,
        "totale_casi": 6,
        "note": null
    },

**Comment by umbros** [comment]
Ciao @mydozer grazie della segnalazione, è stato corretto.
