### ISSUE TITLE
Aggiunta colonna "Incremento Casi Testati" nella scheda riepilogativa

### ISSUE THREAD

**Issue by vi-enne** [pcm-dpc/COVID-19#862]
**Tipo di richiesta**:  richiesta di informazione | richiesta di dati | suggerimento di miglioramento (documentazione, label, _ecc_)

## Riassunto
Ciao,
sarebbe possibile aggiungere alla scheda riepilogativa giornaliera (di seguito quella del 3 ottobre 2020) la colonna Incremento Casi Testati?
![image](https://user-images.githubusercontent.com/44818674/94995349-af8fab80-056b-11eb-806d-ba498150f63f.png)

La colonna darebbe un'utile informazione aggiuntiva, in concerto con la colonna incremento Tamponi.

Per rendere la scheda piu' leggere, si potrebbe togliere una delle due colonne Casi totali (arancione o gialla) che al momento danno la stessa informazione e sono quindi ridondanti.

Grazie,
Vittorio

## Interesse pubblico
Maggiori informazioni utili e maggiore chiarezza

**Comment by umbros** [comment]
Ciao Vittorio, questo è il pdf che rilascia il Ministero, i dati ovviamente sono tutti calcolabili ma giro la richiesta.

Grazie
