### ISSUE TITLE
"sigla_provincia" Napoli assente

### ISSUE THREAD

**Issue by RiccardoBorchi** [pcm-dpc/COVID-19#863]
Tipo di issue:

- [X] Dati mancanti o errati: dpc-covid19-ita-province.json

- Regione: Campania
- Provincia: Napoli

## Riassunto

La provincia **Napoli** non ha valorizzato il campo "sigla_provincia" nel file _dpc-covid19-ita-province.json_.

**Comment by RiccardoBorchi** [comment]
Il campo "sigla_provincia" per Napoli è ancora _null_, non potete valorizzarlo a "NA"?

**Comment by miccoli** [comment]
Mi sono accorto anche io dell'errore, dovuto probabilmente ad un parsing errato dei file `.csv` per la conversione in formato JSON. Infatti molti SW interpretano la stringa "NA" come "not available" da cui l'errore.

Ho aperto la PR #931 che risolve l'errore per il passato, ma fino a quando non si risolve l'errore nella procedura di conversione continuerà a ripresentarsi.

Sto mettendo in piedi una procedura di QA automatica: è possibile vedere i risultati in <https://github.com/miccoli/COVID-19/actions?query=branch%3ACI++>, il codice python è nella PR #847

**Comment by miccoli** [comment]
Vedi anche #755.

**Comment by miccoli** [comment]
@umbros  Se può aiutare, l'errore è comparso nel commit 67f3d5b del 15 agosto: infatti:
```
$ git diff 67f3d5b~ 67f3d5b -- dati-json/dpc-covid19-ita-province.json | head -41
diff --git a/dati-json/dpc-covid19-ita-province.json b/dati-json/dpc-covid19-ita-province.json
index fd72951..6e15216 100644
--- a/dati-json/dpc-covid19-ita-province.json
+++ b/dati-json/dpc-covid19-ita-province.json
@@ -214,7 +214,7 @@
         "denominazione_regione": "Campania",
         "codice_provincia": 63,
         "denominazione_provincia": "Napoli",
-        "sigla_provincia": "NA",
+        "sigla_provincia": null,
         "lat": 40.83956555,
         "long": 14.25084984,
         "totale_casi": 0,
@@ -1878,7 +1878,7 @@
         "denominazione_regione": "Campania",
         "codice_provincia": 63,
         "denominazione_provincia": "Napoli",
-        "sigla_provincia": "NA",
+        "sigla_provincia": null,
         "lat": 40.83956555,
         "long": 14.25084984,
         "totale_casi": 0,
@@ -3542,7 +3542,7 @@
         "denominazione_regione": "Campania",
         "codice_provincia": 63,
         "denominazione_provincia": "Napoli",
-        "sigla_provincia": "NA",
+        "sigla_provincia": null,
         "lat": 40.83956555,
         "long": 14.25084984,
         "totale_casi": 0,
@@ -5206,7 +5206,7 @@
         "denominazione_regione": "Campania",
         "codice_provincia": 63,
         "denominazione_provincia": "Napoli",
-        "sigla_provincia": "NA",
+        "sigla_provincia": null,
         "lat": 40.83956555,
         "long": 14.25084984,
         "totale_casi": 3,
```
etc.

**Comment by miccoli** [comment]
È quasi un anno che questo issue è aperta, e l'errore (banale da correggere), è ancora presente:

```
{
  "data": "2021-09-19T17:00:00",
  "stato": "ITA",
  "codice_regione": 15,
  "denominazione_regione": "Campania",
  "codice_provincia": 63,
  "denominazione_provincia": "Napoli",
  "sigla_provincia": null,
  "lat": 40.83956555,
  "long": 14.25084984,
  "totale_casi": 268396,
  "note": null,
  "codice_nuts_1": "ITF",
  "codice_nuts_2": "ITF3",
  "codice_nuts_3": "ITF33"
}
```
possibile che sia così difficile produrre un JSON con  ```"sigla_provincia": "NA"``` invece che `null`?

**Comment by RiccardoBorchi** [comment]
> È quasi un anno che questo issue è aperta, e l'errore (banale da correggere), è ancora presente:
> 
> ```
> {
>   "data": "2021-09-19T17:00:00",
>   "stato": "ITA",
>   "codice_regione": 15,
>   "denominazione_regione": "Campania",
>   "codice_provincia": 63,
>   "denominazione_provincia": "Napoli",
>   "sigla_provincia": null,
>   "lat": 40.83956555,
>   "long": 14.25084984,
>   "totale_casi": 268396,
>   "note": null,
>   "codice_nuts_1": "ITF",
>   "codice_nuts_2": "ITF3",
>   "codice_nuts_3": "ITF33"
> }
> ```
> 
> possibile che sia così difficile produrre un JSON con `"sigla_provincia": "NA"` invece che `null`?

È quello che mi chiedo anche io.

**Comment by miccoli** [comment]
Un aggiornamento: dopo alcuni tentennamenti, sembra che da 42c8cecf il problema sia risolto :tada:

Un grazie ai gestori della repo!

**Comment by RiccardoBorchi** [comment]
> Un aggiornamento: dopo alcuni tentennamenti, sembra che da [42c8cec](https://github.com/pcm-dpc/COVID-19/commit/42c8cecff5e7e2e956ad415bfcf44116afbb120a) il problema sia risolto 🎉
> 
> Un grazie ai gestori della repo!

Finalmente, ottimo! 🎉
