### ISSUE TITLE
I nuovi_positivi di oggi in Abruzzo sono 50 non 48, e quindi quelli in Italia sono 2679 non 2677

### ISSUE THREAD

**Issue by Rabelaiss** [pcm-dpc/COVID-19#865]
Nelle note odierne si legge 

>La Regione Abruzzo segnala che oggi sono stati riscontrati n.50 nuovi positivi, ma sono stati sottratti dal totale 2 casi dei giorni passati in quanto già in carico ad altre Regioni.

tuttavia nel file dpc-covid19-ita-regioni-latest.csv il campo nuovi_positivi per l'Abruzzo è 48, non 50. Analogamente anche quello dell'Italia è errato e va corretto aggiungendo i 2 casi rimossi

**Comment by Paulsword** [comment]
Perchè non vedo alcuna nota del genere?

**Comment by Rabelaiss** [comment]
@Paulsword la trovi sia qua https://github.com/pcm-dpc/COVID-19/blob/master/note/dpc-covid19-ita-note.csv che qua https://github.com/pcm-dpc/COVID-19/blob/master/schede-riepilogative/regioni/dpc-covid19-ita-scheda-regioni-latest.pdf

**Comment by Rabelaiss** [comment]
@umbros ciao @umbros hai chiuso ma l'errore è ancora presente nel file [dpc-covid19-ita-regioni-20201006.csv](https://github.com/pcm-dpc/COVID-19/blob/master/dati-regioni/dpc-covid19-ita-regioni-20201006.csv) ossia ci sono 48 nuovi_positivi invece di 50, non correggete? grazie buon lavoro
