### ISSUE TITLE
Errore nota Calabria?

### ISSUE THREAD

**Issue by vi-enne** [pcm-dpc/COVID-19#866]
Tipo di issue:

- [x] Dati mancanti o errati 

- Regione: Calabria
- Provincia: 

## Riassunto

Oggi un'imprecisione pare essere nella nota comunicata dalla Regione Calabria: nel bollettino regionale odierno i migranti paiono essere 3 e non 23 come da nota.

https://portale.regione.calabria.it/website/portaltemplates/view/view.cfm?19304

![image](https://user-images.githubusercontent.com/44818674/95220251-4191f100-07c4-11eb-9069-0b987d1c723b.png)

So che le note sono comunicate direttamente dalle Regioni/PA.

Grazie!

**Attesa:** Verifica nota Calabria per informazione corretta

**Attuale:**  nota riporta 23 invece di 3 come segnalato da Regione Calabria nella proprio comunicazione regionale.

**Comment by Rabelaiss** [comment]
direi che 3 è molto più plausibile

**Comment by umbros** [comment]
Ciao stiamo verificando, le note sono inserite dalle Regioni stesse e non sono un dato verificabile matematicamente
