### ISSUE TITLE
Casi testati in Umbria negativi, per risolvere dovete correggete il numero di casi testati del 7/10

### ISSUE THREAD

**Issue by Rabelaiss** [pcm-dpc/COVID-19#868]
Dalle note si legge

> La Regione Umbria segnala che i casi testati di ieri erano 130552 e non come erroneamente digitato 135552; oggi il dato corretto è quello riportato, ossia 131965.

in seguito a questo avviso, mi sarei aspettato che aveste corretto il valore di ieri nel file [dpc-covid19-ita-regioni-20201007](https://github.com/pcm-dpc/COVID-19/blob/master/dati-regioni/dpc-covid19-ita-regioni-20201007.csv) tuttavia vedo che il valore tuttora presente è quello errato ossia 135552, nel file [dpc-covid19-ita-regioni-20201008.csv](https://github.com/pcm-dpc/COVID-19/blob/master/dati-regioni/dpc-covid19-ita-regioni-20201008.csv) è invece presente il valore corretto di oggi ossia 131965.

@umbros potreste correggere il valore di ieri e mettendo quello giusto ossia 130552 ? Altrimenti anche il totale di casi testati in Italia risulta errato

**Comment by umbros** [comment]
@Rabelaiss la modifica deve essere fatta dalla Regione stessa. Domani sarà bonificato il dato di ieri e oggi.

**Comment by Rabelaiss** [comment]
@umbros ciao so che non è colpa vostra, però né i casi di bolzano (#867) né i casi testati dell'umbria sono stati corretti ieri

**Comment by iguandroid** [comment]
> 
> 
> @umbros ciao so che non è colpa vostra, però né i casi di bolzano (#867) né i casi testati dell'umbria sono stati corretti ieri

Temo non abbiano intenzione di fare alcunché... almeno i file complessivi (quelli che non hanno la date nel filename e contengono lo storico di tutto) cosa ci vorrebbe a sistemarli? Chiunque allestisca qualcosa (o voglia fare un refresh dei dati completo) usa quelli... non capisco perché vi si debbano tenere dei valori palesemente incongruenti.

Boh.

**Comment by umbros** [comment]
@iguandroid stiamo attendendo la correzione che tecnicente non è nulla ma il processo del dato è formale...
