### ISSUE TITLE
CHIARIMENTI su Dati-Andamento-Nazionale

### ISSUE THREAD

**Issue by CT-igiul** [pcm-dpc/COVID-19#869]
-->

**Tipo di richiesta**:  richiesta di informazione | richiesta di dati | suggerimento di miglioramento (documentazione, label, _ecc_) | relativo alla pagina grafica

## Riassunto

 Ciao Umbros. 
Mi chiamo Luigi e trovo utile ed interessantissimo il lavoro che fai/fate e che seguo con attenzione da mesi analizzando i Vs dati personalmente dopo la pubblicazione delle 17:00. 
Vorrei solo un semplice chiarimento circa la differenza che c'è nella sezione  DATI-ANDAMENTO-NAZIONALE fra "variazione_totale_positivi". e  "nuovi_positivi".  Non dovrebbero coincidere? C'è qualcosa che mi sfugge?

Mi piacerebbe collaborare con Voi. 
Ho già un mio sito WiX (se vuoi visitarlo clicca sul link nella mia area personale CT-igiul) e vorrei rendere disponibili a tutti le analisi matematiche-statistiche che faccio, attingendo ai Vs dati, integrate da miei commenti personali.

Grazie in anticipo per la risposta. Luigi 

## Interesse pubblico

Capire meglio la genesi dei dati pandemici.

**Comment by Rabelaiss** [comment]
nella [wiki](https://github.com/pcm-dpc/COVID-19/blob/master/dati-andamento-covid19-italia.md) trove le rispettive descrizioni con anche le formule che spiegano come vengono calcolate e che quindi ti faranno capire il significato dei due dati

**Comment by CT-igiul** [comment]
Grazie. 
Lo guardo subito. 
Se vuoi vedere quello che pubblico su WiX, utilizzando i dati prelevati quotidianamente da questo sito ed integrati con le mie analisi matematico/statistiche puoi seguirmi su mio sito interattivo:  
https://www.luigitomaselli.com
dove pubblico blog, quasi quotidiani che raccontano la storia della pandemia dai primi di aprile.
Il sito è in aggiornamento e in questi giorni i dati PANDINAMICI non sono allineati quotidianamente poiché ho introdotto nuovi grafici "A BOLLE" per rendere più comprensibile l'evoluzione pandemica. Penso di riallinearlo entro stasera.
Ciao
Luigi

**Comment by CT-igiul** [comment]
Ho letto le descrizioni dei campi ma ho ancora un dubbio:
Quello che leggo è:
1) "variazione_totale_positivi" = Variazione del totale positivi (totale_positivi giorno corrente - totale_positivi giorno precedente)
2) "nuovi_positivi" =  Nuovi attualmente positivi (totale_casi giorno corrente - totale_casi giorno precedente)
L'unica differenza che leggo, solo nella spiegazione, è nell'identificazione "positivi" e "casi". 

QUESITO: Qual'è la differenza fra questo due identificazioni? Io non la capisco!
Ti allego una schermata parziale del mio database in excel nel quale avevo già identificato gli algoritmi della colonne dei casi NAZIONALI, che coincidono con le descrizioni che mi hai indicato.

Per capire il mio dubbio guarda i dati del 24/02/2020:
a) il TOTALE POSITIVI è pari a 221 (OK);
b) La VARIAZIONE TOTALE POSITIVI è pari a 0 (OK);
c) i NUOVI POSITIVI sono 221 (OK)

Adesso guarda i dati del 25/02/2020:
d) il TOTALE POSITIVI è pari a 311 (OK);
b) La VARIAZIONE TOTALE POSITIVI è pari a 90 (=311-221) (OK);
c) i NUOVI POSITIVI sono 93 (WHY?)  --> ne trovo 3 in più!  CHI SONO?

"POSITIVI" e "CASI" vogliono indicare la stessa cosa?
Il dubbio l'ho sempre avuto ma ho ritenuto fosse causato da una mia non corretta interpretazione e quindi nel tempo ho dimenticato di chiarirlo, impegnato a seguire e commentare l'evoluzione pandemica.

A ieri, 09/10/2020, la differenza che risconto fra VARIAZIONE TOTALE POSITIVI e i NUOVI POSITIVI è pari a 934 casi (= 5.372 - 4.158).

DOVE STO SBAGLIANDO? 
Mi aiutate a capire. GRAZIE
Luigi

![Schermata 2020-10-10 alle 10 24 11](https://user-images.githubusercontent.com/71124532/95650296-0c96de80-0ae3-11eb-9ae2-afb480824368.png)

**Comment by CT-igiul** [comment]
Per completezza, allego due grafici a BOLLE nei quali ho rappresentato i due parametri in discussione che per me devono essere gli stessi.


![Schermata 2020-10-09 alle 17 44 53](https://user-images.githubusercontent.com/71124532/95651029-98126e80-0ae7-11eb-8b1c-aa44cc11f4ae.png)


![Schermata 2020-10-09 alle 17 49 35](https://user-images.githubusercontent.com/71124532/95651035-a2346d00-0ae7-11eb-91c7-d63741ba6200.png)

**Comment by Rabelaiss** [comment]
Per trovare 93 devi applicare la formula scritta nella descrizione di nuovi_positivi ossia totale_casi giorno corrente - totale_casi giorno precedente, quindi 322-229 = 93.
Il numero totale_casi rappresenta tutte le persone in cui il tampone ha diagnosticato la presenza del virus.
Il numero totale_positivi rappresenta tutte le persone che si trovano in isolamento o in ospedale, ossia totale_positivi = totale_ospedalizzati + isolamento_domiciliare.

Ecco un esempio facilissimo per capire la differenza tra CASI e POSITIVI
Ieri in un paese si contavano 10 persone col covid ossia 10 POSITIVI, oggi 2 di questi sono guariti, 1 è deceduto e tramite tampone si trovano 4 nuovi CASI.
I POSITIVI passano quindi da 10 a 7 perché 2 sono guariti e 1 è deceduto, ma poi da 7 a 11 perché ci sono 4 nuovi CASI.
Quindi rispetto a ieri i CASI sono aumentati di 4 ma i POSITIVI sono aumentati di 1 (da 10 a 11).

**Comment by CT-igiul** [comment]
Grazie xxxx. 
Sei stato chiarissimo. Mi hai tolto un dubbio che avevo da sempre e che, fiducioso della correttezza dei dati, non avevo più sentito il bisogno di chiarire.
Adesso ritorno alla modifica del mio sito WiX con la consapevolezza che i dati pubblicati sono corretti.
Grazie ancora. Luigi

**Comment by CT-igiul** [comment]
Forse sarebbe stato meglio usare "NUOVI_CASI" piuttosto che "NUOVI_POSITIVI", nella colonna 322-229. 
Ma adesso è tutto chiaro.

**Comment by umbros** [comment]
Grazie @Rabelaiss per la risposta alla issue

**Comment by CT-igiul** [comment]
Grazie a te Umberto e a Rabelaiss per i chiarimenti ricevuti.
Vi informo che ho aggiornato il mio WiX con i vostri dati odierni. Mi
auguro possa interessarvi.
Luigi

https://www.luigitomaselli.com/post/pandemia-in-ebollizione-10-10-2020-torta-lombardo-campana-veneta-ancora-in-lievitazione


Il sab 10 ott 2020, 17:47 Umberto Rosini <notifications@github.com> ha
scritto:
