### ISSUE TITLE
Proposta API

### ISSUE THREAD

**Issue by alessiodl** [pcm-dpc/COVID-19#87]
**Tipo di richiesta**: suggerimento di miglioramento (accesso dati)

## Riassunto

Ho realizzato una semplice API alimentata dai vostri dati. Trovate la documentazione qui:
https://covid19-it-api.herokuapp.com/doc/

ho intenzione di creare nuovi end point nei prossimi giorni

## Interesse pubblico

Facilitare la creazione e la moltiplicazione delle applicazioni di consultazione dei dati.

**Comment by umbros** [comment]
Ciao @alessiodl stiamo pensando alla pubblicazione di API Rest ma, come potrai ben capire, le richieste potrebbero essere numerose e un servizio pubblico impone resilienza e sicurezza. Grazie intanto per la tua iniziativa 👍
