### ISSUE TITLE
Errore su Bolzano

### ISSUE THREAD

**Issue by LorenzoRuff** [pcm-dpc/COVID-19#870]
C'è un errore sul dato della P.A. Bolzano del 07/10/2020 in dpc-covid19-ita-province.csv. Risultano 0 casi.

**Comment by Rabelaiss** [comment]
il problema è stato segnalato 2 giorni fa qui #867 
umbros disse che il dato sarebbe stato corretto ieri ma è ancora sbagliato

**Comment by LorenzoRuff** [comment]
Anche oggi è sbagliato. Sono passati ormai tre giorni. Qualche speranza che venga corretto?

**Comment by umbros** [comment]
Ciao,
siamo in attesa della comunicazione di correzione chiudo la issue perchè duplicata #867
