### ISSUE TITLE
Totale casi positivi dashboard

### ISSUE THREAD

**Issue by mydozer** [pcm-dpc/COVID-19#873]
Tipo di issue:
Dati mancanti o errati dashboard

Ciao ragazzi,
mi sono accorto che c'è una discrepanza nel totale dei casi presenti sulla vostra dashboard (dato che stanno comunicando tutte le testate giornalistiche)

E' un inezia, ma vorrei capire se mi sfugge qualcosa nel calcolo. Vedi immagine sotto

![immagine](https://user-images.githubusercontent.com/61920330/95890058-8d740580-0d83-11eb-92ae-cc7e0df74ea3.png)

Grazie!!

**Comment by LorenzoRuff** [comment]
C'è stata una revisione in Emilia-Romagna. È scritto nelle note.

**Comment by mydozer** [comment]
> 
> 
> C'è stata una revisione in Emilia-Romagna. È scritto nelle note.

Chiaro. Mi sarei aspettato che il totale degli incrementi fosse consistente rispetto alla somma dei singoli addendi visto che è eseguito a consuntivo del giorno precedente.

**Comment by guivo** [comment]
Concordo con @mydozer. Se i vecchi file non sono stati modificati, l'integrale dei nuovi casi positivi non torna con il numero totale dei casi riportati.

**Comment by guivo** [comment]
Ad esempio, al momento, la somma della colonna nuovi positivi fa 365537, con una discrepanza che può solo che aumentare se non corretta ritoccando i numeri vecchi o riportando i nuovi positivi in maniera coerente.

**Comment by mydozer** [comment]
Anche oggi c'è discrepanza sul totale degli incrementi. I media riportano  9.338 come incremento giornaliero mente la somma dei singoli incrementi è 9.337 = 1.498 + 7.766 + 73

dalle note "Emilia Romagna comunica il seguente ricalcolo: in seguito a verifica sui dati comunicati nei giorni passati è stato eliminato 1 caso ( da Rimini ) in quanto giudicato non caso COVID-19"

Ci si aspetta quindi che incremento positivi fosse 1.499 e qundi dopo la correzione 1.499-1 = 1.498, ciò tuttavia non giustifica che ci sia un unità in più nel totale complessivo degli incrementi. Il totale dovrebbe essere una somma aritmetica degli incrementi.

Il problema persiste. Grazie!!

**Comment by mydozer** [comment]
![image](https://user-images.githubusercontent.com/61920330/96479261-fef6fc80-1238-11eb-87c4-433416dcfb97.png)

**Comment by umbros** [comment]
Grazie della segnalazione, come anticipato in un post l'obiettivo è quello di correggere i dati se sappiamo essere riferiti ad uno specifico giorno, la situazione ora non aiuta ma questa importante attività la faremo.

Grazie a tutti.
