### ISSUE TITLE
Dato tamponi Veneto 13/10/2020 discordante con comunicazione regionale

### ISSUE THREAD

**Issue by vi-enne** [pcm-dpc/COVID-19#874]
**Tipo di richiesta**:  richiesta di informazione

## Riassunto
Il dato sui tamponi totali effettuati comunicato dalla regione Veneto 13/10/2020 e' di 2.081.749, con un incremento di 11.794 rispetto a ieri.
[Conferenza stampa](https://www.facebook.com/watch/live/?v=3363420120434617&ref=watch_permalink) a 0:30

E' disaccordo con la tabella riepilogativa che ne riporta invece 2.074.007 in totale, con un incremento di 4.052.

![image](https://user-images.githubusercontent.com/44818674/95891025-7ff25780-0d52-11eb-869f-a7833969619e.png)

E' possibile sapere se questo data e' in fase di verifica?

Grazie

**Comment by Rabelaiss** [comment]
questa volta non sembra un errore di digitazione, chissà chi ha sbagliato questa volta nella catena di trasmissione dei dati

**Comment by umbros** [comment]
Ciao, il dato comunicato è comunicato dalla stessa regione, quindi potrebbe trattarsi di momenti diversi.

**Comment by vi-enne** [comment]
Ok, quindi mi sembra di capire che il dato non e' in fase di verifica. Grazie!
