### ISSUE TITLE
Chiarimenti casi testati

### ISSUE THREAD

**Issue by Spazio2001** [pcm-dpc/COVID-19#876]
Vorrei un chiarimento sui "casi testati". Leggendo la definizione data si capisce che se una persona viene testata due volte nei casi testati entra solo una volta. Ma se ad esempio è stata testata negativamente a maggio e viene testata oggi nuovamente la si conta due volte o sempre una? Le regioni dispongono quindi di database di tutte le persone testate?

**Comment by umbros** [comment]
Ciao @Spazio2001 #864
