### ISSUE TITLE
Uniformare il contenuto del campo "data" nei vari CSV

### ISSUE THREAD

**Issue by alessiodl** [pcm-dpc/COVID-19#88]
**Tipo di richiesta**: suggerimento di miglioramento (dati)

## Riassunto

Nel realizzare il mio Dashboard ho notato che il campo 'data', nel CSV dell'andamento nazionale, ha sempre il valore: 2020-XX-XX 18:00:00. Nel CSV dei dati regionali, invece, alcune date riportano invece 2020-XX-XX 17:00:00.
Non è una cosa drammatica, ma per far funzionare correttamente una funzionalità di scorrimento dello storico ho dovuto creare un workaround javascript che sostituisce l'orario lato client per quelle date in cui risulta diverso dalle altre. Potete vedere qui il risultato:

https://alessiodl.github.io/COVID19Dashboard/dist/index.html

E' possibile uniformare tutto alle ore 18?

## Interesse pubblico

Maggiore facilità di sviluppo per chi intende costruire applicazioni di consultazione dei dati

**Comment by umbros** [comment]
Ciao @alessiodl, l'orario è indicativo del momento di arrivo dei dati nel nostro processo interno arrotondato all'ora (è più per un'analisi interna) visto che l'aggiornamento è giornaliero puoi ignorare il campo ora e prendere solo il valore data.
