### ISSUE TITLE
Errore Orario pubblicazione dati README.md

### ISSUE THREAD

**Issue by edoardottt** [pcm-dpc/COVID-19#881]
Tipo di issue:

- [ ] Dati mancanti o errati 
- [x] Errore nella documentazione README.md
- [ ] Errore or mancanza nella dashboard 
- [ ] Problemi di visualizzazione nella dashboard 

- Regione: -
- Provincia: -

## Riassunto

Nel README.md c'è scritto: `Dati andamento COVID-19 Italia: ogni giorno alle 18:00`, ma vengono pubblicati un'ora prima

**Attesa:**

Dovrebbe essere `Dati andamento COVID-19 Italia: ogni giorno alle` **17:00**

**Attuale:**

**Comment by umbros** [comment]
Grazie del contributo @edoardottt
