### ISSUE TITLE
Nuovi casi in Basilicata 85 o 95?

### ISSUE THREAD

**Issue by Rabelaiss** [pcm-dpc/COVID-19#882]
Sul [sito della regione](https://regione.basilicata.it/giunta/site/giunta/detail.jsp?sec=100133&otype=1012&id=3069850&value=regione) Basilicata si legge 95 nuovi casi su 1201 tamponi.
Dai dati su github si ricava 85 nuovi casi su 1201 tamponi.
Essendo entrambe le fonti concordi sul numero di tamponi, anche i nuovi casi dovrebbero essere uguali.
Qual'è dunque il dato corretto?

**Comment by vi-enne** [comment]
Nelle comunicazioni regionali della Basilicata sono compresi anche le positività da tamponi analizzati in Basilicata, ma di persone residenti in altre Regioni/PA. In quella di oggi si legge:

_"9 residenti in Puglia e lì in isolamento; 1 residente in Campania e lì in isolamento; "_

Questi 10 non sono riportati nella tabella della PC per la Basilicata perché i casi sono indicati per residenza/domicilio.

Dovrebbero essere riportati in Puglia e Campania e immagino lo siano, ma non saprei come verificarlo.
