### ISSUE TITLE
Casi testati in P.A. Trento

### ISSUE THREAD

**Issue by Fuffo00339958** [pcm-dpc/COVID-19#884]
Tipo di issue:

- [X] Dati mancanti o errati 

- Regione: P.A Trento
- Provincia: 

## Riassunto

I casi testati nella P.A Trento sono giornalmente alcune centinaia (200-600), ieri di più: 1.047, oggi solo 3.

**Comment by umbros** [comment]
Buongiorno @Fuffo00339958 questo è quanto comunicato dalla Regione, possibile domani ci siano dei ricalcoli
