### ISSUE TITLE
*NOTANISSUE* Aiuto per beta testing

### ISSUE THREAD

**Issue by RickySal** [pcm-dpc/COVID-19#889]
Ciao a tutti!
Mi scuso in anticipo per l'off-topic, eliminate pure nel caso.
Ho appena terminato la seconda versione del mio portale con i grafici interattivi, avevo già pubblicato una issue a riguardo qualche mese fa.

Mi chiedevo se qualcuno fosse disposto a farsi un giro nella nuova versione e a riportare qui la propria esperienza con le nuove funzioni (il changelog lo trovate nella sidebar). Purtroppo il sito non è ancora ottimizzato per i dispositivi mobili ma ci sto lavorando.

Nel caso interessasse a qualcuno questo è il link per la beta: [https://www.graficicovid19.org/beta-multilang_89a9a428535c47636c73f6356fde3034/](https://www.graficicovid19.org/beta-multilang_89a9a428535c47636c73f6356fde3034/)

Vi ringrazio in anticipo!
Riccardo.

**Comment by LucaZeta** [comment]
Mi sono fermato ai cookie di terze parti, però sembra carino, curato e ben fatto.
Se vuoi confrontarti, senza cookies, https://covid19.zappi.me/

**Comment by RickySal** [comment]
Oh grazie però non voglio prendermi i meriti della libreria js per i grafici, hanno fatto quasi tutto loro :) 
I cookie di terze parti in realtà non ci sono ma ho dovuto scriverlo. Gli unici sono quelli di Google Analytics per capire un po' come migliorare (ad esempio la lingua inglese l'ho aggiunta dal momento in cui l'80% dei visitatori sono statunitensi). Gli altri dati che mi fornisce mi interessano poco sinceramente. I cookie tecnici permettono fondamentalmente il salvataggio delle preferenze della legenda (PS: **ho appena aggiunto i preset per salvare fino a 3 preferenze**).
La scala si può modificare con un trascinamento verticale sul grafico. E' uno zoom su un asse praticamente.

Visto il tuo sito. Molto interessanti i valori Rt e soprattutto le "previsioni". Se non si dovesse essere così precisi con il mouse nel passaggio sui vari punti sarebbe perfetto ma è comunque un ottimo lavoro.

**Comment by LucaZeta** [comment]
> Gli unici sono quelli di Google Analytics per capire un po' come migliorare (ad esempio la lingua inglese l'ho aggiunta dal momento in cui l'80% dei visitatori sono statunitensi)

Molto probabilmente sarà superfluo, però voglio suggerirti di filtrare, per un periodo, le indagini automatiche che regolarmente i molti motori di ricerca effettuano per la rete. E' sufficiente definire un file testuale nella root-directory del tuo web service con le seguenti caratteristiche:

`cat robot.txt

User-agent: *
Disallow: /
Disallow: /Directory1
Disallow: /Directory2
Disallow: /Directory3`

Se osservi una diminuzione nel rate di accesso al servizio, il delta osservato rappresenta il traffico generato dai motori di ricerca.

**Comment by RickySal** [comment]
@LucaZeta ok perfetto grazie per il suggerimento. I motori di ricerca dovrebbero però avere uno user-agent specifico che dovrei riuscire a filtrare in analytics giusto?

**Comment by LucaZeta** [comment]
**@RickySal** ogni motore di ricerca assegna ai suoi spider lo  stesso user-agent, ma i motori non sono pochi e non tutti noti.

Se sei interessato puoi approfondire [qui](https://www.keycdn.com/blog/web-crawlers).

**Comment by RickySal** [comment]
@LucaZeta Ok perfetto grazie per i consigli :)

**Comment by RickySal** [comment]
La beta è ora terminata. Grazie a tutti per il supporto e i consigli :D.

[https://graficicovid19.org](https://graficicovid19.org)
