### ISSUE TITLE
Split per comuni

### ISSUE THREAD

**Issue by sergiobrisio** [pcm-dpc/COVID-19#89]
**Tipo di richiesta**:  suggerimento di miglioramento (documentazione, label, _ecc_) 

## Riassunto
Vista la diffusione geografica all'interno di una provincia, potrebbe essere interessante avere i csv per comune (di residenza dei casi) in modo che si capisca su una mappa la reale distribuzione geografica.

## Interesse pubblico

Ho provato a caricare alcuni dati comunali delle province di Lecco, Bergamo e Brescia in mymaps di google e si nota immediatamente la distribuzione molto ampia dei casi per comune.

**Comment by umbros** [comment]
Ciao @sergiobrisio, attualmente non diamo i dati dei comuni, se verrà fatto sarà comunicato nei CHANGELOG, ma i dati di residenza non danno un'idea effettiva della popolazione in quel comune, io ad esempio sono residente in un comune della provincia di Teramo ma vivo a Roma, si potrebbe ragionare per domicilio e già il dato è più veritiero.
