### ISSUE TITLE
Numero nuovi ricoveri in terapia intensiva

### ISSUE THREAD

**Issue by robertocarta** [pcm-dpc/COVID-19#891]
**Tipo di richiesta**: richiesta di informazioni

## Riassunto

Esiste un modo o una fonte per ricavare il numero di nuovi ricoveri giornalieri in terapia intensiva? In questo momento abbiamo la variazione giornaliera di posti letto occupati, ma non sembra esserci modo di conoscere il numero giornaliero di nuovi ricoverati

## Interesse pubblico

Non è possibile smontare del tutto alcune obiezioni negazioniste senza questi dati.

**Comment by umbros** [comment]
Buongiorno Roberto, attualmente riusciamo ad avere quel dato che rappresenta i posti in terapia intensiva occupati da pazienti covid.

**Comment by robertocarta** [comment]
E invece esistono fonti per avere il numero di ricoveri totali (covid e non covid) in terapia intensiva?

**Comment by Rabelaiss** [comment]
@robertocarta  non che io sappia
