### ISSUE TITLE
Lazio casi odierni delle province diversi da quelli comunicati da Salute Lazio

### ISSUE THREAD

**Issue by Rabelaiss** [pcm-dpc/COVID-19#893]
I casi odierni nella regione Lazio sono 1687, tuttavia i casi sono ripartiti in modo diverso nelle province se confrontiamo i dati del Ministero con quelli della [Salute Lazio](https://www.facebook.com/101319221288183/posts/362331498520286/):
regione: casi salute lazio vs casi ministero
roma: 1058 vs 976
latina: 138 vs 65
frosinone: 281 vs 438
viterbo: 145 vs 174
rieti: 65 vs 3
nei casi comunicati dal ministero ce ne sono altri 31 in fase di verifica.
Sommando entrambi i set di dati si ottiene in entrambi i casi 1687, quindi i casi totali corrispondono ma la ripartizione nelle province no.
A cosa è dovuta questa discrepanza?

**Comment by vi-enne** [comment]
Secondo me è sempre il solito provincia di residenza/domicilio vs provincia di prelievo tampone.
