### ISSUE TITLE
TI e Ricoveri non aggiornati nelle Marche + Frosinone -200 casi

### ISSUE THREAD

**Issue by Rabelaiss** [pcm-dpc/COVID-19#895]
La regione Marche nel [bollettino di oggi](https://www.regione.marche.it/portals/0/Salute/CORONAVIRUS/DatiGORES/Gialla%2025102020%20ore%2012.pdf) segnala che oggi i pazienti in TI e ricovero sono rispettivamente 26 e 201, tuttavia nel file
https://github.com/pcm-dpc/COVID-19/blob/master/dati-regioni/dpc-covid19-ita-regioni-20201025.csv
sono riportati quelli di ieri, ossia 23 e 178

**Comment by DataEnthusiast84** [comment]
Mi associo alla discussione e segnalo che anche in Molise c'è una discrepanza: sono segnali +26 casi totali mentre altre fonti portano +101.

https://www.molisenews24.it/coronavirus-molise-dati-25-ottobre-2020-49003.html

**Comment by Rabelaiss** [comment]
quelli sono i casi di domani, il molise pubblica alle 18 quindi dopo che la protez civile pubblica i dati del giorno e quindi finiscono sul bollettino del giorno dopo

**Comment by Rabelaiss** [comment]
Altra anomalia i casi odierni di Frosinone che sono 200 in meno di quelli di ieri
