### ISSUE TITLE
Ammissioni ospedaliere giornaliere

### ISSUE THREAD

**Issue by pinoli** [pcm-dpc/COVID-19#897]
**Tipo di richiesta**:  richiesta di informazione

## Riassunto

Sto cercando di capire se è possibile ricavare il numero di ammissioni ospedaliere giornaliere, definito come il numero totale di nuove persone registrate come ospedalizzate con sintomi o direttamente in terapia intensiva.

Nel dataset parto da **Total Hospitalized** che è la somma di **ICU** + **Hospitalized with Symptoms**.
Se sottraggo semplicemente `Total Hospitalized[Oggi] `e `TotalHospitalized[Ieri]`, ottengo il saldo netto di persone in ospedale: nello stesso giorno è molto probabile che molte persone vengano dimesse. Invece del saldo, sto cercando di ricavare il numero di persone che, una volta recatesi in ospedale, sono state ricoverate o immediatamente spostate in terapia intensiva.

L'ipotesi è questa:

`TotalHospitalized[Oggi] - TotalHospitalized[Ieri] == NewHospitalAdmissions[Oggi] - NewRecovered[Oggi]`

Se questa uguaglianza regge, posso risolverla per **NewHospitalAdmissions[Oggi]** che è la grandezza che voglio ottenere

`NewHospitalAdmissions[Oggi] == TotalHospitalized[Oggi] - TotalHospitalized[Ieri] + NewRecovered[Oggi] `

Poichè `NewRecovered[Oggi] `è pari alla differenza tra `Recovered[Oggi]` e `Recovered[Ieri]`, presenti nel dataset, posso indirettamente calcolarmi il numero di persone ammesse in ospedale giornalmente tramite la formula:

`NewHospitalAdmissions[Oggi] == TotalHospitalized[Oggi] - TotalHospitalized[Ieri] + Recovered[Oggi] - Recovered[Ieri] `

Una perplessità è riguardo il flusso di persone ricoverate che vengono spostate successivamente in ICU in un determinato giorno: se ICU viene incrementato di 1 e HWS viene decrementato di -1 ad ogni passaggio da HWS a ICU, questo effetto non dovrebbe avere impatto sul conteggio.

Vi chiedo gentilmente di fare da avvocati del diavolo, per ora ho la sensazione che il calcolo sia corretto e vorrei inserire il dato nel mio [report](https://covid19.intelworks.io/).

## Interesse pubblico

Possibilità di estrarre ulteriori informazioni non immediatamente percebili dal dataset messo a disposizione.

**Comment by Paulsword** [comment]
Sei fuori strada perchè i recovered sono i guariti e provengono anche dalla categoria isolamenti domiciliari.

**Comment by omniaren** [comment]
Il dato TotalHospitalized, se non erro, lo devi vedere come:
ICU [ieri] + New ICU Admission - Today ICU Dismissions +  Hospitalized with Symptoms [ieri] + New Hospitalized with Symptoms Admission - Hospitalized with Symptoms Dismissions
Il dato di ICU e Hospitalized with Symptoms mi risulta essere il saldo a fine giornata e questo e' composto come sopra evidenziato.
Gia' vederlo cosi' ti dice che e' difficile, se non impossibile ricavare la grandezza che desideri, per quanto possa essere interessante.
Il tuo avvocato del diavolo.


    On Tuesday, October 27, 2020, 07:32:37 PM GMT+1, pinoli <notifications@github.com> wrote:  
 
 


Tipo di richiesta: richiesta di informazione

Riassunto

Sto cercando di capire se è possibile ricavare il numero di ammissioni ospedaliere giornaliere, definito come il numero totale di nuove persone registrate come ospedalizzate con sintomi o direttamente in terapia intensiva.

Nel dataset parto da Total Hospitalized che è la somma di ICU + Hospitalized with Symptoms.
Se sottraggo semplicemente Total Hospitalized[Oggi] e TotalHospitalized[Ieri], ottengo il saldo netto di persone in ospedale: nello stesso giorno è molto probabile che molte persone vengano dimesse. Invece del saldo, sto cercando di ricavare il numero di persone che, una volta recatesi in ospedale, sono state ricoverate o immediatamente spostate in terapia intensiva.

L'ipotesi è questa:

TotalHospitalized[Oggi] - TotalHospitalized[Ieri] == NewHospitalAdmissions[Oggi] - NewRecovered[Oggi]

Se questa uguaglianza regge, posso risolverla per NewHospitalAdmissions[Oggi] che è la grandezza che voglio ottenere

NewHospitalAdmissions[Oggi] == TotalHospitalized[Oggi] - TotalHospitalized[Ieri] + NewRecovered[Oggi] 

Poichè NewRecovered[Oggi] è pari alla differenza tra Recovered[Oggi] e Recovered[Ieri], presenti nel dataset, posso indirettamente calcolarmi il numero di persone ammesse in ospedale giornalmente tramite la formula:

NewHospitalAdmissions[Oggi] == TotalHospitalized[Oggi] - TotalHospitalized[Ieri] + Recovered[Oggi] - Recovered[Ieri] 

Una perplessità è riguardo il flusso di persone ricoverate che vengono spostate successivamente in ICU in un determinato giorno: se ICU viene incrementato di 1 e HWS viene decrementato di -1 ad ogni passaggio da HWS a ICU, questo effetto non dovrebbe avere impatto sul conteggio.

Vi chiedo gentilmente di fare da avvocati del diavolo, per ora ho la sensazione che il calcolo sia corretto e vorrei inserire il dato nel mio report.

Interesse pubblico

Possibilità di estrarre ulteriori informazioni non immediatamente percebili dal dataset messo a disposizione.

**Comment by pinoli** [comment]
come non detto 😁
grazie ad entrambi per i commenti

**Comment by MicheleAlfinito** [comment]
Vedi #886 per un esempio numerico.
Il ragionamento formale che ho dedotto dallo studio dei movimenti ospedalieri sin dai primi conteggi (dal 24/2 in poi) è il seguente:

(1)  Cp=Vp+M+DimG

Dove:
Cp sono i nuovi_positivi
Vp è la variazione giornaliera del totale_positivi o variazione positivi
M è la variazione giornaliera dei deceduti
DimG è la variazione giornaliera dei dimessi_guariti
Nota: per variazione giornaliera si intende la differenza fra il totale oggi –(meno) ieri.

E’ evidente che:

(2) Vp=Vq+Vo dove:

Vq è la variazione giornaliera dei isolamento_domiciliare (o variazione quarantene)
Vo è la variazione giornaliera dei totale_ospedalizzati che, ricordo, comprende anche le terapie intensive.
Sostituendo la (2) nella (1):

(3) Cp = Vq + Vo + M + DimG

Definisco ora un insieme nuovo, Cc così espresso: Cc = Vo + M (*). Cc sono i nuovi casi clinici.

Infatti, sostituendo Cc nella (3) posso scrivere:

(4) Cp = Cc + Vq + DimG ed è possibile così ricavarci Cc per verificare la correttezza della sua definizione:

(5) Cc = Cp – Vq – DimG.

E’ evidente cioè che se ai nuovi casi tolgo le occupazioni giornaliere delle quarantene e le uscite dei dimessi/guariri, ottengo i nuovi ricoveri in ospedale.

Consideriamo ora l’insieme Q, dei nuovi in quarantena.

Possiamo scrivere:

(6) Q = Cp – Cc. Sostituendo la (6) nella (5) ricaviamo:

(7)  Cc=Cp-Cc+Cc-Vq-DimG

Cioè,

(8) Q – Vq – DimG = 0

Ed ecco così la definizione congruente di Q:

(9) Q (nuovi in quarantena) = Vq + DimG (**)

(*) nota: se Vo è negativo dopo averlo sommato algebricamente ad M abbiamo sicuramente dei dimessi;
(**) nota: se Q è negativo abbiamo sicuramente una migrazione dalle quarantene ai clinici.
