### ISSUE TITLE
Casi in Liguria localizzati in Africa

### ISSUE THREAD

**Issue by enricorotundo** [pcm-dpc/COVID-19#9]
![Screenshot 2020-03-07 at 18 46 22](https://user-images.githubusercontent.com/4340327/76148179-14e9ef80-60a4-11ea-8a52-c17bf440e2a0.jpg)

**Comment by pescetti** [comment]
Lo vedo anch'io nelle mie visualizzazioni personali su mappa, il problema è qui:

https://github.com/pcm-dpc/COVID-19/blob/master/dati-json/dpc-covid19-ita-province.json#L5182

In altre parole, i casi che sono in Liguria ma ancora in fase di definizione/aggiornamento (cioè non assegnati a una provincia) hanno latitudine/longitudine 0/0 che è effettivamente quel punto vicino all'Africa. Succede ovviamente per tutte le regioni.

Non saprei quale soluzione suggerire, forse il centroide della regione? O (per semplificare, ma forse è troppo grossolano) il capoluogo? Oppure ometterli dalle visualizzazioni per provincia?

**Comment by sabas** [comment]
Metterli null piuttosto? Oppure il centroide potrebbe essere più neutrale.

Quel punto è una nota isola :) https://en.wikipedia.org/wiki/Null_Island

**Comment by etrevis** [comment]
Penso non sia il caso di ometterli, i conti non tornerebbero più con i totali.
Una possibilità è non assegnarli un valore numerico, ma questo potrebbe generare errori se non gestito accuratamente.
Assegnare le coordinate del capoluogo porterebbe ad overstimare il conteggio se solo lat/long vengono usate.

Credo che la migliore opzione si di mantenere 0,0

**Comment by sabas** [comment]
Intendevo "lat": null e "lon": null, dovrebbe essere gestito perché null è un valore valido

**Comment by pescetti** [comment]
Dal punto di vista dei dati, in JSON `null` è sicuramente l'opzione migliore.

Con `null` il problema viene (giustamente, direi) spostato sulla visualizzazione. Poi ciascuno deciderà se ignorare i dati localizzati in `null`, con rischio di fuorvianti omissioni, o gestirli in qualche modo.

Nelle mie mappe li sto ridistribuendo, per la sola visualizzazione, in proporzione ai dati provinciali: se Campobasso ha 100 casi, Isernia 50 e "Molise non assegnati" sono 15, ne colloco 10 a Campobasso e 5 a Isernia (i numeri nell'esempio sono di fantasia).

**Comment by umbros** [comment]
Ciao, innanzitutto grazie per la segnalazione, per i dati ancora assegnati non è possibile ridistribuirli perchè il dato deve essere preciso, vedremo di trovare una soluzione grafica o tabellare per indicarli. Per quanto riguarda la localizzazione in Africa dei dati "non assegnati" era dovuto a lat = 0 e long = 0 messo un filtro se lat e long = 0 non mostrare il punto.

![immagine](https://user-images.githubusercontent.com/4085151/76152877-09f38700-60c5-11ea-8a75-a5637e7af5c4.png)

**Comment by pescetti** [comment]
Grazie ma il problema in questo caso era nei dati, non solo nella visualizzazione.

Sistemare una specifica visualizzazione (la vostra dashboard) non risolve il problema dei dati.

Un dataset con dati localizzati in `(0,0)` è sbagliato. Un dataset con dati localizzati in `(null, null)` è più facilmente gestibile, altrimenti tutti quanti devono implementare un trucchetto come quello implementato da voi per escluderli.

Questo trucchetto nelle visualizzazioni basate su aree (al contrario della vostra che è basata su punti) tra l'altro crea risultati fuorvianti, quindi la cosa migliore sarebbe davvero usare `null` e non `0` nei dati JSON.

Suggerirei di riaprire la issue almeno come possibile miglioramento futuro.
