### ISSUE TITLE
Lazio discrepanze

### ISSUE THREAD

**Issue by ChiaraCCC** [pcm-dpc/COVID-19#90]
Tipo di issue:

- [x] Dati mancanti o errati 
- [ ] Errore nella documentazione 
- [ ] Errore or mancanza nella dashboard 
- [ ] Problemi di visualizzazione nella dashboard 

## Riassunto
Il numero di tamponi effettuati nel Lazio: 1929 sia nei file dell'8/03 che del 9/03, eppure aumentano i casi confermati.

**Comment by umbros** [comment]
Ciao @ChiaraCCC non hanno comunicato un aggiornamento sul dato o non sono stati fatti, però quello è il dato ufficiale comunicato al Ministero della Salute.

**Comment by ChiaraCCC** [comment]
Si ok, sicuramente è il dato ufficiale. Ma se puoi solleciterei un controllo del dato che palesemente non è accurato. Come fanno i casi confermati ad aumentare se non aumentano i tamponi? 

Grazie.
