### ISSUE TITLE
Grafico "Nuovi positivi" errato

### ISSUE THREAD

**Issue by MarioMarietto** [pcm-dpc/COVID-19#900]
Tipo di issue:

- [ ] Dati mancanti o errati 
- [ ] Errore nella documentazione
- [x] Errore or mancanza nella dashboard 
- [ ] Problemi di visualizzazione nella dashboard 

## Riassunto

Nel grafico: "Nuovi positivi", gli ultimi dati riportati sono del 16/07/2020

**Attesa:**

I dati dovrebbero essere aggiornati al 29/10/2020

**Comment by umbros** [comment]
Il grafico è stato corretto il giorno stesso, si trattava di un errore della piattaforma arcgis. Grazie della segnalazione.
