### ISSUE TITLE
Errore dataset nazionale (.csv)

### ISSUE THREAD

**Issue by Achab94** [pcm-dpc/COVID-19#908]
Le ultime due righe sono ripetute.

**Comment by nicola-masarone** [comment]
Confermo, 4 e 5 novembre ripetuti due volte

**Comment by umbros** [comment]
Corretto

**Comment by nicola-masarone** [comment]
C'era anche una discrepanza nel giorno 4 novembre, colonna 'deceduti'
![Istantanea_2020-11-05_17-34-27](https://user-images.githubusercontent.com/50139878/98269082-9e342780-1f8d-11eb-9a09-588c30cc6e41.png)

**Comment by Achab94** [comment]
@nicola-masarone hanno tenuto la 258 e cancellato la 256. Non ricordo quale era il valore pubblicato ieri, hai idea? :(
