### ISSUE TITLE
Record del 04/11/2020 e del 05/11/2020 ripetuti in riepilogo nazionale

### ISSUE THREAD

**Issue by emazep** [pcm-dpc/COVID-19#909]
Nel file:
https://github.com/pcm-dpc/COVID-19/blob/master/dati-andamento-nazionale/dpc-covid19-ita-andamento-nazionale.csv

le ultime 2 righe (corrispondenti al 04/11/2020 e al 05/11/2020) risultano ripetute, ovvero sono la ripetizione delle 2 righe precedenti.

**Comment by Achab94** [comment]
Già segnalato nella #908 :)

**Comment by emazep** [comment]
> 
> 
> Già segnalato nella #908 :)

OK, grazie! :-)

**Comment by umbros** [comment]
Corretto #908
