### ISSUE TITLE
Regione mancante

### ISSUE THREAD

**Issue by cloud78** [pcm-dpc/COVID-19#91]
**Tipo di richiesta**: richiesta di informazione

## Riassunto
C'è un motivo per cui la regione del "Trentino-AltoAdige" è stata divisa in due regioni (Bolzano e Trento) nella csv delle regioni?

## Interesse pubblico

Dati coerenti

**Comment by umbros** [comment]
@cloud78 la Regione Trentino Alto Adige è divisa per Provincia Autonoma di Bolzano e Provincia Autonoma di Trento, riportano tutte e due  il codice 04 nel riepilogo Regioni e la stessa cosa riporta 04 come Regione nei dati per Provincia.

**Comment by cloud78** [comment]
OK, capisco. 19 regioni + 2 province autonome con lo stesso codice regione. 
Non mi é comunque chiara la suddivisione, dato che si tratta di province e non di regioni.
