### ISSUE TITLE
Duplicazione dati JSON in 04/11 e 05/11/2020

### ISSUE THREAD

**Issue by vellons** [pcm-dpc/COVID-19#910]
Tipo di issue:

- [X] Dati mancanti o errati
- [ ] Errore nella documentazione
- [ ] Errore or mancanza nella dashboard
- [ ] Problemi di visualizzazione nella dashboard

## Riassunto
Nel seguente file i dati del 04/11/2020 e del 05/11/2020 risultano duplicati.
dati-json/dpc-covid19-ita-andamento-nazionale.json

**Attesa:**
Rimuzione delle informazioni duplicate.

**Comment by floatingpurr** [comment]
PS: come citavo nella #911, si tratta dello stesso errore corretto nei CSV (b789e15), che però va fixato anche nei JSON

**Comment by LucaZeta** [comment]
Il file da correggere eliminando gli ultimi due record (duplicati) è il "dpc-covid19-ita-andamento-nazionale.json"

**Comment by floatingpurr** [comment]
In realtà potrebbe non bastare nemmeno eliminare i due record perché non sono consistenti. Per esempio, i decessi del 4/11 in un documento sono ´39764`, mentre nell'altro `39747`.  Qual è il dato giusto?

Non so se ci sono altri valori inconsistenti ma serve un check più specifico.

Cc: @umbros 


```json
[
    {
        "data": "2020-11-04T17:00:00",
        "stato": "ITA",
        "ricoverati_con_sintomi": 22116,
        "terapia_intensiva": 2292,
        "totale_ospedalizzati": 24408,
        "isolamento_domiciliare": 418827,
        "totale_positivi": 443235,
        "variazione_totale_positivi": 25093,
        "nuovi_positivi": 30550,
        "dimessi_guariti": 307378,
        "deceduti": 39764,
        "casi_da_sospetto_diagnostico": 520799.0,
        "casi_da_screening": 269578.0,
        "totale_casi": 790377,
        "tamponi": 16497767,
        "casi_testati": 10021035.0,
        "note": null
    },
    {
        "data": "2020-11-05T17:00:00",
        "stato": "ITA",
        "ricoverati_con_sintomi": 23256,
        "terapia_intensiva": 2391,
        "totale_ospedalizzati": 25647,
        "isolamento_domiciliare": 446701,
        "totale_positivi": 472348,
        "variazione_totale_positivi": 29113,
        "nuovi_positivi": 34505,
        "dimessi_guariti": 312339,
        "deceduti": 40192,
        "casi_da_sospetto_diagnostico": 541173.0,
        "casi_da_screening": 283706.0,
        "totale_casi": 824879,
        "tamponi": 16717651,
        "casi_testati": 10155585.0,
        "note": null
    },
    {
        "data": "2020-11-04T17:00:00",
        "stato": "ITA",
        "ricoverati_con_sintomi": 22116,
        "terapia_intensiva": 2292,
        "totale_ospedalizzati": 24408,
        "isolamento_domiciliare": 418827,
        "totale_positivi": 443235,
        "variazione_totale_positivi": 25093,
        "nuovi_positivi": 30550,
        "dimessi_guariti": 307378,
        "deceduti": 39747,
        "casi_da_sospetto_diagnostico": 520799.0,
        "casi_da_screening": 269578.0,
        "totale_casi": 790377,
        "tamponi": 16497767,
        "casi_testati": 10021035.0,
        "note": null
    },
    {
        "data": "2020-11-05T17:00:00",
        "stato": "ITA",
        "ricoverati_con_sintomi": 23256,
        "terapia_intensiva": 2391,
        "totale_ospedalizzati": 25647,
        "isolamento_domiciliare": 446701,
        "totale_positivi": 472348,
        "variazione_totale_positivi": 29113,
        "nuovi_positivi": 34505,
        "dimessi_guariti": 312339,
        "deceduti": 40192,
        "casi_da_sospetto_diagnostico": 541173.0,
        "casi_da_screening": 283706.0,
        "totale_casi": 824879,
        "tamponi": 16717651,
        "casi_testati": 10155585.0,
        "note": null
    }
]
```

**Comment by Rabelaiss** [comment]
@floatingpurr 39764 è il valore errato di ieri, 39747 è quello corretto che tiene conto delle comunicazioni di toscana e calabria (vedi avvisi)

**Comment by floatingpurr** [comment]
Lo definisci _rarissimo_ perché negli altri casi le note di rettifica non hanno generato correzioni retroattive?

**Comment by Rabelaiss** [comment]
@floatingpurr esatto, ad esempio un avviso di ieri riportava che
> La Regione Campania comunica che nei dati di ieri, per mero errore materiale, sono stati aggiunti 45 posti di Terapia Intensiva in più.

quindi il dato del 3/11 dovrebbe essere stato corretto da 227 a 182, ma nel file [dpc-covid19-ita-regioni-20201103.csv](https://github.com/pcm-dpc/COVID-19/blob/master/dati-regioni/dpc-covid19-ita-regioni-20201103.csv) è ancora presente 227

**Comment by floatingpurr** [comment]
Cavolo, sarebbe meglio adottare una policy consistente! @umbros, cosa ne pensi?

**Comment by umbros** [comment]
corretto. @floatingpurr i dati sono quelli che il ministero invia, il procedimento di consegna è ufficiale e solo il Ministero può cambiarli; stiamo collaborando per allineare quando ci sono dei ricalcoli nei giorni precedenti.

**Comment by floatingpurr** [comment]
Grazie @umbros per il feedback.

Immagino ci sia alle spalle un processo di certificazione del dato non banale che guida il tutto. Se fosse possibile portare un _caveat_ al tavolo, si potrebbe sottolineare come i ricalcoli nella serie storica vadano trattati in modo coerente per evitare di generare confusione.
