### ISSUE TITLE
Regione P.A Bolzano del 6/11/2020 imputazione formato CSV errata

### ISSUE THREAD

**Issue by Franceskino** [pcm-dpc/COVID-19#913]
Tipo di issue:

- [x] Dati mancanti o errati in doc: covid-19-ita-regioni.csv 
- [ ] Errore nella documentazione 
- [ ] Errore or mancanza nella dashboard 
- [ ] Problemi di visualizzazione nella dashboard 

- Regione: P.A. Bolzano
- Provincia: 

## Riassunto

la riga della regione in oggetto nel giorno 6/11/2020 spezza la riga con un doppio invio che causa errori nelle query di mancato riconoscimento formato data .

**Attesa:**

**Attuale:**

**Comment by tamamma** [comment]
Confermo, il problema sembra essere nel campo "note" della riga 13 riguardante i dati della PA d Bolzano, infatti vengono viste 24 righe anzichè 22 perchè le note di quella riga vengono viste come 2 righe ulteriori in maniera errata

**Comment by umbros** [comment]
Risolto con l'ultima commit, grazie
