### ISSUE TITLE
Caasi Totali Roma

### ISSUE THREAD

**Issue by 404MassiNotFound** [pcm-dpc/COVID-19#916]
Tipo di issue:

- [x] Dati mancanti o errati 
- [ ] Errore nella documentazione 
- [ ] Errore or mancanza nella dashboard 
- [ ] Problemi di visualizzazione nella dashboard 

- Regione: Lazio
- Provincia: Roma

## Riassunto

Durante un grafico in cui interpolavo in ascisse i casi totali e in ordinati i nuovi casi rispetto al giorno precedente, ho notato un valore negativo (teoricamente assurdo) in data 24/06/2020, ovvero: casi_totali(24/06) - casi_totali(23/06) < 0

**Attesa:**
Un numero maggiore di zero

**Attuale:**
Un numero minore di zero

**Comment by umbros** [comment]
Corretto quanto da te riportato i dati dovrebbero essere modificati con l'invio di domani

**Comment by 404MassiNotFound** [comment]
Visto l'esito positivo della verifica mi permetto di cercarle tutte gli errori che riesco ad estrapolare dello stesso tipo e linkarle un documento con la posizione degli stessi.
