### ISSUE TITLE
App per sufruire dei dati

### ISSUE THREAD

**Issue by croccio** [pcm-dpc/COVID-19#918]
Ho sviluppato un'app mobile (con kotlin-natice quindi compatibile con iOS, android, web Mac ecc ecc con un piccolissimo sforzo di lavoro) e volevo sapere come è possibile chiedere una certificazione per caricare l'app  sugli store o magari collaborare con voi sul progetto covid. 
Grazie 

PS: se vi serve un collaboratore sono disponibile :D https://www.linkedin.com/mwlite/in/antonioscardigno

**Comment by umbros** [comment]
@croccio non certifichiamo app. Grazie.
