### ISSUE TITLE
Issues in the "dati-regioni" dataset 2020-03-10

### ISSUE THREAD

**Issue by xfranky** [pcm-dpc/COVID-19#92]
Type of issue:

- [x] Incorrect or missing data : 
- [ ] Incorrect or missing documentation 
- [ ] Incorrect or missing data in the dashboard 
- [ ] Layout problem in the dashboard 

## Summary
Opening a thread for issues found with the data in the 2020-03-10 "dati-regioni" data set

**Expected:**
Friuli Venezia Giulia is reported as "Friuli Venezia Giulia" in "denominazione_regione" for the 2020-03-10 data point (that is the spelling in all previous records)

**Actual:** 
Friuli Venezia Giulia is reported as "Friuli V. G."

**Comment by umbros** [comment]
Thank you for suggestion, I suggest to use che Region Code!

**Comment by xfranky** [comment]
That makes sense, but then I would suggest publishing a lookup table of region codes and names (and than also province codes and names) together with the data sets.

(actually that sounds like something I could push myself... :smirk: )

**Comment by xfranky** [comment]
On a second thought, using codice_regione to look up names will cause issues because of Trento and Bolzano using the same number while being reported separately in the data set :thinking: 

Trying to be more specific here, I'm calculating trends for regions, and in order to relate the data for a specific region along time and then display the trend linked to each region, I need the following:

- either all names are equal across time and I can search by name, or
- each "region" in the data set has a unique code (not happening for Trento and Bolzano)

There are workarounds, but all the ones I can think of require some sort of ETL either checking the names or aggregating figures for Trento and Bolzano into one region before loading the data.

Any suggestions?

**Comment by mydozer** [comment]
> 
> 
> Thank you for suggestion, I suggest to use che Region Code!

@umbros region code is not unique for all data, see P.A. Trento and Bolzano

Friuli has different denominations and the same code
`{
    "data" : "2020-03-10 18:00:00",
    "stato" : "ITA",
    "codice_regione" : 6,
    "denominazione_regione" : "Friuli Venezia Giulia",
    "lat" : 45.6494354,
    "long" : 13.76813649,
    "ricoverati_con_sintomi" : 27,
    "terapia_intensiva" : 6,
    "totale_ospedalizzati" : 33,
    "isolamento_domiciliare" : 77,
    "totale_attualmente_positivi" : 110,
    "nuovi_attualmente_positivi" : 21,
    "dimessi_guariti" : 3,
    "deceduti" : 3,
    "totale_casi" : 116,
    "tamponi" : 1602
}
{
    "data" : "2020-03-11 17:00:00",
    "stato" : "ITA",
    "codice_regione" : 6,
    "denominazione_regione" : "Friuli V. G. ",
    "lat" : 45.6494354,
    "long" : 13.76813649,
    "ricoverati_con_sintomi" : 16,
    "terapia_intensiva" : 5,
    "totale_ospedalizzati" : 21,
    "isolamento_domiciliare" : 89,
    "totale_attualmente_positivi" : 110,
    "nuovi_attualmente_positivi" : 0,
    "dimessi_guariti" : 10,
    "deceduti" : 6,
    "totale_casi" : 126,
    "tamponi" : 2073
}`

denominazione_regione has an additional traling space "Friuli V. G. "
Autonomous provinces has the same code and different denominations

`{
    "data" : "2020-02-24 18:00:00",
    "stato" : "ITA",
    "codice_regione" : 4,
    "denominazione_regione" : "P.A. Bolzano",
    "lat" : 46.49933453,
    "long" : 11.35662422,
    "ricoverati_con_sintomi" : 0,
    "terapia_intensiva" : 0,
    "totale_ospedalizzati" : 0,
    "isolamento_domiciliare" : 0,
    "totale_attualmente_positivi" : 0,
    "nuovi_attualmente_positivi" : 0,
    "dimessi_guariti" : 0,
    "deceduti" : 0,
    "totale_casi" : 0,
    "tamponi" : 1
}

{
    "data" : "2020-02-24 18:00:00",
    "stato" : "ITA",
    "codice_regione" : 4,
    "denominazione_regione" : "P.A. Trento",
    "lat" : 46.06893511,
    "long" : 11.12123097,
    "ricoverati_con_sintomi" : 0,
    "terapia_intensiva" : 0,
    "totale_ospedalizzati" : 0,
    "isolamento_domiciliare" : 0,
    "totale_attualmente_positivi" : 0,
    "nuovi_attualmente_positivi" : 0,
    "dimessi_guariti" : 0,
    "deceduti" : 0,
    "totale_casi" : 0,
    "tamponi" : 3
}`
