### ISSUE TITLE
Dati del 2020-11-10 (province) riportati due volte.

### ISSUE THREAD

**Issue by CloudItaly** [pcm-dpc/COVID-19#923]
Si segnala che nel JSON https://raw.githubusercontent.com/pcm-dpc/COVID-19/master/dati-json/dpc-covid19-ita-province.json, i dati odierni (10novembre2020) sono riportati due volte.

**Comment by tonysamperi** [comment]
Confermo!

**Comment by alexodus** [comment]
RAGZZI, DOVETE VALIDARE I DATI!!!! SONO 7 MESI CHE VE LO DICO!

**Comment by umbros** [comment]
corretto, grazie
