### ISSUE TITLE
Mancanza di dati sulla Dashboard

### ISSUE THREAD

**Issue by asappia** [pcm-dpc/COVID-19#925]
Tipo di issue:

- [ ] Dati mancanti o errati 
- [ ] Errore nella documentazione 
- [ ] Errore or mancanza nella dashboard 
- [X] Problemi di visualizzazione nella dashboard 

- Regione: Piemonte
- Provincia: 

## Riassunto
http://opendatadpc.maps.arcgis.com/apps/opsdashboard/index.html#/b0c68bce2cce478eaac82fe38d4138b1
Nella mappa della Dashboard non sono visibili i dati relativi ad alcune regioni. Ho notato questa cosa con il Piemonte, selezionando la data del 11/11/2020. L'ultimo dato visibile sulla mappa della Dashboard è del 3/11/2020. Selezionando una qualunque data successiva al 3/11/2020 il cerchio relativo al Piemonte non è più visibile. 

**Attesa:**

Il cerchio dimensionato sui dati per la regione Piemonte
**Attuale:**

**Comment by umbros** [comment]
Corretto grazie!
