### ISSUE TITLE
Richiesta di dati sui posti disponibili

### ISSUE THREAD

**Issue by gianlab** [pcm-dpc/COVID-19#926]
Salve,
nel report qui pubblicato https://www.kaggle.com/gianlab/esplorazione-dati-covid-19-italia per l'aggiornamento dei dati sono costretto a fare copia e incolla in un foglio di calcolo dei dati forniti dall'agenzia agenas sui posti disponibili in terapia intensiva e per i ricoveri e aggiornare il dataset su kaggle.
Potreste per favore caricarli su github in modo che risulta più agevole importarli nei reports?

**Comment by umbros** [comment]
Ciao @gianlab in ottica di interoperabilità i dati possono essere combinati con altri disponibili su altri repository.
