### ISSUE TITLE
Dati complessivi regioni illeggibili

### ISSUE THREAD

**Issue by dariovz** [pcm-dpc/COVID-19#927]
Il file dpc-covid19-ita-regioni.csv è troppo grande per permettere una visualizzazione tabellare fruibile.
Se possibile sarebbe da dividere per periodi, ad es da Febbraio a Maggio, da Giugno a Settembre e così via, in modo da non eccedere le dimensioni massime che permettono la corretta visualizzazione.

Grazie

**Comment by Doc73** [comment]
Mi permetto di estendere la medesima richiesta anche al corrispondente file delle province, da tempo eccedente le dimensioni massime, o almeno quelle di Google Fogli.

Grazie mille

**Comment by umbros** [comment]
Ciao a tutti,
non per accogliere la richiesta ma per una questione di processi da dover gestire, noi rilasciamo così i dati complessivi in questo modo, potrebbero essere lavorati per essere splittati lato consumatori. Su sistemi di gestione dei dati "professionali" non risultano problemi.
