### ISSUE TITLE
Numero negativo di nuovi casi 

### ISSUE THREAD

**Issue by gabri94** [pcm-dpc/COVID-19#93]
Tipo di issue:

- [x] Dati mancanti o errati 
- [ ] Errore nella documentazione 
- [ ] Errore or mancanza nella dashboard 
- [ ] Problemi di visualizzazione nella dashboard 

## Riassunto

Analizzando i dati csv regionali mi sono accorto che il numero di "nuovi_attualmente_positivi" in lombardia per il giorno di oggi (10-3-2020) è pari  a -63.
Sto interprentando male io questi dati? Mi aspettavo un dato sempre positivo, e che indicasse il numero di tamponi trovati positivi  in un dato giorno.

**Comment by agos** [comment]
se interpreto correttamente i dati, la colonna `nuovi_attualmente_positivi` tiene conto anche dei guariti, e un numero negativo indica che in un dato giorno il numero dei guariti (+ deceduti?) ha superato quello dei nuovi diagnosticati positivi

**Comment by xfranky** [comment]
Esatto. Quello a cui fa riferimento @gabri94 dovrebbe essere il totale nuovi casi, che non è incluso nel csv e va calcolato come differenza tra il "totale_casi" di un giorno e quello del giorno precedente

**Comment by Sasso0101** [comment]
Attualmente positivi vuol dire che in questo momento sono positivi. Nel caso di guarigione non saranno più positivi, qundi il numero dobrebbe scendere. Fino ad adesso è stato sempre positivo perché il numero di nuovi contagiati è stato maggiore rispetto al numero dei guariti.

**Comment by agos** [comment]
sicuramente aiuterebbe molto l'interpretazione una chiave che indichi quali campi sono relativi alla giornata in corso, e quali sono un totale

**Comment by umbros** [comment]
Grazie a tutti, spiegheremo meglio nel README l'interpretazione dei dati, faremo l'attività nella giornata di domani e vi anticipo che metteremo anche il README in inglese.
Il dato calcolato è dai dati forniti oggi dalle Regioni tramite il Ministero della Salute, confermo la correttezza.

**Comment by jack29is** [comment]
Nel ReadMe, il campo "nuovi_attualmente_positivi" è descritto come "Nuovi attualmente positivi (ospedalizzati + isolamento domiciliare)". Trovo imprecisa tale definizione in quanto così come è calcolato, il campo "nuovi_attualmente_positivi" rappresenta il saldo complessivo, tra il giorno "x" e il giorno "x-1", del "totale_attualmente_positivi", tenendo quindi in considerazione anche il numero di "dimessi_guariti" e di "deceduti".
Dimostrazione: al 10/03/20, il "totale_attualmente_positivi" è pari a 8514. Lo stesso dato ammontava a 7985 al 09/03/20. Facendo la differenza tra i due numeri si ottiene 8514-7985 = 529.

Al contrario, per calcolare il numero di "nuovi_attualmente_positivi" come da definizione:
"totale_attualmente_positivi" relativo al giorno "x"
-
( "totale_attualmente_positivi" relativo al giorno "x-1" 
- dimessi_guariti nel giorno "x"
- deceduti nel giorno "x")

**Comment by jack29is** [comment]
Nel ReadMe, il campo "nuovi_attualmente_positivi" è descritto come "Nuovi attualmente positivi (ospedalizzati + isolamento domiciliare)". Trovo imprecisa tale definizione in quanto così come è calcolato, il campo "nuovi_attualmente_positivi" rappresenta il saldo complessivo, tra il giorno "x" e il giorno "x-1", del "totale_attualmente_positivi", tenendo quindi in considerazione anche il numero di "dimessi_guariti" e di "deceduti".
Dimostrazione: al 10/03/20, il "totale_attualmente_positivi" è pari a 8514. Lo stesso dato ammontava a 7985 al 09/03/20. Facendo la differenza tra i due numeri si ottiene 8514-7985 = 529.

Al contrario, per calcolare il numero di "nuovi_attualmente_positivi" come da definizione, bisognerebbe adottare la seguente formula: "totale_attualmente_positivi" relativo al giorno "x" - ( "totale_attualmente_positivi" relativo al giorno "x-1" - dimessi_guariti nel giorno "x" - deceduti nel giorno "x")

**Comment by jack29is** [comment]
> se interpreto correttamente i dati, la colonna `nuovi_attualmente_positivi` tiene conto anche dei guariti, e un numero negativo indica che in un dato giorno il numero dei guariti (+ deceduti?) ha superato quello dei nuovi diagnosticati positivi

Corretto, ma per come è attualmente descritto il READ_ME la modalità di calcolo credo sia errata.

**Comment by alesarrett** [comment]
Non sono convinto delle spiegazioni date al valore -63 odierno dei dati della Lombardia. Credo proprio che sia il dato ad essere errato e non la spiegazione nel README... In conferenza stampa è stato detto che non sono arrivati tutti i dati dalla Regione Lombardia: non è questo il motivo?

**Comment by woodybz** [comment]
Esatto.
In ogni caso, credo che "nuovi_attualmente_positivi" debba avere un valore sempre positivo o uguale a zero.
Altrimenti falsa anche il totale che viene comunicato dei nuovi contagiati. 
In conferenza stampa è stato comunicato che ci sono 529 nuovi casi.  Sono in realtà 592 solo dalle alte regioni.

**Comment by jack29is** [comment]
No, errato. I nuovi casi sono 977.
Da quanto pubblicato risulta che:
- Ieri c'erano 7.985 contagiati
- Nella giornata odierna sono dimesse per guarigione 280 persone (1004-724)
- Nella giornata odierna sono decedute 168 persone (631-463)ù
- Ad oggi ci sono 8.514 contagiati

Il numero di contagiati ad oggi (8.514) è pari al numero di contagiati ieri (7.985) meno il numero di guariti (280) meno il numero di deceduti (168) a cui si somma il numero di NUOVI contagi (pari a X, la nostra incognita). Pertanto il numero di NUOVI contagiati X = 8.514 - (7.985 -280 - 168) = 977.
Il valore "nuovi_attualmente_positivi" rappresenta il delta complessivo tra "totale_attualmente_positivi" di oggi vs "totale_attualmente_positivi" di ieri, considerando quindi il totale risultante in termini di NUOVI contagi, morti e guariti.

**Comment by jack29is** [comment]
> Non sono convinto delle spiegazioni date al valore -63 odierno dei dati della Lombardia. Credo proprio che sia il dato ad essere errato e non la spiegazione nel README... In conferenza stampa è stato detto che non sono arrivati tutti i dati dalla Regione Lombardia: non è questo il motivo?

Spiegazione dato Lombardia:
- L'incremento di casi registrato è pari 322, dato dal totale di casi ad oggi (5.791) meno il totale di casi di ieri (5.469)
- Il totale di guariti è di 250 persone (calcolato allo stesso modo come differenza tra ieri ed oggi) 
- Il totale di deceduti è pari a 135

Sulla base di quanto detto prima, il delta della lombardia è dato da:
numero di nuovi contagi (322) meno il numero di dimessi per guarigione (250) meno il numero di deceduti (135), pari appunto a -63

**Comment by jack29is** [comment]
Alla luce di quanto detto, l'unico errore sta nel significato attribuito nel READ_ME al dato "nuovi_attualmente_positivi". Fermo restando che è errato assimilare quest'ultimo al numero di nuovi contagi, dato non presente nel tracciato, che deve essere calcolato come differenza tra il "totale_casi al giorno X" e il "totale_casi al giorno X-1"

**Comment by v4l3r10** [comment]
Partendo dal riferimento alla pagina :
[http://opendatadpc.maps.arcgis.com/apps/opsdashboard/index.html#/b0c68bce2cce478eaac82fe38d4138b1](url)

[<a href="https://imgbb.com/"><img src="https://i.ibb.co/6495wrC/incremento-Daily100320.png" alt="incremento-Daily100320" border="0"></a>](url)

che fa uso dei dati presenti in questo GIT, si evidenzia come l'indice di incremento estratto dal csv crea una falsa lettura dei dati:
si passa da +1598 a +529 quando in realtà i nuovi casi dovrebbero essere:
Casi Totali Di Oggi( 10149) - Casi Totali di ieri (9172)  = 977.

L'incremento giornaliero quindi è +977 e non +529.

nuovi_attualmente_positivi dovrebbe riportare solo i NUOVI casi escludendo dal conteggio i guariti o deceduti.

**Comment by jack29is** [comment]
> Partendo dal riferimento alla pagina :
> [http://opendatadpc.maps.arcgis.com/apps/opsdashboard/index.html#/b0c68bce2cce478eaac82fe38d4138b1](url)
> 
> [![incremento-Daily100320](https://camo.githubusercontent.com/4d6a905bc1e597d9640edd828c3a0aa89a10d2e9/68747470733a2f2f692e6962622e636f2f363439357772432f696e6372656d656e746f2d4461696c793130303332302e706e67)](https://imgbb.com/)
> 
> che fa uso dei dati presenti in questo GIT, si evidenzia come l'indice di incremento estratto dal csv crea una falsa lettura dei dati:
> si passa da +1598 a +529 quando in realtà i nuovi casi dovrebbero essere:
> Casi Totali Di Oggi( 10149) - Casi Totali di ieri (9172) = 977.
> 
> L'incremento giornaliero quindi è +977 e non +529.
> 
> nuovi_attualmente_positivi dovrebbe riportare solo i NUOVI casi escludendo dal conteggio i guariti o deceduti.

è errata l'interpretazione che si da al dato "nuovi_attualmente_positivi". +529 è il delta tra il totale di positivi di oggi e il totale di positivi di ieri! è errato assimilare tale dato al NUMERO DI NUOVI CONTAGI (quest'ultimo dato non è presente nel tracciato)

**Comment by v4l3r10** [comment]
> > Partendo dal riferimento alla pagina :
> > [http://opendatadpc.maps.arcgis.com/apps/opsdashboard/index.html#/b0c68bce2cce478eaac82fe38d4138b1](url)
> > [![incremento-Daily100320](https://camo.githubusercontent.com/4d6a905bc1e597d9640edd828c3a0aa89a10d2e9/68747470733a2f2f692e6962622e636f2f363439357772432f696e6372656d656e746f2d4461696c793130303332302e706e67)](https://imgbb.com/)
> > che fa uso dei dati presenti in questo GIT, si evidenzia come l'indice di incremento estratto dal csv crea una falsa lettura dei dati:
> > si passa da +1598 a +529 quando in realtà i nuovi casi dovrebbero essere:
> > Casi Totali Di Oggi( 10149) - Casi Totali di ieri (9172) = 977.
> > L'incremento giornaliero quindi è +977 e non +529.
> > nuovi_attualmente_positivi dovrebbe riportare solo i NUOVI casi escludendo dal conteggio i guariti o deceduti.
> 
> è errata l'interpretazione che si da al dato "nuovi_attualmente_positivi". +529 è il delta tra il totale di positivi di oggi e il totale di positivi di ieri! è errato assimilare tale dato al NUMERO DI NUOVI CONTAGI (quest'ultimo dato non è presente nel tracciato)

Considerando che questi grafici sono gestiti dalla JHU sarebbe più consono attribuire ai campi i nomi adeguati: "Nuovi attualmente positivi"  in italiano corrisponde a nuovi casi positivi rilevati. e non quindi quella forma aggregata di cui parlate. 
Rimango dell'idea che l'errore è proprio nel chiamare quel campo in quel modo visto che non rappresenta quell'informazione.
Immaginando che un ente internazionale prenda in mano questi campioni, traducendo letteralmente quelle etichette può capitare facilmente che ci siano incomprensioni.
Quel campo andrebbe chiamato in un altro modo.

**Comment by Crusan** [comment]
Confermo quanto rilevato dai precedenti commenti.
Il dato "nuovi attualmente positivi" dovrebbe essere chiarito.
Il cambio può essere in:

- "incremento attualmente infetti" 
- "aumento attualmente infetti"
- " delta infetti"
- "nuovi infetti netti"

o qualunque altra dicitura che sottolinei il fatto che si tratta di NUOVI CASI - NUOVE GUARIGIONI - NUOVI DECESSI (dove nuovo = data odierna)

**Comment by pierpa010** [comment]
Grazie @mydozer
quindi verrà modificata la logica del campo o solo l'intestazione?

**Comment by VariabileAleatoria** [comment]
A me pare che anche i valori di "totale_casi" diminuiscano quindi non capisco cosa rappresenti nemmeno quel dato

**Comment by mydozer** [comment]
@pierpa010 "Grazie a tutti, spiegheremo meglio nel README l'interpretazione dei dati, faremo l'attività nella giornata di domani e vi anticipo che metteremo anche il README in inglese.
Il dato calcolato è dai dati forniti oggi dalle Regioni tramite il Ministero della Salute, confermo la correttezza."

**Comment by pis147879** [comment]
Credo che sarebbe opportuno, includere un campo con il numero di tamponi positivi sul totale di tamponi effettuati, e considerare  questo come valore per i nuovi casi.  

Se fosse possibile: sarebbe utile avere le stesse informazioni a livello dei dati per provincia (dove vengono riportati solo i casi totali)

**Comment by alessiosavi** [comment]
Domanda: Ogni punto relativo al grafico **verde** corrisponde al numero di nuovi casi del giorno?

Ogni punto dell'immagine corrisponde a una entry json del dataset. 

Per intenderci, qualora non si verificassero nuovi casi in un giorno, il grafico verde scenderebbe a 0 ?

![immagine](https://user-images.githubusercontent.com/31842468/76608036-4126c580-6515-11ea-8cbc-bf2cd6d80eae.png)

**Comment by Crusan** [comment]
> Domanda: Ogni punto relativo al grafico **verde** corrisponde al numero di nuovi casi del giorno?
> 
> Ogni punto dell'immagine corrisponde a una entry json del dataset.
> 
> Per intenderci, qualora non si verificassero nuovi casi in un giorno, il grafico verde scenderebbe a 0 ?
> 
> ![immagine](https://user-images.githubusercontent.com/31842468/76608036-4126c580-6515-11ea-8cbc-bf2cd6d80eae.png)

No, ogni punto del grafico verde corrisponde al dato netto dei nuovi infetti ogni giorno, vale a dire al numero risultante dall'operazione NUOVI POSITIVI - NUOVI GUARITI - NUOVI DECESSI. Rappresenta l'incremento in persone attualmente infette. 
Di conseguenza il numero potrebbe anche essere negativo se in un giorno si verificassero più guariti e decessi rispetto ai nuovi casi positivi.

**Comment by pierpa010** [comment]
> > Partendo dal riferimento alla pagina :
> > [http://opendatadpc.maps.arcgis.com/apps/opsdashboard/index.html#/b0c68bce2cce478eaac82fe38d4138b1](url)
> > [![incremento-Daily100320](https://camo.githubusercontent.com/4d6a905bc1e597d9640edd828c3a0aa89a10d2e9/68747470733a2f2f692e6962622e636f2f363439357772432f696e6372656d656e746f2d4461696c793130303332302e706e67)](https://imgbb.com/)
> > che fa uso dei dati presenti in questo GIT, si evidenzia come l'indice di incremento estratto dal csv crea una falsa lettura dei dati:
> > si passa da +1598 a +529 quando in realtà i nuovi casi dovrebbero essere:
> > Casi Totali Di Oggi( 10149) - Casi Totali di ieri (9172) = 977.
> > L'incremento giornaliero quindi è +977 e non +529.
> > nuovi_attualmente_positivi dovrebbe riportare solo i NUOVI casi escludendo dal conteggio i guariti o deceduti.
> 
> è errata l'interpretazione che si da al dato "nuovi_attualmente_positivi". +529 è il delta tra il totale di positivi di oggi e il totale di positivi di ieri! è errato assimilare tale dato al NUMERO DI NUOVI CONTAGI (quest'ultimo dato non è presente nel tracciato)

non sarebbe più corretto il delta fra totale attualmente positivi al giorno x e totale attualmente positivi al giorno x-1?
