### ISSUE TITLE
variazione_totale_positivi = **5.294** è corretto?

### ISSUE THREAD

**Issue by CT-igiul** [pcm-dpc/COVID-19#933]
Ciao UMBROS,
il dato di oggi : variazione_totale_positivi = **5.294** in "andamento nazionale" è corretto?
O meglio, è corretto  il totale positivi = **717.784**?
IFYES: sarebbe una bella notizia.
Attendo conferma. Grazie
Luigi

**Comment by Achab94** [comment]
Ci sono stati 21554 dimessi/guariti tra ieri ed oggi, questa è la motivazione.
Non capisco dove pigli il dato 717.784, a che fa riferimento?

**Comment by Achab94** [comment]
<img width="721" alt="Schermata 2020-11-16 alle 21 56 27" src="https://user-images.githubusercontent.com/9095461/99307313-9a8a8580-2856-11eb-9e75-de5e755d886c.png">
Di questi quasi 14mila sono lombardi. Io mi chiederei dunque se il dato +21554 dimessi/guariti tra ieri ed oggi sia corretto :)

**Comment by CT-igiul** [comment]
![Schermata 2020-11-16 alle 23 36 02](https://user-images.githubusercontent.com/71124532/99316596-ec3a0c80-2864-11eb-87fb-60de741fe73d.png)
Emanuele, ok per la spiegazione. Grazie 
l dato è quello dei  **totale_positivi** di oggi. Mi accorgo adesso che hai cancellato la richiesta.
Rimango in attesa della risposta al tuo quesito circa i +21554 dimessi/guariti.

**Comment by Achab94** [comment]
Chi ha cancellato la richiesta? Che richiesta?

**Comment by CT-igiul** [comment]
Ritenevo fossi stato tu. Ti allego lo screenshot che ho appena fatto dove si vede la Tua richiesta cancellata ma ancora presente nell'email ricevuto ieri. 
Pensavo che tu avessi cancellato la domanda perché capito dove avevo preso il numero del totale_positivi = 717.784.

Rimango in attesa della risposta al tuo quesito circa i +21554 dimessi/guariti. Grazie
Fammi sapere.
Ciao
![Screenshot 2020-11-17 11 24 33](https://user-images.githubusercontent.com/71124532/99379868-82078300-28c9-11eb-94a1-4523ca47bd98.png)

**Comment by Achab94** [comment]
Sìsì ho cancellato semplicemente perchè poi ho capito da dove arriva quel dato.

**Comment by umbros** [comment]
Ciao a tutti, ieri quando abbiamo analizzato i dati abbiamo notificato la cosa e ci è stata data conferma. Quindi il dato è corretto.

Grazie comunque per la segnalazione

**Comment by CT-igiul** [comment]
Grazie a Voi.
Verifico quotidianamente la coerenza dei dati pubblicati e quello di ieri non seguiva il trend di quelli precedenti.
Ho comunque aggiornato il mio sito WiX e più tardi pubblicherò un POST con le spiegazioni necessarie a chi mi legge e guarda i miei grafici a Bolle che son al momento gli unici aggiornati. 
**Sto tentando, da mesi, di far capire ai media che l'INDICE DI CONTAGIOSITA presentato quotidianamente (solo da poche settimane)** non è quello che da una corretta indicazione sull'evoluzione della pandemia. L'INDICE DI CONTAGIOSITA corretto a mio parere è quello che propongo nel mio sito che ho spiegato ampiamente sia nei miei POST di mesi fa che negli ultimi tre di cui vi allego uno screenshot. Ho provato a contattare con insuccesso molte testate giornalistiche e media. Qualcuno di Voi potrebbe condividere con me questa necessità di dare un'informaziione corretta. Grazie
Vi invio il link per Vs Informazione.
https://www.luigitomaselli.com/

![Screenshot 2020-11-17 13 13 23](https://user-images.githubusercontent.com/71124532/99389523-78851780-28d7-11eb-8057-e879b19f6166.png)
