### ISSUE TITLE
Unexpected token ß in JSON

### ISSUE THREAD

**Issue by arpitux** [pcm-dpc/COVID-19#943]
Hello,

there is an unexpected character added in this JSON API -
https://raw.githubusercontent.com/pcm-dpc/COVID-19/master/dati-json/dpc-covid19-ita-province.json

![image](https://user-images.githubusercontent.com/9971612/100005034-58c98400-2dee-11eb-826c-121647a2bb9b.png)

- Arpit

**Comment by pinoli** [comment]
+1 on this, it breaks JSON parsing everywhere

**Comment by stesforz** [comment]
Fix it please, it breaks JSON parsing and doesn't allow our application to update. thanx

**Comment by miccoli** [comment]
Please see also the failure of my test suite (PR #847) at <https://github.com/miccoli/COVID-19/runs/1444432722?check_suite_focus=true>.

**Comment by miccoli** [comment]
Duplicate of #941

**Comment by lp74** [comment]
Please, this issue breaks parsing

**Comment by Gioee** [comment]
+1 please fix this.

**Comment by alexodus** [comment]
+1

**Comment by miccoli** [comment]
Apparently this has been corrected in bc9d167.
