### ISSUE TITLE
Aggiunta errata nel file note

### ISSUE THREAD

**Issue by cristianocasella** [pcm-dpc/COVID-19#950]
Tipo di issue:

- [X] Dati mancanti o errati => https://github.com/pcm-dpc/COVID-19/blob/master/note/dpc-covid19-ita-note.csv
- [ ] Errore nella documentazione 
- [ ] Errore or mancanza nella dashboard 
- [ ] Problemi di visualizzazione nella dashboard 

- Regione:
- Provincia: 

## Riassunto
Sono stati inseriti dei dati prima della riga di intestazione, invalidando il CSV.

**Attesa:**
Va rimossa la prima riga nel file, la stessa entry è stata collocata anche nel giusto ordine più in basso.

**Attuale:** 
Sono stati inseriti dei dati prima della riga di intestazione, invalidando il CSV.

**Comment by floatingpurr** [comment]
Sempre a proposito di #945

**Comment by cristianocasella** [comment]
Manually fixed
