### ISSUE TITLE
Json format error in dpc-covid19-ita-province.json

### ISSUE THREAD

**Issue by tatomix** [pcm-dpc/COVID-19#952]
`There is a Json format error in dpc-covid19-ita-province.json row 4`

**Comment by floatingpurr** [comment]
Duplicate of #948 (Still waiting for a fix).

**Comment by ricir** [comment]
Seems to be fixed now.

**Comment by floatingpurr** [comment]
Looks like this kind of issues is fixed in the next data release 24h later
