### ISSUE TITLE
I nuovi_positivi di oggi sono 20711 non 20709

### ISSUE THREAD

**Issue by Rabelaiss** [pcm-dpc/COVID-19#954]
La differenza tra casi totali di oggi e di ieri fa
1641610-1620901=20709
tuttavia nelle [note](https://github.com/pcm-dpc/COVID-19/blob/master/note/dpc-covid19-ita-note.csv) è riportato che 
> La Regione Emilia Romagna comunica che in seguito a verifica sui dati comunicati nei giorni passati sono stati eliminati 2 casi

quindi ai casi totali di ieri vanno sottratti due casi e il calcolo precedente risulta 20711, invece il campo `nuovi_positivi` nel file [dpc-covid19-ita-andamento-nazionale](https://github.com/pcm-dpc/COVID-19/blob/master/dati-regioni/dpc-covid19-ita-regioni-20201202.csv) è erroneamente 20709.

Questo errore è conseguenza dell'errore nei dati dell'Emilia-Romagna, la differenza tra casi totali di oggi e di ieri fa
126110-124541=1569
ma seguendo l'avviso che ho riportato sopra i casi diventano 1571, invece il campo `nuovi_positivi` nel file [dpc-covid19-ita-regioni-20201202](https://github.com/pcm-dpc/COVID-19/blob/master/dati-regioni/dpc-covid19-ita-regioni-20201202.csv) riporta 1569

**Comment by Paulsword** [comment]
D'accordo

**Comment by LucaZeta** [comment]
> La differenza tra casi totali di oggi e di ieri fa
> 1641610-1620901=20709

#**Rebelais**: Avrai senz'altro già notato che non sempre la differenza con il giorno precedente di totale_casi restituisce esattamente il valore di nuovi_positivi. In questa [vista a dettaglio aumentato dei dati nazionali](https://covid19.zappi.me/table/) si evidenzia con la colonna correzione_totale_casi proprio la differenza tra i due valori che quantifica le operazioni di correzione applicate nel passato e che quindi coinvolgono solo l'indicatore totale_casi.

Qualche volta il valore della correzione trova giustificazione in quanto riportato nelle note, altre volte è più difficile ricostruire la motivazione che ha generato la correzione.

**Comment by Rabelaiss** [comment]
@LucaZeta forse ho spiegato male, come sappaimo `nuovi_positivi` riporta il numero di nuovi casi al netto delle correzioni/riconteggi, tuttavia al numero di ieri non è stata applicata la correzione, altrimenti sarebbe stato 20711

**Comment by LucaZeta** [comment]
A volte mi sembra di ragionare al contrario:  la nota del 2 Dic. dichiara che in seguito a verifica vengono sottratti (eliminati) 2 tra i casi dei giorni scorsi. L'applicazione di questa correzione la vedrei portando il totale_casi da 1.641.610 a 1.641.608, cosa che non essendo avvenuta ieri, mi aspetto che avvenga oggi o comunque prima o poi.

Oggi provo a dormire con la testa dalla parte dei piedi, magari torno a posto :D
