### ISSUE TITLE
Numero errato di casi testati: 23333937 invece di 13333937

### ISSUE THREAD

**Issue by Rabelaiss** [pcm-dpc/COVID-19#955]
numero errato nel file https://raw.githubusercontent.com/pcm-dpc/COVID-19/master/dati-andamento-nazionale/dpc-covid19-ita-andamento-nazionale-latest.csv

**Comment by umbros** [comment]
Ciao @Rabelaiss già notificata

**Comment by Rabelaiss** [comment]
@umbros è la campania che ha 11187787 testati invece di 1187787

**Comment by caigi74** [comment]
ma i casi da sospetto diagnostico? tutti a 0?

**Comment by umbros** [comment]
@caigi74 da oggi non sono più caricati arriveranno altri dati da lunedì

**Comment by iguandroid** [comment]
> 
> 
> @umbros è la campania che ha 11187787 testati invece di 1187787

Non può essere "1187787".
Ieri il progressivo della Campania era 1100911.
Se il valore odierno fosse quanto suggerito ("1187787") vorrebbe dire che 86876 "casi testati" in un giorno...
Del tutto fuori misura per la Campania che nelle circostanze di punta è arrivata a farne nell'ordine di 20mila al giorno

Molto probabilmente l'errore non sta nelle prime cifre di quel numero ("111"), ma nella sequenza finale alternata di "87787".
Plausibilmente il valore corretto è "11187787", che corrisponde a un incremento di 17867 nuovi casi testati nelle ultime 24 ore... in linea con i numeri recenti della Campania,

**Comment by Rabelaiss** [comment]
@iguandroid il dato corretto della campania è 1117787

**Comment by umbros** [comment]
I dati della Campania saranno corretti domani.

**Comment by iguandroid** [comment]
> 
> 
> @iguandroid il dato corretto della campania è 1117787

Beh... avevo colto bene che quel "111" doveva essere corretto e l'errore risiedere nelle cifre successive.

Grazie!

**Comment by fotografAle** [comment]
In base al modello di previsione che ho implementato, risolto con algoritmi di DL a CNN, direi che il dato più verosimile della Campania sia quello di 1'117'787. Questo si traduce in un errore, nel totale dichiarato oggi, di 10'070'000. Il dato che si allinea meglio alle correlazioni del modello, è infatti quello di 13'263'937 casi totali testati, a cui si riferirebbero 96'592 casi testati odierni.

**Comment by LucaZeta** [comment]
> algoritmi di DL a CNN

Deep Learning & Convolutional Neural Network
(Apprendimento profondo e Rete neurale convoluzionale)

Per chi se lo stesse chiedendo.

**Comment by LucaZeta** [comment]
> 
> 
> I dati della Campania saranno corretti domani.

Così non è stato, non nel file json.

**Comment by ilTrev** [comment]
La riga del 3 dicembre nell'andamento nazionale è stata replicata con il dato corretto nella seconda occorrenza. È voluto?

**Comment by LucaZeta** [comment]
> È voluto?

E' stata una "correzione" solo temporanea.
Al momento hanno applicato quella definitiva e corretta. Finalmente.
