### ISSUE TITLE
Dato nuovi ingressi in terapia intensiva nei file csv

### ISSUE THREAD

**Issue by vecchionico** [pcm-dpc/COVID-19#957]
**Tipo di richiesta**:  richiesta di informazione 

## Riassunto

I dati sui nuovi ingressi in terapia intensiva disponibili dal 12-3 saranno aggiunti anche nei .csv? C'è in programma di comunicare i dati degli ingressi relativi al periodo marzo/dicembre?

## Interesse pubblico

Avere il dato degli ingressi in TI solo in formato non machine-readable rende più macchinoso il loro utilizzo. Avere i dati solo a partire dal 12-3 rende un quadro parziale.

**Comment by fotografAle** [comment]
Cerco di racchiudere in una formula il nuovo dato, se ho capito bene di cosa si tratti.

![image](https://user-images.githubusercontent.com/10924915/101166963-7215d000-3639-11eb-8a32-b48350492c25.png)

**Comment by umbros** [comment]
Ciao,
sarà open da lunedì con i dati da ieri 02/12/2020

**Comment by CT-igiul** [comment]
> Cerco di racchiudere in una formula il nuovo dato, se ho capito bene di cosa si tratti.
> 
> ![image](https://user-images.githubusercontent.com/10924915/101167089-aab5a980-3639-11eb-98d1-6866e004615d.png)

Ciao fotografAle.
Forse sarebbe meglio inquadrare la relazione in questa formula:

**T.C.(n) = RcS(n) + T.I.(n-1) + N.I.T.I(n) + I.D.(n) + D/G(n) + M(n)** 



**T.C.(n)**   =Totale casi del giorno corrente
**RcS(n)**   = Ricoverati con Sintomi del giorno
**T.I.(n-1)** = Casi di Terapia Intensiva del giorno precedente
**I.D.(n)**    = Isolamento Domiciliare del giorno corrente
**T.I.(n)**     = Casi di Terapia Intensiva del giorno corrente
**N.I.T.I(n)** = Nuovi Ingressi in Terapia intensiva nel giorno corrente
**D/G(n)**    = Dimessi e Guariti del giorno corrente
**M(n)**       = Morti nel giorno corrente

La formula attuale è di seguito rappresentata:

![Schermata 2020-12-08 alle 11 04 24](https://user-images.githubusercontent.com/71124532/101469724-63832d80-3945-11eb-84cd-19dfb93e7ebc.png)

dove      **T.I.(n) = T.I.(n-1) + N.I.T.I(n)**

**Comment by CT-igiul** [comment]
> Cerco di racchiudere in una formula il nuovo dato, se ho capito bene di cosa si tratti.
> 
> ![image](https://user-images.githubusercontent.com/10924915/101167089-aab5a980-3639-11eb-98d1-6866e004615d.png)

La formula potrebbe essere corretta se conoscessimo il numero di "G" e quello di "D". Dei Guariti/Dimessi e dei Deceduti conosciamo solo il numero totale. Ci devo pensare ancora un po.
