### ISSUE TITLE
 dpc-covid19-ita-andamento-nazionale.json - casi da sospetto diagnostico & casi da screening a 0

### ISSUE THREAD

**Issue by LucaZeta** [pcm-dpc/COVID-19#958]
- [X ] Dati mancanti o errati 

i seguenti campi sono valorizzati in maniera non credibile:

casi da sospetto diagnostico = 0
casi da screening  = 0
casi testati = 23.333.937

**Comment by umbros** [comment]
Ciao,
come da changelog i due dati non saranno più popolati

**Comment by LucaZeta** [comment]
> come da changelog i due dati non saranno più popolati

E il terzo: casi_testati ?
