### ISSUE TITLE
3/12/20 numero di casi testati in campania: 11.187.787 probabilmente errato in eccesso di 1 ordine di grandezza 

### ISSUE THREAD

**Issue by ornolio** [pcm-dpc/COVID-19#959]
Tipo di issue:

- [x ] Dati mancanti o errati 
- [ ] Errore nella documentazione 
- [ ] Errore or mancanza nella dashboard 
- [ ] Problemi di visualizzazione nella dashboard 

- Regione:Campania
- Provincia: 

## Riassunto

3/12/20 numero di casi testati in campania: 11.187.787 > numero di tamponi; probabilmente errato in eccesso di 1 ordine di grandezza (ieri 2/12 erano 1.100.911)

**Attesa:**

**Attuale:**

**Comment by davpirelli** [comment]
Issue segnalata già qui #955 
Anche noi siamo in attesa della correzione del dato. Abbiamo temporaneamente messo un avviso sul nostro portale https://covidanalysis.it

**Comment by ornolio** [comment]
Grazie. Buon Lavoro.

**Comment by umbros** [comment]
Corretto. Grazie
