### ISSUE TITLE
Dati Attuali vs Cumulativi

### ISSUE THREAD

**Issue by mrai5011** [pcm-dpc/COVID-19#96]
Non e` sempre chiarissimo quali dati siano attuali e quali cumulativi.
Per esempio il dato terapia intensiva non mi e` chiaro se sia attuale o cumulativo.
Questo anche se il fatto che in Lombardia si avvicini molto al totale deceduti mi fa pensare che sia attuale.
Grazie per l'ottimo lavoro!

**Comment by umbros** [comment]
Ciao  @mrai5011 il dato si intende attuale.
