### ISSUE TITLE
dpc-covid19-ita-note.csv mal formato

### ISSUE THREAD

**Issue by Doc73** [pcm-dpc/COVID-19#962]
Tipo di issue:

- [x] Dati mancanti o errati nel file `dpc-covid19-ita-note.csv`
- [ ] Errore nella documentazione 
- [ ] Errore or mancanza nella dashboard 
- [ ] Problemi di visualizzazione nella dashboard 

- Regione:
- Provincia: 

## Riassunto
Gentilissimi signori,
il file suddetto presenta l'intestazione sul secondo rigo, anziché sul primo! :-)
Grazie mille,
DC

**Attesa:**

**Attuale:**

**Comment by Doc73** [comment]
PRECISAZIONE: il primo rigo è proprio da buttare via, essendo un duplicato del report del 26 novembre

**Comment by umbros** [comment]
Corretto grazie
