### ISSUE TITLE
oggetto json duplicato in dpc-covid19-ita-andamento-nazionale.json

### ISSUE THREAD

**Issue by chuck2098** [pcm-dpc/COVID-19#966]
Salve,
ho riscontrato il seguente problema:

- [**x**] Dati mancanti o errati  in "dpc-covid19-ita-andamento-nazionale.json"

esistono due oggetti json relativi al giorno 3 dic 2020.
Grazie

**Comment by ilTrev** [comment]
Stesso problema nel csv dell'andamento nazionale

**Comment by LucaZeta** [comment]
Il file in questione risulta al momento corretto e senza duplicazioni.
Ritengo il caso osservato essere stata un maldestro tentativo di soluzione solo temporaneo.
