### ISSUE TITLE
Lazio: Casi testati - Valore non aggiornato (uguale al valore di ieri)

### ISSUE THREAD

**Issue by iguandroid** [pcm-dpc/COVID-19#967]
Tipo di issue:

- [x] Dati mancanti o errati 
- [ ] Errore nella documentazione 
- [ ] Errore or mancanza nella dashboard 
- [ ] Problemi di visualizzazione nella dashboard 

- Regione: LAZIO
- Provincia: 

## Riassunto

Lazio > casi_testati

Valore al 3/12/2020: 1852335
Valore al 4/12/2020: 1852335

**Attesa:**

Visto che in Lazio oggi sono stati contabilizzati 1831 nuovi casi quanto sopra è chiaramente un errore.

Il valore odierno dovrebbe essere >= (1852335 + 1831)

**Attuale:** 

Prego verificare/confermare situazione per consentire elaborazioni.

Grazie.

**Comment by ornolio** [comment]
infatti: il 3/12 e il 4/12 i casi testati totali sono sempre  1852335

**Comment by iguandroid** [comment]
> 
> 
> Valore in linea circa 1852335 + 5*1831 ovvero circa il 20% dei casi testati potrebbero essere stati i positivi.

Il Lazio è una delle pochissime regioni che ha un positivity rate attorno al 10% dei casi testati.
Quindi il "circa" è più plausibilmente un 1852335 + 10 * 1831

Ma se siamo qui, non è per il "circa": sarebbe gradito IL DATO aggiornato.
