### ISSUE TITLE
Dati Lombardia mancanti o incompleti

### ISSUE THREAD

**Issue by Cavallium** [pcm-dpc/COVID-19#97]
Type of issue:

- [x] Incorrect or missing data : 
- [ ] Incorrect or missing documentation 
- [ ] Incorrect or missing data in the dashboard 
- [ ] Layout problem in the dashboard 

## Summary

Noto che i dati dell'aumento dei contagiati nuovi in Lombardia sono stranamente negativi (passando da +1118 a -63), nonostante in tutte le altre regioni siano aumentati rispetto ai giorni precedenti.

è un problema di mancanza di dati aggiornati o si tratta di un bug?

**Expected:**

Un numero realistico di nuovi_attualmente_positivi

**Actual:** 

nuovi_attualmente_positivi: -63

**Comment by orion434** [comment]
Riporto da un [quotidiano nazionale](https://www.repubblica.it/cronaca/2020/03/10/news/coronavirus_austria_e_albania_bloccano_voli_e_traghetti_costa_crociere_sospende_i_viaggi_nel_mediterraneo-250860322/):

> Sono 8.514 i malati di coronavirus in Italia, 529 in più di ieri (+6.6%). "Ma dalla Lombardia aspettiamo un aggiornamento, il dato non è completo in attesa di ricevere l'esito di ulteriori tamponi", ha spiegato il capo della Protezione civile Angelo Borrelli.

**Comment by orion434** [comment]
Confermo quanto detto prima, dall'audio del video ufficiale "Covid-19, il punto della situazione alle 18 del 10 marzo" disponibile sul sito del ministero della Salute ([link](http://www.salute.gov.it/portale/news/p3_2_7_0_1.jsp?lingua=italiano&menu=multimedia&p=video&id=2063)).

**Comment by stormsson** [comment]
la WHO , ancora una volta, espone numeri totalmente diversi: https://www.who.int/docs/default-source/coronaviruse/situation-reports/20200310-sitrep-50-covid-19.pdf?sfvrsn=55e904fb_2

sarebbero +1797 secondo la loro fonte.

Guardando il trend dei giorni scorsi il dato 529 risulta molto anomalo: è quasi 1/3  del valore di ieri, e dato il tempo di incubazione della malattia non è imputabile alle recenti misure di sicurezza

**Comment by elsv87** [comment]
Il dato WHO è aggiornato alle 10 di stamattina e fa riferimento ai dati di ieri e non a quelli di oggi. Anche il numero riferito alle morti riporta infatti il dato di ieri. Sotto il titolo si legge: Data as reported by national authorities by 10AM CET10 March 2020 --> quindi sono i dati della nostra protezione civile.
Concordo che il dato sia basso rispetto al trend degli scorsi giorni, ma dalle dichiarazioni di Borrelli sembra che manchino ancora dei dati come riporta Orion434 :)

**Comment by orion434** [comment]
Probabilmente nell'aggiornamento odierno verranno chiariti i dati mancanti. Spero che per fini statistici vengano esplicitati i dati mancanti. Se oggi (11/03/2020) ci sarà un aumento dei casi (in Lombardia) sarebbe utile distinguere tra quelli precedenti e i nuovi in modo da assegnare correttamente i casi al relativo giorno. E' inoltre possibile che situazioni analoghe si ripeteranno con più frequenza in futuro, a causa della mole di test a cui i laboratori sono sottoposti e che ovviamente, per motivi pratici, non vengono completati tutti entro le ore 17/18. 

Inoltre, nel caso di un picco dovuto alla somma dei dati di ieri e oggi, è di fondamentale importanza far capire all'opinione pubblica che i dati di ieri erano parziali. Troppo spesso i media interpretano solo le variazioni giornaliere per trarre conclusioni sui trend.

**Comment by riccardopinto** [comment]
Se c'è una correzione alle ore 18 bisognerebbe aggiungere i mancanti di ieri al timestamp corretto, per evitare di sporcare il dato odierno

**Comment by riccardopinto** [comment]
In conferenza stampa è stato detto che del dato odierno, circa 600 sono riferiti ai dati mancanti di ieri

**Comment by rapperskull** [comment]
> 
> 
> In conferenza stampa è stato detto che del dato odierno, circa 600 sono riferiti ai dati mancanti di ieri

Immagino abbia più senso aggiungere 600 al dato di ieri, anche se non è una cifra esatta, che lasciare tutto così com'è

**Comment by cortesimone** [comment]
:+1:

**Comment by noizhardware** [comment]
> In conferenza stampa è stato detto che del dato odierno, circa 600 sono riferiti ai dati mancanti di ieri

fonte: https://www.ilfattoquotidiano.it/2020/03/11/coronavirus-borrelli-contagi-oltre-quota-12mila-2mila-in-piu-rispetto-a-ieri-827-le-vittime-mille-i-guariti/5733369/

**Comment by umbros** [comment]
#126
