### ISSUE TITLE
ritardo ?

### ISSUE THREAD

**Issue by bertolem** [pcm-dpc/COVID-19#971]

**Comment by giasar** [comment]
Sì, ufficialmente il record di più alto ritardo dall'inizio dell'epidemia, almeno che io mi ricordi. Ho dovuto aggiornare il mio bot Telegram @daticovid, che invia i dati in automatico appena caricati, per continuare a richiedere aggiornamenti 😅

**Comment by SamanFekri** [comment]
my bot in telegram is waiting for updating here too 😅

**Comment by unbombarolo** [comment]
È sabato sera, saranno andati a prendere un aperitivo... ah, no ;-)

**Comment by giasar** [comment]
Got it, finally!

**Comment by umbros** [comment]
Ciao a tutti, semplice problema tecnico rientrato.
Buona giornata

**Comment by bertolem** [comment]
Grazie
M.
