### ISSUE TITLE
Continua la scarsa accuratezza dei dati

### ISSUE THREAD

**Issue by renatizzi** [pcm-dpc/COVID-19#974]
Tipo di issue:

- [x] Dati mancanti o errati 
- [ ] Errore nella documentazione 
- [ ] Errore or mancanza nella dashboard 
- [ ] Problemi di visualizzazione nella dashboard 

- Regione:
- Provincia: 

## Riassunto

**Attesa:**

**Attuale:**

**Comment by umbros** [comment]
Cosa intendi con accuratezza dei dati?

**Comment by renatizzi** [comment]
Intanto grazie per la risposta... ti confesso che ho difficoltà a interpretare correttamente il senso della tua domanda perché il concetto di accuratezza è basilare e di fondamentale importanza per chi tratta dati ed informazioni. Cito in ogni caso Treccani per il significato in metrologia: "differenza tra il valore misurato e il valore presunto vero di una grandezza".
Ho usato volutamente questo termine e non quello di "precisione" perché, nel caso in specie, il tasso di errore è molto elevato avendo a che fare con dati inseriti manualmente e pertanto, vista la loro rilevante sensibilità, sarebbe opportuno introdurre una serie di controlli formali prima della loro pubblicazione. Peraltro ritengo che la rettifica a posteriore degli stessi dati non soddisfi le esigenze di coloro i quali usano i file csv messi a disposizione.
Spero di essere stato chiaro 
Buon lavoro

Renato Stefanizzi
