### ISSUE TITLE
Nuovo dataset in anteprima

### ISSUE THREAD

**Issue by Rabelaiss** [pcm-dpc/COVID-19#975]
> Da lunedì 07/12/2020 sarà aggiunto il campo "Ingressi in terapia intensiva"

@umbros questo campo, che immagino diventerà `ingressi_in_terapia_intensiva` nei file, sarà aggiunto sia a `dpc-covid19-ita-regioni` sia a `dpc-covid19-ita-andamento-nazionale`?
Sarebbe possibile per voi pubblicare le anteprime dei dataset come faceste con l'aggiornamento di fine giugno in #747 ?
Grazie

**Comment by umbros** [comment]
Ciao Rabelaiss, stasera pubblicherò un'anteprima del dataset (il dato sarà messo in fondo per una migliore gestione). Da domani i dati saranno processati.
