### ISSUE TITLE
CASI SOSPETTO DIAGNOSTICO E SCREENNING OMESSI da DATI REGIONALI

### ISSUE THREAD

**Issue by CT-igiul** [pcm-dpc/COVID-19#976]
Buongiorno,
oggi stavo riallineando il mio DB personale con i Vs dati e mi sono accorto che **dal giorno 3/12 u.s.** mancano dai dati Regionali quotidiani i dati da **SOSPETTO DIAGNOSTICO** da **SCREENING** mentre sono presenti quelli del TOTALE CASI (vedi colonne gialle nello screenshot allegato). E' una scelta voluta, una dimenticanza o non ho letto una Vs comunicazione in merito? Grazie
****
![Schermata 2020-12-06 alle 10 48 53](https://user-images.githubusercontent.com/71124532/101277056-d8256300-37b1-11eb-8a7a-6b87fd563495.png)

![Schermata 2020-12-06 alle 11 07 24](https://user-images.githubusercontent.com/71124532/101277258-736b0800-37b3-11eb-9f82-af6c774bc777.png)

**Comment by Doc73** [comment]
Da alcuni giorni hanno tolto quei dati, come scritto nel changelog

**Comment by CT-igiul** [comment]
Non mi ero accorto dell'esistenza della sezione **changelog** e non avevo proprio pensato di controllare. L'analisi dei dati mi impegna notevolmente ma adesso so cosa guardare quando avrò dubbi. Grazie Domenico.

**JUST FOR INFO:** Che tu sappia c'è un razionale che lo spieghi o si sta solo perdendo il controllo dei dati che diventano troppi. Non è una critica! Da analizzatore di DB capisco benissimo quanto sia difficile il controllo e l'aggiornamento e che un approccio olistico, concentrato sull'essenziale, a volte sia più efficace di un dettaglio irraggiungibile. L'essenziale è il trend!

**Comment by Doc73** [comment]
@CT-igiul 
Non sono un manutentore di questo repo e ti posso solo dire che qui pubblicano i dati come li ricevono dal Ministero, ma non sono più loro a gestire i dati.

**Comment by CT-igiul** [comment]
Grazie per la risposta.
Quando dici loro, suppongo intendi UMBROS  &C. Ma allora i dubbi chi li chiarisce?
Chi è responsabile del MdS ISS DPC della gestione dei dati e i come vengano calcolati? E' possibile aver un riferimento da contattare? Grazie

**Comment by Doc73** [comment]
Non so niente. Sono un utente come te, anzi, almeno io, un utonto!

**Comment by umbros** [comment]
I dati sono saranno più riportati nel repository in quanto il Ministero della Salute per questi dati non li raccoglie più.

**Comment by CT-igiul** [comment]
Grazie umbros. Ne prendo atto.
