### ISSUE TITLE
Formato dati non aggiornato

### ISSUE THREAD

**Issue by ilTrev** [pcm-dpc/COVID-19#979]
Oggi dovrebbe essere introdotto il nuovo campo "Ingressi in terapia intensiva", ma nel descrittore del formato dati ( https://github.com/pcm-dpc/COVID-19/blob/master/dati-andamento-covid19-italia.md ) non se ne vede ancora la definizione. Sarebbe possibile averla **prima** della pubblicazione dei dati odierni?

**Comment by umbros** [comment]
@ilTrev il rilascio dei dati è posticipato a mercoledì e verrà data notizia entro le 15:00. Per dare un servizio continuativo e senza errori e uniformità dei dataset dobbiamo tenere standard qualitativi e di processo che non creino problemi tecnici.
