### ISSUE TITLE
Inconsistent number of total cases reported

### ISSUE THREAD

**Issue by fabiospampinato** [pcm-dpc/COVID-19#98]
Type of issue:

- [x] Incorrect or missing data : 
	- https://raw.githubusercontent.com/pcm-dpc/COVID-19/master/dati-json/dpc-covid19-ita-province.json
  	- https://raw.githubusercontent.com/pcm-dpc/COVID-19/master/dati-json/dpc-covid19-ita-regioni.json

## Summary

The number of total cases reported for the "Catania" province went up from 23 on 09/03 to 35 on 10/03.

At the same time the number of total cases reported for the "Sicilia" region went from 54 on 09/03 to 62 on 10/03.

Now given how "Sicilia" is a superset of "Catania" I don't see how it's possible that the total number of cases increased by 12 in Catania but only by 8 in Sicilia, how should I interpret these numbers?

**Expected:**

The reported numbers should make sense.

**Actual:** 

The reported numbers don't seem to make sense.

**Comment by orion434** [comment]
In yesterday reports, in Sicily there were 19 pending cases "being verified and updated". Today there were none. My understanding is that those cases were assigned today to the relative province. Therefore, although there are in total 8 new cases (54 to 62), there are also those 19 being assigned.

**Comment by fabiospampinato** [comment]
I see, that would seem indeed to be the explanation for this, thanks!

I'm keeping this issue open because:
- It's weird that a province is being assigned to a case only at a later time, how could this even happen?
- Even though for whatever reason a province could have known cases assigned to it at a later time I don't see why that case should be counted in that province's data from the time of province assignment rather from the time it has been discovered, i.e. older erroneous data should get amended instead.

**Comment by orion434** [comment]
A possible explanation is that the number of cases "being verified and updated" account for the tests performed and waiting for a clear answer (some of them might be negative, false positive, false negative, waiting for results,...). Indeed, some of them might be still in progress, while other cases might have symptoms and being scheduled for or waiting for results. 
In addition, the cases are being assigned to the correct provence/region. I am not aware of the procedure for travellers, visitors, or other people being tested in a location different from their residence and how the people locked in different areas are being assigned.
However, I think that they are doing their best, using a constant methodology and every day the previous day cases "being verified and updated" are solved/assigned (and new ones appears from new tests).

**Comment by umbros** [comment]
Thank you @orion434, @fabiospampinato we are editing the readme to be more specific.
Now is reported:
Ogni Regione ha una Provincia denominata "In fase di definizione/aggiornamento" con il codice provincia da 979 a 999, utile ad indicare i dati ancora non assegnati alle Province.
