### ISSUE TITLE
Colore aggiornato status Regioni

### ISSUE THREAD

**Issue by MCilento93** [pcm-dpc/COVID-19#984]
## Riassunto

Introduzione colore regioni e restrizioni.

## Interesse pubblico

Non ho trovato in giro niente di ufficiale, se non il [sito del governo](http://www.governo.it/it/articolo/domande-frequenti-sulle-misure-adottate-dal-governo/15638?gclid=CjwKCAiAwrf-BRA9EiwAUWwKXicC1bzopYynHP9pvRxHUza7Ar4dte9hWHi55Uj4xfuAHanOCf7a1BoCTggQAvD_BwE).

Ho scritto un **API python**  per prendere il colore attuale delle regioni dal sito del governo https://github.com/MCilento93/ColoreRegioni.

Non esistono alternative ufficiali?

**Comment by pierluigicara** [comment]
E' vero non c'era nulla di riutilizzabile e, dunque, Open, per questo abbiamo aggiunto il nuovo dataset "aree_nuove" con i relativi metadati. La struttura dati riprende il modello dati del tema Inspire "Area Management and Restriction..." già usato in precedenza, per i dettagli si può vedere la sezione del ReadMe relative ai dataset sulle misure restrittive, A titolo di esempio, per la rappresentazione simbolica si può utilizzare il campo che si riferisce ad una parte specifica del provvedimento, che è valorizzato con gli articoli del DPCM originario e che definiscono le tre classificazioni in base agli scenari di rischio.

**Comment by MCilento93** [comment]
Grazie,
menziona il file aree-nuove committato 5 giorni fa?
Verrà tenuto aggiornato quindi?

Grazie

Ps. formato file? vedo che molti sono stati rimossi

**Comment by pierluigicara** [comment]
Si verrà aggiornato, almeno finché continuerà quel monitoraggio.
I file vengono cancellati perché il nuovo li ricomprende (il campo versione mantiene questa storicizzazione).
Buonasera




Inviato dal mio Galaxy



-------- Messaggio originale --------
Da: Mario Cilento <notifications@github.com>
Data: 11/12/20 20:12 (GMT+01:00)
A: pcm-dpc/COVID-19 <COVID-19@noreply.github.com>
Cc: Cara Pierluigi <Pierluigi.Cara@protezionecivile.it>, State change <state_change@noreply.github.com>
Oggetto: Re: [pcm-dpc/COVID-19] Colore aggiornato status Regioni (#984)


Grazie,
menziona il file aree-nuove committato 5 giorni fa?
Verrà tenuto aggiornato quindi?

Grazie

Ps. formato file? vedo che molti sono stati rimossi

-
