### ISSUE TITLE
"Ingressi del giorno in Terapia Intensiva" non presente sul .cvs dei dati-regione

### ISSUE THREAD

**Issue by CT-igiul** [pcm-dpc/COVID-19#986]
Buonasera,
non trovo ancora il dato dei "**nuovi ingressi in T.I.**", riportato da qualche giorno nelle schede-riepilogative regionali, nel file **dpc-covid19-ita-regioni-2020mmgg.csv** dei dati-regione.
Quando sarà inserito? Grazie

**Comment by Rabelaiss** [comment]
la data è scritta in 2 posti: 1) sotto al titolo nella [pagina principale](https://github.com/pcm-dpc/COVID-19) 2) nella issue "Modifiche ai dataset Regioni e Andamento nazionale" aperta ieri da chi gestisce il dataset che trovi nella [lista delle issue](https://github.com/pcm-dpc/COVID-19/issues)

**Comment by CT-igiul** [comment]
Grazie.
Mi era sfuggito.
