### ISSUE TITLE
Inconsistenza dei dati di "ingressi_terapia_intensiva"

### ISSUE THREAD

**Issue by bruninoit** [pcm-dpc/COVID-19#987]
Nei file json è stato appena inserito questo nuovo dato, solo che è inconsistente rispetto ai dati postati nei bollettini in pdf dei giorni scorsi e appaiono addirittura dei valori negativi (per esempio in data 07-12-2020 è stato inserito "ingressi_terapia_intensiva":-6.0) che non hanno alcun significato per questo genere di dato, che dovrebbe sempre essere positivo o al più nullo.

**Comment by umbros** [comment]
@bruninoit è stato caricato il dato e aggiornati gli altri. Aggiorna pure grazie.
