### ISSUE TITLE
Scheda riepilogativa regioni sbagliata

### ISSUE THREAD

**Issue by Rabelaiss** [pcm-dpc/COVID-19#988]
La scheda di oggi è quella del 6 dicembre https://github.com/pcm-dpc/COVID-19/blob/f875c1414cbdabbaadb95fce219a3c2209748228/schede-riepilogative/regioni/dpc-covid19-ita-scheda-regioni-20201209.pdf

**Comment by umbros** [comment]
Si la stiamo sostituendo

**Comment by umbros** [comment]
sostituita
