### ISSUE TITLE
Miglioramento su grafico "Incremento giornaliero degli attualmente positivi"

### ISSUE THREAD

**Issue by informagico** [pcm-dpc/COVID-19#99]
**Tipo di richiesta**: relativo alla pagina grafica

## Riassunto

Inserire nel grafico "Incremento giornaliero degli attualmente positivi" anche l'andamento dei tamponi, essendo i due dati **strettamente** collegati.

## Interesse pubblico

<img width="774" alt="Schermata 2020-03-10 alle 21 00 01" src="https://user-images.githubusercontent.com/38808827/76354103-233d4300-6312-11ea-9a7b-6e09a335f164.png">

Come si puó vedere, ad ogni flessione del numero di tamponi si ha una successiva flessione (tenendo presente i tempi tra la rilevazione ed il risultato effettivo) del numero di nuovi positivi (esempio palese tra il 09/03 ed il 10/03 dove sembra esserci perfino un'inversione del trend).
Inserire quel dato darebbe una visione piú oggettiva.

**Comment by umbros** [comment]
Ciao @informagico , il numero dei tamponi effettuati non rappresenta il singolo soggetto ma 1 soggetto può aver fatto n tamponi quindi non è correlabile.
