### ISSUE TITLE
dal 2 dicembre i casi provenienti da sospetto e da screening erano rappresentati con "0", dal 6 dicembre come "null".

### ISSUE THREAD

**Issue by alexodus** [pcm-dpc/COVID-19#990]
Perché questo cambiamento di valore (da 0 a null)? Dove è documentato questo cambio di valore?

**Comment by LucaZeta** [comment]
> Perché questo cambiamento di valore (da 0 a null)?

Personalmente lo trovo corretto: valorizzare null un indicatore del quale non vengono forniti valori.
Così come è stato per i valori, sempre di quegli indicatori, prima del 25 Giugno.

Pittosto andrebbero posti a null anche i valori relativi alla giornata del 3 Dicembre 2020.

**Comment by alexodus** [comment]
> > Perché questo cambiamento di valore (da 0 a null)?
> 
> Personalmente lo trovo corretto: valorizzare null un indicatore del quale non vengono forniti valori.
> Così come è stato per i valori, sempre di quegli indicatori, prima del 25 Giugno.

Concordo, ma pareva che all'inizio si fosse scelto di valorizzarli con "0" e poi si è cambiato approccio.

**Comment by umbros** [comment]
Ciao @alexodus ti ringrazio anche per il post precedente ma era offtopic riguardo la natura di questo repository. Se un dato non viene più erogato è più corretto impostarlo a null che a 0. Ecco il perchè di tale scelta, era stato portato a 0 quando ancora gli script non erano aggiornati e non alimentavano i nuovi dati, con gli script aggiornati (da mercoledì) sono messi a null.
