### ISSUE TITLE
Ancora problema mancanza dati tamponi

### ISSUE THREAD

**Issue by magaspari** [pcm-dpc/COVID-19#991]
Tipo di issue:

- [x] Dati mancanti o errati 
- [ ] Errore nella documentazione 
- [ ] Errore or mancanza nella dashboard 
- [ ] Problemi di visualizzazione nella dashboard 

- Regione:
- Provincia: 

## Riassunto

**Attesa:**

**Attuale:**

**Comment by magaspari** [comment]
Leggo sul commento dei nuovi dati, riguardo alla regione toscana: "positivi diagnosticati solo con test antigenico rapido: in questo momento non è procedura adottata da Regione Toscana, pertanto il valore è pari a zero".
Questo mi sconforta.
Fino alla scorsa settimana venivano almeno riportati tra le note i dati sui tamponi antigenici del Veneto e della Toscana, fino a prima dello screening quelli di Bolzano. Mi sembra leggendo il commento sopra citato che si sta tornando indietro. Ora e' sparito tutto, nulla nemmeno nei commenti, per cui se i ricercatori vogliono analizzare questi dati li devono cercare a mano e/o chiedere direttamente alle regioni, che magari li trasmettono già ma poi non vengono riportati.  
Chi e' il responsabile di quello che viene pubblicato in questo sito?
E' chiaro o no che questi dati sono un riferimento a livello nazionale e che vengono utilizzati dai ricercatori nelle Università e nei Centri di Ricerca oltre che dai giornalisti?
Se non si riesce a fornire il dato completo standardizzato che include gli antigenici positivi + le eventuali politiche per conferma della diagnosi regione per regione, il solo numero degli antigenici effettuati (che fino a poco tempo fa' per alcune regioni era presente se pur nei commenti) permette comunque di migliorare di molto la precisione  (risolvendo in parte il grosso errore sul dato Tamponi che lo rende al momento  inutilizzabile).
Vorrei per favore una conferma, si sta effettivamente lavorando per risolvere questo problema? 
Prof. Mauro Gaspari
Università di Bologna

**Comment by umbros** [comment]
Buongiorno Professore, il Ministero della Salute decide quali sono i dati da raccogliere anche in base alla stabilità degli stessi. Il Dipartimento raccoglie i dati, come avvenuto per gli ingressi in T.I., e li rilascia disponibili qui. L'analisi dei dati, le integrazioni e le modifiche al software di caricamento degli stessi sono attività costanti e su ogni cosa che verrà rilasciata a breve (da lunedì un report di data quality giornaliero) è riportato nel changelog.
