### ISSUE TITLE
Chiarimento: esiste il dato positivi da test antigenico?

### ISSUE THREAD

**Issue by vi-enne** [pcm-dpc/COVID-19#995]
**Tipo di richiesta**:  richiesta di informazione | richiesta di dati | suggerimento di miglioramento (documentazione, label, _ecc_) | relativo alla pagina grafica

## Riassunto

Tra le [note del 2020-12-13](https://github.com/pcm-dpc/COVID-19/blob/master/dati-regioni/dpc-covid19-ita-regioni-20201213.csv) si leggono:

Piemonte: _"Il numero dei tamponi antigenici positivi è sovrastimato in quanto una quota di casi (fino al 40%) potrebbe essere comunque confermata entro i successivi 10 giorni. Il numero di tamponi antigenici complessivamente effettuati è un di cui del totale riportato quotidianamente."_

Toscana: _"Positivi diagnosticati solo con test antigenico rapido: in questo momento non è procedura adottatata da Regione Toscana, pertanto il valore è pari a zero"_

Mi pare di capire che il Ministero della Salute chieda alle Regioni/PA di identificare quanti positivi sono stati trovati a seguito di test antigenici e quanti test antigenici siano stati effettuati.

E' corretto?
Se si, Sarebbe possibile riportare queste informazioni nelle tabelle riepilogative?

Grazie

## Interesse pubblico

Piu' dati piu' chiarezza :)

**Comment by magaspari** [comment]
Dalla dichiarazione del Piemonte, sembra anche che gli antigenici siano inclusi con gli altri.  
Oltre al N. degli antigenici e quelli tra essi positivi sarebbe opportuno aggiungere un flag per indicare se la positività degli antigenici viene confermata o meno con Molecolare, regione per regione, giorno per giorno.
Un documento del ministero della saluta del 23 Ottobre prevedeva infatti l'utilizzo dei soli antigenici a fini diagnostici, successivamente pero' sono arrivate circolari che ne raccomandavano la conferma con molecolare. 
Per cui non e' detto che gli antigenici positivi sono stati sempre confermati con i Molecolari.
Altri interventi sul tema: #991, #917.
Andrebbero ricostruite le serie storiche da ottobre per rendere i dati affidabili, un lavoraccio......ma piano piano si può fare! vedi ad esempio #917.
Purtroppo, sono quasi due mesi che i dati delle regioni sulle percentuali dei tamponi positivi non sono confrontabili.

**Comment by vi-enne** [comment]
Grazie della sua risposta.
Per il Piemonte sappiamo con ragionevole certezza dai [dati dell'assessore Marnati](https://www.facebook.com/matteomarnatilegaassessore/photos/a.151422008598661/948594638881390) che i tamponi effettuati comunicati al Ministero della Salute/Protezione Civile comprendono anche i test rapidi o antigenici.

Quel che mi interesserebbe avere e' la conferma che le voci "numero di tamponi antigenici effettuati" e "positivi diagnosticati solo con test antigenico rapido" siano effettivamente raccolte dal monitoraggio Ministero della Salute/Protezione Civile: dalle due note segnalate ieri pare infatti che questo sia il caso.

In caso venisse confermato, mi chiedo se fosse possibile inserire questi dati nelle tabelle riepilogative.

**Comment by magaspari** [comment]
Grazie per le informazioni sul Piemonte, che pero' nella tabella e' riportato tutto come molecolare.

Sarebbe sicuramente utilissimo avere a disposizione i dati nella forma che suggerisci, se questi dati ci sono!

**Comment by vi-enne** [comment]
Si figuri.
Discorso analogo vale per le Marche: tra i tamponi comunicati vi sono anche gli antigenici, come si può vedere ad esempio qui
https://www.regione.marche.it/News-ed-Eventi/Post/70263/Coronavirus-Marche-aggiornamento-dati-dal-Servizio-Sanit%C3%A0-situazione-al-14-12-2020-ore-9-00

**Comment by magaspari** [comment]
Riguardando il documento del 23 Ottobre, emerge chiaro che e' possibile una politica mista in cui alcuni antigenici vengono confermati da molecolare ed altri no.
Riflettendo su questo dato, forse la miglior rappresentazione (intesa come più compatta ed attuabile) per contare gli antigenici e eliminare i duplicati (non dalla tabella ma dalle stime sulle percentuali) e' la seguente: A) "N. antigenici", B)  "antigenici positivi" e C) "positivi diagnosticati solo con test antigenico rapido". 
Infatti la differenza tra B e C si potrebbe eliminare nelle stime dal numero di tamponi antigenici giornalieri, in quanto ad essi corrisponderà sicuramente un test molecolare lo stesso giorno o i giorni successivi, e i relativi positivi saranno caricati solo in quel momento.  Il tag che ipotizzavo prima non e' cosi essenziale e può essere eliminato o lasciato alle note, in quanto deducibile anche fronte di un C sempre a 0.
Il bias dovuto agli accumuli di molecolari, con picchi in alcune giornate particolari, si può eliminare considerando la media su un periodo, io uso i giorni di incubazione.

**Comment by vi-enne** [comment]
Dalle note nella [tabella del 12/18/2020](https://github.com/pcm-dpc/COVID-19/blob/master/schede-riepilogative/regioni/dpc-covid19-ita-scheda-regioni-20201218.pdf) sembra che per il Piemonte siano stati sottratti i test rapidi dal totale tamponi, che adesso dovrebbe indicare solo i molecolari.

![image](https://user-images.githubusercontent.com/44818674/102639260-c5524d00-4126-11eb-9fde-6625ddc8cf75.png)

**Comment by magaspari** [comment]
Si ma purtroppo la serie precedente non e' stata aggiornata, nella data 2020-12-16 risultano 1801939, la successiva data il 17 scendono a 1586358.  C'è un salto indietro e la serie complessiva del Piemonte purtroppo non si può utilizzare.
Se l'intenzione e' lasciare nella colonna solo i molecolari, sarebbe possibile sistemarla tutta per cortesia?

**Comment by vi-enne** [comment]
A seguito della [nota odierna della regione Friuli Venezia Giulia](https://github.com/pcm-dpc/COVID-19/blob/master/dati-regioni/dpc-covid19-ita-regioni-20201230.csv) rinnovo la mia domanda: esiste il campo **positivi al tampone antigenico**? Sarebbe possibile aggiungerlo alle tabelle riepilogative?

Taggo @umbros 

Grazie.


_"A seguito della periodica verifica dei casi segnalati, 182 casi già positivi al tampone antigenico sono risultati poi positivi al tampone molecolare e pertanto, in data odierna, vengono sottratti dal totale dei positivi al tampone antigenico ed aggiunti all'incremento odierno dei positivi da tampone molecolare"_

**Comment by vi-enne** [comment]
Altra [nota su PA Bolzano il 2021-01-03](https://github.com/pcm-dpc/COVID-19/blob/master/dati-regioni/dpc-covid19-ita-regioni-20210103.csv)

_"Nota del Ministero della Salute: i casi positivi da antigenico sono stati aggiornati dalla PA Bolzano poiché veniva inserito soltanto l'incremento quotidiano e non il dato cumulativo"_

**Comment by magaspari** [comment]
Da alcuni giorni la Provincia di Bolzano ha iniziato a trasmettere questo dato nei suoi Bollettini:
http://www.provincia.bz.it/news/it/news.asp?news_action=4&news_article_id=651460

E' sentito che c'è una proposta delle regioni per riorganizzare il dato, forse si vedrà a breve.
Qualcuno ha informazioni sul dato cumulativo dei Tamponi Antigenici del Veneto?

**Comment by vi-enne** [comment]
#1037 risponde alla domanda, quindi chiudo l'issue.

Grazie!
