### ISSUE TITLE
Formato dati non rispettato in master/dati-json/dpc-covid19-ita-andamento-nazionale-latest.json del 15/12/2020

### ISSUE THREAD

**Issue by ebigogno** [pcm-dpc/COVID-19#996]
Tipo di issue:

- [x] Dati mancanti o errati in `/COVID-19/master/dati-json/dpc-covid19-ita-andamento-nazionale-latest.json`
- [ ] Errore nella documentazione 
- [ ] Errore or mancanza nella dashboard 
- [ ] Problemi di visualizzazione nella dashboard 

- Regione: ---
- Provincia: ---

## Riassunto

Il 15/12/2020 i valori per i campi `casi_da_sospetto_diagnostico` e `casi_da_screening` sono stringhe vuote quando da documentazione il valore dovrebbe essere di tipo numerico

**Attesa:**
null
(perché valori non più popolati)

**Attuale:** 
""
(stringa vuota)

**Comment by LucaZeta** [comment]
I casi indicati non vengono più ripotati dal 3 Dicembre.
La variazione è ufficiale e riportata nel [changelog ](https://github.com/pcm-dpc/COVID-19/blob/master/CHANGELOG.md)dello stesso giorno.

**Comment by LucaZeta** [comment]
Il file dpc-covid19-ita-andamento-nazionale.json è popolato correttamente, il che vuol dire la derivazione "latest" viene definita manualmente la qual cosa è un insulto a procedure e informatica in generale.

Disponibile a fornire script php per la derivazione "latest" automatica dal file nazionale o viceversa a partire dal nazionale del giorno precedente.

**Comment by umbros** [comment]
I valori non sono più caricati dal DPC.
