### ISSUE TITLE
Tamponi totali 16/12 > tamponi totali 17/12

### ISSUE THREAD

**Issue by Achab94** [pcm-dpc/COVID-19#997]
Faccio riferimento a https://github.com/pcm-dpc/COVID-19/blob/master/dati-andamento-nazionale/dpc-covid19-ita-andamento-nazionale.csv . A distanza di 6 mesi ancora non siamo riusciti ad evitare di accumulare errori di questo tipo..... No comment.

**Comment by umbros** [comment]
#998
