### ISSUE TITLE
Ingressi terapia intensiva Campania errato 18/12

### ISSUE THREAD

**Issue by stefano0293849** [pcm-dpc/COVID-19#999]
Tipo di issue:

- [X] Dati mancanti o errati 
- [ ] Errore nella documentazione 
- [ ] Errore or mancanza nella dashboard 
- [ ] Problemi di visualizzazione nella dashboard 

- Regione: Campania
- Provincia: 

## Riassunto
I totali ricoverati in terapia intensiva in Campania risulta essere in data [18/12/20](https://github.com/pcm-dpc/COVID-19/blob/master/schede-riepilogative/regioni/dpc-covid19-ita-scheda-regioni-20201218.pdf) di 120 unità, con ingressi del giorno pari a 0, in data [17/12/20](https://github.com/pcm-dpc/COVID-19/blob/master/schede-riepilogative/regioni/dpc-covid19-ita-scheda-regioni-20201217.pdf) è invece indicato 119 unità.

**Attesa:**
Un numero di ingressi in terapia intensiva >=1 per la regione Campania.

**Attuale:** 
Un numero di ingressi in terapia intensiva pari a 0, vorrei inoltre far notare che tale dato risulta essere nullo  da almeno il 3/12, si ha una stima di quando tale dato verrà fornito? Grazie.

**Comment by vi-enne** [comment]
Suggerimento: si potrebbe usare il valore NULL o NA per la Campania fino a quando non sara' possibile per tale regione riportare il vero numero di ingressi in TI.

**Comment by tamamma** [comment]
C'è un problema anche con i casi testati di Basilicata e Piemonte per lo stesso giorno 18.12 ho aperto topic ma ho sbagliato la data nel titolo, speriamo correggano

**Comment by stefano0293849** [comment]
chiudo essendo i dati di ingresso in  T.I. tornati alla normalità.
